import type { CourseContent } from "../types";

const content: CourseContent = {
  slug: "automatiser-avec-ia",
  chapters: [
    {
      number: 1,
      title: "Introduction à l'Automatisation IA",
      description: "Comprendre ce qu'est l'automatisation IA et pourquoi elle transforme le travail en 2026.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Qu'est-ce que l'Automatisation IA ?" },
        { type: "paragraph", content: "L'automatisation IA combiné l'intelligence artificielle avec des outils d'automatisation pour exécuter des tâches complexes sans intervention humaine. En 2026, ce n'est plus un luxe — c'est un avantage competitif indispensable pour tout professionnel et toute entreprise." },
        { type: "paragraph", content: "Contrairement à l'automatisation classique (règles IF/THEN simples), l'automatisation IA peut comprendre du langage naturel, analyser des images, prendre des décisions contextuelles et s'adapter aux situations imprevues." },
        { type: "callout", content: "Selon McKinsey, 60% des métiers contiennent au moins 30% de tâches automatisables avec l'IA en 2026. Les professionnels qui maitrisent l'automatisation IA gagnent en moyenne 10 heures par semaine." },
        { type: "video", videoId: { fr: "gtvDkxYxW8g", en: "JtdUgJGI_Oo" },
      videoDurationMinutes: 20, label: "Introduction à l'automatisation IA" },
        { type: "heading", content: "Les 3 Niveaux d'Automatisation" },
        { type: "subheading", content: "Niveau 1 : Automatisation Simple" },
        { type: "paragraph", content: "Des règles basiques : quand un email arrive, le classer automatiquement. Quand un formulaire est soumis, envoyer une notification. C'est le point de depart, accessible à tous sans code." },
        { type: "subheading", content: "Niveau 2 : Automatisation Intelligente" },
        { type: "paragraph", content: "L'IA analyse le contenu : elle lit un email, comprend l'intention, rédigé une réponse adaptee, et l'envoie. Elle peut trier des CV, résumer des documents, ou générer des rapports." },
        { type: "subheading", content: "Niveau 3 : Agents Autonomes" },
        { type: "paragraph", content: "Des systèmes IA complets qui planifient, executent et s'adaptent. Un agent peut gérer votre veille technologique, votre comptabilite, ou votre marketing de contenu de manière quasi autonome." },
        { type: "key-point", content: "L'automatisation IA ne remplace pas l'humain — elle amplifie ses capacités. L'objectif est de déléguer les tâches répétitives pour se concentrer sur la stratégie et la créativité." },
        { type: "diagram", label: "Les 3 Niveaux d'Automatisation IA", flow: "vertical", nodes: [
          { label: "Niveau 1 — Simple", sub: "Règles IF/THEN, triggers basiques", color: "blue" },
          { label: "Niveau 2 — Intelligent", sub: "IA analyse, comprend et agit", color: "purple" },
          { label: "Niveau 3 — Autonome", sub: "Agents IA planifient et s'adaptent", color: "emerald" },
        ]},
        { type: "tip", content: "Commencez par automatiser une seule tâche répétitive que vous faites chaque jour. Le gain de temps vous motivera à aller plus loin." },
        { type: "summary", items: [
          "L'automatisation IA combiné intelligence artificielle et outils d'automatisation",
          "3 niveaux : simple (règles), intelligent (IA contextuelle), autonome (agents)",
          "60% des métiers contiennent 30%+ de tâches automatisables",
          "L'objectif est d'amplifier les capacités humaines, pas de remplacer",
          "Commencez petit, puis montez en complexité progressivement",
        ]},
      ],
      quiz: [
        {
          question: "Quelle est la différence principale entre l'automatisation classique et l'automatisation IA ?",
          options: ["L'automatisation IA est plus chère", "L'automatisation IA peut comprendre le contexte et s'adapter", "L'automatisation classique est plus rapide", "Il n'y a pas de différence"],
          correctIndex: 1,
          explanation: "L'automatisation IA peut comprendre du langage naturel, analyser du contenu et prendre des décisions contextuelles, contrairement à l'automatisation classique basée sur des règles fixes.",
        },
        {
          question: "Combien d'heures par semaine les professionnels gagnent-ils en moyenne grâce à l'automatisation IA ?",
          options: ["2 heures", "5 heures", "10 heures", "20 heures"],
          correctIndex: 2,
          explanation: "Selon les études, les professionnels qui maitrisent l'automatisation IA gagnent en moyenne 10 heures par semaine sur leurs tâches répétitives.",
        },
        {
          question: "A quel niveau d'automatisation correspondent les agents IA autonomes ?",
          options: ["Niveau 1", "Niveau 2", "Niveau 3", "Niveau 4"],
          correctIndex: 2,
          explanation: "Les agents IA autonomes correspondent au Niveau 3 — ils planifient, executent et s'adaptent de manière quasi autonome.",
        },
        {
          question: "Quel est le meilleur conseil pour débuter en automatisation IA ?",
          options: ["Automatiser tout d'un coup", "Commencer par une seule tâche répétitive", "Acheter tous les outils premium", "Apprendre a programmer d'abord"],
          correctIndex: 1,
          explanation: "Le meilleur conseil est de commencer par automatiser une seule tâche répétitive quotidienne. Le gain de temps visible motive à aller plus loin.",
        },
      ],
    },
    {
      number: 2,
      title: "Les Outils d'Automatisation en 2026",
      description: "Panorama complet des plateformes d'automatisation : Make, Zapier, n8n et les alternatives.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Le Paysage des Outils d'Automatisation en 2026" },
        { type: "paragraph", content: "En 2026, l'écosystème d'automatisation est riche et mature. Trois plateformes dominent le marche : Make (ex-Integromat), Zapier et n8n. Chacune a ses forces, et le choix dépend de vos besoins spécifiques." },
        { type: "paragraph", content: "Au-dela de ces trois leaders, des outils spécialisés comme Activepieces, Pipedream, Tray.io et Microsoft Power Automate completent l'écosystème. L'intégration native de l'IA dans ces plateformes est désormais la norme." },
        { type: "heading", content: "Comparatif des 3 Leaders" },
        { type: "subheading", content: "Make (ex-Integromat)" },
        { type: "paragraph", content: "Make se distingue par son interface visuelle puissante avec des scénarios complexes. Idéal pour les automatisations multi-étapes avec logique conditionnelle. Prix competitif, excellent pour les PME et freelances." },
        { type: "subheading", content: "Zapier" },
        { type: "paragraph", content: "Zapier est le leader historique avec le plus grand nombre d'intégrations (7000+). Interface simple et intuitive. Idéal pour les débutants et les automatisations simples a moyennes. Les Zap IA permettent désormais de créer des workflows en langage naturel." },
        { type: "subheading", content: "n8n" },
        { type: "paragraph", content: "n8n est l'alternative open source auto-hebergeable. Contrôle total sur vos données, pas de limites d'exécution, et une communauté active. Idéal pour les développeurs et les entreprises soucieuses de la souverainete des données." },
        { type: "video", videoId: { fr: "GBLKHPxokWw", en: "Fy1UCBcgF2o" },
      videoDurationMinutes: 19, label: "Comparatif Make vs Zapier vs n8n en 2026" },
        { type: "diagram", label: "Comparatif des Plateformes d'Automatisation", flow: "horizontal", nodes: [
          { label: "Make", sub: "Visuel, complexe, prix competitif", color: "purple" },
          { label: "Zapier", sub: "7000+ apps, simple, IA native", color: "amber" },
          { label: "n8n", sub: "Open source, auto-hébergé, illimite", color: "blue" },
        ]},
        { type: "key-point", content: "Il n'y a pas de \"meilleur\" outil universel. Choisissez Make pour la complexité visuelle, Zapier pour la simplicité et le nombre d'intégrations, n8n pour le contrôle total et le self-hosting." },
        { type: "prompt-example", prompt: "Compare Make, Zapier et n8n pour automatiser le traitement de 500 emails par jour avec classification IA et réponse automatique. Donne-moi un tableau avec prix, facilité, et limites.", result: "Un tableau comparatif détaillé avec les plans tarifaires, les limites d'opérations, les fonctionnalités IA natives et une recommandation basée sur le volume." },
        { type: "summary", items: [
          "Make : interface visuelle puissante, scénarios complexes, prix competitif",
          "Zapier : 7000+ intégrations, simple, idéal pour débuter",
          "n8n : open source, auto-hebergeable, pas de limites",
          "L'IA est désormais intégrée nativement dans les 3 plateformes",
          "Le choix dépend de vos besoins : complexité, budget, souverainete des données",
        ]},
      ],
      quiz: [
        {
          question: "Quelle plateforme offre le plus grand nombre d'intégrations ?",
          options: ["Make", "n8n", "Zapier", "Power Automate"],
          correctIndex: 2,
          explanation: "Zapier est le leader avec plus de 7000 intégrations disponibles, ce qui en fait la plateforme la plus connectée du marche.",
        },
        {
          question: "Quelle plateforme est open source et auto-hebergeable ?",
          options: ["Make", "Zapier", "n8n", "Tray.io"],
          correctIndex: 2,
          explanation: "n8n est la seule plateforme open source parmi les leaders, permettant l'auto-hébergement et le contrôle total sur les données.",
        },
        {
          question: "Pour quelle raison principale choisirait-on Make plutôt que Zapier ?",
          options: ["Le prix est gratuit", "L'interface visuelle pour les scénarios complexes", "Il a plus d'intégrations", "Il est open source"],
          correctIndex: 1,
          explanation: "Make se distingue par son interface visuelle puissante qui excelle dans la création de scénarios multi-étapes avec logique conditionnelle complexe.",
        },
        {
          question: "Qu'est-ce que les Zap IA de Zapier permettent ?",
          options: ["Générer des images", "Créer des workflows en langage naturel", "Heberger des sites web", "Faire du trading"],
          correctIndex: 1,
          explanation: "Les Zap IA permettent de créer des workflows d'automatisation simplement en decrivant ce que vous voulez faire en langage naturel.",
        },
      ],
    },
    {
      number: 3,
      title: "Make (ex-Integromat) et l'IA",
      description: "Maîtriser Make pour créer des automatisations visuelles puissantes avec l'IA.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Make : L'Automatisation Visuelle Puissante" },
        { type: "paragraph", content: "Make (anciennement Integromat) est une plateforme d'automatisation no-code qui se distingue par son approche visuelle. Vous construisez des \"scénarios\" en connectant des modules sur un canvas, comme un diagramme de flux. C'est la plateforme préférée des automatiseurs avances." },
        { type: "paragraph", content: "En 2026, Make intégré nativement l'IA avec des modules dédiées pour OpenAI, Anthropic (Claude), Google (Gemini), et des modèles open source. Vous pouvez inserer de l'intelligence artificielle a n'importe quel point de votre workflow." },
        { type: "heading", content: "Les Concepts Clés de Make" },
        { type: "subheading", content: "Scenarios et Modules" },
        { type: "paragraph", content: "Un scénario est un workflow automatisé. Il se compose de modules connectés entre eux. Chaque module effectue une action : lire un email, appeler une API, transformer des données, envoyer un message. Les modules sont relies par des fleches qui definissent le flux de données." },
        { type: "subheading", content: "Filtres et Routeurs" },
        { type: "paragraph", content: "Les filtres permettent de conditionner l'exécution (si l'email contient \"urgent\", alors...). Les routeurs permettent de diviser un flux en plusieurs branches parallèles. C'est ce qui rend Make si puissant pour les scénarios complexes." },
        { type: "video", videoId: { fr: "oeli5xkFZJo", en: "JhM7PWCv2EY" },
      videoDurationMinutes: 14, label: "Créer votre premier scénario Make avec l'IA" },
        { type: "heading", content: "Integrer l'IA dans Make" },
        { type: "paragraph", content: "Le module OpenAI/Claude dans Make permet d'ajouter de l'intelligence à vos workflows : classifier des emails, résumer des documents, générer des réponses, analyser des sentiments, extraire des données structurees de texte libre." },
        { type: "prompt-example", prompt: "Dans Make, créé un scénario qui : 1) Surveille un dossier Google Drive, 2) Quand un PDF arrive, extrait le texte, 3) Envoie le texte a Claude pour un résumé, 4) Enregistre le résumé dans Notion.", result: "Un scénario Make en 4 modules : Google Drive Watch → PDF Extract Text → Claude API (résumé) → Notion Create Page, avec les paramètres détaillés pour chaque module." },
        { type: "tip", content: "Utilisez le module 'HTTP - Make a request' pour connecter Make a n'importe quelle API, même celles qui n'ont pas de module natif. C'est votre couteau suisse." },
        { type: "diagram", label: "Anatomie d'un Scénario Make avec IA", flow: "horizontal", nodes: [
          { label: "Trigger", sub: "Email, webhook, planning", color: "blue" },
          { label: "Traitement", sub: "Filtres, routeurs, transformations", color: "purple" },
          { label: "Module IA", sub: "Claude, GPT, Gemini", color: "emerald" },
          { label: "Action", sub: "Envoyer, sauvegarder, notifier", color: "amber" },
        ]},
        { type: "summary", items: [
          "Make utilise des scénarios visuels avec des modules connectés",
          "Filtres et routeurs permettent des logiques complexes",
          "Modules IA natifs pour OpenAI, Claude et Gemini",
          "Le module HTTP permet de connecter n'importe quelle API",
          "Idéal pour les automatisations multi-étapes visuelles",
        ]},
      ],
      quiz: [
        {
          question: "Comment s'appellent les workflows dans Make ?",
          options: ["Zaps", "Flows", "Scenarios", "Pipelines"],
          correctIndex: 2,
          explanation: "Dans Make, les workflows automatises s'appellent des scénarios. Ils sont composes de modules connectés visuellement sur un canvas.",
        },
        {
          question: "A quoi servent les routeurs dans Make ?",
          options: ["A connecter Internet", "A diviser un flux en plusieurs branches parallèles", "A accélérer le traitement", "A sauvegarder les données"],
          correctIndex: 1,
          explanation: "Les routeurs permettent de diviser un flux en plusieurs branches parallèles, chacune avec ses propres conditions et actions.",
        },
        {
          question: "Quel module Make permet de connecter n'importe quelle API ?",
          options: ["Le module Router", "Le module Filter", "Le module HTTP", "Le module AI"],
          correctIndex: 2,
          explanation: "Le module 'HTTP - Make a request' permet de connecter Make a n'importe quelle API, même celles qui n'ont pas de module natif.",
        },
        {
          question: "Quel était l'ancien nom de Make ?",
          options: ["Automate.io", "Integromat", "IFTTT", "Workato"],
          correctIndex: 1,
          explanation: "Make s'appelait auparavant Integromat. Le rebranding a eu lieu en 2022 pour refléter l'évolution de la plateforme.",
        },
      ],
    },
    {
      number: 4,
      title: "Zapier + IA : Automatiser sans Code",
      description: "Utiliser Zapier et ses fonctionnalités IA pour créer des automatisations puissantes sans programmation.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Zapier : Le Leader de l'Automatisation No-Code" },
        { type: "paragraph", content: "Zapier est la plateforme d'automatisation la plus populaire au monde avec plus de 7000 applications connectées. Sa force : la simplicité. En quelques clics, vous connectez deux applications et les faites travailler ensemble automatiquement." },
        { type: "paragraph", content: "En 2026, Zapier a pris un virage majeur vers l'IA avec les Zap IA, les actions IA natives, et Zapier Central — un assistant qui crée des automatisations à partir de descriptions en langage naturel." },
        { type: "heading", content: "Les Bases de Zapier" },
        { type: "paragraph", content: "Un Zap est compose d'un trigger (déclencheur) et d'une ou plusieurs actions. Exemple : quand je recois un email avec une piece jointe (trigger), sauvegarder le fichier dans Google Drive (action 1) et me notifier sur Slack (action 2)." },
        { type: "subheading", content: "Zapier Central et l'IA" },
        { type: "paragraph", content: "Zapier Central est un assistant IA qui vous permet de decrire ce que vous voulez automatiser en français. Il crée le Zap pour vous, suggère des améliorations, et peut même debugger vos automatisations existantes." },
        { type: "video", videoId: { fr: "R2jdPmrirgE", en: "_ZvnD73m40o" },
      videoDurationMinutes: 42, label: "Zapier + IA : tutoriel complet 2026" },
        { type: "callout", content: "Les actions IA de Zapier incluent : résumer du texte, classifier du contenu, extraire des données, générer des réponses, et traduire — tout cela sans configurer d'API externe." },
        { type: "heading", content: "Cas d'Usage Concrets" },
        { type: "paragraph", content: "Support client : un email arrive, l'IA le classifie (question, plainte, demande de devis), rédigé une réponse adaptee, et la soumet pour validation. Lead management : un formulaire est soumis, l'IA enrichit le lead, le score, et l'assigne au bon commercial." },
        { type: "prompt-example", prompt: "Cree un Zap qui surveille mon formulaire Typeform, utilise l'IA pour scorer le lead de 1 à 10, et envoie une alerte Slack si le score est > 7.", result: "Un Zap en 4 étapes : Typeform New Entry → Zapier AI (scoring avec critères) → Filter (score > 7) → Slack Send Message, avec les prompts IA optimises." },
        { type: "diagram", label: "Structure d'un Zap avec IA", flow: "horizontal", nodes: [
          { label: "Trigger", sub: "Email, formulaire, webhook", color: "amber" },
          { label: "Action IA", sub: "Classifier, résumer, générer", color: "purple" },
          { label: "Filtre", sub: "Conditions et logique", color: "blue" },
          { label: "Action finale", sub: "Notifier, sauvegarder, envoyer", color: "emerald" },
        ]},
        { type: "summary", items: [
          "Zapier connecté 7000+ applications sans code",
          "Un Zap = un trigger + une ou plusieurs actions",
          "Zapier Central créé des Zaps à partir de descriptions en langage naturel",
          "Actions IA natives : classification, résumé, génération de texte",
          "Idéal pour le support client, le lead management et la productivité",
        ]},
      ],
      quiz: [
        {
          question: "Combien d'applications Zapier connecté-t-il en 2026 ?",
          options: ["500+", "2000+", "7000+", "15000+"],
          correctIndex: 2,
          explanation: "Zapier connecté plus de 7000 applications, ce qui en fait la plateforme avec le plus grand écosystème d'intégrations.",
        },
        {
          question: "Qu'est-ce que Zapier Central ?",
          options: ["Un serveur cloud", "Un assistant IA qui crée des Zaps en langage naturel", "Un plan tarifaire premium", "Un outil de monitoring"],
          correctIndex: 1,
          explanation: "Zapier Central est un assistant IA qui permet de decrire vos automatisations en langage naturel et les créé automatiquement pour vous.",
        },
        {
          question: "Qu'est-ce qu'un trigger dans Zapier ?",
          options: ["Une action finale", "Un déclencheur qui démarré le Zap", "Un filtre conditionnel", "Une intégration IA"],
          correctIndex: 1,
          explanation: "Un trigger (déclencheur) est l'événement qui démarré l'exécution du Zap, par exemple la réception d'un email ou la soumission d'un formulaire.",
        },
        {
          question: "Quelle action IA n'est PAS native dans Zapier ?",
          options: ["Résumer du texte", "Classifier du contenu", "Générer des images", "Extraire des données"],
          correctIndex: 2,
          explanation: "La génération d'images n'est pas une action IA native de Zapier. Les actions IA natives couvrent le texte : résumé, classification, extraction et génération de réponses.",
        },
      ],
    },
    {
      number: 5,
      title: "n8n : L'Alternative Open Source",
      description: "Découvrir n8n, la plateforme d'automatisation open source auto-hebergeable.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "n8n : L'Automatisation Libre et Puissante" },
        { type: "paragraph", content: "n8n (prononce 'n-eight-n') est une plateforme d'automatisation open source qui vous donne le contrôle total. Contrairement a Make et Zapier, vous pouvez l'héberger sur votre propre serveur, sans limites d'exécution et sans frais par opération." },
        { type: "paragraph", content: "En 2026, n8n s'est impose comme la référence pour les équipes techniques et les entreprises soucieuses de souverainete des données. Son écosystème IA est particulièrement riche avec des noeud dédiés pour les LLM, les agents et les RAG." },
        { type: "heading", content: "Installation et Configuration" },
        { type: "paragraph", content: "n8n s'installé en une commande Docker : docker run -d --name n8n -p 5678:5678 n8nio/n8n. Vous pouvez aussi l'installer via npm ou utiliser n8n Cloud si vous preferez une solution hébergée." },
        { type: "callout", content: "n8n est gratuit en auto-hébergement. La version Cloud démarré a 20 euros/mois avec des exécutions illimitees. C'est le meilleur rapport qualité-prix du marche pour les gros volumes." },
        { type: "video", videoId: { fr: "gtvDkxYxW8g", en: "JtdUgJGI_Oo" },
      videoDurationMinutes: 20, label: "Installer et configurer n8n en 10 minutes" },
        { type: "heading", content: "n8n et l'IA" },
        { type: "subheading", content: "Les Noeuds IA de n8n" },
        { type: "paragraph", content: "n8n propose des noeuds IA avances : AI Agent (agent autonome avec outils), AI Chain (enchainement de prompts), Vector Store (base de données vectorielle pour le RAG), et des connecteurs pour OpenAI, Claude, Gemini, Ollama et les modèles locaux." },
        { type: "subheading", content: "Agents IA dans n8n" },
        { type: "paragraph", content: "Le noeud AI Agent de n8n permet de créer de véritables agents autonomes qui peuvent utiliser des outils, interroger des bases de connaissances, exécuter du code, et prendre des décisions complexes — le tout dans une interface visuelle." },
        { type: "tip", content: "Si vous avez un serveur ou un NAS, installez n8n en Docker. Vous aurez des automatisations illimitees sans frais mensuels. C'est l'idéal pour les projets a gros volume." },
        { type: "diagram", label: "Écosystème IA de n8n", flow: "horizontal", nodes: [
          { label: "AI Agent", sub: "Agents autonomes avec outils", color: "purple" },
          { label: "AI Chain", sub: "Enchainement de prompts", color: "blue" },
          { label: "Vector Store", sub: "RAG et base de connaissances", color: "emerald" },
          { label: "LLM Nodes", sub: "OpenAI, Claude, Ollama", color: "amber" },
        ]},
        { type: "prompt-example", prompt: "Configure un workflow n8n avec un agent IA qui reçoit des questions par webhook, cherche dans une base de connaissances Notion, et répond par email.", result: "Un workflow n8n en 5 noeuds : Webhook → AI Agent (avec outil Notion Search + outil Email Send) → réponse formatee. Le noeud AI Agent gère la logique de recherche et de réponse automatiquement." },
        { type: "summary", items: [
          "n8n est open source, auto-hebergeable et sans limites d'exécution",
          "Installation simple via Docker en une seule commande",
          "Noeuds IA avances : Agent, Chain, Vector Store, LLM",
          "Support des modèles locaux via Ollama",
          "Idéal pour les équipes techniques et la souverainete des données",
        ]},
      ],
      quiz: [
        {
          question: "Quel est l'avantage principal de n8n par rapport à Make et Zapier ?",
          options: ["Il est plus beau", "Il est open source et auto-hebergeable", "Il a plus d'intégrations", "Il est plus rapide"],
          correctIndex: 1,
          explanation: "n8n est open source et peut être auto-hébergé, ce qui donne un contrôle total sur les données et élimine les limites d'exécution.",
        },
        {
          question: "Comment installer n8n le plus simplement ?",
          options: ["Télécharger un .exe", "Avec Docker en une commande", "Compiler depuis les sources", "Depuis l'App Store"],
          correctIndex: 1,
          explanation: "n8n s'installé le plus simplement via Docker avec une seule commande : docker run -d --name n8n -p 5678:5678 n8nio/n8n.",
        },
        {
          question: "Quel noeud n8n permet de créer des agents IA autonomes ?",
          options: ["AI Chain", "Vector Store", "AI Agent", "HTTP Request"],
          correctIndex: 2,
          explanation: "Le noeud AI Agent de n8n permet de créer des agents autonomes qui utilisent des outils, interrogent des bases de connaissances et prennent des décisions.",
        },
        {
          question: "n8n supporte-t-il les modèles IA locaux ?",
          options: ["Non, uniquement les API cloud", "Oui, via Ollama", "Seulement avec un plugin payant", "Uniquement les modèles OpenAI"],
          correctIndex: 1,
          explanation: "n8n supporte les modèles locaux via Ollama, ce qui permet d'utiliser l'IA sans envoyer de données a des services cloud.",
        },
      ],
    },
    {
      number: 6,
      title: "Connecter les APIs avec l'IA",
      description: "Comprendre et utiliser les APIs pour connecter l'IA à tous vos outils.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Les APIs : Le Langage Universel des Outils" },
        { type: "paragraph", content: "Une API (Application Programming Interface) est un pont qui permet à deux applications de communiquer. Quand vous demandez a Make d'envoyer un message Slack, il utilise l'API de Slack. Comprendre les APIs est la clé pour debloquer des automatisations illimitees." },
        { type: "paragraph", content: "En 2026, quasiment tous les outils proposent une API. Les APIs des modèles IA (OpenAI, Anthropic, Google) permettent d'intégrer l'intelligence artificielle directement dans vos workflows personnalisés." },
        { type: "heading", content: "Les Bases des APIs REST" },
        { type: "paragraph", content: "Les APIs REST utilisent des requêtes HTTP : GET (recuperer des données), POST (envoyer des données), PUT (modifier), DELETE (supprimer). Chaque requête contient une URL, des en-têtes (headers) et parfois un corps (body) avec les données." },
        { type: "subheading", content: "Authentification API" },
        { type: "paragraph", content: "La plupart des APIs nécessitent une clé (API key) pour s'authentifier. Cette clé identifié votre application et contrôle vos droits d'accès. Ne partagez jamais vos clés API et stockez-les dans des variables d'environnement." },
        { type: "key-point", content: "Les clés API sont comme des mots de passe. Une clé compromise peut entraîner des coûts importants (appels API factures) ou des fuites de données. Traitez-les avec le même niveau de sécurité." },
        { type: "video", videoId: { fr: "GBLKHPxokWw", en: "Fy1UCBcgF2o" },
      videoDurationMinutes: 19, label: "Comprendre les APIs en 10 minutes" },
        { type: "heading", content: "Webhooks : Des APIs en Temps Réel" },
        { type: "paragraph", content: "Un webhook est l'inverse d'une requête API classique : au lieu de demander des données, c'est l'application qui vous les envoie automatiquement quand un événement se produit. Idéal pour les automatisations en temps réel." },
        { type: "callout", content: "Les webhooks sont le mecanisme préféré pour les automatisations réactives. Au lieu de vérifier toutes les 5 minutes si un événement s'est produit (polling), le webhook vous notifié instantanément." },
        { type: "diagram", label: "API vs Webhook", flow: "horizontal", nodes: [
          { label: "API (Pull)", sub: "Vous demandez les données", color: "blue" },
          { label: "Webhook (Push)", sub: "Les données viennent a vous", color: "emerald" },
        ]},
        { type: "prompt-example", prompt: "Genere un script Python qui appelle l'API Claude pour résumer un article, puis envoie le résumé sur un canal Slack via webhook.", result: "Un script Python complet avec gestion d'erreurs, appel API Anthropic pour le résumé, et envoi du résultat via webhook Slack entrant, avec les variables d'environnement pour les clés." },
        { type: "summary", items: [
          "Les APIs permettent aux applications de communiquer entre elles",
          "Méthodes HTTP : GET, POST, PUT, DELETE",
          "L'authentification par clé API est indispensable",
          "Les webhooks envoient des données en temps réel (push vs pull)",
          "Combiner APIs + IA = automatisations illimitees",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce qu'une API ?",
          options: ["Un type de processeur", "Un pont de communication entre applications", "Un langage de programmation", "Un format de fichier"],
          correctIndex: 1,
          explanation: "Une API (Application Programming Interface) est un pont qui permet à deux applications de communiquer et d'echanger des données.",
        },
        {
          question: "Quelle méthode HTTP est utilisée pour envoyer des données ?",
          options: ["GET", "POST", "DELETE", "HEAD"],
          correctIndex: 1,
          explanation: "La méthode POST est utilisée pour envoyer des données a une API, par exemple soumettre un texte à l'API Claude pour obtenir un résumé.",
        },
        {
          question: "Quelle est la différence entre une API et un webhook ?",
          options: ["L'API est gratuite, le webhook est payant", "L'API demande les données, le webhook les reçoit automatiquement", "Il n'y a pas de différence", "Le webhook est plus lent"],
          correctIndex: 1,
          explanation: "Avec une API, vous demandez activement les données (pull). Avec un webhook, les données vous sont envoyées automatiquement quand un événement se produit (push).",
        },
        {
          question: "Pourquoi ne faut-il jamais partager ses clés API ?",
          options: ["Elles sont uniques et non remplacables", "Elles peuvent entraîner des coûts et des fuites de données", "Elles expirent immédiatement", "C'est illégal"],
          correctIndex: 1,
          explanation: "Une clé API compromise peut être utilisée pour effectuer des appels factures à votre compte ou acceder à vos données sensibles.",
        },
      ],
    },
    {
      number: 7,
      title: "Agents IA Autonomes",
      description: "Concevoir et déployer des agents IA qui travaillent de manière autonome.",
      estimatedMinutes: 10,
      sections: [
        { type: "heading", content: "Les Agents IA : Au-Dela de l'Automatisation" },
        { type: "paragraph", content: "Un agent IA autonome ne se contente pas d'exécuter une séquence predeterminee — il planifie, décide, agit et s'adapte. En 2026, les agents IA transforment radicalement les workflows : un agent peut gérer votre boîte mail, votre veille technologique ou votre support client de manière quasi autonome." },
        { type: "paragraph", content: "La différence fondamentale entre un workflow automatisé et un agent : le workflow suit un chemin predefini, l'agent choisit son propre chemin pour atteindre un objectif. Il peut utiliser des outils, faire des recherches, et modifier sa stratégie en fonction des résultats." },
        { type: "heading", content: "Architectures d'Agents" },
        { type: "subheading", content: "Agent Simple (ReAct)" },
        { type: "paragraph", content: "L'agent ReAct (Reasoning + Acting) alterne entre réflexion et action. Il reçoit un objectif, reflechit a la meilleure approche, exécute une action, observe le résultat, et ajuste. C'est l'architecture la plus courante et la plus fiable." },
        { type: "subheading", content: "Multi-Agents" },
        { type: "paragraph", content: "Plusieurs agents spécialisés collaborent : un agent de recherche, un agent rédacteur, un agent de validation. Chacun a son rôle et ses outils. Le système est plus robuste et plus performant qu'un agent unique pour les tâches complexes." },
        { type: "video", videoId: { fr: "oeli5xkFZJo", en: "JhM7PWCv2EY" },
      videoDurationMinutes: 14, label: "Construire un agent IA autonome" },
        { type: "key-point", content: "Le protocole MCP (Model Context Protocol) d'Anthropic standardisé la communication entre agents et outils. C'est devenu le standard de l'industrie pour connecter des agents IA a des sources de données et des API externes." },
        { type: "heading", content: "Outils pour Créer des Agents" },
        { type: "paragraph", content: "Claude Code et Cursor Agent pour le développement logiciel. CrewAI et AutoGen pour les systèmes multi-agents. n8n AI Agent pour les agents no-code. LangChain et LlamaIndex pour les agents personnalisés en Python." },
        { type: "diagram", label: "Architecture Multi-Agents", flow: "vertical", nodes: [
          { label: "Orchestrateur", sub: "Planifie et distribue les tâches", color: "purple" },
          { label: "Agent Recherche", sub: "Collecte d'informations", color: "blue" },
          { label: "Agent Rédaction", sub: "Production de contenu", color: "emerald" },
          { label: "Agent Validation", sub: "Vérification et qualité", color: "amber" },
        ]},
        { type: "diagram", label: "Boucle d'un Agent ReAct", flow: "cycle", nodes: [
          { label: "Reflexion", sub: "Analyse l'objectif et planifie", color: "purple" },
          { label: "Action", sub: "Execute avec un outil", color: "blue" },
          { label: "Observation", sub: "Evalue le résultat", color: "emerald" },
        ]},
        { type: "tip", content: "Commencez par un agent simple avec 2-3 outils. Un agent trop complexe au depart sera difficile à debugger. Ajoutez des outils et des capacités progressivement." },
        { type: "summary", items: [
          "Les agents IA planifient et s'adaptent, contrairement aux workflows fixes",
          "Architecture ReAct : réflexion → action → observation en boucle",
          "Les systèmes multi-agents sont plus robustes pour les tâches complexes",
          "MCP standardisé la communication agents-outils",
          "Outils : Claude Code, n8n AI Agent, CrewAI, LangChain",
        ]},
      ],
      quiz: [
        {
          question: "Quelle est la différence fondamentale entre un workflow automatisé et un agent IA ?",
          options: ["L'agent est plus rapide", "L'agent choisit son propre chemin pour atteindre un objectif", "L'agent est gratuit", "Il n'y a pas de différence"],
          correctIndex: 1,
          explanation: "Un workflow suit un chemin predefini. Un agent IA choisit son propre chemin, utilise des outils et adapte sa stratégie en fonction des résultats.",
        },
        {
          question: "Que signifie ReAct dans le contexte des agents IA ?",
          options: ["Real-time Action", "Reasoning + Acting", "Recursive Agent Technology", "Remote Activation"],
          correctIndex: 1,
          explanation: "ReAct (Reasoning + Acting) est une architecture ou l'agent alterne entre phases de réflexion, d'action et d'observation des résultats.",
        },
        {
          question: "Qu'est-ce que le protocole MCP ?",
          options: ["Un langage de programmation", "Un standard de communication entre agents et outils", "Un type de base de données", "Un format d'image"],
          correctIndex: 1,
          explanation: "MCP (Model Context Protocol) d'Anthropic standardisé la façon dont les agents interagissent avec les outils et les sources de données externes.",
        },
        {
          question: "Quel est le meilleur conseil pour créer un premier agent IA ?",
          options: ["Ajouter le maximum d'outils des le depart", "Commencer avec un agent simple de 2-3 outils", "Utiliser uniquement des modèles locaux", "Ne pas tester avant de déployer"],
          correctIndex: 1,
          explanation: "Commencer avec un agent simple de 2-3 outils permet de comprendre le comportement de l'agent et de le debugger facilement avant d'ajouter de la complexité.",
        },
      ],
    },
    {
      number: 8,
      title: "Automatiser les Emails et Communications",
      description: "Utiliser l'IA pour gérer automatiquement vos emails, messages et communications.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "L'IA au Service de vos Communications" },
        { type: "paragraph", content: "L'email reste le canal de communication professionnel numero un. En moyenne, un professionnel passe 2h30 par jour sur ses emails. L'automatisation IA peut réduire ce temps de 70% en triant, répondant et organisant automatiquement vos messages." },
        { type: "paragraph", content: "Au-dela des emails, l'IA peut automatiser vos communications sur Slack, Teams, WhatsApp Business, et les réseaux sociaux. L'objectif : une communication réactive sans y passer tout votre temps." },
        { type: "heading", content: "Automatiser le Tri des Emails" },
        { type: "paragraph", content: "L'IA peut classifier vos emails en catégories : urgent, informatif, spam, action requise, FYI. Elle peut aussi détecter le sentiment (positif, négatif, neutre) et identifier les emails nécessitant une réponse prioritaire." },
        { type: "subheading", content: "Réponses Automatiques Intelligentes" },
        { type: "paragraph", content: "Contrairement aux auto-repondeurs basiques, une réponse IA est contextuelle : elle lit l'email, comprend la demande, et génère une réponse adaptee dans le ton de votre communication habituelle." },
        { type: "video", videoId: { fr: "R2jdPmrirgE", en: "_ZvnD73m40o" },
      videoDurationMinutes: 42, label: "Automatiser ses emails avec l'IA" },
        { type: "callout", content: "Attention : ne delegez jamais complètement les emails sensibles à l'IA. Les réponses automatiques doivent être validées par un humain pour les sujets importants (contrats, reclamations, décisions stratégiques)." },
        { type: "prompt-example", prompt: "Cree un workflow qui lit mes emails Gmail, classifie chaque email (urgent/normal/spam) avec Claude, rédigé un brouillon de réponse pour les emails urgents, et m'envoie un résumé quotidien sur Slack.", result: "Un workflow en 5 étapes : Gmail Trigger → Claude API (classification + résumé) → Router (urgent/normal/spam) → Gmail Draft (réponses urgentes) → Slack Daily Digest (résumé a 8h)." },
        { type: "diagram", label: "Pipeline d'Automatisation Email", flow: "horizontal", nodes: [
          { label: "Réception", sub: "Nouveaux emails arrivent", color: "blue" },
          { label: "Classification IA", sub: "Urgent, normal, spam", color: "purple" },
          { label: "Génération réponse", sub: "Brouillon adapte au contexte", color: "emerald" },
          { label: "Notification", sub: "Résumé et alertes", color: "amber" },
        ]},
        { type: "key-point", content: "Le secret d'une bonne automatisation email : donnez à l'IA des exemples de vos réponses habituelles. Plus elle connaît votre style, plus les brouillons seront utilisables directement." },
        { type: "summary", items: [
          "Un professionnel passe 2h30/jour sur ses emails — l'IA réduit de 70%",
          "L'IA classifie, résumé et génère des réponses contextuelles",
          "Les emails sensibles doivent toujours être validés par un humain",
          "Fournir des exemples de votre style améliore la qualité des réponses",
          "Automatisable sur Gmail, Outlook, Slack, Teams et WhatsApp",
        ]},
      ],
      quiz: [
        {
          question: "Combien de temps un professionnel passe-t-il en moyenne sur ses emails ?",
          options: ["30 minutes/jour", "1 heure/jour", "2h30/jour", "4 heures/jour"],
          correctIndex: 2,
          explanation: "Un professionnel passe en moyenne 2h30 par jour a gérer ses emails, ce qui représente un potentiel d'automatisation énorme.",
        },
        {
          question: "Qu'est-ce qui différencié une réponse automatique IA d'un auto-repondeur classique ?",
          options: ["Elle est plus rapide", "Elle est contextuelle et adaptee au contenu de l'email", "Elle est gratuite", "Elle n'utilise pas Internet"],
          correctIndex: 1,
          explanation: "Une réponse IA lit et comprend le contenu de l'email, puis génère une réponse contextuelle adaptee, contrairement a un auto-repondeur qui envoie toujours le même message.",
        },
        {
          question: "Quels emails ne doivent jamais être délégués entièrement à l'IA ?",
          options: ["Les newsletters", "Les emails sensibles (contrats, reclamations)", "Les emails informatifs", "Les confirmations de rendez-vous"],
          correctIndex: 1,
          explanation: "Les emails sensibles comme les contrats, reclamations et décisions stratégiques doivent toujours être validés par un humain avant envoi.",
        },
        {
          question: "Comment améliorer la qualité des réponses IA pour vos emails ?",
          options: ["Utiliser un modèle plus cher", "Fournir des exemples de votre style de communication", "Envoyer plus d'emails", "Desactiver les filtres"],
          correctIndex: 1,
          explanation: "Fournir des exemples de vos réponses habituelles permet à l'IA de reproduire votre ton et votre style, rendant les brouillons directement utilisables.",
        },
      ],
    },
    {
      number: 9,
      title: "Automatiser le Marketing de Contenu",
      description: "Créer un pipeline de contenu automatisé avec l'IA : ideation, rédaction, publication.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Le Pipeline de Contenu Automatise" },
        { type: "paragraph", content: "Le marketing de contenu est l'un des domaines ou l'automatisation IA a le plus d'impact. De l'ideation a la publication en passant par la rédaction et l'optimisation SEO, chaque étape peut être partiellement ou totalement automatisée." },
        { type: "paragraph", content: "Un pipeline de contenu IA typique produit 10 à 20 fois plus de contenu qu'un processus manuel, tout en maintenant une qualité editoriale élevée grâce à la supervision humaine sur les points stratégiques." },
        { type: "heading", content: "Les Étapes du Pipeline" },
        { type: "subheading", content: "1. Veille et Ideation" },
        { type: "paragraph", content: "L'IA surveille vos concurrents, les tendances de votre secteur, et les questions de votre audience. Elle génère des idées d'articles, de posts sociaux et de vidéos basées sur les données réelles." },
        { type: "subheading", content: "2. Rédaction et Optimisation" },
        { type: "paragraph", content: "Claude ou GPT-5.4 redigent les premiers jets. L'IA optimise ensuite pour le SEO (mots-clés, structure, meta-descriptions). Un editeur humain revoit et validé le contenu final." },
        { type: "subheading", content: "3. Publication Multi-Plateforme" },
        { type: "paragraph", content: "Le contenu est automatiquement adapté à chaque plateforme (LinkedIn, Twitter/X, blog, newsletter) et publié selon un calendrier editorial predefini. Chaque format est optimisé pour la plateforme ciblé." },
        { type: "video", videoId: { fr: "gtvDkxYxW8g", en: "JtdUgJGI_Oo" },
      videoDurationMinutes: 20, label: "Pipeline de contenu IA : de l'idée a la publication" },
        { type: "diagram", label: "Pipeline de Contenu Automatise", flow: "horizontal", nodes: [
          { label: "Veille IA", sub: "Tendances, concurrents, audience", color: "blue" },
          { label: "Rédaction IA", sub: "Premiers jets + optimisation SEO", color: "purple" },
          { label: "Validation humaine", sub: "Revision et approbation", color: "amber" },
          { label: "Publication", sub: "Multi-plateforme automatique", color: "emerald" },
        ]},
        { type: "prompt-example", prompt: "Cree un workflow Make qui : 1) Scrape les tendances Twitter sur l'IA, 2) Genere 5 idées d'articles avec Claude, 3) Redige un article de 800 mots sur la meilleure idée, 4) Publié sur WordPress en brouillon.", result: "Un scénario Make avec : Twitter API Search → Claude (analyse tendances + ideation) → Claude (rédaction article 800 mots) → WordPress Create Post (draft), avec les prompts optimises pour chaque étape." },
        { type: "tip", content: "Ne publiez jamais du contenu IA sans relecture humaine. L'IA produit le volume, l'humain apporte la touche authentique et vérifie les faits. C'est le duo gagnant." },
        { type: "summary", items: [
          "Le pipeline IA produit 10-20x plus de contenu qu'un processus manuel",
          "4 étapes : veille, rédaction, validation humaine, publication",
          "L'IA optimise automatiquement pour le SEO",
          "Adaptation automatique du contenu à chaque plateforme",
          "La supervision humaine reste indispensable pour la qualité",
        ]},
      ],
      quiz: [
        {
          question: "Combien de fois plus de contenu un pipeline IA peut-il produire ?",
          options: ["2-3x", "5-7x", "10-20x", "50-100x"],
          correctIndex: 2,
          explanation: "Un pipeline de contenu IA typique produit 10 à 20 fois plus de contenu qu'un processus entièrement manuel, grâce à l'automatisation de chaque étape.",
        },
        {
          question: "Quelle étape du pipeline doit rester humaine ?",
          options: ["La veille", "La rédaction", "La validation et révision", "La publication"],
          correctIndex: 2,
          explanation: "La validation et révision humaine est indispensable pour vérifier les faits, ajuster le ton et s'assurer que le contenu reflète bien la marque.",
        },
        {
          question: "Que fait l'IA lors de l'étape d'ideation ?",
          options: ["Elle publié du contenu", "Elle surveille les tendances et génère des idées", "Elle traduit du contenu", "Elle supprime le contenu obsolète"],
          correctIndex: 1,
          explanation: "Lors de l'ideation, l'IA surveille les concurrents, les tendances du secteur et les questions de l'audience pour générer des idées de contenu pertinentes.",
        },
        {
          question: "Pourquoi adapter le contenu à chaque plateforme ?",
          options: ["Pour économiser de l'argent", "Parce que chaque plateforme a ses codes et formats optimaux", "Pour éviter le plagiat", "C'est optionnel"],
          correctIndex: 1,
          explanation: "Chaque plateforme a ses propres codes (longueur, format, ton, hashtags). Un post LinkedIn n'a pas le même format qu'un tweet ou un article de blog.",
        },
      ],
    },
    {
      number: 10,
      title: "Automatiser la Veille et la Recherche",
      description: "Construire un système de veille automatisé qui collecté, filtre et résumé l'information.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "La Veille Automatisee par l'IA" },
        { type: "paragraph", content: "La veille informationnelle est cruciale mais chronophage. Suivre les tendances, surveiller les concurrents, lire les actualités de son secteur — cela peut prendre des heures. L'IA peut automatiser 90% de ce processus et vous livrer uniquement les informations pertinentes." },
        { type: "paragraph", content: "Un système de veille IA collecté les données (RSS, Twitter, Google Alerts, newsletters), les filtre par pertinence, les résumé, et vous envoie un digest quotidien ou hebdomadaire directement sur Slack, Telegram ou par email." },
        { type: "heading", content: "Sources de Données" },
        { type: "paragraph", content: "Les sources typiques : flux RSS (blogs, médias), réseaux sociaux (Twitter/X, LinkedIn), newsletters, podcasts (transcriptions), brevets, publications académiques, et communiques de presse. Plus vous diversifiez vos sources, plus votre veille est complète." },
        { type: "video", videoId: { fr: "GBLKHPxokWw", en: "Fy1UCBcgF2o" },
      videoDurationMinutes: 19, label: "Construire un système de veille IA" },
        { type: "subheading", content: "Filtrage Intelligent" },
        { type: "paragraph", content: "L'IA ne se contente pas de mots-clés : elle comprend le contexte. Elle peut filtrer par pertinence, détecter les sujets émergents, et identifier les signaux faibles qui pourraient devenir des tendances majeures." },
        { type: "subheading", content: "Résumé et Synthèse" },
        { type: "paragraph", content: "Claude ou GPT-5.4 resumient chaque article en 2-3 phrases, extraient les points clés, et evaluent l'impact potentiel pour votre activité. Vous obtenez l'essentiel en 5 minutes au lieu de 2 heures de lecture." },
        { type: "callout", content: "Perplexity AI est un excellent point de depart pour la veille automatisée. Il combiné recherche web et résumé IA pour fournir des réponses sourcees et actualisées." },
        { type: "diagram", label: "Pipeline de Veille Automatisee", flow: "horizontal", nodes: [
          { label: "Collecte", sub: "RSS, Twitter, newsletters", color: "blue" },
          { label: "Filtrage IA", sub: "Pertinence et contexte", color: "purple" },
          { label: "Résumé IA", sub: "Synthèse et points clés", color: "emerald" },
          { label: "Livraison", sub: "Slack, Telegram, email", color: "amber" },
        ]},
        { type: "prompt-example", prompt: "Cree un système de veille IA qui surveille 10 sources sur l'intelligence artificielle, filtre par pertinence, et m'envoie un résumé quotidien sur Telegram a 8h.", result: "Un workflow n8n : CRON 8h → HTTP (10 flux RSS) → Claude API (filtrage + résumé) → Telegram Bot (message formate avec les 5 infos les plus pertinentes du jour)." },
        { type: "summary", items: [
          "La veille IA automatise 90% du processus de surveillance informationnelle",
          "Sources : RSS, Twitter, newsletters, podcasts, publications académiques",
          "L'IA filtre par contexte, pas seulement par mots-clés",
          "Résumé automatique : l'essentiel en 5 minutes au lieu de 2 heures",
          "Livraison personnalisée sur Slack, Telegram ou email",
        ]},
      ],
      quiz: [
        {
          question: "Quel pourcentage du processus de veille l'IA peut-elle automatiser ?",
          options: ["30%", "50%", "70%", "90%"],
          correctIndex: 3,
          explanation: "L'IA peut automatiser environ 90% du processus de veille : collecté, filtrage, résumé et livraison. L'humain se concentre sur l'analyse stratégique.",
        },
        {
          question: "Qu'est-ce qu'un signal faible en veille ?",
          options: ["Un bug dans le système", "Un sujet émergent qui pourrait devenir une tendance", "Une source peu fiable", "Un message non lu"],
          correctIndex: 1,
          explanation: "Un signal faible est un sujet émergent, peu visible, qui pourrait devenir une tendance majeure. L'IA est particulièrement douee pour les détecter.",
        },
        {
          question: "Quel avantage l'IA a-t-elle sur le filtrage par mots-clés ?",
          options: ["Elle est plus rapide", "Elle comprend le contexte et la pertinence", "Elle est gratuite", "Elle ne fait pas d'erreurs"],
          correctIndex: 1,
          explanation: "L'IA comprend le contexte des articles, pas seulement les mots-clés. Elle peut évaluer la pertinence réelle d'une information pour votre activité.",
        },
        {
          question: "Quel outil est recommandé comme point de depart pour la veille IA ?",
          options: ["Google Search", "Perplexity AI", "Wikipedia", "ChatGPT"],
          correctIndex: 1,
          explanation: "Perplexity AI combiné recherche web et résumé IA pour fournir des réponses sourcees et actualisées, ce qui en fait un excellent outil de veille.",
        },
      ],
    },
    {
      number: 11,
      title: "Automatiser la Comptabilite et les Factures",
      description: "Utiliser l'IA pour automatiser la gestion financiere : factures, notes de frais, rapprochement.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "L'IA dans la Gestion Financiere" },
        { type: "paragraph", content: "La comptabilite et la facturation sont des tâches répétitives par excellence. L'IA peut lire des factures (OCR), extraire les données, les classer, effectuer le rapprochement bancaire, et générer des rapports — le tout automatiquement." },
        { type: "paragraph", content: "En 2026, les outils de comptabilite IA ne se contentent plus de lire des chiffres. Ils comprennent le contexte : ils savent qu'une facture de 'AWS' est une charge informatique, que 'Uber' est un déplacement professionnel, et ils categorisentautomatiquement." },
        { type: "heading", content: "Cas d'Usage Concrets" },
        { type: "subheading", content: "Traitement Automatique des Factures" },
        { type: "paragraph", content: "Un email avec une facture en piece jointe arrive. L'IA extrait le PDF, lit les montants, la date, le fournisseur, le numero de facture. Elle enregistre tout dans votre logiciel comptable et classe le document." },
        { type: "subheading", content: "Notes de Frais" },
        { type: "paragraph", content: "Photographiez un ticket de caisse. L'IA lit le montant, la date, le commerce, identifie la catégorie de dépense, et créé automatiquement la note de frais dans votre système." },
        { type: "video", videoId: { fr: "oeli5xkFZJo", en: "JhM7PWCv2EY" },
      videoDurationMinutes: 14, label: "Automatiser sa comptabilite avec l'IA" },
        { type: "key-point", content: "L'automatisation comptable doit toujours être supervisee par un comptable. L'IA réduit le travail de saisie de 80%, mais la validation humaine reste obligatoire pour la conformite légale." },
        { type: "diagram", label: "Automatisation Comptable IA", flow: "horizontal", nodes: [
          { label: "Réception", sub: "Email, photo, upload", color: "blue" },
          { label: "Extraction IA", sub: "OCR + compréhension", color: "purple" },
          { label: "Categorisation", sub: "Classification automatique", color: "emerald" },
          { label: "Enregistrement", sub: "Logiciel comptable", color: "amber" },
        ]},
        { type: "tip", content: "Commencez par automatiser le traitement des factures recurrentes (hébergement, SaaS, abonnements). Ce sont les plus prévisibles et les plus faciles à automatiser." },
        { type: "prompt-example", prompt: "Cree un workflow qui reçoit des factures par email, extrait les données avec l'IA, et les enregistre dans un Google Sheet avec les colonnes : date, fournisseur, montant HT, TVA, montant TTC.", result: "Un workflow Make : Gmail (piece jointe PDF) → Google Vision OCR → Claude API (extraction structuree) → Google Sheets (ajout ligne avec date, fournisseur, HT, TVA, TTC)." },
        { type: "summary", items: [
          "L'IA lit, extrait et classe les factures automatiquement (OCR + compréhension)",
          "Categorisation contextuelle : l'IA comprend le type de dépense",
          "Réduction de 80% du travail de saisie comptable",
          "Notes de frais automatisees par photo",
          "La validation humaine reste obligatoire pour la conformite légale",
        ]},
      ],
      quiz: [
        {
          question: "Que signifie OCR dans le contexte des factures ?",
          options: ["Online Cloud Recognition", "Optical Character Recognition", "Optimized Content Reading", "Original Copy Repository"],
          correctIndex: 1,
          explanation: "OCR (Optical Character Recognition) est la technologie qui permet de lire du texte dans des images ou des PDF scannes, essentielle pour extraire les données des factures.",
        },
        {
          question: "De combien l'IA peut-elle réduire le travail de saisie comptable ?",
          options: ["20%", "50%", "80%", "100%"],
          correctIndex: 2,
          explanation: "L'IA peut réduire le travail de saisie comptable d'environ 80%. Les 20% restants concernent la validation humaine nécessaire pour la conformite légale.",
        },
        {
          question: "Pourquoi la validation humaine reste-t-elle nécessaire ?",
          options: ["L'IA est trop lente", "Pour la conformite légale", "L'IA est trop chère", "Ce n'est pas nécessaire"],
          correctIndex: 1,
          explanation: "La validation humaine par un comptable est obligatoire pour la conformite légale. L'IA automatise la saisie, mais la responsabilité légale reste humaine.",
        },
        {
          question: "Par quelles factures est-il recommandé de commencer l'automatisation ?",
          options: ["Les factures les plus anciennes", "Les factures internationales", "Les factures recurrentes (SaaS, abonnements)", "Les factures les plus grosses"],
          correctIndex: 2,
          explanation: "Les factures recurrentes (hébergement, SaaS, abonnements) sont les plus prévisibles et donc les plus faciles à automatiser en premier.",
        },
      ],
    },
    {
      number: 12,
      title: "Workflows Multi-Étapes Complexes",
      description: "Concevoir des automatisations avancées avec logique conditionnelle, boucles et gestion d'erreurs.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Au-Dela des Automatisations Simples" },
        { type: "paragraph", content: "Les workflows simples (trigger → action) sont un bon début, mais la vraie puissance de l'automatisation émerge avec les workflows multi-étapes : logique conditionnelle, boucles, traitement par lots, gestion d'erreurs, et orchestration de plusieurs services." },
        { type: "paragraph", content: "Un workflow complexe peut impliquer 10, 20 ou même 50 étapes connectées. La clé est de concevoir l'architecture avant de construire, comme un architecte dessine des plans avant de batir." },
        { type: "heading", content: "Patterns Avances" },
        { type: "subheading", content: "Logique Conditionnelle (If/Else)" },
        { type: "paragraph", content: "Les routeurs et filtres permettent de diriger le flux selon des conditions. Exemple : si le client est VIP, traitement prioritaire. Si le montant depasse 1000 euros, validation manuelle requise. Si l'email est en anglais, traduire avant de traiter." },
        { type: "subheading", content: "Boucles et Iterations" },
        { type: "paragraph", content: "Les iterateurs traitent des listes élément par élément. Exemple : pour chaque ligne d'un fichier CSV, appeler l'API, traiter la réponse, et enregistrer le résultat. Les aggregateurs recombinent les résultats a la fin." },
        { type: "subheading", content: "Gestion d'Erreurs" },
        { type: "paragraph", content: "Les workflows robustes gèrent les erreurs : retry automatique, fallback (plan B), notification en cas d'échec, et logging pour le debugging. Sans gestion d'erreurs, un workflow complexe est une bombe a retardement." },
        { type: "video", videoId: { fr: "R2jdPmrirgE", en: "_ZvnD73m40o" },
      videoDurationMinutes: 42, label: "Workflows multi-étapes : patterns avances" },
        { type: "key-point", content: "La règle d'or : tout workflow qui touche des données critiques (financieres, clients, légales) doit avoir une gestion d'erreurs complète avec notifications et fallback." },
        { type: "diagram", label: "Patterns de Workflows Avances", flow: "vertical", nodes: [
          { label: "Logique conditionnelle", sub: "If/Else, routeurs, filtres", color: "purple" },
          { label: "Boucles", sub: "Iterateurs + aggregateurs", color: "blue" },
          { label: "Gestion d'erreurs", sub: "Retry, fallback, notifications", color: "pink" },
          { label: "Orchestration", sub: "Coordination multi-services", color: "emerald" },
        ]},
        { type: "callout", content: "Documentez vos workflows complexes ! Ajoutez des notes sur chaque module pour expliquer son rôle. Dans 6 mois, vous serez content de pouvoir comprendre rapidement ce que fait chaque étape." },
        { type: "prompt-example", prompt: "Concois un workflow Make qui traité un fichier CSV de 500 contacts : enrichit chaque contact avec l'IA, classifie par score, et envoie des emails personnalisés aux scores > 7, avec gestion d'erreurs.", result: "Un scénario Make avec : CSV Upload → Iterator (par ligne) → Claude API (enrichissement + scoring) → Router (score > 7 / autres) → Gmail Send (email personnalisé) + Error Handler (retry 3x, puis Slack notification)." },
        { type: "summary", items: [
          "La puissance émerge avec les workflows multi-étapes complexes",
          "Patterns clés : conditions, boucles, gestion d'erreurs, orchestration",
          "Les iterateurs traitent les listes, les aggregateurs recombinent",
          "La gestion d'erreurs est obligatoire pour les données critiques",
          "Documentez toujours vos workflows pour la maintenance future",
        ]},
      ],
      quiz: [
        {
          question: "Quel pattern permet de traiter une liste élément par élément ?",
          options: ["Le routeur", "L'iterateur", "Le filtre", "L'aggregateur"],
          correctIndex: 1,
          explanation: "L'iterateur traité une liste élément par élément. L'aggregateur recombine ensuite les résultats en une seule sortie.",
        },
        {
          question: "Que se passe-t-il sans gestion d'erreurs dans un workflow complexe ?",
          options: ["Rien, ca fonctionne toujours", "Le workflow plante silencieusement sans notification", "Les performances augmentent", "Le workflow se corrige automatiquement"],
          correctIndex: 1,
          explanation: "Sans gestion d'erreurs, un workflow peut planter silencieusement, perdre des données ou produire des résultats incorrects sans que personne ne soit averti.",
        },
        {
          question: "Quelle est la première étape pour créer un workflow complexe ?",
          options: ["Commencer a connecter les modules", "Concevoir l'architecture avant de construire", "Acheter un plan premium", "Tester en production"],
          correctIndex: 1,
          explanation: "Comme un architecte dessine des plans avant de batir, il faut concevoir l'architecture du workflow (étapes, conditions, erreurs) avant de commencer la construction.",
        },
        {
          question: "Pourquoi documenter ses workflows ?",
          options: ["Pour impressionner les collègues", "Pour comprendre rapidement ce que fait chaque étape lors de la maintenance", "Pour obtenir un meilleur support client", "Ce n'est pas nécessaire"],
          correctIndex: 1,
          explanation: "La documentation permet de comprendre rapidement le rôle de chaque étape lors de la maintenance ou du debugging, même des mois après la création.",
        },
      ],
    },
    {
      number: 13,
      title: "Monitoring et Maintenance des Automatisations",
      description: "Surveiller, debugger et maintenir vos automatisations pour une fiabilité maximale.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Garder vos Automatisations en Bonne Santé" },
        { type: "paragraph", content: "Créer une automatisation n'est que la première étape. La maintenir fiable dans le temps est le vrai défi. Les APIs changent, les tokens expirent, les limites de rate sont atteintes, et les formats de données evoluent. Sans monitoring, vos automatisations finiront par casser." },
        { type: "paragraph", content: "Un bon système de monitoring détecte les problèmes avant qu'ils n'impactent votre activité. Il vous alerte en temps réel, fournit des logs détaillés pour le debugging, et vous donne une vue d'ensemble de la santé de vos workflows." },
        { type: "heading", content: "Les Metriques a Surveiller" },
        { type: "paragraph", content: "Taux de succès : pourcentage d'exécutions reussies (ciblé : >99%). Temps d'exécution : duree moyenne d'un workflow. Volume : nombre d'exécutions par heure/jour. Erreurs : types et fréquence des échecs. Couts : consommation API et credits." },
        { type: "video", videoId: { fr: "gtvDkxYxW8g", en: "JtdUgJGI_Oo" },
      videoDurationMinutes: 20, label: "Monitoring des automatisations : les bonnes pratiques" },
        { type: "subheading", content: "Alertes et Notifications" },
        { type: "paragraph", content: "Configurez des alertes pour : les échecs d'exécution, les temps de réponse anormaux, l'approche des limites de quota, et l'expiration des tokens d'authentification. Utilisez Slack, Telegram ou email pour les notifications." },
        { type: "tip", content: "Creez un dashboard de monitoring avec les métriques clés de vos automatisations. Un simple Google Sheet avec les stats quotidiennes suffit pour commencer." },
        { type: "diagram", label: "Cycle de Maintenance", flow: "cycle", nodes: [
          { label: "Monitoring", sub: "Surveillance continue", color: "blue" },
          { label: "Alerte", sub: "Détection des anomalies", color: "pink" },
          { label: "Diagnostic", sub: "Analyse des logs", color: "purple" },
          { label: "Correction", sub: "Fix et amélioration", color: "emerald" },
        ]},
        { type: "key-point", content: "La règle des 3R du debugging : Reproduire le problème, Rechercher la cause racine, Résoudre définitivement (pas de patch temporaire)." },
        { type: "summary", items: [
          "Le monitoring est aussi important que la création des automatisations",
          "Metriques clés : taux de succès, temps d'exécution, erreurs, coûts",
          "Configurez des alertes pour les échecs et les anomalies",
          "Les 3R du debugging : Reproduire, Rechercher, Résoudre",
          "Un dashboard simple suffit pour commencer le monitoring",
        ]},
      ],
      quiz: [
        {
          question: "Quel taux de succès minimum viser pour ses automatisations ?",
          options: ["80%", "90%", "95%", "99%"],
          correctIndex: 3,
          explanation: "Un taux de succès de plus de 99% est la ciblé pour des automatisations fiables en production. En dessous, l'impact sur l'activité devient significatif.",
        },
        {
          question: "Quelle est la cause la plus courante de panne d'automatisation ?",
          options: ["Bug dans le code", "Changement d'API ou expiration de token", "Trop d'utilisateurs", "Mise à jour du navigateur"],
          correctIndex: 1,
          explanation: "Les changements d'API (nouveaux formats, endpoints modifiés) et l'expiration des tokens d'authentification sont les causes les plus courantes de pannes.",
        },
        {
          question: "Que signifient les 3R du debugging ?",
          options: ["Read, Run, Repeat", "Reproduire, Rechercher, Résoudre", "Reset, Reboot, Restart", "Review, Refactor, Release"],
          correctIndex: 1,
          explanation: "Les 3R : Reproduire le problème, Rechercher la cause racine, et Résoudre définitivement sans patch temporaire.",
        },
        {
          question: "Pourquoi créer un dashboard de monitoring ?",
          options: ["Pour impressionner les investisseurs", "Pour avoir une vue d'ensemble de la santé des workflows", "Pour respecter la loi", "Ce n'est pas nécessaire"],
          correctIndex: 1,
          explanation: "Un dashboard de monitoring offre une vue d'ensemble des métriques clés et permet de détecter rapidement les anomalies avant qu'elles n'impactent l'activité.",
        },
      ],
    },
    {
      number: 14,
      title: "Sécurité et Bonnes Pratiques",
      description: "Protéger vos automatisations : sécurité des données, clés API, conformite RGPD.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "La Sécurité des Automatisations IA" },
        { type: "paragraph", content: "Les automatisations manipulent souvent des données sensibles : emails clients, informations financieres, données personnelles. Une faille de sécurité dans une automatisation peut avoir des consequences graves : fuite de données, accès non autorisé, ou non-conformite RGPD." },
        { type: "paragraph", content: "La sécurité n'est pas une option — c'est un pre-requis. Chaque automatisation qui touche des données sensibles doit être conçue avec la sécurité comme priorité numero un." },
        { type: "heading", content: "Gestion des Clés API" },
        { type: "paragraph", content: "Ne jamais hardcoder une clé API dans un workflow. Utilisez les variables d'environnement ou les coffres-forts de secrets intègres aux plateformes (Make Connections, Zapier Connected Accounts, n8n Credentials). Rotez vos clés régulièrement." },
        { type: "subheading", content: "Principe du Moindre Privilège" },
        { type: "paragraph", content: "Chaque connexion API doit avoir les permissions minimales nécessaires. Si votre automatisation lit des emails, ne lui donnez pas la permission de supprimer. Si elle lit un Google Sheet, ne lui donnez pas l'accès à tout Google Drive." },
        { type: "video", videoId: { fr: "GBLKHPxokWw", en: "Fy1UCBcgF2o" },
      videoDurationMinutes: 19, label: "Sécuriser ses automatisations IA" },
        { type: "heading", content: "Conformite RGPD" },
        { type: "paragraph", content: "Si vos automatisations traitent des données personnelles de citoyens européens, le RGPD s'appliqué. Cela implique : le consentement explicite, le droit à l'oubli, la minimisation des données, et la documentation du traitement." },
        { type: "callout", content: "Quand vous envoyez des données a un LLM (Claude, GPT), ces données transitent par des serveurs tiers. Verifiez les politiques de retention des données du fournisseur et anonymisez les données sensibles avant de les envoyer." },
        { type: "key-point", content: "La règle d'or de la sécurité des automatisations : ne faites jamais transiter de données personnelles non anonymisees par un LLM, sauf si le fournisseur garantit contractuellement la non-retention." },
        { type: "diagram", label: "Checklist Sécurité des Automatisations", flow: "vertical", nodes: [
          { label: "Clés API", sub: "Variables d'environnement, rotation", color: "blue" },
          { label: "Moindre privilège", sub: "Permissions minimales nécessaires", color: "purple" },
          { label: "Chiffrement", sub: "Données en transit et au repos", color: "emerald" },
          { label: "RGPD", sub: "Consentement, anonymisation, documentation", color: "pink" },
        ]},
        { type: "summary", items: [
          "La sécurité est un pre-requis, pas une option",
          "Ne jamais hardcoder les clés API — utiliser des variables d'environnement",
          "Principe du moindre privilège pour chaque connexion",
          "Anonymiser les données sensibles avant de les envoyer a un LLM",
          "Respecter le RGPD : consentement, droit à l'oubli, documentation",
        ]},
      ],
      quiz: [
        {
          question: "Ou stocker les clés API dans une automatisation ?",
          options: ["Dans le code du workflow", "Dans un fichier texte", "Dans les variables d'environnement ou un coffre-fort de secrets", "Dans un email"],
          correctIndex: 2,
          explanation: "Les clés API doivent être stockées dans des variables d'environnement ou des coffres-forts de secrets (Credentials), jamais en dur dans le code.",
        },
        {
          question: "Qu'est-ce que le principe du moindre privilège ?",
          options: ["Donner toutes les permissions pour éviter les bugs", "Donner uniquement les permissions minimales nécessaires", "Ne donner aucune permission", "Changer les permissions chaque jour"],
          correctIndex: 1,
          explanation: "Le principe du moindre privilège signifie donner à chaque connexion API uniquement les permissions dont elle a besoin, rien de plus.",
        },
        {
          question: "Que faire avant d'envoyer des données personnelles a un LLM ?",
          options: ["Les compresser", "Les anonymiser", "Les dupliquer", "Rien de special"],
          correctIndex: 1,
          explanation: "Les données personnelles doivent être anonymisees avant d'être envoyées a un LLM, sauf si le fournisseur garantit contractuellement la non-retention.",
        },
        {
          question: "Quel règlement européen encadre le traitement des données personnelles ?",
          options: ["AI Act", "RGPD", "Digital Services Act", "ePrivacy"],
          correctIndex: 1,
          explanation: "Le RGPD (Reglement Général sur la Protection des Données) encadre le traitement des données personnelles des citoyens européens, y compris dans les automatisations.",
        },
      ],
    },
    {
      number: 15,
      title: "Construire son Système d'Automatisation Complet",
      description: "Assembler toutes les pieces pour créer un écosystème d'automatisation personnalisé et scalable.",
      estimatedMinutes: 10,
      sections: [
        { type: "heading", content: "Votre Écosystème d'Automatisation" },
        { type: "paragraph", content: "Vous avez maintenant toutes les pieces du puzzle : les outils (Make, Zapier, n8n), les techniques (APIs, webhooks, agents), et les bonnes pratiques (sécurité, monitoring). Il est temps d'assembler le tout en un système cohérent adapté à vos besoins." },
        { type: "paragraph", content: "Un système d'automatisation complet n'est pas une collection de workflows isoles — c'est un écosystème ou les automatisations se completent et s'alimentent mutuellement." },
        { type: "heading", content: "Méthodologie de Construction" },
        { type: "subheading", content: "Étape 1 : Audit de vos Processus" },
        { type: "paragraph", content: "Listez toutes vos tâches recurrentes. Evaluez le temps passe, la fréquence, et la complexité de chacune. Identifiez les quick wins (fort impact, faible complexité) et priorisez-les." },
        { type: "subheading", content: "Étape 2 : Architecture" },
        { type: "paragraph", content: "Dessinez votre architecture : quels outils pour quelles tâches ? Comment les workflows communiquent-ils entre eux ? Ou sont stockées les données ? Quels sont les points de contrôle humains ?" },
        { type: "subheading", content: "Étape 3 : Implementation Progressive" },
        { type: "paragraph", content: "Construisez un workflow à la fois. Testez en conditions réelles. Ajustez. Puis passez au suivant. Ne tentez jamais d'automatiser tout en même temps — c'est la recette de l'échec." },
        { type: "video", videoId: { fr: "oeli5xkFZJo", en: "JhM7PWCv2EY" },
      videoDurationMinutes: 14, label: "Construire son système d'automatisation de A à Z" },
        { type: "heading", content: "Le Stack Recommandé" },
        { type: "paragraph", content: "Pour un freelance ou une PME : n8n (auto-hébergé) pour les workflows complexes + Zapier pour les intégrations rapides + Claude API pour l'intelligence. Pour une grande entreprise : Make ou Tray.io pour l'orchestration + n8n pour les workflows IA + monitoring avance avec Datadog ou Grafana." },
        { type: "diagram", label: "Architecture d'un Système d'Automatisation Complet", flow: "vertical", nodes: [
          { label: "Couche Intelligence", sub: "Claude API, GPT-5.4, modèles locaux", color: "purple" },
          { label: "Couche Orchestration", sub: "Make, Zapier, n8n", color: "blue" },
          { label: "Couche Données", sub: "Bases de données, stockage, cache", color: "emerald" },
          { label: "Couche Monitoring", sub: "Alertes, logs, dashboards", color: "amber" },
          { label: "Couche Sécurité", sub: "Secrets, permissions, RGPD", color: "pink" },
        ]},
        { type: "tip", content: "Calculez le ROI de chaque automatisation : temps gagne x coût horaire = économie. Si une automatisation vous fait gagner 1h/jour a 50 euros/h, c'est 1500 euros/mois d'économie." },
        { type: "prompt-example", prompt: "Cree un plan d'automatisation complet pour un freelance consultant. Liste les 10 automatisations prioritaires, les outils recommandés, et le ROI estime pour chaque.", result: "Un plan structure avec : 1) Emails (n8n, 5h/sem, 1000 euros/mois), 2) Facturation (Make, 3h/sem, 600 euros), 3) Veille (n8n, 2h/sem, 400 euros), etc. Total : 15h/sem recuperees, 3000 euros/mois de ROI." },
        { type: "callout", content: "Felicitations ! Vous avez termine le cours sur l'automatisation IA. Vous avez les connaissances pour transformer votre productivité. L'étape suivante : choisir votre première automatisation et la construire cette semaine." },
        { type: "summary", items: [
          "Un système d'automatisation est un écosystème, pas des workflows isoles",
          "Méthodologie : audit → architecture → implementation progressive",
          "Stack recommandé : n8n + Zapier + Claude API",
          "Calculez le ROI de chaque automatisation pour prioriser",
          "Commencez cette semaine — une seule automatisation suffit pour démarrer",
        ]},
      ],
      quiz: [
        {
          question: "Quelle est la première étape pour construire un système d'automatisation ?",
          options: ["Acheter tous les outils", "Auditer ses processus et identifier les quick wins", "Automatiser toutes les tâches en même temps", "Embaucher un développeur"],
          correctIndex: 1,
          explanation: "La première étape est d'auditer vos processus : lister les tâches recurrentes, évaluer le temps et la complexité, puis identifier les quick wins a prioriser.",
        },
        {
          question: "Pourquoi ne faut-il pas tout automatiser en même temps ?",
          options: ["C'est trop cher", "C'est la recette de l'échec — il faut construire progressivement", "Les outils ne le permettent pas", "C'est interdit par le RGPD"],
          correctIndex: 1,
          explanation: "Tenter d'automatiser tout en même temps mene à l'échec. L'approche progressive (un workflow à la fois, test, ajustement) est beaucoup plus fiable.",
        },
        {
          question: "Comment calculer le ROI d'une automatisation ?",
          options: ["Nombre de workflows x prix de l'outil", "Temps gagne x coût horaire = économie", "Nombre d'emails envoyés x prix par email", "Nombre d'erreurs évitées x coût par erreur"],
          correctIndex: 1,
          explanation: "Le ROI se calcule simplement : temps gagne par l'automatisation multiplie par votre coût horaire. 1h/jour a 50 euros/h = 1500 euros/mois.",
        },
        {
          question: "Quel stack est recommandé pour un freelance ?",
          options: ["Uniquement Make", "Uniquement Zapier", "n8n + Zapier + Claude API", "Power Automate + Azure"],
          correctIndex: 2,
          explanation: "Pour un freelance, le stack recommandé est n8n (auto-hébergé pour les workflows complexes) + Zapier (intégrations rapides) + Claude API (intelligence IA).",
        },
      ],
    },
  ],
};

export default content;
