import type { CourseContent } from "../types";

const content: CourseContent = {
  slug: "coder-avec-ia",
  chapters: [
    {
      number: 1,
      title: "Introduction au Coding avec l'IA",
      description: "Pourquoi l'IA change tout pour les developpeurs et comment en tirer parti.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Bienvenue dans l'Ere du Developpement Assiste par l'IA" },
        { type: "paragraph", content: "En 2026, coder sans IA c'est comme coder sans IDE : techniquement possible, mais personne ne le fait volontairement. Les outils de developpement assistes par l'IA ont transforme la facon dont on ecrit, teste, debogue et deploie du code. Que vous soyez debutant ou senior, l'IA amplifie votre productivite de 2x a 10x selon les taches." },
        { type: "paragraph", content: "Cette revolution ne remplace pas les developpeurs — elle les augmente. Les meilleurs devs de 2026 sont ceux qui maitrisent l'art de collaborer avec l'IA : savoir quand la laisser generer, quand la guider, et quand reprendre la main." },
        { type: "callout", content: "Selon une etude GitHub de 2025, les developpeurs utilisant Copilot completent leurs taches 55% plus vite et rapportent une satisfaction accrue au travail." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Introduction au developpement assiste par l'IA" },
        { type: "heading", content: "Le Paysage des Outils de Dev IA en 2026" },
        { type: "paragraph", content: "L'ecosysteme se divise en plusieurs categories : les completions en ligne (Copilot), les IDE IA natifs (Cursor), les agents de code conversationnels (Claude Code), et les generateurs d'apps completes (Bolt, v0). Chaque outil a ses forces et son cas d'usage ideal." },
        { type: "subheading", content: "Ce que Vous Allez Apprendre" },
        { type: "paragraph", content: "Ce cours couvre l'ensemble du workflow de developpement avec l'IA : de l'ecriture de code au debugging, du testing au deploiement, du frontend au backend. Vous sortirez avec un workflow complet et personnalise." },
        { type: "key-point", content: "L'IA ne remplace pas la comprehension du code. Elle accelere l'execution. Un dev qui comprend ce que l'IA genere sera toujours superieur a un dev qui copie-colle aveuglement." },
        { type: "diagram", label: "Les Categories d'Outils de Dev IA", flow: "horizontal", nodes: [
          { label: "Completion en ligne", sub: "Copilot, Codeium, Supermaven", color: "blue" },
          { label: "IDE IA natif", sub: "Cursor, Windsurf, Zed", color: "purple" },
          { label: "Agent conversationnel", sub: "Claude Code, Aider, Cline", color: "emerald" },
          { label: "Generateur d'apps", sub: "Bolt, v0, Lovable, Replit", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA augmente les developpeurs — elle ne les remplace pas",
          "Gain de productivite de 2x a 10x selon les taches",
          "4 categories d'outils : completion, IDE IA, agents, generateurs d'apps",
          "La comprehension du code reste essentielle",
          "Ce cours couvre le workflow complet du dev moderne avec l'IA",
        ]},
      ],
      quiz: [
        {
          question: "Quel gain de productivite moyen les developpeurs utilisant Copilot rapportent-ils ?",
          options: ["10%", "25%", "55%", "90%"],
          correctIndex: 2,
          explanation: "Selon l'etude GitHub de 2025, les developpeurs utilisant Copilot completent leurs taches 55% plus vite en moyenne.",
        },
        {
          question: "Quelle categorie d'outil est Cursor ?",
          options: ["Completion en ligne", "IDE IA natif", "Agent conversationnel", "Generateur d'apps"],
          correctIndex: 1,
          explanation: "Cursor est un IDE (environnement de developpement) avec l'IA integree nativement dans chaque aspect de l'experience.",
        },
        {
          question: "Quel est le role principal de l'IA dans le developpement ?",
          options: ["Remplacer les developpeurs", "Augmenter la productivite des developpeurs", "Ecrire du code parfait sans erreur", "Eliminer le besoin de comprendre le code"],
          correctIndex: 1,
          explanation: "L'IA augmente les developpeurs en accelerant l'execution, mais la comprehension du code et l'expertise restent essentielles.",
        },
        {
          question: "Bolt et v0 appartiennent a quelle categorie d'outils ?",
          options: ["Completion en ligne", "IDE IA natif", "Agent conversationnel", "Generateur d'apps completes"],
          correctIndex: 3,
          explanation: "Bolt et v0 sont des generateurs d'applications completes qui creent des apps fonctionnelles a partir de descriptions en langage naturel.",
        },
      ],
    },
    {
      number: 2,
      title: "GitHub Copilot : Guide Complet",
      description: "Maitriser GitHub Copilot pour accelerer votre workflow de code au quotidien.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "GitHub Copilot : Votre Copilote de Code" },
        { type: "paragraph", content: "GitHub Copilot est l'outil de completion de code IA le plus utilise au monde, avec plus de 1,8 million de developpeurs payants. Integre directement dans VS Code, JetBrains, Neovim et d'autres editeurs, il suggere du code en temps reel pendant que vous tapez." },
        { type: "paragraph", content: "En 2026, Copilot va bien au-dela de la simple completion : Copilot Chat permet des conversations contextuelles, Copilot Workspace planifie des taches completes, et Copilot Agent execute des modifications multi-fichiers de maniere autonome." },
        { type: "subheading", content: "Installation et Configuration" },
        { type: "paragraph", content: "Installez l'extension GitHub Copilot dans VS Code. Connectez votre compte GitHub avec un abonnement Copilot (Individual a 10$/mois, Business a 19$/mois). Activez les suggestions inline et le chat dans les parametres." },
        { type: "heading", content: "Techniques Avancees" },
        { type: "paragraph", content: "Ecrivez des commentaires descriptifs avant votre code — Copilot les utilise comme contexte. Ouvrez les fichiers pertinents dans des onglets adjacents pour enrichir le contexte. Utilisez des noms de variables et de fonctions explicites pour guider les suggestions." },
        { type: "tip", content: "Raccourci essentiel : Tab pour accepter, Esc pour rejeter, Alt+] pour voir la suggestion suivante, Ctrl+Enter pour voir toutes les suggestions dans un panneau." },
        { type: "prompt-example", prompt: "// Fonction qui valide un email avec regex, retourne true/false et un message d'erreur", result: "Copilot genere automatiquement la fonction complete avec la regex, les cas limites, et les messages d'erreur adaptes." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "GitHub Copilot : guide complet 2026" },
        { type: "diagram", label: "Fonctionnalites de GitHub Copilot", flow: "horizontal", nodes: [
          { label: "Completion inline", sub: "Suggestions en temps reel", color: "blue" },
          { label: "Copilot Chat", sub: "Conversations contextuelles", color: "purple" },
          { label: "Workspace", sub: "Planification de taches", color: "emerald" },
          { label: "Agent", sub: "Modifications multi-fichiers", color: "amber" },
        ]},
        { type: "summary", items: [
          "Copilot est l'outil de completion IA le plus adopte (1,8M+ devs payants)",
          "Va au-dela de la completion : Chat, Workspace, Agent",
          "Les commentaires descriptifs ameliorent les suggestions",
          "Ouvrir les fichiers pertinents enrichit le contexte",
          "Tab pour accepter, Esc pour rejeter, Alt+] pour naviguer",
        ]},
      ],
      quiz: [
        {
          question: "Combien de developpeurs payants utilisent GitHub Copilot ?",
          options: ["500 000", "1 million", "1,8 million+", "5 millions"],
          correctIndex: 2,
          explanation: "GitHub Copilot compte plus de 1,8 million de developpeurs payants, ce qui en fait l'outil de completion IA le plus adopte.",
        },
        {
          question: "Quel raccourci permet d'accepter une suggestion Copilot ?",
          options: ["Enter", "Tab", "Espace", "Ctrl+A"],
          correctIndex: 1,
          explanation: "La touche Tab accepte la suggestion courante de Copilot. Esc la rejette et Alt+] affiche la suggestion suivante.",
        },
        {
          question: "Comment ameliorer la qualite des suggestions Copilot ?",
          options: ["Fermer tous les autres fichiers", "Ecrire des commentaires descriptifs avant le code", "Utiliser des noms de variables courts", "Desactiver le chat"],
          correctIndex: 1,
          explanation: "Les commentaires descriptifs fournissent du contexte a Copilot, ce qui ameliore significativement la pertinence des suggestions generees.",
        },
        {
          question: "Qu'est-ce que Copilot Workspace ?",
          options: ["Un editeur de code", "Un outil de planification de taches", "Un service d'hebergement", "Un debugger"],
          correctIndex: 1,
          explanation: "Copilot Workspace permet de planifier des taches completes : il analyse le probleme, propose un plan, et genere les modifications necessaires.",
        },
      ],
    },
    {
      number: 3,
      title: "Cursor : L'IDE IA",
      description: "Decouvrir Cursor, l'editeur de code avec IA integree nativement.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Cursor : L'IDE Construit Autour de l'IA" },
        { type: "paragraph", content: "Cursor est un fork de VS Code qui integre l'IA dans chaque aspect de l'experience de developpement. Contrairement a Copilot qui est un plugin, Cursor est un IDE entier repense autour de l'IA : completion predictive, edition multi-lignes, chat contextuel, et agent autonome." },
        { type: "paragraph", content: "Cursor comprend votre codebase entier. Il indexe tous vos fichiers, comprend les relations entre les modules, et utilise ce contexte pour generer du code coherent avec votre architecture existante." },
        { type: "subheading", content: "Tab : La Completion Predictive" },
        { type: "paragraph", content: "Cursor Tab va bien au-dela de la completion classique. Il predit vos prochaines modifications en analysant votre pattern d'edition : renommage, refactoring, ajout de parametres. Il anticipe vos intentions et propose des edits multi-lignes contextuels." },
        { type: "subheading", content: "Cmd+K : L'Edition Inline" },
        { type: "paragraph", content: "Selectionnez du code, appuyez sur Cmd+K (ou Ctrl+K), et decrivez ce que vous voulez en langage naturel. Cursor edite le code en place : refactoring, ajout de fonctionnalite, correction de bug, conversion de format." },
        { type: "subheading", content: "Le Chat et l'Agent" },
        { type: "paragraph", content: "Le chat Cursor (Cmd+L) permet des conversations avec votre codebase. L'Agent mode va plus loin : il peut creer des fichiers, modifier plusieurs fichiers simultanement, executer des commandes terminal, et iterer jusqu'a ce que la tache soit complete." },
        { type: "callout", content: "Cursor propose des regles (.cursorrules) pour personnaliser le comportement de l'IA. Definissez votre stack, vos conventions de code, et vos preferences — l'IA les respectera dans toutes ses generations." },
        { type: "key-point", content: "La force de Cursor est l'indexation du codebase. Plus votre projet est gros, plus l'avantage de Cursor sur les outils generiques est important." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Cursor IDE : tutoriel complet" },
        { type: "diagram", label: "Les Fonctionnalites Cles de Cursor", flow: "vertical", nodes: [
          { label: "Tab — Completion predictive", sub: "Anticipe vos edits multi-lignes", color: "blue" },
          { label: "Cmd+K — Edition inline", sub: "Modification en langage naturel", color: "purple" },
          { label: "Cmd+L — Chat contextuel", sub: "Conversation avec votre codebase", color: "emerald" },
          { label: "Agent — Autonomie", sub: "Cree, modifie, execute automatiquement", color: "amber" },
        ]},
        { type: "summary", items: [
          "Cursor est un IDE entier repense autour de l'IA (fork de VS Code)",
          "Tab : completion predictive multi-lignes",
          "Cmd+K : edition inline en langage naturel",
          "Chat + Agent : conversations et modifications autonomes",
          "Les .cursorrules personnalisent le comportement de l'IA",
        ]},
      ],
      quiz: [
        {
          question: "Sur quel editeur Cursor est-il base ?",
          options: ["Vim", "VS Code", "Sublime Text", "IntelliJ"],
          correctIndex: 1,
          explanation: "Cursor est un fork de VS Code, ce qui signifie qu'il supporte toutes les extensions VS Code tout en ajoutant des fonctionnalites IA natives.",
        },
        {
          question: "Quel raccourci lance l'edition inline dans Cursor ?",
          options: ["Cmd+L", "Cmd+K", "Cmd+I", "Cmd+Enter"],
          correctIndex: 1,
          explanation: "Cmd+K (ou Ctrl+K sur Windows/Linux) lance l'edition inline : selectionnez du code et decrivez la modification souhaitee en langage naturel.",
        },
        {
          question: "Qu'est-ce qui differencie Cursor Tab d'une completion classique ?",
          options: ["Il est plus rapide", "Il predit des edits multi-lignes contextuels", "Il ne fonctionne qu'en Python", "Il necessite une connexion internet"],
          correctIndex: 1,
          explanation: "Cursor Tab anticipe vos intentions en analysant votre pattern d'edition et propose des modifications multi-lignes contextuelles, pas juste la ligne suivante.",
        },
        {
          question: "A quoi servent les fichiers .cursorrules ?",
          options: ["Configurer les raccourcis clavier", "Personnaliser le comportement de l'IA", "Definir les regles de linting", "Gerer les permissions Git"],
          correctIndex: 1,
          explanation: "Les .cursorrules permettent de definir votre stack, vos conventions et preferences pour que l'IA de Cursor genere du code coherent avec votre projet.",
        },
      ],
    },
    {
      number: 4,
      title: "Claude Code : Coder en Conversation",
      description: "Utiliser Claude Code comme agent de developpement conversationnel dans le terminal.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Claude Code : L'Agent Dev dans Votre Terminal" },
        { type: "paragraph", content: "Claude Code est un outil CLI developpe par Anthropic qui transforme votre terminal en un environnement de developpement conversationnel. Contrairement aux IDE IA, Claude Code fonctionne directement dans le terminal, lit et modifie vos fichiers, execute des commandes, et itere jusqu'a ce que la tache soit complete." },
        { type: "paragraph", content: "Propulse par Claude Opus 4.6 avec 1 million de tokens de contexte, Claude Code peut comprendre des codebases entiers, planifier des modifications complexes, et les executer de maniere autonome avec une precision remarquable." },
        { type: "subheading", content: "Installation et Premiers Pas" },
        { type: "paragraph", content: "Installez via npm : npm install -g @anthropic-ai/claude-code. Lancez-le dans votre projet avec la commande 'claude'. Il indexe automatiquement votre codebase et commence une session interactive." },
        { type: "heading", content: "Cas d'Usage Puissants" },
        { type: "paragraph", content: "Claude Code excelle dans les taches complexes multi-fichiers : refactoring a grande echelle, migration de frameworks, implementation de features completes, debugging de problemes subtils. Il peut lire des logs d'erreur, analyser le contexte, et proposer des corrections." },
        { type: "prompt-example", prompt: "Refactore le systeme d'authentification pour utiliser JWT au lieu des sessions. Mets a jour les routes, le middleware, et les tests.", result: "Claude Code analyse le code existant, planifie les modifications, edite les fichiers un par un, execute les tests, et corrige les erreurs jusqu'a ce que tout passe." },
        { type: "tip", content: "Utilisez un fichier CLAUDE.md a la racine de votre projet pour donner du contexte permanent a Claude Code : stack, conventions, commandes utiles, architecture." },
        { type: "key-point", content: "La force de Claude Code est sa capacite a maintenir une tache pendant des heures (jusqu'a 14,5h avec Opus 4.6), ce qui le rend ideal pour les refactorings massifs et les migrations." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Claude Code : presentation et demo" },
        { type: "diagram", label: "Workflow Claude Code", flow: "vertical", nodes: [
          { label: "Commande en langage naturel", sub: "Decrivez la tache a accomplir", color: "blue" },
          { label: "Analyse du codebase", sub: "Lecture et comprehension des fichiers", color: "purple" },
          { label: "Plan et execution", sub: "Modifications multi-fichiers", color: "emerald" },
          { label: "Verification", sub: "Tests, lint, validation", color: "amber" },
        ]},
        { type: "summary", items: [
          "Claude Code est un agent dev CLI propulse par Claude Opus 4.6",
          "1 million de tokens de contexte pour comprendre des codebases entiers",
          "Ideal pour les taches complexes multi-fichiers et les refactorings",
          "CLAUDE.md donne du contexte permanent au projet",
          "Jusqu'a 14,5h d'autonomie pour les taches longues",
        ]},
      ],
      quiz: [
        {
          question: "Quel modele propulse Claude Code ?",
          options: ["GPT-5.4", "Claude Sonnet 4.6", "Claude Opus 4.6", "Gemini 3.1"],
          correctIndex: 2,
          explanation: "Claude Code est propulse par Claude Opus 4.6 d'Anthropic, avec 1 million de tokens de contexte et un horizon de tache de 14,5 heures.",
        },
        {
          question: "Ou fonctionne Claude Code ?",
          options: ["Dans un navigateur web", "Dans VS Code uniquement", "Dans le terminal (CLI)", "Dans une app mobile"],
          correctIndex: 2,
          explanation: "Claude Code est un outil CLI (Command Line Interface) qui fonctionne directement dans votre terminal, lisant et modifiant vos fichiers locaux.",
        },
        {
          question: "A quoi sert le fichier CLAUDE.md ?",
          options: ["Documentation utilisateur", "Contexte permanent pour Claude Code", "Configuration du linter", "Changelog du projet"],
          correctIndex: 1,
          explanation: "Le fichier CLAUDE.md a la racine du projet fournit du contexte permanent a Claude Code : stack technique, conventions, commandes utiles, architecture.",
        },
        {
          question: "Pour quel type de tache Claude Code est-il particulierement adapte ?",
          options: ["Completion de lignes simples", "Refactoring multi-fichiers complexes", "Design d'interfaces", "Gestion de base de donnees"],
          correctIndex: 1,
          explanation: "Claude Code excelle dans les taches complexes multi-fichiers comme les refactorings massifs, les migrations de framework, et l'implementation de features completes.",
        },
      ],
    },
    {
      number: 5,
      title: "Bolt et v0 : Generer des Apps Completes",
      description: "Creer des applications fonctionnelles en quelques minutes avec Bolt et v0.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "La Generation d'Applications Completes" },
        { type: "paragraph", content: "Bolt (StackBlitz) et v0 (Vercel) representent une nouvelle categorie d'outils : les generateurs d'applications completes. Decrivez ce que vous voulez en langage naturel, et l'IA genere une application fonctionnelle avec frontend, backend, et base de donnees." },
        { type: "subheading", content: "v0 par Vercel" },
        { type: "paragraph", content: "v0 se specialise dans la generation de composants UI et de pages React/Next.js. Il produit du code propre avec shadcn/ui et Tailwind CSS. Ideal pour prototyper rapidement des interfaces, des landing pages, et des dashboards." },
        { type: "paragraph", content: "Decrivez votre interface et v0 genere le code complet. Vous pouvez iterer en conversation : 'Ajoute un mode sombre', 'Change la couleur primaire en bleu', 'Ajoute un tableau de donnees'. Chaque iteration est instantanee." },
        { type: "subheading", content: "Bolt par StackBlitz" },
        { type: "paragraph", content: "Bolt va plus loin en generant des applications full-stack completes dans un environnement WebContainer. Il cree le frontend, le backend, la base de donnees, l'authentification — le tout en quelques minutes. L'app tourne directement dans le navigateur." },
        { type: "callout", content: "Bolt et v0 sont parfaits pour le prototypage rapide et les MVPs. Pour des applications de production complexes, combinez-les avec Cursor ou Claude Code pour le peaufinage." },
        { type: "prompt-example", prompt: "Cree un dashboard de gestion de taches avec authentification, drag-and-drop Kanban, et mode sombre", result: "Bolt genere une app Next.js complete avec auth, base de donnees SQLite, board Kanban fonctionnel, et toggle dark mode — pret en 3 minutes." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Bolt et v0 : creer des apps avec l'IA" },
        { type: "diagram", label: "Bolt vs v0 : Comparatif", flow: "horizontal", nodes: [
          { label: "v0 (Vercel)", sub: "UI/composants React + Next.js", color: "blue" },
          { label: "Bolt (StackBlitz)", sub: "Apps full-stack completes", color: "purple" },
          { label: "Lovable", sub: "Apps avec design premium", color: "pink" },
          { label: "Replit Agent", sub: "Deploiement instantane", color: "emerald" },
        ]},
        { type: "summary", items: [
          "v0 excelle dans la generation de composants UI React/Next.js",
          "Bolt genere des apps full-stack completes en quelques minutes",
          "Ideal pour le prototypage rapide et les MVPs",
          "Iteration conversationnelle pour affiner le resultat",
          "Combinez avec Cursor/Claude Code pour le peaufinage production",
        ]},
      ],
      quiz: [
        {
          question: "Quelle entreprise developpe v0 ?",
          options: ["StackBlitz", "Vercel", "Anthropic", "GitHub"],
          correctIndex: 1,
          explanation: "v0 est developpe par Vercel, la societe derriere Next.js. Il se specialise dans la generation de composants UI React/Next.js.",
        },
        {
          question: "Que genere Bolt par rapport a v0 ?",
          options: ["Uniquement du CSS", "Des composants UI", "Des applications full-stack completes", "Uniquement du backend"],
          correctIndex: 2,
          explanation: "Bolt genere des applications full-stack completes : frontend, backend, base de donnees et authentification, le tout dans un environnement WebContainer.",
        },
        {
          question: "Pour quel usage Bolt et v0 sont-ils ideaux ?",
          options: ["Applications enterprise a grande echelle", "Prototypage rapide et MVPs", "Maintenance de code legacy", "Administration de serveurs"],
          correctIndex: 1,
          explanation: "Bolt et v0 sont parfaits pour le prototypage rapide et les MVPs. Pour des applications de production complexes, il faut les combiner avec d'autres outils.",
        },
        {
          question: "Quel framework UI v0 utilise-t-il par defaut ?",
          options: ["Bootstrap", "Material UI", "shadcn/ui + Tailwind CSS", "Chakra UI"],
          correctIndex: 2,
          explanation: "v0 genere du code avec shadcn/ui et Tailwind CSS, produisant des composants propres, accessibles et facilement personnalisables.",
        },
      ],
    },
    {
      number: 6,
      title: "Debugger avec l'IA",
      description: "Techniques pour trouver et corriger les bugs plus rapidement avec l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Le Debugging Assiste par l'IA" },
        { type: "paragraph", content: "Le debugging est l'une des taches ou l'IA brille le plus. Copier un message d'erreur dans ChatGPT ou Claude et obtenir une explication claire en quelques secondes — c'est devenu un reflexe pour la majorite des developpeurs. Mais l'IA va bien plus loin que la simple explication d'erreurs." },
        { type: "paragraph", content: "Les outils comme Cursor, Claude Code et Copilot Chat peuvent analyser le contexte complet de votre code, identifier la cause racine d'un bug, et proposer un correctif precis. Ils comprennent les stack traces, les logs d'erreur, et les relations entre fichiers." },
        { type: "heading", content: "Techniques de Debugging avec l'IA" },
        { type: "subheading", content: "1. Le Copier-Coller Contextuel" },
        { type: "paragraph", content: "Ne collez pas juste l'erreur — fournissez le contexte : le code concerne, ce que vous essayiez de faire, le comportement attendu vs observe. Plus le contexte est riche, plus la solution sera precise." },
        { type: "subheading", content: "2. L'Analyse de Stack Trace" },
        { type: "paragraph", content: "Collez la stack trace complete dans le chat IA. Les LLM sont excellents pour remonter la chaine d'appels, identifier la ligne problematique, et expliquer pourquoi l'erreur survient dans ce contexte precis." },
        { type: "prompt-example", prompt: "TypeError: Cannot read properties of undefined (reading 'map')\n  at UserList (UserList.tsx:15)\n  at renderWithHooks (react-dom.js:1234)\n\nVoici le code de UserList.tsx : [code]", result: "L'IA identifie que 'users' est undefined au premier rendu, recommande un optional chaining (users?.map) ou un etat initial vide, et explique le cycle de vie React." },
        { type: "tip", content: "Pour les bugs complexes, utilisez Claude Code avec son million de tokens de contexte. Il peut analyser des dizaines de fichiers simultanement pour trouver la cause racine." },
        { type: "key-point", content: "L'IA excelle en debugging parce qu'elle a \"vu\" des millions de bugs similaires dans ses donnees d'entrainement. Elle reconnait les patterns d'erreur instantanement." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Debugger 10x plus vite avec l'IA" },
        { type: "diagram", label: "Workflow de Debugging IA", flow: "vertical", nodes: [
          { label: "Erreur detectee", sub: "Message d'erreur ou comportement inattendu", color: "pink" },
          { label: "Contexte enrichi", sub: "Code + stack trace + comportement attendu", color: "blue" },
          { label: "Analyse IA", sub: "Identification de la cause racine", color: "purple" },
          { label: "Correction et verification", sub: "Correctif applique et teste", color: "emerald" },
        ]},
        { type: "summary", items: [
          "L'IA est exceptionnelle pour le debugging grace aux patterns reconnus",
          "Fournissez toujours du contexte riche, pas juste le message d'erreur",
          "Les stack traces sont tres bien analysees par les LLM",
          "Claude Code peut analyser des dizaines de fichiers pour trouver la cause",
          "Le debugging IA reduit le temps de resolution de 60-80%",
        ]},
      ],
      quiz: [
        {
          question: "Pourquoi l'IA est-elle efficace pour le debugging ?",
          options: ["Elle execute le code plus vite", "Elle a vu des millions de bugs similaires dans ses donnees", "Elle cree des tests automatiquement", "Elle elimine les bugs avant l'execution"],
          correctIndex: 1,
          explanation: "Les LLM ont ete entraines sur des millions de codes et de messages d'erreur. Ils reconnaissent les patterns de bugs instantanement.",
        },
        {
          question: "Que faut-il fournir a l'IA pour un debugging efficace ?",
          options: ["Juste le message d'erreur", "L'erreur + le code + le contexte + le comportement attendu", "Uniquement le nom du fichier", "Le code source complet du projet"],
          correctIndex: 1,
          explanation: "Plus le contexte est riche (erreur, code, contexte, comportement attendu vs observe), plus la solution proposee sera precise et pertinente.",
        },
        {
          question: "Quel outil est ideal pour debugger des problemes multi-fichiers ?",
          options: ["ChatGPT web", "Claude Code", "Un debugger classique", "Stack Overflow"],
          correctIndex: 1,
          explanation: "Claude Code avec son million de tokens de contexte peut analyser des dizaines de fichiers simultanement pour trouver la cause racine de bugs complexes.",
        },
        {
          question: "De combien le debugging IA reduit-il le temps de resolution ?",
          options: ["10-20%", "30-40%", "60-80%", "100%"],
          correctIndex: 2,
          explanation: "Le debugging assiste par l'IA reduit le temps de resolution de 60 a 80% en moyenne, en identifiant rapidement les causes et en proposant des correctifs.",
        },
      ],
    },
    {
      number: 7,
      title: "Code Review Automatise",
      description: "Utiliser l'IA pour des reviews de code plus rapides et plus completes.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "La Code Review Augmentee par l'IA" },
        { type: "paragraph", content: "La code review est essentielle pour la qualite du code, mais elle est chronophage. L'IA transforme ce processus en detectant automatiquement les bugs potentiels, les failles de securite, les problemes de performance, et les violations de conventions — avant meme que votre collegue ne regarde le code." },
        { type: "paragraph", content: "En 2026, la plupart des equipes combinent review humaine et review IA. L'IA gere les aspects mecaniques (style, conventions, bugs evidents) tandis que les humains se concentrent sur l'architecture, la logique metier et la lisibilite." },
        { type: "subheading", content: "Outils de Review IA" },
        { type: "paragraph", content: "GitHub Copilot Review commente directement vos pull requests. CodeRabbit analyse chaque changement et produit un rapport detaille. Cursor et Claude Code peuvent reviewer du code en conversation avec le contexte complet du projet." },
        { type: "heading", content: "Comment Faire une Bonne Review IA" },
        { type: "paragraph", content: "Demandez a l'IA de verifier des aspects specifiques : securite, performance, gestion d'erreurs, edge cases. Ne vous contentez pas d'un 'review ce code'. Plus votre demande est precise, plus la review sera utile." },
        { type: "prompt-example", prompt: "Review ce composant React pour : 1) fuites memoire potentielles 2) re-renders inutiles 3) accessibilite 4) gestion d'erreurs", result: "L'IA identifie un useEffect sans cleanup, un objet inline recreee a chaque render, un bouton sans aria-label, et une absence de error boundary." },
        { type: "callout", content: "La review IA ne remplace pas la review humaine. Elle la complement en attrapant les problemes techniques que les humains peuvent manquer par fatigue ou familiarite avec le code." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Code review automatisee avec l'IA" },
        { type: "diagram", label: "Review IA vs Review Humaine", flow: "horizontal", nodes: [
          { label: "Review IA", sub: "Bugs, securite, conventions, performance", color: "blue" },
          { label: "Review Humaine", sub: "Architecture, logique metier, lisibilite", color: "purple" },
          { label: "Resultat", sub: "Code de haute qualite", color: "emerald" },
        ]},
        { type: "summary", items: [
          "L'IA detecte bugs, failles de securite et problemes de performance",
          "Combinez review IA (aspects mecaniques) et humaine (logique metier)",
          "Outils : Copilot Review, CodeRabbit, Cursor, Claude Code",
          "Soyez specifique dans vos demandes de review",
          "La review IA complement la review humaine, elle ne la remplace pas",
        ]},
      ],
      quiz: [
        {
          question: "Quel aspect de la review l'IA gere-t-elle le mieux ?",
          options: ["La logique metier", "L'architecture globale", "Les bugs, securite et conventions", "L'experience utilisateur"],
          correctIndex: 2,
          explanation: "L'IA excelle dans la detection des aspects mecaniques : bugs potentiels, failles de securite, violations de conventions et problemes de performance.",
        },
        {
          question: "Quel outil commente directement les pull requests sur GitHub ?",
          options: ["Cursor", "Claude Code", "Copilot Review", "ChatGPT"],
          correctIndex: 2,
          explanation: "GitHub Copilot Review analyse et commente directement vos pull requests sur GitHub, integre dans le workflow de review existant.",
        },
        {
          question: "Comment obtenir une meilleure review IA ?",
          options: ["Demander juste 'review ce code'", "Specifier les aspects a verifier", "Envoyer le moins de code possible", "Utiliser plusieurs outils en meme temps"],
          correctIndex: 1,
          explanation: "Plus votre demande est precise (securite, performance, gestion d'erreurs, accessibilite), plus la review IA sera pertinente et actionnable.",
        },
        {
          question: "Pourquoi la review humaine reste-t-elle necessaire ?",
          options: ["L'IA fait trop d'erreurs", "L'IA ne comprend pas la logique metier et l'architecture", "L'IA est trop lente", "L'IA ne supporte pas tous les langages"],
          correctIndex: 1,
          explanation: "La review humaine est essentielle pour evaluer l'architecture, la logique metier, la lisibilite et les decisions de design que l'IA ne peut pas juger.",
        },
      ],
    },
    {
      number: 8,
      title: "Tests Automatises avec l'IA",
      description: "Generer des tests unitaires, d'integration et E2E avec l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "L'IA Revolutionne le Testing" },
        { type: "paragraph", content: "Ecrire des tests est souvent la partie la moins appreciee du developpement. L'IA change la donne en generant automatiquement des tests pertinents, couvrant les cas limites auxquels vous n'auriez pas pense. Le resultat : une meilleure couverture avec moins d'effort." },
        { type: "paragraph", content: "Les LLM sont particulierement efficaces pour generer des tests unitaires parce qu'ils comprennent l'intention du code et peuvent anticiper les edge cases. Ils connaissent les frameworks de test (Jest, Vitest, Pytest, JUnit) et generent du code idiomatique." },
        { type: "subheading", content: "Tests Unitaires" },
        { type: "paragraph", content: "Donnez votre fonction a l'IA et demandez-lui de generer des tests couvrant tous les cas : happy path, erreurs, edge cases, valeurs limites. L'IA peut produire 10 a 20 tests en quelques secondes la ou un dev en ecrirait 3 a 5." },
        { type: "subheading", content: "Tests E2E avec IA" },
        { type: "paragraph", content: "Pour les tests end-to-end, l'IA peut generer des scenarios Playwright ou Cypress a partir de descriptions en langage naturel. Decrivez le parcours utilisateur et l'IA genere le test complet avec les selecteurs, les assertions et les attentes." },
        { type: "prompt-example", prompt: "Genere des tests Vitest pour cette fonction de panier d'achat : ajout, suppression, calcul total, codes promo, limites de stock", result: "L'IA genere 15 tests couvrant : ajout simple, ajout multiple, suppression, total correct, code promo valide/invalide/expire, stock insuffisant, panier vide, quantite zero." },
        { type: "tip", content: "Utilisez l'approche TDD avec l'IA : demandez-lui de generer les tests AVANT d'ecrire le code. Puis demandez-lui d'implementer le code qui fait passer les tests." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Tests automatises avec l'IA" },
        { type: "diagram", label: "Types de Tests Generes par l'IA", flow: "horizontal", nodes: [
          { label: "Tests unitaires", sub: "Fonctions et methodes isolees", color: "blue" },
          { label: "Tests d'integration", sub: "Interactions entre modules", color: "purple" },
          { label: "Tests E2E", sub: "Parcours utilisateur complets", color: "emerald" },
        ]},
        { type: "summary", items: [
          "L'IA genere des tests pertinents couvrant les edge cases",
          "10 a 20 tests en secondes vs 3 a 5 manuellement",
          "Supporte Jest, Vitest, Pytest, Playwright, Cypress",
          "TDD avec l'IA : tests d'abord, implementation ensuite",
          "Toujours verifier et ajuster les tests generes",
        ]},
      ],
      quiz: [
        {
          question: "Pourquoi l'IA est-elle efficace pour generer des tests ?",
          options: ["Elle execute les tests plus vite", "Elle comprend l'intention du code et anticipe les edge cases", "Elle remplace les frameworks de test", "Elle elimine le besoin de CI/CD"],
          correctIndex: 1,
          explanation: "Les LLM comprennent l'intention du code et anticipent les cas limites auxquels un developpeur n'aurait pas pense, produisant des tests plus complets.",
        },
        {
          question: "Combien de tests l'IA peut-elle generer en quelques secondes ?",
          options: ["1 a 2", "3 a 5", "10 a 20", "100+"],
          correctIndex: 2,
          explanation: "L'IA peut generer 10 a 20 tests pertinents en quelques secondes, couvrant le happy path, les erreurs, les edge cases et les valeurs limites.",
        },
        {
          question: "Qu'est-ce que le TDD avec l'IA ?",
          options: ["Tester en production", "Generer les tests avant le code, puis implementer", "Supprimer les tests existants", "Tester uniquement le frontend"],
          correctIndex: 1,
          explanation: "Le TDD (Test-Driven Development) avec l'IA consiste a generer les tests d'abord, puis demander a l'IA d'implementer le code qui fait passer ces tests.",
        },
        {
          question: "Pour les tests E2E, quel outil l'IA peut-elle cibler ?",
          options: ["Jest uniquement", "Playwright et Cypress", "Selenium uniquement", "Aucun outil E2E"],
          correctIndex: 1,
          explanation: "L'IA peut generer des tests E2E pour Playwright et Cypress a partir de descriptions en langage naturel des parcours utilisateur.",
        },
      ],
    },
    {
      number: 9,
      title: "Refactoring et Optimisation",
      description: "Ameliorer la qualite et les performances du code avec l'assistance IA.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Refactoring Assiste par l'IA" },
        { type: "paragraph", content: "Le refactoring — restructurer du code sans changer son comportement — est une tache ou l'IA excelle. Elle identifie les code smells, propose des patterns plus propres, et peut executer des refactorings massifs a travers des dizaines de fichiers en quelques minutes." },
        { type: "paragraph", content: "En 2026, les outils comme Cursor Agent et Claude Code peuvent analyser un codebase complet, identifier les dettes techniques, et proposer un plan de refactoring priorise." },
        { type: "heading", content: "Techniques de Refactoring IA" },
        { type: "paragraph", content: "Extraction de fonctions et composants, elimination de code duplique (DRY), simplification de conditions complexes, renommage semantique, conversion de callbacks en async/await, migration de class components vers hooks React." },
        { type: "subheading", content: "Optimisation de Performance" },
        { type: "paragraph", content: "L'IA peut analyser votre code pour identifier les goulots d'etranglement : requetes N+1, re-renders inutiles, imports lourds, boucles inefficaces. Elle propose des solutions concretes : memoisation, lazy loading, pagination, indexation." },
        { type: "prompt-example", prompt: "Identifie les problemes de performance dans ce composant React et optimise-le", result: "L'IA detecte : un useMemo manquant, un mapping recreee a chaque render, un composant enfant qui re-render inutilement. Elle ajoute useMemo, useCallback et React.memo." },
        { type: "key-point", content: "Le refactoring IA est plus sur quand il est accompagne de tests. Generez les tests d'abord, puis refactorez — les tests garantissent que le comportement ne change pas." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Refactoring et optimisation avec l'IA" },
        { type: "diagram", label: "Processus de Refactoring IA", flow: "vertical", nodes: [
          { label: "Analyse du code", sub: "Detection des code smells et dettes", color: "blue" },
          { label: "Generation de tests", sub: "Securiser le comportement existant", color: "purple" },
          { label: "Refactoring", sub: "Restructuration automatisee", color: "emerald" },
          { label: "Verification", sub: "Tous les tests passent", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA identifie code smells et dettes techniques automatiquement",
          "Refactoring massif multi-fichiers en quelques minutes",
          "Optimisation : memoisation, lazy loading, requetes N+1",
          "Toujours securiser avec des tests avant de refactorer",
          "Cursor Agent et Claude Code excellent dans ce domaine",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que le refactoring ?",
          options: ["Ajouter de nouvelles fonctionnalites", "Restructurer le code sans changer son comportement", "Supprimer du code", "Changer le langage de programmation"],
          correctIndex: 1,
          explanation: "Le refactoring consiste a restructurer le code pour le rendre plus propre, lisible et maintenable, sans changer son comportement exterieur.",
        },
        {
          question: "Pourquoi faut-il des tests avant de refactorer ?",
          options: ["Pour ralentir le processus", "Pour garantir que le comportement ne change pas", "Pour satisfaire le linter", "Pour documenter le code"],
          correctIndex: 1,
          explanation: "Les tests servent de filet de securite : ils garantissent que le refactoring n'a pas accidentellement change le comportement du code.",
        },
        {
          question: "Quel probleme de performance l'IA peut-elle detecter ?",
          options: ["Fautes d'orthographe", "Requetes N+1 et re-renders inutiles", "Mauvais noms de variables", "Commentaires manquants"],
          correctIndex: 1,
          explanation: "L'IA detecte les goulots d'etranglement comme les requetes N+1, les re-renders inutiles, les imports lourds et les boucles inefficaces.",
        },
        {
          question: "Quel outil peut refactorer des dizaines de fichiers simultanement ?",
          options: ["Un linter", "Claude Code et Cursor Agent", "ESLint", "Prettier"],
          correctIndex: 1,
          explanation: "Claude Code et Cursor Agent peuvent analyser et modifier des dizaines de fichiers simultanement pour des refactorings massifs a travers le codebase.",
        },
      ],
    },
    {
      number: 10,
      title: "Frontend avec l'IA (React, Next.js)",
      description: "Construire des interfaces modernes avec React et Next.js assistes par l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Developpement Frontend Augmente par l'IA" },
        { type: "paragraph", content: "Le frontend est le domaine ou l'IA a le plus d'impact visible. De la generation de composants UI au styling, du responsive design a l'accessibilite, l'IA accelere chaque aspect du developpement d'interfaces modernes." },
        { type: "paragraph", content: "React et Next.js sont les frameworks les mieux supportes par les outils IA. v0, Cursor, Copilot et Claude Code produisent tous du code React/Next.js de haute qualite avec Tailwind CSS et les derniers patterns (Server Components, App Router)." },
        { type: "subheading", content: "Generation de Composants" },
        { type: "paragraph", content: "Decrivez un composant en langage naturel et l'IA le genere instantanement : navbar responsive, modal avec animations, formulaire avec validation, tableau de donnees avec tri et filtrage. Le code respecte les bonnes pratiques : accessibilite, responsive, TypeScript." },
        { type: "subheading", content: "Design System avec l'IA" },
        { type: "paragraph", content: "L'IA peut generer un design system complet : tokens de couleur, typographie, espacements, variantes de composants. shadcn/ui + Tailwind est la combinaison preferee car v0 et Cursor la maitrisent parfaitement." },
        { type: "tip", content: "Commencez par generer un composant de base avec v0, puis peaufinez-le dans Cursor. Cette approche combine la rapidite de v0 avec la precision de Cursor." },
        { type: "prompt-example", prompt: "Cree un composant DataTable React avec tri par colonne, pagination, recherche, et selection multiple. Utilise shadcn/ui et Tailwind.", result: "L'IA genere un DataTable complet avec hooks personnalises, types TypeScript, accessibilite clavier, et responsive design." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Frontend React/Next.js avec l'IA" },
        { type: "diagram", label: "Workflow Frontend IA", flow: "horizontal", nodes: [
          { label: "v0", sub: "Generation rapide de composants", color: "blue" },
          { label: "Cursor", sub: "Edition et peaufinage", color: "purple" },
          { label: "Copilot", sub: "Completion au quotidien", color: "emerald" },
          { label: "Claude Code", sub: "Refactoring et features complexes", color: "amber" },
        ]},
        { type: "summary", items: [
          "React/Next.js sont les frameworks les mieux supportes par l'IA",
          "Generation de composants complets en langage naturel",
          "shadcn/ui + Tailwind = combinaison ideale pour l'IA",
          "v0 pour generer, Cursor pour peaufiner",
          "Accessibilite et responsive generes automatiquement",
        ]},
      ],
      quiz: [
        {
          question: "Quel framework est le mieux supporte par les outils de dev IA ?",
          options: ["Angular", "Vue.js", "React/Next.js", "Svelte"],
          correctIndex: 2,
          explanation: "React et Next.js sont les frameworks les mieux supportes par v0, Cursor, Copilot et Claude Code grace a leur popularite dans les donnees d'entrainement.",
        },
        {
          question: "Quelle combinaison CSS est preferee par les outils IA ?",
          options: ["Bootstrap + CSS", "Material UI + Emotion", "shadcn/ui + Tailwind CSS", "Styled Components"],
          correctIndex: 2,
          explanation: "shadcn/ui + Tailwind CSS est la combinaison preferee car v0 et Cursor la maitrisent parfaitement, produisant du code propre et personnalisable.",
        },
        {
          question: "Quelle approche combine rapidite et precision ?",
          options: ["Tout coder a la main", "Generer avec v0 puis peaufiner dans Cursor", "Utiliser uniquement ChatGPT", "Copier du code de Stack Overflow"],
          correctIndex: 1,
          explanation: "Generer un composant de base avec v0 (rapidite) puis le peaufiner dans Cursor (precision contextuelle) est l'approche optimale.",
        },
        {
          question: "Quels aspects l'IA gere-t-elle dans le frontend ?",
          options: ["Uniquement le style", "Composants, accessibilite, responsive, TypeScript", "Uniquement le HTML", "Uniquement les animations"],
          correctIndex: 1,
          explanation: "L'IA genere des composants complets avec accessibilite, responsive design, types TypeScript et bonnes pratiques — pas juste le visuel.",
        },
      ],
    },
    {
      number: 11,
      title: "Backend et APIs avec l'IA",
      description: "Creer des APIs robustes et des services backend avec l'assistance de l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Backend Development Assiste par l'IA" },
        { type: "paragraph", content: "L'IA transforme le developpement backend : generation d'APIs REST et GraphQL, schemas de base de donnees, middleware d'authentification, validation de donnees, gestion d'erreurs — le tout genere a partir de descriptions en langage naturel." },
        { type: "paragraph", content: "Les LLM maitrisent les frameworks backend populaires : Express, Fastify, Django, FastAPI, Spring Boot, Rails. Ils generent du code idiomatique qui respecte les conventions de chaque ecosysteme." },
        { type: "subheading", content: "Generation d'APIs" },
        { type: "paragraph", content: "Decrivez vos endpoints et l'IA genere le code complet : routes, controllers, validation des inputs, gestion d'erreurs, documentation OpenAPI. Elle peut generer un CRUD complet en quelques secondes." },
        { type: "subheading", content: "Authentification et Securite" },
        { type: "paragraph", content: "L'IA genere des systemes d'authentification complets : JWT, OAuth2, sessions. Elle connait les bonnes pratiques : hashage de mots de passe (bcrypt), protection CSRF, rate limiting, validation d'inputs, headers de securite." },
        { type: "prompt-example", prompt: "Cree une API REST Node.js/Express pour un systeme de reservations avec auth JWT, validation Zod, et pagination", result: "L'IA genere : routes CRUD, middleware JWT, schemas Zod, pagination cursor-based, gestion d'erreurs centralisee, et types TypeScript." },
        { type: "callout", content: "Attention : toujours verifier le code de securite genere par l'IA. Les LLM peuvent introduire des vulnerabilites subtiles (injection SQL, XSS, IDOR). Un audit de securite humain reste indispensable." },
        { type: "key-point", content: "L'IA est excellente pour le boilerplate backend, mais les decisions d'architecture (microservices vs monolithe, choix de base de donnees, strategies de cache) necessitent toujours une expertise humaine." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "APIs et backend avec l'IA" },
        { type: "diagram", label: "Generation Backend avec l'IA", flow: "horizontal", nodes: [
          { label: "API REST/GraphQL", sub: "Routes, controllers, validation", color: "blue" },
          { label: "Authentification", sub: "JWT, OAuth2, sessions", color: "purple" },
          { label: "Base de donnees", sub: "Schemas, migrations, queries", color: "emerald" },
          { label: "Deploiement", sub: "Docker, CI/CD, monitoring", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA genere des APIs completes a partir de descriptions naturelles",
          "Support des frameworks majeurs : Express, Django, FastAPI, Spring",
          "Authentification, validation et securite generees automatiquement",
          "Toujours auditer le code de securite genere par l'IA",
          "Les decisions d'architecture restent humaines",
        ]},
      ],
      quiz: [
        {
          question: "Que peut generer l'IA pour le backend ?",
          options: ["Uniquement des routes", "APIs completes avec auth, validation et gestion d'erreurs", "Uniquement la documentation", "Uniquement les schemas de base de donnees"],
          correctIndex: 1,
          explanation: "L'IA genere des APIs completes incluant routes, controllers, authentification, validation, gestion d'erreurs, et documentation OpenAPI.",
        },
        {
          question: "Pourquoi faut-il auditer le code de securite genere par l'IA ?",
          options: ["L'IA genere du code lent", "L'IA peut introduire des vulnerabilites subtiles", "L'IA ne supporte pas HTTPS", "L'IA ne comprend pas les bases de donnees"],
          correctIndex: 1,
          explanation: "Les LLM peuvent introduire des vulnerabilites subtiles comme des injections SQL, XSS ou IDOR. Un audit de securite humain reste indispensable.",
        },
        {
          question: "Quel aspect du backend reste une decision humaine ?",
          options: ["L'ecriture des routes", "L'architecture (microservices vs monolithe)", "La validation des inputs", "La gestion d'erreurs"],
          correctIndex: 1,
          explanation: "Les decisions d'architecture comme le choix entre microservices et monolithe, le choix de base de donnees, et les strategies de cache necessitent une expertise humaine.",
        },
        {
          question: "Quel outil de validation l'IA utilise-t-elle souvent avec Node.js ?",
          options: ["jQuery Validate", "Zod", "HTML5 Validation", "Regex uniquement"],
          correctIndex: 1,
          explanation: "Zod est la bibliotheque de validation TypeScript-first la plus populaire en 2026, et les LLM la maitrisent parfaitement pour generer des schemas de validation.",
        },
      ],
    },
    {
      number: 12,
      title: "Bases de Donnees et SQL avec l'IA",
      description: "Concevoir des schemas, ecrire des requetes SQL et optimiser avec l'IA.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "SQL et Bases de Donnees Assistes par l'IA" },
        { type: "paragraph", content: "L'IA transforme le travail avec les bases de donnees. De la conception de schemas a l'ecriture de requetes complexes, de l'optimisation de performance a la migration de donnees, les LLM sont devenus des assistants SQL indispensables." },
        { type: "paragraph", content: "Les developpeurs qui ne maitrisent pas SQL en profondeur peuvent maintenant ecrire des requetes complexes en decrivant ce qu'ils veulent en langage naturel. Et les experts SQL utilisent l'IA pour accelerer l'ecriture de requetes et detecter les problemes d'optimisation." },
        { type: "subheading", content: "Conception de Schemas" },
        { type: "paragraph", content: "Decrivez votre modele de donnees en langage naturel et l'IA genere le schema complet : tables, colonnes, types, contraintes, index, relations. Elle connait les bonnes pratiques de normalisation et suggere des optimisations." },
        { type: "subheading", content: "Requetes Complexes" },
        { type: "paragraph", content: "Joins multiples, sous-requetes, window functions, CTEs (Common Table Expressions), requetes recursives — l'IA genere tout cela a partir de descriptions naturelles. Elle explique aussi la logique de chaque requete generee." },
        { type: "prompt-example", prompt: "Ecris une requete SQL qui retourne le top 10 des produits les plus vendus par categorie pour le mois dernier, avec le total des ventes et la variation par rapport au mois precedent", result: "L'IA genere une CTE avec window functions (LAG, ROW_NUMBER, SUM) qui calcule les ventes mensuelles, la variation, et le classement par categorie." },
        { type: "tip", content: "Utilisez Claude Code pour analyser les plans d'execution (EXPLAIN ANALYZE) et identifier les index manquants. Il peut optimiser des requetes lentes en quelques secondes." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "SQL et bases de donnees avec l'IA" },
        { type: "diagram", label: "Taches SQL Assistees par l'IA", flow: "horizontal", nodes: [
          { label: "Conception de schema", sub: "Tables, index, relations", color: "blue" },
          { label: "Requetes complexes", sub: "Joins, CTEs, window functions", color: "purple" },
          { label: "Optimisation", sub: "Index, plans d'execution", color: "emerald" },
          { label: "Migration", sub: "Transformation de donnees", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA genere des schemas et des requetes SQL a partir de langage naturel",
          "Requetes complexes (CTEs, window functions) accessibles a tous",
          "Analyse de plans d'execution et optimisation automatisee",
          "Les experts SQL gagnent aussi du temps avec l'IA",
          "Toujours verifier les requetes generees sur des donnees de test",
        ]},
      ],
      quiz: [
        {
          question: "Comment l'IA aide-t-elle avec les bases de donnees ?",
          options: ["Elle heberge les bases", "Elle genere schemas, requetes et optimisations a partir de langage naturel", "Elle remplace SQL", "Elle cree des backups automatiques"],
          correctIndex: 1,
          explanation: "L'IA genere des schemas, des requetes complexes et des optimisations a partir de descriptions en langage naturel, rendant SQL accessible a tous.",
        },
        {
          question: "Qu'est-ce qu'une CTE en SQL ?",
          options: ["Un type de jointure", "Une Common Table Expression (sous-requete nommee)", "Un index", "Une contrainte"],
          correctIndex: 1,
          explanation: "Une CTE (Common Table Expression) est une sous-requete nommee qui rend les requetes complexes plus lisibles et maintenables.",
        },
        {
          question: "Comment optimiser une requete lente avec l'IA ?",
          options: ["Supprimer la requete", "Faire analyser le plan d'execution (EXPLAIN ANALYZE)", "Augmenter la RAM du serveur", "Changer de base de donnees"],
          correctIndex: 1,
          explanation: "L'IA peut analyser les plans d'execution (EXPLAIN ANALYZE) et identifier les index manquants ou les operations couteuses pour optimiser les requetes.",
        },
        {
          question: "Faut-il verifier les requetes SQL generees par l'IA ?",
          options: ["Non, elles sont toujours correctes", "Oui, toujours sur des donnees de test", "Seulement pour les DELETE", "Seulement en production"],
          correctIndex: 1,
          explanation: "Il faut toujours verifier les requetes generees sur des donnees de test pour s'assurer qu'elles retournent les resultats attendus et sont performantes.",
        },
      ],
    },
    {
      number: 13,
      title: "DevOps et CI/CD Assiste par l'IA",
      description: "Automatiser le deploiement, l'infrastructure et les pipelines avec l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "DevOps Augmente par l'IA" },
        { type: "paragraph", content: "Le DevOps est un domaine ou l'IA apporte une valeur enorme : generation de configurations Docker, pipelines CI/CD, infrastructure as code (Terraform, Pulumi), monitoring, et incident response. Les configurations complexes qui prenaient des heures se generent en minutes." },
        { type: "paragraph", content: "Les LLM maitrisent les ecosystemes DevOps : Docker, Kubernetes, GitHub Actions, GitLab CI, Terraform, Ansible, Nginx, et les services cloud (AWS, GCP, Azure, Vercel). Ils generent des configurations idiomatiques et securisees." },
        { type: "subheading", content: "Dockerisation avec l'IA" },
        { type: "paragraph", content: "Decrivez votre application et l'IA genere un Dockerfile optimise : multi-stage build, layer caching, securite (non-root user), et un docker-compose pour l'environnement de dev complet avec base de donnees et cache." },
        { type: "subheading", content: "Pipelines CI/CD" },
        { type: "paragraph", content: "L'IA genere des pipelines GitHub Actions ou GitLab CI complets : lint, tests, build, deploy. Elle configure les environments, les secrets, les conditions de deploiement, et les notifications." },
        { type: "prompt-example", prompt: "Cree un pipeline GitHub Actions pour une app Next.js : lint, tests, build, preview deploy sur Vercel pour les PRs, et production deploy sur merge dans main", result: "L'IA genere un workflow YAML complet avec les jobs parallelises, les caches npm, les secrets Vercel, et les conditions de trigger." },
        { type: "callout", content: "L'IA peut aussi analyser vos logs de deploiement et diagnostiquer les echecs. Collez le log d'erreur de votre pipeline et obtenez un diagnostic precis en secondes." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "DevOps et CI/CD avec l'IA" },
        { type: "diagram", label: "Pipeline CI/CD Genere par l'IA", flow: "horizontal", nodes: [
          { label: "Lint & Format", sub: "ESLint, Prettier", color: "blue" },
          { label: "Tests", sub: "Unitaires + integration", color: "purple" },
          { label: "Build", sub: "Compilation + optimisation", color: "emerald" },
          { label: "Deploy", sub: "Preview PR + Production", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA genere Dockerfiles, pipelines CI/CD et infra as code",
          "Configurations complexes generees en minutes au lieu d'heures",
          "Support des ecosystemes : Docker, K8s, GitHub Actions, Terraform",
          "Diagnostic automatise des echecs de deploiement",
          "Toujours auditer les configurations de securite generees",
        ]},
      ],
      quiz: [
        {
          question: "Que peut generer l'IA pour le DevOps ?",
          options: ["Uniquement des Dockerfiles", "Dockerfiles, pipelines CI/CD, et infrastructure as code", "Uniquement des scripts bash", "Uniquement de la documentation"],
          correctIndex: 1,
          explanation: "L'IA genere des Dockerfiles optimises, des pipelines CI/CD complets, de l'infrastructure as code (Terraform, Pulumi), et des configurations de monitoring.",
        },
        {
          question: "Quel avantage apporte l'IA pour les pipelines CI/CD ?",
          options: ["Elle les execute plus vite", "Elle genere des configurations complexes en minutes", "Elle remplace GitHub", "Elle heberge les deploiements"],
          correctIndex: 1,
          explanation: "L'IA genere des pipelines complets avec jobs parallelises, caches, secrets et conditions — des configurations qui prenaient des heures manuellement.",
        },
        {
          question: "Qu'est-ce qu'un Dockerfile multi-stage ?",
          options: ["Un Dockerfile avec plusieurs ports", "Un Dockerfile qui separe build et runtime pour des images plus legeres", "Un Dockerfile pour plusieurs apps", "Un Dockerfile avec plusieurs OS"],
          correctIndex: 1,
          explanation: "Un multi-stage build separe l'etape de compilation de l'etape d'execution, produisant des images Docker plus legeres et plus securisees.",
        },
        {
          question: "Comment l'IA aide-t-elle quand un deploiement echoue ?",
          options: ["Elle relance automatiquement le deploy", "Elle analyse les logs et diagnostique l'erreur", "Elle notifie l'equipe", "Elle rollback automatiquement"],
          correctIndex: 1,
          explanation: "L'IA peut analyser les logs d'erreur d'un pipeline et fournir un diagnostic precis avec une solution en quelques secondes.",
        },
      ],
    },
    {
      number: 14,
      title: "Securite du Code avec l'IA",
      description: "Detecter et corriger les vulnerabilites avec l'assistance de l'IA.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Securite du Code Assistee par l'IA" },
        { type: "paragraph", content: "La securite est un domaine critique ou l'IA joue un double role : elle aide a detecter les vulnerabilites, mais elle peut aussi en introduire. Comprendre comment utiliser l'IA pour securiser votre code — et les limites de cette approche — est essentiel." },
        { type: "paragraph", content: "Les LLM connaissent les vulnerabilites courantes (OWASP Top 10), les bonnes pratiques de securite, et les patterns de code dangereux. Ils peuvent auditer du code et proposer des correctifs en quelques secondes." },
        { type: "subheading", content: "Vulnerabilites Courantes Detectees" },
        { type: "paragraph", content: "Injection SQL, Cross-Site Scripting (XSS), Cross-Site Request Forgery (CSRF), authentification cassee, exposition de donnees sensibles, mauvaise configuration de securite, deserialization non securisee." },
        { type: "subheading", content: "Audit de Securite avec l'IA" },
        { type: "paragraph", content: "Demandez a Claude Code ou Cursor d'auditer votre code pour les vulnerabilites OWASP Top 10. L'IA analyse les inputs non valides, les requetes parametrables, les headers de securite, et les secrets exposes." },
        { type: "key-point", content: "L'IA genere parfois du code avec des vulnerabilites. Ne faites JAMAIS confiance aveuglement au code de securite genere par l'IA. Un audit humain expert reste indispensable pour les systemes critiques." },
        { type: "tip", content: "Integrez des outils SAST (Static Application Security Testing) comme Snyk ou SonarQube dans votre CI/CD pour une detection automatique continue." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Securite du code avec l'IA" },
        { type: "diagram", label: "OWASP Top 10 — Vulnerabilites Cles", flow: "vertical", nodes: [
          { label: "Injection (SQL, XSS)", sub: "Inputs non sanitizes", color: "pink" },
          { label: "Authentification cassee", sub: "Sessions, mots de passe faibles", color: "amber" },
          { label: "Exposition de donnees", sub: "Secrets, API keys, PII", color: "purple" },
          { label: "Mauvaise configuration", sub: "Headers, CORS, permissions", color: "blue" },
        ]},
        { type: "summary", items: [
          "L'IA detecte les vulnerabilites OWASP Top 10 dans votre code",
          "Elle peut aussi en introduire — ne jamais faire confiance aveuglement",
          "Injection SQL, XSS, CSRF, secrets exposes detectes automatiquement",
          "Integrez SAST (Snyk, SonarQube) dans votre CI/CD",
          "L'audit humain expert reste indispensable pour les systemes critiques",
        ]},
      ],
      quiz: [
        {
          question: "Quel est le double role de l'IA en securite du code ?",
          options: ["Accelerer et ralentir", "Detecter les vulnerabilites ET potentiellement en introduire", "Chiffrer et dechiffrer", "Tester et deployer"],
          correctIndex: 1,
          explanation: "L'IA aide a detecter les vulnerabilites mais peut aussi en introduire dans le code genere. C'est pourquoi un audit humain reste indispensable.",
        },
        {
          question: "Qu'est-ce que l'OWASP Top 10 ?",
          options: ["Les 10 meilleurs langages", "Les 10 vulnerabilites web les plus courantes", "Les 10 meilleurs outils de dev", "Les 10 frameworks les plus populaires"],
          correctIndex: 1,
          explanation: "L'OWASP Top 10 est une liste des 10 vulnerabilites de securite web les plus courantes et les plus critiques, mise a jour regulierement.",
        },
        {
          question: "Que sont les outils SAST ?",
          options: ["Des editeurs de code", "Des outils d'analyse statique de securite", "Des gestionnaires de paquets", "Des bases de donnees"],
          correctIndex: 1,
          explanation: "SAST (Static Application Security Testing) sont des outils comme Snyk et SonarQube qui analysent le code source pour detecter les vulnerabilites automatiquement.",
        },
        {
          question: "Faut-il faire confiance au code de securite genere par l'IA ?",
          options: ["Oui, toujours", "Non, un audit humain expert reste indispensable", "Seulement pour les petits projets", "Seulement si l'IA est payante"],
          correctIndex: 1,
          explanation: "Il ne faut jamais faire confiance aveuglement au code de securite genere par l'IA. Un audit humain expert reste indispensable pour les systemes critiques.",
        },
      ],
    },
    {
      number: 15,
      title: "Documentation Automatique",
      description: "Generer et maintenir une documentation de qualite avec l'IA.",
      estimatedMinutes: 6,
      sections: [
        { type: "heading", content: "Documentation Automatisee par l'IA" },
        { type: "paragraph", content: "La documentation est souvent negligee parce qu'elle est chronophage. L'IA change la donne : elle genere des JSDoc/TSDoc, des README, des guides d'API, des commentaires inline, et meme des guides d'architecture — le tout a partir du code existant." },
        { type: "paragraph", content: "Les LLM comprennent le code et peuvent expliquer sa logique en langage naturel. Ils produisent une documentation coherente, a jour, et adaptee au public cible (developpeur junior, utilisateur final, devops)." },
        { type: "subheading", content: "Types de Documentation Generee" },
        { type: "paragraph", content: "JSDoc/TSDoc pour les fonctions et classes. README complets avec installation, usage et exemples. Documentation d'API avec endpoints, parametres et reponses. Commentaires inline pour la logique complexe. ADR (Architecture Decision Records) pour les choix techniques." },
        { type: "subheading", content: "Maintenir la Documentation a Jour" },
        { type: "paragraph", content: "Integrez la generation de documentation dans votre workflow : apres chaque modification, demandez a l'IA de mettre a jour la doc correspondante. Certains outils peuvent detecter automatiquement les changements de code et mettre a jour la documentation." },
        { type: "prompt-example", prompt: "Genere la documentation TSDoc pour toutes les fonctions exportees de ce module, avec exemples d'usage", result: "L'IA genere des blocs TSDoc complets pour chaque fonction : description, @param, @returns, @throws, @example — avec des exemples realistes." },
        { type: "tip", content: "Demandez a l'IA de generer la documentation comme si elle expliquait a un developpeur junior qui decouvre le projet. Cela produit des docs plus claires et plus utiles." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Documentation automatique avec l'IA" },
        { type: "diagram", label: "Types de Documentation IA", flow: "horizontal", nodes: [
          { label: "Code (JSDoc)", sub: "Fonctions, classes, types", color: "blue" },
          { label: "Projet (README)", sub: "Installation, usage, exemples", color: "purple" },
          { label: "API", sub: "Endpoints, parametres, reponses", color: "emerald" },
          { label: "Architecture", sub: "ADR, diagrammes, decisions", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA genere JSDoc, README, docs API et commentaires automatiquement",
          "Documentation coherente et adaptee au public cible",
          "Integrez la mise a jour de doc dans votre workflow",
          "Expliquez a un junior = meilleure qualite de documentation",
          "Gain de temps considerable sur une tache souvent negligee",
        ]},
      ],
      quiz: [
        {
          question: "Pourquoi la documentation est-elle souvent negligee ?",
          options: ["Elle n'est pas utile", "Elle est chronophage", "Les outils n'existent pas", "Les clients ne la demandent pas"],
          correctIndex: 1,
          explanation: "La documentation est souvent negligee parce qu'elle prend du temps. L'IA change cela en generant de la documentation de qualite automatiquement.",
        },
        {
          question: "Qu'est-ce qu'un ADR ?",
          options: ["Un type de base de donnees", "Un Architecture Decision Record", "Un outil de test", "Un format d'image"],
          correctIndex: 1,
          explanation: "Un ADR (Architecture Decision Record) documente les decisions techniques importantes : pourquoi tel choix a ete fait, les alternatives considerees, et les consequences.",
        },
        {
          question: "Comment maintenir la documentation a jour ?",
          options: ["La reecrire chaque mois", "Integrer la generation de doc dans le workflow de dev", "Ne pas la maintenir", "La deleguer a un redacteur technique"],
          correctIndex: 1,
          explanation: "Integrer la generation de documentation dans le workflow quotidien : apres chaque modification, demander a l'IA de mettre a jour la doc correspondante.",
        },
        {
          question: "Quel conseil ameliore la qualite de la documentation generee ?",
          options: ["Utiliser un vocabulaire technique maximum", "Demander a l'IA d'expliquer comme a un junior", "Generer le moins de doc possible", "Ecrire en anglais uniquement"],
          correctIndex: 1,
          explanation: "Demander a l'IA de documenter comme si elle expliquait a un developpeur junior produit des documentations plus claires, plus detaillees et plus utiles.",
        },
      ],
    },
    {
      number: 16,
      title: "Projets Full-Stack avec l'IA",
      description: "Construire une application complete de A a Z avec l'IA comme copilote.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Construire un Projet Full-Stack avec l'IA" },
        { type: "paragraph", content: "Construire une application full-stack de A a Z avec l'IA est radicalement different du developpement traditionnel. Au lieu de coder chaque ligne, vous orchestrez : vous decrivez, l'IA genere, vous validez et iterez. Un projet qui prenait des semaines peut se realiser en quelques jours." },
        { type: "paragraph", content: "La cle est de combiner les bons outils pour chaque phase du projet : v0 pour le prototypage UI, Cursor pour le developpement iteratif, Claude Code pour les features complexes, et GitHub Actions pour le CI/CD." },
        { type: "heading", content: "Les Phases d'un Projet Full-Stack IA" },
        { type: "subheading", content: "Phase 1 : Architecture et Planification" },
        { type: "paragraph", content: "Utilisez Claude ou ChatGPT pour definir l'architecture : stack technique, schema de base de donnees, structure de fichiers, API endpoints. L'IA propose des architectures eprouvees adaptees a votre cas d'usage." },
        { type: "subheading", content: "Phase 2 : Prototypage Rapide" },
        { type: "paragraph", content: "Generez les premieres pages avec v0 ou Bolt. En 30 minutes, vous avez un prototype fonctionnel a montrer. Iterez sur le design en conversation jusqu'a satisfaction." },
        { type: "subheading", content: "Phase 3 : Developpement Iteratif" },
        { type: "paragraph", content: "Passez dans Cursor ou Claude Code pour le developpement reel. Implementez feature par feature, avec l'IA comme copilote permanent. Tests et reviews a chaque etape." },
        { type: "callout", content: "Pro tip : gardez un fichier ARCHITECTURE.md a la racine du projet. L'IA le lira a chaque session et generera du code coherent avec votre vision globale." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Projet full-stack avec l'IA de A a Z" },
        { type: "diagram", label: "Phases d'un Projet Full-Stack IA", flow: "vertical", nodes: [
          { label: "Phase 1 — Architecture", sub: "Claude/ChatGPT : stack, schema, API", color: "blue" },
          { label: "Phase 2 — Prototypage", sub: "v0/Bolt : UI fonctionnelle en 30min", color: "purple" },
          { label: "Phase 3 — Developpement", sub: "Cursor/Claude Code : feature par feature", color: "emerald" },
          { label: "Phase 4 — Deploiement", sub: "Vercel/Docker + CI/CD automatise", color: "amber" },
        ]},
        { type: "summary", items: [
          "Un projet full-stack avec l'IA : jours au lieu de semaines",
          "Combiner les outils : v0 (proto), Cursor (dev), Claude Code (complex)",
          "Architecture d'abord, puis prototypage rapide, puis dev iteratif",
          "ARCHITECTURE.md donne de la coherence a l'ensemble",
          "L'IA ne remplace pas la vision produit — elle accelere l'execution",
        ]},
      ],
      quiz: [
        {
          question: "En combien de temps un prototype peut-il etre genere avec v0 ou Bolt ?",
          options: ["5 minutes", "30 minutes", "2 heures", "1 journee"],
          correctIndex: 1,
          explanation: "Avec v0 ou Bolt, un prototype fonctionnel avec UI et interactions peut etre genere en environ 30 minutes d'iteration conversationnelle.",
        },
        {
          question: "Quelle est la premiere phase d'un projet full-stack avec l'IA ?",
          options: ["Coder le frontend", "Architecture et planification", "Deployer sur Vercel", "Ecrire les tests"],
          correctIndex: 1,
          explanation: "La premiere phase est l'architecture : definir le stack, le schema de base de donnees, la structure de fichiers et les API endpoints avec l'aide de l'IA.",
        },
        {
          question: "A quoi sert un fichier ARCHITECTURE.md ?",
          options: ["A documenter les APIs", "A donner a l'IA une vision coherente du projet", "A configurer le deploiement", "A lister les dependances"],
          correctIndex: 1,
          explanation: "ARCHITECTURE.md donne a l'IA le contexte global du projet a chaque session, assurant que le code genere reste coherent avec la vision architecturale.",
        },
        {
          question: "Quel est le role du developpeur dans un projet full-stack IA ?",
          options: ["Coder chaque ligne", "Orchestrer : decrire, valider, iterer", "Juste deployer", "Uniquement tester"],
          correctIndex: 1,
          explanation: "Le developpeur orchestre le projet : il decrit ce qu'il veut, l'IA genere, il valide et itere. La vision produit et la validation restent humaines.",
        },
      ],
    },
    {
      number: 17,
      title: "Travailler en Equipe avec l'IA",
      description: "Integrer les outils IA dans le workflow d'une equipe de developpement.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "L'IA dans le Workflow d'Equipe" },
        { type: "paragraph", content: "Adopter l'IA en equipe est different de l'utiliser seul. Il faut standardiser les outils, definir des conventions, gerer les licences, et s'assurer que le code genere par l'IA respecte les standards de l'equipe." },
        { type: "paragraph", content: "En 2026, les equipes performantes ont un 'IA stack' defini : quels outils, quels modeles, quelles regles. Les fichiers de configuration (.cursorrules, CLAUDE.md) sont partages dans le repo pour assurer la coherence." },
        { type: "subheading", content: "Standardisation des Outils" },
        { type: "paragraph", content: "Definissez un stack IA d'equipe : IDE (Cursor ou VS Code + Copilot), agent CLI (Claude Code), generateur (v0 pour les composants). Partagez les configurations et les regles dans le repo." },
        { type: "subheading", content: "Conventions de Code IA" },
        { type: "paragraph", content: "Definissez des regles : le code genere doit passer les memes reviews que le code humain. Les tests sont obligatoires. Les prompts utilises pour les generations complexes sont documentes dans les commits." },
        { type: "heading", content: "Pair Programming avec l'IA" },
        { type: "paragraph", content: "L'IA est le partenaire de pair programming ideal : disponible 24/7, patient, et connaissant une immense base de code. Mais attention a ne pas devenir dependant — chaque membre de l'equipe doit comprendre le code genere." },
        { type: "key-point", content: "Regle d'or : si un developpeur ne peut pas expliquer le code genere par l'IA, ce code ne devrait pas etre merge. La comprehension humaine reste le garde-fou essentiel." },
        { type: "tip", content: "Organisez des sessions de partage 'IA tips' hebdomadaires ou chaque membre de l'equipe partage une technique ou un prompt utile." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Travailler en equipe avec l'IA" },
        { type: "diagram", label: "IA Stack d'Equipe", flow: "horizontal", nodes: [
          { label: "IDE IA", sub: "Cursor ou VS Code + Copilot", color: "blue" },
          { label: "Agent CLI", sub: "Claude Code partage", color: "purple" },
          { label: "Review IA", sub: "Copilot Review / CodeRabbit", color: "emerald" },
          { label: "Config partagee", sub: ".cursorrules, CLAUDE.md", color: "amber" },
        ]},
        { type: "summary", items: [
          "Definir un stack IA d'equipe standardise",
          "Fichiers de config (.cursorrules, CLAUDE.md) partages dans le repo",
          "Le code IA passe les memes reviews que le code humain",
          "Regle d'or : si tu ne peux pas l'expliquer, ne le merge pas",
          "Sessions 'IA tips' hebdomadaires pour partager les bonnes pratiques",
        ]},
      ],
      quiz: [
        {
          question: "Quelle est la regle d'or pour le code genere par l'IA en equipe ?",
          options: ["Toujours le merger rapidement", "Ne jamais le modifier", "Si tu ne peux pas l'expliquer, ne le merge pas", "Toujours le reecrire"],
          correctIndex: 2,
          explanation: "Si un developpeur ne peut pas expliquer le code genere par l'IA, ce code ne devrait pas etre merge. La comprehension humaine est le garde-fou essentiel.",
        },
        {
          question: "Comment standardiser l'utilisation de l'IA en equipe ?",
          options: ["Laisser chacun choisir ses outils", "Definir un stack IA et partager les configs dans le repo", "Interdire l'IA", "Utiliser uniquement ChatGPT"],
          correctIndex: 1,
          explanation: "Definir un stack IA d'equipe (IDE, agent, generateur) et partager les configurations (.cursorrules, CLAUDE.md) dans le repo assure la coherence.",
        },
        {
          question: "Le code genere par l'IA doit-il passer par une review ?",
          options: ["Non, l'IA ne fait pas d'erreurs", "Oui, les memes reviews que le code humain", "Seulement pour les juniors", "Seulement s'il touche la base de donnees"],
          correctIndex: 1,
          explanation: "Le code genere par l'IA doit passer exactement les memes reviews et les memes tests que le code ecrit par un humain.",
        },
        {
          question: "Qu'est-ce qu'une session 'IA tips' ?",
          options: ["Une formation obligatoire", "Un partage hebdomadaire de techniques et prompts utiles", "Un audit de code", "Une demo produit"],
          correctIndex: 1,
          explanation: "Les sessions 'IA tips' sont des moments hebdomadaires ou chaque membre partage une technique, un prompt ou une astuce IA utile pour toute l'equipe.",
        },
      ],
    },
    {
      number: 18,
      title: "Construire son Workflow de Dev IA",
      description: "Assembler tous les outils en un workflow personnalise et efficace.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Votre Workflow de Developpement IA Personnalise" },
        { type: "paragraph", content: "Vous avez decouvert les outils individuels. Maintenant, il est temps de les assembler en un workflow coherent et personnalise. Le meilleur workflow IA est celui qui s'adapte a VOTRE facon de travailler, pas l'inverse." },
        { type: "paragraph", content: "Il n'existe pas de workflow unique qui fonctionne pour tout le monde. Un freelance solo n'a pas les memes besoins qu'une equipe de 50. Un projet greenfield n'utilise pas les memes outils qu'une maintenance de legacy. L'objectif est de construire VOTRE stack." },
        { type: "heading", content: "Les Composantes d'un Workflow IA" },
        { type: "subheading", content: "1. IDE et Completion" },
        { type: "paragraph", content: "Cursor (tout-en-un) ou VS Code + Copilot (modulaire). Pour la plupart des devs, Cursor est le choix optimal en 2026 grace a son integration native." },
        { type: "subheading", content: "2. Agent pour les Taches Complexes" },
        { type: "paragraph", content: "Claude Code pour les refactorings, migrations, et features complexes. Lancez-le dans un terminal separe pendant que vous continuez a travailler dans votre IDE." },
        { type: "subheading", content: "3. Generateurs pour le Prototypage" },
        { type: "paragraph", content: "v0 pour les composants UI, Bolt pour les prototypes full-stack. Utilisez-les en debut de projet pour aller vite, puis migrez dans Cursor pour le peaufinage." },
        { type: "subheading", content: "4. Automatisation" },
        { type: "paragraph", content: "GitHub Actions pour le CI/CD, Copilot Review pour les PRs, et des scripts custom avec Claude API pour les taches repetitives specifiques a votre projet." },
        { type: "callout", content: "Commencez simple : Cursor + Claude Code suffisent pour 90% des taches. Ajoutez des outils au fur et a mesure que vous identifiez des besoins specifiques." },
        { type: "key-point", content: "Le workflow ideal evolue avec le temps. Revoyez-le chaque mois : quels outils utilisez-vous vraiment ? Lesquels sont superflus ? Quels nouveaux outils valent la peine d'etre testes ?" },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Construire son workflow de dev IA" },
        { type: "diagram", label: "Workflow de Dev IA Complet", flow: "vertical", nodes: [
          { label: "IDE — Cursor / VS Code + Copilot", sub: "Developpement quotidien", color: "blue" },
          { label: "Agent — Claude Code", sub: "Taches complexes et refactoring", color: "purple" },
          { label: "Generateur — v0 / Bolt", sub: "Prototypage rapide", color: "emerald" },
          { label: "CI/CD — GitHub Actions + Review IA", sub: "Automatisation et qualite", color: "amber" },
          { label: "LLM — ChatGPT / Claude", sub: "Recherche, debugging, documentation", color: "pink" },
        ]},
        { type: "diagram", label: "Cycle d'Amelioration du Workflow", flow: "cycle", nodes: [
          { label: "Utiliser", sub: "Travailler avec vos outils actuels", color: "blue" },
          { label: "Evaluer", sub: "Identifier ce qui marche et ce qui manque", color: "purple" },
          { label: "Ajuster", sub: "Ajouter, retirer ou remplacer des outils", color: "emerald" },
        ]},
        { type: "summary", items: [
          "Le meilleur workflow s'adapte a VOTRE facon de travailler",
          "Cursor + Claude Code couvrent 90% des besoins",
          "v0/Bolt pour le prototypage, GitHub Actions pour le CI/CD",
          "Commencez simple et ajoutez des outils selon les besoins",
          "Revoyez votre workflow chaque mois pour l'optimiser",
        ]},
      ],
      quiz: [
        {
          question: "Quels deux outils couvrent 90% des besoins de developpement IA ?",
          options: ["ChatGPT + Midjourney", "Cursor + Claude Code", "v0 + Bolt", "Copilot + Stack Overflow"],
          correctIndex: 1,
          explanation: "Cursor (IDE IA) + Claude Code (agent CLI) couvrent environ 90% des besoins quotidiens de developpement assiste par l'IA.",
        },
        {
          question: "A quelle frequence faut-il revoir son workflow IA ?",
          options: ["Jamais", "Chaque mois", "Chaque annee", "A chaque nouveau projet"],
          correctIndex: 1,
          explanation: "Il est recommande de revoir son workflow chaque mois pour identifier les outils sous-utilises, les lacunes, et les nouveaux outils a tester.",
        },
        {
          question: "Quel est le meilleur conseil pour commencer ?",
          options: ["Installer tous les outils immediatement", "Commencer simple et ajouter selon les besoins", "Attendre que les outils soient matures", "Utiliser uniquement des outils gratuits"],
          correctIndex: 1,
          explanation: "Commencer avec Cursor + Claude Code puis ajouter des outils au fur et a mesure des besoins specifiques identifies est l'approche la plus efficace.",
        },
        {
          question: "Pourquoi n'existe-t-il pas de workflow unique ideal ?",
          options: ["Les outils changent trop vite", "Chaque dev, equipe et projet a des besoins differents", "L'IA n'est pas assez mature", "Les couts sont trop eleves"],
          correctIndex: 1,
          explanation: "Un freelance solo, une equipe de 50, un projet greenfield et une maintenance legacy ont tous des besoins differents. Le workflow doit s'adapter au contexte.",
        },
      ],
    },
  ],
};

export default content;
