import type { CourseContent } from "../types";

const content: CourseContent = {
  slug: "coder-avec-ia",
  chapters: [
    {
      number: 1,
      title: "Introduction au Coding avec l'IA",
      description: "Pourquoi l'IA change tout pour les développeurs et comment en tirer parti.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Bienvenue dans l'Ère du Développement Assiste par l'IA" },
        { type: "paragraph", content: "En 2026, coder sans IA c'est comme coder sans IDE : techniquement possible, mais personne ne le fait volontairement. Les outils de développement assistés par l'IA ont transformé la façon dont on écrit, testé, debogue et déploie du code. Que vous soyez débutant ou senior, l'IA amplifie votre productivité de 2x a 10x selon les tâches." },
        { type: "paragraph", content: "Cette révolution ne remplace pas les développeurs — elle les augmente. Les meilleurs devs de 2026 sont ceux qui maitrisent l'art de collaborer avec l'IA : savoir quand la laisser générer, quand la guider, et quand reprendre la main." },
        { type: "callout", content: "Selon une étude GitHub de 2025, les développeurs utilisant Copilot completent leurs tâches 55% plus vite et rapportent une satisfaction accrue au travail." },
        { type: "video", videoId: { fr: "18oAWvzjmTw", en: "ocMOZpuAMw4" },
      videoDurationMinutes: 15, label: "Introduction au développement assisté par l'IA" },
        { type: "heading", content: "Le Paysage des Outils de Dev IA en 2026" },
        { type: "paragraph", content: "L'écosystème se divise en plusieurs catégories : les completions en ligne (Copilot), les IDE IA natifs (Cursor), les agents de code conversationnels (Claude Code), et les générateurs d'apps complètes (Bolt, v0). Chaque outil a ses forces et son cas d'usage idéal." },
        { type: "subheading", content: "Ce que Vous Allez Apprendre" },
        { type: "paragraph", content: "Ce cours couvre l'ensemble du workflow de développement avec l'IA : de l'écriture de code au debugging, du testing au déploiement, du frontend au backend. Vous sortirez avec un workflow complet et personnalisé." },
        { type: "key-point", content: "L'IA ne remplace pas la compréhension du code. Elle accélère l'exécution. Un dev qui comprend ce que l'IA génère sera toujours supérieur a un dev qui copie-colle aveuglement." },
        { type: "diagram", label: "Les Catégories d'Outils de Dev IA", flow: "horizontal", nodes: [
          { label: "Completion en ligne", sub: "Copilot, Codeium, Supermaven", color: "blue" },
          { label: "IDE IA natif", sub: "Cursor, Windsurf, Zed", color: "purple" },
          { label: "Agent conversationnel", sub: "Claude Code, Aider, Cline", color: "emerald" },
          { label: "Generateur d'apps", sub: "Bolt, v0, Lovable, Replit", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA augmente les développeurs — elle ne les remplace pas",
          "Gain de productivité de 2x a 10x selon les tâches",
          "4 catégories d'outils : complétion, IDE IA, agents, générateurs d'apps",
          "La compréhension du code reste essentielle",
          "Ce cours couvre le workflow complet du dev moderne avec l'IA",
        ]},
      ],
      quiz: [
        {
          question: "Quel gain de productivité moyen les développeurs utilisant Copilot rapportent-ils ?",
          options: ["10%", "25%", "55%", "90%"],
          correctIndex: 2,
          explanation: "Selon l'étude GitHub de 2025, les développeurs utilisant Copilot completent leurs tâches 55% plus vite en moyenne.",
        },
        {
          question: "Quelle catégorie d'outil est Cursor ?",
          options: ["Completion en ligne", "IDE IA natif", "Agent conversationnel", "Generateur d'apps"],
          correctIndex: 1,
          explanation: "Cursor est un IDE (environnement de développement) avec l'IA intégrée nativement dans chaque aspect de l'expérience.",
        },
        {
          question: "Quel est le rôle principal de l'IA dans le développement ?",
          options: ["Remplacer les développeurs", "Augmenter la productivité des développeurs", "Écrire du code parfait sans erreur", "Eliminer le besoin de comprendre le code"],
          correctIndex: 1,
          explanation: "L'IA augmente les développeurs en accelerant l'exécution, mais la compréhension du code et l'expertise restent essentielles.",
        },
        {
          question: "Bolt et v0 appartiennent a quelle catégorie d'outils ?",
          options: ["Completion en ligne", "IDE IA natif", "Agent conversationnel", "Generateur d'apps complètes"],
          correctIndex: 3,
          explanation: "Bolt et v0 sont des générateurs d'applications complètes qui créent des apps fonctionnelles à partir de descriptions en langage naturel.",
        },
      ],
    },
    {
      number: 2,
      title: "GitHub Copilot : Guide Complet",
      description: "Maîtriser GitHub Copilot pour accélérer votre workflow de code au quotidien.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "GitHub Copilot : Votre Copilote de Code" },
        { type: "paragraph", content: "GitHub Copilot est l'outil de complétion de code IA le plus utilise au monde, avec plus de 1,8 million de développeurs payants. Intégré directement dans VS Code, JetBrains, Neovim et d'autres editeurs, il suggère du code en temps réel pendant que vous tapez." },
        { type: "paragraph", content: "En 2026, Copilot va bien au-dela de la simple complétion : Copilot Chat permet des conversations contextuelles, Copilot Workspace planifie des tâches complètes, et Copilot Agent exécute des modifications multi-fichiers de manière autonome." },
        { type: "subheading", content: "Installation et Configuration" },
        { type: "paragraph", content: "Installez l'extension GitHub Copilot dans VS Code. Connectez votre compte GitHub avec un abonnement Copilot (Individual a 10$/mois, Business a 19$/mois). Activez les suggestions inline et le chat dans les paramètres." },
        { type: "heading", content: "Techniques Avancées" },
        { type: "paragraph", content: "Ecrivez des commentaires descriptifs avant votre code — Copilot les utilise comme contexte. Ouvrez les fichiers pertinents dans des onglets adjacents pour enrichir le contexte. Utilisez des noms de variables et de fonctions explicites pour guider les suggestions." },
        { type: "tip", content: "Raccourci essentiel : Tab pour accepter, Esc pour rejeter, Alt+] pour voir la suggestion suivante, Ctrl+Enter pour voir toutes les suggestions dans un panneau." },
        { type: "prompt-example", prompt: "// Fonction qui validé un email avec regex, retourné true/false et un message d'erreur", result: "Copilot génère automatiquement la fonction complète avec la regex, les cas limites, et les messages d'erreur adaptes." },
        { type: "video", videoId: { fr: "Xagh-g3zyuw", en: "n0NlxUyA7FI" },
      videoDurationMinutes: 11, label: "GitHub Copilot : guide complet 2026" },
        { type: "diagram", label: "Fonctionnalites de GitHub Copilot", flow: "horizontal", nodes: [
          { label: "Completion inline", sub: "Suggestions en temps réel", color: "blue" },
          { label: "Copilot Chat", sub: "Conversations contextuelles", color: "purple" },
          { label: "Workspace", sub: "Planification de tâches", color: "emerald" },
          { label: "Agent", sub: "Modifications multi-fichiers", color: "amber" },
        ]},
        { type: "summary", items: [
          "Copilot est l'outil de complétion IA le plus adopte (1,8M+ devs payants)",
          "Va au-dela de la complétion : Chat, Workspace, Agent",
          "Les commentaires descriptifs ameliorent les suggestions",
          "Ouvrir les fichiers pertinents enrichit le contexte",
          "Tab pour accepter, Esc pour rejeter, Alt+] pour naviguer",
        ]},
      ],
      quiz: [
        {
          question: "Combien de développeurs payants utilisent GitHub Copilot ?",
          options: ["500 000", "1 million", "1,8 million+", "5 millions"],
          correctIndex: 2,
          explanation: "GitHub Copilot compte plus de 1,8 million de développeurs payants, ce qui en fait l'outil de complétion IA le plus adopte.",
        },
        {
          question: "Quel raccourci permet d'accepter une suggestion Copilot ?",
          options: ["Enter", "Tab", "Espace", "Ctrl+A"],
          correctIndex: 1,
          explanation: "La touche Tab accepte la suggestion courante de Copilot. Esc la rejette et Alt+] affiche la suggestion suivante.",
        },
        {
          question: "Comment améliorer la qualité des suggestions Copilot ?",
          options: ["Fermer tous les autres fichiers", "Écrire des commentaires descriptifs avant le code", "Utiliser des noms de variables courts", "Desactiver le chat"],
          correctIndex: 1,
          explanation: "Les commentaires descriptifs fournissent du contexte a Copilot, ce qui améliore significativement la pertinence des suggestions générées.",
        },
        {
          question: "Qu'est-ce que Copilot Workspace ?",
          options: ["Un editeur de code", "Un outil de planification de tâches", "Un service d'hébergement", "Un debugger"],
          correctIndex: 1,
          explanation: "Copilot Workspace permet de planifier des tâches complètes : il analyse le problème, propose un plan, et génère les modifications nécessaires.",
        },
      ],
    },
    {
      number: 3,
      title: "Cursor : L'IDE IA",
      description: "Découvrir Cursor, l'editeur de code avec IA intégrée nativement.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Cursor : L'IDE Construit Autour de l'IA" },
        { type: "paragraph", content: "Cursor est un fork de VS Code qui intégré l'IA dans chaque aspect de l'expérience de développement. Contrairement a Copilot qui est un plugin, Cursor est un IDE entier repense autour de l'IA : complétion prédictive, edition multi-lignes, chat contextuel, et agent autonome." },
        { type: "paragraph", content: "Cursor comprend votre codebase entier. Il indexe tous vos fichiers, comprend les relations entre les modules, et utilise ce contexte pour générer du code cohérent avec votre architecture existante." },
        { type: "subheading", content: "Tab : La Completion Predictive" },
        { type: "paragraph", content: "Cursor Tab va bien au-dela de la complétion classique. Il prédit vos prochaines modifications en analysant votre pattern d'edition : renommage, refactoring, ajout de paramètres. Il anticipe vos intentions et propose des edits multi-lignes contextuels." },
        { type: "subheading", content: "Cmd+K : L'Edition Inline" },
        { type: "paragraph", content: "Selectionnez du code, appuyez sur Cmd+K (ou Ctrl+K), et decrivez ce que vous voulez en langage naturel. Cursor edite le code en place : refactoring, ajout de fonctionnalité, correction de bug, conversion de format." },
        { type: "subheading", content: "Le Chat et l'Agent" },
        { type: "paragraph", content: "Le chat Cursor (Cmd+L) permet des conversations avec votre codebase. L'Agent mode va plus loin : il peut créer des fichiers, modifier plusieurs fichiers simultanement, exécuter des commandes terminal, et iterer jusqu'à ce que la tâche soit complète." },
        { type: "callout", content: "Cursor propose des règles (.cursorrules) pour personnaliser le comportement de l'IA. Definissez votre stack, vos conventions de code, et vos préférences — l'IA les respectera dans toutes ses générations." },
        { type: "key-point", content: "La force de Cursor est l'indexation du codebase. Plus votre projet est gros, plus l'avantage de Cursor sur les outils génériques est important." },
        { type: "video", videoId: { fr: "Xagh-g3zyuw", en: "Fi3AJZZregI" },
      videoDurationMinutes: 15, label: "Cursor IDE : tutoriel complet" },
        { type: "diagram", label: "Les Fonctionnalites Clés de Cursor", flow: "vertical", nodes: [
          { label: "Tab — Completion prédictive", sub: "Anticipe vos edits multi-lignes", color: "blue" },
          { label: "Cmd+K — Edition inline", sub: "Modification en langage naturel", color: "purple" },
          { label: "Cmd+L — Chat contextuel", sub: "Conversation avec votre codebase", color: "emerald" },
          { label: "Agent — Autonomie", sub: "Cree, modifié, exécute automatiquement", color: "amber" },
        ]},
        { type: "summary", items: [
          "Cursor est un IDE entier repense autour de l'IA (fork de VS Code)",
          "Tab : complétion prédictive multi-lignes",
          "Cmd+K : edition inline en langage naturel",
          "Chat + Agent : conversations et modifications autonomes",
          "Les .cursorrules personnalisent le comportement de l'IA",
        ]},
      ],
      quiz: [
        {
          question: "Sur quel editeur Cursor est-il base ?",
          options: ["Vim", "VS Code", "Sublime Text", "IntelliJ"],
          correctIndex: 1,
          explanation: "Cursor est un fork de VS Code, ce qui signifie qu'il supporte toutes les extensions VS Code tout en ajoutant des fonctionnalités IA natives.",
        },
        {
          question: "Quel raccourci lance l'edition inline dans Cursor ?",
          options: ["Cmd+L", "Cmd+K", "Cmd+I", "Cmd+Enter"],
          correctIndex: 1,
          explanation: "Cmd+K (ou Ctrl+K sur Windows/Linux) lance l'edition inline : selectionnez du code et decrivez la modification souhaitee en langage naturel.",
        },
        {
          question: "Qu'est-ce qui différencié Cursor Tab d'une complétion classique ?",
          options: ["Il est plus rapide", "Il prédit des edits multi-lignes contextuels", "Il ne fonctionne qu'en Python", "Il nécessite une connexion internet"],
          correctIndex: 1,
          explanation: "Cursor Tab anticipe vos intentions en analysant votre pattern d'edition et propose des modifications multi-lignes contextuelles, pas juste la ligne suivante.",
        },
        {
          question: "A quoi servent les fichiers .cursorrules ?",
          options: ["Configurer les raccourcis clavier", "Personnaliser le comportement de l'IA", "Définir les règles de linting", "Gérer les permissions Git"],
          correctIndex: 1,
          explanation: "Les .cursorrules permettent de définir votre stack, vos conventions et préférences pour que l'IA de Cursor génère du code cohérent avec votre projet.",
        },
      ],
    },
    {
      number: 4,
      title: "Claude Code : Coder en Conversation",
      description: "Utiliser Claude Code comme agent de développement conversationnel dans le terminal.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Claude Code : L'Agent Dev dans Votre Terminal" },
        { type: "paragraph", content: "Claude Code est un outil CLI développé par Anthropic qui transformé votre terminal en un environnement de développement conversationnel. Contrairement aux IDE IA, Claude Code fonctionne directement dans le terminal, lit et modifié vos fichiers, exécute des commandes, et itere jusqu'à ce que la tâche soit complète." },
        { type: "paragraph", content: "Propulse par Claude Opus 4.6 avec 1 million de tokens de contexte, Claude Code peut comprendre des codebases entiers, planifier des modifications complexes, et les exécuter de manière autonome avec une précision remarquable." },
        { type: "subheading", content: "Installation et Premiers Pas" },
        { type: "paragraph", content: "Installez via npm : npm install -g @anthropic-ai/claude-code. Lancez-le dans votre projet avec la commande 'claude'. Il indexe automatiquement votre codebase et commence une session interactive." },
        { type: "heading", content: "Cas d'Usage Puissants" },
        { type: "paragraph", content: "Claude Code excelle dans les tâches complexes multi-fichiers : refactoring a grande échelle, migration de frameworks, implementation de features complètes, debugging de problèmes subtils. Il peut lire des logs d'erreur, analyser le contexte, et proposer des corrections." },
        { type: "prompt-example", prompt: "Refactore le système d'authentification pour utiliser JWT au lieu des sessions. Mets à jour les routes, le middleware, et les tests.", result: "Claude Code analyse le code existant, planifie les modifications, edite les fichiers un par un, exécute les tests, et corrige les erreurs jusqu'à ce que tout passe." },
        { type: "tip", content: "Utilisez un fichier CLAUDE.md a la racine de votre projet pour donner du contexte permanent a Claude Code : stack, conventions, commandes utiles, architecture." },
        { type: "key-point", content: "La force de Claude Code est sa capacité a maintenir une tâche pendant des heures (jusqu'à 14,5h avec Opus 4.6), ce qui le rend idéal pour les refactorings massifs et les migrations." },
        { type: "video", videoId: { fr: "oeli5xkFZJo", en: "JhM7PWCv2EY" },
      videoDurationMinutes: 14, label: "Claude Code : présentation et demo" },
        { type: "diagram", label: "Workflow Claude Code", flow: "vertical", nodes: [
          { label: "Commande en langage naturel", sub: "Decrivez la tâche a accomplir", color: "blue" },
          { label: "Analyse du codebase", sub: "Lecture et compréhension des fichiers", color: "purple" },
          { label: "Plan et exécution", sub: "Modifications multi-fichiers", color: "emerald" },
          { label: "Vérification", sub: "Tests, lint, validation", color: "amber" },
        ]},
        { type: "summary", items: [
          "Claude Code est un agent dev CLI propulse par Claude Opus 4.6",
          "1 million de tokens de contexte pour comprendre des codebases entiers",
          "Idéal pour les tâches complexes multi-fichiers et les refactorings",
          "CLAUDE.md donne du contexte permanent au projet",
          "Jusqu'à 14,5h d'autonomie pour les tâches longues",
        ]},
      ],
      quiz: [
        {
          question: "Quel modèle propulse Claude Code ?",
          options: ["GPT-5.4", "Claude Sonnet 4.6", "Claude Opus 4.6", "Gemini 3.1"],
          correctIndex: 2,
          explanation: "Claude Code est propulse par Claude Opus 4.6 d'Anthropic, avec 1 million de tokens de contexte et un horizon de tâche de 14,5 heures.",
        },
        {
          question: "Ou fonctionne Claude Code ?",
          options: ["Dans un navigateur web", "Dans VS Code uniquement", "Dans le terminal (CLI)", "Dans une app mobile"],
          correctIndex: 2,
          explanation: "Claude Code est un outil CLI (Command Line Interface) qui fonctionne directement dans votre terminal, lisant et modifiant vos fichiers locaux.",
        },
        {
          question: "A quoi sert le fichier CLAUDE.md ?",
          options: ["Documentation utilisateur", "Contexte permanent pour Claude Code", "Configuration du linter", "Changelog du projet"],
          correctIndex: 1,
          explanation: "Le fichier CLAUDE.md a la racine du projet fournit du contexte permanent a Claude Code : stack technique, conventions, commandes utiles, architecture.",
        },
        {
          question: "Pour quel type de tâche Claude Code est-il particulièrement adapte ?",
          options: ["Completion de lignes simples", "Refactoring multi-fichiers complexes", "Design d'interfaces", "Gestion de base de données"],
          correctIndex: 1,
          explanation: "Claude Code excelle dans les tâches complexes multi-fichiers comme les refactorings massifs, les migrations de framework, et l'implementation de features complètes.",
        },
      ],
    },
    {
      number: 5,
      title: "Bolt et v0 : Générer des Apps Completes",
      description: "Créer des applications fonctionnelles en quelques minutes avec Bolt et v0.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "La Génération d'Applications Completes" },
        { type: "paragraph", content: "Bolt (StackBlitz) et v0 (Vercel) représentent une nouvelle catégorie d'outils : les générateurs d'applications complètes. Decrivez ce que vous voulez en langage naturel, et l'IA génère une application fonctionnelle avec frontend, backend, et base de données." },
        { type: "subheading", content: "v0 par Vercel" },
        { type: "paragraph", content: "v0 se spécialisé dans la génération de composants UI et de pages React/Next.js. Il produit du code propre avec shadcn/ui et Tailwind CSS. Idéal pour prototyper rapidement des interfaces, des landing pages, et des dashboards." },
        { type: "paragraph", content: "Decrivez votre interface et v0 génère le code complet. Vous pouvez iterer en conversation : 'Ajoute un mode sombre', 'Change la couleur primaire en bleu', 'Ajoute un tableau de données'. Chaque iteration est instantanée." },
        { type: "subheading", content: "Bolt par StackBlitz" },
        { type: "paragraph", content: "Bolt va plus loin en generant des applications full-stack complètes dans un environnement WebContainer. Il crée le frontend, le backend, la base de données, l'authentification — le tout en quelques minutes. L'app tourne directement dans le navigateur." },
        { type: "callout", content: "Bolt et v0 sont parfaits pour le prototypage rapide et les MVPs. Pour des applications de production complexes, combinez-les avec Cursor ou Claude Code pour le peaufinage." },
        { type: "prompt-example", prompt: "Cree un dashboard de gestion de tâches avec authentification, drag-and-drop Kanban, et mode sombre", result: "Bolt génère une app Next.js complète avec auth, base de données SQLite, board Kanban fonctionnel, et toggle dark mode — prêt en 3 minutes." },
        { type: "video", videoId: { fr: "18oAWvzjmTw", en: "ocMOZpuAMw4" },
      videoDurationMinutes: 15, label: "Bolt et v0 : créer des apps avec l'IA" },
        { type: "diagram", label: "Bolt vs v0 : Comparatif", flow: "horizontal", nodes: [
          { label: "v0 (Vercel)", sub: "UI/composants React + Next.js", color: "blue" },
          { label: "Bolt (StackBlitz)", sub: "Apps full-stack complètes", color: "purple" },
          { label: "Lovable", sub: "Apps avec design premium", color: "pink" },
          { label: "Replit Agent", sub: "Déploiement instantané", color: "emerald" },
        ]},
        { type: "summary", items: [
          "v0 excelle dans la génération de composants UI React/Next.js",
          "Bolt génère des apps full-stack complètes en quelques minutes",
          "Idéal pour le prototypage rapide et les MVPs",
          "Iteration conversationnelle pour affiner le résultat",
          "Combinez avec Cursor/Claude Code pour le peaufinage production",
        ]},
      ],
      quiz: [
        {
          question: "Quelle entreprise développé v0 ?",
          options: ["StackBlitz", "Vercel", "Anthropic", "GitHub"],
          correctIndex: 1,
          explanation: "v0 est développé par Vercel, la société derrière Next.js. Il se spécialisé dans la génération de composants UI React/Next.js.",
        },
        {
          question: "Que génère Bolt par rapport à v0 ?",
          options: ["Uniquement du CSS", "Des composants UI", "Des applications full-stack complètes", "Uniquement du backend"],
          correctIndex: 2,
          explanation: "Bolt génère des applications full-stack complètes : frontend, backend, base de données et authentification, le tout dans un environnement WebContainer.",
        },
        {
          question: "Pour quel usage Bolt et v0 sont-ils idéaux ?",
          options: ["Applications enterprise a grande échelle", "Prototypage rapide et MVPs", "Maintenance de code legacy", "Administration de serveurs"],
          correctIndex: 1,
          explanation: "Bolt et v0 sont parfaits pour le prototypage rapide et les MVPs. Pour des applications de production complexes, il faut les combiner avec d'autres outils.",
        },
        {
          question: "Quel framework UI v0 utilise-t-il par défaut ?",
          options: ["Bootstrap", "Material UI", "shadcn/ui + Tailwind CSS", "Chakra UI"],
          correctIndex: 2,
          explanation: "v0 génère du code avec shadcn/ui et Tailwind CSS, produisant des composants propres, accessibles et facilement personnalisables.",
        },
      ],
    },
    {
      number: 6,
      title: "Debugger avec l'IA",
      description: "Techniques pour trouver et corriger les bugs plus rapidement avec l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Le Debugging Assiste par l'IA" },
        { type: "paragraph", content: "Le debugging est l'une des tâches ou l'IA brille le plus. Copier un message d'erreur dans ChatGPT ou Claude et obtenir une explication claire en quelques secondes — c'est devenu un reflexe pour la majorité des développeurs. Mais l'IA va bien plus loin que la simple explication d'erreurs." },
        { type: "paragraph", content: "Les outils comme Cursor, Claude Code et Copilot Chat peuvent analyser le contexte complet de votre code, identifier la cause racine d'un bug, et proposer un correctif précis. Ils comprennent les stack traces, les logs d'erreur, et les relations entre fichiers." },
        { type: "heading", content: "Techniques de Debugging avec l'IA" },
        { type: "subheading", content: "1. Le Copier-Coller Contextuel" },
        { type: "paragraph", content: "Ne collez pas juste l'erreur — fournissez le contexte : le code concerne, ce que vous essayiez de faire, le comportement attendu vs observe. Plus le contexte est riche, plus la solution sera précise." },
        { type: "subheading", content: "2. L'Analyse de Stack Trace" },
        { type: "paragraph", content: "Collez la stack trace complète dans le chat IA. Les LLM sont excellents pour remonter la chaîne d'appels, identifier la ligne problematique, et expliquer pourquoi l'erreur survient dans ce contexte précis." },
        { type: "prompt-example", prompt: "TypeError: Cannot read properties of undefined (reading 'map')\n  at UserList (UserList.tsx:15)\n  at renderWithHooks (react-dom.js:1234)\n\nVoici le code de UserList.tsx : [code]", result: "L'IA identifie que 'users' est undefined au premier rendu, recommandé un optional chaining (users?.map) ou un état initial vide, et expliqué le cycle de vie React." },
        { type: "tip", content: "Pour les bugs complexes, utilisez Claude Code avec son million de tokens de contexte. Il peut analyser des dizaines de fichiers simultanement pour trouver la cause racine." },
        { type: "key-point", content: "L'IA excelle en debugging parce qu'elle a \"vu\" des millions de bugs similaires dans ses données d'entraînement. Elle reconnait les patterns d'erreur instantanément." },
        { type: "video", videoId: { fr: "Xagh-g3zyuw", en: "n0NlxUyA7FI" },
      videoDurationMinutes: 11, label: "Debugger 10x plus vite avec l'IA" },
        { type: "diagram", label: "Workflow de Debugging IA", flow: "vertical", nodes: [
          { label: "Erreur détectée", sub: "Message d'erreur ou comportement inattendu", color: "pink" },
          { label: "Contexte enrichi", sub: "Code + stack trace + comportement attendu", color: "blue" },
          { label: "Analyse IA", sub: "Identification de la cause racine", color: "purple" },
          { label: "Correction et vérification", sub: "Correctif appliqué et testé", color: "emerald" },
        ]},
        { type: "summary", items: [
          "L'IA est exceptionnelle pour le debugging grâce aux patterns reconnus",
          "Fournissez toujours du contexte riche, pas juste le message d'erreur",
          "Les stack traces sont très bien analysées par les LLM",
          "Claude Code peut analyser des dizaines de fichiers pour trouver la cause",
          "Le debugging IA réduit le temps de résolution de 60-80%",
        ]},
      ],
      quiz: [
        {
          question: "Pourquoi l'IA est-elle efficace pour le debugging ?",
          options: ["Elle exécute le code plus vite", "Elle a vu des millions de bugs similaires dans ses données", "Elle crée des tests automatiquement", "Elle élimine les bugs avant l'exécution"],
          correctIndex: 1,
          explanation: "Les LLM ont été entraînés sur des millions de codes et de messages d'erreur. Ils reconnaissent les patterns de bugs instantanément.",
        },
        {
          question: "Que faut-il fournir à l'IA pour un debugging efficace ?",
          options: ["Juste le message d'erreur", "L'erreur + le code + le contexte + le comportement attendu", "Uniquement le nom du fichier", "Le code source complet du projet"],
          correctIndex: 1,
          explanation: "Plus le contexte est riche (erreur, code, contexte, comportement attendu vs observe), plus la solution proposée sera précise et pertinente.",
        },
        {
          question: "Quel outil est idéal pour debugger des problèmes multi-fichiers ?",
          options: ["ChatGPT web", "Claude Code", "Un debugger classique", "Stack Overflow"],
          correctIndex: 1,
          explanation: "Claude Code avec son million de tokens de contexte peut analyser des dizaines de fichiers simultanement pour trouver la cause racine de bugs complexes.",
        },
        {
          question: "De combien le debugging IA réduit-il le temps de résolution ?",
          options: ["10-20%", "30-40%", "60-80%", "100%"],
          correctIndex: 2,
          explanation: "Le debugging assisté par l'IA réduit le temps de résolution de 60 à 80% en moyenne, en identifiant rapidement les causes et en proposant des correctifs.",
        },
      ],
    },
    {
      number: 7,
      title: "Code Review Automatise",
      description: "Utiliser l'IA pour des reviews de code plus rapides et plus complètes.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "La Code Review Augmentee par l'IA" },
        { type: "paragraph", content: "La code review est essentielle pour la qualité du code, mais elle est chronophage. L'IA transforme ce processus en detectant automatiquement les bugs potentiels, les failles de sécurité, les problèmes de performance, et les violations de conventions — avant même que votre collègue ne regarde le code." },
        { type: "paragraph", content: "En 2026, la plupart des équipes combinent review humaine et review IA. L'IA gère les aspects mécaniques (style, conventions, bugs évidents) tandis que les humains se concentrent sur l'architecture, la logique métier et la lisibilite." },
        { type: "subheading", content: "Outils de Review IA" },
        { type: "paragraph", content: "GitHub Copilot Review commente directement vos pull requests. CodeRabbit analyse chaque changement et produit un rapport détaillé. Cursor et Claude Code peuvent reviewer du code en conversation avec le contexte complet du projet." },
        { type: "heading", content: "Comment Faire une Bonne Review IA" },
        { type: "paragraph", content: "Demandez à l'IA de vérifier des aspects spécifiques : sécurité, performance, gestion d'erreurs, edge cases. Ne vous contentez pas d'un 'review ce code'. Plus votre demande est précise, plus la review sera utile." },
        { type: "prompt-example", prompt: "Review ce composant React pour : 1) fuites mémoire potentielles 2) re-renders inutiles 3) accessibilité 4) gestion d'erreurs", result: "L'IA identifie un useEffect sans cleanup, un objet inline recreee à chaque render, un bouton sans aria-label, et une absence de error boundary." },
        { type: "callout", content: "La review IA ne remplace pas la review humaine. Elle la complement en attrapant les problèmes techniques que les humains peuvent manquer par fatigue ou familiarite avec le code." },
        { type: "video", videoId: { fr: "Xagh-g3zyuw", en: "Fi3AJZZregI" },
      videoDurationMinutes: 15, label: "Code review automatisée avec l'IA" },
        { type: "diagram", label: "Review IA vs Review Humaine", flow: "horizontal", nodes: [
          { label: "Review IA", sub: "Bugs, sécurité, conventions, performance", color: "blue" },
          { label: "Review Humaine", sub: "Architecture, logique métier, lisibilite", color: "purple" },
          { label: "Résultat", sub: "Code de haute qualité", color: "emerald" },
        ]},
        { type: "summary", items: [
          "L'IA détecte bugs, failles de sécurité et problèmes de performance",
          "Combinez review IA (aspects mécaniques) et humaine (logique métier)",
          "Outils : Copilot Review, CodeRabbit, Cursor, Claude Code",
          "Soyez spécifique dans vos demandes de review",
          "La review IA complement la review humaine, elle ne la remplace pas",
        ]},
      ],
      quiz: [
        {
          question: "Quel aspect de la review l'IA gère-t-elle le mieux ?",
          options: ["La logique métier", "L'architecture globale", "Les bugs, sécurité et conventions", "L'expérience utilisateur"],
          correctIndex: 2,
          explanation: "L'IA excelle dans la détection des aspects mécaniques : bugs potentiels, failles de sécurité, violations de conventions et problèmes de performance.",
        },
        {
          question: "Quel outil commente directement les pull requests sur GitHub ?",
          options: ["Cursor", "Claude Code", "Copilot Review", "ChatGPT"],
          correctIndex: 2,
          explanation: "GitHub Copilot Review analyse et commente directement vos pull requests sur GitHub, intégré dans le workflow de review existant.",
        },
        {
          question: "Comment obtenir une meilleure review IA ?",
          options: ["Demander juste 'review ce code'", "Specifier les aspects a vérifier", "Envoyer le moins de code possible", "Utiliser plusieurs outils en même temps"],
          correctIndex: 1,
          explanation: "Plus votre demande est précise (sécurité, performance, gestion d'erreurs, accessibilité), plus la review IA sera pertinente et actionnable.",
        },
        {
          question: "Pourquoi la review humaine reste-t-elle nécessaire ?",
          options: ["L'IA fait trop d'erreurs", "L'IA ne comprend pas la logique métier et l'architecture", "L'IA est trop lente", "L'IA ne supporte pas tous les langages"],
          correctIndex: 1,
          explanation: "La review humaine est essentielle pour évaluer l'architecture, la logique métier, la lisibilite et les décisions de design que l'IA ne peut pas juger.",
        },
      ],
    },
    {
      number: 8,
      title: "Tests Automatises avec l'IA",
      description: "Générer des tests unitaires, d'intégration et E2E avec l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "L'IA Révolutionne le Testing" },
        { type: "paragraph", content: "Écrire des tests est souvent la partie la moins appréciée du développement. L'IA change la donne en generant automatiquement des tests pertinents, couvrant les cas limites auxquels vous n'auriez pas pense. Le résultat : une meilleure couverture avec moins d'effort." },
        { type: "paragraph", content: "Les LLM sont particulièrement efficaces pour générer des tests unitaires parce qu'ils comprennent l'intention du code et peuvent anticiper les edge cases. Ils connaissent les frameworks de test (Jest, Vitest, Pytest, JUnit) et generent du code idiomatique." },
        { type: "subheading", content: "Tests Unitaires" },
        { type: "paragraph", content: "Donnez votre fonction à l'IA et demandez-lui de générer des tests couvrant tous les cas : happy path, erreurs, edge cases, valeurs limites. L'IA peut produire 10 à 20 tests en quelques secondes là où un dev en ecrirait 3 à 5." },
        { type: "subheading", content: "Tests E2E avec IA" },
        { type: "paragraph", content: "Pour les tests end-to-end, l'IA peut générer des scénarios Playwright ou Cypress à partir de descriptions en langage naturel. Decrivez le parcours utilisateur et l'IA génère le test complet avec les selecteurs, les assertions et les attentes." },
        { type: "prompt-example", prompt: "Genere des tests Vitest pour cette fonction de panier d'achat : ajout, suppression, calcul total, codes promo, limites de stock", result: "L'IA génère 15 tests couvrant : ajout simple, ajout multiple, suppression, total correct, code promo validé/invalide/expire, stock insuffisant, panier vide, quantité zéro." },
        { type: "tip", content: "Utilisez l'approche TDD avec l'IA : demandez-lui de générer les tests AVANT d'écrire le code. Puis demandez-lui d'implementer le code qui fait passer les tests." },
        { type: "video", videoId: { fr: "oeli5xkFZJo", en: "JhM7PWCv2EY" },
      videoDurationMinutes: 14, label: "Tests automatises avec l'IA" },
        { type: "diagram", label: "Types de Tests Generes par l'IA", flow: "horizontal", nodes: [
          { label: "Tests unitaires", sub: "Fonctions et méthodes isolees", color: "blue" },
          { label: "Tests d'intégration", sub: "Interactions entre modules", color: "purple" },
          { label: "Tests E2E", sub: "Parcours utilisateur complets", color: "emerald" },
        ]},
        { type: "summary", items: [
          "L'IA génère des tests pertinents couvrant les edge cases",
          "10 à 20 tests en secondes vs 3 à 5 manuellement",
          "Supporte Jest, Vitest, Pytest, Playwright, Cypress",
          "TDD avec l'IA : tests d'abord, implementation ensuite",
          "Toujours vérifier et ajuster les tests générés",
        ]},
      ],
      quiz: [
        {
          question: "Pourquoi l'IA est-elle efficace pour générer des tests ?",
          options: ["Elle exécute les tests plus vite", "Elle comprend l'intention du code et anticipe les edge cases", "Elle remplace les frameworks de test", "Elle élimine le besoin de CI/CD"],
          correctIndex: 1,
          explanation: "Les LLM comprennent l'intention du code et anticipent les cas limites auxquels un développeur n'aurait pas pense, produisant des tests plus complets.",
        },
        {
          question: "Combien de tests l'IA peut-elle générer en quelques secondes ?",
          options: ["1 à 2", "3 à 5", "10 à 20", "100+"],
          correctIndex: 2,
          explanation: "L'IA peut générer 10 à 20 tests pertinents en quelques secondes, couvrant le happy path, les erreurs, les edge cases et les valeurs limites.",
        },
        {
          question: "Qu'est-ce que le TDD avec l'IA ?",
          options: ["Tester en production", "Générer les tests avant le code, puis implementer", "Supprimer les tests existants", "Tester uniquement le frontend"],
          correctIndex: 1,
          explanation: "Le TDD (Test-Driven Development) avec l'IA consiste à générer les tests d'abord, puis demander à l'IA d'implementer le code qui fait passer ces tests.",
        },
        {
          question: "Pour les tests E2E, quel outil l'IA peut-elle cibler ?",
          options: ["Jest uniquement", "Playwright et Cypress", "Selenium uniquement", "Aucun outil E2E"],
          correctIndex: 1,
          explanation: "L'IA peut générer des tests E2E pour Playwright et Cypress à partir de descriptions en langage naturel des parcours utilisateur.",
        },
      ],
    },
    {
      number: 9,
      title: "Refactoring et Optimisation",
      description: "Améliorer la qualité et les performances du code avec l'assistance IA.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Refactoring Assiste par l'IA" },
        { type: "paragraph", content: "Le refactoring — restructurer du code sans changer son comportement — est une tâche ou l'IA excelle. Elle identifie les code smells, propose des patterns plus propres, et peut exécuter des refactorings massifs à travers des dizaines de fichiers en quelques minutes." },
        { type: "paragraph", content: "En 2026, les outils comme Cursor Agent et Claude Code peuvent analyser un codebase complet, identifier les dettes techniques, et proposer un plan de refactoring priorise." },
        { type: "heading", content: "Techniques de Refactoring IA" },
        { type: "paragraph", content: "Extraction de fonctions et composants, élimination de code dupliqué (DRY), simplification de conditions complexes, renommage sémantique, conversion de callbacks en async/await, migration de class components vers hooks React." },
        { type: "subheading", content: "Optimisation de Performance" },
        { type: "paragraph", content: "L'IA peut analyser votre code pour identifier les goulots d'etranglement : requêtes N+1, re-renders inutiles, imports lourds, boucles inefficaces. Elle propose des solutions concrètes : memoisation, lazy loading, pagination, indexation." },
        { type: "prompt-example", prompt: "Identifie les problèmes de performance dans ce composant React et optimisé-le", result: "L'IA détecte : un useMemo manquant, un mapping recreee à chaque render, un composant enfant qui re-render inutilement. Elle ajoute useMemo, useCallback et React.memo." },
        { type: "key-point", content: "Le refactoring IA est plus sur quand il est accompagné de tests. Generez les tests d'abord, puis refactorez — les tests garantissent que le comportement ne changé pas." },
        { type: "video", videoId: { fr: "18oAWvzjmTw", en: "ocMOZpuAMw4" },
      videoDurationMinutes: 15, label: "Refactoring et optimisation avec l'IA" },
        { type: "diagram", label: "Processus de Refactoring IA", flow: "vertical", nodes: [
          { label: "Analyse du code", sub: "Détection des code smells et dettes", color: "blue" },
          { label: "Génération de tests", sub: "Sécuriser le comportement existant", color: "purple" },
          { label: "Refactoring", sub: "Restructuration automatisée", color: "emerald" },
          { label: "Vérification", sub: "Tous les tests passent", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA identifie code smells et dettes techniques automatiquement",
          "Refactoring massif multi-fichiers en quelques minutes",
          "Optimisation : memoisation, lazy loading, requêtes N+1",
          "Toujours sécuriser avec des tests avant de refactorer",
          "Cursor Agent et Claude Code excellent dans ce domaine",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que le refactoring ?",
          options: ["Ajouter de nouvelles fonctionnalités", "Restructurer le code sans changer son comportement", "Supprimer du code", "Changer le langage de programmation"],
          correctIndex: 1,
          explanation: "Le refactoring consiste à restructurer le code pour le rendre plus propre, lisible et maintenable, sans changer son comportement extérieur.",
        },
        {
          question: "Pourquoi faut-il des tests avant de refactorer ?",
          options: ["Pour ralentir le processus", "Pour garantir que le comportement ne changé pas", "Pour satisfaire le linter", "Pour documenter le code"],
          correctIndex: 1,
          explanation: "Les tests servent de filet de sécurité : ils garantissent que le refactoring n'a pas accidentellement changé le comportement du code.",
        },
        {
          question: "Quel problème de performance l'IA peut-elle détecter ?",
          options: ["Fautes d'orthographe", "Requêtes N+1 et re-renders inutiles", "Mauvais noms de variables", "Commentaires manquants"],
          correctIndex: 1,
          explanation: "L'IA détecte les goulots d'etranglement comme les requêtes N+1, les re-renders inutiles, les imports lourds et les boucles inefficaces.",
        },
        {
          question: "Quel outil peut refactorer des dizaines de fichiers simultanement ?",
          options: ["Un linter", "Claude Code et Cursor Agent", "ESLint", "Prettier"],
          correctIndex: 1,
          explanation: "Claude Code et Cursor Agent peuvent analyser et modifier des dizaines de fichiers simultanement pour des refactorings massifs à travers le codebase.",
        },
      ],
    },
    {
      number: 10,
      title: "Frontend avec l'IA (React, Next.js)",
      description: "Construire des interfaces modernes avec React et Next.js assistés par l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Développement Frontend Augmente par l'IA" },
        { type: "paragraph", content: "Le frontend est le domaine ou l'IA a le plus d'impact visible. De la génération de composants UI au styling, du responsive design à l'accessibilité, l'IA accélère chaque aspect du développement d'interfaces modernes." },
        { type: "paragraph", content: "React et Next.js sont les frameworks les mieux supportes par les outils IA. v0, Cursor, Copilot et Claude Code produisent tous du code React/Next.js de haute qualité avec Tailwind CSS et les derniers patterns (Server Components, App Router)." },
        { type: "subheading", content: "Génération de Composants" },
        { type: "paragraph", content: "Decrivez un composant en langage naturel et l'IA le génère instantanément : navbar responsive, modal avec animations, formulaire avec validation, tableau de données avec tri et filtrage. Le code respecte les bonnes pratiques : accessibilité, responsive, TypeScript." },
        { type: "subheading", content: "Design System avec l'IA" },
        { type: "paragraph", content: "L'IA peut générer un design system complet : tokens de couleur, typographie, espacements, variantes de composants. shadcn/ui + Tailwind est la combinaison préférée car v0 et Cursor la maitrisent parfaitement." },
        { type: "tip", content: "Commencez par générer un composant de base avec v0, puis peaufinez-le dans Cursor. Cette approche combiné la rapidité de v0 avec la précision de Cursor." },
        { type: "prompt-example", prompt: "Cree un composant DataTable React avec tri par colonne, pagination, recherche, et sélection multiple. Utilise shadcn/ui et Tailwind.", result: "L'IA génère un DataTable complet avec hooks personnalisés, types TypeScript, accessibilité clavier, et responsive design." },
        { type: "video", videoId: { fr: "Xagh-g3zyuw", en: "n0NlxUyA7FI" },
      videoDurationMinutes: 11, label: "Frontend React/Next.js avec l'IA" },
        { type: "diagram", label: "Workflow Frontend IA", flow: "horizontal", nodes: [
          { label: "v0", sub: "Génération rapide de composants", color: "blue" },
          { label: "Cursor", sub: "Edition et peaufinage", color: "purple" },
          { label: "Copilot", sub: "Completion au quotidien", color: "emerald" },
          { label: "Claude Code", sub: "Refactoring et features complexes", color: "amber" },
        ]},
        { type: "summary", items: [
          "React/Next.js sont les frameworks les mieux supportes par l'IA",
          "Génération de composants complets en langage naturel",
          "shadcn/ui + Tailwind = combinaison idéale pour l'IA",
          "v0 pour générer, Cursor pour peaufiner",
          "Accessibilité et responsive générés automatiquement",
        ]},
      ],
      quiz: [
        {
          question: "Quel framework est le mieux supporte par les outils de dev IA ?",
          options: ["Angular", "Vue.js", "React/Next.js", "Svelte"],
          correctIndex: 2,
          explanation: "React et Next.js sont les frameworks les mieux supportes par v0, Cursor, Copilot et Claude Code grâce à leur popularite dans les données d'entraînement.",
        },
        {
          question: "Quelle combinaison CSS est préférée par les outils IA ?",
          options: ["Bootstrap + CSS", "Material UI + Émotion", "shadcn/ui + Tailwind CSS", "Styled Components"],
          correctIndex: 2,
          explanation: "shadcn/ui + Tailwind CSS est la combinaison préférée car v0 et Cursor la maitrisent parfaitement, produisant du code propre et personnalisable.",
        },
        {
          question: "Quelle approche combiné rapidité et précision ?",
          options: ["Tout coder a la main", "Générer avec v0 puis peaufiner dans Cursor", "Utiliser uniquement ChatGPT", "Copier du code de Stack Overflow"],
          correctIndex: 1,
          explanation: "Générer un composant de base avec v0 (rapidité) puis le peaufiner dans Cursor (précision contextuelle) est l'approche optimale.",
        },
        {
          question: "Quels aspects l'IA gère-t-elle dans le frontend ?",
          options: ["Uniquement le style", "Composants, accessibilité, responsive, TypeScript", "Uniquement le HTML", "Uniquement les animations"],
          correctIndex: 1,
          explanation: "L'IA génère des composants complets avec accessibilité, responsive design, types TypeScript et bonnes pratiques — pas juste le visuel.",
        },
      ],
    },
    {
      number: 11,
      title: "Backend et APIs avec l'IA",
      description: "Créer des APIs robustes et des services backend avec l'assistance de l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Backend Development Assiste par l'IA" },
        { type: "paragraph", content: "L'IA transforme le développement backend : génération d'APIs REST et GraphQL, schémas de base de données, middleware d'authentification, validation de données, gestion d'erreurs — le tout génère à partir de descriptions en langage naturel." },
        { type: "paragraph", content: "Les LLM maitrisent les frameworks backend populaires : Express, Fastify, Django, FastAPI, Spring Boot, Rails. Ils generent du code idiomatique qui respecte les conventions de chaque écosystème." },
        { type: "subheading", content: "Génération d'APIs" },
        { type: "paragraph", content: "Decrivez vos endpoints et l'IA génère le code complet : routes, controllers, validation des inputs, gestion d'erreurs, documentation OpenAPI. Elle peut générer un CRUD complet en quelques secondes." },
        { type: "subheading", content: "Authentification et Sécurité" },
        { type: "paragraph", content: "L'IA génère des systèmes d'authentification complets : JWT, OAuth2, sessions. Elle connaît les bonnes pratiques : hashage de mots de passe (bcrypt), protection CSRF, rate limiting, validation d'inputs, headers de sécurité." },
        { type: "prompt-example", prompt: "Cree une API REST Node.js/Express pour un système de reservations avec auth JWT, validation Zod, et pagination", result: "L'IA génère : routes CRUD, middleware JWT, schémas Zod, pagination cursor-based, gestion d'erreurs centralisee, et types TypeScript." },
        { type: "callout", content: "Attention : toujours vérifier le code de sécurité généré par l'IA. Les LLM peuvent introduire des vulnérabilités subtiles (injection SQL, XSS, IDOR). Un audit de sécurité humain reste indispensable." },
        { type: "key-point", content: "L'IA est excellente pour le boilerplate backend, mais les décisions d'architecture (microservices vs monolithe, choix de base de données, stratégies de cache) nécessitent toujours une expertise humaine." },
        { type: "video", videoId: { fr: "Xagh-g3zyuw", en: "Fi3AJZZregI" },
      videoDurationMinutes: 15, label: "APIs et backend avec l'IA" },
        { type: "diagram", label: "Génération Backend avec l'IA", flow: "horizontal", nodes: [
          { label: "API REST/GraphQL", sub: "Routes, controllers, validation", color: "blue" },
          { label: "Authentification", sub: "JWT, OAuth2, sessions", color: "purple" },
          { label: "Base de données", sub: "Schémas, migrations, queries", color: "emerald" },
          { label: "Déploiement", sub: "Docker, CI/CD, monitoring", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA génère des APIs complètes à partir de descriptions naturelles",
          "Support des frameworks majeurs : Express, Django, FastAPI, Spring",
          "Authentification, validation et sécurité générées automatiquement",
          "Toujours auditer le code de sécurité généré par l'IA",
          "Les décisions d'architecture restent humaines",
        ]},
      ],
      quiz: [
        {
          question: "Que peut générer l'IA pour le backend ?",
          options: ["Uniquement des routes", "APIs complètes avec auth, validation et gestion d'erreurs", "Uniquement la documentation", "Uniquement les schémas de base de données"],
          correctIndex: 1,
          explanation: "L'IA génère des APIs complètes incluant routes, controllers, authentification, validation, gestion d'erreurs, et documentation OpenAPI.",
        },
        {
          question: "Pourquoi faut-il auditer le code de sécurité généré par l'IA ?",
          options: ["L'IA génère du code lent", "L'IA peut introduire des vulnérabilités subtiles", "L'IA ne supporte pas HTTPS", "L'IA ne comprend pas les bases de données"],
          correctIndex: 1,
          explanation: "Les LLM peuvent introduire des vulnérabilités subtiles comme des injections SQL, XSS ou IDOR. Un audit de sécurité humain reste indispensable.",
        },
        {
          question: "Quel aspect du backend reste une décision humaine ?",
          options: ["L'écriture des routes", "L'architecture (microservices vs monolithe)", "La validation des inputs", "La gestion d'erreurs"],
          correctIndex: 1,
          explanation: "Les décisions d'architecture comme le choix entre microservices et monolithe, le choix de base de données, et les stratégies de cache nécessitent une expertise humaine.",
        },
        {
          question: "Quel outil de validation l'IA utilise-t-elle souvent avec Node.js ?",
          options: ["jQuery Validate", "Zod", "HTML5 Validation", "Regex uniquement"],
          correctIndex: 1,
          explanation: "Zod est la bibliotheque de validation TypeScript-first la plus populaire en 2026, et les LLM la maitrisent parfaitement pour générer des schémas de validation.",
        },
      ],
    },
    {
      number: 12,
      title: "Bases de Données et SQL avec l'IA",
      description: "Concevoir des schémas, écrire des requêtes SQL et optimiser avec l'IA.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "SQL et Bases de Données Assistes par l'IA" },
        { type: "paragraph", content: "L'IA transforme le travail avec les bases de données. De la conception de schémas à l'écriture de requêtes complexes, de l'optimisation de performance a la migration de données, les LLM sont devenus des assistants SQL indispensables." },
        { type: "paragraph", content: "Les développeurs qui ne maitrisent pas SQL en profondeur peuvent maintenant écrire des requêtes complexes en decrivant ce qu'ils veulent en langage naturel. Et les experts SQL utilisent l'IA pour accélérer l'écriture de requêtes et détecter les problèmes d'optimisation." },
        { type: "subheading", content: "Conception de Schémas" },
        { type: "paragraph", content: "Decrivez votre modèle de données en langage naturel et l'IA génère le schéma complet : tables, colonnes, types, contraintes, index, relations. Elle connaît les bonnes pratiques de normalisation et suggère des optimisations." },
        { type: "subheading", content: "Requêtes Complexes" },
        { type: "paragraph", content: "Joins multiples, sous-requêtes, window functions, CTEs (Common Table Expressions), requêtes recursives — l'IA génère tout cela à partir de descriptions naturelles. Elle expliqué aussi la logique de chaque requête générée." },
        { type: "prompt-example", prompt: "Ecris une requête SQL qui retourné le top 10 des produits les plus vendus par catégorie pour le mois dernier, avec le total des ventes et la variation par rapport au mois précédent", result: "L'IA génère une CTE avec window functions (LAG, ROW_NUMBER, SUM) qui calcule les ventes mensuelles, la variation, et le classement par catégorie." },
        { type: "tip", content: "Utilisez Claude Code pour analyser les plans d'exécution (EXPLAIN ANALYZE) et identifier les index manquants. Il peut optimiser des requêtes lentes en quelques secondes." },
        { type: "video", videoId: { fr: "oeli5xkFZJo", en: "JhM7PWCv2EY" },
      videoDurationMinutes: 14, label: "SQL et bases de données avec l'IA" },
        { type: "diagram", label: "Tâches SQL Assistees par l'IA", flow: "horizontal", nodes: [
          { label: "Conception de schéma", sub: "Tables, index, relations", color: "blue" },
          { label: "Requêtes complexes", sub: "Joins, CTEs, window functions", color: "purple" },
          { label: "Optimisation", sub: "Index, plans d'exécution", color: "emerald" },
          { label: "Migration", sub: "Transformation de données", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA génère des schémas et des requêtes SQL à partir de langage naturel",
          "Requêtes complexes (CTEs, window functions) accessibles à tous",
          "Analyse de plans d'exécution et optimisation automatisée",
          "Les experts SQL gagnent aussi du temps avec l'IA",
          "Toujours vérifier les requêtes générées sur des données de test",
        ]},
      ],
      quiz: [
        {
          question: "Comment l'IA aide-t-elle avec les bases de données ?",
          options: ["Elle hébergé les bases", "Elle génère schémas, requêtes et optimisations à partir de langage naturel", "Elle remplace SQL", "Elle crée des backups automatiques"],
          correctIndex: 1,
          explanation: "L'IA génère des schémas, des requêtes complexes et des optimisations à partir de descriptions en langage naturel, rendant SQL accessible à tous.",
        },
        {
          question: "Qu'est-ce qu'une CTE en SQL ?",
          options: ["Un type de jointure", "Une Common Table Expression (sous-requête nommee)", "Un index", "Une contrainte"],
          correctIndex: 1,
          explanation: "Une CTE (Common Table Expression) est une sous-requête nommee qui rend les requêtes complexes plus lisibles et maintenables.",
        },
        {
          question: "Comment optimiser une requête lente avec l'IA ?",
          options: ["Supprimer la requête", "Faire analyser le plan d'exécution (EXPLAIN ANALYZE)", "Augmenter la RAM du serveur", "Changer de base de données"],
          correctIndex: 1,
          explanation: "L'IA peut analyser les plans d'exécution (EXPLAIN ANALYZE) et identifier les index manquants ou les opérations couteuses pour optimiser les requêtes.",
        },
        {
          question: "Faut-il vérifier les requêtes SQL générées par l'IA ?",
          options: ["Non, elles sont toujours correctes", "Oui, toujours sur des données de test", "Seulement pour les DELETE", "Seulement en production"],
          correctIndex: 1,
          explanation: "Il faut toujours vérifier les requêtes générées sur des données de test pour s'assurer qu'elles retournent les résultats attendus et sont performantes.",
        },
      ],
    },
    {
      number: 13,
      title: "DevOps et CI/CD Assiste par l'IA",
      description: "Automatiser le déploiement, l'infrastructure et les pipelines avec l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "DevOps Augmente par l'IA" },
        { type: "paragraph", content: "Le DevOps est un domaine ou l'IA apporte une valeur énorme : génération de configurations Docker, pipelines CI/CD, infrastructure as code (Terraform, Pulumi), monitoring, et incident response. Les configurations complexes qui prenaient des heures se generent en minutes." },
        { type: "paragraph", content: "Les LLM maitrisent les écosystèmes DevOps : Docker, Kubernetes, GitHub Actions, GitLab CI, Terraform, Ansible, Nginx, et les services cloud (AWS, GCP, Azure, Vercel). Ils generent des configurations idiomatiques et sécurisées." },
        { type: "subheading", content: "Dockerisation avec l'IA" },
        { type: "paragraph", content: "Decrivez votre application et l'IA génère un Dockerfile optimisé : multi-stage build, layer caching, sécurité (non-root user), et un docker-compose pour l'environnement de dev complet avec base de données et cache." },
        { type: "subheading", content: "Pipelines CI/CD" },
        { type: "paragraph", content: "L'IA génère des pipelines GitHub Actions ou GitLab CI complets : lint, tests, build, deploy. Elle configure les environments, les secrets, les conditions de déploiement, et les notifications." },
        { type: "prompt-example", prompt: "Cree un pipeline GitHub Actions pour une app Next.js : lint, tests, build, preview deploy sur Vercel pour les PRs, et production deploy sur merge dans main", result: "L'IA génère un workflow YAML complet avec les jobs parallelises, les caches npm, les secrets Vercel, et les conditions de trigger." },
        { type: "callout", content: "L'IA peut aussi analyser vos logs de déploiement et diagnostiquer les échecs. Collez le log d'erreur de votre pipeline et obtenez un diagnostic précis en secondes." },
        { type: "video", videoId: { fr: "18oAWvzjmTw", en: "ocMOZpuAMw4" },
      videoDurationMinutes: 15, label: "DevOps et CI/CD avec l'IA" },
        { type: "diagram", label: "Pipeline CI/CD Genere par l'IA", flow: "horizontal", nodes: [
          { label: "Lint & Format", sub: "ESLint, Prettier", color: "blue" },
          { label: "Tests", sub: "Unitaires + intégration", color: "purple" },
          { label: "Build", sub: "Compilation + optimisation", color: "emerald" },
          { label: "Deploy", sub: "Preview PR + Production", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA génère Dockerfiles, pipelines CI/CD et infra as code",
          "Configurations complexes générées en minutes au lieu d'heures",
          "Support des écosystèmes : Docker, K8s, GitHub Actions, Terraform",
          "Diagnostic automatisé des échecs de déploiement",
          "Toujours auditer les configurations de sécurité générées",
        ]},
      ],
      quiz: [
        {
          question: "Que peut générer l'IA pour le DevOps ?",
          options: ["Uniquement des Dockerfiles", "Dockerfiles, pipelines CI/CD, et infrastructure as code", "Uniquement des scripts bash", "Uniquement de la documentation"],
          correctIndex: 1,
          explanation: "L'IA génère des Dockerfiles optimises, des pipelines CI/CD complets, de l'infrastructure as code (Terraform, Pulumi), et des configurations de monitoring.",
        },
        {
          question: "Quel avantage apporte l'IA pour les pipelines CI/CD ?",
          options: ["Elle les exécute plus vite", "Elle génère des configurations complexes en minutes", "Elle remplace GitHub", "Elle hébergé les déploiements"],
          correctIndex: 1,
          explanation: "L'IA génère des pipelines complets avec jobs parallelises, caches, secrets et conditions — des configurations qui prenaient des heures manuellement.",
        },
        {
          question: "Qu'est-ce qu'un Dockerfile multi-stage ?",
          options: ["Un Dockerfile avec plusieurs ports", "Un Dockerfile qui séparé build et runtime pour des images plus légères", "Un Dockerfile pour plusieurs apps", "Un Dockerfile avec plusieurs OS"],
          correctIndex: 1,
          explanation: "Un multi-stage build séparé l'étape de compilation de l'étape d'exécution, produisant des images Docker plus légères et plus sécurisées.",
        },
        {
          question: "Comment l'IA aide-t-elle quand un déploiement echoue ?",
          options: ["Elle relance automatiquement le deploy", "Elle analyse les logs et diagnostique l'erreur", "Elle notifié l'équipe", "Elle rollback automatiquement"],
          correctIndex: 1,
          explanation: "L'IA peut analyser les logs d'erreur d'un pipeline et fournir un diagnostic précis avec une solution en quelques secondes.",
        },
      ],
    },
    {
      number: 14,
      title: "Sécurité du Code avec l'IA",
      description: "Détecter et corriger les vulnérabilités avec l'assistance de l'IA.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Sécurité du Code Assistee par l'IA" },
        { type: "paragraph", content: "La sécurité est un domaine critique ou l'IA joue un double rôle : elle aide à détecter les vulnérabilités, mais elle peut aussi en introduire. Comprendre comment utiliser l'IA pour sécuriser votre code — et les limites de cette approche — est essentiel." },
        { type: "paragraph", content: "Les LLM connaissent les vulnérabilités courantes (OWASP Top 10), les bonnes pratiques de sécurité, et les patterns de code dangereux. Ils peuvent auditer du code et proposer des correctifs en quelques secondes." },
        { type: "subheading", content: "Vulnerabilites Courantes Detectees" },
        { type: "paragraph", content: "Injection SQL, Cross-Site Scripting (XSS), Cross-Site Request Forgery (CSRF), authentification cassee, exposition de données sensibles, mauvaise configuration de sécurité, deserialization non sécurisée." },
        { type: "subheading", content: "Audit de Sécurité avec l'IA" },
        { type: "paragraph", content: "Demandez a Claude Code ou Cursor d'auditer votre code pour les vulnérabilités OWASP Top 10. L'IA analyse les inputs non validés, les requêtes parametrables, les headers de sécurité, et les secrets exposes." },
        { type: "key-point", content: "L'IA génère parfois du code avec des vulnérabilités. Ne faites JAMAIS confiance aveuglement au code de sécurité généré par l'IA. Un audit humain expert reste indispensable pour les systèmes critiques." },
        { type: "tip", content: "Integrez des outils SAST (Static Application Security Testing) comme Snyk ou SonarQube dans votre CI/CD pour une détection automatique continue." },
        { type: "video", videoId: { fr: "Xagh-g3zyuw", en: "n0NlxUyA7FI" },
      videoDurationMinutes: 11, label: "Sécurité du code avec l'IA" },
        { type: "diagram", label: "OWASP Top 10 — Vulnerabilites Clés", flow: "vertical", nodes: [
          { label: "Injection (SQL, XSS)", sub: "Inputs non sanitizes", color: "pink" },
          { label: "Authentification cassee", sub: "Sessions, mots de passe faibles", color: "amber" },
          { label: "Exposition de données", sub: "Secrets, API keys, PII", color: "purple" },
          { label: "Mauvaise configuration", sub: "Headers, CORS, permissions", color: "blue" },
        ]},
        { type: "summary", items: [
          "L'IA détecte les vulnérabilités OWASP Top 10 dans votre code",
          "Elle peut aussi en introduire — ne jamais faire confiance aveuglement",
          "Injection SQL, XSS, CSRF, secrets exposes détectés automatiquement",
          "Integrez SAST (Snyk, SonarQube) dans votre CI/CD",
          "L'audit humain expert reste indispensable pour les systèmes critiques",
        ]},
      ],
      quiz: [
        {
          question: "Quel est le double rôle de l'IA en sécurité du code ?",
          options: ["Accelerer et ralentir", "Détecter les vulnérabilités ET potentiellement en introduire", "Chiffrer et dechiffrer", "Tester et déployer"],
          correctIndex: 1,
          explanation: "L'IA aide à détecter les vulnérabilités mais peut aussi en introduire dans le code génère. C'est pourquoi un audit humain reste indispensable.",
        },
        {
          question: "Qu'est-ce que l'OWASP Top 10 ?",
          options: ["Les 10 meilleurs langages", "Les 10 vulnérabilités web les plus courantes", "Les 10 meilleurs outils de dev", "Les 10 frameworks les plus populaires"],
          correctIndex: 1,
          explanation: "L'OWASP Top 10 est une liste des 10 vulnérabilités de sécurité web les plus courantes et les plus critiques, mise à jour régulièrement.",
        },
        {
          question: "Que sont les outils SAST ?",
          options: ["Des editeurs de code", "Des outils d'analyse statique de sécurité", "Des gestionnaires de paquets", "Des bases de données"],
          correctIndex: 1,
          explanation: "SAST (Static Application Security Testing) sont des outils comme Snyk et SonarQube qui analysent le code source pour détecter les vulnérabilités automatiquement.",
        },
        {
          question: "Faut-il faire confiance au code de sécurité généré par l'IA ?",
          options: ["Oui, toujours", "Non, un audit humain expert reste indispensable", "Seulement pour les petits projets", "Seulement si l'IA est payante"],
          correctIndex: 1,
          explanation: "Il ne faut jamais faire confiance aveuglement au code de sécurité généré par l'IA. Un audit humain expert reste indispensable pour les systèmes critiques.",
        },
      ],
    },
    {
      number: 15,
      title: "Documentation Automatique",
      description: "Générer et maintenir une documentation de qualité avec l'IA.",
      estimatedMinutes: 6,
      sections: [
        { type: "heading", content: "Documentation Automatisee par l'IA" },
        { type: "paragraph", content: "La documentation est souvent negligee parce qu'elle est chronophage. L'IA change la donne : elle génère des JSDoc/TSDoc, des README, des guides d'API, des commentaires inline, et même des guides d'architecture — le tout à partir du code existant." },
        { type: "paragraph", content: "Les LLM comprennent le code et peuvent expliquer sa logique en langage naturel. Ils produisent une documentation cohérente, à jour, et adaptee au public ciblé (développeur junior, utilisateur final, devops)." },
        { type: "subheading", content: "Types de Documentation Générée" },
        { type: "paragraph", content: "JSDoc/TSDoc pour les fonctions et classes. README complets avec installation, usage et exemples. Documentation d'API avec endpoints, paramètres et réponses. Commentaires inline pour la logique complexe. ADR (Architecture Décision Records) pour les choix techniques." },
        { type: "subheading", content: "Maintenir la Documentation a Jour" },
        { type: "paragraph", content: "Integrez la génération de documentation dans votre workflow : après chaque modification, demandez à l'IA de mettre à jour la doc correspondante. Certains outils peuvent détecter automatiquement les changements de code et mettre à jour la documentation." },
        { type: "prompt-example", prompt: "Genere la documentation TSDoc pour toutes les fonctions exportées de ce module, avec exemples d'usage", result: "L'IA génère des blocs TSDoc complets pour chaque fonction : description, @param, @returns, @throws, @example — avec des exemples réalistes." },
        { type: "tip", content: "Demandez à l'IA de générer la documentation comme si elle expliquait a un développeur junior qui découvre le projet. Cela produit des docs plus claires et plus utiles." },
        { type: "video", videoId: { fr: "Xagh-g3zyuw", en: "Fi3AJZZregI" },
      videoDurationMinutes: 15, label: "Documentation automatique avec l'IA" },
        { type: "diagram", label: "Types de Documentation IA", flow: "horizontal", nodes: [
          { label: "Code (JSDoc)", sub: "Fonctions, classes, types", color: "blue" },
          { label: "Projet (README)", sub: "Installation, usage, exemples", color: "purple" },
          { label: "API", sub: "Endpoints, paramètres, réponses", color: "emerald" },
          { label: "Architecture", sub: "ADR, diagrammes, décisions", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA génère JSDoc, README, docs API et commentaires automatiquement",
          "Documentation cohérente et adaptee au public ciblé",
          "Integrez la mise à jour de doc dans votre workflow",
          "Expliquez a un junior = meilleure qualité de documentation",
          "Gain de temps considerable sur une tâche souvent negligee",
        ]},
      ],
      quiz: [
        {
          question: "Pourquoi la documentation est-elle souvent negligee ?",
          options: ["Elle n'est pas utile", "Elle est chronophage", "Les outils n'existent pas", "Les clients ne la demandent pas"],
          correctIndex: 1,
          explanation: "La documentation est souvent negligee parce qu'elle prend du temps. L'IA change cela en generant de la documentation de qualité automatiquement.",
        },
        {
          question: "Qu'est-ce qu'un ADR ?",
          options: ["Un type de base de données", "Un Architecture Décision Record", "Un outil de test", "Un format d'image"],
          correctIndex: 1,
          explanation: "Un ADR (Architecture Décision Record) documente les décisions techniques importantes : pourquoi tel choix a été fait, les alternatives considérées, et les consequences.",
        },
        {
          question: "Comment maintenir la documentation à jour ?",
          options: ["La reecrire chaque mois", "Integrer la génération de doc dans le workflow de dev", "Ne pas la maintenir", "La déléguer a un rédacteur technique"],
          correctIndex: 1,
          explanation: "Integrer la génération de documentation dans le workflow quotidien : après chaque modification, demander à l'IA de mettre à jour la doc correspondante.",
        },
        {
          question: "Quel conseil améliore la qualité de la documentation générée ?",
          options: ["Utiliser un vocabulaire technique maximum", "Demander à l'IA d'expliquer comme a un junior", "Générer le moins de doc possible", "Écrire en anglais uniquement"],
          correctIndex: 1,
          explanation: "Demander à l'IA de documenter comme si elle expliquait a un développeur junior produit des documentations plus claires, plus détaillées et plus utiles.",
        },
      ],
    },
    {
      number: 16,
      title: "Projets Full-Stack avec l'IA",
      description: "Construire une application complète de A à Z avec l'IA comme copilote.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Construire un Projet Full-Stack avec l'IA" },
        { type: "paragraph", content: "Construire une application full-stack de A à Z avec l'IA est radicalement différent du développement traditionnel. Au lieu de coder chaque ligne, vous orchestrez : vous decrivez, l'IA génère, vous validez et iterez. Un projet qui prenait des semaines peut se réaliser en quelques jours." },
        { type: "paragraph", content: "La clé est de combiner les bons outils pour chaque phase du projet : v0 pour le prototypage UI, Cursor pour le développement iteratif, Claude Code pour les features complexes, et GitHub Actions pour le CI/CD." },
        { type: "heading", content: "Les Phases d'un Projet Full-Stack IA" },
        { type: "subheading", content: "Phase 1 : Architecture et Planification" },
        { type: "paragraph", content: "Utilisez Claude ou ChatGPT pour définir l'architecture : stack technique, schéma de base de données, structure de fichiers, API endpoints. L'IA propose des architectures éprouvées adaptées à votre cas d'usage." },
        { type: "subheading", content: "Phase 2 : Prototypage Rapide" },
        { type: "paragraph", content: "Generez les premières pages avec v0 ou Bolt. En 30 minutes, vous avez un prototype fonctionnel a montrer. Iterez sur le design en conversation jusqu'à satisfaction." },
        { type: "subheading", content: "Phase 3 : Développement Iteratif" },
        { type: "paragraph", content: "Passez dans Cursor ou Claude Code pour le développement réel. Implementez feature par feature, avec l'IA comme copilote permanent. Tests et reviews à chaque étape." },
        { type: "callout", content: "Pro tip : gardez un fichier ARCHITECTURE.md a la racine du projet. L'IA le lira à chaque session et generera du code cohérent avec votre vision globale." },
        { type: "video", videoId: { fr: "oeli5xkFZJo", en: "JhM7PWCv2EY" },
      videoDurationMinutes: 14, label: "Projet full-stack avec l'IA de A à Z" },
        { type: "diagram", label: "Phases d'un Projet Full-Stack IA", flow: "vertical", nodes: [
          { label: "Phase 1 — Architecture", sub: "Claude/ChatGPT : stack, schéma, API", color: "blue" },
          { label: "Phase 2 — Prototypage", sub: "v0/Bolt : UI fonctionnelle en 30min", color: "purple" },
          { label: "Phase 3 — Développement", sub: "Cursor/Claude Code : feature par feature", color: "emerald" },
          { label: "Phase 4 — Déploiement", sub: "Vercel/Docker + CI/CD automatisé", color: "amber" },
        ]},
        { type: "summary", items: [
          "Un projet full-stack avec l'IA : jours au lieu de semaines",
          "Combiner les outils : v0 (proto), Cursor (dev), Claude Code (complex)",
          "Architecture d'abord, puis prototypage rapide, puis dev iteratif",
          "ARCHITECTURE.md donne de la cohérence à l'ensemble",
          "L'IA ne remplace pas la vision produit — elle accélère l'exécution",
        ]},
      ],
      quiz: [
        {
          question: "En combien de temps un prototype peut-il être génère avec v0 ou Bolt ?",
          options: ["5 minutes", "30 minutes", "2 heures", "1 journée"],
          correctIndex: 1,
          explanation: "Avec v0 ou Bolt, un prototype fonctionnel avec UI et interactions peut être génère en environ 30 minutes d'iteration conversationnelle.",
        },
        {
          question: "Quelle est la première phase d'un projet full-stack avec l'IA ?",
          options: ["Coder le frontend", "Architecture et planification", "Déployer sur Vercel", "Écrire les tests"],
          correctIndex: 1,
          explanation: "La première phase est l'architecture : définir le stack, le schéma de base de données, la structure de fichiers et les API endpoints avec l'aide de l'IA.",
        },
        {
          question: "A quoi sert un fichier ARCHITECTURE.md ?",
          options: ["A documenter les APIs", "A donner à l'IA une vision cohérente du projet", "A configurer le déploiement", "A lister les dépendances"],
          correctIndex: 1,
          explanation: "ARCHITECTURE.md donne à l'IA le contexte global du projet à chaque session, assurant que le code génère reste cohérent avec la vision architecturale.",
        },
        {
          question: "Quel est le rôle du développeur dans un projet full-stack IA ?",
          options: ["Coder chaque ligne", "Orchestrer : decrire, valider, iterer", "Juste déployer", "Uniquement tester"],
          correctIndex: 1,
          explanation: "Le développeur orchestre le projet : il decrit ce qu'il veut, l'IA génère, il validé et itere. La vision produit et la validation restent humaines.",
        },
      ],
    },
    {
      number: 17,
      title: "Travailler en Équipe avec l'IA",
      description: "Integrer les outils IA dans le workflow d'une équipe de développement.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "L'IA dans le Workflow d'Équipe" },
        { type: "paragraph", content: "Adopter l'IA en équipe est différent de l'utiliser seul. Il faut standardiser les outils, définir des conventions, gérer les licences, et s'assurer que le code généré par l'IA respecte les standards de l'équipe." },
        { type: "paragraph", content: "En 2026, les équipes performantes ont un 'IA stack' défini : quels outils, quels modèles, quelles règles. Les fichiers de configuration (.cursorrules, CLAUDE.md) sont partages dans le repo pour assurer la cohérence." },
        { type: "subheading", content: "Standardisation des Outils" },
        { type: "paragraph", content: "Definissez un stack IA d'équipe : IDE (Cursor ou VS Code + Copilot), agent CLI (Claude Code), générateur (v0 pour les composants). Partagez les configurations et les règles dans le repo." },
        { type: "subheading", content: "Conventions de Code IA" },
        { type: "paragraph", content: "Definissez des règles : le code génère doit passer les mêmes reviews que le code humain. Les tests sont obligatoires. Les prompts utilisés pour les générations complexes sont documentes dans les commits." },
        { type: "heading", content: "Pair Programming avec l'IA" },
        { type: "paragraph", content: "L'IA est le partenaire de pair programming idéal : disponible 24/7, patient, et connaissant une immense base de code. Mais attention a ne pas devenir dépendant — chaque membre de l'équipe doit comprendre le code génère." },
        { type: "key-point", content: "Règle d'or : si un développeur ne peut pas expliquer le code généré par l'IA, ce code ne devrait pas être merge. La compréhension humaine reste le garde-fou essentiel." },
        { type: "tip", content: "Organisez des sessions de partage 'IA tips' hebdomadaires ou chaque membre de l'équipe partage une technique ou un prompt utile." },
        { type: "video", videoId: { fr: "18oAWvzjmTw", en: "ocMOZpuAMw4" },
      videoDurationMinutes: 15, label: "Travailler en équipe avec l'IA" },
        { type: "diagram", label: "IA Stack d'Équipe", flow: "horizontal", nodes: [
          { label: "IDE IA", sub: "Cursor ou VS Code + Copilot", color: "blue" },
          { label: "Agent CLI", sub: "Claude Code partage", color: "purple" },
          { label: "Review IA", sub: "Copilot Review / CodeRabbit", color: "emerald" },
          { label: "Config partagee", sub: ".cursorrules, CLAUDE.md", color: "amber" },
        ]},
        { type: "summary", items: [
          "Définir un stack IA d'équipe standardisé",
          "Fichiers de config (.cursorrules, CLAUDE.md) partages dans le repo",
          "Le code IA passe les mêmes reviews que le code humain",
          "Règle d'or : si tu ne peux pas l'expliquer, ne le merge pas",
          "Sessions 'IA tips' hebdomadaires pour partager les bonnes pratiques",
        ]},
      ],
      quiz: [
        {
          question: "Quelle est la règle d'or pour le code généré par l'IA en équipe ?",
          options: ["Toujours le merger rapidement", "Ne jamais le modifier", "Si tu ne peux pas l'expliquer, ne le merge pas", "Toujours le reecrire"],
          correctIndex: 2,
          explanation: "Si un développeur ne peut pas expliquer le code généré par l'IA, ce code ne devrait pas être merge. La compréhension humaine est le garde-fou essentiel.",
        },
        {
          question: "Comment standardiser l'utilisation de l'IA en équipe ?",
          options: ["Laisser chacun choisir ses outils", "Définir un stack IA et partager les configs dans le repo", "Interdire l'IA", "Utiliser uniquement ChatGPT"],
          correctIndex: 1,
          explanation: "Définir un stack IA d'équipe (IDE, agent, générateur) et partager les configurations (.cursorrules, CLAUDE.md) dans le repo assure la cohérence.",
        },
        {
          question: "Le code généré par l'IA doit-il passer par une review ?",
          options: ["Non, l'IA ne fait pas d'erreurs", "Oui, les mêmes reviews que le code humain", "Seulement pour les juniors", "Seulement s'il touche la base de données"],
          correctIndex: 1,
          explanation: "Le code généré par l'IA doit passer exactement les mêmes reviews et les mêmes tests que le code écrit par un humain.",
        },
        {
          question: "Qu'est-ce qu'une session 'IA tips' ?",
          options: ["Une formation obligatoire", "Un partage hebdomadaire de techniques et prompts utiles", "Un audit de code", "Une demo produit"],
          correctIndex: 1,
          explanation: "Les sessions 'IA tips' sont des moments hebdomadaires ou chaque membre partage une technique, un prompt ou une astuce IA utile pour toute l'équipe.",
        },
      ],
    },
    {
      number: 18,
      title: "Construire son Workflow de Dev IA",
      description: "Assembler tous les outils en un workflow personnalisé et efficace.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Votre Workflow de Développement IA Personnalisé" },
        { type: "paragraph", content: "Vous avez découvert les outils individuels. Maintenant, il est temps de les assembler en un workflow cohérent et personnalisé. Le meilleur workflow IA est celui qui s'adapte à VOTRE façon de travailler, pas l'inverse." },
        { type: "paragraph", content: "Il n'existe pas de workflow unique qui fonctionne pour tout le monde. Un freelance solo n'a pas les mêmes besoins qu'une équipe de 50. Un projet greenfield n'utilise pas les mêmes outils qu'une maintenance de legacy. L'objectif est de construire VOTRE stack." },
        { type: "heading", content: "Les Composantes d'un Workflow IA" },
        { type: "subheading", content: "1. IDE et Completion" },
        { type: "paragraph", content: "Cursor (tout-en-un) ou VS Code + Copilot (modulaire). Pour la plupart des devs, Cursor est le choix optimal en 2026 grâce à son intégration native." },
        { type: "subheading", content: "2. Agent pour les Tâches Complexes" },
        { type: "paragraph", content: "Claude Code pour les refactorings, migrations, et features complexes. Lancez-le dans un terminal séparé pendant que vous continuez à travailler dans votre IDE." },
        { type: "subheading", content: "3. Generateurs pour le Prototypage" },
        { type: "paragraph", content: "v0 pour les composants UI, Bolt pour les prototypes full-stack. Utilisez-les en début de projet pour aller vite, puis migrez dans Cursor pour le peaufinage." },
        { type: "subheading", content: "4. Automatisation" },
        { type: "paragraph", content: "GitHub Actions pour le CI/CD, Copilot Review pour les PRs, et des scripts custom avec Claude API pour les tâches répétitives spécifiques à votre projet." },
        { type: "callout", content: "Commencez simple : Cursor + Claude Code suffisent pour 90% des tâches. Ajoutez des outils au fur et à mesure que vous identifiez des besoins spécifiques." },
        { type: "key-point", content: "Le workflow idéal évolue avec le temps. Revoyez-le chaque mois : quels outils utilisez-vous vraiment ? Lesquels sont superflus ? Quels nouveaux outils valent la peine d'être testés ?" },
        { type: "video", videoId: { fr: "Xagh-g3zyuw", en: "n0NlxUyA7FI" },
      videoDurationMinutes: 11, label: "Construire son workflow de dev IA" },
        { type: "diagram", label: "Workflow de Dev IA Complet", flow: "vertical", nodes: [
          { label: "IDE — Cursor / VS Code + Copilot", sub: "Développement quotidien", color: "blue" },
          { label: "Agent — Claude Code", sub: "Tâches complexes et refactoring", color: "purple" },
          { label: "Generateur — v0 / Bolt", sub: "Prototypage rapide", color: "emerald" },
          { label: "CI/CD — GitHub Actions + Review IA", sub: "Automatisation et qualité", color: "amber" },
          { label: "LLM — ChatGPT / Claude", sub: "Recherche, debugging, documentation", color: "pink" },
        ]},
        { type: "diagram", label: "Cycle d'Amélioration du Workflow", flow: "cycle", nodes: [
          { label: "Utiliser", sub: "Travailler avec vos outils actuels", color: "blue" },
          { label: "Évaluer", sub: "Identifier ce qui marche et ce qui manque", color: "purple" },
          { label: "Ajuster", sub: "Ajouter, retirer ou remplacer des outils", color: "emerald" },
        ]},
        { type: "summary", items: [
          "Le meilleur workflow s'adapte à VOTRE façon de travailler",
          "Cursor + Claude Code couvrent 90% des besoins",
          "v0/Bolt pour le prototypage, GitHub Actions pour le CI/CD",
          "Commencez simple et ajoutez des outils selon les besoins",
          "Revoyez votre workflow chaque mois pour l'optimiser",
        ]},
      ],
      quiz: [
        {
          question: "Quels deux outils couvrent 90% des besoins de développement IA ?",
          options: ["ChatGPT + Midjourney", "Cursor + Claude Code", "v0 + Bolt", "Copilot + Stack Overflow"],
          correctIndex: 1,
          explanation: "Cursor (IDE IA) + Claude Code (agent CLI) couvrent environ 90% des besoins quotidiens de développement assisté par l'IA.",
        },
        {
          question: "A quelle fréquence faut-il revoir son workflow IA ?",
          options: ["Jamais", "Chaque mois", "Chaque année", "À chaque nouveau projet"],
          correctIndex: 1,
          explanation: "Il est recommandé de revoir son workflow chaque mois pour identifier les outils sous-utilisés, les lacunes, et les nouveaux outils à tester.",
        },
        {
          question: "Quel est le meilleur conseil pour commencer ?",
          options: ["Installer tous les outils immédiatement", "Commencer simple et ajouter selon les besoins", "Attendre que les outils soient matures", "Utiliser uniquement des outils gratuits"],
          correctIndex: 1,
          explanation: "Commencer avec Cursor + Claude Code puis ajouter des outils au fur et à mesure des besoins spécifiques identifiés est l'approche la plus efficace.",
        },
        {
          question: "Pourquoi n'existe-t-il pas de workflow unique idéal ?",
          options: ["Les outils changent trop vite", "Chaque dev, équipe et projet a des besoins différents", "L'IA n'est pas assez mature", "Les coûts sont trop élèves"],
          correctIndex: 1,
          explanation: "Un freelance solo, une équipe de 50, un projet greenfield et une maintenance legacy ont tous des besoins différents. Le workflow doit s'adapter au contexte.",
        },
      ],
    },
  ],
};

export default content;
