import type { CourseContent } from "../types";

const content: CourseContent = {
  slug: "cybersecurite-ia",
  chapters: [
    {
      number: 1,
      title: "Introduction a la Cybersecurite IA",
      description: "Comprendre les enjeux de la cybersecurite a l'ere de l'intelligence artificielle.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "La Cybersecurite a l'Ere de l'IA" },
        { type: "paragraph", content: "La cybersecurite a toujours ete une course entre attaquants et defenseurs. Avec l'arrivee de l'intelligence artificielle, cette course s'accelere drastiquement. L'IA donne aux attaquants des capacites inedites pour automatiser et sophistiquer leurs attaques, mais elle offre aussi aux defenseurs des outils puissants pour detecter et neutraliser les menaces." },
        { type: "paragraph", content: "En 2026, les cyberattaques assistees par l'IA representent plus de 40% des incidents majeurs. Les deepfakes, le phishing genere par LLM, les malwares polymorphes et l'ingenierie sociale automatisee sont devenus des menaces quotidiennes pour les entreprises et les individus." },
        { type: "callout", content: "Selon le rapport IBM X-Force 2026, le cout moyen d'une violation de donnees a atteint 5,2 millions de dollars, en hausse de 15% par rapport a 2024. L'IA est a la fois le probleme et la solution." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Introduction a la Cybersecurite IA" },
        { type: "heading", content: "Pourquoi l'IA Change la Donne" },
        { type: "paragraph", content: "L'IA transforme la cybersecurite de trois manieres fondamentales : elle automatise les attaques a une echelle sans precedent, elle rend les attaques plus convaincantes et difficiles a detecter, et elle permet aux defenseurs d'analyser des millions d'evenements en temps reel." },
        { type: "subheading", content: "Le Paysage des Menaces en 2026" },
        { type: "paragraph", content: "Les organisations font face a des attaques de plus en plus sophistiquees : phishing hyper-personnalise genere par GPT-5.4, deepfakes video en temps reel pour l'usurpation d'identite, malwares qui mutent automatiquement pour echapper a la detection, et attaques adversariales contre les modeles d'IA eux-memes." },
        { type: "key-point", content: "La cybersecurite IA n'est pas une specialite de niche — c'est une competence essentielle pour tout professionnel du numerique en 2026. Chaque utilisateur d'IA doit comprendre les risques et les protections." },
        { type: "diagram", label: "L'IA dans la Cybersecurite : Double Tranchant", flow: "horizontal", nodes: [
          { label: "IA Offensive", sub: "Phishing, deepfakes, malwares", color: "pink" },
          { label: "IA Defensive", sub: "Detection, reponse, prevention", color: "emerald" },
          { label: "Course aux Armements", sub: "Escalade continue attaque/defense", color: "amber" },
        ]},
        { type: "tip", content: "Ce cours couvre les deux cotes : comprendre les attaques pour mieux se defendre. La meilleure defense commence par la connaissance des techniques offensives." },
        { type: "summary", items: [
          "L'IA accelere la course entre attaquants et defenseurs en cybersecurite",
          "40% des incidents majeurs en 2026 impliquent de l'IA",
          "Le cout moyen d'une violation de donnees atteint 5,2 millions de dollars",
          "L'IA est a la fois le probleme (attaques) et la solution (defense)",
          "La cybersecurite IA est une competence essentielle pour tous",
        ]},
      ],
      quiz: [
        {
          question: "Quel pourcentage des incidents majeurs en 2026 implique l'IA ?",
          options: ["10%", "25%", "40%", "60%"],
          correctIndex: 2,
          explanation: "En 2026, les cyberattaques assistees par l'IA representent plus de 40% des incidents majeurs, selon les rapports de cybersecurite.",
        },
        {
          question: "Comment l'IA transforme-t-elle la cybersecurite ?",
          options: ["Elle remplace completement les experts humains", "Elle automatise les attaques et renforce les defenses", "Elle elimine tous les risques de piratage", "Elle ne concerne que les grandes entreprises"],
          correctIndex: 1,
          explanation: "L'IA est un outil a double tranchant : elle automatise et sophistique les attaques, mais offre aussi des outils puissants de detection et de defense.",
        },
        {
          question: "Quel est le cout moyen d'une violation de donnees en 2026 ?",
          options: ["1,5 million de dollars", "3,8 millions de dollars", "5,2 millions de dollars", "10 millions de dollars"],
          correctIndex: 2,
          explanation: "Selon le rapport IBM X-Force 2026, le cout moyen d'une violation de donnees a atteint 5,2 millions de dollars, en hausse de 15% par rapport a 2024.",
        },
        {
          question: "Pourquoi la cybersecurite IA concerne-t-elle tous les professionnels ?",
          options: ["Parce que tout le monde doit devenir hacker", "Parce que les menaces IA touchent tous les utilisateurs du numerique", "Parce que c'est obligatoire par la loi", "Parce que les antivirus ne fonctionnent plus"],
          correctIndex: 1,
          explanation: "Les menaces basees sur l'IA (phishing, deepfakes, ingenierie sociale) ciblent tous les utilisateurs du numerique, rendant cette competence essentielle pour tous.",
        },
      ],
    },
    {
      number: 2,
      title: "Menaces Generees par l'IA",
      description: "Cartographie complete des cybermenaces augmentees par l'intelligence artificielle.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Les Menaces IA : Une Nouvelle Generation d'Attaques" },
        { type: "paragraph", content: "L'intelligence artificielle a ouvert la boite de Pandore des cybermenaces. Les attaquants utilisent desormais des LLM pour generer des emails de phishing parfaits, des outils de generation d'images pour creer des deepfakes convaincants, et des algorithmes d'apprentissage pour concevoir des malwares qui echappent a la detection." },
        { type: "subheading", content: "Malwares Polymorphes et Evasifs" },
        { type: "paragraph", content: "Les malwares assistes par l'IA peuvent modifier leur code automatiquement a chaque execution pour echapper aux signatures antivirus. Ils analysent l'environnement de la cible et adaptent leur comportement en consequence. En 2026, ces malwares polymorphes representent 30% des nouvelles souches detectees." },
        { type: "subheading", content: "Attaques par Injection de Prompt" },
        { type: "paragraph", content: "Les systemes bases sur des LLM sont vulnerables aux injections de prompt : un attaquant insere des instructions malveillantes dans les donnees que le modele traite. Cela peut conduire a l'exfiltration de donnees, au contournement des garde-fous, ou a l'execution d'actions non autorisees." },
        { type: "callout", content: "En 2025, une attaque par injection de prompt sur un chatbot bancaire a permis a des attaquants d'acceder aux informations de 50 000 clients. Les injections de prompt sont le nouveau SQL injection." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Les cybermenaces IA expliquees" },
        { type: "subheading", content: "Reconnaissance Automatisee" },
        { type: "paragraph", content: "L'IA permet aux attaquants de scanner automatiquement des milliers de cibles, d'analyser les reseaux sociaux pour profiler les victimes, et d'identifier les vulnerabilites des systemes en quelques minutes au lieu de jours. Les outils OSINT (Open Source Intelligence) boostes a l'IA rendent la phase de reconnaissance devastatrice." },
        { type: "key-point", content: "Les attaques IA ne sont pas reservees aux hackers sophistiques. Des outils comme WormGPT et FraudGPT, vendus sur le dark web, permettent a n'importe qui de lancer des attaques IA sans competences techniques." },
        { type: "diagram", label: "Taxonomie des Menaces IA", flow: "vertical", nodes: [
          { label: "Phishing IA", sub: "Emails et messages generes par LLM", color: "pink" },
          { label: "Deepfakes", sub: "Video, audio, images falsifiees", color: "purple" },
          { label: "Malwares polymorphes", sub: "Code qui mute automatiquement", color: "blue" },
          { label: "Injection de prompt", sub: "Manipulation des systemes LLM", color: "amber" },
          { label: "Reconnaissance OSINT", sub: "Profilage automatise des cibles", color: "emerald" },
        ]},
        { type: "prompt-example", prompt: "Analyse cette liste d'emails recus et identifie ceux qui pourraient etre du phishing genere par IA. Explique les indices pour chacun.", result: "L'IA peut vous aider a detecter les tentatives de phishing en analysant le style, la coherence et les meta-donnees des messages suspects." },
        { type: "summary", items: [
          "Les malwares polymorphes IA representent 30% des nouvelles souches en 2026",
          "L'injection de prompt est le nouveau vecteur d'attaque contre les systemes LLM",
          "Les outils OSINT IA automatisent la reconnaissance des cibles",
          "WormGPT et FraudGPT democratisent les attaques IA sur le dark web",
          "Chaque nouvelle capacite IA cree de nouveaux vecteurs d'attaque",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce qu'un malware polymorphe ?",
          options: ["Un virus qui attaque plusieurs systemes", "Un malware qui modifie son code automatiquement", "Un logiciel qui se duplique", "Un virus qui fonctionne sur plusieurs OS"],
          correctIndex: 1,
          explanation: "Un malware polymorphe modifie automatiquement son code a chaque execution pour echapper aux signatures antivirus, rendant sa detection traditionnelle inefficace.",
        },
        {
          question: "Qu'est-ce qu'une injection de prompt ?",
          options: ["Un bug dans un programme", "L'insertion d'instructions malveillantes dans les donnees traitees par un LLM", "Une technique de programmation", "Un type de virus informatique"],
          correctIndex: 1,
          explanation: "L'injection de prompt consiste a inserer des instructions malveillantes dans les donnees que le modele traite, pouvant conduire a l'exfiltration de donnees ou au contournement des garde-fous.",
        },
        {
          question: "Que sont WormGPT et FraudGPT ?",
          options: ["Des outils de securite officiels", "Des LLM malveillants vendus sur le dark web", "Des antivirus nouvelle generation", "Des modeles open source de recherche"],
          correctIndex: 1,
          explanation: "WormGPT et FraudGPT sont des LLM malveillants vendus sur le dark web, permettant a n'importe qui de generer des attaques de phishing ou des malwares sans competences techniques.",
        },
        {
          question: "Comment l'IA ameliore-t-elle la phase de reconnaissance des attaquants ?",
          options: ["Elle ne l'ameliore pas", "Elle automatise le scan des cibles et le profilage via OSINT", "Elle remplace le besoin de reconnaissance", "Elle bloque les attaques avant la reconnaissance"],
          correctIndex: 1,
          explanation: "L'IA permet de scanner automatiquement des milliers de cibles, d'analyser les reseaux sociaux et d'identifier les vulnerabilites en quelques minutes grace aux outils OSINT boostes.",
        },
      ],
    },
    {
      number: 3,
      title: "Phishing et Ingenierie Sociale IA",
      description: "Comment l'IA rend le phishing et l'ingenierie sociale plus dangereux que jamais.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Le Phishing a l'Ere de l'IA" },
        { type: "paragraph", content: "Le phishing est l'attaque la plus courante et la plus efficace en cybersecurite. Avec l'IA, il atteint un niveau de sophistication sans precedent. Les LLM generent des emails parfaitement rediges, personnalises et sans fautes — les indices traditionnels de phishing (fautes d'orthographe, mise en page douteuse) disparaissent." },
        { type: "paragraph", content: "Les attaques de spear-phishing (phishing cible) sont desormais automatisees : l'IA analyse les profils LinkedIn, les publications sur les reseaux sociaux, et les communications publiques pour creer des messages ultra-personnalises qui referent a des projets reels, des collegues existants, et des evenements recents." },
        { type: "subheading", content: "Vishing : L'Arnaque Vocale IA" },
        { type: "paragraph", content: "Le vishing (voice phishing) exploite la synthese vocale IA. Un attaquant peut cloner la voix d'un PDG en 3 secondes d'echantillon audio et appeler le directeur financier pour ordonner un virement urgent. En 2025, une entreprise de Hong Kong a perdu 25 millions de dollars suite a un appel deepfake du 'PDG'." },
        { type: "callout", content: "Les emails de phishing generes par GPT-4 ont un taux de clic 4 a 5 fois superieur aux emails de phishing traditionnels. Avec GPT-5.4, ce taux est encore plus eleve grace a la personnalisation contextuelle." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Le phishing IA en action" },
        { type: "heading", content: "Techniques d'Ingenierie Sociale Augmentee" },
        { type: "paragraph", content: "L'ingenierie sociale IA va au-dela du simple email. Les attaquants utilisent des chatbots IA pour maintenir des conversations convaincantes sur plusieurs jours, des deepfakes en visioconference pour usurper des identites, et des profils sociaux generes par IA pour infiltrer des organisations." },
        { type: "key-point", content: "La regle numero 1 face au phishing IA : ne jamais se fier a un seul canal de communication. Verifiez toujours par un autre canal (telephone, en personne) avant d'effectuer une action sensible." },
        { type: "diagram", label: "Evolution du Phishing", flow: "horizontal", nodes: [
          { label: "Phishing classique", sub: "Emails generiques, fautes, urgence", color: "blue" },
          { label: "Spear-phishing IA", sub: "Personnalise, sans fautes, contextuel", color: "purple" },
          { label: "Vishing deepfake", sub: "Voix clonee, visio truquee", color: "pink" },
        ]},
        { type: "prompt-example", prompt: "Tu es un expert en cybersecurite. Analyse cet email et identifie tous les indices de phishing, meme subtils : [coller l'email suspect]", result: "L'IA identifie les anomalies : expediteur usurpe, urgence artificielle, liens suspects, demandes inhabituelles, incoherences temporelles." },
        { type: "summary", items: [
          "Le phishing IA est sans fautes, personnalise et contextuellement coherent",
          "Le spear-phishing automatise utilise OSINT pour cibler precisement les victimes",
          "Le vishing deepfake peut cloner une voix en 3 secondes d'echantillon",
          "Les emails de phishing IA ont un taux de clic 4-5x superieur",
          "Regle d'or : verifier par un autre canal avant toute action sensible",
        ]},
      ],
      quiz: [
        {
          question: "Pourquoi le phishing IA est-il plus dangereux que le phishing traditionnel ?",
          options: ["Il est plus rapide", "Il genere des emails parfaits, personnalises et sans fautes", "Il coute moins cher", "Il ne peut pas etre detecte"],
          correctIndex: 1,
          explanation: "Le phishing IA genere des emails parfaitement rediges, sans fautes, personnalises avec des informations reelles de la cible, eliminant les indices traditionnels de detection.",
        },
        {
          question: "Qu'est-ce que le vishing ?",
          options: ["Le phishing par SMS", "Le phishing par email video", "Le phishing vocal avec voix synthetique", "Le phishing sur les reseaux sociaux"],
          correctIndex: 2,
          explanation: "Le vishing (voice phishing) utilise la synthese vocale IA pour cloner des voix et passer des appels telephoniques frauduleux, souvent en imitant des dirigeants.",
        },
        {
          question: "Combien de temps faut-il pour cloner une voix avec l'IA ?",
          options: ["1 heure", "10 minutes", "3 secondes", "24 heures"],
          correctIndex: 2,
          explanation: "Les outils modernes de clonage vocal IA peuvent reproduire une voix convaincante a partir de seulement 3 secondes d'echantillon audio.",
        },
        {
          question: "Quelle est la meilleure defense contre le phishing IA ?",
          options: ["Installer un meilleur antivirus", "Verifier par un autre canal avant toute action sensible", "Ne jamais ouvrir ses emails", "Bloquer tous les expediteurs inconnus"],
          correctIndex: 1,
          explanation: "La verification multi-canal est la meilleure defense : avant toute action sensible (virement, envoi de donnees), confirmez la demande par un canal different (telephone, en personne).",
        },
      ],
    },
    {
      number: 4,
      title: "Deepfakes et Usurpation d'Identite",
      description: "Comprendre, detecter et se proteger contre les deepfakes et l'usurpation d'identite IA.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Les Deepfakes : La Menace Invisible" },
        { type: "paragraph", content: "Les deepfakes sont des contenus mediatiques (video, audio, images) generes ou manipules par l'IA pour paraitre authentiques. En 2026, la qualite des deepfakes est telle qu'ils sont pratiquement impossibles a distinguer de contenus reels a l'oeil nu." },
        { type: "paragraph", content: "Les deepfakes sont utilises pour l'usurpation d'identite en visioconference, la fraude financiere, la desinformation politique, le chantage, et l'atteinte a la reputation. Le volume de deepfakes detectes en ligne a augmente de 900% entre 2024 et 2026." },
        { type: "subheading", content: "Deepfakes Video en Temps Reel" },
        { type: "paragraph", content: "Les technologies de face-swapping en temps reel permettent a un attaquant de prendre l'apparence de n'importe qui lors d'un appel Zoom ou Teams. En 2025, une multinationale a perdu 25 millions de dollars apres qu'un employe ait suivi les instructions d'un 'collegue' en visioconference — un deepfake en temps reel." },
        { type: "subheading", content: "Deepfakes Audio" },
        { type: "paragraph", content: "Le clonage vocal est devenu trivial. ElevenLabs, Resemble.ai et d'autres outils permettent de cloner une voix avec quelques secondes d'audio. Les attaquants utilisent ces voix clonees pour des arnaques telephoniques, du chantage, et de la manipulation d'autorisations vocales." },
        { type: "callout", content: "Les deepfakes ne menacent pas seulement les personnalites publiques. En 2026, des particuliers sont cibles : fausses videos compromettantes pour du chantage, usurpation d'identite pour des prets bancaires, faux temoignages." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Comment fonctionnent les deepfakes" },
        { type: "heading", content: "Detection des Deepfakes" },
        { type: "paragraph", content: "Plusieurs techniques existent pour detecter les deepfakes : analyse des micro-expressions faciales, detection d'artefacts de generation (bords flous, eclairage incoherent), analyse spectrale de l'audio, et verification du watermarking C2PA. Des outils comme Microsoft Video Authenticator et Intel FakeCatcher aident a la detection." },
        { type: "key-point", content: "Le standard C2PA (Coalition for Content Provenance and Authenticity) integre des metadonnees cryptographiques dans les contenus pour certifier leur origine. C'est la defense la plus prometteuse contre les deepfakes a grande echelle." },
        { type: "diagram", label: "Types de Deepfakes et Defenses", flow: "vertical", nodes: [
          { label: "Deepfake Video", sub: "Face-swapping, lip-syncing temps reel", color: "pink" },
          { label: "Deepfake Audio", sub: "Clonage vocal, synthese de parole", color: "purple" },
          { label: "Deepfake Image", sub: "Visages generes, manipulation de photos", color: "blue" },
          { label: "Detection IA", sub: "FakeCatcher, Video Authenticator", color: "emerald" },
          { label: "C2PA Watermarking", sub: "Certification cryptographique d'origine", color: "amber" },
        ]},
        { type: "summary", items: [
          "Le volume de deepfakes a augmente de 900% entre 2024 et 2026",
          "Les deepfakes video en temps reel permettent l'usurpation en visioconference",
          "Le clonage vocal ne necessite que quelques secondes d'echantillon",
          "La detection repose sur l'analyse d'artefacts et le watermarking C2PA",
          "Toujours verifier l'identite par un canal independant",
        ]},
      ],
      quiz: [
        {
          question: "De combien le volume de deepfakes a-t-il augmente entre 2024 et 2026 ?",
          options: ["100%", "300%", "900%", "50%"],
          correctIndex: 2,
          explanation: "Le volume de deepfakes detectes en ligne a augmente de 900% entre 2024 et 2026, refletant la democratisation des outils de generation.",
        },
        {
          question: "Qu'est-ce que le standard C2PA ?",
          options: ["Un antivirus pour deepfakes", "Un standard de watermarking cryptographique pour certifier l'origine du contenu", "Un format video securise", "Un protocole de visioconference"],
          correctIndex: 1,
          explanation: "C2PA (Coalition for Content Provenance and Authenticity) integre des metadonnees cryptographiques dans les contenus pour certifier leur origine et leur authenticite.",
        },
        {
          question: "Comment un deepfake en temps reel a-t-il coute 25 millions a une entreprise ?",
          options: ["En piratant le systeme bancaire", "En usurpant l'identite d'un collegue en visioconference", "En envoyant un email frauduleux", "En compromettant le reseau"],
          correctIndex: 1,
          explanation: "Un attaquant a utilise un deepfake en temps reel pour prendre l'apparence d'un collegue lors d'une visioconference, convainquant un employe d'effectuer un virement de 25 millions de dollars.",
        },
        {
          question: "Quel outil aide a detecter les deepfakes video ?",
          options: ["ChatGPT", "Microsoft Video Authenticator", "Midjourney", "Google Translate"],
          correctIndex: 1,
          explanation: "Microsoft Video Authenticator analyse les videos pour detecter les artefacts de generation et estimer la probabilite qu'un contenu soit un deepfake.",
        },
      ],
    },
    {
      number: 5,
      title: "Defense et Detection avec l'IA",
      description: "Comment l'IA renforce la detection des menaces et la defense des systemes informatiques.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "L'IA au Service de la Cyberdefense" },
        { type: "paragraph", content: "Si l'IA est une arme pour les attaquants, elle est aussi le bouclier le plus puissant des defenseurs. Les systemes de securite bases sur l'IA analysent des millions d'evenements par seconde, detectent des anomalies invisibles a l'oeil humain, et automatisent les reponses aux incidents." },
        { type: "paragraph", content: "Les SIEM (Security Information and Event Management) de nouvelle generation integrent des modeles de machine learning pour correler les evenements, identifier les menaces zero-day, et reduire le temps de detection de mois a minutes." },
        { type: "subheading", content: "Detection d'Anomalies par ML" },
        { type: "paragraph", content: "L'apprentissage non supervise est particulierement efficace pour la detection d'anomalies. Le modele apprend le comportement 'normal' du reseau et alerte des que quelque chose devie : trafic inhabituel, acces anormal, transferts de donnees suspects. Cette approche detecte les menaces inconnues (zero-day) que les regles traditionnelles manquent." },
        { type: "subheading", content: "Analyse Comportementale (UEBA)" },
        { type: "paragraph", content: "L'User and Entity Behavior Analytics (UEBA) utilise l'IA pour profiler le comportement de chaque utilisateur et equipement. Si un employe accede soudainement a des fichiers sensibles a 3h du matin depuis un pays etranger, le systeme declenche une alerte immediatement." },
        { type: "callout", content: "CrowdStrike Falcon, SentinelOne, et Darktrace utilisent l'IA pour detecter et neutraliser les menaces en temps reel. Ces outils reduisent le temps moyen de detection (MTTD) de 197 jours a moins de 24 heures." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "L'IA defensive en cybersecurite" },
        { type: "heading", content: "Reponse Automatisee aux Incidents" },
        { type: "paragraph", content: "Les plateformes SOAR (Security Orchestration, Automation and Response) utilisent l'IA pour automatiser la reponse aux incidents : isolation automatique des machines compromises, blocage des IP malveillantes, revocation des acces compromis, et generation de rapports d'incident." },
        { type: "key-point", content: "L'IA ne remplace pas les analystes de securite — elle les augmente. Le modele ideal combine detection automatisee IA + validation humaine pour les cas complexes. C'est le concept de 'human-in-the-loop'." },
        { type: "diagram", label: "Stack de Cyberdefense IA", flow: "vertical", nodes: [
          { label: "SIEM IA", sub: "Correlation d'evenements en temps reel", color: "blue" },
          { label: "UEBA", sub: "Analyse comportementale utilisateurs", color: "purple" },
          { label: "EDR / XDR", sub: "Detection et reponse sur endpoints", color: "emerald" },
          { label: "SOAR", sub: "Automatisation de la reponse", color: "amber" },
        ]},
        { type: "diagram", label: "Reduction du Temps de Detection", flow: "horizontal", nodes: [
          { label: "Sans IA", sub: "MTTD : 197 jours en moyenne", color: "pink" },
          { label: "Avec IA", sub: "MTTD : moins de 24 heures", color: "emerald" },
          { label: "Impact", sub: "Reduction des degats de 80%", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA analyse des millions d'evenements par seconde pour detecter les menaces",
          "La detection d'anomalies par ML identifie les menaces zero-day inconnues",
          "L'UEBA profile le comportement de chaque utilisateur pour detecter les compromissions",
          "Les outils IA reduisent le MTTD de 197 jours a moins de 24 heures",
          "Le modele ideal combine IA automatisee et validation humaine (human-in-the-loop)",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que l'UEBA en cybersecurite ?",
          options: ["Un type de firewall", "L'analyse comportementale des utilisateurs et entites", "Un protocole reseau", "Un format de log"],
          correctIndex: 1,
          explanation: "UEBA (User and Entity Behavior Analytics) utilise l'IA pour profiler le comportement normal de chaque utilisateur et equipement, detectant les anomalies suspectes.",
        },
        {
          question: "De combien l'IA reduit-elle le temps moyen de detection (MTTD) ?",
          options: ["De 197 jours a 100 jours", "De 197 jours a moins de 24 heures", "De 30 jours a 7 jours", "De 365 jours a 30 jours"],
          correctIndex: 1,
          explanation: "Les outils de cybersecurite bases sur l'IA (CrowdStrike, SentinelOne, Darktrace) reduisent le MTTD de 197 jours en moyenne a moins de 24 heures.",
        },
        {
          question: "Que signifie SOAR en cybersecurite ?",
          options: ["Security Online Attack Response", "Security Orchestration, Automation and Response", "Secure Operations and Risk", "System Optimization and Recovery"],
          correctIndex: 1,
          explanation: "SOAR (Security Orchestration, Automation and Response) designe les plateformes qui automatisent la reponse aux incidents : isolation, blocage, revocation, rapports.",
        },
        {
          question: "Pourquoi l'IA ne remplace-t-elle pas les analystes de securite ?",
          options: ["Elle est trop chere", "Les cas complexes necessitent une validation humaine (human-in-the-loop)", "Elle est trop lente", "Elle ne detecte que les menaces connues"],
          correctIndex: 1,
          explanation: "L'IA augmente les analystes mais ne les remplace pas. Les cas complexes et les faux positifs necessitent un jugement humain — c'est le concept de human-in-the-loop.",
        },
      ],
    },
    {
      number: 6,
      title: "Securite des Modeles d'IA",
      description: "Attaques adversariales, empoisonnement de donnees et protection des modeles d'IA.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Proteger les Modeles d'IA Eux-Memes" },
        { type: "paragraph", content: "Les modeles d'IA ne sont pas seulement des outils de securite — ils sont aussi des cibles. Les attaquants cherchent a manipuler, corrompre ou voler les modeles IA. La securite des modeles est un domaine critique qui inclut la protection contre les attaques adversariales, l'empoisonnement de donnees, et le vol de propriete intellectuelle." },
        { type: "subheading", content: "Attaques Adversariales" },
        { type: "paragraph", content: "Une attaque adversariale consiste a modifier subtilement les entrees d'un modele pour le tromper. Un panneau stop avec quelques autocollants strategiques peut etre classifie comme un panneau de limitation de vitesse par un systeme de conduite autonome. Un pixel modifie dans une image peut changer completement la classification." },
        { type: "paragraph", content: "Ces attaques exploitent les faiblesses mathematiques des reseaux de neurones. Elles sont particulierement dangereuses dans les systemes critiques : vehicules autonomes, imagerie medicale, systemes de surveillance, et moderation de contenu." },
        { type: "subheading", content: "Empoisonnement de Donnees" },
        { type: "paragraph", content: "L'empoisonnement de donnees (data poisoning) consiste a contaminer les donnees d'entrainement d'un modele pour y inserer des backdoors. Par exemple, un attaquant peut inserer des exemples malveillants dans un dataset open source pour que le modele entraine dessus se comporte de maniere specifique face a certains declencheurs." },
        { type: "callout", content: "En 2025, des chercheurs ont demontre qu'en modifiant seulement 0,01% des donnees d'entrainement d'un LLM, ils pouvaient y inserer un backdoor indetectable qui s'active face a un mot-declencheur specifique." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Attaques adversariales expliquees" },
        { type: "heading", content: "Protections et Bonnes Pratiques" },
        { type: "paragraph", content: "Les defenses incluent : l'entrainement adversarial (exposer le modele a des exemples adversariaux pendant l'entrainement), la detection d'entrees anormales, la verification cryptographique des datasets, le red teaming (tests d'intrusion sur les modeles), et l'utilisation de gardrails pour limiter les comportements du modele." },
        { type: "key-point", content: "Le red teaming des modeles IA est devenu une pratique standard. Anthropic, OpenAI et Google emploient des equipes dediees pour tester la robustesse de leurs modeles avant chaque release." },
        { type: "diagram", label: "Menaces sur les Modeles d'IA", flow: "horizontal", nodes: [
          { label: "Attaques adversariales", sub: "Manipulation des entrees", color: "pink" },
          { label: "Empoisonnement", sub: "Contamination des donnees", color: "purple" },
          { label: "Vol de modele", sub: "Extraction de propriete intellectuelle", color: "amber" },
        ]},
        { type: "tip", content: "Si vous deployez un modele IA en production, integrez systematiquement des tests adversariaux dans votre pipeline CI/CD. La robustesse se teste avant le deploiement, pas apres." },
        { type: "summary", items: [
          "Les modeles d'IA sont des cibles : attaques adversariales, empoisonnement, vol",
          "Les attaques adversariales trompent les modeles avec des modifications subtiles",
          "L'empoisonnement de donnees insere des backdoors dans les modeles entraines",
          "Les defenses incluent l'entrainement adversarial et le red teaming",
          "La securite des modeles doit etre integree des la conception (security by design)",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce qu'une attaque adversariale ?",
          options: ["Un virus qui detruit un modele IA", "Une modification subtile des entrees pour tromper le modele", "Un DDoS contre un serveur IA", "Un vol de donnees d'entrainement"],
          correctIndex: 1,
          explanation: "Une attaque adversariale modifie subtilement les entrees d'un modele (image, texte) pour le tromper et obtenir une classification ou une reponse incorrecte.",
        },
        {
          question: "Qu'est-ce que l'empoisonnement de donnees ?",
          options: ["La suppression des donnees d'entrainement", "La contamination des donnees d'entrainement pour inserer des backdoors", "La corruption du modele apres deploiement", "Le chiffrement des donnees par un ransomware"],
          correctIndex: 1,
          explanation: "L'empoisonnement de donnees consiste a contaminer les donnees d'entrainement avec des exemples malveillants, inserant des backdoors activables par des declencheurs specifiques.",
        },
        {
          question: "Quelle proportion des donnees d'entrainement suffit pour inserer un backdoor ?",
          options: ["10%", "1%", "0,01%", "50%"],
          correctIndex: 2,
          explanation: "Des chercheurs ont demontre qu'en modifiant seulement 0,01% des donnees d'entrainement d'un LLM, ils pouvaient y inserer un backdoor indetectable.",
        },
        {
          question: "Qu'est-ce que le red teaming des modeles IA ?",
          options: ["La mise a jour des modeles", "Des tests d'intrusion sur les modeles pour evaluer leur robustesse", "La formation des equipes de securite", "Le deploiement en production"],
          correctIndex: 1,
          explanation: "Le red teaming consiste a tester systematiquement la robustesse des modeles IA en simulant des attaques pour identifier les vulnerabilites avant le deploiement.",
        },
      ],
    },
    {
      number: 7,
      title: "Protection des Donnees et IA",
      description: "RGPD, vie privee, anonymisation — proteger les donnees a l'ere de l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Donnees et IA : Un Equilibre Delicat" },
        { type: "paragraph", content: "L'IA est vorace en donnees. Les modeles de langage sont entraines sur des milliards de textes, les systemes de reconnaissance faciale sur des millions de visages. Cette dependance aux donnees souleve des questions cruciales de vie privee, de consentement, et de conformite reglementaire." },
        { type: "paragraph", content: "Le RGPD europeen et l'AI Act imposent des obligations strictes sur la collecte, le traitement et la conservation des donnees utilisees par l'IA. Les violations peuvent couter jusqu'a 4% du chiffre d'affaires mondial ou 20 millions d'euros." },
        { type: "subheading", content: "Risques de Fuite de Donnees par l'IA" },
        { type: "paragraph", content: "Les LLM peuvent memoriser et regurgiter des donnees sensibles de leur entrainement. Un employe qui colle du code source proprietaire ou des donnees clients dans ChatGPT risque de voir ces informations accessibles a d'autres utilisateurs. Samsung a interdit ChatGPT apres qu'un ingenieur ait colle du code source confidentiel." },
        { type: "callout", content: "En 2025, des chercheurs ont reussi a extraire des numeros de telephone, adresses email et extraits de code source des donnees d'entrainement de GPT-3.5 par des techniques de prompt specifiques. La memorisation non intentionnelle est un risque reel." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Protection des donnees et IA" },
        { type: "heading", content: "Techniques de Protection" },
        { type: "paragraph", content: "Plusieurs techniques protegent les donnees dans le contexte IA : l'anonymisation et la pseudonymisation des datasets, le differential privacy (ajout de bruit statistique pour proteger les individus), l'apprentissage federe (le modele va aux donnees plutot que l'inverse), et le chiffrement homomorphe (calculs sur des donnees chiffrees)." },
        { type: "key-point", content: "L'apprentissage federe est une revolution pour la vie privee : le modele est entraine localement sur chaque appareil et seuls les gradients agreges sont partages. Les donnees brutes ne quittent jamais l'appareil de l'utilisateur." },
        { type: "diagram", label: "Techniques de Protection des Donnees IA", flow: "horizontal", nodes: [
          { label: "Anonymisation", sub: "Supprimer les identifiants personnels", color: "blue" },
          { label: "Differential Privacy", sub: "Bruit statistique protecteur", color: "purple" },
          { label: "Apprentissage federe", sub: "Donnees locales, modele distribue", color: "emerald" },
          { label: "Chiffrement homomorphe", sub: "Calcul sur donnees chiffrees", color: "amber" },
        ]},
        { type: "tip", content: "Avant d'utiliser un outil IA en entreprise, verifiez sa politique de donnees. Privilegiez les outils qui ne retiennent pas vos donnees pour l'entrainement (Claude API, ChatGPT Enterprise, etc.)." },
        { type: "summary", items: [
          "Les LLM peuvent memoriser et regurgiter des donnees sensibles de leur entrainement",
          "Le RGPD impose des amendes jusqu'a 4% du CA mondial pour non-conformite",
          "L'anonymisation, le differential privacy et l'apprentissage federe protegent les donnees",
          "Ne jamais coller de donnees sensibles dans un LLM grand public",
          "Verifier la politique de donnees de chaque outil IA avant usage professionnel",
        ]},
      ],
      quiz: [
        {
          question: "Pourquoi Samsung a-t-elle interdit ChatGPT ?",
          options: ["A cause du cout", "Un ingenieur a colle du code source confidentiel", "ChatGPT etait trop lent", "Pour des raisons de concurrence"],
          correctIndex: 1,
          explanation: "Samsung a interdit ChatGPT apres qu'un ingenieur ait colle du code source proprietaire dans le chatbot, risquant de voir ces informations utilisees dans l'entrainement du modele.",
        },
        {
          question: "Qu'est-ce que l'apprentissage federe ?",
          options: ["Un modele entraine dans plusieurs pays", "Un entrainement ou les donnees restent locales et seuls les gradients sont partages", "Un reseau de modeles interconnectes", "Un type de cloud computing"],
          correctIndex: 1,
          explanation: "L'apprentissage federe entraine le modele localement sur chaque appareil et ne partage que les gradients agreges. Les donnees brutes ne quittent jamais l'appareil de l'utilisateur.",
        },
        {
          question: "Quelle amende maximale le RGPD prevoit-il pour les violations de donnees ?",
          options: ["1% du CA mondial", "4% du CA mondial ou 20M EUR", "10 millions d'euros", "100 000 euros"],
          correctIndex: 1,
          explanation: "Le RGPD prevoit des amendes pouvant atteindre 4% du chiffre d'affaires mondial annuel ou 20 millions d'euros, selon le montant le plus eleve.",
        },
        {
          question: "Qu'est-ce que le differential privacy ?",
          options: ["Un type de chiffrement", "L'ajout de bruit statistique pour proteger les donnees individuelles", "Une politique de confidentialite", "Un protocole de reseau securise"],
          correctIndex: 1,
          explanation: "Le differential privacy ajoute un bruit statistique calibre aux donnees ou aux resultats, rendant impossible l'identification d'un individu specifique tout en preservant l'utilite des donnees agregees.",
        },
      ],
    },
    {
      number: 8,
      title: "Audit de Securite Assiste par l'IA",
      description: "Utiliser l'IA pour auditer la securite des systemes, du code et des processus.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "L'IA Transforme l'Audit de Securite" },
        { type: "paragraph", content: "Les audits de securite traditionnels sont longs, couteux et ponctuels. L'IA transforme cette pratique en permettant des audits continus, automatises et exhaustifs. Les outils d'audit IA analysent le code source, les configurations reseau, les politiques d'acces, et les logs en permanence." },
        { type: "paragraph", content: "En 2026, les outils d'audit IA detectent jusqu'a 95% des vulnerabilites connues automatiquement, contre 60% pour les scanners traditionnels. Ils identifient egalement des patterns de vulnerabilites zero-day que les outils classiques manquent." },
        { type: "subheading", content: "Audit de Code Source par IA" },
        { type: "paragraph", content: "Les LLM excellent dans la revue de code securite. Claude Code, GitHub Copilot et Snyk AI analysent le code pour identifier les injections SQL, XSS, CSRF, gestion insecure des secrets, et autres vulnerabilites OWASP Top 10. Ils suggerent des corrections en contexte." },
        { type: "callout", content: "GitHub Copilot a detecte et bloque plus de 40% de code potentiellement vulnerable avant qu'il soit commite en 2025. L'IA comme garde-fou pendant le developpement, pas seulement apres." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Audit de securite IA en pratique" },
        { type: "subheading", content: "Audit de Configuration et Infrastructure" },
        { type: "paragraph", content: "L'IA audite les configurations cloud (AWS, GCP, Azure) pour detecter les buckets S3 publics, les groupes de securite trop permissifs, les secrets en clair, et les certificats expirs. Des outils comme Prisma Cloud et Wiz utilisent le ML pour prioriser les risques et reduire le bruit." },
        { type: "heading", content: "Tests de Penetration Automatises" },
        { type: "paragraph", content: "Les pentests assistes par IA combinent la creativite des LLM avec la rigueur des scanners. PentestGPT et BurpGPT utilisent des LLM pour generer des payloads de test personnalises, enchainer les etapes d'exploitation, et generer des rapports detailles." },
        { type: "key-point", content: "L'audit IA continu est plus efficace que l'audit ponctuel. Integrez les outils d'audit IA dans votre pipeline CI/CD pour scanner chaque commit et chaque deploiement automatiquement." },
        { type: "prompt-example", prompt: "Analyse ce fichier de configuration nginx et identifie toutes les vulnerabilites de securite, les headers manquants, et les bonnes pratiques non respectees. [coller la config]", result: "L'IA identifie : headers de securite manquants (CSP, HSTS, X-Frame-Options), TLS 1.0/1.1 encore actif, server_tokens on, absence de rate limiting." },
        { type: "diagram", label: "Pipeline d'Audit Securite IA", flow: "horizontal", nodes: [
          { label: "Code Source", sub: "Snyk AI, Copilot, Claude Code", color: "blue" },
          { label: "Infrastructure", sub: "Prisma Cloud, Wiz, ScoutSuite", color: "purple" },
          { label: "Pentest IA", sub: "PentestGPT, BurpGPT", color: "pink" },
          { label: "Rapport & Priorisation", sub: "Scoring de risques ML", color: "emerald" },
        ]},
        { type: "summary", items: [
          "L'IA detecte 95% des vulnerabilites connues vs 60% pour les scanners classiques",
          "Les LLM analysent le code pour les vulnerabilites OWASP Top 10",
          "L'audit IA des configurations cloud detecte buckets publics et secrets en clair",
          "Les pentests IA combinent creativite LLM et rigueur des scanners",
          "Integrer l'audit IA en continu dans le pipeline CI/CD est la meilleure pratique",
        ]},
      ],
      quiz: [
        {
          question: "Quel pourcentage de vulnerabilites les outils d'audit IA detectent-ils ?",
          options: ["40%", "60%", "80%", "95%"],
          correctIndex: 3,
          explanation: "Les outils d'audit IA detectent jusqu'a 95% des vulnerabilites connues automatiquement, contre 60% pour les scanners traditionnels.",
        },
        {
          question: "Qu'est-ce que l'OWASP Top 10 ?",
          options: ["Les 10 meilleurs antivirus", "Les 10 vulnerabilites web les plus critiques", "Les 10 meilleurs langages de programmation", "Les 10 plus grandes entreprises de cybersecurite"],
          correctIndex: 1,
          explanation: "L'OWASP Top 10 est la liste des 10 categories de vulnerabilites web les plus critiques, incluant les injections SQL, XSS, CSRF, et la gestion insecure des authentifications.",
        },
        {
          question: "Pourquoi l'audit IA continu est-il preferable a l'audit ponctuel ?",
          options: ["Il est moins cher", "Il scanne chaque commit et deploiement en temps reel", "Il ne necessite pas de competences", "Il remplace les pentests manuels"],
          correctIndex: 1,
          explanation: "L'audit IA continu integre dans le CI/CD scanne chaque commit et deploiement, detectant les vulnerabilites immediatement plutot qu'une fois par trimestre.",
        },
        {
          question: "Quel outil IA a bloque 40% de code vulnerable avant le commit ?",
          options: ["ChatGPT", "GitHub Copilot", "Midjourney", "Sora"],
          correctIndex: 1,
          explanation: "GitHub Copilot a detecte et bloque plus de 40% de code potentiellement vulnerable avant qu'il ne soit commite, agissant comme garde-fou pendant le developpement.",
        },
      ],
    },
    {
      number: 9,
      title: "Reponse aux Incidents avec l'IA",
      description: "Automatiser et accelerer la reponse aux incidents de securite grace a l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Accelerer la Reponse aux Incidents" },
        { type: "paragraph", content: "Quand une cyberattaque survient, chaque minute compte. Le temps moyen de reponse a un incident (MTTR) est de 73 jours sans IA. Avec l'IA, ce temps chute a quelques heures. L'automatisation de la reponse est devenue indispensable face au volume et a la vitesse des attaques modernes." },
        { type: "paragraph", content: "Les plateformes SOAR (Security Orchestration, Automation and Response) modernes utilisent l'IA pour orchestrer la reponse : triage automatique des alertes, enrichissement contextuel, containment automatise, investigation forensique, et generation de rapports reglementaires." },
        { type: "subheading", content: "Triage Intelligent des Alertes" },
        { type: "paragraph", content: "Les equipes SOC (Security Operations Center) recoivent des milliers d'alertes par jour. L'IA trie ces alertes par priorite, corrige les alertes, elimine les faux positifs (jusqu'a 80%), et regroupe les alertes correlees en incidents uniques. Les analystes se concentrent sur les vrais problemes." },
        { type: "subheading", content: "Investigation Forensique Assistee" },
        { type: "paragraph", content: "L'IA accelere l'investigation forensique en analysant automatiquement les logs, les captures reseau, la memoire et les disques. Elle reconstruit la chronologie de l'attaque (kill chain), identifie les indicateurs de compromission (IoC), et determine l'etendue de la breche." },
        { type: "callout", content: "Microsoft Security Copilot utilise GPT-4 pour permettre aux analystes de poser des questions en langage naturel : 'Quels fichiers ont ete accedes par cet utilisateur compromis dans les dernieres 48h ?' — et obtenir une reponse en secondes." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Reponse aux incidents avec l'IA" },
        { type: "heading", content: "Playbooks de Reponse Automatises" },
        { type: "paragraph", content: "Les playbooks automatises definissent les actions a prendre pour chaque type d'incident. L'IA les execute instantanement : isoler la machine compromise, revoquer les sessions actives, scanner les systemes adjacents, notifier les equipes, et documenter chaque action pour la conformite." },
        { type: "key-point", content: "L'IA reduit le 'alert fatigue' des equipes SOC. En eliminant 80% des faux positifs et en automatisant le triage, les analystes peuvent se concentrer sur les incidents critiques au lieu de noyer dans le bruit." },
        { type: "diagram", label: "Pipeline de Reponse aux Incidents IA", flow: "vertical", nodes: [
          { label: "Detection", sub: "SIEM IA detecte l'anomalie", color: "pink" },
          { label: "Triage", sub: "IA priorise et elimine les faux positifs", color: "blue" },
          { label: "Investigation", sub: "Forensique automatisee, kill chain", color: "purple" },
          { label: "Containment", sub: "Isolation et blocage automatises", color: "amber" },
          { label: "Remediation", sub: "Correction, rapport, retour d'experience", color: "emerald" },
        ]},
        { type: "summary", items: [
          "L'IA reduit le MTTR de 73 jours a quelques heures",
          "Le triage IA elimine 80% des faux positifs",
          "L'investigation forensique IA reconstruit la kill chain automatiquement",
          "Les playbooks automatises executent la reponse en secondes",
          "Microsoft Security Copilot permet l'investigation en langage naturel",
        ]},
      ],
      quiz: [
        {
          question: "Quel est le temps moyen de reponse a un incident sans IA ?",
          options: ["7 jours", "30 jours", "73 jours", "365 jours"],
          correctIndex: 2,
          explanation: "Le temps moyen de reponse a un incident (MTTR) est de 73 jours sans IA. Avec l'IA, ce temps chute a quelques heures.",
        },
        {
          question: "Quel pourcentage de faux positifs l'IA peut-elle eliminer ?",
          options: ["30%", "50%", "80%", "100%"],
          correctIndex: 2,
          explanation: "L'IA elimine jusqu'a 80% des faux positifs dans les alertes de securite, reduisant considerablement la fatigue des analystes SOC.",
        },
        {
          question: "Qu'est-ce qu'une kill chain en cybersecurite ?",
          options: ["Un type de malware", "La chronologie des etapes d'une attaque", "Un outil de defense", "Un protocole de communication"],
          correctIndex: 1,
          explanation: "La kill chain est la chronologie des etapes d'une cyberattaque, de la reconnaissance initiale a l'exfiltration de donnees. L'IA peut la reconstruire automatiquement.",
        },
        {
          question: "Qu'est-ce que l'alert fatigue ?",
          options: ["Un bug dans les systemes d'alerte", "L'epuisement des analystes face au volume d'alertes", "La desactivation des alertes", "Un type d'attaque DDoS"],
          correctIndex: 1,
          explanation: "L'alert fatigue est l'epuisement des analystes SOC face aux milliers d'alertes quotidiennes, dont la majorite sont des faux positifs. L'IA reduit ce probleme en triant et priorisant automatiquement.",
        },
      ],
    },
    {
      number: 10,
      title: "Strategie de Cybersecurite IA",
      description: "Construire une strategie de cybersecurite integrant l'IA pour votre organisation.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Construire une Strategie de Cybersecurite IA" },
        { type: "paragraph", content: "Une strategie de cybersecurite IA ne se resume pas a acheter des outils. C'est une approche holistique qui integre la technologie, les processus, les personnes et la gouvernance. En 2026, les organisations matures adoptent le paradigme 'AI-First Security' — l'IA est au coeur de chaque couche de defense." },
        { type: "paragraph", content: "Cette strategie doit couvrir la prevention (reduire la surface d'attaque), la detection (identifier les menaces en temps reel), la reponse (reagir rapidement aux incidents), et la recovery (restaurer les operations normales). L'IA intervient a chaque etape." },
        { type: "subheading", content: "Le Framework Zero Trust + IA" },
        { type: "paragraph", content: "Le Zero Trust ('ne jamais faire confiance, toujours verifier') est le fondement de la cybersecurite moderne. L'IA enrichit ce framework en evaluant en continu le niveau de confiance de chaque utilisateur, appareil et connexion. L'authentification adaptative ajuste les exigences de securite selon le contexte." },
        { type: "subheading", content: "Formation et Sensibilisation" },
        { type: "paragraph", content: "La technologie seule ne suffit pas. 85% des violations impliquent un facteur humain. Les programmes de sensibilisation IA simulent des attaques de phishing personnalisees, forment les employes avec des scenarios realistes, et mesurent l'amelioration continue." },
        { type: "callout", content: "Les organisations avec un programme de sensibilisation IA ont 3x moins de chances d'etre victimes de phishing. L'investissement dans la formation est le meilleur ROI en cybersecurite." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Strategie de cybersecurite IA" },
        { type: "heading", content: "Feuille de Route Implementee" },
        { type: "paragraph", content: "Phase 1 (Mois 1-3) : Audit de maturite, deploiement EDR/XDR IA, formation des equipes. Phase 2 (Mois 4-6) : SIEM IA, UEBA, automatisation SOAR. Phase 3 (Mois 7-12) : Zero Trust complet, threat hunting proactif, red teaming continu." },
        { type: "key-point", content: "Le budget cybersecurite recommande en 2026 est de 10-15% du budget IT total. Les organisations qui investissent proactivement depensent 3x moins en remediation post-incident que celles qui reagissent." },
        { type: "diagram", label: "Feuille de Route Cybersecurite IA", flow: "vertical", nodes: [
          { label: "Phase 1 : Fondations", sub: "Audit, EDR/XDR, formation (Mois 1-3)", color: "blue" },
          { label: "Phase 2 : Detection", sub: "SIEM IA, UEBA, SOAR (Mois 4-6)", color: "purple" },
          { label: "Phase 3 : Maturite", sub: "Zero Trust, threat hunting (Mois 7-12)", color: "emerald" },
        ]},
        { type: "diagram", label: "Les 4 Piliers de la Cybersecurite IA", flow: "horizontal", nodes: [
          { label: "Prevention", sub: "Reduire la surface d'attaque", color: "blue" },
          { label: "Detection", sub: "Identifier les menaces en temps reel", color: "purple" },
          { label: "Reponse", sub: "Reagir rapidement aux incidents", color: "amber" },
          { label: "Recovery", sub: "Restaurer les operations", color: "emerald" },
        ]},
        { type: "tip", content: "Commencez par les quick wins : EDR IA sur tous les postes, MFA partout, et un programme de sensibilisation au phishing. Ces trois mesures bloquent 80% des attaques courantes." },
        { type: "summary", items: [
          "La strategie cybersecurite IA est holistique : technologie, processus, personnes, gouvernance",
          "Le Zero Trust + IA est le fondement de la securite moderne",
          "85% des violations impliquent un facteur humain — la formation est essentielle",
          "Budget recommande : 10-15% du budget IT total",
          "Quick wins : EDR IA + MFA + sensibilisation bloquent 80% des attaques",
        ]},
      ],
      quiz: [
        {
          question: "Quel pourcentage des violations implique un facteur humain ?",
          options: ["25%", "50%", "70%", "85%"],
          correctIndex: 3,
          explanation: "85% des violations de securite impliquent un facteur humain (erreur, negligence, manipulation). C'est pourquoi la formation et la sensibilisation sont essentielles.",
        },
        {
          question: "Qu'est-ce que le Zero Trust ?",
          options: ["Ne jamais utiliser l'IA", "Ne jamais faire confiance, toujours verifier", "Ne jamais se connecter a Internet", "Ne jamais partager ses mots de passe"],
          correctIndex: 1,
          explanation: "Le Zero Trust est un paradigme de securite qui stipule de ne jamais faire confiance par defaut et de toujours verifier chaque utilisateur, appareil et connexion.",
        },
        {
          question: "Quel budget cybersecurite est recommande en 2026 ?",
          options: ["1-3% du budget IT", "5-7% du budget IT", "10-15% du budget IT", "25% du budget IT"],
          correctIndex: 2,
          explanation: "Le budget cybersecurite recommande en 2026 est de 10-15% du budget IT total. Les organisations qui investissent proactivement depensent 3x moins en remediation.",
        },
        {
          question: "Quels sont les 3 quick wins en cybersecurite ?",
          options: ["VPN, antivirus, pare-feu", "EDR IA, MFA, sensibilisation au phishing", "Cloud, blockchain, quantique", "Chiffrement, backup, monitoring"],
          correctIndex: 1,
          explanation: "EDR IA sur tous les postes, MFA (authentification multi-facteurs) partout, et un programme de sensibilisation au phishing bloquent 80% des attaques courantes.",
        },
      ],
    },
  ],
};

export default content;
