import type { CourseContent } from "../types";

const content: CourseContent = {
  slug: "cybersecurite-ia",
  chapters: [
    {
      number: 1,
      title: "Introduction a la Cybersécurité IA",
      description: "Comprendre les enjeux de la cybersécurité à l'ère de l'intelligence artificielle.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "La Cybersécurité à l'Ère de l'IA" },
        { type: "paragraph", content: "La cybersécurité a toujours été une course entre attaquants et défenseurs. Avec l'arrivée de l'intelligence artificielle, cette course s'accélère drastiquement. L'IA donne aux attaquants des capacités inédites pour automatiser et sophistiquer leurs attaques, mais elle offre aussi aux défenseurs des outils puissants pour détecter et neutraliser les menaces." },
        { type: "paragraph", content: "En 2026, les cyberattaques assistées par l'IA représentent plus de 40% des incidents majeurs. Les deepfakes, le phishing génère par LLM, les malwares polymorphes et l'ingénierie sociale automatisée sont devenus des menaces quotidiennes pour les entreprises et les individus." },
        { type: "callout", content: "Selon le rapport IBM X-Force 2026, le coût moyen d'une violation de données a atteint 5,2 millions de dollars, en hausse de 15% par rapport à 2024. L'IA est à la fois le problème et la solution." },
        { type: "video", videoId: "bPVaOlJ6ln0",
      videoDurationMinutes: 12, label: "Introduction a la Cybersécurité IA" },
        { type: "heading", content: "Pourquoi l'IA Change la Donne" },
        { type: "paragraph", content: "L'IA transformé la cybersécurité de trois manières fondamentales : elle automatisé les attaques a une échelle sans précédent, elle rend les attaques plus convaincantes et difficiles a détecter, et elle permet aux défenseurs d'analyser des millions d'événements en temps réel." },
        { type: "subheading", content: "Le Paysage des Menaces en 2026" },
        { type: "paragraph", content: "Les organisations font face à des attaques de plus en plus sophistiquees : phishing hyper-personnalisé génère par GPT-5.4, deepfakes video en temps réel pour l'usurpation d'identité, malwares qui mutent automatiquement pour echapper a la détection, et attaques adversariales contre les modèles d'IA eux-mêmes." },
        { type: "key-point", content: "La cybersécurité IA n'est pas une spécialité de niche — c'est une compétence essentielle pour tout professionnel du numérique en 2026. Chaque utilisateur d'IA doit comprendre les risques et les protections." },
        { type: "diagram", label: "L'IA dans la Cybersécurité : Double Tranchant", flow: "horizontal", nodes: [
          { label: "IA Offensive", sub: "Phishing, deepfakes, malwares", color: "pink" },
          { label: "IA Defensive", sub: "Détection, réponse, prévention", color: "emerald" },
          { label: "Course aux Armements", sub: "Escalade continue attaque/défense", color: "amber" },
        ]},
        { type: "tip", content: "Ce cours couvre les deux côtés : comprendre les attaques pour mieux se défendre. La meilleure défense commence par la connaissance des techniques offensives." },
        { type: "summary", items: [
          "L'IA accélère la course entre attaquants et défenseurs en cybersécurité",
          "40% des incidents majeurs en 2026 impliquent de l'IA",
          "Le coût moyen d'une violation de données atteint 5,2 millions de dollars",
          "L'IA est à la fois le problème (attaques) et la solution (défense)",
          "La cybersécurité IA est une compétence essentielle pour tous",
        ]},
      ],
      quiz: [
        {
          question: "Quel pourcentage des incidents majeurs en 2026 implique l'IA ?",
          options: ["10%", "25%", "40%", "60%"],
          correctIndex: 2,
          explanation: "En 2026, les cyberattaques assistées par l'IA représentent plus de 40% des incidents majeurs, selon les rapports de cybersécurité.",
        },
        {
          question: "Comment l'IA transformé-t-elle la cybersécurité ?",
          options: ["Elle remplace complètement les experts humains", "Elle automatisé les attaques et renforce les défenses", "Elle élimine tous les risques de piratage", "Elle ne concerne que les grandes entreprises"],
          correctIndex: 1,
          explanation: "L'IA est un outil a double tranchant : elle automatisé et sophistique les attaques, mais offre aussi des outils puissants de détection et de défense.",
        },
        {
          question: "Quel est le coût moyen d'une violation de données en 2026 ?",
          options: ["1,5 million de dollars", "3,8 millions de dollars", "5,2 millions de dollars", "10 millions de dollars"],
          correctIndex: 2,
          explanation: "Selon le rapport IBM X-Force 2026, le coût moyen d'une violation de données a atteint 5,2 millions de dollars, en hausse de 15% par rapport à 2024.",
        },
        {
          question: "Pourquoi la cybersécurité IA concerne-t-elle tous les professionnels ?",
          options: ["Parce que tout le monde doit devenir hacker", "Parce que les menaces IA touchent tous les utilisateurs du numérique", "Parce que c'est obligatoire par la loi", "Parce que les antivirus ne fonctionnent plus"],
          correctIndex: 1,
          explanation: "Les menaces basées sur l'IA (phishing, deepfakes, ingénierie sociale) ciblent tous les utilisateurs du numérique, rendant cette compétence essentielle pour tous.",
        },
      ],
    },
    {
      number: 2,
      title: "Menaces Generees par l'IA",
      description: "Cartographie complète des cybermenaces augmentees par l'intelligence artificielle.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Les Menaces IA : Une Nouvelle Génération d'Attaques" },
        { type: "paragraph", content: "L'intelligence artificielle a ouvert la boîte de Pandore des cybermenaces. Les attaquants utilisent désormais des LLM pour générer des emails de phishing parfaits, des outils de génération d'images pour créer des deepfakes convaincants, et des algorithmes d'apprentissage pour concevoir des malwares qui echappent a la détection." },
        { type: "subheading", content: "Malwares Polymorphes et Evasifs" },
        { type: "paragraph", content: "Les malwares assistés par l'IA peuvent modifier leur code automatiquement à chaque exécution pour echapper aux signatures antivirus. Ils analysent l'environnement de la ciblé et adaptent leur comportement en consequence. En 2026, ces malwares polymorphes représentent 30% des nouvelles souches détectées." },
        { type: "subheading", content: "Attaques par Injection de Prompt" },
        { type: "paragraph", content: "Les systèmes bases sur des LLM sont vulnérables aux injections de prompt : un attaquant insere des instructions malveillantes dans les données que le modèle traité. Cela peut conduire à l'exfiltration de données, au contournement des garde-fous, ou à l'exécution d'actions non autorisees." },
        { type: "callout", content: "En 2025, une attaque par injection de prompt sur un chatbot bancaire a permis à des attaquants d'acceder aux informations de 50 000 clients. Les injections de prompt sont le nouveau SQL injection." },
        { type: "video", videoId: "pg19Z8LL06w",
      videoDurationMinutes: 68, label: "Les cybermenaces IA expliquees" },
        { type: "subheading", content: "Reconnaissance Automatisee" },
        { type: "paragraph", content: "L'IA permet aux attaquants de scanner automatiquement des milliers de ciblés, d'analyser les réseaux sociaux pour profiler les victimes, et d'identifier les vulnérabilités des systèmes en quelques minutes au lieu de jours. Les outils OSINT (Open Source Intelligence) boostes à l'IA rendent la phase de reconnaissance devastatrice." },
        { type: "key-point", content: "Les attaques IA ne sont pas reservees aux hackers sophistiques. Des outils comme WormGPT et FraudGPT, vendus sur le dark web, permettent à n'importé qui de lancer des attaques IA sans compétences techniques." },
        { type: "diagram", label: "Taxonomie des Menaces IA", flow: "vertical", nodes: [
          { label: "Phishing IA", sub: "Emails et messages générés par LLM", color: "pink" },
          { label: "Deepfakes", sub: "Vidéo, audio, images falsifiees", color: "purple" },
          { label: "Malwares polymorphes", sub: "Code qui mute automatiquement", color: "blue" },
          { label: "Injection de prompt", sub: "Manipulation des systèmes LLM", color: "amber" },
          { label: "Reconnaissance OSINT", sub: "Profilage automatisé des ciblés", color: "emerald" },
        ]},
        { type: "prompt-example", prompt: "Analyse cette liste d'emails reçus et identifié ceux qui pourraient être du phishing génère par IA. Explique les indices pour chacun.", result: "L'IA peut vous aider a détecter les tentatives de phishing en analysant le style, la cohérence et les meta-données des messages suspects." },
        { type: "summary", items: [
          "Les malwares polymorphes IA représentent 30% des nouvelles souches en 2026",
          "L'injection de prompt est le nouveau vecteur d'attaque contre les systèmes LLM",
          "Les outils OSINT IA automatisent la reconnaissance des ciblés",
          "WormGPT et FraudGPT democratisent les attaques IA sur le dark web",
          "Chaque nouvelle capacité IA créé de nouveaux vecteurs d'attaque",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce qu'un malware polymorphe ?",
          options: ["Un virus qui attaque plusieurs systèmes", "Un malware qui modifié son code automatiquement", "Un logiciel qui se dupliqué", "Un virus qui fonctionne sur plusieurs OS"],
          correctIndex: 1,
          explanation: "Un malware polymorphe modifié automatiquement son code à chaque exécution pour echapper aux signatures antivirus, rendant sa détection traditionnelle inefficace.",
        },
        {
          question: "Qu'est-ce qu'une injection de prompt ?",
          options: ["Un bug dans un programmé", "L'insertion d'instructions malveillantes dans les données traitées par un LLM", "Une technique de programmation", "Un type de virus informatique"],
          correctIndex: 1,
          explanation: "L'injection de prompt consiste à inserer des instructions malveillantes dans les données que le modèle traité, pouvant conduire à l'exfiltration de données ou au contournement des garde-fous.",
        },
        {
          question: "Que sont WormGPT et FraudGPT ?",
          options: ["Des outils de sécurité officiels", "Des LLM malveillants vendus sur le dark web", "Des antivirus nouvelle génération", "Des modèles open source de recherche"],
          correctIndex: 1,
          explanation: "WormGPT et FraudGPT sont des LLM malveillants vendus sur le dark web, permettant a n'importé qui de générer des attaques de phishing ou des malwares sans compétences techniques.",
        },
        {
          question: "Comment l'IA améliore-t-elle la phase de reconnaissance des attaquants ?",
          options: ["Elle ne l'améliore pas", "Elle automatisé le scan des ciblés et le profilage via OSINT", "Elle remplace le besoin de reconnaissance", "Elle bloque les attaques avant la reconnaissance"],
          correctIndex: 1,
          explanation: "L'IA permet de scanner automatiquement des milliers de ciblés, d'analyser les réseaux sociaux et d'identifier les vulnérabilités en quelques minutes grâce aux outils OSINT boostes.",
        },
      ],
    },
    {
      number: 3,
      title: "Phishing et Ingénierie Sociale IA",
      description: "Comment l'IA rend le phishing et l'ingénierie sociale plus dangereux que jamais.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Le Phishing à l'Ère de l'IA" },
        { type: "paragraph", content: "Le phishing est l'attaque la plus courante et la plus efficace en cybersécurité. Avec l'IA, il atteint un niveau de sophistication sans précédent. Les LLM generent des emails parfaitement rédigés, personnalisés et sans fautes — les indices traditionnels de phishing (fautes d'orthographe, mise en page douteuse) disparaissent." },
        { type: "paragraph", content: "Les attaques de spear-phishing (phishing ciblé) sont désormais automatisees : l'IA analyse les profils LinkedIn, les publications sur les réseaux sociaux, et les communications publiques pour créer des messages ultra-personnalisés qui referent a des projets réels, des collègues existants, et des événements récents." },
        { type: "subheading", content: "Vishing : L'Arnaque Vocale IA" },
        { type: "paragraph", content: "Le vishing (voice phishing) exploite la synthese vocale IA. Un attaquant peut cloner la voix d'un PDG en 3 secondes d'echantillon audio et appeler le directeur financier pour ordonner un virement urgent. En 2025, une entreprise de Hong Kong a perdu 25 millions de dollars suite à un appel deepfake du 'PDG'." },
        { type: "callout", content: "Les emails de phishing générés par GPT-4 ont un taux de clic 4 à 5 fois supérieur aux emails de phishing traditionnels. Avec GPT-5.4, ce taux est encore plus élève grâce à la personnalisation contextuelle." },
        { type: "video", videoId: "JEBDfGqrAUA",
      videoDurationMinutes: 72, label: "Le phishing IA en action" },
        { type: "heading", content: "Techniques d'Ingénierie Sociale Augmentee" },
        { type: "paragraph", content: "L'ingénierie sociale IA va au-dela du simple email. Les attaquants utilisent des chatbots IA pour maintenir des conversations convaincantes sur plusieurs jours, des deepfakes en visioconference pour usurper des identités, et des profils sociaux générés par IA pour infiltrer des organisations." },
        { type: "key-point", content: "La règle numero 1 face au phishing IA : ne jamais se fier a un seul canal de communication. Verifiez toujours par un autre canal (téléphone, en personne) avant d'effectuer une action sensible." },
        { type: "diagram", label: "Évolution du Phishing", flow: "horizontal", nodes: [
          { label: "Phishing classique", sub: "Emails génériques, fautes, urgence", color: "blue" },
          { label: "Spear-phishing IA", sub: "Personnalisé, sans fautes, contextuel", color: "purple" },
          { label: "Vishing deepfake", sub: "Voix clonee, visio truquee", color: "pink" },
        ]},
        { type: "prompt-example", prompt: "Tu es un expert en cybersécurité. Analyse cet email et identifié tous les indices de phishing, même subtils : [coller l'email suspect]", result: "L'IA identifié les anomalies : expediteur usurpe, urgence artificielle, liens suspects, demandes inhabituelles, incoherences temporelles." },
        { type: "summary", items: [
          "Le phishing IA est sans fautes, personnalisé et contextuellement cohérent",
          "Le spear-phishing automatisé utilise OSINT pour cibler précisément les victimes",
          "Le vishing deepfake peut cloner une voix en 3 secondes d'echantillon",
          "Les emails de phishing IA ont un taux de clic 4-5x supérieur",
          "Règle d'or : vérifier par un autre canal avant toute action sensible",
        ]},
      ],
      quiz: [
        {
          question: "Pourquoi le phishing IA est-il plus dangereux que le phishing traditionnel ?",
          options: ["Il est plus rapide", "Il génère des emails parfaits, personnalisés et sans fautes", "Il coûte moins cher", "Il ne peut pas être détecte"],
          correctIndex: 1,
          explanation: "Le phishing IA génère des emails parfaitement rédigés, sans fautes, personnalisés avec des informations réelles de la ciblé, eliminant les indices traditionnels de détection.",
        },
        {
          question: "Qu'est-ce que le vishing ?",
          options: ["Le phishing par SMS", "Le phishing par email video", "Le phishing vocal avec voix synthetique", "Le phishing sur les réseaux sociaux"],
          correctIndex: 2,
          explanation: "Le vishing (voice phishing) utilise la synthese vocale IA pour cloner des voix et passer des appels telephoniques frauduleux, souvent en imitant des dirigeants.",
        },
        {
          question: "Combien de temps faut-il pour cloner une voix avec l'IA ?",
          options: ["1 heure", "10 minutes", "3 secondes", "24 heures"],
          correctIndex: 2,
          explanation: "Les outils modernes de clonage vocal IA peuvent reproduire une voix convaincante à partir de seulement 3 secondes d'echantillon audio.",
        },
        {
          question: "Quelle est la meilleure défense contre le phishing IA ?",
          options: ["Installer un meilleur antivirus", "Vérifier par un autre canal avant toute action sensible", "Ne jamais ouvrir ses emails", "Bloquer tous les expediteurs inconnus"],
          correctIndex: 1,
          explanation: "La vérification multi-canal est la meilleure défense : avant toute action sensible (virement, envoi de données), confirmez la demande par un canal différent (téléphone, en personne).",
        },
      ],
    },
    {
      number: 4,
      title: "Deepfakes et Usurpation d'Identité",
      description: "Comprendre, détecter et se protéger contre les deepfakes et l'usurpation d'identité IA.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Les Deepfakes : La Menace Invisible" },
        { type: "paragraph", content: "Les deepfakes sont des contenus médiatiques (video, audio, images) générés ou manipules par l'IA pour paraître authentiques. En 2026, la qualité des deepfakes est telle qu'ils sont pratiquement impossibles à distinguer de contenus réels à l'oeil nu." },
        { type: "paragraph", content: "Les deepfakes sont utilisés pour l'usurpation d'identité en visioconference, la fraude financiere, la désinformation politique, le chantage, et l'atteinte a la reputation. Le volume de deepfakes détectés en ligne a augmente de 900% entre 2024 et 2026." },
        { type: "subheading", content: "Deepfakes Vidéo en Temps Réel" },
        { type: "paragraph", content: "Les technologies de face-swapping en temps réel permettent à un attaquant de prendre l'apparence de n'importé qui lors d'un appel Zoom ou Teams. En 2025, une multinationale a perdu 25 millions de dollars après qu'un employé ait suivi les instructions d'un 'collègue' en visioconference — un deepfake en temps réel." },
        { type: "subheading", content: "Deepfakes Audio" },
        { type: "paragraph", content: "Le clonage vocal est devenu trivial. ElevenLabs, Resemble.ai et d'autres outils permettent de cloner une voix avec quelques secondes d'audio. Les attaquants utilisent ces voix clonees pour des arnaques telephoniques, du chantage, et de la manipulation d'autorisations vocales." },
        { type: "callout", content: "Les deepfakes ne menacent pas seulement les personnalités publiques. En 2026, des particuliers sont ciblés : fausses vidéos compromettantes pour du chantage, usurpation d'identité pour des prêts bancaires, faux temoignages." },
        { type: "video", videoId: "bPVaOlJ6ln0",
      videoDurationMinutes: 12, label: "Comment fonctionnent les deepfakes" },
        { type: "heading", content: "Détection des Deepfakes" },
        { type: "paragraph", content: "Plusieurs techniques existent pour détecter les deepfakes : analyse des micro-expressions faciales, détection d'artefacts de génération (bords flous, eclairage incoherent), analyse spectrale de l'audio, et vérification du watermarking C2PA. Des outils comme Microsoft Vidéo Authenticator et Intel FakeCatcher aident à la détection." },
        { type: "key-point", content: "Le standard C2PA (Coalition for Content Provenance and Authenticity) intégré des metadonnees cryptographiques dans les contenus pour certifier leur origine. C'est la défense la plus prometteuse contre les deepfakes a grande échelle." },
        { type: "diagram", label: "Types de Deepfakes et Defenses", flow: "vertical", nodes: [
          { label: "Deepfake Vidéo", sub: "Face-swapping, lip-syncing temps réel", color: "pink" },
          { label: "Deepfake Audio", sub: "Clonage vocal, synthese de parole", color: "purple" },
          { label: "Deepfake Image", sub: "Visages générés, manipulation de photos", color: "blue" },
          { label: "Détection IA", sub: "FakeCatcher, Vidéo Authenticator", color: "emerald" },
          { label: "C2PA Watermarking", sub: "Certification cryptographique d'origine", color: "amber" },
        ]},
        { type: "summary", items: [
          "Le volume de deepfakes a augmente de 900% entre 2024 et 2026",
          "Les deepfakes video en temps réel permettent l'usurpation en visioconference",
          "Le clonage vocal ne nécessite que quelques secondes d'echantillon",
          "La détection repose sur l'analyse d'artefacts et le watermarking C2PA",
          "Toujours vérifier l'identité par un canal independant",
        ]},
      ],
      quiz: [
        {
          question: "De combien le volume de deepfakes a-t-il augmente entre 2024 et 2026 ?",
          options: ["100%", "300%", "900%", "50%"],
          correctIndex: 2,
          explanation: "Le volume de deepfakes détectés en ligne a augmente de 900% entre 2024 et 2026, refletant la démocratisation des outils de génération.",
        },
        {
          question: "Qu'est-ce que le standard C2PA ?",
          options: ["Un antivirus pour deepfakes", "Un standard de watermarking cryptographique pour certifier l'origine du contenu", "Un format video sécurisé", "Un protocole de visioconference"],
          correctIndex: 1,
          explanation: "C2PA (Coalition for Content Provenance and Authenticity) intégré des metadonnees cryptographiques dans les contenus pour certifier leur origine et leur authenticite.",
        },
        {
          question: "Comment un deepfake en temps réel a-t-il coûte 25 millions a une entreprise ?",
          options: ["En piratant le système bancaire", "En usurpant l'identité d'un collègue en visioconference", "En envoyant un email frauduleux", "En compromettant le réseau"],
          correctIndex: 1,
          explanation: "Un attaquant a utilisé un deepfake en temps réel pour prendre l'apparence d'un collègue lors d'une visioconference, convainquant un employé d'effectuer un virement de 25 millions de dollars.",
        },
        {
          question: "Quel outil aide à détecter les deepfakes video ?",
          options: ["ChatGPT", "Microsoft Vidéo Authenticator", "Midjourney", "Google Translate"],
          correctIndex: 1,
          explanation: "Microsoft Vidéo Authenticator analyse les vidéos pour détecter les artefacts de génération et estimer la probabilité qu'un contenu soit un deepfake.",
        },
      ],
    },
    {
      number: 5,
      title: "Défense et Détection avec l'IA",
      description: "Comment l'IA renforce la détection des menaces et la défense des systèmes informatiques.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "L'IA au Service de la Cyberdefense" },
        { type: "paragraph", content: "Si l'IA est une arme pour les attaquants, elle est aussi le bouclier le plus puissant des défenseurs. Les systèmes de sécurité bases sur l'IA analysent des millions d'événements par seconde, detectent des anomalies invisibles à l'oeil humain, et automatisent les réponses aux incidents." },
        { type: "paragraph", content: "Les SIEM (Security Information and Event Management) de nouvelle génération integrent des modèles de machine learning pour correler les événements, identifier les menaces zéro-day, et réduire le temps de détection de mois a minutes." },
        { type: "subheading", content: "Détection d'Anomalies par ML" },
        { type: "paragraph", content: "L'apprentissage non supervisé est particulièrement efficace pour la détection d'anomalies. Le modèle apprend le comportement 'normal' du réseau et alerte des que quelque chose devie : trafic inhabituel, accès anormal, transferts de données suspects. Cette approche détecte les menaces inconnues (zéro-day) que les règles traditionnelles manquent." },
        { type: "subheading", content: "Analyse Comportementale (UEBA)" },
        { type: "paragraph", content: "L'User and Entity Behavior Analytics (UEBA) utilise l'IA pour profiler le comportement de chaque utilisateur et équipement. Si un employé accede soudainement a des fichiers sensibles à 3h du matin depuis un pays étranger, le système déclenche une alerte immédiatement." },
        { type: "callout", content: "CrowdStrike Falcon, SentinelOne, et Darktrace utilisent l'IA pour détecter et neutraliser les menaces en temps réel. Ces outils reduisent le temps moyen de détection (MTTD) de 197 jours a moins de 24 heures." },
        { type: "video", videoId: "pg19Z8LL06w",
      videoDurationMinutes: 68, label: "L'IA defensive en cybersécurité" },
        { type: "heading", content: "Réponse Automatisee aux Incidents" },
        { type: "paragraph", content: "Les plateformes SOAR (Security Orchestration, Automation and Response) utilisent l'IA pour automatiser la réponse aux incidents : isolation automatique des machines compromises, blocage des IP malveillantes, revocation des accès compromis, et génération de rapports d'incident." },
        { type: "key-point", content: "L'IA ne remplace pas les analystes de sécurité — elle les augmente. Le modèle idéal combiné détection automatisée IA + validation humaine pour les cas complexes. C'est le concept de 'human-in-the-loop'." },
        { type: "diagram", label: "Stack de Cyberdefense IA", flow: "vertical", nodes: [
          { label: "SIEM IA", sub: "Correlation d'événements en temps réel", color: "blue" },
          { label: "UEBA", sub: "Analyse comportementale utilisateurs", color: "purple" },
          { label: "EDR / XDR", sub: "Détection et réponse sur endpoints", color: "emerald" },
          { label: "SOAR", sub: "Automatisation de la réponse", color: "amber" },
        ]},
        { type: "diagram", label: "Réduction du Temps de Détection", flow: "horizontal", nodes: [
          { label: "Sans IA", sub: "MTTD : 197 jours en moyenne", color: "pink" },
          { label: "Avec IA", sub: "MTTD : moins de 24 heures", color: "emerald" },
          { label: "Impact", sub: "Réduction des degats de 80%", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA analyse des millions d'événements par seconde pour détecter les menaces",
          "La détection d'anomalies par ML identifié les menaces zéro-day inconnues",
          "L'UEBA profile le comportement de chaque utilisateur pour détecter les compromissions",
          "Les outils IA reduisent le MTTD de 197 jours a moins de 24 heures",
          "Le modèle idéal combiné IA automatisée et validation humaine (human-in-the-loop)",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que l'UEBA en cybersécurité ?",
          options: ["Un type de firewall", "L'analyse comportementale des utilisateurs et entites", "Un protocole réseau", "Un format de log"],
          correctIndex: 1,
          explanation: "UEBA (User and Entity Behavior Analytics) utilise l'IA pour profiler le comportement normal de chaque utilisateur et équipement, detectant les anomalies suspectes.",
        },
        {
          question: "De combien l'IA réduit-elle le temps moyen de détection (MTTD) ?",
          options: ["De 197 jours a 100 jours", "De 197 jours a moins de 24 heures", "De 30 jours a 7 jours", "De 365 jours a 30 jours"],
          correctIndex: 1,
          explanation: "Les outils de cybersécurité bases sur l'IA (CrowdStrike, SentinelOne, Darktrace) reduisent le MTTD de 197 jours en moyenne a moins de 24 heures.",
        },
        {
          question: "Que signifie SOAR en cybersécurité ?",
          options: ["Security Online Attack Response", "Security Orchestration, Automation and Response", "Secure Operations and Risk", "System Optimization and Recovery"],
          correctIndex: 1,
          explanation: "SOAR (Security Orchestration, Automation and Response) désigné les plateformes qui automatisent la réponse aux incidents : isolation, blocage, revocation, rapports.",
        },
        {
          question: "Pourquoi l'IA ne remplace-t-elle pas les analystes de sécurité ?",
          options: ["Elle est trop chère", "Les cas complexes nécessitent une validation humaine (human-in-the-loop)", "Elle est trop lente", "Elle ne détecte que les menaces connues"],
          correctIndex: 1,
          explanation: "L'IA augmente les analystes mais ne les remplace pas. Les cas complexes et les faux positifs nécessitent un jugement humain — c'est le concept de human-in-the-loop.",
        },
      ],
    },
    {
      number: 6,
      title: "Sécurité des Modèles d'IA",
      description: "Attaques adversariales, empoisonnement de données et protection des modèles d'IA.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Protéger les Modèles d'IA Eux-Mêmes" },
        { type: "paragraph", content: "Les modèles d'IA ne sont pas seulement des outils de sécurité — ils sont aussi des ciblés. Les attaquants cherchent à manipuler, corrompre ou voler les modèles IA. La sécurité des modèles est un domaine critique qui inclut la protection contre les attaques adversariales, l'empoisonnement de données, et le vol de propriété intellectuelle." },
        { type: "subheading", content: "Attaques Adversariales" },
        { type: "paragraph", content: "Une attaque adversariale consiste à modifier subtilement les entrées d'un modèle pour le tromper. Un panneau stop avec quelques autocollants stratégiques peut être classifie comme un panneau de limitation de vitesse par un système de conduite autonome. Un pixel modifié dans une image peut changer complètement la classification." },
        { type: "paragraph", content: "Ces attaques exploitent les faiblesses mathématiques des réseaux de neurones. Elles sont particulièrement dangereuses dans les systèmes critiques : véhicules autonomes, imagerie médicale, systèmes de surveillance, et modération de contenu." },
        { type: "subheading", content: "Empoisonnement de Données" },
        { type: "paragraph", content: "L'empoisonnement de données (data poisoning) consiste à contaminer les données d'entraînement d'un modèle pour y inserer des backdoors. Par exemple, un attaquant peut inserer des exemples malveillants dans un dataset open source pour que le modèle entraîné dessus se comporte de manière spécifique face à certains declencheurs." },
        { type: "callout", content: "En 2025, des chercheurs ont démontré qu'en modifiant seulement 0,01% des données d'entraînement d'un LLM, ils pouvaient y inserer un backdoor indetectable qui s'active face à un mot-déclencheur spécifique." },
        { type: "video", videoId: "JEBDfGqrAUA",
      videoDurationMinutes: 72, label: "Attaques adversariales expliquees" },
        { type: "heading", content: "Protections et Bonnes Pratiques" },
        { type: "paragraph", content: "Les défenses incluent : l'entraînement adversarial (exposer le modèle a des exemples adversariaux pendant l'entraînement), la détection d'entrées anormales, la vérification cryptographique des datasets, le red teaming (tests d'intrusion sur les modèles), et l'utilisation de gardrails pour limiter les comportements du modèle." },
        { type: "key-point", content: "Le red teaming des modèles IA est devenu une pratique standard. Anthropic, OpenAI et Google emploient des équipes dédiées pour tester la robustesse de leurs modèles avant chaque release." },
        { type: "diagram", label: "Menaces sur les Modèles d'IA", flow: "horizontal", nodes: [
          { label: "Attaques adversariales", sub: "Manipulation des entrées", color: "pink" },
          { label: "Empoisonnement", sub: "Contamination des données", color: "purple" },
          { label: "Vol de modèle", sub: "Extraction de propriété intellectuelle", color: "amber" },
        ]},
        { type: "tip", content: "Si vous deployez un modèle IA en production, integrez systematiquement des tests adversariaux dans votre pipeline CI/CD. La robustesse se testé avant le déploiement, pas après." },
        { type: "summary", items: [
          "Les modèles d'IA sont des ciblés : attaques adversariales, empoisonnement, vol",
          "Les attaques adversariales trompent les modèles avec des modifications subtiles",
          "L'empoisonnement de données insere des backdoors dans les modèles entraînés",
          "Les défenses incluent l'entraînement adversarial et le red teaming",
          "La sécurité des modèles doit être intégrée des la conception (security by design)",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce qu'une attaque adversariale ?",
          options: ["Un virus qui détruit un modèle IA", "Une modification subtile des entrées pour tromper le modèle", "Un DDoS contre un serveur IA", "Un vol de données d'entraînement"],
          correctIndex: 1,
          explanation: "Une attaque adversariale modifié subtilement les entrées d'un modèle (image, texte) pour le tromper et obtenir une classification ou une réponse incorrecte.",
        },
        {
          question: "Qu'est-ce que l'empoisonnement de données ?",
          options: ["La suppression des données d'entraînement", "La contamination des données d'entraînement pour inserer des backdoors", "La corruption du modèle après déploiement", "Le chiffrement des données par un ransomware"],
          correctIndex: 1,
          explanation: "L'empoisonnement de données consiste à contaminer les données d'entraînement avec des exemples malveillants, inserant des backdoors activables par des declencheurs spécifiques.",
        },
        {
          question: "Quelle proportion des données d'entraînement suffit pour inserer un backdoor ?",
          options: ["10%", "1%", "0,01%", "50%"],
          correctIndex: 2,
          explanation: "Des chercheurs ont démontré qu'en modifiant seulement 0,01% des données d'entraînement d'un LLM, ils pouvaient y inserer un backdoor indetectable.",
        },
        {
          question: "Qu'est-ce que le red teaming des modèles IA ?",
          options: ["La mise à jour des modèles", "Des tests d'intrusion sur les modèles pour évaluer leur robustesse", "La formation des équipes de sécurité", "Le déploiement en production"],
          correctIndex: 1,
          explanation: "Le red teaming consiste à tester systematiquement la robustesse des modèles IA en simulant des attaques pour identifier les vulnérabilités avant le déploiement.",
        },
      ],
    },
    {
      number: 7,
      title: "Protection des Données et IA",
      description: "RGPD, vie privee, anonymisation — protéger les données à l'ère de l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Données et IA : Un Équilibre Delicat" },
        { type: "paragraph", content: "L'IA est vorace en données. Les modèles de langage sont entraînés sur des milliards de textes, les systèmes de reconnaissance faciale sur des millions de visages. Cette dépendance aux données souleve des questions cruciales de vie privee, de consentement, et de conformite réglementaire." },
        { type: "paragraph", content: "Le RGPD européen et l'AI Act imposent des obligations strictes sur la collecte, le traitement et la conservation des données utilisées par l'IA. Les violations peuvent coûter jusqu'à 4% du chiffre d'affaires mondial ou 20 millions d'euros." },
        { type: "subheading", content: "Risques de Fuite de Données par l'IA" },
        { type: "paragraph", content: "Les LLM peuvent mémoriser et regurgiter des données sensibles de leur entraînement. Un employé qui colle du code source propriétaire ou des données clients dans ChatGPT risque de voir ces informations accessibles a d'autres utilisateurs. Samsung a interdit ChatGPT après qu'un ingénieur ait colle du code source confidentiel." },
        { type: "callout", content: "En 2025, des chercheurs ont réussi a extraire des numeros de téléphone, adresses email et extraits de code source des données d'entraînement de GPT-3.5 par des techniques de prompt spécifiques. La memorisation non intentionnelle est un risque réel." },
        { type: "video", videoId: "bPVaOlJ6ln0",
      videoDurationMinutes: 12, label: "Protection des données et IA" },
        { type: "heading", content: "Techniques de Protection" },
        { type: "paragraph", content: "Plusieurs techniques protegent les données dans le contexte IA : l'anonymisation et la pseudonymisation des datasets, le differential privacy (ajout de bruit statistique pour protéger les individus), l'apprentissage fédéré (le modèle va aux données plutôt que l'inverse), et le chiffrement homomorphe (calculs sur des données chiffrées)." },
        { type: "key-point", content: "L'apprentissage fédéré est une révolution pour la vie privee : le modèle est entraîné localement sur chaque appareil et seuls les gradients agreges sont partages. Les données brutes ne quittent jamais l'appareil de l'utilisateur." },
        { type: "diagram", label: "Techniques de Protection des Données IA", flow: "horizontal", nodes: [
          { label: "Anonymisation", sub: "Supprimer les identifiants personnels", color: "blue" },
          { label: "Differential Privacy", sub: "Bruit statistique protecteur", color: "purple" },
          { label: "Apprentissage fédéré", sub: "Données locales, modèle distribue", color: "emerald" },
          { label: "Chiffrement homomorphe", sub: "Calcul sur données chiffrées", color: "amber" },
        ]},
        { type: "tip", content: "Avant d'utiliser un outil IA en entreprise, verifiez sa politique de données. Privilegiez les outils qui ne retiennent pas vos données pour l'entraînement (Claude API, ChatGPT Enterprise, etc.)." },
        { type: "summary", items: [
          "Les LLM peuvent mémoriser et regurgiter des données sensibles de leur entraînement",
          "Le RGPD impose des amendes jusqu'à 4% du CA mondial pour non-conformite",
          "L'anonymisation, le differential privacy et l'apprentissage fédéré protegent les données",
          "Ne jamais coller de données sensibles dans un LLM grand public",
          "Vérifier la politique de données de chaque outil IA avant usage professionnel",
        ]},
      ],
      quiz: [
        {
          question: "Pourquoi Samsung a-t-elle interdit ChatGPT ?",
          options: ["A cause du coût", "Un ingénieur a colle du code source confidentiel", "ChatGPT était trop lent", "Pour des raisons de concurrence"],
          correctIndex: 1,
          explanation: "Samsung a interdit ChatGPT après qu'un ingénieur ait colle du code source propriétaire dans le chatbot, risquant de voir ces informations utilisées dans l'entraînement du modèle.",
        },
        {
          question: "Qu'est-ce que l'apprentissage fédéré ?",
          options: ["Un modèle entraîné dans plusieurs pays", "Un entraînement ou les données restent locales et seuls les gradients sont partages", "Un réseau de modèles interconnectes", "Un type de cloud computing"],
          correctIndex: 1,
          explanation: "L'apprentissage fédéré entraîné le modèle localement sur chaque appareil et ne partage que les gradients agreges. Les données brutes ne quittent jamais l'appareil de l'utilisateur.",
        },
        {
          question: "Quelle amende maximale le RGPD prevoit-il pour les violations de données ?",
          options: ["1% du CA mondial", "4% du CA mondial ou 20M EUR", "10 millions d'euros", "100 000 euros"],
          correctIndex: 1,
          explanation: "Le RGPD prevoit des amendes pouvant atteindre 4% du chiffre d'affaires mondial annuel ou 20 millions d'euros, selon le montant le plus élève.",
        },
        {
          question: "Qu'est-ce que le differential privacy ?",
          options: ["Un type de chiffrement", "L'ajout de bruit statistique pour protéger les données individuelles", "Une politique de confidentialité", "Un protocole de réseau sécurisé"],
          correctIndex: 1,
          explanation: "Le differential privacy ajouté un bruit statistique calibre aux données ou aux résultats, rendant impossible l'identification d'un individu spécifique tout en preservant l'utilité des données agrégées.",
        },
      ],
    },
    {
      number: 8,
      title: "Audit de Sécurité Assiste par l'IA",
      description: "Utiliser l'IA pour auditer la sécurité des systèmes, du code et des processus.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "L'IA Transforme l'Audit de Sécurité" },
        { type: "paragraph", content: "Les audits de sécurité traditionnels sont longs, couteux et ponctuels. L'IA transformé cette pratique en permettant des audits continus, automatises et exhaustifs. Les outils d'audit IA analysent le code source, les configurations réseau, les politiques d'accès, et les logs en permanence." },
        { type: "paragraph", content: "En 2026, les outils d'audit IA detectent jusqu'à 95% des vulnérabilités connues automatiquement, contre 60% pour les scanners traditionnels. Ils identifient également des patterns de vulnérabilités zéro-day que les outils classiques manquent." },
        { type: "subheading", content: "Audit de Code Source par IA" },
        { type: "paragraph", content: "Les LLM excellent dans la revue de code sécurité. Claude Code, GitHub Copilot et Snyk AI analysent le code pour identifier les injections SQL, XSS, CSRF, gestion insecure des secrets, et autres vulnérabilités OWASP Top 10. Ils suggerent des corrections en contexte." },
        { type: "callout", content: "GitHub Copilot a détecte et bloque plus de 40% de code potentiellement vulnérable avant qu'il soit commite en 2025. L'IA comme garde-fou pendant le développement, pas seulement après." },
        { type: "video", videoId: "pg19Z8LL06w",
      videoDurationMinutes: 68, label: "Audit de sécurité IA en pratique" },
        { type: "subheading", content: "Audit de Configuration et Infrastructure" },
        { type: "paragraph", content: "L'IA audite les configurations cloud (AWS, GCP, Azure) pour détecter les buckets S3 publics, les groupes de sécurité trop permissifs, les secrets en clair, et les certificats expirs. Des outils comme Prisma Cloud et Wiz utilisent le ML pour prioriser les risques et réduire le bruit." },
        { type: "heading", content: "Tests de Penetration Automatises" },
        { type: "paragraph", content: "Les pentests assistés par IA combinent la créativité des LLM avec la rigueur des scanners. PentestGPT et BurpGPT utilisent des LLM pour générer des payloads de test personnalisés, enchainer les étapes d'exploitation, et générer des rapports détaillés." },
        { type: "key-point", content: "L'audit IA continu est plus efficace que l'audit ponctuel. Integrez les outils d'audit IA dans votre pipeline CI/CD pour scanner chaque commit et chaque déploiement automatiquement." },
        { type: "prompt-example", prompt: "Analyse ce fichier de configuration nginx et identifié toutes les vulnérabilités de sécurité, les headers manquants, et les bonnes pratiques non respectees. [coller la config]", result: "L'IA identifié : headers de sécurité manquants (CSP, HSTS, X-Frame-Options), TLS 1.0/1.1 encore actif, server_tokens on, absence de rate limiting." },
        { type: "diagram", label: "Pipeline d'Audit Sécurité IA", flow: "horizontal", nodes: [
          { label: "Code Source", sub: "Snyk AI, Copilot, Claude Code", color: "blue" },
          { label: "Infrastructure", sub: "Prisma Cloud, Wiz, ScoutSuite", color: "purple" },
          { label: "Pentest IA", sub: "PentestGPT, BurpGPT", color: "pink" },
          { label: "Rapport & Priorisation", sub: "Scoring de risques ML", color: "emerald" },
        ]},
        { type: "summary", items: [
          "L'IA détecte 95% des vulnérabilités connues vs 60% pour les scanners classiques",
          "Les LLM analysent le code pour les vulnérabilités OWASP Top 10",
          "L'audit IA des configurations cloud détecte buckets publics et secrets en clair",
          "Les pentests IA combinent créativité LLM et rigueur des scanners",
          "Integrer l'audit IA en continu dans le pipeline CI/CD est la meilleure pratique",
        ]},
      ],
      quiz: [
        {
          question: "Quel pourcentage de vulnérabilités les outils d'audit IA detectent-ils ?",
          options: ["40%", "60%", "80%", "95%"],
          correctIndex: 3,
          explanation: "Les outils d'audit IA detectent jusqu'à 95% des vulnérabilités connues automatiquement, contre 60% pour les scanners traditionnels.",
        },
        {
          question: "Qu'est-ce que l'OWASP Top 10 ?",
          options: ["Les 10 meilleurs antivirus", "Les 10 vulnérabilités web les plus critiques", "Les 10 meilleurs langages de programmation", "Les 10 plus grandes entreprises de cybersécurité"],
          correctIndex: 1,
          explanation: "L'OWASP Top 10 est la liste des 10 catégories de vulnérabilités web les plus critiques, incluant les injections SQL, XSS, CSRF, et la gestion insecure des authentifications.",
        },
        {
          question: "Pourquoi l'audit IA continu est-il preferable à l'audit ponctuel ?",
          options: ["Il est moins cher", "Il scanne chaque commit et déploiement en temps réel", "Il ne nécessite pas de compétences", "Il remplace les pentests manuels"],
          correctIndex: 1,
          explanation: "L'audit IA continu intégré dans le CI/CD scanne chaque commit et déploiement, detectant les vulnérabilités immédiatement plutôt qu'une fois par trimestre.",
        },
        {
          question: "Quel outil IA a bloque 40% de code vulnérable avant le commit ?",
          options: ["ChatGPT", "GitHub Copilot", "Midjourney", "Sora"],
          correctIndex: 1,
          explanation: "GitHub Copilot a détecte et bloque plus de 40% de code potentiellement vulnérable avant qu'il ne soit commite, agissant comme garde-fou pendant le développement.",
        },
      ],
    },
    {
      number: 9,
      title: "Réponse aux Incidents avec l'IA",
      description: "Automatiser et accélérer la réponse aux incidents de sécurité grâce à l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Accelerer la Réponse aux Incidents" },
        { type: "paragraph", content: "Quand une cyberattaque survient, chaque minute compte. Le temps moyen de réponse a un incident (MTTR) est de 73 jours sans IA. Avec l'IA, ce temps chute a quelques heures. L'automatisation de la réponse est devenue indispensable face au volume et a la vitesse des attaques modernes." },
        { type: "paragraph", content: "Les plateformes SOAR (Security Orchestration, Automation and Response) modernes utilisent l'IA pour orchestrer la réponse : triage automatique des alertes, enrichissement contextuel, containment automatisé, investigation forensique, et génération de rapports réglementaires." },
        { type: "subheading", content: "Triage Intelligent des Alertes" },
        { type: "paragraph", content: "Les équipes SOC (Security Operations Center) reçoivent des milliers d'alertes par jour. L'IA trie ces alertes par priorité, corrige les alertes, élimine les faux positifs (jusqu'à 80%), et regroupe les alertes correlees en incidents uniques. Les analystes se concentrent sur les vrais problèmes." },
        { type: "subheading", content: "Investigation Forensique Assistee" },
        { type: "paragraph", content: "L'IA accélère l'investigation forensique en analysant automatiquement les logs, les captures réseau, la mémoire et les disques. Elle reconstruit la chronologie de l'attaque (kill chain), identifié les indicateurs de compromission (IoC), et détermine l'étendue de la breche." },
        { type: "callout", content: "Microsoft Security Copilot utilise GPT-4 pour permettre aux analystes de poser des questions en langage naturel : 'Quels fichiers ont été accedes par cet utilisateur compromis dans les dernières 48h ?' — et obtenir une réponse en secondes." },
        { type: "video", videoId: "JEBDfGqrAUA",
      videoDurationMinutes: 72, label: "Réponse aux incidents avec l'IA" },
        { type: "heading", content: "Playbooks de Réponse Automatises" },
        { type: "paragraph", content: "Les playbooks automatises definissent les actions à prendre pour chaque type d'incident. L'IA les exécute instantanément : isoler la machine compromise, revoquer les sessions actives, scanner les systèmes adjacents, notifier les équipes, et documenter chaque action pour la conformite." },
        { type: "key-point", content: "L'IA réduit le 'alert fatigue' des équipes SOC. En eliminant 80% des faux positifs et en automatisant le triage, les analystes peuvent se concentrer sur les incidents critiques au lieu de noyer dans le bruit." },
        { type: "diagram", label: "Pipeline de Réponse aux Incidents IA", flow: "vertical", nodes: [
          { label: "Détection", sub: "SIEM IA détecte l'anomalie", color: "pink" },
          { label: "Triage", sub: "IA priorise et élimine les faux positifs", color: "blue" },
          { label: "Investigation", sub: "Forensique automatisée, kill chain", color: "purple" },
          { label: "Containment", sub: "Isolation et blocage automatises", color: "amber" },
          { label: "Remediation", sub: "Correction, rapport, retour d'expérience", color: "emerald" },
        ]},
        { type: "summary", items: [
          "L'IA réduit le MTTR de 73 jours a quelques heures",
          "Le triage IA élimine 80% des faux positifs",
          "L'investigation forensique IA reconstruit la kill chain automatiquement",
          "Les playbooks automatises executent la réponse en secondes",
          "Microsoft Security Copilot permet l'investigation en langage naturel",
        ]},
      ],
      quiz: [
        {
          question: "Quel est le temps moyen de réponse a un incident sans IA ?",
          options: ["7 jours", "30 jours", "73 jours", "365 jours"],
          correctIndex: 2,
          explanation: "Le temps moyen de réponse a un incident (MTTR) est de 73 jours sans IA. Avec l'IA, ce temps chute a quelques heures.",
        },
        {
          question: "Quel pourcentage de faux positifs l'IA peut-elle éliminer ?",
          options: ["30%", "50%", "80%", "100%"],
          correctIndex: 2,
          explanation: "L'IA élimine jusqu'à 80% des faux positifs dans les alertes de sécurité, reduisant considerablement la fatigue des analystes SOC.",
        },
        {
          question: "Qu'est-ce qu'une kill chain en cybersécurité ?",
          options: ["Un type de malware", "La chronologie des étapes d'une attaque", "Un outil de défense", "Un protocole de communication"],
          correctIndex: 1,
          explanation: "La kill chain est la chronologie des étapes d'une cyberattaque, de la reconnaissance initiale à l'exfiltration de données. L'IA peut la reconstruire automatiquement.",
        },
        {
          question: "Qu'est-ce que l'alert fatigue ?",
          options: ["Un bug dans les systèmes d'alerte", "L'épuisement des analystes face au volume d'alertes", "La desactivation des alertes", "Un type d'attaque DDoS"],
          correctIndex: 1,
          explanation: "L'alert fatigue est l'épuisement des analystes SOC face aux milliers d'alertes quotidiennes, dont la majorité sont des faux positifs. L'IA réduit ce problème en triant et priorisant automatiquement.",
        },
      ],
    },
    {
      number: 10,
      title: "Stratégie de Cybersécurité IA",
      description: "Construire une stratégie de cybersécurité intégrant l'IA pour votre organisation.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Construire une Stratégie de Cybersécurité IA" },
        { type: "paragraph", content: "Une stratégie de cybersécurité IA ne se résumé pas a acheter des outils. C'est une approche holistique qui intégré la technologie, les processus, les personnes et la gouvernance. En 2026, les organisations matures adoptent le paradigme 'AI-First Security' — l'IA est au coeur de chaque couche de défense." },
        { type: "paragraph", content: "Cette stratégie doit couvrir la prévention (réduire la surface d'attaque), la détection (identifier les menaces en temps réel), la réponse (reagir rapidement aux incidents), et la recovery (restaurer les opérations normales). L'IA intervient à chaque étape." },
        { type: "subheading", content: "Le Framework Zero Trust + IA" },
        { type: "paragraph", content: "Le Zero Trust ('ne jamais faire confiance, toujours vérifier') est le fondement de la cybersécurité moderne. L'IA enrichit ce framework en evaluant en continu le niveau de confiance de chaque utilisateur, appareil et connexion. L'authentification adaptative ajuste les exigences de sécurité selon le contexte." },
        { type: "subheading", content: "Formation et Sensibilisation" },
        { type: "paragraph", content: "La technologie seule ne suffit pas. 85% des violations impliquent un facteur humain. Les programmés de sensibilisation IA simulent des attaques de phishing personnalisées, forment les employés avec des scénarios réalistes, et mesurent l'amélioration continue." },
        { type: "callout", content: "Les organisations avec un programmé de sensibilisation IA ont 3x moins de chances d'être victimes de phishing. L'investissement dans la formation est le meilleur ROI en cybersécurité." },
        { type: "video", videoId: "bPVaOlJ6ln0",
      videoDurationMinutes: 12, label: "Stratégie de cybersécurité IA" },
        { type: "heading", content: "Feuille de Route Implementee" },
        { type: "paragraph", content: "Phase 1 (Mois 1-3) : Audit de maturite, déploiement EDR/XDR IA, formation des équipes. Phase 2 (Mois 4-6) : SIEM IA, UEBA, automatisation SOAR. Phase 3 (Mois 7-12) : Zero Trust complet, threat hunting proactif, red teaming continu." },
        { type: "key-point", content: "Le budget cybersécurité recommandé en 2026 est de 10-15% du budget IT total. Les organisations qui investissent proactivement depensent 3x moins en remediation post-incident que celles qui reagissent." },
        { type: "diagram", label: "Feuille de Route Cybersécurité IA", flow: "vertical", nodes: [
          { label: "Phase 1 : Fondations", sub: "Audit, EDR/XDR, formation (Mois 1-3)", color: "blue" },
          { label: "Phase 2 : Détection", sub: "SIEM IA, UEBA, SOAR (Mois 4-6)", color: "purple" },
          { label: "Phase 3 : Maturite", sub: "Zero Trust, threat hunting (Mois 7-12)", color: "emerald" },
        ]},
        { type: "diagram", label: "Les 4 Piliers de la Cybersécurité IA", flow: "horizontal", nodes: [
          { label: "Prévention", sub: "Réduire la surface d'attaque", color: "blue" },
          { label: "Détection", sub: "Identifier les menaces en temps réel", color: "purple" },
          { label: "Réponse", sub: "Reagir rapidement aux incidents", color: "amber" },
          { label: "Recovery", sub: "Restaurer les opérations", color: "emerald" },
        ]},
        { type: "tip", content: "Commencez par les quick wins : EDR IA sur tous les postes, MFA partout, et un programmé de sensibilisation au phishing. Ces trois mesures bloquent 80% des attaques courantes." },
        { type: "summary", items: [
          "La stratégie cybersécurité IA est holistique : technologie, processus, personnes, gouvernance",
          "Le Zero Trust + IA est le fondement de la sécurité moderne",
          "85% des violations impliquent un facteur humain — la formation est essentielle",
          "Budget recommandé : 10-15% du budget IT total",
          "Quick wins : EDR IA + MFA + sensibilisation bloquent 80% des attaques",
        ]},
      ],
      quiz: [
        {
          question: "Quel pourcentage des violations implique un facteur humain ?",
          options: ["25%", "50%", "70%", "85%"],
          correctIndex: 3,
          explanation: "85% des violations de sécurité impliquent un facteur humain (erreur, negligence, manipulation). C'est pourquoi la formation et la sensibilisation sont essentielles.",
        },
        {
          question: "Qu'est-ce que le Zero Trust ?",
          options: ["Ne jamais utiliser l'IA", "Ne jamais faire confiance, toujours vérifier", "Ne jamais se connecter a Internet", "Ne jamais partager ses mots de passe"],
          correctIndex: 1,
          explanation: "Le Zero Trust est un paradigme de sécurité qui stipule de ne jamais faire confiance par défaut et de toujours vérifier chaque utilisateur, appareil et connexion.",
        },
        {
          question: "Quel budget cybersécurité est recommandé en 2026 ?",
          options: ["1-3% du budget IT", "5-7% du budget IT", "10-15% du budget IT", "25% du budget IT"],
          correctIndex: 2,
          explanation: "Le budget cybersécurité recommandé en 2026 est de 10-15% du budget IT total. Les organisations qui investissent proactivement depensent 3x moins en remediation.",
        },
        {
          question: "Quels sont les 3 quick wins en cybersécurité ?",
          options: ["VPN, antivirus, pare-feu", "EDR IA, MFA, sensibilisation au phishing", "Cloud, blockchain, quantique", "Chiffrement, backup, monitoring"],
          correctIndex: 1,
          explanation: "EDR IA sur tous les postes, MFA (authentification multi-facteurs) partout, et un programmé de sensibilisation au phishing bloquent 80% des attaques courantes.",
        },
      ],
    },
  ],
};

export default content;
