import type { CourseContent } from "../types";

const content: CourseContent = {
  slug: "ia-freelances",
  chapters: [
    {
      number: 1,
      title: "Introduction : L'IA comme Avantage Freelance",
      description: "Comprendre pourquoi l'IA est un levier de croissance incontournable pour les freelances.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "L'IA : Votre Avantage Competitif en Freelance" },
        { type: "paragraph", content: "En 2026, les freelances qui maitrisent l'IA gagnent en moyenne 40% de plus que ceux qui ne l'utilisent pas. Pas parce qu'ils travaillent plus — parce qu'ils livrent plus vite, prospectent mieux, et offrent des services a plus haute valeur ajoutee." },
        { type: "paragraph", content: "L'IA ne menace pas les freelances — elle les libere. Elle automatise les taches repetitives (admin, facturation, prospection) pour que vous puissiez vous concentrer sur ce qui vous rend unique : votre expertise, votre creativite, et votre relation client." },
        { type: "callout", content: "73% des freelances utilisant l'IA quotidiennement rapportent avoir augmente leur chiffre d'affaires en moins de 6 mois (etude Malt x BCG, 2025)." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "L'IA pour les freelances : pourquoi maintenant" },
        { type: "heading", content: "Les 5 Piliers de l'IA Freelance" },
        { type: "paragraph", content: "Ce cours couvre les 5 piliers qui transforment une activite freelance avec l'IA : la prospection automatisee, les propositions commerciales generees, les livrables acceleres, l'administration automatisee, et le personal branding amplifie." },
        { type: "key-point", content: "L'IA ne remplace pas votre expertise — elle l'amplifie. Un freelance avec l'IA peut faire le travail de 3 sans sacrifier la qualite. C'est un multiplicateur de force." },
        { type: "tip", content: "Vous n'avez besoin d'aucune competence technique pour commencer. Les outils couverts dans ce cours sont accessibles a tous les profils : designer, redacteur, consultant, developpeur, coach." },
        { type: "diagram", label: "Les 5 Piliers de l'IA Freelance", flow: "horizontal", nodes: [
          { label: "Prospection", sub: "Trouver des clients automatiquement", color: "blue" },
          { label: "Proposals", sub: "Propositions commerciales IA", color: "purple" },
          { label: "Livrables", sub: "Production acceleree", color: "emerald" },
          { label: "Admin", sub: "Facturation et gestion", color: "amber" },
          { label: "Branding", sub: "Visibilite et reputation", color: "pink" },
        ]},
        { type: "summary", items: [
          "Les freelances avec l'IA gagnent 40% de plus en moyenne",
          "L'IA automatise l'admin pour se concentrer sur l'expertise",
          "5 piliers : prospection, proposals, livrables, admin, branding",
          "Aucune competence technique requise",
          "L'IA est un multiplicateur de force, pas un remplacement",
        ]},
      ],
      quiz: [
        {
          question: "Quel gain moyen les freelances utilisant l'IA observent-ils ?",
          options: ["10%", "25%", "40%", "80%"],
          correctIndex: 2,
          explanation: "Les freelances qui maitrisent l'IA gagnent en moyenne 40% de plus, grace a une livraison plus rapide et des services a plus haute valeur ajoutee.",
        },
        {
          question: "Comment l'IA impacte-t-elle l'activite freelance ?",
          options: ["Elle remplace les freelances", "Elle automatise les taches repetitives pour se concentrer sur l'expertise", "Elle reduit la qualite des livrables", "Elle augmente le temps de travail"],
          correctIndex: 1,
          explanation: "L'IA automatise les taches repetitives (admin, prospection, facturation) permettant aux freelances de se concentrer sur leur expertise et leur creativite.",
        },
        {
          question: "Faut-il des competences techniques pour utiliser l'IA en freelance ?",
          options: ["Oui, il faut savoir programmer", "Non, les outils sont accessibles a tous les profils", "Seulement pour les developpeurs", "Il faut au minimum connaitre Excel"],
          correctIndex: 1,
          explanation: "Les outils IA modernes sont accessibles a tous les profils de freelances : designers, redacteurs, consultants, coaches — aucune competence technique requise.",
        },
        {
          question: "Combien de piliers composent la strategie IA freelance de ce cours ?",
          options: ["3", "5", "7", "10"],
          correctIndex: 1,
          explanation: "Le cours couvre 5 piliers : prospection automatisee, propositions commerciales, livrables acceleres, administration automatisee, et personal branding.",
        },
      ],
    },
    {
      number: 2,
      title: "Prospection et Acquisition Clients avec l'IA",
      description: "Automatiser la recherche de clients et la prise de contact avec l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "La Prospection Augmentee par l'IA" },
        { type: "paragraph", content: "La prospection est la bete noire de nombreux freelances. L'IA transforme cette corvee en processus semi-automatise : identification de prospects qualifies, personnalisation des messages, suivi automatique, et analyse des meilleurs canaux d'acquisition." },
        { type: "paragraph", content: "En 2026, les outils d'IA peuvent scanner LinkedIn, les plateformes freelance, et les annonces d'emploi pour identifier les prospects qui correspondent exactement a votre profil. Ils generent ensuite des messages personnalises qui convertissent 3x mieux que les templates generiques." },
        { type: "subheading", content: "Identifier les Bons Prospects" },
        { type: "paragraph", content: "Utilisez Claude ou ChatGPT pour definir votre ICP (Ideal Customer Profile). Decrivez votre offre et l'IA vous aide a identifier les criteres cles : taille d'entreprise, secteur, budget, problematiques, signaux d'achat." },
        { type: "subheading", content: "Messages de Prospection Personnalises" },
        { type: "paragraph", content: "L'IA genere des messages de prospection personnalises pour chaque prospect. Elle analyse le profil LinkedIn, le site web de l'entreprise, et les actualites recentes pour creer un message qui resonne avec les problematiques specifiques du prospect." },
        { type: "prompt-example", prompt: "Je suis designer UX freelance. Voici le profil LinkedIn de mon prospect [lien]. Genere un message de prospection personnalise qui mentionne un probleme UX visible sur leur site et propose une solution concrete.", result: "L'IA genere un message de 4 lignes qui mentionne un probleme de conversion identifie sur le site, cite un chiffre de leur secteur, et propose un audit gratuit de 15 minutes." },
        { type: "heading", content: "Automatiser le Suivi" },
        { type: "paragraph", content: "Utilisez des outils comme Make ou Zapier + IA pour automatiser les suivis : relance a J+3 si pas de reponse, message de valeur a J+7, derniere relance a J+14. L'IA personnalise chaque relance en fonction du contexte." },
        { type: "callout", content: "Attention : la prospection automatisee doit rester humaine et authentique. L'objectif n'est pas d'envoyer 1000 messages generiques, mais 50 messages parfaitement personnalises par semaine." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Prospection freelance avec l'IA" },
        { type: "diagram", label: "Pipeline de Prospection IA", flow: "vertical", nodes: [
          { label: "Definir l'ICP", sub: "Profil client ideal avec l'IA", color: "blue" },
          { label: "Identifier les prospects", sub: "Scan LinkedIn, plateformes, annonces", color: "purple" },
          { label: "Messages personnalises", sub: "Personnalisation par prospect", color: "emerald" },
          { label: "Suivi automatise", sub: "Relances intelligentes J+3, J+7, J+14", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA transforme la prospection en processus semi-automatise",
          "Messages personnalises qui convertissent 3x mieux",
          "Definissez votre ICP (Ideal Customer Profile) avec l'IA",
          "Automatisez les relances avec Make/Zapier + IA",
          "Qualite > quantite : 50 messages personnalises > 1000 generiques",
        ]},
      ],
      quiz: [
        {
          question: "Combien de fois mieux convertissent les messages IA personnalises ?",
          options: ["1,5x", "2x", "3x", "5x"],
          correctIndex: 2,
          explanation: "Les messages de prospection personnalises par l'IA convertissent en moyenne 3 fois mieux que les templates generiques non personnalises.",
        },
        {
          question: "Qu'est-ce qu'un ICP en prospection ?",
          options: ["Internet Connection Protocol", "Ideal Customer Profile", "Internal Communication Plan", "Integrated Client Platform"],
          correctIndex: 1,
          explanation: "L'ICP (Ideal Customer Profile) definit le profil de votre client ideal : taille, secteur, budget, problematiques, signaux d'achat.",
        },
        {
          question: "Quelle est la bonne approche de prospection automatisee ?",
          options: ["Envoyer 1000 messages identiques", "50 messages parfaitement personnalises par semaine", "Ne jamais relancer", "Prospecter uniquement par telephone"],
          correctIndex: 1,
          explanation: "La qualite prime sur la quantite : 50 messages parfaitement personnalises par semaine sont bien plus efficaces que 1000 messages generiques.",
        },
        {
          question: "Quels outils automatisent le suivi de prospection ?",
          options: ["Photoshop", "Make ou Zapier + IA", "Excel uniquement", "Canva"],
          correctIndex: 1,
          explanation: "Make et Zapier couples a l'IA permettent d'automatiser les relances de prospection avec des messages personnalises selon le contexte.",
        },
      ],
    },
    {
      number: 3,
      title: "Propositions Commerciales Generees par l'IA",
      description: "Creer des propositions commerciales convaincantes en quelques minutes.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Des Proposals qui Convertissent" },
        { type: "paragraph", content: "La proposition commerciale est le document le plus important de votre activite freelance. C'est elle qui transforme un prospect en client. L'IA vous permet de generer des proposals personnalisees et professionnelles en 15 minutes au lieu de 3 heures." },
        { type: "paragraph", content: "Le secret n'est pas de laisser l'IA tout ecrire — c'est de l'utiliser pour structurer, personnaliser et peaufiner rapidement. Votre expertise et votre comprehension du besoin client restent le coeur de la proposition." },
        { type: "heading", content: "Structure d'une Proposal Gagnante" },
        { type: "paragraph", content: "Contexte et comprehension du besoin (montrez que vous avez compris), solution proposee (livrables concrets), methodologie et planning, investissement (prix), a propos de vous (credibilite), et prochaines etapes (call to action)." },
        { type: "subheading", content: "Personnalisation avec l'IA" },
        { type: "paragraph", content: "Fournissez a l'IA : le brief du client, son site web, son secteur, et votre offre type. L'IA genere une proposition personnalisee qui utilise le vocabulaire du client, reference des problematiques specifiques de son secteur, et propose des solutions adaptees." },
        { type: "prompt-example", prompt: "Genere une proposition commerciale pour [client] qui veut refondre son site e-commerce. Budget : 8000€. Delai : 6 semaines. Mon expertise : UX/UI + dev Next.js. Inclus des KPIs mesurables.", result: "L'IA genere une proposal de 3 pages avec : diagnostic du site actuel, wireframes proposes, planning Agile, KPIs (taux de conversion +25%, temps de chargement -50%), et 3 formules tarifaires." },
        { type: "tip", content: "Creez un template de base avec l'IA puis personnalisez pour chaque client. Gardez un dossier de proposals gagnantes que l'IA peut utiliser comme reference." },
        { type: "key-point", content: "Une bonne proposal ne vend pas un prix — elle vend une transformation. Montrez le ROI : 'Pour 8000€ d'investissement, votre taux de conversion augmentera de 25%, soit 40 000€ de CA additionnel par an.'" },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Propositions commerciales avec l'IA" },
        { type: "diagram", label: "Structure d'une Proposal Gagnante", flow: "vertical", nodes: [
          { label: "Comprehension du besoin", sub: "Montrez que vous avez compris le client", color: "blue" },
          { label: "Solution et livrables", sub: "Ce que vous allez livrer concretement", color: "purple" },
          { label: "Methodologie et planning", sub: "Comment et quand", color: "emerald" },
          { label: "Investissement et ROI", sub: "Prix justifie par la valeur", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA genere des proposals personnalisees en 15 min au lieu de 3h",
          "Structure : besoin, solution, methodologie, investissement, CTA",
          "Personnalisation avec le vocabulaire et le secteur du client",
          "Vendez la transformation et le ROI, pas un prix",
          "Gardez un dossier de proposals gagnantes comme reference",
        ]},
      ],
      quiz: [
        {
          question: "Combien de temps gagne-t-on sur une proposal avec l'IA ?",
          options: ["De 1h a 30min", "De 3h a 15min", "De 1 jour a 3h", "Aucun gain"],
          correctIndex: 1,
          explanation: "L'IA permet de generer une proposition commerciale personnalisee en environ 15 minutes, contre 3 heures en redaction manuelle.",
        },
        {
          question: "Qu'est-ce qui doit rester au coeur de la proposition ?",
          options: ["Le design du document", "Votre expertise et comprehension du besoin client", "Le nombre de pages", "Les references techniques"],
          correctIndex: 1,
          explanation: "L'IA aide a structurer et personnaliser, mais votre expertise et votre comprehension du besoin client restent le coeur d'une proposition convaincante.",
        },
        {
          question: "Que doit vendre une bonne proposal ?",
          options: ["Un prix bas", "Une transformation avec ROI mesurable", "Le maximum de services", "Des technologies innovantes"],
          correctIndex: 1,
          explanation: "Une bonne proposition ne vend pas un prix — elle vend une transformation. Montrer le ROI concret justifie l'investissement aux yeux du client.",
        },
        {
          question: "Comment ameliorer ses proposals au fil du temps ?",
          options: ["Utiliser le meme template pour tout le monde", "Garder un dossier de proposals gagnantes comme reference pour l'IA", "Reduire le contenu", "Augmenter les prix"],
          correctIndex: 1,
          explanation: "Conserver un dossier de proposals gagnantes permet a l'IA de s'en inspirer pour generer des propositions de plus en plus efficaces.",
        },
      ],
    },
    {
      number: 4,
      title: "Gestion de Projet Freelance avec l'IA",
      description: "Organiser ses projets, gerer les deadlines et communiquer efficacement.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Gestion de Projet Augmentee par l'IA" },
        { type: "paragraph", content: "Un freelance est aussi un chef de projet. L'IA vous aide a planifier, suivre et livrer vos projets de maniere plus efficace : estimation de temps, decoupage de taches, gestion des risques, et reporting client — le tout automatise." },
        { type: "paragraph", content: "Les outils comme Notion AI, Linear, et Claude excellent dans la gestion de projet. Ils transforment un brief vague en plan de projet structure avec milestones, dependances, et dates estimees." },
        { type: "subheading", content: "Planification avec l'IA" },
        { type: "paragraph", content: "Fournissez le brief client a l'IA et demandez un decoupage en phases, taches et sous-taches avec estimations de temps. L'IA anticipe les dependances et les risques potentiels. Ajustez selon votre experience." },
        { type: "subheading", content: "Estimation de Temps" },
        { type: "paragraph", content: "L'un des plus grands defis du freelance est l'estimation. Demandez a l'IA d'estimer chaque tache en fournissant le contexte : technologie, complexite, votre experience. L'IA propose des fourchettes realistes (optimiste, probable, pessimiste)." },
        { type: "prompt-example", prompt: "Decoupe ce projet de refonte e-commerce en taches avec estimations : design UX (wireframes + maquettes), dev frontend Next.js, integration Stripe, tests. Budget client : 6 semaines.", result: "L'IA genere un plan en 4 phases avec 15 taches, des estimations en heures, les dependances, les milestones hebdomadaires, et un buffer de 15% pour les imprevus." },
        { type: "heading", content: "Reporting et Communication Client" },
        { type: "paragraph", content: "L'IA genere des comptes-rendus hebdomadaires clairs pour vos clients : progression, prochaines etapes, risques identifies, decisions requises. Un email professionnel en 30 secondes au lieu de 20 minutes." },
        { type: "tip", content: "Ajoutez toujours un buffer de 15-20% a vos estimations IA. L'IA tend a etre optimiste car elle ne prend pas en compte les reunions, les allers-retours client, et les imprevus." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Gestion de projet freelance avec l'IA" },
        { type: "diagram", label: "Cycle de Gestion de Projet IA", flow: "cycle", nodes: [
          { label: "Planifier", sub: "Decoupage et estimation avec l'IA", color: "blue" },
          { label: "Executer", sub: "Livraison avec outils IA", color: "emerald" },
          { label: "Communiquer", sub: "Reports auto pour le client", color: "purple" },
        ]},
        { type: "summary", items: [
          "L'IA transforme un brief vague en plan de projet structure",
          "Estimations en fourchettes : optimiste, probable, pessimiste",
          "Reports client hebdomadaires generes en 30 secondes",
          "Buffer de 15-20% toujours necessaire sur les estimations IA",
          "Outils : Notion AI, Linear, Claude pour la gestion de projet",
        ]},
      ],
      quiz: [
        {
          question: "Pourquoi ajouter un buffer aux estimations IA ?",
          options: ["Pour facturer plus", "L'IA est optimiste et ne compte pas reunions, allers-retours et imprevus", "Par habitude", "Pour impressionner le client"],
          correctIndex: 1,
          explanation: "L'IA tend a sous-estimer le temps car elle ne prend pas en compte les reunions, les allers-retours client, les corrections et les imprevus. Un buffer de 15-20% est recommande.",
        },
        {
          question: "Comment l'IA aide-t-elle pour l'estimation de temps ?",
          options: ["Elle donne un chiffre exact", "Elle propose des fourchettes realistes (optimiste, probable, pessimiste)", "Elle elimine les imprevus", "Elle accelere le travail"],
          correctIndex: 1,
          explanation: "L'IA propose des fourchettes d'estimation (optimiste, probable, pessimiste) basees sur le contexte : technologie, complexite et experience.",
        },
        {
          question: "Combien de temps faut-il pour generer un report client avec l'IA ?",
          options: ["20 minutes", "5 minutes", "30 secondes", "1 heure"],
          correctIndex: 2,
          explanation: "L'IA genere un compte-rendu hebdomadaire professionnel en environ 30 secondes, contre 20 minutes de redaction manuelle.",
        },
        {
          question: "Que fait l'IA avec un brief client vague ?",
          options: ["Elle refuse de travailler", "Elle le transforme en plan structure avec milestones", "Elle demande plus d'informations", "Elle genere uniquement un devis"],
          correctIndex: 1,
          explanation: "L'IA peut transformer un brief vague en plan de projet structure avec phases, taches, estimations, dependances et milestones.",
        },
      ],
    },
    {
      number: 5,
      title: "Creer des Livrables Plus Vite",
      description: "Accelerer la production de livrables de haute qualite avec l'IA.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Production de Livrables Acceleree par l'IA" },
        { type: "paragraph", content: "C'est la ou l'IA a le plus d'impact direct sur vos revenus : produire des livrables de qualite plus rapidement. Un freelance qui livre en 3 jours ce qui en prenait 10 peut soit prendre plus de missions, soit augmenter ses tarifs." },
        { type: "paragraph", content: "L'IA accelere la production dans pratiquement tous les metiers freelance : redaction, design, developpement, consulting, marketing, traduction, data analyse, formation." },
        { type: "heading", content: "Par Metier Freelance" },
        { type: "subheading", content: "Redacteurs et Copywriters" },
        { type: "paragraph", content: "Claude et ChatGPT generent des premiers jets de haute qualite. Le freelance ajoute son expertise : ton de marque, connaissance du secteur, anecdotes, donnees proprietaires. Gain : 60-70% de temps sur la redaction brute." },
        { type: "subheading", content: "Designers et Creatifs" },
        { type: "paragraph", content: "Midjourney pour les moodboards et explorations visuelles. v0 pour les maquettes UI. Canva AI pour les presentations. Le freelance ajoute : direction artistique, coherence de marque, peaufinage pixel-perfect." },
        { type: "subheading", content: "Developpeurs" },
        { type: "paragraph", content: "Cursor et Claude Code pour la generation de code, les tests, le debugging. Bolt pour les prototypes rapides. Le freelance ajoute : architecture, securite, optimisation, decisions techniques." },
        { type: "subheading", content: "Consultants et Analystes" },
        { type: "paragraph", content: "L'IA analyse des documents, synthetise des donnees, genere des rapports structures. Perplexity pour la veille sectorielle. Claude pour l'analyse strategique. Le freelance ajoute : interpretation, recommandations contextuelles, experience." },
        { type: "key-point", content: "L'IA genere 80% du livrable en 20% du temps. Les 20% restants — peaufinage, expertise, touche personnelle — sont ce qui justifie votre tarif." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Livrables plus rapides avec l'IA" },
        { type: "diagram", label: "Gain de Temps par Metier", flow: "horizontal", nodes: [
          { label: "Redaction", sub: "Gain de 60-70%", color: "blue" },
          { label: "Design", sub: "Gain de 40-50%", color: "purple" },
          { label: "Developpement", sub: "Gain de 50-60%", color: "emerald" },
          { label: "Consulting", sub: "Gain de 30-40%", color: "amber" },
        ]},
        { type: "summary", items: [
          "L'IA genere 80% du livrable en 20% du temps",
          "Redaction : 60-70% de gain, Design : 40-50%, Dev : 50-60%",
          "Votre valeur ajoutee : expertise, ton, peaufinage, contexte",
          "Tous les metiers freelance beneficient de l'IA",
          "Livrer plus vite = plus de missions ou tarifs plus eleves",
        ]},
      ],
      quiz: [
        {
          question: "Quel pourcentage du livrable l'IA peut-elle generer ?",
          options: ["20%", "50%", "80%", "100%"],
          correctIndex: 2,
          explanation: "L'IA genere environ 80% du livrable en 20% du temps. Les 20% restants (peaufinage, expertise, touche personnelle) sont la valeur ajoutee du freelance.",
        },
        {
          question: "Quel gain de temps les redacteurs obtiennent-ils avec l'IA ?",
          options: ["10-20%", "30-40%", "60-70%", "90-100%"],
          correctIndex: 2,
          explanation: "Les redacteurs et copywriters gagnent 60 a 70% de temps sur la redaction brute, en utilisant l'IA pour les premiers jets qu'ils peaufinent ensuite.",
        },
        {
          question: "Qu'est-ce qui justifie le tarif du freelance malgre l'IA ?",
          options: ["La vitesse de generation", "L'expertise, le peaufinage et la touche personnelle", "Le nombre d'outils utilises", "La quantite de contenu"],
          correctIndex: 1,
          explanation: "L'expertise sectorielle, le peaufinage qualite, et la touche personnelle du freelance sont ce qui justifie le tarif — c'est ce que l'IA ne peut pas remplacer.",
        },
        {
          question: "Quel outil est recommande pour la veille sectorielle ?",
          options: ["Midjourney", "Perplexity", "Canva", "Cursor"],
          correctIndex: 1,
          explanation: "Perplexity AI est ideal pour la veille sectorielle grace a ses reponses sourcees et a jour, permettant aux consultants de rester informes rapidement.",
        },
      ],
    },
    {
      number: 6,
      title: "Facturation et Administration Automatisees",
      description: "Automatiser la facturation, les relances et l'administratif avec l'IA.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "L'Admin Freelance Automatisee" },
        { type: "paragraph", content: "L'administration est le cauchemar du freelance : devis, factures, relances de paiement, declarations, notes de frais, contrats. Ces taches ne generent pas de revenus mais consomment 15-20% de votre temps. L'IA peut reduire ce chiffre a 5%." },
        { type: "paragraph", content: "L'objectif n'est pas de tout automatiser mais de creer des systemes semi-automatiques : l'IA prepare, vous validez d'un clic. Facturation en 30 secondes au lieu de 15 minutes." },
        { type: "subheading", content: "Facturation Intelligente" },
        { type: "paragraph", content: "Connectez votre outil de facturation (Indy, Freebe, Henrri) a Make/Zapier. L'IA genere automatiquement les factures a partir des milestones du projet, envoie les rappels de paiement, et suit les encaissements." },
        { type: "subheading", content: "Contrats et Documents Legaux" },
        { type: "paragraph", content: "L'IA genere des contrats freelance personnalises, des CGV, des NDA, et des avenants. Attention : faites toujours valider les documents juridiques par un professionnel pour les gros contrats." },
        { type: "subheading", content: "Relances de Paiement" },
        { type: "paragraph", content: "Automatisez les relances de paiement : rappel amical a J+7, rappel ferme a J+15, mise en demeure a J+30. L'IA adapte le ton selon le delai et la relation client." },
        { type: "prompt-example", prompt: "Genere un email de relance de paiement pour une facture de 3500€ en retard de 12 jours. Client : agence marketing avec qui j'ai une bonne relation. Ton : professionnel mais amical.", result: "L'IA genere un email court et professionnel qui rappelle le montant, la date d'echeance, propose un lien de paiement direct, et suggere un echeancier si besoin — tout en preservant la relation." },
        { type: "tip", content: "Regroupez votre admin au vendredi apres-midi. Utilisez l'IA pour preparer tout en batch : factures, relances, rapports. 1h par semaine au lieu de 30min par jour." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Automatiser l'admin freelance" },
        { type: "diagram", label: "Pipeline d'Administration Automatisee", flow: "vertical", nodes: [
          { label: "Devis genere par l'IA", sub: "A partir du brief client", color: "blue" },
          { label: "Facture automatique", sub: "Declenchee par les milestones", color: "purple" },
          { label: "Relances intelligentes", sub: "J+7, J+15, J+30 adaptes au ton", color: "amber" },
          { label: "Comptabilite simplifiee", sub: "Classification automatique des depenses", color: "emerald" },
        ]},
        { type: "summary", items: [
          "L'admin consomme 15-20% du temps — l'IA reduit a 5%",
          "Facturation en 30 secondes au lieu de 15 minutes",
          "Relances de paiement automatisees avec ton adapte",
          "Contrats et documents legaux generes (a valider par un pro)",
          "Batch admin le vendredi : 1h par semaine suffit",
        ]},
      ],
      quiz: [
        {
          question: "Combien de temps l'admin consomme-t-elle sans IA ?",
          options: ["5%", "10%", "15-20%", "30%"],
          correctIndex: 2,
          explanation: "L'administration (devis, factures, relances, declarations) consomme 15 a 20% du temps d'un freelance. L'IA peut reduire ce chiffre a environ 5%.",
        },
        {
          question: "Combien de temps prend une facturation avec l'IA ?",
          options: ["15 minutes", "5 minutes", "30 secondes", "1 heure"],
          correctIndex: 2,
          explanation: "Avec un systeme semi-automatise, la facturation prend environ 30 secondes : l'IA prepare la facture, vous validez d'un clic.",
        },
        {
          question: "Faut-il faire valider les contrats generes par l'IA ?",
          options: ["Non, l'IA est suffisante", "Oui, par un professionnel du droit pour les gros contrats", "Seulement pour les clients internationaux", "Jamais"],
          correctIndex: 1,
          explanation: "Les documents juridiques generes par l'IA doivent etre valides par un professionnel du droit, surtout pour les gros contrats et les engagements importants.",
        },
        {
          question: "Quelle est la meilleure strategie pour l'admin freelance ?",
          options: ["Un peu chaque jour", "Tout le lundi matin", "Batch le vendredi apres-midi avec l'IA", "Deleguer a un comptable"],
          correctIndex: 2,
          explanation: "Regrouper l'admin au vendredi apres-midi et utiliser l'IA pour tout preparer en batch est la strategie la plus efficace : 1 heure par semaine suffit.",
        },
      ],
    },
    {
      number: 7,
      title: "Personal Branding et Visibilite",
      description: "Construire une marque personnelle forte avec l'aide de l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Personal Branding Amplifie par l'IA" },
        { type: "paragraph", content: "En 2026, votre personal brand est votre meilleur commercial. Les freelances avec une presence en ligne forte attirent des clients entrants — plus besoin de prospecter. L'IA vous aide a creer du contenu de qualite regulierement sans y passer des heures." },
        { type: "paragraph", content: "Le personal branding ne consiste pas a se vanter. Il s'agit de partager votre expertise, vos apprentissages et vos points de vue pour attirer des clients qui resonnent avec votre approche." },
        { type: "subheading", content: "Strategie de Contenu avec l'IA" },
        { type: "paragraph", content: "Definissez 3 a 5 piliers de contenu (vos sujets d'expertise). L'IA genere un calendrier editorial mensuel avec des idees de posts, articles et videos. Chaque semaine, elle genere les premiers jets que vous personnalisez avec votre voix." },
        { type: "subheading", content: "LinkedIn pour les Freelances" },
        { type: "paragraph", content: "LinkedIn est le canal #1 des freelances B2B. L'IA genere des posts engageants : storytelling de missions, partage d'expertise, commentaires d'actualite sectorielle. Le format accroche + valeur + appel a l'action fonctionne systematiquement." },
        { type: "heading", content: "Contenu Multi-Plateforme" },
        { type: "paragraph", content: "Un seul contenu peut etre adapte pour LinkedIn, Twitter/X, newsletter, blog, et Instagram. L'IA adapte le format, le ton et la longueur pour chaque plateforme automatiquement." },
        { type: "prompt-example", prompt: "J'ai termine une mission de refonte UX pour un e-commerce de mode. Le taux de conversion est passe de 1,2% a 3,1%. Genere un post LinkedIn storytelling qui partage cette victoire sans citer le client.", result: "L'IA genere un post en format storytelling : accroche chiffree, probleme initial, processus, resultat, lecon a retenir. Format optimise pour l'algorithme LinkedIn (pas de liens externes, emojis strategiques)." },
        { type: "tip", content: "Regle des 80/20 : 80% de contenu qui donne de la valeur (tips, retours d'experience, analyses) et 20% qui parle de vos services. Les gens suivent ceux qui les aident, pas ceux qui se vendent." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Personal branding freelance avec l'IA" },
        { type: "diagram", label: "Strategie de Contenu Freelance", flow: "horizontal", nodes: [
          { label: "Piliers de contenu", sub: "3-5 sujets d'expertise", color: "blue" },
          { label: "Calendrier editorial", sub: "Genere mensuellement par l'IA", color: "purple" },
          { label: "Creation", sub: "Premiers jets IA + votre voix", color: "emerald" },
          { label: "Distribution", sub: "Adapte par plateforme", color: "amber" },
        ]},
        { type: "summary", items: [
          "Le personal brand attire des clients entrants sans prospection",
          "3 a 5 piliers de contenu + calendrier editorial IA",
          "LinkedIn = canal #1 pour les freelances B2B",
          "Regle 80/20 : 80% valeur, 20% services",
          "Un contenu adapte a plusieurs plateformes automatiquement",
        ]},
      ],
      quiz: [
        {
          question: "Pourquoi le personal branding est-il important pour un freelance ?",
          options: ["Pour impressionner les amis", "Pour attirer des clients entrants sans prospection", "Pour obtenir des likes", "Pour remplacer un site web"],
          correctIndex: 1,
          explanation: "Un personal brand fort attire des clients qui vous contactent directement (inbound), reduisant ou eliminant le besoin de prospection active.",
        },
        {
          question: "Quelle est la regle des 80/20 en contenu ?",
          options: ["80% ventes, 20% valeur", "80% valeur, 20% services", "80% images, 20% texte", "80% LinkedIn, 20% autres"],
          correctIndex: 1,
          explanation: "La regle des 80/20 recommande 80% de contenu qui apporte de la valeur (tips, retours d'experience) et 20% qui parle de vos services.",
        },
        {
          question: "Quel canal est #1 pour les freelances B2B ?",
          options: ["Instagram", "TikTok", "LinkedIn", "YouTube"],
          correctIndex: 2,
          explanation: "LinkedIn est le canal numero 1 pour les freelances B2B grace a son audience professionnelle et son algorithme qui favorise les posts de valeur.",
        },
        {
          question: "Comment l'IA aide-t-elle pour le contenu multi-plateforme ?",
          options: ["Elle publie automatiquement", "Elle adapte format, ton et longueur par plateforme", "Elle cree les comptes", "Elle achete de la publicite"],
          correctIndex: 1,
          explanation: "L'IA adapte automatiquement un seul contenu aux formats specifiques de chaque plateforme : longueur, ton, hashtags, et structure optimisee.",
        },
      ],
    },
    {
      number: 8,
      title: "Fixer ses Tarifs a l'Ere de l'IA",
      description: "Definir sa strategie tarifaire quand l'IA accelere la production.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Pricing Freelance a l'Ere de l'IA" },
        { type: "paragraph", content: "L'IA pose une question fondamentale pour les freelances : si je livre en 2 jours ce qui prenait 10, dois-je facturer moins ? La reponse courte : NON. Vous devez facturer a la valeur, pas au temps passe." },
        { type: "paragraph", content: "Le passage du taux horaire au tarif forfaitaire (ou mieux, a la valeur) est le pivot strategique le plus important de votre carriere freelance en 2026. L'IA vous rend plus productif — captez cette valeur au lieu de la donner au client." },
        { type: "heading", content: "Les 3 Modeles Tarifaires" },
        { type: "subheading", content: "1. Taux Horaire (a eviter)" },
        { type: "paragraph", content: "Le taux horaire vous penalise quand vous etes plus productif. Plus vous etes rapide (grace a l'IA), moins vous gagnez. C'est le modele le moins adapte a l'ere de l'IA." },
        { type: "subheading", content: "2. Forfait par Projet (bon)" },
        { type: "paragraph", content: "Vous estimez la valeur du livrable et proposez un prix fixe. L'IA vous permet de livrer plus vite, mais le prix reste le meme. Votre marge augmente." },
        { type: "subheading", content: "3. Tarification a la Valeur (ideal)" },
        { type: "paragraph", content: "Vous fixez votre prix en fonction de l'impact business pour le client. Une refonte qui genere 100 000€ de CA additionnel vaut 15 000-20 000€, peu importe le temps passe. C'est le modele le plus rentable avec l'IA." },
        { type: "callout", content: "Un designer qui utilise l'IA pour livrer une landing page en 2 jours au lieu de 8 ne devrait PAS baisser son prix. La valeur pour le client (une landing page qui convertit) est la meme." },
        { type: "key-point", content: "L'IA augmente votre marge, pas vos prix. Si vous livrez plus vite a qualite egale, votre taux horaire implicite augmente. Ne donnez pas cet avantage au client." },
        { type: "tip", content: "Calculez votre 'taux horaire implicite' : prix du projet / heures reelles. Avec l'IA, ce taux devrait etre 2x a 5x votre ancien taux horaire." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Pricing freelance a l'ere de l'IA" },
        { type: "diagram", label: "Du Taux Horaire a la Valeur", flow: "horizontal", nodes: [
          { label: "Taux horaire", sub: "Penalise la productivite IA", color: "pink" },
          { label: "Forfait projet", sub: "Bon — marge augmentee", color: "blue" },
          { label: "Tarification valeur", sub: "Ideal — prix = impact business", color: "emerald" },
        ]},
        { type: "summary", items: [
          "Ne facturez PAS moins parce que l'IA vous rend plus rapide",
          "Passez du taux horaire au forfait ou a la tarification a la valeur",
          "L'IA augmente votre marge, pas vos prix",
          "Prix = impact business pour le client, pas temps passe",
          "Taux horaire implicite avec l'IA : 2x a 5x l'ancien taux",
        ]},
      ],
      quiz: [
        {
          question: "Faut-il baisser ses tarifs quand l'IA accelere la production ?",
          options: ["Oui, c'est plus honnete", "Non, il faut facturer a la valeur livree", "Oui, pour rester competitif", "Ca depend du client"],
          correctIndex: 1,
          explanation: "L'IA augmente votre productivite mais pas la valeur du livrable pour le client. Facturez a la valeur, pas au temps passe.",
        },
        {
          question: "Quel modele tarifaire est le moins adapte a l'ere de l'IA ?",
          options: ["Forfait par projet", "Tarification a la valeur", "Taux horaire", "Retainer mensuel"],
          correctIndex: 2,
          explanation: "Le taux horaire penalise les freelances productifs : plus vous etes rapide grace a l'IA, moins vous gagnez. C'est le modele a eviter.",
        },
        {
          question: "Comment calculer son 'taux horaire implicite' ?",
          options: ["Salaire annuel / 12", "Prix du projet / heures reelles passees", "Prix du projet / heures estimees", "Tarif marche x experience"],
          correctIndex: 1,
          explanation: "Le taux horaire implicite = prix du projet divise par les heures reelles passees. Avec l'IA, ce taux devrait etre 2x a 5x votre ancien taux horaire.",
        },
        {
          question: "Qu'est-ce que la tarification a la valeur ?",
          options: ["Facturer le minimum possible", "Fixer le prix en fonction de l'impact business pour le client", "Facturer a l'heure", "Copier les tarifs des concurrents"],
          correctIndex: 1,
          explanation: "La tarification a la valeur fixe le prix en fonction de l'impact business pour le client (CA genere, couts economises), pas du temps passe.",
        },
      ],
    },
    {
      number: 9,
      title: "Relation Client et Communication",
      description: "Ameliorer la communication client et la satisfaction grace a l'IA.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Communication Client Augmentee par l'IA" },
        { type: "paragraph", content: "La relation client est ce qui differencie un freelance qui galere d'un freelance qui prospere. L'IA vous aide a communiquer mieux, plus vite, et plus professionnellement : emails, comptes-rendus, gestion des desaccords, et onboarding client." },
        { type: "paragraph", content: "80% des problemes en freelance sont des problemes de communication, pas de competence. Un email bien formule, un compte-rendu clair, une reponse rapide — l'IA rend tout cela sans effort." },
        { type: "subheading", content: "Emails Professionnels" },
        { type: "paragraph", content: "L'IA genere des emails professionnels adaptes a chaque situation : demande de brief, clarification de scope, annonce de retard, livraison de milestone, demande de feedback. Chaque email est calibre en ton et en longueur." },
        { type: "subheading", content: "Gestion des Situations Difficiles" },
        { type: "paragraph", content: "Client insatisfait, demande de scope creep, retard de paiement, desaccord sur les livrables — l'IA vous aide a formuler des reponses diplomatiques mais fermes. Elle propose des solutions constructives qui preservent la relation." },
        { type: "prompt-example", prompt: "Le client me demande d'ajouter 3 fonctionnalites hors scope sans budget supplementaire. J'ai une bonne relation avec lui. Genere un email qui refuse poliment en proposant un avenant.", result: "L'IA genere un email qui : 1) remercie pour la confiance, 2) rappelle le scope initial, 3) valorise les fonctionnalites demandees, 4) propose un avenant chiffre, 5) offre une alternative simplifiee dans le budget actuel." },
        { type: "heading", content: "Onboarding Client" },
        { type: "paragraph", content: "L'IA genere un kit d'onboarding client personnalise : questionnaire de decouverte, document de cadrage, planning, outils de communication, et processus de feedback. Premiere impression professionnelle garantie." },
        { type: "key-point", content: "La communication n'est pas juste un 'soft skill' — c'est ce qui determine si un client revient, vous recommande, et accepte vos augmentations de tarif." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Communication client avec l'IA" },
        { type: "diagram", label: "Cycle de Communication Client", flow: "cycle", nodes: [
          { label: "Onboarding", sub: "Kit de bienvenue professionnel", color: "blue" },
          { label: "Suivi", sub: "Reports hebdomadaires automatises", color: "purple" },
          { label: "Livraison", sub: "Presentation soignee des livrables", color: "emerald" },
        ]},
        { type: "summary", items: [
          "80% des problemes freelance sont des problemes de communication",
          "L'IA genere des emails professionnels pour chaque situation",
          "Gestion diplomatique des situations difficiles (scope creep, retards)",
          "Kit d'onboarding client pour une premiere impression pro",
          "Bonne communication = clients fideles + recommandations + tarifs plus eleves",
        ]},
      ],
      quiz: [
        {
          question: "Quel pourcentage des problemes freelance sont lies a la communication ?",
          options: ["20%", "50%", "80%", "100%"],
          correctIndex: 2,
          explanation: "80% des problemes en freelance sont des problemes de communication, pas de competence technique. Bien communiquer est essentiel.",
        },
        {
          question: "Comment l'IA aide-t-elle face au scope creep ?",
          options: ["Elle accepte automatiquement", "Elle genere un email de refus diplomatique avec proposition d'avenant", "Elle ignore la demande", "Elle negocie le prix"],
          correctIndex: 1,
          explanation: "L'IA genere des reponses diplomatiques mais fermes qui refusent poliment le scope creep tout en proposant un avenant chiffre ou une alternative.",
        },
        {
          question: "Qu'est-ce qu'un kit d'onboarding client ?",
          options: ["Un logiciel de gestion", "Un ensemble de documents pour demarrer la collaboration professionnellement", "Un formulaire de paiement", "Un portfolio"],
          correctIndex: 1,
          explanation: "Un kit d'onboarding comprend : questionnaire de decouverte, document de cadrage, planning, outils de communication, et processus de feedback.",
        },
        {
          question: "Pourquoi la communication impacte-t-elle les tarifs ?",
          options: ["Les clients paient plus pour les emails", "Une bonne communication fidelise et genere des recommandations", "C'est une obligation legale", "Ca n'a aucun impact"],
          correctIndex: 1,
          explanation: "Une communication excellente fidelise les clients, genere des recommandations, et cree la confiance necessaire pour que les clients acceptent vos augmentations de tarif.",
        },
      ],
    },
    {
      number: 10,
      title: "Construire un Business Freelance Scalable",
      description: "Passer de freelance solo a une activite scalable grace a l'IA.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Du Freelance Solo au Business Scalable" },
        { type: "paragraph", content: "Le plafond de verre du freelance, c'est le temps : vous ne pouvez pas travailler plus de 40-50 heures par semaine. L'IA brise ce plafond en vous permettant de scaler votre activite sans proportionnellement augmenter vos heures." },
        { type: "paragraph", content: "Scaler ne signifie pas necessairement embaucher. Avec l'IA, un freelance solo peut avoir l'output d'une equipe de 3 a 5 personnes. Et quand vous etes pret, l'IA facilite la delegation et la formation." },
        { type: "heading", content: "Strategies de Scaling" },
        { type: "subheading", content: "1. Productisation de votre Expertise" },
        { type: "paragraph", content: "Transformez vos services sur-mesure en offres packagées : audit UX a 2500€, kit de branding a 5000€, landing page a 3000€. L'IA vous aide a standardiser la production tout en gardant la personnalisation." },
        { type: "subheading", content: "2. Revenus Passifs avec l'IA" },
        { type: "paragraph", content: "Creez des templates, des formations, des guides, des outils. L'IA accelere la creation de produits digitaux : cours en ligne (comme celui-ci !), ebooks, templates Notion/Figma, outils no-code." },
        { type: "subheading", content: "3. Delegation Augmentee" },
        { type: "paragraph", content: "Quand vous etes pret a deleguer, l'IA facilite la transition : documentation des processus, creation de SOPs (Standard Operating Procedures), formation des sous-traitants, et controle qualite automatise." },
        { type: "subheading", content: "4. Positionnement Premium" },
        { type: "paragraph", content: "L'IA vous libere du temps pour le positionnement strategique : conferences, articles de fond, podcast, consulting high-level. Montez en gamme pendant que l'IA gere la production." },
        { type: "callout", content: "Le freelance le plus rentable de 2026 n'est pas celui qui travaille le plus — c'est celui qui utilise le mieux l'IA pour multiplier son impact tout en limitant son temps de travail." },
        { type: "key-point", content: "L'objectif final : travailler 4 jours par semaine en gagnant plus qu'en 5. L'IA rend cet objectif realiste pour les freelances qui optimisent leur workflow." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Scaler son activite freelance avec l'IA" },
        { type: "diagram", label: "Les 4 Leviers de Scaling", flow: "vertical", nodes: [
          { label: "Productisation", sub: "Offres packagées et standardisees", color: "blue" },
          { label: "Revenus passifs", sub: "Templates, formations, produits digitaux", color: "purple" },
          { label: "Delegation augmentee", sub: "SOPs + IA + sous-traitants", color: "emerald" },
          { label: "Positionnement premium", sub: "Consulting high-level, thought leadership", color: "amber" },
        ]},
        { type: "diagram", label: "Evolution du Freelance avec l'IA", flow: "horizontal", nodes: [
          { label: "Freelance solo", sub: "Services sur-mesure, taux horaire", color: "blue" },
          { label: "Freelance augmente", sub: "IA + forfaits, marge elevee", color: "purple" },
          { label: "Business scalable", sub: "Produits + delegation + premium", color: "emerald" },
        ]},
        { type: "summary", items: [
          "L'IA brise le plafond de verre du temps en freelance",
          "Un freelance avec l'IA = output de 3 a 5 personnes",
          "4 leviers : productisation, revenus passifs, delegation, premium",
          "Objectif : 4 jours/semaine en gagnant plus qu'en 5",
          "Le freelance le plus rentable utilise le mieux l'IA, pas travaille le plus",
        ]},
      ],
      quiz: [
        {
          question: "Quel est le plafond de verre du freelance ?",
          options: ["Le manque de clients", "Le temps disponible (40-50h/semaine)", "La competition", "Les tarifs du marche"],
          correctIndex: 1,
          explanation: "Le plafond de verre du freelance est le temps : on ne peut pas travailler plus de 40-50 heures par semaine. L'IA brise ce plafond en multipliant l'output.",
        },
        {
          question: "Qu'est-ce que la productisation en freelance ?",
          options: ["Vendre des produits physiques", "Transformer ses services sur-mesure en offres packagées standardisees", "Augmenter ses tarifs", "Sous-traiter tout"],
          correctIndex: 1,
          explanation: "La productisation consiste a transformer vos services sur-mesure en offres packagées (audit a prix fixe, kit de branding, etc.) pour standardiser et scaler.",
        },
        {
          question: "Quel est l'objectif de travail ideal avec l'IA selon le cours ?",
          options: ["7 jours/semaine", "5 jours/semaine", "4 jours/semaine en gagnant plus qu'en 5", "Ne plus travailler"],
          correctIndex: 2,
          explanation: "L'objectif est de travailler 4 jours par semaine en gagnant plus qu'en 5, grace a l'optimisation du workflow et a la multiplication de l'impact par l'IA.",
        },
        {
          question: "Qu'est-ce qu'un SOP en delegation ?",
          options: ["Un outil de facturation", "Une Standard Operating Procedure pour documenter les processus", "Un type de contrat", "Un logiciel de gestion"],
          correctIndex: 1,
          explanation: "Un SOP (Standard Operating Procedure) documente les processus etape par etape, facilitant la delegation a des sous-traitants ou assistants.",
        },
      ],
    },
  ],
};

export default content;
