import type { CourseContent } from "../types";

const content: CourseContent = {
  slug: "ia-generative-avancee",
  chapters: [
    {
      number: 1,
      title: "Introduction a l'IA Generative Avancee",
      description: "Vue d'ensemble des techniques avancees de l'IA generative en 2026.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Au-Dela des Bases : l'IA Generative Avancee" },
        { type: "paragraph", content: "Vous connaissez ChatGPT et Midjourney. Vous avez ecrit des prompts et genere des images. Mais l'IA generative avancee va bien au-dela de l'utilisation basique. Ce cours vous emmene dans les coulisses : fine-tuning, RAG, agents, APIs, embeddings, multimodal, et mise en production." },
        { type: "paragraph", content: "En 2026, les professionnels qui maitrisent ces techniques avancees sont ceux qui construisent des produits IA — pas seulement ceux qui les utilisent. La difference entre un utilisateur et un createur d'IA reside dans la comprehension des architectures sous-jacentes et la capacite a les assembler." },
        { type: "callout", content: "Ce cours est concu pour les developpeurs, data scientists, et tech leads qui veulent passer du niveau 'utilisateur' au niveau 'constructeur' d'applications IA. Des bases en programmation (Python/JavaScript) sont recommandees." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Introduction a l'IA Generative Avancee" },
        { type: "heading", content: "L'Ecosysteme en 2026" },
        { type: "paragraph", content: "L'ecosysteme IA generative a enormement mature. Les APIs sont standardisees, les frameworks d'orchestration (LangChain, LlamaIndex, Vercel AI SDK) simplifient le developpement, les bases vectorielles sont performantes, et les couts ont chute de 90% en deux ans." },
        { type: "subheading", content: "Ce Que Vous Allez Apprendre" },
        { type: "paragraph", content: "Architectures Transformer en profondeur, fine-tuning de modeles, RAG pour ancrer vos reponses dans vos donnees, agents IA autonomes, prompt engineering systeme, APIs des grands providers, frameworks d'orchestration, embeddings et bases vectorielles, generation d'images avancee, multimodal, evaluation, mise en production, optimisation des couts, et construction d'un produit IA complet." },
        { type: "key-point", content: "L'objectif n'est pas de tout memoriser mais de comprendre les patterns architecturaux. Chaque chapitre est un bloc que vous assemblerez pour construire vos propres applications IA." },
        { type: "diagram", label: "Parcours du Cours", flow: "vertical", nodes: [
          { label: "Fondations", sub: "Transformers, fine-tuning, RAG", color: "blue" },
          { label: "Orchestration", sub: "Agents, APIs, frameworks", color: "purple" },
          { label: "Avance", sub: "Multimodal, embeddings, evaluation", color: "emerald" },
          { label: "Production", sub: "Deploiement, couts, produit IA", color: "amber" },
        ]},
        { type: "summary", items: [
          "Ce cours couvre les techniques avancees pour construire des applications IA",
          "L'ecosysteme IA generative a enormement mature avec des APIs et frameworks standardises",
          "Les couts des APIs IA ont chute de 90% en deux ans",
          "Objectif : passer du niveau utilisateur au niveau constructeur d'IA",
          "Chaque chapitre est un bloc architectural assemblable",
        ]},
      ],
      quiz: [
        {
          question: "Quelle est la difference entre un utilisateur et un constructeur d'IA ?",
          options: ["Le constructeur a un meilleur abonnement", "Le constructeur comprend les architectures et assemble les composants", "Le constructeur programme en C++", "Il n'y a pas de difference"],
          correctIndex: 1,
          explanation: "Le constructeur d'IA comprend les architectures sous-jacentes (Transformers, RAG, agents) et sait les assembler pour creer des applications IA, pas seulement utiliser des outils existants.",
        },
        {
          question: "De combien les couts des APIs IA ont-ils chute en deux ans ?",
          options: ["30%", "50%", "70%", "90%"],
          correctIndex: 3,
          explanation: "Les couts des APIs IA ont chute de 90% en deux ans grace a la concurrence entre providers, l'optimisation des modeles, et les economies d'echelle.",
        },
        {
          question: "Quel prerequis est recommande pour ce cours ?",
          options: ["Un doctorat en IA", "Des bases en programmation (Python/JavaScript)", "10 ans d'experience en ML", "Aucun"],
          correctIndex: 1,
          explanation: "Des bases en programmation Python ou JavaScript sont recommandees pour suivre les exemples de code et construire des applications IA.",
        },
        {
          question: "Que signifie RAG dans le contexte de l'IA ?",
          options: ["Rapid AI Generation", "Retrieval-Augmented Generation", "Random Algorithm Generator", "Real-time AI Gateway"],
          correctIndex: 1,
          explanation: "RAG (Retrieval-Augmented Generation) est une technique qui ancre les reponses d'un LLM dans des donnees externes specifiques, reduisant les hallucinations et personnalisant les reponses.",
        },
      ],
    },
    {
      number: 2,
      title: "Architectures Transformer en Profondeur",
      description: "Comprendre en detail le mecanisme d'attention, les couches et les variantes des Transformers.",
      estimatedMinutes: 10,
      sections: [
        { type: "heading", content: "Le Transformer Decortique" },
        { type: "paragraph", content: "L'architecture Transformer, introduite dans 'Attention Is All You Need' (2017), est la fondation de tous les LLM modernes. Comprendre son fonctionnement est essentiel pour le fine-tuning, l'optimisation et le debugging des applications IA." },
        { type: "subheading", content: "Le Mecanisme d'Attention" },
        { type: "paragraph", content: "Le self-attention permet a chaque token de 'regarder' tous les autres tokens de la sequence pour comprendre le contexte. Pour chaque token, le modele calcule trois vecteurs : Query (ce que je cherche), Key (ce que je represente), et Value (l'information que je porte). Le score d'attention est le produit scalaire Query * Key, normalise et pondere." },
        { type: "paragraph", content: "Le Multi-Head Attention execute plusieurs mecanismes d'attention en parallele, chaque 'tete' apprenant a se focaliser sur differents aspects : l'une sur la syntaxe, une autre sur la semantique, une autre sur les relations longue distance." },
        { type: "callout", content: "L'attention est la raison pour laquelle les Transformers surpassent les RNN : ils traitent toute la sequence en parallele au lieu de la parcourir sequentiellement. C'est aussi pourquoi l'entrainement est plus rapide sur GPU." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Le mecanisme d'attention explique visuellement" },
        { type: "heading", content: "Architecture Encoder-Decoder vs Decoder-Only" },
        { type: "paragraph", content: "Le Transformer original est un encoder-decoder (utilise pour la traduction). BERT est un encoder-only (comprend le texte). GPT, Claude et Gemini sont des decoder-only (generent du texte). Les decoder-only dominent en 2026 car ils sont plus simples a scaler et plus polyvalents." },
        { type: "subheading", content: "Positional Encoding et Contexte Long" },
        { type: "paragraph", content: "Les Transformers n'ont pas de notion intrinseque de position. Le positional encoding injecte l'information de position. RoPE (Rotary Position Embedding) est utilise par la plupart des LLM modernes et permet l'extension du contexte a 1 million+ de tokens via des techniques comme YaRN et ALiBi." },
        { type: "key-point", content: "La complexite du self-attention est O(n²) par rapport a la longueur de la sequence. C'est le principal goulot d'etranglement pour les contextes longs. Les techniques comme Flash Attention et Ring Attention reduisent ce cout en pratique." },
        { type: "diagram", label: "Architecture d'un Bloc Transformer", flow: "vertical", nodes: [
          { label: "Input Embeddings + Positional Encoding", sub: "Tokens → vecteurs + positions", color: "blue" },
          { label: "Multi-Head Self-Attention", sub: "Query, Key, Value × N tetes", color: "purple" },
          { label: "Feed-Forward Network", sub: "Transformation non-lineaire", color: "emerald" },
          { label: "Layer Normalization + Residual", sub: "Stabilisation de l'entrainement", color: "amber" },
        ]},
        { type: "tip", content: "Pour visualiser le mecanisme d'attention en action, utilisez BertViz ou l'outil d'attention de 3Blue1Brown. Voir les patterns d'attention aide enormement a comprendre ce que le modele 'regarde'." },
        { type: "summary", items: [
          "Le self-attention permet a chaque token de considerer tous les autres tokens",
          "Multi-Head Attention : plusieurs tetes focalisees sur differents aspects",
          "Decoder-only (GPT, Claude) domine en 2026 par sa polyvalence",
          "RoPE et YaRN permettent d'etendre le contexte a 1 million+ de tokens",
          "La complexite O(n²) est le principal goulot, attenude par Flash Attention",
        ]},
      ],
      quiz: [
        {
          question: "Quels sont les trois vecteurs calcules dans le self-attention ?",
          options: ["Input, Output, Hidden", "Query, Key, Value", "Encoder, Decoder, Attention", "Weight, Bias, Activation"],
          correctIndex: 1,
          explanation: "Pour chaque token, le mecanisme de self-attention calcule trois vecteurs : Query (ce que je cherche), Key (ce que je represente), et Value (l'information que je porte).",
        },
        {
          question: "Quelle est la complexite du self-attention par rapport a la longueur de sequence ?",
          options: ["O(n)", "O(n log n)", "O(n²)", "O(n³)"],
          correctIndex: 2,
          explanation: "La complexite du self-attention est O(n²) par rapport a la longueur de la sequence, car chaque token doit 'regarder' tous les autres tokens.",
        },
        {
          question: "Quel type d'architecture utilisent GPT et Claude ?",
          options: ["Encoder-only", "Encoder-decoder", "Decoder-only", "Attention-only"],
          correctIndex: 2,
          explanation: "GPT, Claude et Gemini utilisent une architecture decoder-only, optimisee pour la generation de texte. Elle domine en 2026 par sa simplicite et sa polyvalence.",
        },
        {
          question: "Quelle technique reduit le cout de l'attention sur les sequences longues ?",
          options: ["Dropout", "Flash Attention", "Batch normalization", "L2 regularization"],
          correctIndex: 1,
          explanation: "Flash Attention est une technique d'optimisation qui reduit le cout memoire et calcul du self-attention en reorganisant les operations pour mieux utiliser la hierarchie memoire du GPU.",
        },
      ],
    },
    {
      number: 3,
      title: "Fine-tuning de Modeles de Langage",
      description: "Adapter un modele pre-entraine a vos donnees et votre cas d'usage specifique.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Le Fine-tuning : Personnaliser un LLM" },
        { type: "paragraph", content: "Le fine-tuning consiste a re-entrainer partiellement un modele pre-entraine sur vos propres donnees pour l'adapter a votre cas d'usage. Un modele generique devient un expert de votre domaine : juridique, medical, financier, ou technique." },
        { type: "paragraph", content: "En 2026, le fine-tuning est devenu accessible grace aux techniques de parameter-efficient fine-tuning (PEFT) qui ne modifient qu'une fraction des parametres. LoRA, QLoRA et adapters permettent de fine-tuner des modeles de 70B parametres sur un seul GPU." },
        { type: "subheading", content: "Quand Fine-Tuner vs Quand Utiliser RAG ?" },
        { type: "paragraph", content: "Fine-tuning quand : vous voulez changer le style/ton du modele, vous avez des patterns de raisonnement specifiques, ou le prompt engineering ne suffit pas. RAG quand : vous voulez ancrer les reponses dans des donnees actualisees, les donnees changent frequemment, ou vous avez besoin de citations exactes." },
        { type: "callout", content: "Regle d'or : essayez d'abord le prompt engineering, puis RAG, puis le fine-tuning. Chaque etape est plus couteuse et complexe. Le fine-tuning est la derniere option, pas la premiere." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Fine-tuning de LLM en pratique" },
        { type: "heading", content: "Techniques de Fine-tuning" },
        { type: "subheading", content: "LoRA (Low-Rank Adaptation)" },
        { type: "paragraph", content: "LoRA gele les poids du modele original et ajoute de petites matrices de rang faible a chaque couche. Seules ces matrices sont entrainees (0,1% des parametres totaux). Le resultat : un fine-tuning rapide, peu couteux, et reversible — vous pouvez empiler plusieurs LoRA pour differents cas d'usage." },
        { type: "subheading", content: "QLoRA" },
        { type: "paragraph", content: "QLoRA combine LoRA avec la quantification 4-bit. Le modele de base est compresse en 4-bit pour tenir en memoire, et les adapters LoRA sont entraines en precision normale. Resultat : fine-tuner un modele 70B sur un GPU de 24GB." },
        { type: "key-point", content: "La qualite du fine-tuning depend a 80% de la qualite de vos donnees. Investissez dans la curation de votre dataset : exemples propres, divers, representatifs, et alignes avec votre objectif." },
        { type: "diagram", label: "Decision : Prompt vs RAG vs Fine-tuning", flow: "vertical", nodes: [
          { label: "Prompt Engineering", sub: "Premier essai, gratuit, rapide", color: "emerald" },
          { label: "RAG", sub: "Donnees dynamiques, citations, precision", color: "blue" },
          { label: "Fine-tuning", sub: "Style, ton, patterns specifiques", color: "purple" },
        ]},
        { type: "prompt-example", prompt: "Tu es un expert en fine-tuning. J'ai 5000 conversations de support client. Comment preparer mes donnees pour fine-tuner un modele qui repond aux tickets automatiquement ?", result: "Structurez chaque exemple en format instruction/reponse. Filtrez les conversations de qualite, anonymisez les donnees, et divisez en train/eval (90/10). Utilisez le format ChatML ou Alpaca." },
        { type: "summary", items: [
          "Le fine-tuning adapte un modele pre-entraine a votre domaine specifique",
          "LoRA ne modifie que 0,1% des parametres — rapide et economique",
          "QLoRA permet de fine-tuner un modele 70B sur un GPU de 24GB",
          "Hierarchie : prompt engineering → RAG → fine-tuning (du plus simple au plus complexe)",
          "La qualite des donnees determine 80% du resultat du fine-tuning",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que LoRA ?",
          options: ["Un nouveau modele de langage", "Une technique de fine-tuning qui ajoute des matrices de rang faible", "Un framework d'orchestration", "Un type d'attention"],
          correctIndex: 1,
          explanation: "LoRA (Low-Rank Adaptation) gele les poids originaux du modele et ajoute de petites matrices de rang faible entrainees, ne modifiant que 0,1% des parametres totaux.",
        },
        {
          question: "Quel est l'ordre recommande pour personnaliser un LLM ?",
          options: ["Fine-tuning → RAG → Prompt engineering", "Prompt engineering → RAG → Fine-tuning", "RAG → Fine-tuning → Prompt engineering", "Fine-tuning → Prompt engineering → RAG"],
          correctIndex: 1,
          explanation: "On recommande de commencer par le prompt engineering (gratuit, rapide), puis RAG (donnees dynamiques), et enfin le fine-tuning (plus couteux) seulement si necessaire.",
        },
        {
          question: "Que permet QLoRA ?",
          options: ["D'entrainer un modele depuis zero", "De fine-tuner un modele 70B sur un GPU de 24GB", "De generer des images", "De traduire automatiquement"],
          correctIndex: 1,
          explanation: "QLoRA combine LoRA avec la quantification 4-bit, permettant de fine-tuner un modele de 70 milliards de parametres sur un seul GPU de 24GB de VRAM.",
        },
        {
          question: "Quel facteur determine 80% du resultat du fine-tuning ?",
          options: ["La taille du modele", "Le GPU utilise", "La qualite des donnees d'entrainement", "Le nombre d'epochs"],
          correctIndex: 2,
          explanation: "La qualite des donnees d'entrainement determine 80% du resultat. Des exemples propres, divers et representatifs sont plus importants que la quantite ou le materiel.",
        },
      ],
    },
    {
      number: 4,
      title: "RAG : Retrieval-Augmented Generation",
      description: "Ancrer les reponses de votre LLM dans vos propres donnees avec le RAG.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "RAG : Le Pattern Architectural Incontournable" },
        { type: "paragraph", content: "Le RAG (Retrieval-Augmented Generation) est le pattern le plus utilise en IA generative en 2026. Il combine un systeme de recherche (retrieval) avec un LLM (generation) pour produire des reponses ancrees dans vos donnees specifiques. C'est la solution au probleme des hallucinations et de la connaissance limitee des LLM." },
        { type: "paragraph", content: "Le principe est simple : avant de generer une reponse, le systeme recherche les documents pertinents dans votre base de connaissances, les injecte dans le contexte du LLM, et le modele genere sa reponse en se basant sur ces documents." },
        { type: "subheading", content: "Architecture RAG Standard" },
        { type: "paragraph", content: "1) Indexation : vos documents sont decoupes en chunks, convertis en embeddings vectoriels, et stockes dans une base vectorielle. 2) Retrieval : la question de l'utilisateur est convertie en embedding et les chunks les plus similaires sont recuperes. 3) Generation : les chunks pertinents sont injectes dans le prompt et le LLM genere la reponse." },
        { type: "callout", content: "Le chunking est l'etape la plus sous-estimee du RAG. La taille des chunks (256-1024 tokens), le chevauchement (10-20%), et la strategie de decoupage (paragraphes, sections, phrases) impactent enormement la qualite des reponses." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "RAG en detail" },
        { type: "heading", content: "RAG Avance" },
        { type: "paragraph", content: "Les techniques avancees de RAG incluent : le re-ranking (reordonner les resultats par pertinence), le RAG iteratif (plusieurs cycles de recherche), l'agentic RAG (le LLM decide quand et quoi chercher), le RAG multimodal (texte + images), et le fusion RAG (combiner plusieurs strategies de retrieval)." },
        { type: "key-point", content: "La qualite du RAG depend de la qualite du retrieval. Un retrieval mediocre = des reponses mediocres. Investissez dans les embeddings, le chunking, et le re-ranking avant d'optimiser la generation." },
        { type: "diagram", label: "Architecture RAG", flow: "horizontal", nodes: [
          { label: "Indexation", sub: "Chunks → Embeddings → Vector DB", color: "blue" },
          { label: "Retrieval", sub: "Query → Recherche semantique", color: "purple" },
          { label: "Generation", sub: "Contexte + LLM → Reponse", color: "emerald" },
        ]},
        { type: "diagram", label: "Techniques RAG Avancees", flow: "vertical", nodes: [
          { label: "Re-ranking", sub: "Reordonner par pertinence", color: "blue" },
          { label: "RAG iteratif", sub: "Plusieurs cycles de recherche", color: "purple" },
          { label: "Agentic RAG", sub: "LLM decide quoi chercher", color: "emerald" },
          { label: "RAG multimodal", sub: "Texte + images + tableaux", color: "amber" },
        ]},
        { type: "summary", items: [
          "Le RAG combine recherche documentaire et generation LLM",
          "Il resout le probleme des hallucinations en ancrant les reponses dans vos donnees",
          "Le chunking est l'etape la plus critique et la plus sous-estimee",
          "Les techniques avancees incluent re-ranking, RAG iteratif et agentic RAG",
          "La qualite du retrieval determine la qualite de la generation",
        ]},
      ],
      quiz: [
        {
          question: "Quel probleme principal le RAG resout-il ?",
          options: ["La lenteur des LLM", "Les hallucinations et la connaissance limitee", "Le cout des APIs", "La generation d'images"],
          correctIndex: 1,
          explanation: "Le RAG ancre les reponses du LLM dans vos donnees specifiques, reduisant les hallucinations et permettant au modele de repondre sur des sujets qu'il ne connait pas nativement.",
        },
        {
          question: "Quelle est la taille de chunk recommandee pour le RAG ?",
          options: ["32-64 tokens", "256-1024 tokens", "5000-10000 tokens", "1 document entier"],
          correctIndex: 1,
          explanation: "La taille de chunk recommandee est de 256 a 1024 tokens, avec un chevauchement de 10-20% entre les chunks pour preserver le contexte.",
        },
        {
          question: "Qu'est-ce que l'agentic RAG ?",
          options: ["Un agent qui remplace le RAG", "Un RAG ou le LLM decide quand et quoi chercher", "Un RAG sans base vectorielle", "Un RAG pour les agents de support"],
          correctIndex: 1,
          explanation: "L'agentic RAG donne au LLM le controle sur le processus de recherche : il decide quand chercher, quelle requete formuler, et s'il a besoin de recherches supplementaires.",
        },
        {
          question: "Quelle etape du RAG est la plus sous-estimee ?",
          options: ["La generation", "Le choix du LLM", "Le chunking", "L'interface utilisateur"],
          correctIndex: 2,
          explanation: "Le chunking est l'etape la plus sous-estimee. La taille, le chevauchement et la strategie de decoupage impactent enormement la qualite du retrieval et donc des reponses.",
        },
      ],
    },
    {
      number: 5,
      title: "Agents IA et Tool Use",
      description: "Construire des agents autonomes qui raisonnent, planifient et utilisent des outils.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Les Agents IA : L'IA qui Agit" },
        { type: "paragraph", content: "Un agent IA est un systeme autonome qui utilise un LLM comme moteur de raisonnement pour planifier et executer des sequences d'actions. Contrairement a un chatbot, un agent peut utiliser des outils (recherche web, execution de code, appels API, manipulation de fichiers) pour atteindre des objectifs complexes." },
        { type: "paragraph", content: "En 2026, les agents IA sont la prochaine frontiere. Claude Opus 4.6 avec 14,5h d'autonomie, GPT-5.4 avec Computer Use natif, et des frameworks comme LangGraph et CrewAI permettent de construire des agents sophistiques." },
        { type: "subheading", content: "Le Paradigme ReAct" },
        { type: "paragraph", content: "ReAct (Reasoning + Acting) est le paradigme dominant pour les agents. L'agent alterne entre pensee (Thought : je reflechis a ce qu'il faut faire), action (Action : j'utilise un outil), et observation (Observation : j'analyse le resultat). Cette boucle continue jusqu'a atteindre l'objectif." },
        { type: "subheading", content: "Tool Use et Function Calling" },
        { type: "paragraph", content: "Le function calling permet au LLM d'appeler des fonctions/outils de maniere structuree. Le modele recoit une liste de fonctions disponibles (avec leur schema JSON), decide laquelle appeler avec quels arguments, et integre le resultat dans son raisonnement." },
        { type: "callout", content: "Le protocole MCP (Model Context Protocol) d'Anthropic standardise la communication entre agents et outils. C'est le 'USB-C des agents IA' — un standard universel pour connecter n'importe quel outil a n'importe quel agent." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Construire un agent IA" },
        { type: "heading", content: "Patterns d'Architecture Multi-Agent" },
        { type: "paragraph", content: "Les systemes multi-agents assignent des roles specialises a differents agents qui collaborent. Un agent 'planificateur' decompose la tache, un agent 'chercheur' collecte les informations, un agent 'executeur' effectue les actions, et un agent 'revieweur' valide le resultat. CrewAI, AutoGen et LangGraph facilitent cette orchestration." },
        { type: "key-point", content: "La cle d'un bon agent est la definition precise des outils disponibles et de leurs schemas. Un outil mal defini = un agent qui hallucine ses appels. Investissez dans la documentation des outils." },
        { type: "diagram", label: "Boucle ReAct d'un Agent", flow: "cycle", nodes: [
          { label: "Thought", sub: "Raisonnement sur la prochaine etape", color: "blue" },
          { label: "Action", sub: "Appel d'un outil ou fonction", color: "emerald" },
          { label: "Observation", sub: "Analyse du resultat", color: "purple" },
        ]},
        { type: "prompt-example", prompt: "Construis un agent de recherche qui : 1) Recoit une question, 2) Cherche sur le web, 3) Analyse les sources, 4) Genere un rapport structure avec citations.", result: "L'agent utilise ReAct : il planifie les requetes de recherche, appelle l'outil web_search, analyse chaque resultat, et compile un rapport avec les sources." },
        { type: "summary", items: [
          "Les agents IA utilisent des LLM pour raisonner et des outils pour agir",
          "ReAct alterne pensee, action et observation en boucle",
          "Le function calling structure les appels d'outils par le LLM",
          "MCP standardise la connexion entre agents et outils",
          "Les systemes multi-agents assignent des roles specialises pour collaborer",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce qui differencie un agent IA d'un chatbot ?",
          options: ["Un agent est plus rapide", "Un agent peut planifier et utiliser des outils", "Un agent est gratuit", "Un agent ne fait que du texte"],
          correctIndex: 1,
          explanation: "Un agent IA peut planifier des sequences d'actions, utiliser des outils externes, et s'adapter aux resultats — un chatbot se contente de repondre a des messages.",
        },
        {
          question: "Que signifie MCP dans l'ecosysteme des agents IA ?",
          options: ["Machine Core Protocol", "Model Context Protocol", "Multi-Channel Processing", "Managed Cloud Platform"],
          correctIndex: 1,
          explanation: "MCP (Model Context Protocol) est un standard cree par Anthropic pour la communication entre agents IA et outils, permettant une interoperabilite universelle.",
        },
        {
          question: "Dans le paradigme ReAct, quelle est la sequence correcte ?",
          options: ["Action → Thought → Observation", "Observation → Action → Thought", "Thought → Action → Observation", "Action → Observation → Thought"],
          correctIndex: 2,
          explanation: "ReAct suit la sequence Thought (reflexion), Action (utilisation d'un outil), Observation (analyse du resultat), repetee en boucle jusqu'a l'objectif.",
        },
        {
          question: "Quel framework permet l'orchestration multi-agents ?",
          options: ["React.js", "Django", "CrewAI / LangGraph", "Express.js"],
          correctIndex: 2,
          explanation: "CrewAI, LangGraph et AutoGen sont des frameworks specialises dans l'orchestration de systemes multi-agents avec des roles et des workflows collaboratifs.",
        },
      ],
    },
    {
      number: 6,
      title: "Prompt Engineering Systeme",
      description: "System prompts, meta-prompting et techniques avancees de prompt engineering.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Le Prompt Engineering Systeme" },
        { type: "paragraph", content: "Le prompt engineering systeme va au-dela des prompts utilisateur. Il s'agit de definir le comportement, la personnalite, les contraintes et les capacites d'un systeme IA complet via le system prompt. C'est l'equivalent de la 'programmation' d'un LLM." },
        { type: "paragraph", content: "Un system prompt bien concu transforme un LLM generique en un assistant specialise. Il definit le role, le ton, les regles de securite, le format de sortie, les limites, et les instructions de fallback. C'est le coeur de toute application IA." },
        { type: "subheading", content: "Structure d'un System Prompt Professionnel" },
        { type: "paragraph", content: "Un system prompt efficace suit une structure en couches : 1) Identite et role, 2) Contexte et connaissances, 3) Regles et contraintes, 4) Format de sortie, 5) Exemples (few-shot), 6) Instructions de securite. Chaque couche renforce la precedente." },
        { type: "callout", content: "Le system prompt de Claude (Anthropic) fait plus de 4000 tokens. Celui de ChatGPT (OpenAI) en fait environ 3000. Les system prompts professionnels sont des documents detailles, pas des phrases simples." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "System prompts avances" },
        { type: "subheading", content: "Meta-Prompting" },
        { type: "paragraph", content: "Le meta-prompting utilise un LLM pour generer ou optimiser des prompts. Vous decrivez votre objectif et le modele genere le prompt optimal. C'est particulierement utile pour les cas d'usage complexes ou le prompt engineering manuel atteint ses limites." },
        { type: "heading", content: "Techniques Avancees" },
        { type: "paragraph", content: "Chain-of-Thought force le raisonnement etape par etape. Tree-of-Thought explore plusieurs pistes en parallele. Prompt chaining enchaine plusieurs appels LLM. Le constitutional AI integre des principes ethiques directement dans le prompt." },
        { type: "key-point", content: "Le prompt caching est critique pour les couts. Placez les instructions stables (system prompt, exemples) au debut et le contenu dynamique a la fin. Le cache Anthropic a un TTL de 5 minutes — structurez vos appels en consequence." },
        { type: "prompt-example", prompt: "Tu es un expert en redaction de system prompts. Cree un system prompt pour un assistant juridique specialise en droit du travail francais. Il doit citer les articles de loi, refuser les questions hors perimetre, et avertir qu'il ne remplace pas un avocat.", result: "Le system prompt genere inclut le role (juriste assistant), les connaissances (Code du travail), les regles (citations obligatoires, disclaimers), le format (structure juridique) et les garde-fous (perimetre, disclaimer)." },
        { type: "diagram", label: "Structure d'un System Prompt", flow: "vertical", nodes: [
          { label: "Identite & Role", sub: "Qui est l'assistant, son expertise", color: "purple" },
          { label: "Regles & Contraintes", sub: "Ce qu'il peut et ne peut pas faire", color: "blue" },
          { label: "Format de Sortie", sub: "Structure, longueur, style", color: "emerald" },
          { label: "Securite & Garde-fous", sub: "Limites, disclaimers, refus", color: "pink" },
        ]},
        { type: "summary", items: [
          "Le system prompt est la 'programmation' d'un LLM pour une application specifique",
          "Structure en couches : identite, regles, format, exemples, securite",
          "Les system prompts professionnels font 3000-4000+ tokens",
          "Le meta-prompting utilise un LLM pour generer des prompts optimaux",
          "Le prompt caching reduit les couts — structurez statique en premier",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que le prompt engineering systeme ?",
          options: ["Ecrire des prompts utilisateur", "Definir le comportement complet d'un systeme IA via le system prompt", "Programmer un LLM en Python", "Generer des images avec des prompts"],
          correctIndex: 1,
          explanation: "Le prompt engineering systeme consiste a definir le comportement, la personnalite, les contraintes et les capacites d'un systeme IA complet via le system prompt.",
        },
        {
          question: "Combien de tokens fait un system prompt professionnel ?",
          options: ["50-100 tokens", "500-1000 tokens", "3000-4000+ tokens", "100 000 tokens"],
          correctIndex: 2,
          explanation: "Les system prompts professionnels comme ceux de Claude ou ChatGPT font 3000-4000+ tokens. Ce sont des documents detailles definissant le comportement complet du systeme.",
        },
        {
          question: "Qu'est-ce que le meta-prompting ?",
          options: ["Un prompt tres long", "Utiliser un LLM pour generer des prompts optimaux", "Un type de prompt pour les images", "Un prompt qui se corrige lui-meme"],
          correctIndex: 1,
          explanation: "Le meta-prompting utilise un LLM pour generer ou optimiser des prompts, particulierement utile pour les cas d'usage complexes ou le prompt engineering manuel atteint ses limites.",
        },
        {
          question: "Pourquoi le prompt caching est-il important ?",
          options: ["Pour accelerer la generation", "Pour reduire les couts en cachant les parties statiques", "Pour sauvegarder les prompts", "Pour partager les prompts"],
          correctIndex: 1,
          explanation: "Le prompt caching permet de ne pas re-traiter les parties statiques du prompt (system prompt, exemples) a chaque appel, reduisant significativement les couts d'API.",
        },
      ],
    },
    {
      number: 7,
      title: "APIs OpenAI, Anthropic et Google",
      description: "Maitriser les APIs des trois grands providers pour construire des applications IA.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Les APIs des Grands Providers IA" },
        { type: "paragraph", content: "Les APIs d'OpenAI, Anthropic et Google sont les briques de base pour construire des applications IA. Chaque provider a ses forces, ses prix et ses specificites. Maitriser ces APIs est essentiel pour tout developpeur IA." },
        { type: "subheading", content: "API OpenAI (GPT-5.4)" },
        { type: "paragraph", content: "L'API OpenAI est la plus utilisee. Elle offre les endpoints Chat Completions, Assistants API (avec memory et tools), DALL-E, Whisper (speech-to-text), et TTS (text-to-speech). Le streaming, le function calling, et la vision sont integres nativement. Tarif : $2.50/M tokens input, $10/M tokens output pour GPT-5.4." },
        { type: "subheading", content: "API Anthropic (Claude 4.6)" },
        { type: "paragraph", content: "L'API Anthropic se distingue par le prompt caching (reduction de 90% des couts sur les parties statiques), l'Extended Thinking (raisonnement visible), le Computer Use, et les batches (50% de reduction). Claude Opus 4.6 : $15/M input, $75/M output. Claude Sonnet 4.6 : $3/M input, $15/M output." },
        { type: "subheading", content: "API Google (Gemini 3.1)" },
        { type: "paragraph", content: "L'API Gemini est nativement multimodal (texte, image, audio, video dans le meme appel). Contexte de 1M tokens, grounding with Google Search, et integration a l'ecosysteme Google Cloud. Gemini 3.1 Pro est gratuit pour les developpeurs jusqu'a 60 requetes/minute." },
        { type: "callout", content: "Astuce couts : utilisez Claude Haiku ou GPT-4o-mini pour les taches simples (classification, extraction), et reservez les modeles premium (Opus, GPT-5.4 Pro) pour les taches complexes de raisonnement. Le routing intelligent reduit les couts de 70%." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "APIs IA en pratique" },
        { type: "key-point", content: "Ne vous enfermez pas dans un seul provider. Utilisez une couche d'abstraction (Vercel AI SDK, LiteLLM) pour pouvoir switcher entre providers selon les performances et les couts." },
        { type: "diagram", label: "Comparatif des APIs en 2026", flow: "horizontal", nodes: [
          { label: "OpenAI", sub: "Le plus utilise, Assistants API, DALL-E", color: "emerald" },
          { label: "Anthropic", sub: "Prompt caching, Extended Thinking", color: "purple" },
          { label: "Google", sub: "Multimodal natif, gratuit dev, Google Search", color: "blue" },
        ]},
        { type: "prompt-example", prompt: "Compare le cout pour traiter 1 million de documents de 500 tokens chacun avec Claude Sonnet vs GPT-4o-mini vs Gemini Flash. Inclus le prompt caching pour Claude.", result: "Avec prompt caching Anthropic, Claude Sonnet revient a ~$0.30/M tokens cache. GPT-4o-mini : $0.15/M input. Gemini Flash : gratuit jusqu'au quota. Le choix depend du ratio qualite/cout." },
        { type: "summary", items: [
          "OpenAI : l'API la plus utilisee avec Assistants API et function calling",
          "Anthropic : prompt caching (-90% couts), Extended Thinking, batches",
          "Google : multimodal natif, 1M tokens, gratuit pour les developpeurs",
          "Le routing intelligent entre modeles reduit les couts de 70%",
          "Utilisez une couche d'abstraction pour ne pas dependre d'un seul provider",
        ]},
      ],
      quiz: [
        {
          question: "Quel avantage unique offre l'API Anthropic ?",
          options: ["La generation d'images", "Le prompt caching avec 90% de reduction", "La generation de video", "L'acces gratuit illimite"],
          correctIndex: 1,
          explanation: "L'API Anthropic se distingue par son prompt caching qui reduit de 90% les couts sur les parties statiques du prompt, un avantage majeur pour les applications avec des system prompts longs.",
        },
        {
          question: "Quelle API est nativement multimodale (texte + image + audio + video) ?",
          options: ["OpenAI", "Anthropic", "Google Gemini", "Mistral"],
          correctIndex: 2,
          explanation: "L'API Gemini de Google est nativement multimodale, acceptant texte, images, audio et video dans le meme appel API, sans endpoints separes.",
        },
        {
          question: "Comment reduire les couts d'API de 70% ?",
          options: ["En negociant un contrat", "En utilisant le routing intelligent entre modeles", "En envoyant moins de requetes", "En compressant les donnees"],
          correctIndex: 1,
          explanation: "Le routing intelligent dirige les taches simples vers des modeles economiques (Haiku, GPT-4o-mini) et reserve les modeles premium pour les taches complexes, reduisant les couts de 70%.",
        },
        {
          question: "Pourquoi utiliser une couche d'abstraction comme Vercel AI SDK ?",
          options: ["Pour accelerer les reponses", "Pour pouvoir switcher entre providers sans changer le code", "Pour generer des images", "Pour stocker les conversations"],
          correctIndex: 1,
          explanation: "Une couche d'abstraction permet de changer de provider (OpenAI, Anthropic, Google) sans modifier le code applicatif, offrant flexibilite et resilience.",
        },
      ],
    },
    {
      number: 8,
      title: "Langchain et Frameworks d'Orchestration",
      description: "Utiliser LangChain, LlamaIndex et LangGraph pour orchestrer des applications IA complexes.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Les Frameworks d'Orchestration IA" },
        { type: "paragraph", content: "Les frameworks d'orchestration simplifient la construction d'applications IA complexes en fournissant des abstractions pour les chains, les agents, les outils, la memoire et le RAG. LangChain, LlamaIndex et LangGraph sont les trois piliers de l'ecosysteme en 2026." },
        { type: "subheading", content: "LangChain" },
        { type: "paragraph", content: "LangChain est le framework le plus populaire. Il fournit des abstractions pour les LLM, les prompts, les chains (sequences d'appels), les agents (boucles de raisonnement), les outils, et la memoire. Il supporte Python et JavaScript/TypeScript." },
        { type: "subheading", content: "LlamaIndex" },
        { type: "paragraph", content: "LlamaIndex est specialise dans le RAG et l'indexation de donnees. Il excelle dans l'ingestion de documents (PDF, web, bases de donnees), le chunking intelligent, les embeddings, et la recherche semantique. C'est le choix ideal pour les applications centrees sur les donnees." },
        { type: "subheading", content: "LangGraph" },
        { type: "paragraph", content: "LangGraph est le framework pour les agents complexes et les workflows multi-etapes. Il modelise les applications IA comme des graphes d'etats (state machines) avec des noeuds (actions) et des aretes (transitions). Il gere nativement la persistence, le streaming, et le human-in-the-loop." },
        { type: "callout", content: "Attention a la 'framework fatigue' : LangChain a ete critique pour sa complexite. Evaluez si un simple appel API suffit avant d'ajouter un framework. La simplicite est souvent la meilleure architecture." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "LangChain et LangGraph en pratique" },
        { type: "heading", content: "Alternatives Legeres" },
        { type: "paragraph", content: "Vercel AI SDK est une alternative legere et moderne pour les applications web. Il gere le streaming, le function calling, et les providers multiples avec une API simple. Pour les projets simples, un appel API direct avec gestion manuelle du contexte peut suffire." },
        { type: "key-point", content: "Choisissez votre framework selon le cas d'usage : LlamaIndex pour le RAG, LangGraph pour les agents complexes, Vercel AI SDK pour les apps web, et API directe pour les cas simples." },
        { type: "diagram", label: "Ecosysteme des Frameworks IA", flow: "horizontal", nodes: [
          { label: "LangChain", sub: "Chains, agents, outils, memoire", color: "blue" },
          { label: "LlamaIndex", sub: "RAG, indexation, documents", color: "purple" },
          { label: "LangGraph", sub: "Graphes d'etats, agents complexes", color: "emerald" },
          { label: "Vercel AI SDK", sub: "Apps web, streaming, leger", color: "amber" },
        ]},
        { type: "summary", items: [
          "LangChain : framework generaliste pour chains, agents et outils",
          "LlamaIndex : specialise RAG, indexation et ingestion de documents",
          "LangGraph : graphes d'etats pour agents complexes et workflows",
          "Vercel AI SDK : alternative legere pour les applications web",
          "Evaluer si un framework est necessaire — la simplicite est souvent preferable",
        ]},
      ],
      quiz: [
        {
          question: "Quel framework est specialise dans le RAG et l'indexation ?",
          options: ["LangChain", "LlamaIndex", "LangGraph", "React"],
          correctIndex: 1,
          explanation: "LlamaIndex est specialise dans le RAG et l'indexation de donnees, avec des outils avances pour l'ingestion, le chunking et la recherche semantique.",
        },
        {
          question: "Comment LangGraph modelise-t-il les applications IA ?",
          options: ["Comme des listes", "Comme des graphes d'etats", "Comme des tableaux", "Comme des arbres"],
          correctIndex: 1,
          explanation: "LangGraph modelise les applications IA comme des graphes d'etats (state machines) avec des noeuds (actions) et des aretes (transitions), ideal pour les agents complexes.",
        },
        {
          question: "Quel conseil est donne concernant les frameworks ?",
          options: ["Toujours utiliser LangChain", "Evaluer si un simple appel API suffit avant d'ajouter un framework", "Combiner tous les frameworks", "Eviter tous les frameworks"],
          correctIndex: 1,
          explanation: "Il est recommande d'evaluer si un simple appel API suffit avant d'ajouter un framework complexe. La simplicite est souvent la meilleure architecture.",
        },
        {
          question: "Quel framework est recommande pour les applications web avec streaming ?",
          options: ["LangChain", "LlamaIndex", "LangGraph", "Vercel AI SDK"],
          correctIndex: 3,
          explanation: "Vercel AI SDK est une alternative legere et moderne specialisee pour les applications web, avec gestion native du streaming et du function calling.",
        },
      ],
    },
    {
      number: 9,
      title: "Embeddings et Bases Vectorielles",
      description: "Comprendre les embeddings et utiliser les bases vectorielles pour la recherche semantique.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Les Embeddings : Le Langage des Machines" },
        { type: "paragraph", content: "Les embeddings sont des representations numeriques (vecteurs) du texte, des images ou de l'audio dans un espace multidimensionnel. Deux textes semantiquement similaires auront des embeddings proches. C'est la technologie qui permet la recherche semantique, le clustering, et le RAG." },
        { type: "paragraph", content: "Les modeles d'embedding modernes (OpenAI text-embedding-3, Cohere Embed v3, Voyage AI) produisent des vecteurs de 256 a 3072 dimensions. La similarite entre deux embeddings est mesuree par la distance cosinus ou le produit scalaire." },
        { type: "subheading", content: "Bases de Donnees Vectorielles" },
        { type: "paragraph", content: "Les bases vectorielles stockent et indexent des millions d'embeddings pour permettre des recherches par similarite en millisecondes. Les principales : Pinecone (managed, serverless), Weaviate (open source, filtrage hybride), Qdrant (Rust, performant), ChromaDB (leger, local), et pgvector (extension PostgreSQL)." },
        { type: "callout", content: "Pour la plupart des projets, pgvector (extension PostgreSQL) est suffisant. Vous n'avez pas besoin d'une base vectorielle dedicee si vous avez deja PostgreSQL. Commencez simple et scalez si necessaire." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Embeddings et bases vectorielles" },
        { type: "heading", content: "Recherche Hybride" },
        { type: "paragraph", content: "La recherche hybride combine la recherche semantique (embeddings) avec la recherche lexicale (BM25, full-text search). Cette combinaison donne les meilleurs resultats pour le RAG car elle capture a la fois le sens (semantique) et les mots-cles exacts (lexical)." },
        { type: "key-point", content: "La qualite des embeddings depend du modele utilise. Pour le francais, testez Voyage AI (multilingue de reference), Cohere Embed v3, et OpenAI text-embedding-3-large. Evaluez sur vos propres donnees — les benchmarks generiques ne suffisent pas." },
        { type: "diagram", label: "Pipeline Embeddings + Vector DB", flow: "horizontal", nodes: [
          { label: "Texte / Documents", sub: "Chunks de contenu brut", color: "blue" },
          { label: "Modele d'Embedding", sub: "text-embedding-3, Voyage AI", color: "purple" },
          { label: "Base Vectorielle", sub: "Pinecone, pgvector, Qdrant", color: "emerald" },
          { label: "Recherche Semantique", sub: "Similarite cosinus → top K", color: "amber" },
        ]},
        { type: "tip", content: "Dimensionalite des embeddings : plus de dimensions = plus de nuances mais plus de stockage et de latence. OpenAI text-embedding-3 permet de choisir la dimensionalite (256, 1024, 3072). 1024 est un bon equilibre." },
        { type: "summary", items: [
          "Les embeddings representent le sens du texte sous forme de vecteurs numeriques",
          "Les bases vectorielles permettent la recherche par similarite en millisecondes",
          "pgvector (PostgreSQL) suffit pour la plupart des projets",
          "La recherche hybride (semantique + lexicale) donne les meilleurs resultats RAG",
          "Evaluez les modeles d'embedding sur vos propres donnees, pas sur les benchmarks",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce qu'un embedding ?",
          options: ["Un type de base de donnees", "Une representation numerique du texte dans un espace vectoriel", "Un algorithme de tri", "Un format de fichier"],
          correctIndex: 1,
          explanation: "Un embedding est un vecteur numerique representant le sens d'un texte (ou image/audio) dans un espace multidimensionnel. Des textes similaires ont des embeddings proches.",
        },
        {
          question: "Quelle base vectorielle est recommandee pour commencer ?",
          options: ["Pinecone", "Weaviate", "pgvector (PostgreSQL)", "FAISS"],
          correctIndex: 2,
          explanation: "pgvector, l'extension PostgreSQL, est recommandee pour commencer car elle s'integre a une base existante sans infrastructure supplementaire. Scalez vers une base dediee si necessaire.",
        },
        {
          question: "Qu'est-ce que la recherche hybride ?",
          options: ["Chercher dans deux bases differentes", "Combiner recherche semantique (embeddings) et lexicale (BM25)", "Chercher en ligne et hors ligne", "Chercher du texte et des images"],
          correctIndex: 1,
          explanation: "La recherche hybride combine la recherche semantique (sens) et la recherche lexicale (mots-cles exacts) pour de meilleurs resultats, capturant a la fois le sens et la precision.",
        },
        {
          question: "Quelle dimensionalite d'embedding est un bon equilibre ?",
          options: ["32", "256", "1024", "10000"],
          correctIndex: 2,
          explanation: "1024 dimensions est un bon equilibre entre nuance (qualite de la representation semantique) et efficacite (stockage et latence de recherche).",
        },
      ],
    },
    {
      number: 10,
      title: "Generation d'Images Avancee",
      description: "Techniques avancees de generation d'images : ControlNet, inpainting, flux workflows.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Au-Dela du Prompt : Generation d'Images Avancee" },
        { type: "paragraph", content: "La generation d'images IA ne se limite pas a ecrire un prompt dans Midjourney. Les techniques avancees offrent un controle precis : ControlNet pour guider la composition, l'inpainting pour modifier des zones specifiques, img2img pour transformer des images existantes, et les flux workflows pour automatiser des pipelines complexes." },
        { type: "subheading", content: "ControlNet" },
        { type: "paragraph", content: "ControlNet ajoute des conditions supplementaires au processus de generation : pose humaine (OpenPose), contours (Canny), profondeur (Depth), segmentation. Vous pouvez fournir un croquis ou une pose et obtenir une image photoraliste qui respecte exactement votre composition." },
        { type: "subheading", content: "Inpainting et Outpainting" },
        { type: "paragraph", content: "L'inpainting modifie une zone specifique d'une image tout en preservant le reste. L'outpainting etend l'image au-dela de ses bordures. Ces techniques sont essentielles pour l'edition non destructive et la creation de contenus marketing." },
        { type: "callout", content: "Flux (de Black Forest Labs) est devenu le modele open source de reference en 2026, surpassant Stable Diffusion pour la qualite d'image et la fidelite au prompt. ComfyUI est l'interface standard pour les workflows avances." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Generation d'images avancee" },
        { type: "heading", content: "Workflows de Production" },
        { type: "paragraph", content: "Les workflows de production combinent plusieurs etapes : generation initiale, upscaling (Real-ESRGAN, Topaz), retouche (inpainting), variantes (img2img), et post-traitement. ComfyUI permet de designer ces workflows visuellement et de les automatiser via API." },
        { type: "key-point", content: "Pour les projets professionnels, le controle est plus important que la qualite brute. ControlNet + inpainting + workflows reproductibles permettent de produire des resultats consistants, pas juste de beaux hasards." },
        { type: "diagram", label: "Techniques de Generation Avancee", flow: "horizontal", nodes: [
          { label: "ControlNet", sub: "Pose, contours, profondeur", color: "purple" },
          { label: "Inpainting", sub: "Edition locale precise", color: "blue" },
          { label: "Img2Img", sub: "Transformation d'images", color: "emerald" },
          { label: "Upscaling", sub: "Real-ESRGAN, amelioration", color: "amber" },
        ]},
        { type: "summary", items: [
          "ControlNet guide la generation avec des conditions (pose, contours, profondeur)",
          "L'inpainting modifie des zones specifiques sans toucher au reste",
          "Flux est le modele open source de reference en 2026",
          "ComfyUI est l'interface standard pour les workflows avances",
          "Le controle reproductible est plus important que la qualite brute en production",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que ControlNet ?",
          options: ["Un antivirus", "Un systeme de controle qui guide la generation d'images avec des conditions", "Un reseau social", "Un format d'image"],
          correctIndex: 1,
          explanation: "ControlNet ajoute des conditions supplementaires (pose, contours, profondeur) au processus de generation d'images, offrant un controle precis sur la composition.",
        },
        {
          question: "Qu'est-ce que l'inpainting ?",
          options: ["Peindre une image entiere", "Modifier une zone specifique d'une image tout en preservant le reste", "Compresser une image", "Convertir une image en texte"],
          correctIndex: 1,
          explanation: "L'inpainting modifie une zone specifique d'une image (selectionnee par un masque) tout en preservant le reste, permettant l'edition non destructive.",
        },
        {
          question: "Quel modele open source de generation d'images domine en 2026 ?",
          options: ["Stable Diffusion", "DALL-E", "Flux (Black Forest Labs)", "Midjourney"],
          correctIndex: 2,
          explanation: "Flux de Black Forest Labs a surpasse Stable Diffusion en 2026 pour la qualite d'image et la fidelite au prompt, devenant le modele open source de reference.",
        },
        {
          question: "Quel outil est le standard pour les workflows de generation d'images ?",
          options: ["Photoshop", "ComfyUI", "Canva", "Figma"],
          correctIndex: 1,
          explanation: "ComfyUI est l'interface standard pour designer des workflows de generation d'images avances, combinant ControlNet, inpainting, upscaling et autres etapes.",
        },
      ],
    },
    {
      number: 11,
      title: "Multimodal : Texte, Image, Audio, Video",
      description: "Construire des applications qui combinent texte, images, audio et video avec l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "L'Ere du Multimodal" },
        { type: "paragraph", content: "Les modeles multimodaux traitent et generent plusieurs types de donnees dans un seul modele : texte, images, audio et video. En 2026, le multimodal est la norme — GPT-5.4, Claude 4.6 et Gemini 3.1 sont tous nativement multimodaux." },
        { type: "paragraph", content: "Les applications multimodales vont au-dela du simple 'decrire une image'. Elles combinent vision + langage pour l'analyse de documents, audio + texte pour les assistants vocaux, video + texte pour le sous-titrage et l'indexation, et image + texte pour le e-commerce et la recherche visuelle." },
        { type: "subheading", content: "Vision + Langage" },
        { type: "paragraph", content: "L'OCR IA extrait du texte structure de n'importe quel document (factures, contrats, formulaires). L'analyse d'images repond a des questions complexes sur le contenu visuel. Le visual grounding identifie et localise des objets mentionnes en langage naturel." },
        { type: "subheading", content: "Audio + Texte" },
        { type: "paragraph", content: "La transcription (Whisper, Deepgram) convertit la parole en texte avec une precision de 95%+. La synthese vocale (ElevenLabs, Play.ht) genere des voix naturelles. La combinaison des deux cree des assistants vocaux complets." },
        { type: "callout", content: "Gemini 3.1 accepte nativement des videos completes comme input — pas besoin d'extraire des frames. Vous pouvez poser des questions sur une video d'une heure et obtenir des reponses contextuelles precises." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Applications multimodales" },
        { type: "key-point", content: "Le multimodal simplifie les architectures. Au lieu de pipelines complexes (OCR → NLP → classification), un seul appel multimodal traite le document entier. Moins de code, moins de bugs, meilleure precision." },
        { type: "diagram", label: "Applications Multimodales", flow: "horizontal", nodes: [
          { label: "Vision + Langage", sub: "OCR, analyse docs, e-commerce", color: "purple" },
          { label: "Audio + Texte", sub: "Transcription, assistants vocaux", color: "blue" },
          { label: "Video + Texte", sub: "Sous-titrage, indexation, Q&A", color: "emerald" },
          { label: "Tout-en-un", sub: "Un seul modele, une seule API", color: "amber" },
        ]},
        { type: "summary", items: [
          "Les modeles multimodaux traitent texte, images, audio et video nativement",
          "L'OCR IA extrait du texte structure de n'importe quel document",
          "Gemini 3.1 accepte des videos completes comme input",
          "Le multimodal simplifie les architectures (1 appel au lieu de pipelines)",
          "Les cas d'usage : analyse de documents, assistants vocaux, e-commerce visuel",
        ]},
      ],
      quiz: [
        {
          question: "Que signifie 'multimodal' pour un modele IA ?",
          options: ["Il est tres puissant", "Il traite plusieurs types de donnees (texte, image, audio, video)", "Il fonctionne sur plusieurs appareils", "Il parle plusieurs langues"],
          correctIndex: 1,
          explanation: "Un modele multimodal peut traiter et generer plusieurs types de donnees — texte, images, audio et video — dans un seul modele unifie.",
        },
        {
          question: "Quel avantage architectural offre le multimodal ?",
          options: ["Plus de complexite", "Simplification : un seul appel remplace des pipelines complexes", "Plus de serveurs necessaires", "Des couts plus eleves"],
          correctIndex: 1,
          explanation: "Le multimodal simplifie les architectures : un seul appel API multimodal remplace des pipelines complexes (OCR + NLP + classification), avec moins de code et meilleure precision.",
        },
        {
          question: "Quel modele accepte nativement des videos completes comme input ?",
          options: ["GPT-5.4", "Claude 4.6", "Gemini 3.1", "Mistral"],
          correctIndex: 2,
          explanation: "Gemini 3.1 accepte nativement des videos completes comme input, permettant de poser des questions sur une video d'une heure sans extraire de frames.",
        },
        {
          question: "Quelle precision les meilleurs systemes de transcription IA atteignent-ils ?",
          options: ["70%", "85%", "95%+", "100%"],
          correctIndex: 2,
          explanation: "Les systemes de transcription modernes (Whisper, Deepgram) atteignent une precision de 95%+ sur la parole claire, rivalisant avec les transcripteurs humains.",
        },
      ],
    },
    {
      number: 12,
      title: "Evaluation et Benchmarking",
      description: "Mesurer la qualite de vos systemes IA : metriques, benchmarks et evaluation humaine.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Evaluer la Qualite de Vos Systemes IA" },
        { type: "paragraph", content: "L'evaluation est le parent pauvre de l'IA generative. Beaucoup construisent des systemes sans mesurer leur qualite. Pourtant, sans evaluation rigoureuse, vous ne savez pas si votre systeme s'ameliore ou se degrade. L'evaluation doit etre systematique, reproductible et automatisee." },
        { type: "subheading", content: "Metriques pour le RAG" },
        { type: "paragraph", content: "Les metriques cles du RAG : Faithfulness (la reponse est-elle fidele aux documents recuperes ?), Relevance (les documents recuperes sont-ils pertinents ?), Answer completeness (la reponse couvre-t-elle toute la question ?). Des frameworks comme RAGAS automatisent ces evaluations." },
        { type: "subheading", content: "Evaluation LLM-as-Judge" },
        { type: "paragraph", content: "Utiliser un LLM pour evaluer les sorties d'un autre LLM est devenu standard. Claude Opus ou GPT-5.4 Pro evaluent les reponses selon des criteres definis (pertinence, precision, completude, ton). C'est plus rapide et moins cher que l'evaluation humaine pour les iterations rapides." },
        { type: "callout", content: "Les benchmarks publics (MMLU, HumanEval, ARC-AGI) comparent les modeles entre eux, mais ne mesurent pas la performance sur votre cas d'usage specifique. Creez toujours un benchmark interne avec vos propres donnees." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Evaluer vos systemes IA" },
        { type: "key-point", content: "La regle d'or de l'evaluation : mesurez ce qui compte pour vos utilisateurs, pas ce qui est facile a mesurer. Le taux de satisfaction utilisateur est plus important que le score BLEU." },
        { type: "diagram", label: "Types d'Evaluation IA", flow: "horizontal", nodes: [
          { label: "Metriques automatiques", sub: "RAGAS, BLEU, ROUGE, perplexite", color: "blue" },
          { label: "LLM-as-Judge", sub: "Claude/GPT evalue les sorties", color: "purple" },
          { label: "Evaluation humaine", sub: "Annotateurs, A/B testing", color: "emerald" },
        ]},
        { type: "tip", content: "Creez un 'golden dataset' de 100+ exemples avec les reponses attendues. Executez-le a chaque changement de prompt, modele ou pipeline. C'est votre suite de tests pour l'IA." },
        { type: "summary", items: [
          "L'evaluation doit etre systematique, reproductible et automatisee",
          "Metriques RAG : faithfulness, relevance, completeness",
          "LLM-as-Judge est standard pour les iterations rapides",
          "Les benchmarks publics ne remplacent pas l'evaluation sur vos donnees",
          "Creez un golden dataset de 100+ exemples comme suite de tests",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que LLM-as-Judge ?",
          options: ["Un benchmark public", "Utiliser un LLM pour evaluer les sorties d'un autre LLM", "Un juge humain", "Un framework de test"],
          correctIndex: 1,
          explanation: "LLM-as-Judge utilise un LLM puissant (Claude Opus, GPT-5.4 Pro) pour evaluer automatiquement les reponses d'un autre LLM selon des criteres definis.",
        },
        {
          question: "Quelle metrique RAG mesure si la reponse est fidele aux documents ?",
          options: ["Relevance", "Faithfulness", "Completeness", "Perplexite"],
          correctIndex: 1,
          explanation: "La Faithfulness mesure si la reponse generee est fidele aux documents recuperes — c'est-a-dire si elle ne contient pas d'informations inventees par le modele.",
        },
        {
          question: "Combien d'exemples un golden dataset doit-il contenir au minimum ?",
          options: ["10", "50", "100+", "1000+"],
          correctIndex: 2,
          explanation: "Un golden dataset de 100+ exemples avec les reponses attendues est recommande comme suite de tests pour evaluer votre systeme IA a chaque changement.",
        },
        {
          question: "Que faut-il mesurer en priorite ?",
          options: ["Le score BLEU", "Le nombre de tokens", "Ce qui compte pour vos utilisateurs", "La vitesse de generation"],
          correctIndex: 2,
          explanation: "La priorite est de mesurer ce qui compte pour vos utilisateurs (satisfaction, pertinence, precision) plutot que des metriques techniques faciles a calculer.",
        },
      ],
    },
    {
      number: 13,
      title: "Mise en Production",
      description: "Deployer un systeme IA en production : infrastructure, monitoring et scalabilite.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "De la Demo a la Production" },
        { type: "paragraph", content: "Faire fonctionner un prototype IA est facile. Le deployer en production de maniere fiable, performante et economique est un tout autre defi. La mise en production couvre l'infrastructure, le monitoring, la scalabilite, la securite, la gestion des erreurs et la conformite." },
        { type: "paragraph", content: "80% des projets IA restent au stade de prototype. Les raisons : couts mal anticipes, latence trop elevee, hallucinations non gerees, absence de monitoring, et non-conformite reglementaire. Ce chapitre couvre tout ce qu'il faut pour franchir le cap." },
        { type: "subheading", content: "Architecture de Production" },
        { type: "paragraph", content: "Une architecture IA de production inclut : un gateway API (rate limiting, auth), un routeur de modeles (selection du meilleur modele), un cache (reponses frequentes), un systeme de fallback (provider alternatif si le primaire tombe), et un pipeline d'observabilite (logs, traces, metriques)." },
        { type: "subheading", content: "Monitoring et Observabilite" },
        { type: "paragraph", content: "Les metriques cles a surveiller : latence (P50, P95, P99), taux d'erreur, tokens consommes, cout par requete, taux d'hallucination, satisfaction utilisateur. Des outils comme Langfuse, LangSmith et Helicone fournissent l'observabilite complete." },
        { type: "callout", content: "Le streaming est incontournable en production. Il reduit la latence percue de 10x : l'utilisateur voit la reponse se construire en temps reel au lieu d'attendre 5 secondes. Tous les providers supportent le streaming." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Mise en production IA" },
        { type: "heading", content: "Gestion des Erreurs et Guardrails" },
        { type: "paragraph", content: "Les guardrails en production incluent : la validation des sorties (format JSON, longueur, contenu), la detection d'hallucinations, le filtrage de contenu toxique, le circuit breaker (arreter les appels si le taux d'erreur explose), et les alertes automatiques." },
        { type: "key-point", content: "Le cache semantique peut reduire vos couts de 40-60%. Si la question de l'utilisateur est semantiquement similaire a une question deja posee, retournez la reponse en cache. GPTCache et Redis avec embeddings implementent cette strategie." },
        { type: "diagram", label: "Architecture de Production IA", flow: "vertical", nodes: [
          { label: "API Gateway", sub: "Rate limiting, auth, routing", color: "blue" },
          { label: "Routeur de Modeles", sub: "Selection du modele optimal", color: "purple" },
          { label: "Cache Semantique", sub: "Reponses frequentes, -60% couts", color: "emerald" },
          { label: "Observabilite", sub: "Langfuse, metriques, alertes", color: "amber" },
        ]},
        { type: "summary", items: [
          "80% des projets IA restent au stade de prototype — la production est le vrai defi",
          "L'architecture inclut gateway, routeur, cache, fallback et observabilite",
          "Le streaming reduit la latence percue de 10x",
          "Le cache semantique reduit les couts de 40-60%",
          "Les guardrails (validation, detection, circuit breaker) sont essentiels en production",
        ]},
      ],
      quiz: [
        {
          question: "Quel pourcentage des projets IA reste au stade de prototype ?",
          options: ["20%", "40%", "60%", "80%"],
          correctIndex: 3,
          explanation: "80% des projets IA restent au stade de prototype, faute de gestion des couts, de monitoring, de guardrails et de conformite reglementaire.",
        },
        {
          question: "De combien le cache semantique peut-il reduire les couts ?",
          options: ["10-20%", "20-30%", "40-60%", "90%"],
          correctIndex: 2,
          explanation: "Le cache semantique retourne les reponses en cache pour les questions similaires, reduisant les couts d'API de 40 a 60%.",
        },
        {
          question: "Pourquoi le streaming est-il incontournable en production ?",
          options: ["Il reduit les couts", "Il reduit la latence percue de 10x", "Il ameliore la qualite", "Il securise les donnees"],
          correctIndex: 1,
          explanation: "Le streaming permet a l'utilisateur de voir la reponse se construire en temps reel, reduisant la latence percue de 10x au lieu d'attendre la reponse complete.",
        },
        {
          question: "Qu'est-ce qu'un circuit breaker dans le contexte IA ?",
          options: ["Un composant electrique", "Un systeme qui arrete les appels si le taux d'erreur explose", "Un outil de debug", "Un type de cache"],
          correctIndex: 1,
          explanation: "Le circuit breaker arrete automatiquement les appels au provider IA si le taux d'erreur depasse un seuil, empechant une cascade de defaillances et des couts incontroles.",
        },
      ],
    },
    {
      number: 14,
      title: "Couts et Optimisation",
      description: "Reduire les couts de vos applications IA sans compromettre la qualite.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Maitriser les Couts de l'IA" },
        { type: "paragraph", content: "Les couts des APIs IA peuvent exploser rapidement : un chatbot avec 100 000 utilisateurs actifs peut couter des dizaines de milliers de dollars par mois. L'optimisation des couts est une competence essentielle pour rendre un produit IA viable economiquement." },
        { type: "paragraph", content: "La bonne nouvelle : les couts ont chute de 90% en deux ans, et les techniques d'optimisation permettent de reduire encore de 70-80% sans perte de qualite. Le secret est de combiner plusieurs strategies." },
        { type: "subheading", content: "Strategie 1 : Routing Intelligent" },
        { type: "paragraph", content: "Dirigez les requetes simples (classification, extraction, reformulation) vers des modeles economiques (Haiku, GPT-4o-mini, Gemini Flash) et reservez les modeles premium (Opus, GPT-5.4) pour les taches complexes. Un classificateur de complexite en premiere etape route automatiquement." },
        { type: "subheading", content: "Strategie 2 : Prompt Caching et Batching" },
        { type: "paragraph", content: "Le prompt caching Anthropic reduit le cout des parties statiques de 90%. Le batching OpenAI et Anthropic offre 50% de reduction pour les traitements non urgents. Combinez les deux pour des reductions massives sur les pipelines de traitement." },
        { type: "callout", content: "Exemple reel : une startup traitant 50 000 documents/jour est passee de $8 000/mois a $1 200/mois en combinant routing intelligent + prompt caching + batching — sans perte de qualite." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Optimiser les couts IA" },
        { type: "subheading", content: "Strategie 3 : Modeles Open Source" },
        { type: "paragraph", content: "Pour les taches specifiques, un modele open source fine-tune (Llama 3.3, Qwen 3.5, Mistral) peut rivaliser avec les modeles proprietaires a une fraction du cout. L'hebergement sur GPU cloud (RunPod, Together AI) revient a $0.10-0.30/heure pour un modele 7B." },
        { type: "key-point", content: "Le monitoring des couts en temps reel est non negociable. Configurez des alertes de budget quotidien/mensuel. Un bug de boucle infinie sur l'API peut couter des milliers de dollars en minutes." },
        { type: "diagram", label: "Strategies d'Optimisation des Couts", flow: "vertical", nodes: [
          { label: "Routing intelligent", sub: "Modele adapte a la complexite, -70%", color: "blue" },
          { label: "Prompt caching", sub: "Parties statiques cachees, -90%", color: "purple" },
          { label: "Batching", sub: "Traitements groupes, -50%", color: "emerald" },
          { label: "Modeles open source", sub: "Fine-tuning local, cout minimal", color: "amber" },
        ]},
        { type: "summary", items: [
          "Les couts IA ont chute de 90% en 2 ans et sont optimisables de 70-80%",
          "Le routing intelligent dirige les taches vers le modele le moins couteux suffisant",
          "Le prompt caching Anthropic reduit les parties statiques de 90%",
          "Le batching offre 50% de reduction pour les traitements non urgents",
          "Configurez des alertes de budget — les boucles infinies coutent cher",
        ]},
      ],
      quiz: [
        {
          question: "De combien le prompt caching Anthropic reduit-il les couts ?",
          options: ["30%", "50%", "70%", "90%"],
          correctIndex: 3,
          explanation: "Le prompt caching Anthropic reduit de 90% le cout des parties statiques du prompt (system prompt, exemples), un avantage considerable pour les applications avec des prompts longs.",
        },
        {
          question: "Quelle est la premiere strategie d'optimisation des couts ?",
          options: ["Utiliser moins l'IA", "Le routing intelligent vers le modele adapte", "Compresser les prompts", "Limiter les utilisateurs"],
          correctIndex: 1,
          explanation: "Le routing intelligent dirige chaque requete vers le modele le moins couteux capable de la traiter, evitant de sur-utiliser les modeles premium pour des taches simples.",
        },
        {
          question: "Combien coute l'hebergement d'un modele open source 7B sur GPU cloud ?",
          options: ["$10-30/heure", "$1-5/heure", "$0.10-0.30/heure", "Gratuit"],
          correctIndex: 2,
          explanation: "L'hebergement d'un modele 7B sur GPU cloud (RunPod, Together AI) revient a environ $0.10-0.30/heure, rendant les modeles open source tres economiques.",
        },
        {
          question: "Pourquoi les alertes de budget sont-elles essentielles ?",
          options: ["Pour impressionner le management", "Un bug de boucle infinie peut couter des milliers de dollars en minutes", "Pour surveiller les concurrents", "Pour le reporting trimestriel"],
          correctIndex: 1,
          explanation: "Un bug de boucle infinie sur l'API IA peut generer des milliers de requetes en quelques minutes, coutant potentiellement des milliers de dollars. Les alertes permettent de detecter et stopper rapidement.",
        },
      ],
    },
    {
      number: 15,
      title: "Construire un Produit IA",
      description: "De l'idee au lancement : construire un produit IA complet et viable.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "De l'Idee au Produit IA" },
        { type: "paragraph", content: "Construire un produit IA viable est different de construire un prototype. Il faut penser experience utilisateur, valeur metier, modele economique, fiabilite, et scalabilite des le depart. Ce chapitre synthetise tout le cours en un framework actionnable pour lancer votre produit IA." },
        { type: "subheading", content: "Identifier le Bon Probleme" },
        { type: "paragraph", content: "Le piege #1 est de construire une solution IA en cherchant un probleme. Partez du probleme : quel processus est lent, couteux, ou penible ? L'IA est un accelerateur, pas une fin en soi. Les meilleurs produits IA resolvent un probleme reel de maniere 10x meilleure que les alternatives." },
        { type: "subheading", content: "MVP IA en 2 Semaines" },
        { type: "paragraph", content: "Semaine 1 : definir le cas d'usage, choisir l'API provider, construire le pipeline (prompt + RAG si besoin), creer l'interface minimal. Semaine 2 : ajouter les guardrails, tester avec des utilisateurs beta, mesurer la qualite, iterer. Lancez en 2 semaines, pas en 6 mois." },
        { type: "callout", content: "Les produits IA les plus reussis en 2026 ne sont pas ceux avec la meilleure technologie, mais ceux avec la meilleure experience utilisateur. L'UX prime sur le modele. Un GPT-4o-mini avec une excellente UX bat un Opus avec une mauvaise UX." },
        { type: "video", videoId: "dQw4w9WgXcQ", label: "Construire un produit IA" },
        { type: "heading", content: "Stack Recommandee en 2026" },
        { type: "paragraph", content: "Frontend : Next.js + Vercel AI SDK pour le streaming. Backend : API routes + base vectorielle (pgvector). LLM : Claude Sonnet (equilibre qualite/cout) avec fallback GPT-4o. RAG : LlamaIndex pour l'indexation. Monitoring : Langfuse. Deploiement : Vercel ou Railway." },
        { type: "key-point", content: "Le moat (avantage concurrentiel) d'un produit IA n'est pas le modele — tout le monde utilise les memes APIs. Le moat est dans les donnees proprietaires, l'UX, le workflow specifique, et la base utilisateurs. Construisez autour de ces piliers." },
        { type: "diagram", label: "Framework de Lancement Produit IA", flow: "vertical", nodes: [
          { label: "Probleme", sub: "Identifier un probleme reel 10x", color: "pink" },
          { label: "MVP 2 semaines", sub: "API + RAG + UI minimale", color: "blue" },
          { label: "Validation", sub: "Beta users, metriques, iteration", color: "purple" },
          { label: "Scaling", sub: "Optimisation couts, monitoring, UX", color: "emerald" },
        ]},
        { type: "prompt-example", prompt: "Tu es un consultant produit IA. J'ai une base de 10 000 PDF de contrats juridiques. Propose 3 produits IA viables avec estimation de marche, stack technique, et plan de lancement en 4 semaines.", result: "1) Analyseur de clauses a risque (cible: directions juridiques, RAG + Claude). 2) Extracteur de donnees contractuelles (cible: legal ops, OCR multimodal + structured output). 3) Assistant de redaction contractuelle (cible: avocats, fine-tuning + RAG)." },
        { type: "summary", items: [
          "Partez du probleme, pas de la technologie — l'IA est un accelerateur",
          "Lancez un MVP en 2 semaines, pas en 6 mois",
          "L'UX prime sur le modele — une bonne experience bat un meilleur modele",
          "Le moat est dans les donnees, l'UX et le workflow, pas dans le modele",
          "Stack 2026 : Next.js + Vercel AI SDK + Claude + pgvector + Langfuse",
        ]},
      ],
      quiz: [
        {
          question: "Quel est le piege #1 en construction de produit IA ?",
          options: ["Choisir le mauvais modele", "Construire une solution IA en cherchant un probleme", "Ne pas utiliser assez de donnees", "Lancer trop vite"],
          correctIndex: 1,
          explanation: "Le piege #1 est de partir de la technologie IA et chercher un probleme a resoudre, au lieu de partir d'un probleme reel et d'utiliser l'IA comme accelerateur.",
        },
        {
          question: "En combien de temps doit-on lancer un MVP IA ?",
          options: ["2 jours", "2 semaines", "2 mois", "6 mois"],
          correctIndex: 1,
          explanation: "Un MVP IA doit etre lance en 2 semaines : semaine 1 pour le pipeline technique, semaine 2 pour les guardrails, tests beta et iterations.",
        },
        {
          question: "Quel est le vrai avantage concurrentiel (moat) d'un produit IA ?",
          options: ["Le modele IA utilise", "La puissance de calcul", "Les donnees proprietaires, l'UX et le workflow", "Le nombre de parametres"],
          correctIndex: 2,
          explanation: "Le moat n'est pas dans le modele (tout le monde utilise les memes APIs) mais dans les donnees proprietaires, l'experience utilisateur, le workflow specifique et la base utilisateurs.",
        },
        {
          question: "Qu'est-ce qui prime dans un produit IA reussi ?",
          options: ["La taille du modele", "L'experience utilisateur", "Le nombre de features", "Le prix le plus bas"],
          correctIndex: 1,
          explanation: "Les produits IA les plus reussis en 2026 sont ceux avec la meilleure experience utilisateur. Un modele plus petit avec une excellente UX bat un modele plus gros avec une mauvaise UX.",
        },
      ],
    },
  ],
};

export default content;
