import type { CourseContent } from "../types";

const content: CourseContent = {
  slug: "ia-generative-avancee",
  chapters: [
    {
      number: 1,
      title: "Introduction à l'IA Générative Avancée",
      description: "Vue d'ensemble des techniques avancées de l'IA générative en 2026.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Au-Dela des Bases : l'IA Générative Avancée" },
        { type: "paragraph", content: "Vous connaissez ChatGPT et Midjourney. Vous avez écrit des prompts et génère des images. Mais l'IA générative avancée va bien au-dela de l'utilisation basique. Ce cours vous emmene dans les coulisses : fine-tuning, RAG, agents, APIs, embeddings, multimodal, et mise en production." },
        { type: "paragraph", content: "En 2026, les professionnels qui maitrisent ces techniques avancées sont ceux qui construisent des produits IA — pas seulement ceux qui les utilisent. La différence entre un utilisateur et un créateur d'IA reside dans la compréhension des architectures sous-jacentes et la capacité a les assembler." },
        { type: "callout", content: "Ce cours est conçu pour les développeurs, data scientists, et tech leads qui veulent passer du niveau 'utilisateur' au niveau 'constructeur' d'applications IA. Des bases en programmation (Python/JavaScript) sont recommandées." },
        { type: "video", videoId: "zjkBMFhNj_g",
      videoDurationMinutes: 60, label: "Introduction à l'IA Générative Avancée" },
        { type: "heading", content: "L'Écosystème en 2026" },
        { type: "paragraph", content: "L'écosystème IA générative a énormément mature. Les APIs sont standardisees, les frameworks d'orchestration (LangChain, LlamaIndex, Vercel AI SDK) simplifient le développement, les bases vectorielles sont performantes, et les coûts ont chute de 90% en deux ans." },
        { type: "subheading", content: "Ce Que Vous Allez Apprendre" },
        { type: "paragraph", content: "Architectures Transformer en profondeur, fine-tuning de modèles, RAG pour ancrer vos réponses dans vos données, agents IA autonomes, prompt engineering système, APIs des grands providers, frameworks d'orchestration, embeddings et bases vectorielles, génération d'images avancée, multimodal, évaluation, mise en production, optimisation des coûts, et construction d'un produit IA complet." },
        { type: "key-point", content: "L'objectif n'est pas de tout mémoriser mais de comprendre les patterns architecturaux. Chaque chapitre est un bloc que vous assemblerez pour construire vos propres applications IA." },
        { type: "diagram", label: "Parcours du Cours", flow: "vertical", nodes: [
          { label: "Fondations", sub: "Transformers, fine-tuning, RAG", color: "blue" },
          { label: "Orchestration", sub: "Agents, APIs, frameworks", color: "purple" },
          { label: "Avance", sub: "Multimodal, embeddings, évaluation", color: "emerald" },
          { label: "Production", sub: "Déploiement, coûts, produit IA", color: "amber" },
        ]},
        { type: "summary", items: [
          "Ce cours couvre les techniques avancées pour construire des applications IA",
          "L'écosystème IA générative a énormément mature avec des APIs et frameworks standardises",
          "Les coûts des APIs IA ont chute de 90% en deux ans",
          "Objectif : passer du niveau utilisateur au niveau constructeur d'IA",
          "Chaque chapitre est un bloc architectural assemblable",
        ]},
      ],
      quiz: [
        {
          question: "Quelle est la différence entre un utilisateur et un constructeur d'IA ?",
          options: ["Le constructeur a un meilleur abonnement", "Le constructeur comprend les architectures et assemble les composants", "Le constructeur programmé en C++", "Il n'y a pas de différence"],
          correctIndex: 1,
          explanation: "Le constructeur d'IA comprend les architectures sous-jacentes (Transformers, RAG, agents) et sait les assembler pour créer des applications IA, pas seulement utiliser des outils existants.",
        },
        {
          question: "De combien les coûts des APIs IA ont-ils chute en deux ans ?",
          options: ["30%", "50%", "70%", "90%"],
          correctIndex: 3,
          explanation: "Les coûts des APIs IA ont chute de 90% en deux ans grâce à la concurrence entre providers, l'optimisation des modèles, et les économies d'échelle.",
        },
        {
          question: "Quel prerequis est recommandé pour ce cours ?",
          options: ["Un doctorat en IA", "Des bases en programmation (Python/JavaScript)", "10 ans d'expérience en ML", "Aucun"],
          correctIndex: 1,
          explanation: "Des bases en programmation Python ou JavaScript sont recommandées pour suivre les exemples de code et construire des applications IA.",
        },
        {
          question: "Que signifie RAG dans le contexte de l'IA ?",
          options: ["Rapid AI Génération", "Retrieval-Augmented Génération", "Random Algorithm Generator", "Real-time AI Gateway"],
          correctIndex: 1,
          explanation: "RAG (Retrieval-Augmented Génération) est une technique qui ancre les réponses d'un LLM dans des données externes spécifiques, reduisant les hallucinations et personnalisant les réponses.",
        },
      ],
    },
    {
      number: 2,
      title: "Architectures Transformer en Profondeur",
      description: "Comprendre en détail le mecanisme d'attention, les couches et les variantes des Transformers.",
      estimatedMinutes: 10,
      sections: [
        { type: "heading", content: "Le Transformer Decortique" },
        { type: "paragraph", content: "L'architecture Transformer, introduite dans 'Attention Is All You Need' (2017), est la fondation de tous les LLM modernes. Comprendre son fonctionnement est essentiel pour le fine-tuning, l'optimisation et le debugging des applications IA." },
        { type: "subheading", content: "Le Mecanisme d'Attention" },
        { type: "paragraph", content: "Le self-attention permet à chaque token de 'regarder' tous les autres tokens de la séquence pour comprendre le contexte. Pour chaque token, le modèle calcule trois vecteurs : Query (ce que je cherche), Key (ce que je représente), et Value (l'information que je porte). Le score d'attention est le produit scalaire Query * Key, normalisé et pondere." },
        { type: "paragraph", content: "Le Multi-Head Attention exécute plusieurs mecanismes d'attention en parallèle, chaque 'tête' apprenant a se focaliser sur différents aspects : l'une sur la syntaxe, une autre sur la sémantique, une autre sur les relations longue distance." },
        { type: "callout", content: "L'attention est la raison pour laquelle les Transformers surpassent les RNN : ils traitent toute la séquence en parallèle au lieu de la parcourir sequentiellement. C'est aussi pourquoi l'entraînement est plus rapide sur GPU." },
        { type: "video", videoId: { fr: "UoBVumRnyds", en: "kCc8FmEb1nY" },
      videoDurationMinutes: 116, label: "Le mecanisme d'attention expliqué visuellement" },
        { type: "heading", content: "Architecture Encoder-Decoder vs Decoder-Only" },
        { type: "paragraph", content: "Le Transformer original est un encoder-décoder (utilise pour la traduction). BERT est un encoder-only (comprend le texte). GPT, Claude et Gemini sont des décoder-only (generent du texte). Les décoder-only dominent en 2026 car ils sont plus simples a scaler et plus polyvalents." },
        { type: "subheading", content: "Positional Encoding et Contexte Long" },
        { type: "paragraph", content: "Les Transformers n'ont pas de notion intrinseque de position. Le positional encoding injecte l'information de position. RoPE (Rotary Position Embedding) est utilisé par la plupart des LLM modernes et permet l'extension du contexte a 1 million+ de tokens via des techniques comme YaRN et ALiBi." },
        { type: "key-point", content: "La complexité du self-attention est O(n²) par rapport à la longueur de la séquence. C'est le principal goulot d'etranglement pour les contextes longs. Les techniques comme Flash Attention et Ring Attention reduisent ce coût en pratique." },
        { type: "diagram", label: "Architecture d'un Bloc Transformer", flow: "vertical", nodes: [
          { label: "Input Embeddings + Positional Encoding", sub: "Tokens → vecteurs + positions", color: "blue" },
          { label: "Multi-Head Self-Attention", sub: "Query, Key, Value × N têtes", color: "purple" },
          { label: "Feed-Forward Network", sub: "Transformation non-lineaire", color: "emerald" },
          { label: "Layer Normalization + Residual", sub: "Stabilisation de l'entraînement", color: "amber" },
        ]},
        { type: "tip", content: "Pour visualiser le mecanisme d'attention en action, utilisez BertViz ou l'outil d'attention de 3Blue1Brown. Voir les patterns d'attention aide énormément à comprendre ce que le modèle 'regarde'." },
        { type: "summary", items: [
          "Le self-attention permet à chaque token de considérer tous les autres tokens",
          "Multi-Head Attention : plusieurs têtes focalisees sur différents aspects",
          "Decoder-only (GPT, Claude) domine en 2026 par sa polyvalence",
          "RoPE et YaRN permettent d'étendre le contexte a 1 million+ de tokens",
          "La complexité O(n²) est le principal goulot, attenude par Flash Attention",
        ]},
      ],
      quiz: [
        {
          question: "Quels sont les trois vecteurs calcules dans le self-attention ?",
          options: ["Input, Output, Hidden", "Query, Key, Value", "Encoder, Decoder, Attention", "Weight, Bias, Activation"],
          correctIndex: 1,
          explanation: "Pour chaque token, le mecanisme de self-attention calcule trois vecteurs : Query (ce que je cherche), Key (ce que je représente), et Value (l'information que je porte).",
        },
        {
          question: "Quelle est la complexité du self-attention par rapport à la longueur de séquence ?",
          options: ["O(n)", "O(n log n)", "O(n²)", "O(n³)"],
          correctIndex: 2,
          explanation: "La complexité du self-attention est O(n²) par rapport à la longueur de la séquence, car chaque token doit 'regarder' tous les autres tokens.",
        },
        {
          question: "Quel type d'architecture utilisent GPT et Claude ?",
          options: ["Encoder-only", "Encoder-décoder", "Decoder-only", "Attention-only"],
          correctIndex: 2,
          explanation: "GPT, Claude et Gemini utilisent une architecture décoder-only, optimisée pour la génération de texte. Elle domine en 2026 par sa simplicité et sa polyvalence.",
        },
        {
          question: "Quelle technique réduit le coût de l'attention sur les séquences longues ?",
          options: ["Dropout", "Flash Attention", "Batch normalization", "L2 regularization"],
          correctIndex: 1,
          explanation: "Flash Attention est une technique d'optimisation qui réduit le coût mémoire et calcul du self-attention en reorganisant les opérations pour mieux utiliser la hiérarchie mémoire du GPU.",
        },
      ],
    },
    {
      number: 3,
      title: "Fine-tuning de Modèles de Langage",
      description: "Adapter un modèle pre-entraîné à vos données et votre cas d'usage spécifique.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Le Fine-tuning : Personnaliser un LLM" },
        { type: "paragraph", content: "Le fine-tuning consiste à re-entraîner partiellement un modèle pre-entraîné sur vos propres données pour l'adapter à votre cas d'usage. Un modèle générique devient un expert de votre domaine : juridique, médical, financier, ou technique." },
        { type: "paragraph", content: "En 2026, le fine-tuning est devenu accessible grâce aux techniques de parameter-efficient fine-tuning (PEFT) qui ne modifient qu'une fraction des paramètres. LoRA, QLoRA et adapters permettent de fine-tuner des modèles de 70B paramètres sur un seul GPU." },
        { type: "subheading", content: "Quand Fine-Tuner vs Quand Utiliser RAG ?" },
        { type: "paragraph", content: "Fine-tuning quand : vous voulez changer le style/ton du modèle, vous avez des patterns de raisonnement spécifiques, ou le prompt engineering ne suffit pas. RAG quand : vous voulez ancrer les réponses dans des données actualisées, les données changent fréquemment, ou vous avez besoin de citations exactes." },
        { type: "callout", content: "Règle d'or : essayez d'abord le prompt engineering, puis RAG, puis le fine-tuning. Chaque étape est plus couteuse et complexe. Le fine-tuning est la dernière option, pas la première." },
        { type: "video", videoId: "bZQun8Y4L2A",
      videoDurationMinutes: 43, label: "Fine-tuning de LLM en pratique" },
        { type: "heading", content: "Techniques de Fine-tuning" },
        { type: "subheading", content: "LoRA (Low-Rank Adaptation)" },
        { type: "paragraph", content: "LoRA gele les poids du modèle original et ajouté de petites matrices de rang faible à chaque couche. Seules ces matrices sont entraînées (0,1% des paramètres totaux). Le résultat : un fine-tuning rapide, peu couteux, et reversible — vous pouvez empiler plusieurs LoRA pour différents cas d'usage." },
        { type: "subheading", content: "QLoRA" },
        { type: "paragraph", content: "QLoRA combiné LoRA avec la quantification 4-bit. Le modèle de base est compresse en 4-bit pour tenir en mémoire, et les adapters LoRA sont entraînés en précision normale. Résultat : fine-tuner un modèle 70B sur un GPU de 24GB." },
        { type: "key-point", content: "La qualité du fine-tuning dépend a 80% de la qualité de vos données. Investissez dans la curation de votre dataset : exemples propres, divers, representatifs, et alignes avec votre objectif." },
        { type: "diagram", label: "Décision : Prompt vs RAG vs Fine-tuning", flow: "vertical", nodes: [
          { label: "Prompt Engineering", sub: "Premier essai, gratuit, rapide", color: "emerald" },
          { label: "RAG", sub: "Données dynamiques, citations, précision", color: "blue" },
          { label: "Fine-tuning", sub: "Style, ton, patterns spécifiques", color: "purple" },
        ]},
        { type: "prompt-example", prompt: "Tu es un expert en fine-tuning. J'ai 5000 conversations de support client. Comment préparer mes données pour fine-tuner un modèle qui répond aux tickets automatiquement ?", result: "Structurez chaque exemple en format instruction/réponse. Filtrez les conversations de qualité, anonymisez les données, et divisez en train/eval (90/10). Utilisez le format ChatML ou Alpaca." },
        { type: "summary", items: [
          "Le fine-tuning adapte un modèle pre-entraîné à votre domaine spécifique",
          "LoRA ne modifié que 0,1% des paramètres — rapide et économique",
          "QLoRA permet de fine-tuner un modèle 70B sur un GPU de 24GB",
          "Hiérarchie : prompt engineering → RAG → fine-tuning (du plus simple au plus complexe)",
          "La qualité des données détermine 80% du résultat du fine-tuning",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que LoRA ?",
          options: ["Un nouveau modèle de langage", "Une technique de fine-tuning qui ajouté des matrices de rang faible", "Un framework d'orchestration", "Un type d'attention"],
          correctIndex: 1,
          explanation: "LoRA (Low-Rank Adaptation) gele les poids originaux du modèle et ajouté de petites matrices de rang faible entraînées, ne modifiant que 0,1% des paramètres totaux.",
        },
        {
          question: "Quel est l'ordre recommandé pour personnaliser un LLM ?",
          options: ["Fine-tuning → RAG → Prompt engineering", "Prompt engineering → RAG → Fine-tuning", "RAG → Fine-tuning → Prompt engineering", "Fine-tuning → Prompt engineering → RAG"],
          correctIndex: 1,
          explanation: "On recommande de commencer par le prompt engineering (gratuit, rapide), puis RAG (données dynamiques), et enfin le fine-tuning (plus couteux) seulement si nécessaire.",
        },
        {
          question: "Que permet QLoRA ?",
          options: ["D'entraîner un modèle depuis zéro", "De fine-tuner un modèle 70B sur un GPU de 24GB", "De générer des images", "De traduire automatiquement"],
          correctIndex: 1,
          explanation: "QLoRA combiné LoRA avec la quantification 4-bit, permettant de fine-tuner un modèle de 70 milliards de paramètres sur un seul GPU de 24GB de VRAM.",
        },
        {
          question: "Quel facteur détermine 80% du résultat du fine-tuning ?",
          options: ["La taille du modèle", "Le GPU utilise", "La qualité des données d'entraînement", "Le nombre d'epochs"],
          correctIndex: 2,
          explanation: "La qualité des données d'entraînement détermine 80% du résultat. Des exemples propres, divers et representatifs sont plus importants que la quantité ou le matériel.",
        },
      ],
    },
    {
      number: 4,
      title: "RAG : Retrieval-Augmented Génération",
      description: "Ancrer les réponses de votre LLM dans vos propres données avec le RAG.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "RAG : Le Pattern Architectural Incontournable" },
        { type: "paragraph", content: "Le RAG (Retrieval-Augmented Génération) est le pattern le plus utilise en IA générative en 2026. Il combiné un système de recherche (retrieval) avec un LLM (génération) pour produire des réponses ancrees dans vos données spécifiques. C'est la solution au problème des hallucinations et de la connaissance limitée des LLM." },
        { type: "paragraph", content: "Le principe est simple : avant de générer une réponse, le système recherche les documents pertinents dans votre base de connaissances, les injecte dans le contexte du LLM, et le modèle génère sa réponse en se basant sur ces documents." },
        { type: "subheading", content: "Architecture RAG Standard" },
        { type: "paragraph", content: "1) Indexation : vos documents sont découpés en chunks, convertis en embeddings vectoriels, et stockés dans une base vectorielle. 2) Retrieval : la question de l'utilisateur est convertie en embedding et les chunks les plus similaires sont recuperes. 3) Génération : les chunks pertinents sont injectes dans le prompt et le LLM génère la réponse." },
        { type: "callout", content: "Le chunking est l'étape la plus sous-estimee du RAG. La taille des chunks (256-1024 tokens), le chevauchement (10-20%), et la stratégie de découpage (paragraphes, sections, phrases) impactent énormément la qualité des réponses." },
        { type: "video", videoId: { fr: "clCFL0JuE-w", en: "T-D1OfcDW1M" },
      videoDurationMinutes: 7, label: "RAG en détail" },
        { type: "heading", content: "RAG Avance" },
        { type: "paragraph", content: "Les techniques avancées de RAG incluent : le re-ranking (reordonner les résultats par pertinence), le RAG iteratif (plusieurs cycles de recherche), l'agentic RAG (le LLM décide quand et quoi chercher), le RAG multimodal (texte + images), et le fusion RAG (combiner plusieurs stratégies de retrieval)." },
        { type: "key-point", content: "La qualité du RAG dépend de la qualité du retrieval. Un retrieval mediocre = des réponses mediocres. Investissez dans les embeddings, le chunking, et le re-ranking avant d'optimiser la génération." },
        { type: "diagram", label: "Architecture RAG", flow: "horizontal", nodes: [
          { label: "Indexation", sub: "Chunks → Embeddings → Vector DB", color: "blue" },
          { label: "Retrieval", sub: "Query → Recherche sémantique", color: "purple" },
          { label: "Génération", sub: "Contexte + LLM → Réponse", color: "emerald" },
        ]},
        { type: "diagram", label: "Techniques RAG Avancées", flow: "vertical", nodes: [
          { label: "Re-ranking", sub: "Reordonner par pertinence", color: "blue" },
          { label: "RAG iteratif", sub: "Plusieurs cycles de recherche", color: "purple" },
          { label: "Agentic RAG", sub: "LLM décide quoi chercher", color: "emerald" },
          { label: "RAG multimodal", sub: "Texte + images + tableaux", color: "amber" },
        ]},
        { type: "summary", items: [
          "Le RAG combiné recherche documentaire et génération LLM",
          "Il résout le problème des hallucinations en ancrant les réponses dans vos données",
          "Le chunking est l'étape la plus critique et la plus sous-estimee",
          "Les techniques avancées incluent re-ranking, RAG iteratif et agentic RAG",
          "La qualité du retrieval détermine la qualité de la génération",
        ]},
      ],
      quiz: [
        {
          question: "Quel problème principal le RAG résout-il ?",
          options: ["La lenteur des LLM", "Les hallucinations et la connaissance limitée", "Le coût des APIs", "La génération d'images"],
          correctIndex: 1,
          explanation: "Le RAG ancre les réponses du LLM dans vos données spécifiques, reduisant les hallucinations et permettant au modèle de répondre sur des sujets qu'il ne connaît pas nativement.",
        },
        {
          question: "Quelle est la taille de chunk recommandée pour le RAG ?",
          options: ["32-64 tokens", "256-1024 tokens", "5000-10000 tokens", "1 document entier"],
          correctIndex: 1,
          explanation: "La taille de chunk recommandée est de 256 à 1024 tokens, avec un chevauchement de 10-20% entre les chunks pour préserver le contexte.",
        },
        {
          question: "Qu'est-ce que l'agentic RAG ?",
          options: ["Un agent qui remplace le RAG", "Un RAG ou le LLM décide quand et quoi chercher", "Un RAG sans base vectorielle", "Un RAG pour les agents de support"],
          correctIndex: 1,
          explanation: "L'agentic RAG donne au LLM le contrôle sur le processus de recherche : il décide quand chercher, quelle requête formuler, et s'il a besoin de recherches supplémentaires.",
        },
        {
          question: "Quelle étape du RAG est la plus sous-estimee ?",
          options: ["La génération", "Le choix du LLM", "Le chunking", "L'interface utilisateur"],
          correctIndex: 2,
          explanation: "Le chunking est l'étape la plus sous-estimee. La taille, le chevauchement et la stratégie de découpage impactent énormément la qualité du retrieval et donc des réponses.",
        },
      ],
    },
    {
      number: 5,
      title: "Agents IA et Tool Use",
      description: "Construire des agents autonomes qui raisonnent, planifient et utilisent des outils.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Les Agents IA : L'IA qui Agit" },
        { type: "paragraph", content: "Un agent IA est un système autonome qui utilise un LLM comme moteur de raisonnement pour planifier et exécuter des séquences d'actions. Contrairement a un chatbot, un agent peut utiliser des outils (recherche web, exécution de code, appels API, manipulation de fichiers) pour atteindre des objectifs complexes." },
        { type: "paragraph", content: "En 2026, les agents IA sont la prochaine frontiere. Claude Opus 4.6 avec 14,5h d'autonomie, GPT-5.4 avec Computer Use natif, et des frameworks comme LangGraph et CrewAI permettent de construire des agents sophistiques." },
        { type: "subheading", content: "Le Paradigme ReAct" },
        { type: "paragraph", content: "ReAct (Reasoning + Acting) est le paradigme dominant pour les agents. L'agent alterne entre pensee (Thought : je reflechis a ce qu'il faut faire), action (Action : j'utilise un outil), et observation (Observation : j'analyse le résultat). Cette boucle continue jusqu'à atteindre l'objectif." },
        { type: "subheading", content: "Tool Use et Function Calling" },
        { type: "paragraph", content: "Le function calling permet au LLM d'appeler des fonctions/outils de manière structuree. Le modèle reçoit une liste de fonctions disponibles (avec leur schéma JSON), décide laquelle appeler avec quels arguments, et intégré le résultat dans son raisonnement." },
        { type: "callout", content: "Le protocole MCP (Model Context Protocol) d'Anthropic standardisé la communication entre agents et outils. C'est le 'USB-C des agents IA' — un standard universel pour connecter n'importe quel outil a n'importe quel agent." },
        { type: "video", videoId: "zjkBMFhNj_g",
      videoDurationMinutes: 60, label: "Construire un agent IA" },
        { type: "heading", content: "Patterns d'Architecture Multi-Agent" },
        { type: "paragraph", content: "Les systèmes multi-agents assignent des rôles spécialisés a différents agents qui collaborent. Un agent 'planificateur' decompose la tâche, un agent 'chercheur' collecté les informations, un agent 'exécuteur' effectue les actions, et un agent 'revieweur' validé le résultat. CrewAI, AutoGen et LangGraph facilitent cette orchestration." },
        { type: "key-point", content: "La clé d'un bon agent est la définition précise des outils disponibles et de leurs schémas. Un outil mal défini = un agent qui hallucine ses appels. Investissez dans la documentation des outils." },
        { type: "diagram", label: "Boucle ReAct d'un Agent", flow: "cycle", nodes: [
          { label: "Thought", sub: "Raisonnement sur la prochaine étape", color: "blue" },
          { label: "Action", sub: "Appel d'un outil ou fonction", color: "emerald" },
          { label: "Observation", sub: "Analyse du résultat", color: "purple" },
        ]},
        { type: "prompt-example", prompt: "Construis un agent de recherche qui : 1) Recoit une question, 2) Cherche sur le web, 3) Analyse les sources, 4) Genere un rapport structure avec citations.", result: "L'agent utilise ReAct : il planifie les requêtes de recherche, appelle l'outil web_search, analyse chaque résultat, et compile un rapport avec les sources." },
        { type: "summary", items: [
          "Les agents IA utilisent des LLM pour raisonner et des outils pour agir",
          "ReAct alterne pensee, action et observation en boucle",
          "Le function calling structure les appels d'outils par le LLM",
          "MCP standardisé la connexion entre agents et outils",
          "Les systèmes multi-agents assignent des rôles spécialisés pour collaborer",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce qui différencié un agent IA d'un chatbot ?",
          options: ["Un agent est plus rapide", "Un agent peut planifier et utiliser des outils", "Un agent est gratuit", "Un agent ne fait que du texte"],
          correctIndex: 1,
          explanation: "Un agent IA peut planifier des séquences d'actions, utiliser des outils externes, et s'adapter aux résultats — un chatbot se contente de répondre a des messages.",
        },
        {
          question: "Que signifie MCP dans l'écosystème des agents IA ?",
          options: ["Machine Core Protocol", "Model Context Protocol", "Multi-Channel Processing", "Managed Cloud Platform"],
          correctIndex: 1,
          explanation: "MCP (Model Context Protocol) est un standard créé par Anthropic pour la communication entre agents IA et outils, permettant une interoperabilite universelle.",
        },
        {
          question: "Dans le paradigme ReAct, quelle est la séquence correcte ?",
          options: ["Action → Thought → Observation", "Observation → Action → Thought", "Thought → Action → Observation", "Action → Observation → Thought"],
          correctIndex: 2,
          explanation: "ReAct suit la séquence Thought (réflexion), Action (utilisation d'un outil), Observation (analyse du résultat), répétée en boucle jusqu'à l'objectif.",
        },
        {
          question: "Quel framework permet l'orchestration multi-agents ?",
          options: ["React.js", "Django", "CrewAI / LangGraph", "Express.js"],
          correctIndex: 2,
          explanation: "CrewAI, LangGraph et AutoGen sont des frameworks spécialisés dans l'orchestration de systèmes multi-agents avec des rôles et des workflows collaboratifs.",
        },
      ],
    },
    {
      number: 6,
      title: "Prompt Engineering Système",
      description: "System prompts, meta-prompting et techniques avancées de prompt engineering.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Le Prompt Engineering Système" },
        { type: "paragraph", content: "Le prompt engineering système va au-dela des prompts utilisateur. Il s'agit de définir le comportement, la personnalité, les contraintes et les capacités d'un système IA complet via le system prompt. C'est l'équivalent de la 'programmation' d'un LLM." },
        { type: "paragraph", content: "Un system prompt bien conçu transformé un LLM générique en un assistant spécialisé. Il definit le rôle, le ton, les règles de sécurité, le format de sortie, les limites, et les instructions de fallback. C'est le coeur de toute application IA." },
        { type: "subheading", content: "Structure d'un System Prompt Professionnel" },
        { type: "paragraph", content: "Un system prompt efficace suit une structure en couches : 1) Identité et rôle, 2) Contexte et connaissances, 3) Règles et contraintes, 4) Format de sortie, 5) Exemples (few-shot), 6) Instructions de sécurité. Chaque couche renforce la précédente." },
        { type: "callout", content: "Le system prompt de Claude (Anthropic) fait plus de 4000 tokens. Celui de ChatGPT (OpenAI) en fait environ 3000. Les system prompts professionnels sont des documents détaillés, pas des phrases simples." },
        { type: "video", videoId: { fr: "UoBVumRnyds", en: "kCc8FmEb1nY" },
      videoDurationMinutes: 116, label: "System prompts avances" },
        { type: "subheading", content: "Meta-Prompting" },
        { type: "paragraph", content: "Le meta-prompting utilise un LLM pour générer ou optimiser des prompts. Vous decrivez votre objectif et le modèle génère le prompt optimal. C'est particulièrement utile pour les cas d'usage complexes ou le prompt engineering manuel atteint ses limites." },
        { type: "heading", content: "Techniques Avancées" },
        { type: "paragraph", content: "Chain-of-Thought force le raisonnement étape par étape. Tree-of-Thought explore plusieurs pistes en parallèle. Prompt chaining enchaine plusieurs appels LLM. Le constitutional AI intégré des principes ethiques directement dans le prompt." },
        { type: "key-point", content: "Le prompt caching est critique pour les coûts. Placez les instructions stables (system prompt, exemples) au début et le contenu dynamique a la fin. Le cache Anthropic a un TTL de 5 minutes — structurez vos appels en consequence." },
        { type: "prompt-example", prompt: "Tu es un expert en rédaction de system prompts. Cree un system prompt pour un assistant juridique spécialisé en droit du travail français. Il doit citer les articles de loi, refuser les questions hors perimetre, et avertir qu'il ne remplace pas un avocat.", result: "Le system prompt génère inclut le rôle (juriste assistant), les connaissances (Code du travail), les règles (citations obligatoires, disclaimers), le format (structure juridique) et les garde-fous (perimetre, disclaimer)." },
        { type: "diagram", label: "Structure d'un System Prompt", flow: "vertical", nodes: [
          { label: "Identité & Rôle", sub: "Qui est l'assistant, son expertise", color: "purple" },
          { label: "Règles & Contraintes", sub: "Ce qu'il peut et ne peut pas faire", color: "blue" },
          { label: "Format de Sortie", sub: "Structure, longueur, style", color: "emerald" },
          { label: "Sécurité & Garde-fous", sub: "Limites, disclaimers, refus", color: "pink" },
        ]},
        { type: "summary", items: [
          "Le system prompt est la 'programmation' d'un LLM pour une application spécifique",
          "Structure en couches : identité, règles, format, exemples, sécurité",
          "Les system prompts professionnels font 3000-4000+ tokens",
          "Le meta-prompting utilise un LLM pour générer des prompts optimaux",
          "Le prompt caching réduit les coûts — structurez statique en premier",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que le prompt engineering système ?",
          options: ["Écrire des prompts utilisateur", "Définir le comportement complet d'un système IA via le system prompt", "Programmer un LLM en Python", "Générer des images avec des prompts"],
          correctIndex: 1,
          explanation: "Le prompt engineering système consiste à définir le comportement, la personnalité, les contraintes et les capacités d'un système IA complet via le system prompt.",
        },
        {
          question: "Combien de tokens fait un system prompt professionnel ?",
          options: ["50-100 tokens", "500-1000 tokens", "3000-4000+ tokens", "100 000 tokens"],
          correctIndex: 2,
          explanation: "Les system prompts professionnels comme ceux de Claude ou ChatGPT font 3000-4000+ tokens. Ce sont des documents détaillés definissant le comportement complet du système.",
        },
        {
          question: "Qu'est-ce que le meta-prompting ?",
          options: ["Un prompt très long", "Utiliser un LLM pour générer des prompts optimaux", "Un type de prompt pour les images", "Un prompt qui se corrige lui-même"],
          correctIndex: 1,
          explanation: "Le meta-prompting utilise un LLM pour générer ou optimiser des prompts, particulièrement utile pour les cas d'usage complexes ou le prompt engineering manuel atteint ses limites.",
        },
        {
          question: "Pourquoi le prompt caching est-il important ?",
          options: ["Pour accélérer la génération", "Pour réduire les coûts en cachant les parties statiques", "Pour sauvegarder les prompts", "Pour partager les prompts"],
          correctIndex: 1,
          explanation: "Le prompt caching permet de ne pas re-traiter les parties statiques du prompt (system prompt, exemples) à chaque appel, reduisant significativement les coûts d'API.",
        },
      ],
    },
    {
      number: 7,
      title: "APIs OpenAI, Anthropic et Google",
      description: "Maîtriser les APIs des trois grands providers pour construire des applications IA.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Les APIs des Grands Providers IA" },
        { type: "paragraph", content: "Les APIs d'OpenAI, Anthropic et Google sont les briques de base pour construire des applications IA. Chaque provider a ses forces, ses prix et ses specificites. Maîtriser ces APIs est essentiel pour tout développeur IA." },
        { type: "subheading", content: "API OpenAI (GPT-5.4)" },
        { type: "paragraph", content: "L'API OpenAI est la plus utilisée. Elle offre les endpoints Chat Completions, Assistants API (avec memory et tools), DALL-E, Whisper (speech-to-text), et TTS (text-to-speech). Le streaming, le function calling, et la vision sont intègres nativement. Tarif : $2.50/M tokens input, $10/M tokens output pour GPT-5.4." },
        { type: "subheading", content: "API Anthropic (Claude 4.6)" },
        { type: "paragraph", content: "L'API Anthropic se distingue par le prompt caching (réduction de 90% des coûts sur les parties statiques), l'Extended Thinking (raisonnement visible), le Computer Use, et les batches (50% de réduction). Claude Opus 4.6 : $15/M input, $75/M output. Claude Sonnet 4.6 : $3/M input, $15/M output." },
        { type: "subheading", content: "API Google (Gemini 3.1)" },
        { type: "paragraph", content: "L'API Gemini est nativement multimodal (texte, image, audio, video dans le même appel). Contexte de 1M tokens, grounding with Google Search, et intégration à l'écosystème Google Cloud. Gemini 3.1 Pro est gratuit pour les développeurs jusqu'à 60 requêtes/minute." },
        { type: "callout", content: "Astuce coûts : utilisez Claude Haiku ou GPT-4o-mini pour les tâches simples (classification, extraction), et reservez les modèles premium (Opus, GPT-5.4 Pro) pour les tâches complexes de raisonnement. Le routing intelligent réduit les coûts de 70%." },
        { type: "video", videoId: "bZQun8Y4L2A",
      videoDurationMinutes: 43, label: "APIs IA en pratique" },
        { type: "key-point", content: "Ne vous enfermez pas dans un seul provider. Utilisez une couche d'abstraction (Vercel AI SDK, LiteLLM) pour pouvoir switcher entre providers selon les performances et les coûts." },
        { type: "diagram", label: "Comparatif des APIs en 2026", flow: "horizontal", nodes: [
          { label: "OpenAI", sub: "Le plus utilise, Assistants API, DALL-E", color: "emerald" },
          { label: "Anthropic", sub: "Prompt caching, Extended Thinking", color: "purple" },
          { label: "Google", sub: "Multimodal natif, gratuit dev, Google Search", color: "blue" },
        ]},
        { type: "prompt-example", prompt: "Compare le coût pour traiter 1 million de documents de 500 tokens chacun avec Claude Sonnet vs GPT-4o-mini vs Gemini Flash. Inclus le prompt caching pour Claude.", result: "Avec prompt caching Anthropic, Claude Sonnet revient a ~$0.30/M tokens cache. GPT-4o-mini : $0.15/M input. Gemini Flash : gratuit jusqu'au quota. Le choix dépend du ratio qualité/coût." },
        { type: "summary", items: [
          "OpenAI : l'API la plus utilisée avec Assistants API et function calling",
          "Anthropic : prompt caching (-90% coûts), Extended Thinking, batches",
          "Google : multimodal natif, 1M tokens, gratuit pour les développeurs",
          "Le routing intelligent entre modèles réduit les coûts de 70%",
          "Utilisez une couche d'abstraction pour ne pas dépendre d'un seul provider",
        ]},
      ],
      quiz: [
        {
          question: "Quel avantage unique offre l'API Anthropic ?",
          options: ["La génération d'images", "Le prompt caching avec 90% de réduction", "La génération de video", "L'accès gratuit illimite"],
          correctIndex: 1,
          explanation: "L'API Anthropic se distingue par son prompt caching qui réduit de 90% les coûts sur les parties statiques du prompt, un avantage majeur pour les applications avec des system prompts longs.",
        },
        {
          question: "Quelle API est nativement multimodale (texte + image + audio + video) ?",
          options: ["OpenAI", "Anthropic", "Google Gemini", "Mistral"],
          correctIndex: 2,
          explanation: "L'API Gemini de Google est nativement multimodale, acceptant texte, images, audio et video dans le même appel API, sans endpoints séparés.",
        },
        {
          question: "Comment réduire les coûts d'API de 70% ?",
          options: ["En negociant un contrat", "En utilisant le routing intelligent entre modèles", "En envoyant moins de requêtes", "En compressant les données"],
          correctIndex: 1,
          explanation: "Le routing intelligent dirige les tâches simples vers des modèles économiques (Haiku, GPT-4o-mini) et réservé les modèles premium pour les tâches complexes, reduisant les coûts de 70%.",
        },
        {
          question: "Pourquoi utiliser une couche d'abstraction comme Vercel AI SDK ?",
          options: ["Pour accélérer les réponses", "Pour pouvoir switcher entre providers sans changer le code", "Pour générer des images", "Pour stocker les conversations"],
          correctIndex: 1,
          explanation: "Une couche d'abstraction permet de changer de provider (OpenAI, Anthropic, Google) sans modifier le code applicatif, offrant flexibilité et resilience.",
        },
      ],
    },
    {
      number: 8,
      title: "Langchain et Frameworks d'Orchestration",
      description: "Utiliser LangChain, LlamaIndex et LangGraph pour orchestrer des applications IA complexes.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Les Frameworks d'Orchestration IA" },
        { type: "paragraph", content: "Les frameworks d'orchestration simplifient la construction d'applications IA complexes en fournissant des abstractions pour les chains, les agents, les outils, la mémoire et le RAG. LangChain, LlamaIndex et LangGraph sont les trois piliers de l'écosystème en 2026." },
        { type: "subheading", content: "LangChain" },
        { type: "paragraph", content: "LangChain est le framework le plus populaire. Il fournit des abstractions pour les LLM, les prompts, les chains (séquences d'appels), les agents (boucles de raisonnement), les outils, et la mémoire. Il supporte Python et JavaScript/TypeScript." },
        { type: "subheading", content: "LlamaIndex" },
        { type: "paragraph", content: "LlamaIndex est spécialisé dans le RAG et l'indexation de données. Il excelle dans l'ingestion de documents (PDF, web, bases de données), le chunking intelligent, les embeddings, et la recherche sémantique. C'est le choix idéal pour les applications centrees sur les données." },
        { type: "subheading", content: "LangGraph" },
        { type: "paragraph", content: "LangGraph est le framework pour les agents complexes et les workflows multi-étapes. Il modelise les applications IA comme des graphes d'états (state machines) avec des noeuds (actions) et des aretes (transitions). Il gère nativement la persistence, le streaming, et le human-in-the-loop." },
        { type: "callout", content: "Attention a la 'framework fatigue' : LangChain a été critique pour sa complexité. Evaluez si un simple appel API suffit avant d'ajouter un framework. La simplicité est souvent la meilleure architecture." },
        { type: "video", videoId: { fr: "clCFL0JuE-w", en: "T-D1OfcDW1M" },
      videoDurationMinutes: 7, label: "LangChain et LangGraph en pratique" },
        { type: "heading", content: "Alternatives Legeres" },
        { type: "paragraph", content: "Vercel AI SDK est une alternative légère et moderne pour les applications web. Il gère le streaming, le function calling, et les providers multiples avec une API simple. Pour les projets simples, un appel API direct avec gestion manuelle du contexte peut suffire." },
        { type: "key-point", content: "Choisissez votre framework selon le cas d'usage : LlamaIndex pour le RAG, LangGraph pour les agents complexes, Vercel AI SDK pour les apps web, et API directe pour les cas simples." },
        { type: "diagram", label: "Écosystème des Frameworks IA", flow: "horizontal", nodes: [
          { label: "LangChain", sub: "Chains, agents, outils, mémoire", color: "blue" },
          { label: "LlamaIndex", sub: "RAG, indexation, documents", color: "purple" },
          { label: "LangGraph", sub: "Graphes d'états, agents complexes", color: "emerald" },
          { label: "Vercel AI SDK", sub: "Apps web, streaming, léger", color: "amber" },
        ]},
        { type: "summary", items: [
          "LangChain : framework generaliste pour chains, agents et outils",
          "LlamaIndex : spécialisé RAG, indexation et ingestion de documents",
          "LangGraph : graphes d'états pour agents complexes et workflows",
          "Vercel AI SDK : alternative légère pour les applications web",
          "Évaluer si un framework est nécessaire — la simplicité est souvent preferable",
        ]},
      ],
      quiz: [
        {
          question: "Quel framework est spécialisé dans le RAG et l'indexation ?",
          options: ["LangChain", "LlamaIndex", "LangGraph", "React"],
          correctIndex: 1,
          explanation: "LlamaIndex est spécialisé dans le RAG et l'indexation de données, avec des outils avances pour l'ingestion, le chunking et la recherche sémantique.",
        },
        {
          question: "Comment LangGraph modelise-t-il les applications IA ?",
          options: ["Comme des listes", "Comme des graphes d'états", "Comme des tableaux", "Comme des arbres"],
          correctIndex: 1,
          explanation: "LangGraph modelise les applications IA comme des graphes d'états (state machines) avec des noeuds (actions) et des aretes (transitions), idéal pour les agents complexes.",
        },
        {
          question: "Quel conseil est donne concernant les frameworks ?",
          options: ["Toujours utiliser LangChain", "Évaluer si un simple appel API suffit avant d'ajouter un framework", "Combiner tous les frameworks", "Éviter tous les frameworks"],
          correctIndex: 1,
          explanation: "Il est recommandé d'évaluer si un simple appel API suffit avant d'ajouter un framework complexe. La simplicité est souvent la meilleure architecture.",
        },
        {
          question: "Quel framework est recommandé pour les applications web avec streaming ?",
          options: ["LangChain", "LlamaIndex", "LangGraph", "Vercel AI SDK"],
          correctIndex: 3,
          explanation: "Vercel AI SDK est une alternative légère et moderne spécialisée pour les applications web, avec gestion native du streaming et du function calling.",
        },
      ],
    },
    {
      number: 9,
      title: "Embeddings et Bases Vectorielles",
      description: "Comprendre les embeddings et utiliser les bases vectorielles pour la recherche sémantique.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Les Embeddings : Le Langage des Machines" },
        { type: "paragraph", content: "Les embeddings sont des représentations numériques (vecteurs) du texte, des images ou de l'audio dans un espace multidimensionnel. Deux textes semantiquement similaires auront des embeddings proches. C'est la technologie qui permet la recherche sémantique, le clustering, et le RAG." },
        { type: "paragraph", content: "Les modèles d'embedding modernes (OpenAI text-embedding-3, Cohere Embed v3, Voyage AI) produisent des vecteurs de 256 à 3072 dimensions. La similarite entre deux embeddings est mesuree par la distance cosinus ou le produit scalaire." },
        { type: "subheading", content: "Bases de Données Vectorielles" },
        { type: "paragraph", content: "Les bases vectorielles stockent et indexent des millions d'embeddings pour permettre des recherches par similarite en millisecondes. Les principales : Pinecone (managed, serverless), Weaviate (open source, filtrage hybride), Qdrant (Rust, performant), ChromaDB (léger, local), et pgvector (extension PostgreSQL)." },
        { type: "callout", content: "Pour la plupart des projets, pgvector (extension PostgreSQL) est suffisant. Vous n'avez pas besoin d'une base vectorielle dedicee si vous avez déjà PostgreSQL. Commencez simple et scalez si nécessaire." },
        { type: "video", videoId: "zjkBMFhNj_g",
      videoDurationMinutes: 60, label: "Embeddings et bases vectorielles" },
        { type: "heading", content: "Recherche Hybride" },
        { type: "paragraph", content: "La recherche hybride combiné la recherche sémantique (embeddings) avec la recherche lexicale (BM25, full-text search). Cette combinaison donne les meilleurs résultats pour le RAG car elle capture à la fois le sens (sémantique) et les mots-clés exacts (lexical)." },
        { type: "key-point", content: "La qualité des embeddings dépend du modèle utilise. Pour le français, testez Voyage AI (multilingue de référence), Cohere Embed v3, et OpenAI text-embedding-3-large. Evaluez sur vos propres données — les benchmarks génériques ne suffisent pas." },
        { type: "diagram", label: "Pipeline Embeddings + Vector DB", flow: "horizontal", nodes: [
          { label: "Texte / Documents", sub: "Chunks de contenu brut", color: "blue" },
          { label: "Modèle d'Embedding", sub: "text-embedding-3, Voyage AI", color: "purple" },
          { label: "Base Vectorielle", sub: "Pinecone, pgvector, Qdrant", color: "emerald" },
          { label: "Recherche Sémantique", sub: "Similarite cosinus → top K", color: "amber" },
        ]},
        { type: "tip", content: "Dimensionalite des embeddings : plus de dimensions = plus de nuances mais plus de stockage et de latence. OpenAI text-embedding-3 permet de choisir la dimensionalite (256, 1024, 3072). 1024 est un bon équilibre." },
        { type: "summary", items: [
          "Les embeddings représentent le sens du texte sous forme de vecteurs numériques",
          "Les bases vectorielles permettent la recherche par similarite en millisecondes",
          "pgvector (PostgreSQL) suffit pour la plupart des projets",
          "La recherche hybride (sémantique + lexicale) donne les meilleurs résultats RAG",
          "Evaluez les modèles d'embedding sur vos propres données, pas sur les benchmarks",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce qu'un embedding ?",
          options: ["Un type de base de données", "Une représentation numérique du texte dans un espace vectoriel", "Un algorithme de tri", "Un format de fichier"],
          correctIndex: 1,
          explanation: "Un embedding est un vecteur numérique représentant le sens d'un texte (ou image/audio) dans un espace multidimensionnel. Des textes similaires ont des embeddings proches.",
        },
        {
          question: "Quelle base vectorielle est recommandée pour commencer ?",
          options: ["Pinecone", "Weaviate", "pgvector (PostgreSQL)", "FAISS"],
          correctIndex: 2,
          explanation: "pgvector, l'extension PostgreSQL, est recommandée pour commencer car elle s'intégré a une base existante sans infrastructure supplémentaire. Scalez vers une base dédiée si nécessaire.",
        },
        {
          question: "Qu'est-ce que la recherche hybride ?",
          options: ["Chercher dans deux bases différentes", "Combiner recherche sémantique (embeddings) et lexicale (BM25)", "Chercher en ligne et hors ligne", "Chercher du texte et des images"],
          correctIndex: 1,
          explanation: "La recherche hybride combiné la recherche sémantique (sens) et la recherche lexicale (mots-clés exacts) pour de meilleurs résultats, capturant à la fois le sens et la précision.",
        },
        {
          question: "Quelle dimensionalite d'embedding est un bon équilibre ?",
          options: ["32", "256", "1024", "10000"],
          correctIndex: 2,
          explanation: "1024 dimensions est un bon équilibre entre nuance (qualité de la représentation sémantique) et efficacité (stockage et latence de recherche).",
        },
      ],
    },
    {
      number: 10,
      title: "Génération d'Images Avancée",
      description: "Techniques avancées de génération d'images : ControlNet, inpainting, flux workflows.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Au-Dela du Prompt : Génération d'Images Avancée" },
        { type: "paragraph", content: "La génération d'images IA ne se limite pas à écrire un prompt dans Midjourney. Les techniques avancées offrent un contrôle précis : ControlNet pour guider la composition, l'inpainting pour modifier des zones spécifiques, img2img pour transformer des images existantes, et les flux workflows pour automatiser des pipelines complexes." },
        { type: "subheading", content: "ControlNet" },
        { type: "paragraph", content: "ControlNet ajouté des conditions supplémentaires au processus de génération : pose humaine (OpenPose), contours (Canny), profondeur (Depth), segmentation. Vous pouvez fournir un croquis ou une pose et obtenir une image photoraliste qui respecte exactement votre composition." },
        { type: "subheading", content: "Inpainting et Outpainting" },
        { type: "paragraph", content: "L'inpainting modifié une zone spécifique d'une image tout en preservant le reste. L'outpainting etend l'image au-dela de ses bordures. Ces techniques sont essentielles pour l'edition non destructive et la création de contenus marketing." },
        { type: "callout", content: "Flux (de Black Forest Labs) est devenu le modèle open source de référence en 2026, surpassant Stable Diffusion pour la qualité d'image et la fidélité au prompt. ComfyUI est l'interface standard pour les workflows avances." },
        { type: "video", videoId: { fr: "UoBVumRnyds", en: "kCc8FmEb1nY" },
      videoDurationMinutes: 116, label: "Génération d'images avancée" },
        { type: "heading", content: "Workflows de Production" },
        { type: "paragraph", content: "Les workflows de production combinent plusieurs étapes : génération initiale, upscaling (Real-ESRGAN, Topaz), retouche (inpainting), variantes (img2img), et post-traitement. ComfyUI permet de désigner ces workflows visuellement et de les automatiser via API." },
        { type: "key-point", content: "Pour les projets professionnels, le contrôle est plus important que la qualité brute. ControlNet + inpainting + workflows reproductibles permettent de produire des résultats consistants, pas juste de beaux hasards." },
        { type: "diagram", label: "Techniques de Génération Avancée", flow: "horizontal", nodes: [
          { label: "ControlNet", sub: "Pose, contours, profondeur", color: "purple" },
          { label: "Inpainting", sub: "Edition locale précise", color: "blue" },
          { label: "Img2Img", sub: "Transformation d'images", color: "emerald" },
          { label: "Upscaling", sub: "Real-ESRGAN, amélioration", color: "amber" },
        ]},
        { type: "summary", items: [
          "ControlNet guide la génération avec des conditions (pose, contours, profondeur)",
          "L'inpainting modifié des zones spécifiques sans toucher au reste",
          "Flux est le modèle open source de référence en 2026",
          "ComfyUI est l'interface standard pour les workflows avances",
          "Le contrôle reproductible est plus important que la qualité brute en production",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que ControlNet ?",
          options: ["Un antivirus", "Un système de contrôle qui guide la génération d'images avec des conditions", "Un réseau social", "Un format d'image"],
          correctIndex: 1,
          explanation: "ControlNet ajouté des conditions supplémentaires (pose, contours, profondeur) au processus de génération d'images, offrant un contrôle précis sur la composition.",
        },
        {
          question: "Qu'est-ce que l'inpainting ?",
          options: ["Peindre une image entière", "Modifier une zone spécifique d'une image tout en preservant le reste", "Compresser une image", "Convertir une image en texte"],
          correctIndex: 1,
          explanation: "L'inpainting modifié une zone spécifique d'une image (sélectionnée par un masque) tout en preservant le reste, permettant l'edition non destructive.",
        },
        {
          question: "Quel modèle open source de génération d'images domine en 2026 ?",
          options: ["Stable Diffusion", "DALL-E", "Flux (Black Forest Labs)", "Midjourney"],
          correctIndex: 2,
          explanation: "Flux de Black Forest Labs a surpasse Stable Diffusion en 2026 pour la qualité d'image et la fidélité au prompt, devenant le modèle open source de référence.",
        },
        {
          question: "Quel outil est le standard pour les workflows de génération d'images ?",
          options: ["Photoshop", "ComfyUI", "Canva", "Figma"],
          correctIndex: 1,
          explanation: "ComfyUI est l'interface standard pour désigner des workflows de génération d'images avances, combinant ControlNet, inpainting, upscaling et autres étapes.",
        },
      ],
    },
    {
      number: 11,
      title: "Multimodal : Texte, Image, Audio, Vidéo",
      description: "Construire des applications qui combinent texte, images, audio et video avec l'IA.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "L'Ère du Multimodal" },
        { type: "paragraph", content: "Les modèles multimodaux traitent et generent plusieurs types de données dans un seul modèle : texte, images, audio et video. En 2026, le multimodal est la norme — GPT-5.4, Claude 4.6 et Gemini 3.1 sont tous nativement multimodaux." },
        { type: "paragraph", content: "Les applications multimodales vont au-dela du simple 'decrire une image'. Elles combinent vision + langage pour l'analyse de documents, audio + texte pour les assistants vocaux, video + texte pour le sous-titrage et l'indexation, et image + texte pour le e-commerce et la recherche visuelle." },
        { type: "subheading", content: "Vision + Langage" },
        { type: "paragraph", content: "L'OCR IA extrait du texte structure de n'importe quel document (factures, contrats, formulaires). L'analyse d'images répond a des questions complexes sur le contenu visuel. Le visual grounding identifié et localise des objets mentionnes en langage naturel." },
        { type: "subheading", content: "Audio + Texte" },
        { type: "paragraph", content: "La transcription (Whisper, Deepgram) convertit la parole en texte avec une précision de 95%+. La synthèse vocale (ElevenLabs, Play.ht) génère des voix naturelles. La combinaison des deux créé des assistants vocaux complets." },
        { type: "callout", content: "Gemini 3.1 accepte nativement des vidéos complètes comme input — pas besoin d'extraire des frames. Vous pouvez poser des questions sur une video d'une heure et obtenir des réponses contextuelles précises." },
        { type: "video", videoId: "bZQun8Y4L2A",
      videoDurationMinutes: 43, label: "Applications multimodales" },
        { type: "key-point", content: "Le multimodal simplifie les architectures. Au lieu de pipelines complexes (OCR → NLP → classification), un seul appel multimodal traité le document entier. Moins de code, moins de bugs, meilleure précision." },
        { type: "diagram", label: "Applications Multimodales", flow: "horizontal", nodes: [
          { label: "Vision + Langage", sub: "OCR, analyse docs, e-commerce", color: "purple" },
          { label: "Audio + Texte", sub: "Transcription, assistants vocaux", color: "blue" },
          { label: "Vidéo + Texte", sub: "Sous-titrage, indexation, Q&A", color: "emerald" },
          { label: "Tout-en-un", sub: "Un seul modèle, une seule API", color: "amber" },
        ]},
        { type: "summary", items: [
          "Les modèles multimodaux traitent texte, images, audio et video nativement",
          "L'OCR IA extrait du texte structure de n'importe quel document",
          "Gemini 3.1 accepte des vidéos complètes comme input",
          "Le multimodal simplifie les architectures (1 appel au lieu de pipelines)",
          "Les cas d'usage : analyse de documents, assistants vocaux, e-commerce visuel",
        ]},
      ],
      quiz: [
        {
          question: "Que signifie 'multimodal' pour un modèle IA ?",
          options: ["Il est très puissant", "Il traité plusieurs types de données (texte, image, audio, video)", "Il fonctionne sur plusieurs appareils", "Il parle plusieurs langues"],
          correctIndex: 1,
          explanation: "Un modèle multimodal peut traiter et générer plusieurs types de données — texte, images, audio et video — dans un seul modèle unifie.",
        },
        {
          question: "Quel avantage architectural offre le multimodal ?",
          options: ["Plus de complexité", "Simplification : un seul appel remplace des pipelines complexes", "Plus de serveurs nécessaires", "Des coûts plus élèves"],
          correctIndex: 1,
          explanation: "Le multimodal simplifie les architectures : un seul appel API multimodal remplace des pipelines complexes (OCR + NLP + classification), avec moins de code et meilleure précision.",
        },
        {
          question: "Quel modèle accepte nativement des vidéos complètes comme input ?",
          options: ["GPT-5.4", "Claude 4.6", "Gemini 3.1", "Mistral"],
          correctIndex: 2,
          explanation: "Gemini 3.1 accepte nativement des vidéos complètes comme input, permettant de poser des questions sur une video d'une heure sans extraire de frames.",
        },
        {
          question: "Quelle précision les meilleurs systèmes de transcription IA atteignent-ils ?",
          options: ["70%", "85%", "95%+", "100%"],
          correctIndex: 2,
          explanation: "Les systèmes de transcription modernes (Whisper, Deepgram) atteignent une précision de 95%+ sur la parole claire, rivalisant avec les transcripteurs humains.",
        },
      ],
    },
    {
      number: 12,
      title: "Évaluation et Benchmarking",
      description: "Mesurer la qualité de vos systèmes IA : métriques, benchmarks et évaluation humaine.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Évaluer la Qualité de Vos Systèmes IA" },
        { type: "paragraph", content: "L'évaluation est le parent pauvre de l'IA générative. Beaucoup construisent des systèmes sans mesurer leur qualité. Pourtant, sans évaluation rigoureuse, vous ne savez pas si votre système s'améliore ou se dégradé. L'évaluation doit être systematique, reproductible et automatisée." },
        { type: "subheading", content: "Metriques pour le RAG" },
        { type: "paragraph", content: "Les métriques clés du RAG : Faithfulness (la réponse est-elle fidèle aux documents recuperes ?), Relevance (les documents recuperes sont-ils pertinents ?), Answer completeness (la réponse couvre-t-elle toute la question ?). Des frameworks comme RAGAS automatisent ces évaluations." },
        { type: "subheading", content: "Évaluation LLM-as-Judge" },
        { type: "paragraph", content: "Utiliser un LLM pour évaluer les sorties d'un autre LLM est devenu standard. Claude Opus ou GPT-5.4 Pro evaluent les réponses selon des critères définis (pertinence, précision, complétude, ton). C'est plus rapide et moins cher que l'évaluation humaine pour les iterations rapides." },
        { type: "callout", content: "Les benchmarks publics (MMLU, HumanEval, ARC-AGI) comparent les modèles entre eux, mais ne mesurent pas la performance sur votre cas d'usage spécifique. Creez toujours un benchmark interne avec vos propres données." },
        { type: "video", videoId: { fr: "clCFL0JuE-w", en: "T-D1OfcDW1M" },
      videoDurationMinutes: 7, label: "Évaluer vos systèmes IA" },
        { type: "key-point", content: "La règle d'or de l'évaluation : mesurez ce qui compte pour vos utilisateurs, pas ce qui est facile à mesurer. Le taux de satisfaction utilisateur est plus important que le score BLEU." },
        { type: "diagram", label: "Types d'Évaluation IA", flow: "horizontal", nodes: [
          { label: "Metriques automatiques", sub: "RAGAS, BLEU, ROUGE, perplexite", color: "blue" },
          { label: "LLM-as-Judge", sub: "Claude/GPT évalue les sorties", color: "purple" },
          { label: "Évaluation humaine", sub: "Annotateurs, A/B testing", color: "emerald" },
        ]},
        { type: "tip", content: "Creez un 'golden dataset' de 100+ exemples avec les réponses attendues. Executez-le à chaque changement de prompt, modèle ou pipeline. C'est votre suite de tests pour l'IA." },
        { type: "summary", items: [
          "L'évaluation doit être systematique, reproductible et automatisée",
          "Metriques RAG : faithfulness, relevance, completeness",
          "LLM-as-Judge est standard pour les iterations rapides",
          "Les benchmarks publics ne remplacent pas l'évaluation sur vos données",
          "Creez un golden dataset de 100+ exemples comme suite de tests",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que LLM-as-Judge ?",
          options: ["Un benchmark public", "Utiliser un LLM pour évaluer les sorties d'un autre LLM", "Un juge humain", "Un framework de test"],
          correctIndex: 1,
          explanation: "LLM-as-Judge utilise un LLM puissant (Claude Opus, GPT-5.4 Pro) pour évaluer automatiquement les réponses d'un autre LLM selon des critères définis.",
        },
        {
          question: "Quelle métrique RAG mesure si la réponse est fidèle aux documents ?",
          options: ["Relevance", "Faithfulness", "Completeness", "Perplexite"],
          correctIndex: 1,
          explanation: "La Faithfulness mesure si la réponse générée est fidèle aux documents recuperes — c'est-a-dire si elle ne contient pas d'informations inventées par le modèle.",
        },
        {
          question: "Combien d'exemples un golden dataset doit-il contenir au minimum ?",
          options: ["10", "50", "100+", "1000+"],
          correctIndex: 2,
          explanation: "Un golden dataset de 100+ exemples avec les réponses attendues est recommandé comme suite de tests pour évaluer votre système IA à chaque changement.",
        },
        {
          question: "Que faut-il mesurer en priorité ?",
          options: ["Le score BLEU", "Le nombre de tokens", "Ce qui compte pour vos utilisateurs", "La vitesse de génération"],
          correctIndex: 2,
          explanation: "La priorité est de mesurer ce qui compte pour vos utilisateurs (satisfaction, pertinence, précision) plutôt que des métriques techniques faciles à calculer.",
        },
      ],
    },
    {
      number: 13,
      title: "Mise en Production",
      description: "Déployer un système IA en production : infrastructure, monitoring et scalabilite.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "De la Demo a la Production" },
        { type: "paragraph", content: "Faire fonctionner un prototype IA est facile. Le déployer en production de manière fiable, performante et économique est un tout autre défi. La mise en production couvre l'infrastructure, le monitoring, la scalabilite, la sécurité, la gestion des erreurs et la conformite." },
        { type: "paragraph", content: "80% des projets IA restent au stade de prototype. Les raisons : coûts mal anticipes, latence trop élevée, hallucinations non gérées, absence de monitoring, et non-conformite réglementaire. Ce chapitre couvre tout ce qu'il faut pour franchir le cap." },
        { type: "subheading", content: "Architecture de Production" },
        { type: "paragraph", content: "Une architecture IA de production inclut : un gateway API (rate limiting, auth), un routeur de modèles (sélection du meilleur modèle), un cache (réponses fréquentes), un système de fallback (provider alternatif si le primaire tombe), et un pipeline d'observabilite (logs, traces, métriques)." },
        { type: "subheading", content: "Monitoring et Observabilite" },
        { type: "paragraph", content: "Les métriques clés a surveiller : latence (P50, P95, P99), taux d'erreur, tokens consommes, coût par requête, taux d'hallucination, satisfaction utilisateur. Des outils comme Langfuse, LangSmith et Helicone fournissent l'observabilite complète." },
        { type: "callout", content: "Le streaming est incontournable en production. Il réduit la latence percue de 10x : l'utilisateur voit la réponse se construire en temps réel au lieu d'attendre 5 secondes. Tous les providers supportent le streaming." },
        { type: "video", videoId: "zjkBMFhNj_g",
      videoDurationMinutes: 60, label: "Mise en production IA" },
        { type: "heading", content: "Gestion des Erreurs et Guardrails" },
        { type: "paragraph", content: "Les guardrails en production incluent : la validation des sorties (format JSON, longueur, contenu), la détection d'hallucinations, le filtrage de contenu toxique, le circuit breaker (arrêter les appels si le taux d'erreur explose), et les alertes automatiques." },
        { type: "key-point", content: "Le cache sémantique peut réduire vos coûts de 40-60%. Si la question de l'utilisateur est semantiquement similaire à une question déjà posee, retournez la réponse en cache. GPTCache et Redis avec embeddings implementent cette stratégie." },
        { type: "diagram", label: "Architecture de Production IA", flow: "vertical", nodes: [
          { label: "API Gateway", sub: "Rate limiting, auth, routing", color: "blue" },
          { label: "Routeur de Modèles", sub: "Sélection du modèle optimal", color: "purple" },
          { label: "Cache Sémantique", sub: "Réponses fréquentes, -60% coûts", color: "emerald" },
          { label: "Observabilite", sub: "Langfuse, métriques, alertes", color: "amber" },
        ]},
        { type: "summary", items: [
          "80% des projets IA restent au stade de prototype — la production est le vrai défi",
          "L'architecture inclut gateway, routeur, cache, fallback et observabilite",
          "Le streaming réduit la latence percue de 10x",
          "Le cache sémantique réduit les coûts de 40-60%",
          "Les guardrails (validation, détection, circuit breaker) sont essentiels en production",
        ]},
      ],
      quiz: [
        {
          question: "Quel pourcentage des projets IA reste au stade de prototype ?",
          options: ["20%", "40%", "60%", "80%"],
          correctIndex: 3,
          explanation: "80% des projets IA restent au stade de prototype, faute de gestion des coûts, de monitoring, de guardrails et de conformite réglementaire.",
        },
        {
          question: "De combien le cache sémantique peut-il réduire les coûts ?",
          options: ["10-20%", "20-30%", "40-60%", "90%"],
          correctIndex: 2,
          explanation: "Le cache sémantique retourné les réponses en cache pour les questions similaires, reduisant les coûts d'API de 40 à 60%.",
        },
        {
          question: "Pourquoi le streaming est-il incontournable en production ?",
          options: ["Il réduit les coûts", "Il réduit la latence percue de 10x", "Il améliore la qualité", "Il sécurisé les données"],
          correctIndex: 1,
          explanation: "Le streaming permet à l'utilisateur de voir la réponse se construire en temps réel, reduisant la latence percue de 10x au lieu d'attendre la réponse complète.",
        },
        {
          question: "Qu'est-ce qu'un circuit breaker dans le contexte IA ?",
          options: ["Un composant électrique", "Un système qui arrête les appels si le taux d'erreur explose", "Un outil de debug", "Un type de cache"],
          correctIndex: 1,
          explanation: "Le circuit breaker arrête automatiquement les appels au provider IA si le taux d'erreur depasse un seuil, empechant une cascade de défaillances et des coûts incontroles.",
        },
      ],
    },
    {
      number: 14,
      title: "Couts et Optimisation",
      description: "Réduire les coûts de vos applications IA sans compromettre la qualité.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Maîtriser les Couts de l'IA" },
        { type: "paragraph", content: "Les coûts des APIs IA peuvent exploser rapidement : un chatbot avec 100 000 utilisateurs actifs peut coûter des dizaines de milliers de dollars par mois. L'optimisation des coûts est une compétence essentielle pour rendre un produit IA viable economiquement." },
        { type: "paragraph", content: "La bonne nouvelle : les coûts ont chute de 90% en deux ans, et les techniques d'optimisation permettent de réduire encore de 70-80% sans perte de qualité. Le secret est de combiner plusieurs stratégies." },
        { type: "subheading", content: "Stratégie 1 : Routing Intelligent" },
        { type: "paragraph", content: "Dirigez les requêtes simples (classification, extraction, reformulation) vers des modèles économiques (Haiku, GPT-4o-mini, Gemini Flash) et reservez les modèles premium (Opus, GPT-5.4) pour les tâches complexes. Un classificateur de complexité en première étape route automatiquement." },
        { type: "subheading", content: "Stratégie 2 : Prompt Caching et Batching" },
        { type: "paragraph", content: "Le prompt caching Anthropic réduit le coût des parties statiques de 90%. Le batching OpenAI et Anthropic offre 50% de réduction pour les traitements non urgents. Combinez les deux pour des réductions massives sur les pipelines de traitement." },
        { type: "callout", content: "Exemple réel : une startup traitant 50 000 documents/jour est passée de $8 000/mois a $1 200/mois en combinant routing intelligent + prompt caching + batching — sans perte de qualité." },
        { type: "video", videoId: { fr: "UoBVumRnyds", en: "kCc8FmEb1nY" },
      videoDurationMinutes: 116, label: "Optimiser les coûts IA" },
        { type: "subheading", content: "Stratégie 3 : Modèles Open Source" },
        { type: "paragraph", content: "Pour les tâches spécifiques, un modèle open source fine-tune (Llama 3.3, Qwen 3.5, Mistral) peut rivaliser avec les modèles propriétaires a une fraction du coût. L'hébergement sur GPU cloud (RunPod, Together AI) revient a $0.10-0.30/heure pour un modèle 7B." },
        { type: "key-point", content: "Le monitoring des coûts en temps réel est non negociable. Configurez des alertes de budget quotidien/mensuel. Un bug de boucle infinie sur l'API peut coûter des milliers de dollars en minutes." },
        { type: "diagram", label: "Strategies d'Optimisation des Couts", flow: "vertical", nodes: [
          { label: "Routing intelligent", sub: "Modèle adapté à la complexité, -70%", color: "blue" },
          { label: "Prompt caching", sub: "Parties statiques cachées, -90%", color: "purple" },
          { label: "Batching", sub: "Traitements groupes, -50%", color: "emerald" },
          { label: "Modèles open source", sub: "Fine-tuning local, coût minimal", color: "amber" },
        ]},
        { type: "summary", items: [
          "Les coûts IA ont chute de 90% en 2 ans et sont optimisables de 70-80%",
          "Le routing intelligent dirige les tâches vers le modèle le moins couteux suffisant",
          "Le prompt caching Anthropic réduit les parties statiques de 90%",
          "Le batching offre 50% de réduction pour les traitements non urgents",
          "Configurez des alertes de budget — les boucles infinies coûtent cher",
        ]},
      ],
      quiz: [
        {
          question: "De combien le prompt caching Anthropic réduit-il les coûts ?",
          options: ["30%", "50%", "70%", "90%"],
          correctIndex: 3,
          explanation: "Le prompt caching Anthropic réduit de 90% le coût des parties statiques du prompt (system prompt, exemples), un avantage considerable pour les applications avec des prompts longs.",
        },
        {
          question: "Quelle est la première stratégie d'optimisation des coûts ?",
          options: ["Utiliser moins l'IA", "Le routing intelligent vers le modèle adapte", "Compresser les prompts", "Limiter les utilisateurs"],
          correctIndex: 1,
          explanation: "Le routing intelligent dirige chaque requête vers le modèle le moins couteux capable de la traiter, evitant de sur-utiliser les modèles premium pour des tâches simples.",
        },
        {
          question: "Combien coûte l'hébergement d'un modèle open source 7B sur GPU cloud ?",
          options: ["$10-30/heure", "$1-5/heure", "$0.10-0.30/heure", "Gratuit"],
          correctIndex: 2,
          explanation: "L'hébergement d'un modèle 7B sur GPU cloud (RunPod, Together AI) revient a environ $0.10-0.30/heure, rendant les modèles open source très économiques.",
        },
        {
          question: "Pourquoi les alertes de budget sont-elles essentielles ?",
          options: ["Pour impressionner le management", "Un bug de boucle infinie peut coûter des milliers de dollars en minutes", "Pour surveiller les concurrents", "Pour le reporting trimestriel"],
          correctIndex: 1,
          explanation: "Un bug de boucle infinie sur l'API IA peut générer des milliers de requêtes en quelques minutes, coutant potentiellement des milliers de dollars. Les alertes permettent de détecter et stopper rapidement.",
        },
      ],
    },
    {
      number: 15,
      title: "Construire un Produit IA",
      description: "De l'idée au lancement : construire un produit IA complet et viable.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "De l'Idée au Produit IA" },
        { type: "paragraph", content: "Construire un produit IA viable est différent de construire un prototype. Il faut penser expérience utilisateur, valeur métier, modèle économique, fiabilité, et scalabilite des le depart. Ce chapitre synthetise tout le cours en un framework actionnable pour lancer votre produit IA." },
        { type: "subheading", content: "Identifier le Bon Problème" },
        { type: "paragraph", content: "Le piege #1 est de construire une solution IA en cherchant un problème. Partez du problème : quel processus est lent, couteux, ou pénible ? L'IA est un accélérateur, pas une fin en soi. Les meilleurs produits IA resolvent un problème réel de manière 10x meilleure que les alternatives." },
        { type: "subheading", content: "MVP IA en 2 Semaines" },
        { type: "paragraph", content: "Semaine 1 : définir le cas d'usage, choisir l'API provider, construire le pipeline (prompt + RAG si besoin), créer l'interface minimal. Semaine 2 : ajouter les guardrails, tester avec des utilisateurs beta, mesurer la qualité, iterer. Lancez en 2 semaines, pas en 6 mois." },
        { type: "callout", content: "Les produits IA les plus réussis en 2026 ne sont pas ceux avec la meilleure technologie, mais ceux avec la meilleure expérience utilisateur. L'UX prime sur le modèle. Un GPT-4o-mini avec une excellente UX bat un Opus avec une mauvaise UX." },
        { type: "video", videoId: "bZQun8Y4L2A",
      videoDurationMinutes: 43, label: "Construire un produit IA" },
        { type: "heading", content: "Stack Recommandee en 2026" },
        { type: "paragraph", content: "Frontend : Next.js + Vercel AI SDK pour le streaming. Backend : API routes + base vectorielle (pgvector). LLM : Claude Sonnet (équilibre qualité/coût) avec fallback GPT-4o. RAG : LlamaIndex pour l'indexation. Monitoring : Langfuse. Déploiement : Vercel ou Railway." },
        { type: "key-point", content: "Le moat (avantage concurrentiel) d'un produit IA n'est pas le modèle — tout le monde utilise les mêmes APIs. Le moat est dans les données propriétaires, l'UX, le workflow spécifique, et la base utilisateurs. Construisez autour de ces piliers." },
        { type: "diagram", label: "Framework de Lancement Produit IA", flow: "vertical", nodes: [
          { label: "Problème", sub: "Identifier un problème réel 10x", color: "pink" },
          { label: "MVP 2 semaines", sub: "API + RAG + UI minimale", color: "blue" },
          { label: "Validation", sub: "Beta users, métriques, iteration", color: "purple" },
          { label: "Scaling", sub: "Optimisation coûts, monitoring, UX", color: "emerald" },
        ]},
        { type: "prompt-example", prompt: "Tu es un consultant produit IA. J'ai une base de 10 000 PDF de contrats juridiques. Propose 3 produits IA viables avec estimation de marche, stack technique, et plan de lancement en 4 semaines.", result: "1) Analyseur de clauses a risque (ciblé: directions juridiques, RAG + Claude). 2) Extracteur de données contractuelles (ciblé: légal ops, OCR multimodal + structured output). 3) Assistant de rédaction contractuelle (ciblé: avocats, fine-tuning + RAG)." },
        { type: "summary", items: [
          "Partez du problème, pas de la technologie — l'IA est un accélérateur",
          "Lancez un MVP en 2 semaines, pas en 6 mois",
          "L'UX prime sur le modèle — une bonne expérience bat un meilleur modèle",
          "Le moat est dans les données, l'UX et le workflow, pas dans le modèle",
          "Stack 2026 : Next.js + Vercel AI SDK + Claude + pgvector + Langfuse",
        ]},
      ],
      quiz: [
        {
          question: "Quel est le piege #1 en construction de produit IA ?",
          options: ["Choisir le mauvais modèle", "Construire une solution IA en cherchant un problème", "Ne pas utiliser assez de données", "Lancer trop vite"],
          correctIndex: 1,
          explanation: "Le piege #1 est de partir de la technologie IA et chercher un problème a résoudre, au lieu de partir d'un problème réel et d'utiliser l'IA comme accélérateur.",
        },
        {
          question: "En combien de temps doit-on lancer un MVP IA ?",
          options: ["2 jours", "2 semaines", "2 mois", "6 mois"],
          correctIndex: 1,
          explanation: "Un MVP IA doit être lance en 2 semaines : semaine 1 pour le pipeline technique, semaine 2 pour les guardrails, tests beta et iterations.",
        },
        {
          question: "Quel est le vrai avantage concurrentiel (moat) d'un produit IA ?",
          options: ["Le modèle IA utilise", "La puissance de calcul", "Les données propriétaires, l'UX et le workflow", "Le nombre de paramètres"],
          correctIndex: 2,
          explanation: "Le moat n'est pas dans le modèle (tout le monde utilise les mêmes APIs) mais dans les données propriétaires, l'expérience utilisateur, le workflow spécifique et la base utilisateurs.",
        },
        {
          question: "Qu'est-ce qui prime dans un produit IA réussi ?",
          options: ["La taille du modèle", "L'expérience utilisateur", "Le nombre de features", "Le prix le plus bas"],
          correctIndex: 1,
          explanation: "Les produits IA les plus réussis en 2026 sont ceux avec la meilleure expérience utilisateur. Un modèle plus petit avec une excellente UX bat un modèle plus gros avec une mauvaise UX.",
        },
      ],
    },
  ],
};

export default content;
