import type { CourseContent } from "../types";

const content: CourseContent = {
  slug: "ia-marketing-digital",
  chapters: [
    {
      number: 1,
      title: "Introduction au Marketing Digital IA",
      description: "Comprendre comment l'IA révolutionné le marketing digital en 2026.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Le Marketing Digital à l'Ère de l'IA" },
        { type: "paragraph", content: "Le marketing digital a connu plus de changements en 2 ans qu'en 20 ans. L'IA ne se contente pas d'optimiser les campagnes existantes — elle reinvente complètement la manière dont les marques attirent, engagent et convertissent leurs audiences." },
        { type: "paragraph", content: "En 2026, les marketeurs qui n'utilisent pas l'IA sont déjà en retard. Les outils IA permettent de produire du contenu 10x plus vite, de cibler les audiences avec une précision chirurgicale, et d'optimiser les campagnes en temps réel grâce à l'analyse prédictive." },
        { type: "callout", content: "Selon HubSpot, 87% des marketeurs utilisent l'IA dans au moins une partie de leur workflow en 2026. Les équipes augmentées par l'IA generent en moyenne 40% de leads en plus." },
        { type: "video", videoId: "nkuPUJVzB_E",
      videoDurationMinutes: 12, label: "L'IA dans le marketing digital en 2026" },
        { type: "heading", content: "Les Piliers du Marketing Digital IA" },
        { type: "paragraph", content: "Le marketing digital IA repose sur 5 piliers : la création de contenu (texte, image, video), l'optimisation SEO, le ciblage publicitaire, l'analyse de données, et la personnalisation a grande échelle. Chacun de ces piliers est transformé par l'IA." },
        { type: "subheading", content: "Le Paradigme a Change" },
        { type: "paragraph", content: "Avant l'IA : un marketeur passait 80% de son temps sur l'exécution (créer des visuels, rédiger des posts, analyser des données). Avec l'IA : 80% du temps est consacre a la stratégie, la créativité et la relation client. L'exécution est largement automatisée." },
        { type: "key-point", content: "L'IA est un multiplicateur de force. Un marketeur seul avec les bons outils IA peut produire autant qu'une équipe de 5 personnes en 2020. Mais la stratégie et la créativité humaine restent irremplacables." },
        { type: "diagram", label: "Les 5 Piliers du Marketing Digital IA", flow: "horizontal", nodes: [
          { label: "Contenu", sub: "Texte, image, video IA", color: "purple" },
          { label: "SEO", sub: "Optimisation automatisée", color: "blue" },
          { label: "Publicité", sub: "Ciblage et optimisation IA", color: "emerald" },
          { label: "Analytics", sub: "Analyse prédictive", color: "amber" },
          { label: "Personnalisation", sub: "Expérience sur-mesure", color: "pink" },
        ]},
        { type: "tip", content: "Ce cours est structure pour être actionnable : chaque chapitre vous donne des outils et des techniques que vous pouvez appliquer immédiatement à votre activité." },
        { type: "summary", items: [
          "L'IA révolutionné les 5 piliers du marketing digital",
          "87% des marketeurs utilisent déjà l'IA en 2026",
          "Un marketeur + IA = la productivité d'une équipe de 5 personnes",
          "Le temps passe sur l'exécution diminue, celui sur la stratégie augmente",
          "La créativité et la stratégie humaine restent irremplacables",
        ]},
      ],
      quiz: [
        {
          question: "Quel pourcentage de marketeurs utilise l'IA en 2026 ?",
          options: ["45%", "62%", "87%", "95%"],
          correctIndex: 2,
          explanation: "Selon HubSpot, 87% des marketeurs utilisent l'IA dans au moins une partie de leur workflow en 2026.",
        },
        {
          question: "Combien de piliers composent le marketing digital IA ?",
          options: ["3", "4", "5", "7"],
          correctIndex: 2,
          explanation: "Le marketing digital IA repose sur 5 piliers : contenu, SEO, publicité, analytics et personnalisation.",
        },
        {
          question: "Comment l'IA changé-t-elle la repartition du temps des marketeurs ?",
          options: ["Plus de temps sur l'exécution", "Plus de temps sur la stratégie et la créativité", "Aucun changement", "Plus de temps sur la formation"],
          correctIndex: 1,
          explanation: "L'IA automatise l'exécution, liberant 80% du temps pour la stratégie, la créativité et la relation client — les tâches a haute valeur ajoutée.",
        },
        {
          question: "Quelle affirmation est FAUSSE concernant l'IA en marketing ?",
          options: ["L'IA accélère la création de contenu", "L'IA remplace complètement la créativité humaine", "L'IA optimise le ciblage publicitaire", "L'IA analyse les données en temps réel"],
          correctIndex: 1,
          explanation: "L'IA ne remplace pas la créativité humaine — elle amplifie les capacités du marketeur mais la stratégie et la vision restent irremplacables.",
        },
      ],
    },
    {
      number: 2,
      title: "SEO et IA : Dominer les Moteurs de Recherche",
      description: "Utiliser l'IA pour optimiser votre référencement et surpasser la concurrence.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Le SEO à l'Ère de l'IA" },
        { type: "paragraph", content: "Le SEO en 2026 n'est plus celui de 2020. Google utilise massivement l'IA (Gemini) dans son algorithme de recherche. Les AI Overviews répondent directement aux questions des utilisateurs. Pour rester visible, votre stratégie SEO doit intégrer l'IA à chaque étape." },
        { type: "paragraph", content: "L'IA transforme le SEO des deux côtés : les moteurs de recherche l'utilisent pour mieux comprendre le contenu, et les marketeurs l'utilisent pour créer du contenu mieux optimisé. C'est une course à l'armement ou l'IA est votre meilleure arme." },
        { type: "heading", content: "Recherche de Mots-Clés avec l'IA" },
        { type: "paragraph", content: "Les outils IA analysent les intentions de recherche, pas seulement les volumes. Ils identifient les questions que posent vraiment vos ciblés, les sujets connexes, et les opportunités de long-tail keywords sous-exploites par vos concurrents." },
        { type: "subheading", content: "Outils de Recherche IA" },
        { type: "paragraph", content: "Semrush AI, Ahrefs Content Grader, Surfer SEO, et Claude/GPT pour l'analyse sémantique avancée. Combinez ces outils pour une recherche de mots-clés exhaustive et stratégique." },
        { type: "video", videoId: "oeli5xkFZJo",
      videoDurationMinutes: 14, label: "SEO et IA : stratégies avancées 2026" },
        { type: "heading", content: "Rédaction SEO Augmentee par l'IA" },
        { type: "paragraph", content: "L'IA rédigé des articles optimises pour le SEO : structure H1-H6, densite de mots-clés naturelle, maillage interne, meta-descriptions, et rich snippets. Mais attention : Google détecte le contenu 100% IA sans valeur ajoutée. La touche humaine reste essentielle." },
        { type: "callout", content: "Google a confirme en 2025 que le contenu généré par l'IA n'est pas penalise en soi. C'est la qualité et l'utilité du contenu qui comptent, pas la méthode de création. Ajoutez toujours de l'expertise et de l'expérience personnelle." },
        { type: "prompt-example", prompt: "Analyse la SERP Google pour le mot-clé 'automatisation marketing IA'. Identifie les top 5 articles, leurs points forts et faiblesses, et propose un plan d'article qui les surpasse en profondeur et en valeur.", result: "Analyse des 5 premiers résultats avec scores de contenu, gaps identifiés, et un plan d'article en 8 sections couvrant les angles manquants avec des données fraîches et des exemples concrets." },
        { type: "key-point", content: "Le framework E-E-A-T (Expérience, Expertise, Authoritativeness, Trustworthiness) de Google est plus important que jamais. L'IA vous aide à produire, mais c'est votre expertise qui fait la différence dans le ranking." },
        { type: "diagram", label: "Pipeline SEO Augmente par l'IA", flow: "horizontal", nodes: [
          { label: "Recherche mots-clés", sub: "IA + Semrush, intentions", color: "blue" },
          { label: "Rédaction IA", sub: "Structure, optimisation", color: "purple" },
          { label: "Expertise humaine", sub: "E-E-A-T, expérience", color: "emerald" },
          { label: "Analyse résultats", sub: "Ranking, trafic, conversions", color: "amber" },
        ]},
        { type: "summary", items: [
          "Google utilise l'IA (Gemini) dans son algorithme — adaptez votre stratégie",
          "L'IA analyse les intentions de recherche, pas seulement les volumes",
          "Outils clés : Semrush AI, Ahrefs, Surfer SEO, Claude/GPT",
          "Le contenu IA n'est pas penalise, mais l'expertise humaine est indispensable",
          "E-E-A-T : Expérience, Expertise, Authoritativeness, Trustworthiness",
        ]},
      ],
      quiz: [
        {
          question: "Que sont les AI Overviews de Google ?",
          options: ["Un outil SEO payant", "Des réponses IA directement dans les résultats de recherche", "Un algorithme de penalite", "Un format de publicité"],
          correctIndex: 1,
          explanation: "Les AI Overviews sont des réponses générées par l'IA de Google (Gemini) qui apparaissent directement en haut des résultats de recherche.",
        },
        {
          question: "Google penalise-t-il le contenu généré par l'IA ?",
          options: ["Oui, tout contenu IA est penalise", "Non, c'est la qualité et l'utilité qui comptent", "Seulement si c'est du texte long", "Seulement pour les sites de moins de 1000 pages"],
          correctIndex: 1,
          explanation: "Google a confirme que le contenu IA n'est pas penalise en soi. C'est la qualité, l'utilité et l'expertise du contenu qui determinent le ranking.",
        },
        {
          question: "Que signifie E-E-A-T ?",
          options: ["Easy, Efficient, Automatic, Technical", "Expérience, Expertise, Authoritativeness, Trustworthiness", "Engagement, Éducation, Awareness, Traffic", "Export, Edit, Analyze, Track"],
          correctIndex: 1,
          explanation: "E-E-A-T (Expérience, Expertise, Authoritativeness, Trustworthiness) est le framework de Google pour évaluer la qualité du contenu.",
        },
        {
          question: "Quel outil est recommandé pour la recherche de mots-clés IA ?",
          options: ["Canva", "Semrush AI", "Slack", "Zoom"],
          correctIndex: 1,
          explanation: "Semrush AI est un outil de référence pour la recherche de mots-clés augmentée par l'IA, avec analyse des intentions et des opportunités.",
        },
      ],
    },
    {
      number: 3,
      title: "Content Marketing Augmente par l'IA",
      description: "Créer une stratégie de contenu performante avec l'IA : articles, vidéos, infographies.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Le Content Marketing Propulse par l'IA" },
        { type: "paragraph", content: "Le content marketing est le pilier de toute stratégie digitale. En 2026, l'IA permet de produire du contenu a une échelle et une vitesse inimaginables il y a 3 ans, tout en maintenant une qualité editoriale élevée." },
        { type: "paragraph", content: "Un article de blog, 3 posts LinkedIn, 5 tweets, une newsletter et une infographie — ce qui prenait une semaine a une équipe de contenu peut désormais être produit en quelques heures avec le bon workflow IA." },
        { type: "heading", content: "Stratégie de Contenu IA" },
        { type: "subheading", content: "Le Content Repurposing" },
        { type: "paragraph", content: "La technique la plus puissante : créer un contenu pilier (article long, video, podcast) et laisser l'IA le décliner en dizaines de formats. Un article de 2000 mots devient 10 posts LinkedIn, 20 tweets, 5 réels scripts, et une newsletter — automatiquement." },
        { type: "subheading", content: "La Rédaction Assistee" },
        { type: "paragraph", content: "L'IA ne remplace pas le rédacteur — elle l'amplifie. Le workflow optimal : vous definissez l'angle et les points clés, l'IA rédigé le premier jet, vous ajoutez votre expertise et votre voix, l'IA optimise pour le SEO et la lisibilite." },
        { type: "video", videoId: "_ZvnD73m40o",
      videoDurationMinutes: 42, label: "Content marketing IA : workflow complet" },
        { type: "callout", content: "Le contenu le plus performant en 2026 combiné l'expertise humaine et l'efficacité de l'IA. Les articles qui rankent le mieux sont ceux qui apportent une expérience et une perspective uniques, impossibles a générer par l'IA seule." },
        { type: "prompt-example", prompt: "Tu es un expert en marketing digital. Transforme cet article de 2000 mots sur le SEO en : 1) 3 posts LinkedIn engageants, 2) 5 tweets avec hooks, 3) Un script de Réel de 60 secondes, 4) Un email newsletter de 300 mots.", result: "3 posts LinkedIn avec hooks percutants et CTA, 5 tweets avec chiffres et questions, un script Réel structure (hook-contenu-CTA), et un email newsletter conversationnel avec un lien vers l'article." },
        { type: "diagram", label: "Le Content Repurposing IA", flow: "vertical", nodes: [
          { label: "Contenu Pilier", sub: "Article long, video, podcast", color: "purple" },
          { label: "Declinaison IA", sub: "Posts, tweets, réels, emails", color: "blue" },
          { label: "Optimisation", sub: "SEO, hashtags, CTA adaptes", color: "emerald" },
          { label: "Publication", sub: "Multi-plateforme automatisée", color: "amber" },
        ]},
        { type: "tip", content: "Creez une banque de prompts pour chaque type de contenu. Un bon prompt de declinaison LinkedIn est reutilisable des centaines de fois avec différents articles sources." },
        { type: "summary", items: [
          "Le content repurposing transformé 1 contenu en dizaines de formats",
          "Workflow optimal : angle humain → premier jet IA → révision → optimisation",
          "L'expertise et la perspective humaine font la différence",
          "Creez une banque de prompts reutilisables pour chaque format",
          "Automatisez la publication multi-plateforme",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que le content repurposing ?",
          options: ["Supprimer du vieux contenu", "Decliner un contenu pilier en multiples formats", "Copier le contenu des concurrents", "Traduire du contenu en anglais"],
          correctIndex: 1,
          explanation: "Le content repurposing consiste à prendre un contenu pilier et a le décliner automatiquement en multiples formats adaptés à chaque plateforme.",
        },
        {
          question: "Quel est le workflow optimal de rédaction avec l'IA ?",
          options: ["L'IA écrit tout, on publié directement", "On écrit tout, l'IA corrige l'orthographe", "Angle humain → premier jet IA → révision → optimisation", "On copie des articles existants"],
          correctIndex: 2,
          explanation: "Le workflow optimal combiné la vision stratégique humaine avec la rapidité de l'IA : l'humain definit l'angle, l'IA rédigé, l'humain révisé, l'IA optimisé.",
        },
        {
          question: "Combien de posts LinkedIn peut-on générer à partir d'un article de 2000 mots ?",
          options: ["1-2", "3-5", "10+", "Ce n'est pas possible"],
          correctIndex: 2,
          explanation: "Un article de 2000 mots contient suffisamment de matière pour générer 10 ou plus posts LinkedIn, chacun mettant en avant un angle ou un point clé différent.",
        },
        {
          question: "Pourquoi créer une banque de prompts ?",
          options: ["Pour les revendre", "Pour reutiliser des prompts optimises avec différents contenus sources", "Pour remplacer l'IA", "Pour le SEO"],
          correctIndex: 1,
          explanation: "Une banque de prompts permet de reutiliser des prompts optimises et testés avec différents contenus sources, garantissant une qualité constante.",
        },
      ],
    },
    {
      number: 4,
      title: "Réseaux Sociaux et IA",
      description: "Optimiser votre présence sur les réseaux sociaux grâce à l'IA : contenu, timing, engagement.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Les Réseaux Sociaux Augmentes par l'IA" },
        { type: "paragraph", content: "Les réseaux sociaux en 2026 sont un terrain de jeu idéal pour l'IA. De la création de contenu au choix du moment de publication, en passant par l'analyse de l'engagement et la gestion des communautés, l'IA intervient à chaque étape." },
        { type: "paragraph", content: "Les plateformes elles-mêmes utilisent massivement l'IA : algorithmes de recommandation, détection de contenu inapproprie, outils de création intègres. Comprendre comment fonctionne l'IA des plateformes est essentiel pour maximiser votre visibilité." },
        { type: "heading", content: "Création de Contenu Social IA" },
        { type: "subheading", content: "Texte et Copy" },
        { type: "paragraph", content: "L'IA génère des hooks (accroches), des corps de texte engageants, des CTA (call-to-action) adaptés à chaque plateforme. Le secret : donner à l'IA votre voix de marque et des exemples de posts qui ont bien fonctionne." },
        { type: "subheading", content: "Visuels et Vidéos" },
        { type: "paragraph", content: "Midjourney et DALL-E pour les visuels. Canva AI pour les designs adaptes aux formats de chaque plateforme. Sora 2 et Runway pour les vidéos courtes. L'IA peut produire un mois de visuels en une journée." },
        { type: "video", videoId: "nkuPUJVzB_E",
      videoDurationMinutes: 12, label: "Stratégie réseaux sociaux avec l'IA" },
        { type: "heading", content: "Timing et Analyse" },
        { type: "paragraph", content: "L'IA analyse quand votre audience est la plus active, quels types de contenu generent le plus d'engagement, et quels hashtags augmentent la portée. Les outils comme Buffer AI et Hootsuite AI optimisent automatiquement le calendrier de publication." },
        { type: "callout", content: "L'algorithme de LinkedIn en 2026 favorise les contenus qui generent des commentaires significatifs. L'IA peut vous aider a créer des posts qui suscitent le débat et l'interaction, mais l'engagement authentique dans les commentaires reste humain." },
        { type: "diagram", label: "Workflow Social Média IA", flow: "horizontal", nodes: [
          { label: "Stratégie", sub: "Sujets, calendrier, objectifs", color: "purple" },
          { label: "Création IA", sub: "Texte + visuels + vidéos", color: "blue" },
          { label: "Publication auto", sub: "Timing optimal, multi-plateforme", color: "emerald" },
          { label: "Analyse IA", sub: "Engagement, portée, ROI", color: "amber" },
        ]},
        { type: "prompt-example", prompt: "Analyse mes 10 derniers posts LinkedIn. Identifie les patterns de ceux qui ont le plus d'engagement (likes, commentaires, partages). Genere 5 nouveaux posts qui reprennent ces patterns gagnants.", result: "Analyse avec scores d'engagement, identification des hooks efficaces (questions, chiffres, controverses), et 5 nouveaux posts reprenant les formats gagnants avec des sujets frais." },
        { type: "summary", items: [
          "L'IA optimise chaque étape du marketing social : création, timing, analyse",
          "Generez texte, visuels et vidéos avec les outils IA",
          "Les outils de scheduling IA optimisent le moment de publication",
          "Analysez les patterns d'engagement pour reproduire le succès",
          "L'engagement authentique dans les commentaires reste humain",
        ]},
      ],
      quiz: [
        {
          question: "Quel est le secret pour que l'IA crée du contenu social efficace ?",
          options: ["Utiliser le prompt le plus long possible", "Lui donner votre voix de marque et des exemples de posts performants", "Publier le plus possible", "Copier les concurrents"],
          correctIndex: 1,
          explanation: "L'IA crée du contenu social plus efficace quand vous lui fournissez votre voix de marque et des exemples de posts qui ont bien fonctionne dans le passe.",
        },
        {
          question: "Qu'optimisent les outils comme Buffer AI et Hootsuite AI ?",
          options: ["Le prix des abonnements", "Le calendrier et timing de publication", "La taille des images", "Le nombre de followers"],
          correctIndex: 1,
          explanation: "Buffer AI et Hootsuite AI analysent quand votre audience est active et optimisent automatiquement le calendrier de publication pour maximiser l'engagement.",
        },
        {
          question: "Que favorise l'algorithme LinkedIn en 2026 ?",
          options: ["Les posts avec beaucoup d'hashtags", "Les contenus qui generent des commentaires significatifs", "Les posts très longs", "Les publications a 8h du matin"],
          correctIndex: 1,
          explanation: "L'algorithme LinkedIn favorise les contenus qui generent des commentaires significatifs et des interactions, pas simplement des likes.",
        },
        {
          question: "Quelle tâche des réseaux sociaux doit rester humaine ?",
          options: ["La création de visuels", "L'engagement authentique dans les commentaires", "La planification du calendrier", "L'analyse des métriques"],
          correctIndex: 1,
          explanation: "L'engagement authentique dans les commentaires — répondre aux questions, participer aux discussions — reste une tâche ou l'humain fait la différence.",
        },
      ],
    },
    {
      number: 5,
      title: "Email Marketing Intelligent",
      description: "Transformer votre email marketing avec l'IA : segmentation, personnalisation, automatisation.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "L'Email Marketing Reinvente par l'IA" },
        { type: "paragraph", content: "L'email marketing reste le canal avec le meilleur ROI en 2026 : 36 euros de retour pour chaque euro investi. L'IA le rend encore plus puissant grâce à la segmentation intelligente, la personnalisation hyper-contextuelle et l'optimisation automatique." },
        { type: "paragraph", content: "Les outils comme Mailchimp AI, ActiveCampaign, Brevo (ex-Sendinblue) et Klaviyo integrent désormais l'IA nativement pour optimiser les objets, le contenu, le timing d'envoi et la segmentation." },
        { type: "heading", content: "Segmentation Intelligente" },
        { type: "paragraph", content: "L'IA va au-dela de la segmentation classique (age, localisation, achat). Elle identifie des micro-segments bases sur le comportement : les lecteurs assidus qui n'achetent pas, les clients a risque de churn, les ambassadeurs potentiels, les acheteurs saisonniers." },
        { type: "subheading", content: "Personnalisation Hyper-Contextuelle" },
        { type: "paragraph", content: "Chaque email peut être unique : l'objet, le contenu, les produits recommandés, le CTA, et même le moment d'envoi sont adaptés à chaque destinataire. L'IA génère des variantes personnalisées a grande échelle." },
        { type: "video", videoId: "oeli5xkFZJo",
      videoDurationMinutes: 14, label: "Email marketing IA : segmentation et personnalisation" },
        { type: "key-point", content: "L'objet de l'email détermine 80% du taux d'ouverture. L'IA peut générer et A/B tester des dizaines de variantes d'objets pour trouver celui qui performe le mieux pour chaque segment." },
        { type: "heading", content: "Sequences Automatisees" },
        { type: "paragraph", content: "Les séquences d'emails automatisees (onboarding, nurturing, reactivation, abandon de panier) sont les plus rentables. L'IA optimise chaque email de la séquence : contenu, timing, et décision de continuer ou d'arrêter la séquence selon le comportement du destinataire." },
        { type: "diagram", label: "Pipeline Email Marketing IA", flow: "horizontal", nodes: [
          { label: "Segmentation IA", sub: "Micro-segments comportementaux", color: "purple" },
          { label: "Personnalisation", sub: "Contenu unique par destinataire", color: "blue" },
          { label: "Optimisation", sub: "Objet, timing, CTA", color: "emerald" },
          { label: "Analyse", sub: "Taux d'ouverture, clics, conversions", color: "amber" },
        ]},
        { type: "prompt-example", prompt: "Cree 10 variantes d'objet d'email pour une promotion Black Friday sur une formation en marketing digital. Cible : freelances francophones, 25-40 ans. Objectif : maximiser le taux d'ouverture.", result: "10 variantes utilisant différentes techniques (urgence, curiosite, chiffres, personnalisation, question) avec des prédictions de performance basées sur les patterns qui fonctionnent pour ce segment." },
        { type: "tip", content: "Testez toujours au moins 3 variantes d'objet d'email. L'IA peut prédire la performance, mais seul le test réel avec votre audience donne des résultats fiables." },
        { type: "summary", items: [
          "L'email marketing reste le canal au meilleur ROI : 36x en 2026",
          "L'IA identifie des micro-segments comportementaux avances",
          "Personnalisation hyper-contextuelle a grande échelle",
          "L'objet détermine 80% du taux d'ouverture — testez avec l'IA",
          "Les séquences automatisees sont les plus rentables",
        ]},
      ],
      quiz: [
        {
          question: "Quel est le ROI moyen de l'email marketing en 2026 ?",
          options: ["5x", "12x", "36x", "50x"],
          correctIndex: 2,
          explanation: "L'email marketing offre un ROI de 36 euros pour chaque euro investi, ce qui en fait le canal marketing le plus rentable en 2026.",
        },
        {
          question: "Quel élément détermine 80% du taux d'ouverture d'un email ?",
          options: ["Le contenu", "L'objet (subject line)", "Les images", "Le CTA"],
          correctIndex: 1,
          explanation: "L'objet de l'email détermine 80% du taux d'ouverture. C'est la première chose que voit le destinataire et elle décide s'il ouvre ou non l'email.",
        },
        {
          question: "Qu'est-ce que la segmentation comportementale ?",
          options: ["Segmenter par age et localisation", "Segmenter par comportement (clics, achats, engagement)", "Segmenter par nom de famille", "Ne pas segmenter du tout"],
          correctIndex: 1,
          explanation: "La segmentation comportementale créé des groupes bases sur les actions des utilisateurs : clics, achats, fréquence de lecture, etc., au-dela des critères demographiques.",
        },
        {
          question: "Combien de variantes d'objet tester au minimum ?",
          options: ["1", "3", "10", "50"],
          correctIndex: 1,
          explanation: "Il est recommandé de tester au moins 3 variantes d'objet pour obtenir des résultats statistiquement significatifs avec votre audience.",
        },
      ],
    },
    {
      number: 6,
      title: "Publicité en Ligne avec l'IA (Google, Meta)",
      description: "Optimiser vos campagnes Google Ads et Meta Ads avec l'intelligence artificielle.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "La Publicité Digitale Augmentee par l'IA" },
        { type: "paragraph", content: "Google Ads et Meta Ads (Facebook, Instagram) utilisent déjà massivement l'IA dans leurs algorithmes de diffusion. Mais au-dela de l'IA des plateformes, vous pouvez utiliser vos propres outils IA pour créer de meilleurs visuels, rédiger des copies plus percutantes et optimiser vos budgets." },
        { type: "paragraph", content: "En 2026, les campagnes Performance Max de Google et Advantage+ de Meta sont pilotees par l'IA. Le rôle du marketeur évolue : moins de micro-gestion des encheres, plus de stratégie créative et de qualité des signaux." },
        { type: "heading", content: "Google Ads et l'IA" },
        { type: "subheading", content: "Performance Max" },
        { type: "paragraph", content: "Performance Max utilise l'IA de Google pour diffuser vos annonces sur tous les canaux Google (Search, Display, YouTube, Maps, Gmail). Vous fournissez les assets (textes, images, vidéos) et l'IA optimise la diffusion en temps réel." },
        { type: "paragraph", content: "L'IA génère même des variantes de vos annonces : combinaisons de titres et descriptions, adaptations visuelles, et ciblage d'audiences similaires à vos clients existants." },
        { type: "heading", content: "Meta Ads (Advantage+)" },
        { type: "subheading", content: "Advantage+ Shopping et Créative" },
        { type: "paragraph", content: "Advantage+ automatisé le ciblage, les placements et l'optimisation créative. Advantage+ Créative génère automatiquement des variantes de vos visuels adaptées à chaque audience. Le ROI des campagnes Advantage+ est en moyenne 30% supérieur aux campagnes manuelles." },
        { type: "video", videoId: "_ZvnD73m40o",
      videoDurationMinutes: 42, label: "Google Ads + Meta Ads : optimisation IA" },
        { type: "key-point", content: "En 2026, la qualité des créatives (visuels et textes) est le levier #1 de performance publicitaire. L'IA des plateformes optimisé la diffusion, mais c'est votre créative qui détermine si les gens cliquent." },
        { type: "diagram", label: "Publicité Digitale IA : Écosystème", flow: "horizontal", nodes: [
          { label: "Creatives IA", sub: "Visuels, textes, vidéos", color: "purple" },
          { label: "Google Performance Max", sub: "Tous canaux Google, auto-optimisé", color: "blue" },
          { label: "Meta Advantage+", sub: "Facebook, Instagram, auto-ciblage", color: "emerald" },
          { label: "Analyse IA", sub: "ROI, CPA, attribution", color: "amber" },
        ]},
        { type: "prompt-example", prompt: "Genere 5 variantes de texte publicitaire Google Ads pour une formation en ligne sur le marketing digital IA. Cible : entrepreneurs francophones. Limite : 30 caractères titre, 90 caractères description.", result: "5 variantes avec titres accrocheurs et descriptions percutantes, chacune exploitant un angle différent (ROI, gain de temps, concurrence, compétence, carrière) dans les limites de caractères." },
        { type: "callout", content: "Ne faites pas confiance aveuglement à l'IA des plateformes publicitaires. Elles optimisent pour leurs métriques (clics, impressions), pas nécessairement pour votre ROI réel. Suivez toujours vos conversions finales." },
        { type: "summary", items: [
          "Google Performance Max et Meta Advantage+ sont pilotes par l'IA",
          "La qualité des créatives est le levier #1 de performance",
          "L'IA des plateformes optimisé la diffusion, vous optimisez les créatives",
          "Advantage+ offre en moyenne 30% de ROI supérieur aux campagnes manuelles",
          "Suivez toujours vos conversions finales, pas seulement les métriques plateforme",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que Google Performance Max ?",
          options: ["Un type de serveur", "Une campagne IA qui diffuse sur tous les canaux Google", "Un outil de SEO", "Un plan tarifaire premium"],
          correctIndex: 1,
          explanation: "Performance Max est un type de campagne Google Ads qui utilise l'IA pour diffuser vos annonces sur tous les canaux Google (Search, Display, YouTube, Maps, Gmail).",
        },
        {
          question: "Quel est le levier #1 de performance publicitaire en 2026 ?",
          options: ["Le budget", "La qualité des créatives", "Le nombre de campagnes", "L'heure de diffusion"],
          correctIndex: 1,
          explanation: "La qualité des créatives (visuels et textes) est le principal levier de performance. L'IA optimise la diffusion, mais ce sont les créatives qui determinent les clics.",
        },
        {
          question: "Quel est l'avantage moyen de ROI des campagnes Advantage+ de Meta ?",
          options: ["10% supérieur", "30% supérieur", "50% supérieur", "100% supérieur"],
          correctIndex: 1,
          explanation: "Les campagnes Advantage+ de Meta offrent en moyenne 30% de ROI supérieur aux campagnes configurees manuellement, grâce à l'optimisation IA.",
        },
        {
          question: "Pourquoi ne pas faire confiance aveuglement aux métriques des plateformes ?",
          options: ["Elles sont toujours fausses", "Elles optimisent pour leurs métriques, pas votre ROI réel", "Elles sont trop complexes", "Elles changent chaque jour"],
          correctIndex: 1,
          explanation: "Les plateformes optimisent pour leurs propres métriques (clics, impressions). Votre ROI réel dépend des conversions finales, qui peuvent differer significativement.",
        },
      ],
    },
    {
      number: 7,
      title: "Landing Pages et Conversion",
      description: "Créer des landing pages a haute conversion grâce à l'IA : copy, design, A/B testing.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Landing Pages : L'Art de la Conversion" },
        { type: "paragraph", content: "Une landing page est la page ou atterrissent vos visiteurs après avoir clique sur une publicité ou un lien. Son unique objectif : convertir le visiteur en lead ou en client. L'IA transforme la création de landing pages en permettant de générer, tester et optimiser des dizaines de variantes rapidement." },
        { type: "paragraph", content: "En 2026, les outils comme Unbounce Smart Builder, Instapage AI et même v0/Bolt generent des landing pages complètes à partir d'une simple description. L'IA optimise ensuite chaque élément pour maximiser les conversions." },
        { type: "heading", content: "Les Éléments d'une Landing Page qui Convertit" },
        { type: "paragraph", content: "Les éléments clés : un headline percutant (bénéfice principal), un sous-titre clarifiant, une preuve sociale (temoignages, chiffres), un CTA visible et convaincant, et un formulaire simple. L'IA peut générer et tester chacun de ces éléments." },
        { type: "subheading", content: "Copywriting IA pour la Conversion" },
        { type: "paragraph", content: "Les frameworks de copywriting (AIDA, PAS, FAB) combinés à l'IA produisent des textes de vente redoutablement efficaces. AIDA : Attention, Intérêt, Désir, Action. PAS : Problème, Agitation, Solution. L'IA adapte ces frameworks à votre offre spécifique." },
        { type: "video", videoId: "nkuPUJVzB_E",
      videoDurationMinutes: 12, label: "Créer une landing page a haute conversion avec l'IA" },
        { type: "key-point", content: "Une landing page n'a qu'un seul objectif et un seul CTA. Si vous donnez trop de choix au visiteur, il ne fait rien. L'IA peut vous aider a simplifier et a focaliser votre message." },
        { type: "heading", content: "A/B Testing avec l'IA" },
        { type: "paragraph", content: "L'A/B testing IA va plus loin que le test classique : il peut tester des dizaines de variantes simultanement (multivariate testing), identifier le gagnant plus rapidement grâce au machine learning, et même adapter la page en temps réel selon le profil du visiteur." },
        { type: "callout", content: "Les tests montrent qu'un changement de headline peut augmenter les conversions de 30 à 50%. Ne sous-estimez jamais la puissance du texte — testez au moins 5 variantes de headline avec l'IA." },
        { type: "diagram", label: "Anatomie d'une Landing Page Optimisee", flow: "vertical", nodes: [
          { label: "Headline", sub: "Bénéfice principal, clair et percutant", color: "purple" },
          { label: "Preuve sociale", sub: "Temoignages, chiffres, logos", color: "blue" },
          { label: "Proposition de valeur", sub: "Pourquoi vous, pourquoi maintenant", color: "emerald" },
          { label: "CTA", sub: "Un seul bouton, action claire", color: "amber" },
        ]},
        { type: "prompt-example", prompt: "Genere 5 headlines pour une landing page de formation 'Marketing Digital IA'. Utilise le framework PAS (Problème, Agitation, Solution). Cible : entrepreneurs qui veulent plus de clients.", result: "5 headlines PAS : ex. 'Vos concurrents utilisent déjà l'IA pour voler vos clients — voici comment reprendre l'avantage en 30 jours', chacun avec un angle émotionnel différent." },
        { type: "summary", items: [
          "Une landing page a un seul objectif et un seul CTA",
          "Outils IA : Unbounce Smart Builder, Instapage AI, v0/Bolt",
          "Frameworks de copywriting : AIDA, PAS, FAB combinés à l'IA",
          "Un changement de headline peut augmenter les conversions de 30-50%",
          "L'A/B testing IA testé des dizaines de variantes simultanement",
        ]},
      ],
      quiz: [
        {
          question: "Quel est l'unique objectif d'une landing page ?",
          options: ["Informer le visiteur", "Convertir le visiteur en lead ou client", "Présenter toute l'entreprise", "Afficher un maximum de produits"],
          correctIndex: 1,
          explanation: "Une landing page a un seul objectif : convertir le visiteur (en lead, en client, en inscrit). Tout élément qui ne sert pas cet objectif est superflu.",
        },
        {
          question: "Que signifie PAS en copywriting ?",
          options: ["Prix, Avantage, Service", "Problème, Agitation, Solution", "Public, Action, Stratégie", "Performance, Analyse, Score"],
          correctIndex: 1,
          explanation: "PAS (Problème, Agitation, Solution) est un framework de copywriting qui identifie le problème du lecteur, amplifie la douleur, puis presente la solution.",
        },
        {
          question: "De combien un changement de headline peut-il augmenter les conversions ?",
          options: ["5-10%", "10-20%", "30-50%", "100-200%"],
          correctIndex: 2,
          explanation: "Les tests montrent qu'un changement de headline peut augmenter les conversions de 30 à 50%, ce qui en fait l'élément le plus impactant de la page.",
        },
        {
          question: "Qu'est-ce que le multivariate testing ?",
          options: ["Tester 2 versions d'une page", "Tester des dizaines de variantes simultanement", "Tester sur différents navigateurs", "Tester la vitesse de chargement"],
          correctIndex: 1,
          explanation: "Le multivariate testing testé des dizaines de combinaisons de variantes simultanement (headlines, images, CTA), bien au-dela du simple A/B classique.",
        },
      ],
    },
    {
      number: 8,
      title: "Analytics et Data Marketing",
      description: "Exploiter les données marketing avec l'IA : analyse prédictive, attribution, dashboards.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Le Data Marketing Propulse par l'IA" },
        { type: "paragraph", content: "Les données sont le carburant du marketing digital. Mais avoir des données ne suffit pas — il faut les analyser, les interpréter et en tirer des actions concrètes. L'IA transforme des montagnes de données en insights actionnables en quelques secondes." },
        { type: "paragraph", content: "En 2026, Google Analytics 4 intégré l'IA pour l'analyse prédictive. Les outils comme Looker Studio AI, Mixpanel et Amplitude offrent des insights automatiques. Et Claude/GPT peuvent analyser vos exports CSV pour répondre a n'importe quelle question marketing." },
        { type: "heading", content: "Les KPIs Essentiels" },
        { type: "paragraph", content: "Les métriques qui comptent vraiment : le coût d'acquisition client (CAC), la valeur vie client (LTV), le taux de conversion par étape du funnel, le ROI par canal, et le taux de churn. L'IA peut calculer et prédire chacune de ces métriques." },
        { type: "subheading", content: "Analyse Predictive" },
        { type: "paragraph", content: "L'analyse prédictive utilise le machine learning pour anticiper les comportements : qui va acheter ? Qui risque de se desabonner ? Quel canal va performer le mieux le mois prochain ? Ces prédictions permettent d'agir avant que les problèmes ne surviennent." },
        { type: "video", videoId: "oeli5xkFZJo",
      videoDurationMinutes: 14, label: "Analytics marketing IA : de la donnée à l'action" },
        { type: "heading", content: "Attribution Multi-Touch" },
        { type: "paragraph", content: "L'attribution détermine quel canal marketing merite le credit d'une conversion. Un client voit une pub Instagram, clique sur un email, puis acheté via Google — quel canal a vendu ? L'IA calcule l'attribution multi-touch avec des modèles data-driven plus précis que les règles manuelles." },
        { type: "callout", content: "L'ère des cookies tiers est terminee. L'attribution IA basée sur les données first-party (vos propres données) devient indispensable. Investissez dans la collecte de données propriétaires." },
        { type: "diagram", label: "Pipeline Data Marketing IA", flow: "horizontal", nodes: [
          { label: "Collecte", sub: "GA4, CRM, email, social", color: "blue" },
          { label: "Analyse IA", sub: "Patterns, anomalies, trends", color: "purple" },
          { label: "Prédiction", sub: "Comportements futurs", color: "emerald" },
          { label: "Action", sub: "Decisions basées sur les données", color: "amber" },
        ]},
        { type: "prompt-example", prompt: "Voici un export CSV de mes campagnes marketing des 6 derniers mois (canal, dépense, leads, clients, CA). Analyse les performances, identifié le canal le plus rentable et recommande une reallocation budgetaire.", result: "Analyse complète avec ROI par canal, identification du canal le plus rentable (ex: email 12x ROI vs paid social 3x), et recommandation de reallouer 30% du budget paid social vers email et SEO." },
        { type: "key-point", content: "Le ratio LTV/CAC est le KPI ultime. Si la valeur vie client est 3x ou plus supérieure au coût d'acquisition, votre business est sain. L'IA peut calculer ce ratio en temps réel pour chaque canal." },
        { type: "summary", items: [
          "L'IA transforme les données marketing en insights actionnables",
          "KPIs essentiels : CAC, LTV, taux de conversion, ROI par canal, churn",
          "L'analyse prédictive anticipe les comportements clients",
          "L'attribution multi-touch IA est plus précise que les règles manuelles",
          "LTV/CAC > 3x = business sain — calculez par canal avec l'IA",
        ]},
      ],
      quiz: [
        {
          question: "Que signifie CAC en marketing ?",
          options: ["Content Automation Campaign", "Coût d'Acquisition Client", "Click Average Cost", "Campaign Analysis Chart"],
          correctIndex: 1,
          explanation: "CAC (Coût d'Acquisition Client) est le coût total pour acquerir un nouveau client, incluant toutes les dépenses marketing et commerciales.",
        },
        {
          question: "Quel ratio LTV/CAC indique un business sain ?",
          options: ["LTV/CAC > 1x", "LTV/CAC > 2x", "LTV/CAC > 3x", "LTV/CAC > 10x"],
          correctIndex: 2,
          explanation: "Un ratio LTV/CAC supérieur a 3x est considéré comme sain : la valeur générée par un client est au moins 3 fois supérieure a son coût d'acquisition.",
        },
        {
          question: "Qu'est-ce que l'attribution multi-touch ?",
          options: ["Mesurer les clics sur plusieurs écrans", "Déterminer quel canal merite le credit d'une conversion", "Analyser les touches sur un téléphone", "Compter le nombre d'interactions"],
          correctIndex: 1,
          explanation: "L'attribution multi-touch détermine la contribution de chaque point de contact (pub, email, organic) dans le parcours qui mene a une conversion.",
        },
        {
          question: "Pourquoi les données first-party sont-elles devenues essentielles ?",
          options: ["Elles sont gratuites", "L'ère des cookies tiers est terminee", "Elles sont plus belles", "Google les exige"],
          correctIndex: 1,
          explanation: "Avec la fin des cookies tiers, les données first-party (collectées directement auprès de vos utilisateurs) sont devenues indispensables pour l'attribution et le ciblage.",
        },
      ],
    },
    {
      number: 9,
      title: "Personal Branding avec l'IA",
      description: "Construire et amplifier votre marque personnelle grâce à l'IA.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Le Personal Branding Augmente par l'IA" },
        { type: "paragraph", content: "En 2026, votre marque personnelle est votre actif le plus précieux. Les gens achetent a des personnes, pas à des entreprises. L'IA vous aide à construire, amplifier et maintenir votre personal brand a une échelle impossible manuellement." },
        { type: "paragraph", content: "L'IA n'est pas la pour créer un faux personnage — elle amplifie votre authenticite. Elle vous aide à articuler votre expertise, à produire du contenu régulièrement, et à être présent sur plusieurs plateformes sans y passer tout votre temps." },
        { type: "heading", content: "Définir votre Positionnement" },
        { type: "paragraph", content: "L'IA peut analyser votre secteur, identifier les niches sous-exploitees et vous aider a trouver votre positionnement unique. Votre personal brand doit répondre a 3 questions : Quelle est votre expertise ? Quelle est votre perspective unique ? Pour qui créez-vous de la valeur ?" },
        { type: "subheading", content: "Votre Voice of Brand" },
        { type: "paragraph", content: "Alimentez l'IA avec vos meilleurs contenus, vos emails, vos présentations. Elle apprend votre style, votre vocabulaire, vos tournures. Ensuite, elle peut produire du contenu qui sonne comme vous, pas comme un robot." },
        { type: "video", videoId: "_ZvnD73m40o",
      videoDurationMinutes: 42, label: "Construire son personal branding avec l'IA" },
        { type: "callout", content: "Le piege du personal branding IA : publier du contenu générique qui ressemble à tout le monde. Votre avantage competitif, c'est votre expérience vécue, vos échecs, vos opinions tranchees. L'IA amplifie votre voix, elle ne la remplace pas." },
        { type: "diagram", label: "Les 3 Piliers du Personal Brand", flow: "horizontal", nodes: [
          { label: "Expertise", sub: "Ce que vous savez faire", color: "purple" },
          { label: "Perspective", sub: "Votre vision unique", color: "blue" },
          { label: "Audience", sub: "Pour qui vous créez de la valeur", color: "emerald" },
        ]},
        { type: "tip", content: "Publiez au moins 3 fois par semaine sur votre plateforme principale (LinkedIn, Twitter/X). L'IA peut vous aider a préparer un mois de contenu en une seule session de 2 heures." },
        { type: "prompt-example", prompt: "Tu es mon ghostwriter. Voici 5 exemples de mes meilleurs posts LinkedIn. Analyse mon style, mon ton, mes thèmes recurrents. Puis génère 10 idées de posts et rédigé les 3 meilleurs en imitant mon style.", result: "Analyse de style (ton direct, anecdotes personnelles, chiffres concrets), 10 idées thematiques, et 3 posts complets avec hooks personnalisés, contenu de valeur et CTA naturels." },
        { type: "summary", items: [
          "Votre personal brand est votre actif le plus précieux en 2026",
          "3 piliers : expertise, perspective unique, audience ciblé",
          "L'IA apprend votre style pour produire du contenu authentique",
          "Le piege : le contenu générique — gardez vos opinions et expériences",
          "Publiez 3x/semaine minimum — preparez un mois en 2 heures avec l'IA",
        ]},
      ],
      quiz: [
        {
          question: "Quelles sont les 3 questions fondamentales du personal branding ?",
          options: ["Combien je gagne ? Ou je travaille ? Quel age ai-je ?", "Quelle expertise ? Quelle perspective ? Pour qui ?", "Quel outil ? Quel budget ? Quel résultat ?", "Quel réseau ? Quelle fréquence ? Quel format ?"],
          correctIndex: 1,
          explanation: "Les 3 questions clés : Quelle est votre expertise ? Quelle est votre perspective unique ? Pour qui créez-vous de la valeur ? Elles definissent votre positionnement.",
        },
        {
          question: "Quel est le piege du personal branding IA ?",
          options: ["Publier trop souvent", "Publier du contenu générique qui ressemble à tout le monde", "Ne pas utiliser assez d'IA", "Publier uniquement des images"],
          correctIndex: 1,
          explanation: "Le piege est de publier du contenu générique généré par l'IA sans y apporter votre expérience, vos opinions et votre perspective unique.",
        },
        {
          question: "Comment l'IA apprend-elle votre style de communication ?",
          options: ["Elle devine automatiquement", "Vous l'alimentez avec vos meilleurs contenus et emails", "Elle copie des influenceurs", "Elle lit votre CV"],
          correctIndex: 1,
          explanation: "En alimentant l'IA avec vos meilleurs contenus, emails et présentations, elle apprend votre style, vocabulaire et tournures pour produire du contenu qui sonne comme vous.",
        },
        {
          question: "Quelle fréquence de publication est recommandée ?",
          options: ["1 fois par mois", "1 fois par semaine", "3 fois par semaine minimum", "Chaque jour obligatoirement"],
          correctIndex: 2,
          explanation: "Publier au moins 3 fois par semaine sur votre plateforme principale est recommandé pour construire une présence régulière et rester visible dans les algorithmes.",
        },
      ],
    },
    {
      number: 10,
      title: "Vidéo Marketing et IA",
      description: "Créer des vidéos marketing performantes avec l'IA : scripts, montage, sous-titres, shorts.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Le Vidéo Marketing Propulse par l'IA" },
        { type: "paragraph", content: "La video est le format roi du marketing digital en 2026. Les Reels, TikToks, YouTube Shorts et les vidéos LinkedIn generent 5 à 10 fois plus d'engagement que le texte seul. L'IA rend la production video accessible à tous, même sans compétence technique." },
        { type: "paragraph", content: "De la génération de scripts a la création de vidéos complètes, en passant par le sous-titrage, le montage et la traduction, l'IA couvre l'ensemble du pipeline de production video." },
        { type: "heading", content: "Scripts et Storyboards IA" },
        { type: "paragraph", content: "Claude et GPT-5.4 excellent dans la rédaction de scripts video. Le format idéal : un hook de 3 secondes (capturer l'attention), un contenu de valeur (enseigner ou divertir), et un CTA clair (s'abonner, commenter, acheter). L'IA peut générer des dizaines de variantes de scripts optimises." },
        { type: "subheading", content: "Génération de Vidéos IA" },
        { type: "paragraph", content: "Sora 2 d'OpenAI, Runway Gen-3, et Kling AI generent des clips video à partir de descriptions textuelles. HeyGen et Synthesia créent des vidéos avec des avatars IA réalistes. Idéal pour les vidéos explicatives, les demos produit et le contenu éducatif." },
        { type: "video", videoId: "nkuPUJVzB_E",
      videoDurationMinutes: 12, label: "Vidéo marketing IA : du script a la publication" },
        { type: "heading", content: "Optimisation et Distribution" },
        { type: "paragraph", content: "OpusClip et Descript decoupent automatiquement vos vidéos longues en shorts viraux. L'IA identifie les moments forts, ajouté les sous-titres, et optimise le format pour chaque plateforme. Un webinar de 1 heure peut devenir 20 shorts en quelques minutes." },
        { type: "key-point", content: "Les sous-titres augmentent le taux de visionnage de 80%. La majorité des vidéos sur mobile sont regardees sans le son. L'IA génère des sous-titres précis automatiquement." },
        { type: "diagram", label: "Pipeline Vidéo Marketing IA", flow: "horizontal", nodes: [
          { label: "Script IA", sub: "Hook, contenu, CTA", color: "purple" },
          { label: "Production", sub: "Sora 2, HeyGen, camera", color: "blue" },
          { label: "Montage IA", sub: "OpusClip, Descript, sous-titres", color: "emerald" },
          { label: "Distribution", sub: "Multi-plateforme, shorts", color: "amber" },
        ]},
        { type: "prompt-example", prompt: "Ecris un script de Réel Instagram de 60 secondes sur le sujet : 'Comment l'IA peut doubler vos leads marketing'. Structure : hook 3 sec → problème → 3 astuces → CTA.", result: "Script structure : Hook ('Vos concurrents generent 2x plus de leads que vous — voici comment ils font'), problème (marketing manuel = lent), 3 astuces (segmentation IA, A/B testing auto, chatbot IA), CTA ('Suivez pour plus d'astuces IA')." },
        { type: "tip", content: "Le hook de 3 secondes détermine si votre video sera vue. Testez 5 hooks différents pour chaque video et gardez celui qui retient le plus l'attention." },
        { type: "summary", items: [
          "La video génère 5-10x plus d'engagement que le texte seul",
          "L'IA couvre tout le pipeline : script, production, montage, distribution",
          "Les sous-titres augmentent le visionnage de 80%",
          "OpusClip transformé 1 video longue en 20 shorts automatiquement",
          "Le hook de 3 secondes est l'élément le plus crucial",
        ]},
      ],
      quiz: [
        {
          question: "Combien de fois plus d'engagement la video génère-t-elle par rapport au texte ?",
          options: ["2x", "5-10x", "20x", "50x"],
          correctIndex: 1,
          explanation: "La video génère 5 à 10 fois plus d'engagement que le texte seul, ce qui en fait le format roi du marketing digital en 2026.",
        },
        {
          question: "De combien les sous-titres augmentent-ils le taux de visionnage ?",
          options: ["20%", "40%", "60%", "80%"],
          correctIndex: 3,
          explanation: "Les sous-titres augmentent le taux de visionnage de 80%, car la majorité des vidéos sur mobile sont regardees sans le son.",
        },
        {
          question: "Que fait OpusClip ?",
          options: ["Genere des images", "Decoupe les vidéos longues en shorts automatiquement", "Traduit des textes", "Cree des podcasts"],
          correctIndex: 1,
          explanation: "OpusClip utilise l'IA pour découper automatiquement les vidéos longues en shorts viraux, en identifiant les moments forts et en ajoutant des sous-titres.",
        },
        {
          question: "Quelle est la duree idéale du hook d'une video courte ?",
          options: ["1 seconde", "3 secondes", "10 secondes", "30 secondes"],
          correctIndex: 1,
          explanation: "Le hook doit capturer l'attention en 3 secondes. Au-dela, le spectateur scroll. C'est l'élément le plus crucial d'une video courte.",
        },
      ],
    },
    {
      number: 11,
      title: "Stratégie Marketing IA Complète",
      description: "Assembler toutes les pieces pour créer une stratégie marketing digitale intégrée et cohérente.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Votre Stratégie Marketing IA Intégrée" },
        { type: "paragraph", content: "Vous maitrisez maintenant chaque composante : SEO, contenu, social média, email, publicité, analytics, personal branding et video. Il est temps d'assembler le tout en une stratégie cohérente ou chaque élément renforce les autres." },
        { type: "paragraph", content: "Une stratégie marketing intégrée n'est pas une collection de tactiques isolees — c'est un écosystème ou le contenu alimenté le SEO, le SEO alimenté le trafic, le trafic alimenté l'email, l'email alimenté les ventes, et les ventes financent la publicité." },
        { type: "heading", content: "Le Funnel Marketing IA" },
        { type: "subheading", content: "Top of Funnel (TOFU) — Attirer" },
        { type: "paragraph", content: "Objectif : attirer du trafic qualifie. Leviers IA : SEO (articles optimises), réseaux sociaux (contenu IA), video (YouTube, Reels), publicité (Google/Meta). L'IA produit le volume, votre expertise attire la qualité." },
        { type: "subheading", content: "Middle of Funnel (MOFU) — Engager" },
        { type: "paragraph", content: "Objectif : transformer les visiteurs en leads. Leviers IA : lead magnets (ebooks, templates générés par IA), séquences email (personnalisation IA), webinaires, chatbot IA pour qualifier les leads." },
        { type: "subheading", content: "Bottom of Funnel (BOFU) — Convertir" },
        { type: "paragraph", content: "Objectif : transformer les leads en clients. Leviers IA : landing pages optimisées, séquences de vente personnalisées, demos sur-mesure, temoignages et preuves sociales mises en avant par l'IA." },
        { type: "video", videoId: "oeli5xkFZJo",
      videoDurationMinutes: 14, label: "Construire sa stratégie marketing IA complète" },
        { type: "diagram", label: "Le Funnel Marketing IA", flow: "vertical", nodes: [
          { label: "TOFU — Attirer", sub: "SEO, social, video, ads", color: "blue" },
          { label: "MOFU — Engager", sub: "Lead magnets, email, chatbot", color: "purple" },
          { label: "BOFU — Convertir", sub: "Landing pages, demos, vente", color: "emerald" },
          { label: "Retention", sub: "Onboarding, upsell, fidelisation", color: "amber" },
        ]},
        { type: "heading", content: "Plan d'Action 30-60-90 Jours" },
        { type: "paragraph", content: "Jours 1-30 : audit de l'existant, configuration des outils IA, création des premiers contenus SEO et sociaux. Jours 31-60 : lancement des séquences email, première campagne publicitaire, création du lead magnet. Jours 61-90 : optimisation basée sur les données, scaling des canaux performants, automatisation des workflows répétitifs." },
        { type: "tip", content: "Ne tentez pas de tout lancer en même temps. Concentrez-vous sur un canal principal (généralement le SEO ou LinkedIn) et ajoutez progressivement les autres. La constance bat la perfection." },
        { type: "prompt-example", prompt: "Cree un plan marketing digital IA sur 90 jours pour un consultant freelance en transformation digitale. Budget : 500 euros/mois. Objectif : générer 10 leads qualifies par mois.", result: "Plan détaillé : J1-30 (LinkedIn + 2 articles SEO + profil optimisé), J31-60 (lead magnet + séquence email + première campagne LinkedIn Ads a 200 euros), J61-90 (optimisation + content repurposing + scaling a 15 leads/mois)." },
        { type: "summary", items: [
          "Une stratégie intégrée est un écosystème, pas des tactiques isolees",
          "Funnel : TOFU (attirer) → MOFU (engager) → BOFU (convertir) → Retention",
          "Plan 30-60-90 : audit, lancement, optimisation progressive",
          "Concentrez-vous sur un canal principal puis etendez",
          "La constance bat la perfection — publiez régulièrement",
        ]},
      ],
      quiz: [
        {
          question: "Que signifie TOFU en marketing ?",
          options: ["Total Organic Funnel Usage", "Top of Funnel", "Tactical Online Framework Upgrade", "Target Opportunity For Upselling"],
          correctIndex: 1,
          explanation: "TOFU (Top of Funnel) désigné la phase d'attraction du funnel marketing, ou l'objectif est d'attirer du trafic qualifie via SEO, social média, video et publicité.",
        },
        {
          question: "Quel est l'objectif du MOFU (Middle of Funnel) ?",
          options: ["Attirer du trafic", "Transformer les visiteurs en leads", "Vendre directement", "Fideliser les clients"],
          correctIndex: 1,
          explanation: "Le MOFU vise à transformer les visiteurs en leads grâce aux lead magnets, séquences email, webinaires et chatbots IA de qualification.",
        },
        {
          question: "Que faire les 30 premiers jours du plan marketing ?",
          options: ["Lancer des publicités massives", "Auditer, configurer les outils et créer les premiers contenus", "Embaucher une équipe", "Tout automatiser"],
          correctIndex: 1,
          explanation: "Les 30 premiers jours sont consacres à l'audit de l'existant, la configuration des outils IA, et la création des premiers contenus SEO et sociaux.",
        },
        {
          question: "Quel conseil est donne pour le lancement ?",
          options: ["Lancer tout en même temps", "Se concentrer sur un canal principal et étendre progressivement", "Depenser le maximum en publicité", "Attendre d'avoir tout parfait"],
          correctIndex: 1,
          explanation: "Il est recommandé de se concentrer sur un canal principal (SEO ou LinkedIn) et d'ajouter progressivement les autres. La constance bat la perfection.",
        },
      ],
    },
    {
      number: 12,
      title: "Mesurer et Optimiser ses Résultats",
      description: "Suivre vos performances, identifier les opportunités et scaler ce qui fonctionne.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "L'Optimisation Continue avec l'IA" },
        { type: "paragraph", content: "Le marketing digital n'est pas un projet a date de fin — c'est un processus d'amélioration continue. L'IA excelle dans l'analyse de performance et l'identification d'opportunités d'optimisation que l'oeil humain pourrait manquer." },
        { type: "paragraph", content: "Le cycle d'optimisation : mesurer les résultats, analyser les données avec l'IA, identifier les opportunités, implementer les changements, puis mesurer à nouveau. Ce cycle doit tourner en permanence." },
        { type: "heading", content: "Tableaux de Bord Marketing" },
        { type: "paragraph", content: "Creez un dashboard unique qui centralise toutes vos métriques : trafic (GA4), engagement social (natifs + outils tiers), email (taux d'ouverture, clics), publicité (CPA, ROAS), et conversions. L'IA peut générer des rapports hebdomadaires automatiques avec insights et recommandations." },
        { type: "subheading", content: "Les Metriques North Star" },
        { type: "paragraph", content: "Chaque business a une métrique North Star — celle qui reflette le mieux la valeur créée. Pour un SaaS : le MRR (Monthly Recurring Revenue). Pour un e-commerce : le CA par visiteur. Pour un consultant : le nombre de leads qualifies. Identifiez la votre et optimisez tout autour." },
        { type: "video", videoId: "_ZvnD73m40o",
      videoDurationMinutes: 42, label: "Mesurer et optimiser ses résultats marketing" },
        { type: "heading", content: "Scaling Intelligent" },
        { type: "paragraph", content: "Quand un canal fonctionne, la tentation est de doubler le budget immédiatement. L'IA vous aide à scaler intelligemment : elle identifie le point de rendement decroissant, suggère des budgets optimaux, et détecte la saturation d'audience avant qu'elle ne devienne un problème." },
        { type: "key-point", content: "Doublez ce qui fonctionne, arretez ce qui ne fonctionne pas. Cela semble évident, mais la plupart des marketeurs persistent avec des canaux sous-performants par inertie. L'IA vous donne les données pour prendre des décisions objectives." },
        { type: "callout", content: "Felicitations ! Vous avez termine le cours complet de Marketing Digital IA. Vous avez les outils et les stratégies pour transformer votre marketing. L'étape suivante : appliquez le plan 30-60-90 des maintenant." },
        { type: "diagram", label: "Cycle d'Optimisation Continue", flow: "cycle", nodes: [
          { label: "Mesurer", sub: "Collecter les métriques clés", color: "blue" },
          { label: "Analyser", sub: "IA identifié patterns et opportunités", color: "purple" },
          { label: "Implementer", sub: "Appliquer les optimisations", color: "emerald" },
        ]},
        { type: "prompt-example", prompt: "Voici mes métriques marketing du mois : SEO (5000 visites, 50 leads), LinkedIn (2000 impressions, 15 leads), Email (3000 envoyés, 30% ouverture, 20 leads), Ads (1000 euros dépenses, 25 leads). Analyse et recommande les optimisations.", result: "Analyse : SEO meilleur CPA (0 euro/lead), email meilleur taux de conversion (0,67%). Recommandations : doubler la production SEO, optimiser les objets d'emails (30% ouverture = ameliorable), réduire le budget ads et reallouer vers le contenu organic." },
        { type: "tip", content: "Faites un bilan mensuel de 30 minutes avec l'IA : exportez vos données, demandez une analyse complète, et implementez les 3 recommandations les plus impactantes. C'est le minimum pour une optimisation continue efficace." },
        { type: "summary", items: [
          "Le marketing est un processus d'amélioration continue, pas un projet fini",
          "Cycle : mesurer → analyser avec l'IA → implementer → mesurer",
          "Identifiez votre métrique North Star et optimisez tout autour",
          "Doublez ce qui fonctionne, arretez ce qui ne fonctionne pas",
          "Bilan mensuel de 30 minutes avec l'IA = optimisation continue efficace",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce qu'une métrique North Star ?",
          options: ["La métrique la plus facile à mesurer", "La métrique qui reflette le mieux la valeur créée par votre business", "Le nombre total de visiteurs", "Le nombre de followers"],
          correctIndex: 1,
          explanation: "La métrique North Star est celle qui reflette le mieux la valeur créée : MRR pour un SaaS, CA/visiteur pour un e-commerce, leads qualifies pour un consultant.",
        },
        {
          question: "Que signifie ROAS en marketing ?",
          options: ["Rate of Audience Size", "Return on Ad Spend", "Ranking of All Sources", "Revenue Over Average Sales"],
          correctIndex: 1,
          explanation: "ROAS (Return on Ad Spend) mesure le revenu génère pour chaque euro dépense en publicité. Un ROAS de 5x signifie 5 euros de revenu pour 1 euro dépense.",
        },
        {
          question: "Quel est le risque de scaler trop vite un canal publicitaire ?",
          options: ["Aucun risque", "Saturation d'audience et rendements decroissants", "Le compte est banni", "Les prix baissent"],
          correctIndex: 1,
          explanation: "Scaler trop vite un canal peut mener a la saturation d'audience (montrer la même pub trop souvent) et a des rendements decroissants ou le CPA augmente.",
        },
        {
          question: "A quelle fréquence faire un bilan d'optimisation ?",
          options: ["Tous les jours", "Toutes les semaines", "Tous les mois (minimum 30 min avec l'IA)", "Tous les 6 mois"],
          correctIndex: 2,
          explanation: "Un bilan mensuel de 30 minutes avec l'IA est le minimum recommandé : exporter les données, analyser, et implementer les 3 recommandations les plus impactantes.",
        },
      ],
    },
  ],
};

export default content;
