import type { CourseContent } from "../types";

const content: CourseContent = {
  slug: "ia-marketing-digital",
  chapters: [
    {
      number: 1,
      title: "Introduction au Marketing Digital IA",
      description: "Comprendre comment l'IA revolutionne le marketing digital en 2026.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Le Marketing Digital a l'Ere de l'IA" },
        { type: "paragraph", content: "Le marketing digital a connu plus de changements en 2 ans qu'en 20 ans. L'IA ne se contente pas d'optimiser les campagnes existantes — elle reinvente completement la maniere dont les marques attirent, engagent et convertissent leurs audiences." },
        { type: "paragraph", content: "En 2026, les marketeurs qui n'utilisent pas l'IA sont deja en retard. Les outils IA permettent de produire du contenu 10x plus vite, de cibler les audiences avec une precision chirurgicale, et d'optimiser les campagnes en temps reel grace a l'analyse predictive." },
        { type: "callout", content: "Selon HubSpot, 87% des marketeurs utilisent l'IA dans au moins une partie de leur workflow en 2026. Les equipes augmentees par l'IA generent en moyenne 40% de leads en plus." },
        { type: "video", videoId: "Z-ikDaRJ2ZQ", label: "L'IA dans le marketing digital en 2026" },
        { type: "heading", content: "Les Piliers du Marketing Digital IA" },
        { type: "paragraph", content: "Le marketing digital IA repose sur 5 piliers : la creation de contenu (texte, image, video), l'optimisation SEO, le ciblage publicitaire, l'analyse de donnees, et la personnalisation a grande echelle. Chacun de ces piliers est transforme par l'IA." },
        { type: "subheading", content: "Le Paradigme a Change" },
        { type: "paragraph", content: "Avant l'IA : un marketeur passait 80% de son temps sur l'execution (creer des visuels, rediger des posts, analyser des donnees). Avec l'IA : 80% du temps est consacre a la strategie, la creativite et la relation client. L'execution est largement automatisee." },
        { type: "key-point", content: "L'IA est un multiplicateur de force. Un marketeur seul avec les bons outils IA peut produire autant qu'une equipe de 5 personnes en 2020. Mais la strategie et la creativite humaine restent irremplacables." },
        { type: "diagram", label: "Les 5 Piliers du Marketing Digital IA", flow: "horizontal", nodes: [
          { label: "Contenu", sub: "Texte, image, video IA", color: "purple" },
          { label: "SEO", sub: "Optimisation automatisee", color: "blue" },
          { label: "Publicite", sub: "Ciblage et optimisation IA", color: "emerald" },
          { label: "Analytics", sub: "Analyse predictive", color: "amber" },
          { label: "Personnalisation", sub: "Experience sur-mesure", color: "pink" },
        ]},
        { type: "tip", content: "Ce cours est structure pour etre actionnable : chaque chapitre vous donne des outils et des techniques que vous pouvez appliquer immediatement a votre activite." },
        { type: "summary", items: [
          "L'IA revolutionne les 5 piliers du marketing digital",
          "87% des marketeurs utilisent deja l'IA en 2026",
          "Un marketeur + IA = la productivite d'une equipe de 5 personnes",
          "Le temps passe sur l'execution diminue, celui sur la strategie augmente",
          "La creativite et la strategie humaine restent irremplacables",
        ]},
      ],
      quiz: [
        {
          question: "Quel pourcentage de marketeurs utilise l'IA en 2026 ?",
          options: ["45%", "62%", "87%", "95%"],
          correctIndex: 2,
          explanation: "Selon HubSpot, 87% des marketeurs utilisent l'IA dans au moins une partie de leur workflow en 2026.",
        },
        {
          question: "Combien de piliers composent le marketing digital IA ?",
          options: ["3", "4", "5", "7"],
          correctIndex: 2,
          explanation: "Le marketing digital IA repose sur 5 piliers : contenu, SEO, publicite, analytics et personnalisation.",
        },
        {
          question: "Comment l'IA change-t-elle la repartition du temps des marketeurs ?",
          options: ["Plus de temps sur l'execution", "Plus de temps sur la strategie et la creativite", "Aucun changement", "Plus de temps sur la formation"],
          correctIndex: 1,
          explanation: "L'IA automatise l'execution, liberant 80% du temps pour la strategie, la creativite et la relation client — les taches a haute valeur ajoutee.",
        },
        {
          question: "Quelle affirmation est FAUSSE concernant l'IA en marketing ?",
          options: ["L'IA accelere la creation de contenu", "L'IA remplace completement la creativite humaine", "L'IA optimise le ciblage publicitaire", "L'IA analyse les donnees en temps reel"],
          correctIndex: 1,
          explanation: "L'IA ne remplace pas la creativite humaine — elle amplifie les capacites du marketeur mais la strategie et la vision restent irremplacables.",
        },
      ],
    },
    {
      number: 2,
      title: "SEO et IA : Dominer les Moteurs de Recherche",
      description: "Utiliser l'IA pour optimiser votre referencement et surpasser la concurrence.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Le SEO a l'Ere de l'IA" },
        { type: "paragraph", content: "Le SEO en 2026 n'est plus celui de 2020. Google utilise massivement l'IA (Gemini) dans son algorithme de recherche. Les AI Overviews repondent directement aux questions des utilisateurs. Pour rester visible, votre strategie SEO doit integrer l'IA a chaque etape." },
        { type: "paragraph", content: "L'IA transforme le SEO des deux cotes : les moteurs de recherche l'utilisent pour mieux comprendre le contenu, et les marketeurs l'utilisent pour creer du contenu mieux optimise. C'est une course a l'armement ou l'IA est votre meilleure arme." },
        { type: "heading", content: "Recherche de Mots-Cles avec l'IA" },
        { type: "paragraph", content: "Les outils IA analysent les intentions de recherche, pas seulement les volumes. Ils identifient les questions que posent vraiment vos cibles, les sujets connexes, et les opportunites de long-tail keywords sous-exploites par vos concurrents." },
        { type: "subheading", content: "Outils de Recherche IA" },
        { type: "paragraph", content: "Semrush AI, Ahrefs Content Grader, Surfer SEO, et Claude/GPT pour l'analyse semantique avancee. Combinez ces outils pour une recherche de mots-cles exhaustive et strategique." },
        { type: "video", videoId: "V1ERnMiKxkA", label: "SEO et IA : strategies avancees 2026" },
        { type: "heading", content: "Redaction SEO Augmentee par l'IA" },
        { type: "paragraph", content: "L'IA redige des articles optimises pour le SEO : structure H1-H6, densite de mots-cles naturelle, maillage interne, meta-descriptions, et rich snippets. Mais attention : Google detecte le contenu 100% IA sans valeur ajoutee. La touche humaine reste essentielle." },
        { type: "callout", content: "Google a confirme en 2025 que le contenu genere par l'IA n'est pas penalise en soi. C'est la qualite et l'utilite du contenu qui comptent, pas la methode de creation. Ajoutez toujours de l'expertise et de l'experience personnelle." },
        { type: "prompt-example", prompt: "Analyse la SERP Google pour le mot-cle 'automatisation marketing IA'. Identifie les top 5 articles, leurs points forts et faiblesses, et propose un plan d'article qui les surpasse en profondeur et en valeur.", result: "Analyse des 5 premiers resultats avec scores de contenu, gaps identifies, et un plan d'article en 8 sections couvrant les angles manquants avec des donnees fraiches et des exemples concrets." },
        { type: "key-point", content: "Le framework E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness) de Google est plus important que jamais. L'IA vous aide a produire, mais c'est votre expertise qui fait la difference dans le ranking." },
        { type: "diagram", label: "Pipeline SEO Augmente par l'IA", flow: "horizontal", nodes: [
          { label: "Recherche mots-cles", sub: "IA + Semrush, intentions", color: "blue" },
          { label: "Redaction IA", sub: "Structure, optimisation", color: "purple" },
          { label: "Expertise humaine", sub: "E-E-A-T, experience", color: "emerald" },
          { label: "Analyse resultats", sub: "Ranking, trafic, conversions", color: "amber" },
        ]},
        { type: "summary", items: [
          "Google utilise l'IA (Gemini) dans son algorithme — adaptez votre strategie",
          "L'IA analyse les intentions de recherche, pas seulement les volumes",
          "Outils cles : Semrush AI, Ahrefs, Surfer SEO, Claude/GPT",
          "Le contenu IA n'est pas penalise, mais l'expertise humaine est indispensable",
          "E-E-A-T : Experience, Expertise, Authoritativeness, Trustworthiness",
        ]},
      ],
      quiz: [
        {
          question: "Que sont les AI Overviews de Google ?",
          options: ["Un outil SEO payant", "Des reponses IA directement dans les resultats de recherche", "Un algorithme de penalite", "Un format de publicite"],
          correctIndex: 1,
          explanation: "Les AI Overviews sont des reponses generees par l'IA de Google (Gemini) qui apparaissent directement en haut des resultats de recherche.",
        },
        {
          question: "Google penalise-t-il le contenu genere par l'IA ?",
          options: ["Oui, tout contenu IA est penalise", "Non, c'est la qualite et l'utilite qui comptent", "Seulement si c'est du texte long", "Seulement pour les sites de moins de 1000 pages"],
          correctIndex: 1,
          explanation: "Google a confirme que le contenu IA n'est pas penalise en soi. C'est la qualite, l'utilite et l'expertise du contenu qui determinent le ranking.",
        },
        {
          question: "Que signifie E-E-A-T ?",
          options: ["Easy, Efficient, Automatic, Technical", "Experience, Expertise, Authoritativeness, Trustworthiness", "Engagement, Education, Awareness, Traffic", "Export, Edit, Analyze, Track"],
          correctIndex: 1,
          explanation: "E-E-A-T (Experience, Expertise, Authoritativeness, Trustworthiness) est le framework de Google pour evaluer la qualite du contenu.",
        },
        {
          question: "Quel outil est recommande pour la recherche de mots-cles IA ?",
          options: ["Canva", "Semrush AI", "Slack", "Zoom"],
          correctIndex: 1,
          explanation: "Semrush AI est un outil de reference pour la recherche de mots-cles augmentee par l'IA, avec analyse des intentions et des opportunites.",
        },
      ],
    },
    {
      number: 3,
      title: "Content Marketing Augmente par l'IA",
      description: "Creer une strategie de contenu performante avec l'IA : articles, videos, infographies.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Le Content Marketing Propulse par l'IA" },
        { type: "paragraph", content: "Le content marketing est le pilier de toute strategie digitale. En 2026, l'IA permet de produire du contenu a une echelle et une vitesse inimaginables il y a 3 ans, tout en maintenant une qualite editoriale elevee." },
        { type: "paragraph", content: "Un article de blog, 3 posts LinkedIn, 5 tweets, une newsletter et une infographie — ce qui prenait une semaine a une equipe de contenu peut desormais etre produit en quelques heures avec le bon workflow IA." },
        { type: "heading", content: "Strategie de Contenu IA" },
        { type: "subheading", content: "Le Content Repurposing" },
        { type: "paragraph", content: "La technique la plus puissante : creer un contenu pilier (article long, video, podcast) et laisser l'IA le decliner en dizaines de formats. Un article de 2000 mots devient 10 posts LinkedIn, 20 tweets, 5 reels scripts, et une newsletter — automatiquement." },
        { type: "subheading", content: "La Redaction Assistee" },
        { type: "paragraph", content: "L'IA ne remplace pas le redacteur — elle l'amplifie. Le workflow optimal : vous definissez l'angle et les points cles, l'IA redige le premier jet, vous ajoutez votre expertise et votre voix, l'IA optimise pour le SEO et la lisibilite." },
        { type: "video", videoId: "W9S3s7gEUqs", label: "Content marketing IA : workflow complet" },
        { type: "callout", content: "Le contenu le plus performant en 2026 combine l'expertise humaine et l'efficacite de l'IA. Les articles qui rankent le mieux sont ceux qui apportent une experience et une perspective uniques, impossibles a generer par l'IA seule." },
        { type: "prompt-example", prompt: "Tu es un expert en marketing digital. Transforme cet article de 2000 mots sur le SEO en : 1) 3 posts LinkedIn engageants, 2) 5 tweets avec hooks, 3) Un script de Reel de 60 secondes, 4) Un email newsletter de 300 mots.", result: "3 posts LinkedIn avec hooks percutants et CTA, 5 tweets avec chiffres et questions, un script Reel structure (hook-contenu-CTA), et un email newsletter conversationnel avec un lien vers l'article." },
        { type: "diagram", label: "Le Content Repurposing IA", flow: "vertical", nodes: [
          { label: "Contenu Pilier", sub: "Article long, video, podcast", color: "purple" },
          { label: "Declinaison IA", sub: "Posts, tweets, reels, emails", color: "blue" },
          { label: "Optimisation", sub: "SEO, hashtags, CTA adaptes", color: "emerald" },
          { label: "Publication", sub: "Multi-plateforme automatisee", color: "amber" },
        ]},
        { type: "tip", content: "Creez une banque de prompts pour chaque type de contenu. Un bon prompt de declinaison LinkedIn est reutilisable des centaines de fois avec differents articles sources." },
        { type: "summary", items: [
          "Le content repurposing transforme 1 contenu en dizaines de formats",
          "Workflow optimal : angle humain → premier jet IA → revision → optimisation",
          "L'expertise et la perspective humaine font la difference",
          "Creez une banque de prompts reutilisables pour chaque format",
          "Automatisez la publication multi-plateforme",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que le content repurposing ?",
          options: ["Supprimer du vieux contenu", "Decliner un contenu pilier en multiples formats", "Copier le contenu des concurrents", "Traduire du contenu en anglais"],
          correctIndex: 1,
          explanation: "Le content repurposing consiste a prendre un contenu pilier et a le decliner automatiquement en multiples formats adaptes a chaque plateforme.",
        },
        {
          question: "Quel est le workflow optimal de redaction avec l'IA ?",
          options: ["L'IA ecrit tout, on publie directement", "On ecrit tout, l'IA corrige l'orthographe", "Angle humain → premier jet IA → revision → optimisation", "On copie des articles existants"],
          correctIndex: 2,
          explanation: "Le workflow optimal combine la vision strategique humaine avec la rapidite de l'IA : l'humain definit l'angle, l'IA redige, l'humain revise, l'IA optimise.",
        },
        {
          question: "Combien de posts LinkedIn peut-on generer a partir d'un article de 2000 mots ?",
          options: ["1-2", "3-5", "10+", "Ce n'est pas possible"],
          correctIndex: 2,
          explanation: "Un article de 2000 mots contient suffisamment de matiere pour generer 10 ou plus posts LinkedIn, chacun mettant en avant un angle ou un point cle different.",
        },
        {
          question: "Pourquoi creer une banque de prompts ?",
          options: ["Pour les revendre", "Pour reutiliser des prompts optimises avec differents contenus sources", "Pour remplacer l'IA", "Pour le SEO"],
          correctIndex: 1,
          explanation: "Une banque de prompts permet de reutiliser des prompts optimises et testes avec differents contenus sources, garantissant une qualite constante.",
        },
      ],
    },
    {
      number: 4,
      title: "Reseaux Sociaux et IA",
      description: "Optimiser votre presence sur les reseaux sociaux grace a l'IA : contenu, timing, engagement.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Les Reseaux Sociaux Augmentes par l'IA" },
        { type: "paragraph", content: "Les reseaux sociaux en 2026 sont un terrain de jeu ideal pour l'IA. De la creation de contenu au choix du moment de publication, en passant par l'analyse de l'engagement et la gestion des communautes, l'IA intervient a chaque etape." },
        { type: "paragraph", content: "Les plateformes elles-memes utilisent massivement l'IA : algorithmes de recommandation, detection de contenu inapproprie, outils de creation integres. Comprendre comment fonctionne l'IA des plateformes est essentiel pour maximiser votre visibilite." },
        { type: "heading", content: "Creation de Contenu Social IA" },
        { type: "subheading", content: "Texte et Copy" },
        { type: "paragraph", content: "L'IA genere des hooks (accroches), des corps de texte engageants, des CTA (call-to-action) adaptes a chaque plateforme. Le secret : donner a l'IA votre voix de marque et des exemples de posts qui ont bien fonctionne." },
        { type: "subheading", content: "Visuels et Videos" },
        { type: "paragraph", content: "Midjourney et DALL-E pour les visuels. Canva AI pour les designs adaptes aux formats de chaque plateforme. Sora 2 et Runway pour les videos courtes. L'IA peut produire un mois de visuels en une journee." },
        { type: "video", videoId: "Z-ikDaRJ2ZQ", label: "Strategie reseaux sociaux avec l'IA" },
        { type: "heading", content: "Timing et Analyse" },
        { type: "paragraph", content: "L'IA analyse quand votre audience est la plus active, quels types de contenu generent le plus d'engagement, et quels hashtags augmentent la portee. Les outils comme Buffer AI et Hootsuite AI optimisent automatiquement le calendrier de publication." },
        { type: "callout", content: "L'algorithme de LinkedIn en 2026 favorise les contenus qui generent des commentaires significatifs. L'IA peut vous aider a creer des posts qui suscitent le debat et l'interaction, mais l'engagement authentique dans les commentaires reste humain." },
        { type: "diagram", label: "Workflow Social Media IA", flow: "horizontal", nodes: [
          { label: "Strategie", sub: "Sujets, calendrier, objectifs", color: "purple" },
          { label: "Creation IA", sub: "Texte + visuels + videos", color: "blue" },
          { label: "Publication auto", sub: "Timing optimal, multi-plateforme", color: "emerald" },
          { label: "Analyse IA", sub: "Engagement, portee, ROI", color: "amber" },
        ]},
        { type: "prompt-example", prompt: "Analyse mes 10 derniers posts LinkedIn. Identifie les patterns de ceux qui ont le plus d'engagement (likes, commentaires, partages). Genere 5 nouveaux posts qui reprennent ces patterns gagnants.", result: "Analyse avec scores d'engagement, identification des hooks efficaces (questions, chiffres, controverses), et 5 nouveaux posts reprenant les formats gagnants avec des sujets frais." },
        { type: "summary", items: [
          "L'IA optimise chaque etape du marketing social : creation, timing, analyse",
          "Generez texte, visuels et videos avec les outils IA",
          "Les outils de scheduling IA optimisent le moment de publication",
          "Analysez les patterns d'engagement pour reproduire le succes",
          "L'engagement authentique dans les commentaires reste humain",
        ]},
      ],
      quiz: [
        {
          question: "Quel est le secret pour que l'IA cree du contenu social efficace ?",
          options: ["Utiliser le prompt le plus long possible", "Lui donner votre voix de marque et des exemples de posts performants", "Publier le plus possible", "Copier les concurrents"],
          correctIndex: 1,
          explanation: "L'IA cree du contenu social plus efficace quand vous lui fournissez votre voix de marque et des exemples de posts qui ont bien fonctionne dans le passe.",
        },
        {
          question: "Qu'optimisent les outils comme Buffer AI et Hootsuite AI ?",
          options: ["Le prix des abonnements", "Le calendrier et timing de publication", "La taille des images", "Le nombre de followers"],
          correctIndex: 1,
          explanation: "Buffer AI et Hootsuite AI analysent quand votre audience est active et optimisent automatiquement le calendrier de publication pour maximiser l'engagement.",
        },
        {
          question: "Que favorise l'algorithme LinkedIn en 2026 ?",
          options: ["Les posts avec beaucoup d'hashtags", "Les contenus qui generent des commentaires significatifs", "Les posts tres longs", "Les publications a 8h du matin"],
          correctIndex: 1,
          explanation: "L'algorithme LinkedIn favorise les contenus qui generent des commentaires significatifs et des interactions, pas simplement des likes.",
        },
        {
          question: "Quelle tache des reseaux sociaux doit rester humaine ?",
          options: ["La creation de visuels", "L'engagement authentique dans les commentaires", "La planification du calendrier", "L'analyse des metriques"],
          correctIndex: 1,
          explanation: "L'engagement authentique dans les commentaires — repondre aux questions, participer aux discussions — reste une tache ou l'humain fait la difference.",
        },
      ],
    },
    {
      number: 5,
      title: "Email Marketing Intelligent",
      description: "Transformer votre email marketing avec l'IA : segmentation, personnalisation, automatisation.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "L'Email Marketing Reinvente par l'IA" },
        { type: "paragraph", content: "L'email marketing reste le canal avec le meilleur ROI en 2026 : 36 euros de retour pour chaque euro investi. L'IA le rend encore plus puissant grace a la segmentation intelligente, la personnalisation hyper-contextuelle et l'optimisation automatique." },
        { type: "paragraph", content: "Les outils comme Mailchimp AI, ActiveCampaign, Brevo (ex-Sendinblue) et Klaviyo integrent desormais l'IA nativement pour optimiser les objets, le contenu, le timing d'envoi et la segmentation." },
        { type: "heading", content: "Segmentation Intelligente" },
        { type: "paragraph", content: "L'IA va au-dela de la segmentation classique (age, localisation, achat). Elle identifie des micro-segments bases sur le comportement : les lecteurs assidus qui n'achetent pas, les clients a risque de churn, les ambassadeurs potentiels, les acheteurs saisonniers." },
        { type: "subheading", content: "Personnalisation Hyper-Contextuelle" },
        { type: "paragraph", content: "Chaque email peut etre unique : l'objet, le contenu, les produits recommandes, le CTA, et meme le moment d'envoi sont adaptes a chaque destinataire. L'IA genere des variantes personnalisees a grande echelle." },
        { type: "video", videoId: "V1ERnMiKxkA", label: "Email marketing IA : segmentation et personnalisation" },
        { type: "key-point", content: "L'objet de l'email determine 80% du taux d'ouverture. L'IA peut generer et A/B tester des dizaines de variantes d'objets pour trouver celui qui performe le mieux pour chaque segment." },
        { type: "heading", content: "Sequences Automatisees" },
        { type: "paragraph", content: "Les sequences d'emails automatisees (onboarding, nurturing, reactivation, abandon de panier) sont les plus rentables. L'IA optimise chaque email de la sequence : contenu, timing, et decision de continuer ou d'arreter la sequence selon le comportement du destinataire." },
        { type: "diagram", label: "Pipeline Email Marketing IA", flow: "horizontal", nodes: [
          { label: "Segmentation IA", sub: "Micro-segments comportementaux", color: "purple" },
          { label: "Personnalisation", sub: "Contenu unique par destinataire", color: "blue" },
          { label: "Optimisation", sub: "Objet, timing, CTA", color: "emerald" },
          { label: "Analyse", sub: "Taux d'ouverture, clics, conversions", color: "amber" },
        ]},
        { type: "prompt-example", prompt: "Cree 10 variantes d'objet d'email pour une promotion Black Friday sur une formation en marketing digital. Cible : freelances francophones, 25-40 ans. Objectif : maximiser le taux d'ouverture.", result: "10 variantes utilisant differentes techniques (urgence, curiosite, chiffres, personnalisation, question) avec des predictions de performance basees sur les patterns qui fonctionnent pour ce segment." },
        { type: "tip", content: "Testez toujours au moins 3 variantes d'objet d'email. L'IA peut predire la performance, mais seul le test reel avec votre audience donne des resultats fiables." },
        { type: "summary", items: [
          "L'email marketing reste le canal au meilleur ROI : 36x en 2026",
          "L'IA identifie des micro-segments comportementaux avances",
          "Personnalisation hyper-contextuelle a grande echelle",
          "L'objet determine 80% du taux d'ouverture — testez avec l'IA",
          "Les sequences automatisees sont les plus rentables",
        ]},
      ],
      quiz: [
        {
          question: "Quel est le ROI moyen de l'email marketing en 2026 ?",
          options: ["5x", "12x", "36x", "50x"],
          correctIndex: 2,
          explanation: "L'email marketing offre un ROI de 36 euros pour chaque euro investi, ce qui en fait le canal marketing le plus rentable en 2026.",
        },
        {
          question: "Quel element determine 80% du taux d'ouverture d'un email ?",
          options: ["Le contenu", "L'objet (subject line)", "Les images", "Le CTA"],
          correctIndex: 1,
          explanation: "L'objet de l'email determine 80% du taux d'ouverture. C'est la premiere chose que voit le destinataire et elle decide s'il ouvre ou non l'email.",
        },
        {
          question: "Qu'est-ce que la segmentation comportementale ?",
          options: ["Segmenter par age et localisation", "Segmenter par comportement (clics, achats, engagement)", "Segmenter par nom de famille", "Ne pas segmenter du tout"],
          correctIndex: 1,
          explanation: "La segmentation comportementale cree des groupes bases sur les actions des utilisateurs : clics, achats, frequence de lecture, etc., au-dela des criteres demographiques.",
        },
        {
          question: "Combien de variantes d'objet tester au minimum ?",
          options: ["1", "3", "10", "50"],
          correctIndex: 1,
          explanation: "Il est recommande de tester au moins 3 variantes d'objet pour obtenir des resultats statistiquement significatifs avec votre audience.",
        },
      ],
    },
    {
      number: 6,
      title: "Publicite en Ligne avec l'IA (Google, Meta)",
      description: "Optimiser vos campagnes Google Ads et Meta Ads avec l'intelligence artificielle.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "La Publicite Digitale Augmentee par l'IA" },
        { type: "paragraph", content: "Google Ads et Meta Ads (Facebook, Instagram) utilisent deja massivement l'IA dans leurs algorithmes de diffusion. Mais au-dela de l'IA des plateformes, vous pouvez utiliser vos propres outils IA pour creer de meilleurs visuels, rediger des copies plus percutantes et optimiser vos budgets." },
        { type: "paragraph", content: "En 2026, les campagnes Performance Max de Google et Advantage+ de Meta sont pilotees par l'IA. Le role du marketeur evolue : moins de micro-gestion des encheres, plus de strategie creative et de qualite des signaux." },
        { type: "heading", content: "Google Ads et l'IA" },
        { type: "subheading", content: "Performance Max" },
        { type: "paragraph", content: "Performance Max utilise l'IA de Google pour diffuser vos annonces sur tous les canaux Google (Search, Display, YouTube, Maps, Gmail). Vous fournissez les assets (textes, images, videos) et l'IA optimise la diffusion en temps reel." },
        { type: "paragraph", content: "L'IA genere meme des variantes de vos annonces : combinaisons de titres et descriptions, adaptations visuelles, et ciblage d'audiences similaires a vos clients existants." },
        { type: "heading", content: "Meta Ads (Advantage+)" },
        { type: "subheading", content: "Advantage+ Shopping et Creative" },
        { type: "paragraph", content: "Advantage+ automatise le ciblage, les placements et l'optimisation creative. Advantage+ Creative genere automatiquement des variantes de vos visuels adaptees a chaque audience. Le ROI des campagnes Advantage+ est en moyenne 30% superieur aux campagnes manuelles." },
        { type: "video", videoId: "W9S3s7gEUqs", label: "Google Ads + Meta Ads : optimisation IA" },
        { type: "key-point", content: "En 2026, la qualite des creatives (visuels et textes) est le levier #1 de performance publicitaire. L'IA des plateformes optimise la diffusion, mais c'est votre creative qui determine si les gens cliquent." },
        { type: "diagram", label: "Publicite Digitale IA : Ecosysteme", flow: "horizontal", nodes: [
          { label: "Creatives IA", sub: "Visuels, textes, videos", color: "purple" },
          { label: "Google Performance Max", sub: "Tous canaux Google, auto-optimise", color: "blue" },
          { label: "Meta Advantage+", sub: "Facebook, Instagram, auto-ciblage", color: "emerald" },
          { label: "Analyse IA", sub: "ROI, CPA, attribution", color: "amber" },
        ]},
        { type: "prompt-example", prompt: "Genere 5 variantes de texte publicitaire Google Ads pour une formation en ligne sur le marketing digital IA. Cible : entrepreneurs francophones. Limite : 30 caracteres titre, 90 caracteres description.", result: "5 variantes avec titres accrocheurs et descriptions percutantes, chacune exploitant un angle different (ROI, gain de temps, concurrence, competence, carriere) dans les limites de caracteres." },
        { type: "callout", content: "Ne faites pas confiance aveuglement a l'IA des plateformes publicitaires. Elles optimisent pour leurs metriques (clics, impressions), pas necessairement pour votre ROI reel. Suivez toujours vos conversions finales." },
        { type: "summary", items: [
          "Google Performance Max et Meta Advantage+ sont pilotes par l'IA",
          "La qualite des creatives est le levier #1 de performance",
          "L'IA des plateformes optimise la diffusion, vous optimisez les creatives",
          "Advantage+ offre en moyenne 30% de ROI superieur aux campagnes manuelles",
          "Suivez toujours vos conversions finales, pas seulement les metriques plateforme",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce que Google Performance Max ?",
          options: ["Un type de serveur", "Une campagne IA qui diffuse sur tous les canaux Google", "Un outil de SEO", "Un plan tarifaire premium"],
          correctIndex: 1,
          explanation: "Performance Max est un type de campagne Google Ads qui utilise l'IA pour diffuser vos annonces sur tous les canaux Google (Search, Display, YouTube, Maps, Gmail).",
        },
        {
          question: "Quel est le levier #1 de performance publicitaire en 2026 ?",
          options: ["Le budget", "La qualite des creatives", "Le nombre de campagnes", "L'heure de diffusion"],
          correctIndex: 1,
          explanation: "La qualite des creatives (visuels et textes) est le principal levier de performance. L'IA optimise la diffusion, mais ce sont les creatives qui determinent les clics.",
        },
        {
          question: "Quel est l'avantage moyen de ROI des campagnes Advantage+ de Meta ?",
          options: ["10% superieur", "30% superieur", "50% superieur", "100% superieur"],
          correctIndex: 1,
          explanation: "Les campagnes Advantage+ de Meta offrent en moyenne 30% de ROI superieur aux campagnes configurees manuellement, grace a l'optimisation IA.",
        },
        {
          question: "Pourquoi ne pas faire confiance aveuglement aux metriques des plateformes ?",
          options: ["Elles sont toujours fausses", "Elles optimisent pour leurs metriques, pas votre ROI reel", "Elles sont trop complexes", "Elles changent chaque jour"],
          correctIndex: 1,
          explanation: "Les plateformes optimisent pour leurs propres metriques (clics, impressions). Votre ROI reel depend des conversions finales, qui peuvent differer significativement.",
        },
      ],
    },
    {
      number: 7,
      title: "Landing Pages et Conversion",
      description: "Creer des landing pages a haute conversion grace a l'IA : copy, design, A/B testing.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Landing Pages : L'Art de la Conversion" },
        { type: "paragraph", content: "Une landing page est la page ou atterrissent vos visiteurs apres avoir clique sur une publicite ou un lien. Son unique objectif : convertir le visiteur en lead ou en client. L'IA transforme la creation de landing pages en permettant de generer, tester et optimiser des dizaines de variantes rapidement." },
        { type: "paragraph", content: "En 2026, les outils comme Unbounce Smart Builder, Instapage AI et meme v0/Bolt generent des landing pages completes a partir d'une simple description. L'IA optimise ensuite chaque element pour maximiser les conversions." },
        { type: "heading", content: "Les Elements d'une Landing Page qui Convertit" },
        { type: "paragraph", content: "Les elements cles : un headline percutant (benefice principal), un sous-titre clarifiant, une preuve sociale (temoignages, chiffres), un CTA visible et convaincant, et un formulaire simple. L'IA peut generer et tester chacun de ces elements." },
        { type: "subheading", content: "Copywriting IA pour la Conversion" },
        { type: "paragraph", content: "Les frameworks de copywriting (AIDA, PAS, FAB) combines a l'IA produisent des textes de vente redoutablement efficaces. AIDA : Attention, Interet, Desir, Action. PAS : Probleme, Agitation, Solution. L'IA adapte ces frameworks a votre offre specifique." },
        { type: "video", videoId: "Z-ikDaRJ2ZQ", label: "Creer une landing page a haute conversion avec l'IA" },
        { type: "key-point", content: "Une landing page n'a qu'un seul objectif et un seul CTA. Si vous donnez trop de choix au visiteur, il ne fait rien. L'IA peut vous aider a simplifier et a focaliser votre message." },
        { type: "heading", content: "A/B Testing avec l'IA" },
        { type: "paragraph", content: "L'A/B testing IA va plus loin que le test classique : il peut tester des dizaines de variantes simultanement (multivariate testing), identifier le gagnant plus rapidement grace au machine learning, et meme adapter la page en temps reel selon le profil du visiteur." },
        { type: "callout", content: "Les tests montrent qu'un changement de headline peut augmenter les conversions de 30 a 50%. Ne sous-estimez jamais la puissance du texte — testez au moins 5 variantes de headline avec l'IA." },
        { type: "diagram", label: "Anatomie d'une Landing Page Optimisee", flow: "vertical", nodes: [
          { label: "Headline", sub: "Benefice principal, clair et percutant", color: "purple" },
          { label: "Preuve sociale", sub: "Temoignages, chiffres, logos", color: "blue" },
          { label: "Proposition de valeur", sub: "Pourquoi vous, pourquoi maintenant", color: "emerald" },
          { label: "CTA", sub: "Un seul bouton, action claire", color: "amber" },
        ]},
        { type: "prompt-example", prompt: "Genere 5 headlines pour une landing page de formation 'Marketing Digital IA'. Utilise le framework PAS (Probleme, Agitation, Solution). Cible : entrepreneurs qui veulent plus de clients.", result: "5 headlines PAS : ex. 'Vos concurrents utilisent deja l'IA pour voler vos clients — voici comment reprendre l'avantage en 30 jours', chacun avec un angle emotionnel different." },
        { type: "summary", items: [
          "Une landing page a un seul objectif et un seul CTA",
          "Outils IA : Unbounce Smart Builder, Instapage AI, v0/Bolt",
          "Frameworks de copywriting : AIDA, PAS, FAB combines a l'IA",
          "Un changement de headline peut augmenter les conversions de 30-50%",
          "L'A/B testing IA teste des dizaines de variantes simultanement",
        ]},
      ],
      quiz: [
        {
          question: "Quel est l'unique objectif d'une landing page ?",
          options: ["Informer le visiteur", "Convertir le visiteur en lead ou client", "Presenter toute l'entreprise", "Afficher un maximum de produits"],
          correctIndex: 1,
          explanation: "Une landing page a un seul objectif : convertir le visiteur (en lead, en client, en inscrit). Tout element qui ne sert pas cet objectif est superflu.",
        },
        {
          question: "Que signifie PAS en copywriting ?",
          options: ["Prix, Avantage, Service", "Probleme, Agitation, Solution", "Public, Action, Strategie", "Performance, Analyse, Score"],
          correctIndex: 1,
          explanation: "PAS (Probleme, Agitation, Solution) est un framework de copywriting qui identifie le probleme du lecteur, amplifie la douleur, puis presente la solution.",
        },
        {
          question: "De combien un changement de headline peut-il augmenter les conversions ?",
          options: ["5-10%", "10-20%", "30-50%", "100-200%"],
          correctIndex: 2,
          explanation: "Les tests montrent qu'un changement de headline peut augmenter les conversions de 30 a 50%, ce qui en fait l'element le plus impactant de la page.",
        },
        {
          question: "Qu'est-ce que le multivariate testing ?",
          options: ["Tester 2 versions d'une page", "Tester des dizaines de variantes simultanement", "Tester sur differents navigateurs", "Tester la vitesse de chargement"],
          correctIndex: 1,
          explanation: "Le multivariate testing teste des dizaines de combinaisons de variantes simultanement (headlines, images, CTA), bien au-dela du simple A/B classique.",
        },
      ],
    },
    {
      number: 8,
      title: "Analytics et Data Marketing",
      description: "Exploiter les donnees marketing avec l'IA : analyse predictive, attribution, dashboards.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Le Data Marketing Propulse par l'IA" },
        { type: "paragraph", content: "Les donnees sont le carburant du marketing digital. Mais avoir des donnees ne suffit pas — il faut les analyser, les interpreter et en tirer des actions concretes. L'IA transforme des montagnes de donnees en insights actionnables en quelques secondes." },
        { type: "paragraph", content: "En 2026, Google Analytics 4 integre l'IA pour l'analyse predictive. Les outils comme Looker Studio AI, Mixpanel et Amplitude offrent des insights automatiques. Et Claude/GPT peuvent analyser vos exports CSV pour repondre a n'importe quelle question marketing." },
        { type: "heading", content: "Les KPIs Essentiels" },
        { type: "paragraph", content: "Les metriques qui comptent vraiment : le cout d'acquisition client (CAC), la valeur vie client (LTV), le taux de conversion par etape du funnel, le ROI par canal, et le taux de churn. L'IA peut calculer et predire chacune de ces metriques." },
        { type: "subheading", content: "Analyse Predictive" },
        { type: "paragraph", content: "L'analyse predictive utilise le machine learning pour anticiper les comportements : qui va acheter ? Qui risque de se desabonner ? Quel canal va performer le mieux le mois prochain ? Ces predictions permettent d'agir avant que les problemes ne surviennent." },
        { type: "video", videoId: "V1ERnMiKxkA", label: "Analytics marketing IA : de la donnee a l'action" },
        { type: "heading", content: "Attribution Multi-Touch" },
        { type: "paragraph", content: "L'attribution determine quel canal marketing merite le credit d'une conversion. Un client voit une pub Instagram, clique sur un email, puis achete via Google — quel canal a vendu ? L'IA calcule l'attribution multi-touch avec des modeles data-driven plus precis que les regles manuelles." },
        { type: "callout", content: "L'ere des cookies tiers est terminee. L'attribution IA basee sur les donnees first-party (vos propres donnees) devient indispensable. Investissez dans la collecte de donnees proprietaires." },
        { type: "diagram", label: "Pipeline Data Marketing IA", flow: "horizontal", nodes: [
          { label: "Collecte", sub: "GA4, CRM, email, social", color: "blue" },
          { label: "Analyse IA", sub: "Patterns, anomalies, trends", color: "purple" },
          { label: "Prediction", sub: "Comportements futurs", color: "emerald" },
          { label: "Action", sub: "Decisions basees sur les donnees", color: "amber" },
        ]},
        { type: "prompt-example", prompt: "Voici un export CSV de mes campagnes marketing des 6 derniers mois (canal, depense, leads, clients, CA). Analyse les performances, identifie le canal le plus rentable et recommande une reallocation budgetaire.", result: "Analyse complete avec ROI par canal, identification du canal le plus rentable (ex: email 12x ROI vs paid social 3x), et recommandation de reallouer 30% du budget paid social vers email et SEO." },
        { type: "key-point", content: "Le ratio LTV/CAC est le KPI ultime. Si la valeur vie client est 3x ou plus superieure au cout d'acquisition, votre business est sain. L'IA peut calculer ce ratio en temps reel pour chaque canal." },
        { type: "summary", items: [
          "L'IA transforme les donnees marketing en insights actionnables",
          "KPIs essentiels : CAC, LTV, taux de conversion, ROI par canal, churn",
          "L'analyse predictive anticipe les comportements clients",
          "L'attribution multi-touch IA est plus precise que les regles manuelles",
          "LTV/CAC > 3x = business sain — calculez par canal avec l'IA",
        ]},
      ],
      quiz: [
        {
          question: "Que signifie CAC en marketing ?",
          options: ["Content Automation Campaign", "Cout d'Acquisition Client", "Click Average Cost", "Campaign Analysis Chart"],
          correctIndex: 1,
          explanation: "CAC (Cout d'Acquisition Client) est le cout total pour acquerir un nouveau client, incluant toutes les depenses marketing et commerciales.",
        },
        {
          question: "Quel ratio LTV/CAC indique un business sain ?",
          options: ["LTV/CAC > 1x", "LTV/CAC > 2x", "LTV/CAC > 3x", "LTV/CAC > 10x"],
          correctIndex: 2,
          explanation: "Un ratio LTV/CAC superieur a 3x est considere comme sain : la valeur generee par un client est au moins 3 fois superieure a son cout d'acquisition.",
        },
        {
          question: "Qu'est-ce que l'attribution multi-touch ?",
          options: ["Mesurer les clics sur plusieurs ecrans", "Determiner quel canal merite le credit d'une conversion", "Analyser les touches sur un telephone", "Compter le nombre d'interactions"],
          correctIndex: 1,
          explanation: "L'attribution multi-touch determine la contribution de chaque point de contact (pub, email, organic) dans le parcours qui mene a une conversion.",
        },
        {
          question: "Pourquoi les donnees first-party sont-elles devenues essentielles ?",
          options: ["Elles sont gratuites", "L'ere des cookies tiers est terminee", "Elles sont plus belles", "Google les exige"],
          correctIndex: 1,
          explanation: "Avec la fin des cookies tiers, les donnees first-party (collectees directement aupres de vos utilisateurs) sont devenues indispensables pour l'attribution et le ciblage.",
        },
      ],
    },
    {
      number: 9,
      title: "Personal Branding avec l'IA",
      description: "Construire et amplifier votre marque personnelle grace a l'IA.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Le Personal Branding Augmente par l'IA" },
        { type: "paragraph", content: "En 2026, votre marque personnelle est votre actif le plus precieux. Les gens achetent a des personnes, pas a des entreprises. L'IA vous aide a construire, amplifier et maintenir votre personal brand a une echelle impossible manuellement." },
        { type: "paragraph", content: "L'IA n'est pas la pour creer un faux personnage — elle amplifie votre authenticite. Elle vous aide a articuler votre expertise, a produire du contenu regulierement, et a etre present sur plusieurs plateformes sans y passer tout votre temps." },
        { type: "heading", content: "Definir votre Positionnement" },
        { type: "paragraph", content: "L'IA peut analyser votre secteur, identifier les niches sous-exploitees et vous aider a trouver votre positionnement unique. Votre personal brand doit repondre a 3 questions : Quelle est votre expertise ? Quelle est votre perspective unique ? Pour qui creez-vous de la valeur ?" },
        { type: "subheading", content: "Votre Voice of Brand" },
        { type: "paragraph", content: "Alimentez l'IA avec vos meilleurs contenus, vos emails, vos presentations. Elle apprend votre style, votre vocabulaire, vos tournures. Ensuite, elle peut produire du contenu qui sonne comme vous, pas comme un robot." },
        { type: "video", videoId: "W9S3s7gEUqs", label: "Construire son personal branding avec l'IA" },
        { type: "callout", content: "Le piege du personal branding IA : publier du contenu generique qui ressemble a tout le monde. Votre avantage competitif, c'est votre experience vecue, vos echecs, vos opinions tranchees. L'IA amplifie votre voix, elle ne la remplace pas." },
        { type: "diagram", label: "Les 3 Piliers du Personal Brand", flow: "horizontal", nodes: [
          { label: "Expertise", sub: "Ce que vous savez faire", color: "purple" },
          { label: "Perspective", sub: "Votre vision unique", color: "blue" },
          { label: "Audience", sub: "Pour qui vous creez de la valeur", color: "emerald" },
        ]},
        { type: "tip", content: "Publiez au moins 3 fois par semaine sur votre plateforme principale (LinkedIn, Twitter/X). L'IA peut vous aider a preparer un mois de contenu en une seule session de 2 heures." },
        { type: "prompt-example", prompt: "Tu es mon ghostwriter. Voici 5 exemples de mes meilleurs posts LinkedIn. Analyse mon style, mon ton, mes themes recurrents. Puis genere 10 idees de posts et redige les 3 meilleurs en imitant mon style.", result: "Analyse de style (ton direct, anecdotes personnelles, chiffres concrets), 10 idees thematiques, et 3 posts complets avec hooks personnalises, contenu de valeur et CTA naturels." },
        { type: "summary", items: [
          "Votre personal brand est votre actif le plus precieux en 2026",
          "3 piliers : expertise, perspective unique, audience cible",
          "L'IA apprend votre style pour produire du contenu authentique",
          "Le piege : le contenu generique — gardez vos opinions et experiences",
          "Publiez 3x/semaine minimum — preparez un mois en 2 heures avec l'IA",
        ]},
      ],
      quiz: [
        {
          question: "Quelles sont les 3 questions fondamentales du personal branding ?",
          options: ["Combien je gagne ? Ou je travaille ? Quel age ai-je ?", "Quelle expertise ? Quelle perspective ? Pour qui ?", "Quel outil ? Quel budget ? Quel resultat ?", "Quel reseau ? Quelle frequence ? Quel format ?"],
          correctIndex: 1,
          explanation: "Les 3 questions cles : Quelle est votre expertise ? Quelle est votre perspective unique ? Pour qui creez-vous de la valeur ? Elles definissent votre positionnement.",
        },
        {
          question: "Quel est le piege du personal branding IA ?",
          options: ["Publier trop souvent", "Publier du contenu generique qui ressemble a tout le monde", "Ne pas utiliser assez d'IA", "Publier uniquement des images"],
          correctIndex: 1,
          explanation: "Le piege est de publier du contenu generique genere par l'IA sans y apporter votre experience, vos opinions et votre perspective unique.",
        },
        {
          question: "Comment l'IA apprend-elle votre style de communication ?",
          options: ["Elle devine automatiquement", "Vous l'alimentez avec vos meilleurs contenus et emails", "Elle copie des influenceurs", "Elle lit votre CV"],
          correctIndex: 1,
          explanation: "En alimentant l'IA avec vos meilleurs contenus, emails et presentations, elle apprend votre style, vocabulaire et tournures pour produire du contenu qui sonne comme vous.",
        },
        {
          question: "Quelle frequence de publication est recommandee ?",
          options: ["1 fois par mois", "1 fois par semaine", "3 fois par semaine minimum", "Chaque jour obligatoirement"],
          correctIndex: 2,
          explanation: "Publier au moins 3 fois par semaine sur votre plateforme principale est recommande pour construire une presence reguliere et rester visible dans les algorithmes.",
        },
      ],
    },
    {
      number: 10,
      title: "Video Marketing et IA",
      description: "Creer des videos marketing performantes avec l'IA : scripts, montage, sous-titres, shorts.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Le Video Marketing Propulse par l'IA" },
        { type: "paragraph", content: "La video est le format roi du marketing digital en 2026. Les Reels, TikToks, YouTube Shorts et les videos LinkedIn generent 5 a 10 fois plus d'engagement que le texte seul. L'IA rend la production video accessible a tous, meme sans competence technique." },
        { type: "paragraph", content: "De la generation de scripts a la creation de videos completes, en passant par le sous-titrage, le montage et la traduction, l'IA couvre l'ensemble du pipeline de production video." },
        { type: "heading", content: "Scripts et Storyboards IA" },
        { type: "paragraph", content: "Claude et GPT-5.4 excellent dans la redaction de scripts video. Le format ideal : un hook de 3 secondes (capturer l'attention), un contenu de valeur (enseigner ou divertir), et un CTA clair (s'abonner, commenter, acheter). L'IA peut generer des dizaines de variantes de scripts optimises." },
        { type: "subheading", content: "Generation de Videos IA" },
        { type: "paragraph", content: "Sora 2 d'OpenAI, Runway Gen-3, et Kling AI generent des clips video a partir de descriptions textuelles. HeyGen et Synthesia creent des videos avec des avatars IA realistes. Ideal pour les videos explicatives, les demos produit et le contenu educatif." },
        { type: "video", videoId: "Z-ikDaRJ2ZQ", label: "Video marketing IA : du script a la publication" },
        { type: "heading", content: "Optimisation et Distribution" },
        { type: "paragraph", content: "OpusClip et Descript decoupent automatiquement vos videos longues en shorts viraux. L'IA identifie les moments forts, ajoute les sous-titres, et optimise le format pour chaque plateforme. Un webinar de 1 heure peut devenir 20 shorts en quelques minutes." },
        { type: "key-point", content: "Les sous-titres augmentent le taux de visionnage de 80%. La majorite des videos sur mobile sont regardees sans le son. L'IA genere des sous-titres precis automatiquement." },
        { type: "diagram", label: "Pipeline Video Marketing IA", flow: "horizontal", nodes: [
          { label: "Script IA", sub: "Hook, contenu, CTA", color: "purple" },
          { label: "Production", sub: "Sora 2, HeyGen, camera", color: "blue" },
          { label: "Montage IA", sub: "OpusClip, Descript, sous-titres", color: "emerald" },
          { label: "Distribution", sub: "Multi-plateforme, shorts", color: "amber" },
        ]},
        { type: "prompt-example", prompt: "Ecris un script de Reel Instagram de 60 secondes sur le sujet : 'Comment l'IA peut doubler vos leads marketing'. Structure : hook 3 sec → probleme → 3 astuces → CTA.", result: "Script structure : Hook ('Vos concurrents generent 2x plus de leads que vous — voici comment ils font'), probleme (marketing manuel = lent), 3 astuces (segmentation IA, A/B testing auto, chatbot IA), CTA ('Suivez pour plus d'astuces IA')." },
        { type: "tip", content: "Le hook de 3 secondes determine si votre video sera vue. Testez 5 hooks differents pour chaque video et gardez celui qui retient le plus l'attention." },
        { type: "summary", items: [
          "La video genere 5-10x plus d'engagement que le texte seul",
          "L'IA couvre tout le pipeline : script, production, montage, distribution",
          "Les sous-titres augmentent le visionnage de 80%",
          "OpusClip transforme 1 video longue en 20 shorts automatiquement",
          "Le hook de 3 secondes est l'element le plus crucial",
        ]},
      ],
      quiz: [
        {
          question: "Combien de fois plus d'engagement la video genere-t-elle par rapport au texte ?",
          options: ["2x", "5-10x", "20x", "50x"],
          correctIndex: 1,
          explanation: "La video genere 5 a 10 fois plus d'engagement que le texte seul, ce qui en fait le format roi du marketing digital en 2026.",
        },
        {
          question: "De combien les sous-titres augmentent-ils le taux de visionnage ?",
          options: ["20%", "40%", "60%", "80%"],
          correctIndex: 3,
          explanation: "Les sous-titres augmentent le taux de visionnage de 80%, car la majorite des videos sur mobile sont regardees sans le son.",
        },
        {
          question: "Que fait OpusClip ?",
          options: ["Genere des images", "Decoupe les videos longues en shorts automatiquement", "Traduit des textes", "Cree des podcasts"],
          correctIndex: 1,
          explanation: "OpusClip utilise l'IA pour decouper automatiquement les videos longues en shorts viraux, en identifiant les moments forts et en ajoutant des sous-titres.",
        },
        {
          question: "Quelle est la duree ideale du hook d'une video courte ?",
          options: ["1 seconde", "3 secondes", "10 secondes", "30 secondes"],
          correctIndex: 1,
          explanation: "Le hook doit capturer l'attention en 3 secondes. Au-dela, le spectateur scroll. C'est l'element le plus crucial d'une video courte.",
        },
      ],
    },
    {
      number: 11,
      title: "Strategie Marketing IA Complete",
      description: "Assembler toutes les pieces pour creer une strategie marketing digitale integree et coherente.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Votre Strategie Marketing IA Integree" },
        { type: "paragraph", content: "Vous maitrisez maintenant chaque composante : SEO, contenu, social media, email, publicite, analytics, personal branding et video. Il est temps d'assembler le tout en une strategie coherente ou chaque element renforce les autres." },
        { type: "paragraph", content: "Une strategie marketing integree n'est pas une collection de tactiques isolees — c'est un ecosysteme ou le contenu alimente le SEO, le SEO alimente le trafic, le trafic alimente l'email, l'email alimente les ventes, et les ventes financent la publicite." },
        { type: "heading", content: "Le Funnel Marketing IA" },
        { type: "subheading", content: "Top of Funnel (TOFU) — Attirer" },
        { type: "paragraph", content: "Objectif : attirer du trafic qualifie. Leviers IA : SEO (articles optimises), reseaux sociaux (contenu IA), video (YouTube, Reels), publicite (Google/Meta). L'IA produit le volume, votre expertise attire la qualite." },
        { type: "subheading", content: "Middle of Funnel (MOFU) — Engager" },
        { type: "paragraph", content: "Objectif : transformer les visiteurs en leads. Leviers IA : lead magnets (ebooks, templates generes par IA), sequences email (personnalisation IA), webinaires, chatbot IA pour qualifier les leads." },
        { type: "subheading", content: "Bottom of Funnel (BOFU) — Convertir" },
        { type: "paragraph", content: "Objectif : transformer les leads en clients. Leviers IA : landing pages optimisees, sequences de vente personnalisees, demos sur-mesure, temoignages et preuves sociales mises en avant par l'IA." },
        { type: "video", videoId: "V1ERnMiKxkA", label: "Construire sa strategie marketing IA complete" },
        { type: "diagram", label: "Le Funnel Marketing IA", flow: "vertical", nodes: [
          { label: "TOFU — Attirer", sub: "SEO, social, video, ads", color: "blue" },
          { label: "MOFU — Engager", sub: "Lead magnets, email, chatbot", color: "purple" },
          { label: "BOFU — Convertir", sub: "Landing pages, demos, vente", color: "emerald" },
          { label: "Retention", sub: "Onboarding, upsell, fidelisation", color: "amber" },
        ]},
        { type: "heading", content: "Plan d'Action 30-60-90 Jours" },
        { type: "paragraph", content: "Jours 1-30 : audit de l'existant, configuration des outils IA, creation des premiers contenus SEO et sociaux. Jours 31-60 : lancement des sequences email, premiere campagne publicitaire, creation du lead magnet. Jours 61-90 : optimisation basee sur les donnees, scaling des canaux performants, automatisation des workflows repetitifs." },
        { type: "tip", content: "Ne tentez pas de tout lancer en meme temps. Concentrez-vous sur un canal principal (generalement le SEO ou LinkedIn) et ajoutez progressivement les autres. La constance bat la perfection." },
        { type: "prompt-example", prompt: "Cree un plan marketing digital IA sur 90 jours pour un consultant freelance en transformation digitale. Budget : 500 euros/mois. Objectif : generer 10 leads qualifies par mois.", result: "Plan detaille : J1-30 (LinkedIn + 2 articles SEO + profil optimise), J31-60 (lead magnet + sequence email + premiere campagne LinkedIn Ads a 200 euros), J61-90 (optimisation + content repurposing + scaling a 15 leads/mois)." },
        { type: "summary", items: [
          "Une strategie integree est un ecosysteme, pas des tactiques isolees",
          "Funnel : TOFU (attirer) → MOFU (engager) → BOFU (convertir) → Retention",
          "Plan 30-60-90 : audit, lancement, optimisation progressive",
          "Concentrez-vous sur un canal principal puis etendez",
          "La constance bat la perfection — publiez regulierement",
        ]},
      ],
      quiz: [
        {
          question: "Que signifie TOFU en marketing ?",
          options: ["Total Organic Funnel Usage", "Top of Funnel", "Tactical Online Framework Upgrade", "Target Opportunity For Upselling"],
          correctIndex: 1,
          explanation: "TOFU (Top of Funnel) designe la phase d'attraction du funnel marketing, ou l'objectif est d'attirer du trafic qualifie via SEO, social media, video et publicite.",
        },
        {
          question: "Quel est l'objectif du MOFU (Middle of Funnel) ?",
          options: ["Attirer du trafic", "Transformer les visiteurs en leads", "Vendre directement", "Fideliser les clients"],
          correctIndex: 1,
          explanation: "Le MOFU vise a transformer les visiteurs en leads grace aux lead magnets, sequences email, webinaires et chatbots IA de qualification.",
        },
        {
          question: "Que faire les 30 premiers jours du plan marketing ?",
          options: ["Lancer des publicites massives", "Auditer, configurer les outils et creer les premiers contenus", "Embaucher une equipe", "Tout automatiser"],
          correctIndex: 1,
          explanation: "Les 30 premiers jours sont consacres a l'audit de l'existant, la configuration des outils IA, et la creation des premiers contenus SEO et sociaux.",
        },
        {
          question: "Quel conseil est donne pour le lancement ?",
          options: ["Lancer tout en meme temps", "Se concentrer sur un canal principal et etendre progressivement", "Depenser le maximum en publicite", "Attendre d'avoir tout parfait"],
          correctIndex: 1,
          explanation: "Il est recommande de se concentrer sur un canal principal (SEO ou LinkedIn) et d'ajouter progressivement les autres. La constance bat la perfection.",
        },
      ],
    },
    {
      number: 12,
      title: "Mesurer et Optimiser ses Resultats",
      description: "Suivre vos performances, identifier les opportunites et scaler ce qui fonctionne.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "L'Optimisation Continue avec l'IA" },
        { type: "paragraph", content: "Le marketing digital n'est pas un projet a date de fin — c'est un processus d'amelioration continue. L'IA excelle dans l'analyse de performance et l'identification d'opportunites d'optimisation que l'oeil humain pourrait manquer." },
        { type: "paragraph", content: "Le cycle d'optimisation : mesurer les resultats, analyser les donnees avec l'IA, identifier les opportunites, implementer les changements, puis mesurer a nouveau. Ce cycle doit tourner en permanence." },
        { type: "heading", content: "Tableaux de Bord Marketing" },
        { type: "paragraph", content: "Creez un dashboard unique qui centralise toutes vos metriques : trafic (GA4), engagement social (natifs + outils tiers), email (taux d'ouverture, clics), publicite (CPA, ROAS), et conversions. L'IA peut generer des rapports hebdomadaires automatiques avec insights et recommandations." },
        { type: "subheading", content: "Les Metriques North Star" },
        { type: "paragraph", content: "Chaque business a une metrique North Star — celle qui reflette le mieux la valeur creee. Pour un SaaS : le MRR (Monthly Recurring Revenue). Pour un e-commerce : le CA par visiteur. Pour un consultant : le nombre de leads qualifies. Identifiez la votre et optimisez tout autour." },
        { type: "video", videoId: "W9S3s7gEUqs", label: "Mesurer et optimiser ses resultats marketing" },
        { type: "heading", content: "Scaling Intelligent" },
        { type: "paragraph", content: "Quand un canal fonctionne, la tentation est de doubler le budget immediatement. L'IA vous aide a scaler intelligemment : elle identifie le point de rendement decroissant, suggere des budgets optimaux, et detecte la saturation d'audience avant qu'elle ne devienne un probleme." },
        { type: "key-point", content: "Doublez ce qui fonctionne, arretez ce qui ne fonctionne pas. Cela semble evident, mais la plupart des marketeurs persistent avec des canaux sous-performants par inertie. L'IA vous donne les donnees pour prendre des decisions objectives." },
        { type: "callout", content: "Felicitations ! Vous avez termine le cours complet de Marketing Digital IA. Vous avez les outils et les strategies pour transformer votre marketing. L'etape suivante : appliquez le plan 30-60-90 des maintenant." },
        { type: "diagram", label: "Cycle d'Optimisation Continue", flow: "cycle", nodes: [
          { label: "Mesurer", sub: "Collecter les metriques cles", color: "blue" },
          { label: "Analyser", sub: "IA identifie patterns et opportunites", color: "purple" },
          { label: "Implementer", sub: "Appliquer les optimisations", color: "emerald" },
        ]},
        { type: "prompt-example", prompt: "Voici mes metriques marketing du mois : SEO (5000 visites, 50 leads), LinkedIn (2000 impressions, 15 leads), Email (3000 envoyes, 30% ouverture, 20 leads), Ads (1000 euros depenses, 25 leads). Analyse et recommande les optimisations.", result: "Analyse : SEO meilleur CPA (0 euro/lead), email meilleur taux de conversion (0,67%). Recommandations : doubler la production SEO, optimiser les objets d'emails (30% ouverture = ameliorable), reduire le budget ads et reallouer vers le contenu organic." },
        { type: "tip", content: "Faites un bilan mensuel de 30 minutes avec l'IA : exportez vos donnees, demandez une analyse complete, et implementez les 3 recommandations les plus impactantes. C'est le minimum pour une optimisation continue efficace." },
        { type: "summary", items: [
          "Le marketing est un processus d'amelioration continue, pas un projet fini",
          "Cycle : mesurer → analyser avec l'IA → implementer → mesurer",
          "Identifiez votre metrique North Star et optimisez tout autour",
          "Doublez ce qui fonctionne, arretez ce qui ne fonctionne pas",
          "Bilan mensuel de 30 minutes avec l'IA = optimisation continue efficace",
        ]},
      ],
      quiz: [
        {
          question: "Qu'est-ce qu'une metrique North Star ?",
          options: ["La metrique la plus facile a mesurer", "La metrique qui reflette le mieux la valeur creee par votre business", "Le nombre total de visiteurs", "Le nombre de followers"],
          correctIndex: 1,
          explanation: "La metrique North Star est celle qui reflette le mieux la valeur creee : MRR pour un SaaS, CA/visiteur pour un e-commerce, leads qualifies pour un consultant.",
        },
        {
          question: "Que signifie ROAS en marketing ?",
          options: ["Rate of Audience Size", "Return on Ad Spend", "Ranking of All Sources", "Revenue Over Average Sales"],
          correctIndex: 1,
          explanation: "ROAS (Return on Ad Spend) mesure le revenu genere pour chaque euro depense en publicite. Un ROAS de 5x signifie 5 euros de revenu pour 1 euro depense.",
        },
        {
          question: "Quel est le risque de scaler trop vite un canal publicitaire ?",
          options: ["Aucun risque", "Saturation d'audience et rendements decroissants", "Le compte est banni", "Les prix baissent"],
          correctIndex: 1,
          explanation: "Scaler trop vite un canal peut mener a la saturation d'audience (montrer la meme pub trop souvent) et a des rendements decroissants ou le CPA augmente.",
        },
        {
          question: "A quelle frequence faire un bilan d'optimisation ?",
          options: ["Tous les jours", "Toutes les semaines", "Tous les mois (minimum 30 min avec l'IA)", "Tous les 6 mois"],
          correctIndex: 2,
          explanation: "Un bilan mensuel de 30 minutes avec l'IA est le minimum recommande : exporter les donnees, analyser, et implementer les 3 recommandations les plus impactantes.",
        },
      ],
    },
  ],
};

export default content;
