import type { CourseContent } from "../types";

const content: CourseContent = {
  slug: "maitriser-outils-ia",
  chapters: [
    {
      number: 1,
      title: "Panorama des Outils IA en 2026",
      description: "Tour d'horizon des catégories d'outils IA et comment choisir les bons.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "L'écosystème des outils IA en 2026" },
        { type: "paragraph", content: "En 2026, le paysage des outils IA est immense : chatbots conversationnels, générateurs d'images, outils vidéo, assistants audio, outils de code, automatisation... Il existe des centaines d'outils, mais une dizaine dominent chaque catégorie. Ce cours vous guide vers les meilleurs." },
        { type: "subheading", content: "Les grandes catégories" },
        { type: "paragraph", content: "Chatbots et assistants texte : ChatGPT, Claude, Gemini, Mistral. Génération d'images : Midjourney, DALL-E, Stable Diffusion, Firefly. Vidéo : Sora 2, Runway Gen-3, Pika, Kling. Audio et voix : ElevenLabs, Suno, Udio. Code : Cursor, GitHub Copilot, Claude Code. Recherche : Perplexity. Automatisation : Make, Zapier." },
        { type: "subheading", content: "Comment choisir ses outils ?" },
        { type: "paragraph", content: "Trois critères principaux : votre cas d'usage (texte, image, code ?), votre budget (gratuit, abonnement, paiement à l'usage), et votre niveau technique. Commencez toujours par les versions gratuites avant de passer aux offres payantes." },
        { type: "tip", content: "La règle des 3 outils : choisissez un outil généraliste (ChatGPT ou Claude), un outil spécialisé pour votre métier, et un outil d'automatisation. C'est suffisant pour transformer votre productivité." },
        { type: "key-point", content: "En 2026, les meilleurs outils IA sont accessibles sans connaissances techniques. L'interface en langage naturel a démocratisé l'accès à des capacités autrefois réservées aux ingénieurs." },
        { type: "diagram", label: "Les 7 Catégories d'Outils IA en 2026", flow: "horizontal", nodes: [
          { label: "Chatbots", sub: "ChatGPT, Claude, Gemini", color: "purple" },
          { label: "Images", sub: "Midjourney, DALL-E, Firefly", color: "blue" },
          { label: "Vidéo", sub: "Sora 2, Runway, Kling", color: "emerald" },
          { label: "Audio", sub: "ElevenLabs, Suno, Udio", color: "amber" },
          { label: "Code", sub: "Cursor, Copilot, Claude Code", color: "pink" },
        ]},
        { type: "video", videoId: "ad79nYk2keg",
      videoDurationMinutes: 5, label: "L'Intelligence Artificielle expliquée en 5 minutes" },
        { type: "summary", items: [
          "L'écosystème IA se divise en 7 catégories principales",
          "Une dizaine d'outils dominent chaque catégorie",
          "Critères de choix : cas d'usage, budget, niveau technique",
          "Commencez toujours par les versions gratuites",
          "3 outils bien choisis suffisent pour transformer votre productivité"
        ]},
      ],
      quiz: [
        { question: "Combien d'outils faut-il maîtriser pour transformer sa productivité ?", options: ["1 seul outil", "3 outils bien choisis", "10 outils différents", "Tous les outils disponibles"], correctIndex: 1, explanation: "Trois outils bien choisis (un généraliste, un spécialisé, un automatisation) suffisent pour transformer significativement sa productivité." },
        { question: "Quel est le premier critère pour choisir un outil IA ?", options: ["Le prix", "La popularité sur les réseaux sociaux", "Votre cas d'usage", "La date de sortie"], correctIndex: 2, explanation: "Le cas d'usage est le premier critère : à quoi voulez-vous utiliser l'IA ? Texte, images, code, automatisation ? Chaque besoin a ses meilleurs outils." },
        { question: "Quelle est la bonne pratique avant de payer un abonnement IA ?", options: ["Acheter immédiatement la version pro", "Tester d'abord la version gratuite", "Demander à un ami", "Lire toutes les reviews"], correctIndex: 1, explanation: "Toujours tester la version gratuite d'abord. La plupart des outils IA proposent des essais gratuits qui permettent d'évaluer l'adéquation avec vos besoins." },
        { question: "Qu'est-ce qui a rendu les outils IA accessibles à tous en 2026 ?", options: ["La baisse du prix des ordinateurs", "L'interface en langage naturel", "La formation obligatoire à l'école", "Les réseaux sociaux"], correctIndex: 1, explanation: "L'interface en langage naturel (écrire simplement ce qu'on veut) a démocratisé l'accès aux outils IA, sans nécessiter de connaissances techniques." },
      ],
    },
    {
      number: 2,
      title: "ChatGPT et GPT-5.4 — Le Standard de l'Industrie",
      description: "Maîtriser ChatGPT : modes, Custom GPTs, Computer Use et astuces avancées.",
      estimatedMinutes: 10,
      sections: [
        { type: "heading", content: "ChatGPT en 2026 : bien plus qu'un chatbot" },
        { type: "paragraph", content: "ChatGPT, lancé par OpenAI en 2022, est devenu la référence mondiale avec plus de 500 millions d'utilisateurs actifs en 2026. GPT-5.4, sorti le 5 mars 2026, est disponible en trois variantes : Standard, Thinking (raisonnement avancé) et Pro (capacité maximale)." },
        { type: "subheading", content: "Les modes de ChatGPT" },
        { type: "paragraph", content: "Mode Standard : réponses rapides pour les tâches quotidiennes. Mode Thinking : le modèle réfléchit étape par étape avant de répondre — idéal pour les problèmes complexes, le code ou les mathématiques. Mode Pro : accès à GPT-5.4 Pro avec les meilleures performances pour les tâches les plus exigeantes." },
        { type: "subheading", content: "Custom GPTs — Créer votre assistant personnalisé" },
        { type: "paragraph", content: "Les Custom GPTs permettent de créer des assistants IA spécialisés sans coder. Vous définissez des instructions, chargez des documents de référence, et connectez des outils. Exemple : un Custom GPT pour rédiger uniquement dans le style de votre marque, avec accès à votre guide de style." },
        { type: "subheading", content: "Computer Use — L'IA qui contrôle votre ordinateur" },
        { type: "paragraph", content: "GPT-5.4 intègre nativement le Computer Use : il peut naviguer sur le web, remplir des formulaires, extraire des données, et effectuer des tâches répétitives sur votre ordinateur. C'est la fonctionnalité la plus révolutionnaire de 2026 pour les agents IA autonomes." },
        { type: "callout", content: "Astuce : utilisez le mode Thinking pour les analyses complexes, le code difficile ou les décisions importantes. La qualité des réponses est significativement supérieure au mode Standard, mais la réponse prend plus de temps." },
        { type: "diagram", label: "Les 3 Modes de ChatGPT GPT-5.4", flow: "horizontal", nodes: [
          { label: "Standard", sub: "Réponses rapides, tâches quotidiennes", color: "blue" },
          { label: "Thinking", sub: "Raisonnement étape par étape, problèmes complexes", color: "purple" },
          { label: "Pro", sub: "Capacité maximale, usage intensif", color: "emerald" },
        ]},
        { type: "video", videoId: "7ell8KEbhJo",
      videoDurationMinutes: 27, label: "Comment fonctionne ChatGPT ?" },
        { type: "summary", items: [
          "GPT-5.4 existe en 3 variantes : Standard, Thinking et Pro",
          "1,05 million de tokens de contexte — l'équivalent d'un roman entier",
          "Les Custom GPTs permettent de créer des assistants spécialisés sans code",
          "Computer Use : l'IA peut contrôler votre ordinateur de façon autonome",
          "33% moins d'hallucinations que GPT-5.2"
        ]},
      ],
      quiz: [
        { question: "Combien de variantes propose GPT-5.4 ?", options: ["1 (Standard seulement)", "2 (Standard et Pro)", "3 (Standard, Thinking, Pro)", "4 (Lite, Standard, Thinking, Pro)"], correctIndex: 2, explanation: "GPT-5.4 est disponible en 3 variantes : Standard pour les tâches quotidiennes, Thinking pour le raisonnement avancé, et Pro pour les capacités maximales." },
        { question: "Que permet le Computer Use dans ChatGPT ?", options: ["Accélérer votre ordinateur", "Contrôler votre ordinateur de façon autonome", "Réparer les bugs système", "Installer des logiciels"], correctIndex: 1, explanation: "Le Computer Use permet à GPT-5.4 de naviguer sur le web, remplir des formulaires et effectuer des tâches répétitives sur votre ordinateur, comme un opérateur humain." },
        { question: "Dans quel mode faut-il utiliser ChatGPT pour résoudre un problème de code complexe ?", options: ["Mode Standard", "Mode Light", "Mode Thinking", "Mode Basic"], correctIndex: 2, explanation: "Le mode Thinking est recommandé pour les problèmes complexes car le modèle réfléchit étape par étape avant de répondre, produisant des résultats de meilleure qualité." },
        { question: "Que sont les Custom GPTs ?", options: ["Des versions modifiées de GPT-4", "Des assistants IA spécialisés créés sans code", "Des plugins payants", "Des versions hors ligne de ChatGPT"], correctIndex: 1, explanation: "Les Custom GPTs permettent à n'importe qui de créer un assistant IA spécialisé en définissant des instructions et en chargeant des documents de référence, sans aucune programmation." },
      ],
    },
    {
      number: 3,
      title: "Claude 4.6 — L'IA la Plus Précise",
      description: "Maîtriser Claude : Opus/Sonnet/Haiku, Projects, artifacts et Claude Code.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Claude par Anthropic : précision et honnêteté" },
        { type: "paragraph", content: "Claude, développé par Anthropic, se distingue par sa précision, son honnêteté et sa capacité à admettre ses incertitudes. En 2026, Claude 4.6 est disponible en trois versions : Opus 4.6 (le plus puissant), Sonnet 4.6 (le meilleur rapport qualité/vitesse) et Haiku 4.5 (rapide et économique)." },
        { type: "subheading", content: "Claude Opus 4.6 — La puissance maximale" },
        { type: "paragraph", content: "Opus 4.6 offre 1 million de tokens de contexte et un horizon de tâche de 14,5 heures — le plus long de tous les modèles. Il excelle en raisonnement complexe, en analyse de documents longs, en codage avancé et en recherche approfondie." },
        { type: "subheading", content: "Les Projects — Votre espace de travail persistant" },
        { type: "paragraph", content: "Les Projects permettent de donner à Claude un contexte permanent : chargez vos documents, définissez votre style, vos préférences et le contexte de votre projet. Claude s'en souvient entre chaque conversation. Idéal pour les projets longs ou les équipes." },
        { type: "subheading", content: "Les Artifacts — Contenu structuré en temps réel" },
        { type: "paragraph", content: "Les Artifacts affichent le contenu structuré (code, HTML, SVG, tableaux) dans un panneau séparé en temps réel. Vous pouvez prévisualiser directement du code HTML ou modifier le contenu interactivement. C'est particulièrement puissant pour le développement web." },
        { type: "subheading", content: "Claude Code — Votre développeur IA en ligne de commande" },
        { type: "paragraph", content: "Claude Code est un outil CLI qui intègre Claude directement dans votre terminal. Il peut lire, écrire et modifier des fichiers, exécuter des commandes, et gérer des projets entiers de façon autonome. Les développeurs le considèrent comme l'outil de codage IA le plus avancé de 2026." },
        { type: "tip", content: "Pour les tâches créatives et rédactionnelles, Claude surpasse souvent ChatGPT grâce à sa nuance et sa capacité à respecter des instructions complexes. Essayez Claude pour vos emails importants, vos rapports et vos analyses." },
        { type: "diagram", label: "Les 3 Versions de Claude 4.6", flow: "horizontal", nodes: [
          { label: "Haiku 4.5", sub: "Rapide et économique — tâches simples", color: "blue" },
          { label: "Sonnet 4.6", sub: "Équilibre qualité/vitesse — usage quotidien", color: "purple" },
          { label: "Opus 4.6", sub: "Puissance maximale — 14,5h d'autonomie", color: "emerald" },
        ]},
        { type: "diagram", label: "Fonctionnalités Clés de Claude", flow: "vertical", nodes: [
          { label: "Projects", sub: "Contexte permanent entre sessions", color: "amber" },
          { label: "Artifacts", sub: "Code et HTML en temps réel", color: "blue" },
          { label: "Claude Code", sub: "Gestion de projets depuis le terminal", color: "purple" },
        ]},
        { type: "summary", items: [
          "Claude 4.6 existe en 3 versions : Opus (puissant), Sonnet (équilibré), Haiku (rapide)",
          "1 million de tokens de contexte — l'équivalent de 750 000 mots",
          "Les Projects donnent à Claude un contexte permanent entre les sessions",
          "Les Artifacts affichent le code et le HTML en temps réel dans un panneau séparé",
          "Claude Code gère des projets entiers directement depuis le terminal"
        ]},
      ],
      quiz: [
        { question: "Quelle est la durée maximale d'une tâche autonome pour Claude Opus 4.6 ?", options: ["1 heure", "4 heures", "14,5 heures", "24 heures"], correctIndex: 2, explanation: "Claude Opus 4.6 peut maintenir une tâche pendant 14,5 heures d'affilée — c'est le plus long horizon de tâche de tous les modèles IA en 2026." },
        { question: "À quoi servent les Projects dans Claude ?", options: ["Organiser les fichiers sur votre ordinateur", "Donner à Claude un contexte permanent entre sessions", "Créer des images", "Partager des conversations avec des amis"], correctIndex: 1, explanation: "Les Projects permettent de charger des documents et définir un contexte que Claude conserve entre toutes vos conversations liées au projet." },
        { question: "Qu'est-ce que Claude Code ?", options: ["Un langage de programmation créé par Anthropic", "Un outil CLI qui intègre Claude dans le terminal", "Un éditeur de code en ligne", "Une extension VS Code"], correctIndex: 1, explanation: "Claude Code est un outil en ligne de commande qui intègre Claude directement dans le terminal pour lire, écrire et modifier des fichiers de code de façon autonome." },
        { question: "Pour quelle tâche Claude est-il particulièrement recommandé ?", options: ["La génération d'images", "La création de vidéos", "La rédaction nuancée et l'analyse complexe", "Le montage audio"], correctIndex: 2, explanation: "Claude excelle dans la rédaction nuancée, l'analyse complexe et le respect d'instructions détaillées, ce qui en fait le choix privilégié pour les emails importants et les rapports." },
      ],
    },
    {
      number: 4,
      title: "Gemini 3.1 — L'IA de Google",
      description: "Intégration G Suite, Gemini Advanced, analyse de documents et multimodalité.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Gemini 3.1 : l'IA native dans l'écosystème Google" },
        { type: "paragraph", content: "Gemini 3.1, développé par Google DeepMind, est le modèle IA le plus intégré dans un écosystème d'applications. Nativement multimodal, il traite simultanément texte, images, audio, vidéo et code. Son intégration dans Gmail, Google Docs, Sheets et Drive en fait un outil incontournable pour les utilisateurs Google." },
        { type: "subheading", content: "Gemini Advanced — La version premium" },
        { type: "paragraph", content: "Gemini Advanced (inclus dans Google One Premium) donne accès à Gemini 3.1 Pro avec 1 million de tokens de contexte. Il peut analyser des documents PDF entiers, des tableurs complexes ou des heures de vidéo en une seule conversation." },
        { type: "subheading", content: "Intégration dans Google Workspace" },
        { type: "paragraph", content: "Dans Gmail : résumé automatique d'emails, rédaction de réponses, traduction instantanée. Dans Google Docs : génération de contenu, amélioration de style, résumé de documents. Dans Sheets : analyse de données, génération de formules complexes, visualisation automatique. Dans Meet : transcription en temps réel, résumé de réunion." },
        { type: "subheading", content: "Les points forts de Gemini" },
        { type: "paragraph", content: "Gemini 3.1 excelle dans : l'analyse de documents très longs (jusqu'à 1M tokens), la recherche web en temps réel (Google Search intégré), le traitement multimodal natif, et l'intégration dans les flux de travail Google. Son score de 77,1% sur ARC-AGI-2 le place parmi les meilleurs modèles de raisonnement." },
        { type: "callout", content: "Si vous êtes déjà dans l'écosystème Google (Gmail, Drive, Docs), Gemini est votre meilleur choix car il accède directement à vos fichiers et emails sans copier-coller." },
        { type: "diagram", label: "Gemini dans l'Écosystème Google", flow: "horizontal", nodes: [
          { label: "Gmail", sub: "Résumé et rédaction d'emails", color: "blue" },
          { label: "Google Docs", sub: "Génération et amélioration de contenu", color: "purple" },
          { label: "Google Sheets", sub: "Analyse et formules automatiques", color: "emerald" },
          { label: "Google Meet", sub: "Transcription et résumé de réunion", color: "amber" },
        ]},
        { type: "summary", items: [
          "Gemini 3.1 est nativement multimodal : texte, image, audio, vidéo, code",
          "1 million de tokens de contexte dans Gemini Advanced",
          "Intégré dans Gmail, Docs, Sheets, Meet — sans copier-coller",
          "Score de 77,1% sur ARC-AGI-2, parmi les meilleurs en raisonnement",
          "Accès à Google Search en temps réel pour des réponses toujours à jour"
        ]},
      ],
      quiz: [
        { question: "Quelle est la grande force de Gemini par rapport aux autres LLM ?", options: ["Il est gratuit pour tous", "Son intégration native dans l'écosystème Google", "Il parle plus de langues", "Il génère des images plus rapidement"], correctIndex: 1, explanation: "La grande force de Gemini est son intégration directe dans Gmail, Google Docs, Sheets et Drive, permettant de travailler sans copier-coller." },
        { question: "Qu'est-ce que la multimodalité native de Gemini ?", options: ["Il fonctionne sur plusieurs appareils", "Il traite simultanément texte, images, audio et vidéo", "Il supporte plusieurs langues", "Il peut être utilisé par plusieurs personnes"], correctIndex: 1, explanation: "La multimodalité native signifie que Gemini peut traiter et combiner différents types de données (texte, images, audio, vidéo) dans une même conversation." },
        { question: "Quel abonnement donne accès à Gemini Advanced ?", options: ["Google One Premium", "YouTube Premium", "Google Play Pass", "Chrome Enterprise"], correctIndex: 0, explanation: "Gemini Advanced est inclus dans l'abonnement Google One Premium, qui inclut aussi du stockage supplémentaire et d'autres avantages Google." },
        { question: "Quel est le score de Gemini 3.1 sur ARC-AGI-2 ?", options: ["55,3%", "68,9%", "77,1%", "92,4%"], correctIndex: 2, explanation: "Gemini 3.1 Pro obtient 77,1% sur le benchmark ARC-AGI-2, un test de raisonnement abstrait, le plaçant parmi les meilleurs modèles de 2026." },
      ],
    },
    {
      number: 5,
      title: "Midjourney V7/V8 — L'Art de la Génération d'Images",
      description: "Commandes /imagine, paramètres, styles et techniques avancées de Midjourney.",
      estimatedMinutes: 10,
      sections: [
        { type: "heading", content: "Midjourney : le leader incontesté de la génération d'images" },
        { type: "paragraph", content: "Midjourney est reconnu comme l'outil de génération d'images IA de la plus haute qualité esthétique. Les versions V7 et V8 (2025-2026) ont franchi un cap avec une cohérence des personnages, une gestion de la lumière et des détails photographiques sans précédent." },
        { type: "subheading", content: "La commande de base : /imagine" },
        { type: "paragraph", content: "Tout commence par /imagine suivi de votre description (prompt). Exemple : /imagine prompt: a golden hour portrait of a young woman in Paris, film photography, 35mm, bokeh. Plus votre description est précise et riche, meilleur sera le résultat." },
        { type: "subheading", content: "Les paramètres essentiels" },
        { type: "paragraph", content: "Ratio d'aspect : --ar 16:9 (paysage), --ar 9:16 (portrait), --ar 1:1 (carré). Qualité : --q 2 pour la qualité maximale. Style : --style raw pour un rendu plus réaliste, --style expressive pour plus de créativité. Version : --v 8 pour la dernière version. Négatifs : --no text, logo pour exclure ces éléments." },
        { type: "subheading", content: "Techniques avancées" },
        { type: "paragraph", content: "Image reference (--iref) : utilisez une image existante comme référence de style. Character reference (--cref) : maintenez la cohérence d'un personnage entre plusieurs images. Seed (--seed) : reproduisez exactement le même résultat. Style reference (--sref) : copiez le style d'une image de référence." },
        { type: "subheading", content: "Les modes de Midjourney" },
        { type: "paragraph", content: "Mode Fast : génération rapide, consomme des crédits. Mode Relax : gratuit mais plus lent. Mode Turbo : génération ultra-rapide pour les abonnés Pro. Stealth Mode : vos créations restent privées (abonnement Pro requis)." },
        { type: "tip", content: "Pour des portraits professionnels : utilisez toujours --ar 4:5, ajoutez 'professional lighting, sharp focus, 85mm portrait lens' et testez --style raw pour un rendu moins artificiel." },
        { type: "diagram", label: "Paramètres Essentiels Midjourney", flow: "horizontal", nodes: [
          { label: "--ar", sub: "Ratio d'aspect (16:9, 9:16, 1:1)", color: "blue" },
          { label: "--style", sub: "raw (réaliste) ou expressive (créatif)", color: "purple" },
          { label: "--cref", sub: "Cohérence d'un personnage", color: "emerald" },
          { label: "--sref", sub: "Copier le style d'une image", color: "amber" },
        ]},
        { type: "summary", items: [
          "La commande de base est /imagine suivi d'une description précise",
          "Paramètres clés : --ar (ratio), --q (qualité), --style, --v (version)",
          "Character Reference (--cref) maintient la cohérence d'un personnage",
          "Style Reference (--sref) copie le style d'une image existante",
          "Abonnement requis : Basic (10$/mois), Standard (30$), Pro (60$), Mega (120$)"
        ]},
      ],
      quiz: [
        { question: "Quelle commande utilise-t-on pour générer une image sur Midjourney ?", options: ["/create", "/generate", "/imagine", "/draw"], correctIndex: 2, explanation: "La commande /imagine est la commande principale de Midjourney pour générer des images. Elle est suivie du mot 'prompt:' puis de votre description." },
        { question: "Quel paramètre définit le ratio d'aspect d'une image sur Midjourney ?", options: ["--size", "--ar", "--ratio", "--format"], correctIndex: 1, explanation: "Le paramètre --ar (aspect ratio) définit le ratio d'aspect. Exemples : --ar 16:9 pour un format paysage, --ar 9:16 pour un portrait, --ar 1:1 pour un carré." },
        { question: "À quoi sert le paramètre --cref dans Midjourney V8 ?", options: ["Choisir une couleur de référence", "Maintenir la cohérence d'un personnage entre plusieurs images", "Copier le style d'un artiste", "Définir la résolution de sortie"], correctIndex: 1, explanation: "--cref (character reference) permet de maintenir la cohérence visuelle d'un personnage à travers plusieurs générations d'images." },
        { question: "Quel mode Midjourney est gratuit mais plus lent ?", options: ["Fast Mode", "Turbo Mode", "Relax Mode", "Stealth Mode"], correctIndex: 2, explanation: "Le Relax Mode est disponible gratuitement pour les abonnés Standard et Pro mais les générations prennent plus de temps, car elles sont moins prioritaires." },
      ],
    },
    {
      number: 6,
      title: "DALL-E 3 et les Générateurs d'Images Alternatifs",
      description: "DALL-E 3, Adobe Firefly, Ideogram, Playground AI — forces et cas d'usage.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Au-delà de Midjourney : les alternatives puissantes" },
        { type: "paragraph", content: "Si Midjourney domine l'esthétique artistique, d'autres outils excellent dans des domaines spécifiques. DALL-E 3 est intégré dans ChatGPT et brille pour les images avec du texte. Adobe Firefly est fait pour les professionnels créatifs avec des droits commerciaux clairs. Ideogram est le meilleur pour la typographie." },
        { type: "subheading", content: "DALL-E 3 — La puissance du texte dans les images" },
        { type: "paragraph", content: "DALL-E 3, accessible directement dans ChatGPT, est imbattable pour générer des images contenant du texte précis et lisible : logos avec texte, affiches, maquettes d'interface, infographies. Il comprend des instructions très détaillées grâce à son intégration avec GPT-5.4." },
        { type: "subheading", content: "Adobe Firefly — La création sans risque légal" },
        { type: "paragraph", content: "Adobe Firefly est entraîné exclusivement sur des images Adobe Stock et des contenus en licence Creative Commons. Ses créations sont safe pour un usage commercial sans risque de poursuites en droits d'auteur. Idéal pour les professionnels du design, les agences et les entreprises." },
        { type: "subheading", content: "Ideogram — La typographie parfaite" },
        { type: "paragraph", content: "Ideogram 3.0 est spécialisé dans la génération d'images avec une typographie irréprochable. Il peut créer des logos, des affiches et des designs graphiques où le texte est parfaitement intégré. Sa précision sur les lettres dépasse tous les autres modèles." },
        { type: "subheading", content: "Playground AI — L'outil polyvalent gratuit" },
        { type: "paragraph", content: "Playground AI offre une interface web intuitive avec accès à plusieurs modèles (SDXL, Playground v3). Il propose un plan gratuit généreux et des fonctionnalités d'édition avancées comme l'inpainting et l'outpainting directement dans le navigateur." },
        { type: "key-point", content: "Règle d'or : Midjourney pour l'esthétique artistique, DALL-E 3 pour les images avec texte, Firefly pour l'usage commercial sécurisé, Ideogram pour la typographie, Stable Diffusion pour le contrôle total." },
        { type: "diagram", label: "Quel Générateur d'Images Choisir ?", flow: "horizontal", nodes: [
          { label: "Midjourney V8", sub: "Esthétique artistique maximale", color: "purple" },
          { label: "DALL-E 3", sub: "Images avec texte précis", color: "blue" },
          { label: "Adobe Firefly", sub: "Usage commercial sécurisé", color: "emerald" },
          { label: "Ideogram 3.0", sub: "Typographie parfaite", color: "amber" },
        ]},
        { type: "summary", items: [
          "DALL-E 3 excelle pour les images contenant du texte précis et lisible",
          "Adobe Firefly est juridiquement sûr pour un usage commercial",
          "Ideogram 3.0 est le meilleur outil pour la typographie dans les images",
          "Playground AI offre un plan gratuit généreux avec plusieurs modèles",
          "Chaque outil a une spécialité : choisissez selon votre besoin précis"
        ]},
      ],
      quiz: [
        { question: "Pour quel cas d'usage DALL-E 3 est-il le meilleur choix ?", options: ["Les portraits artistiques", "Les images contenant du texte précis", "Les paysages photoréalistes", "Les illustrations manga"], correctIndex: 1, explanation: "DALL-E 3 est imbattable pour générer des images contenant du texte lisible et précis : logos, affiches, maquettes d'interface, infographies." },
        { question: "Pourquoi Adobe Firefly est-il particulièrement adapté aux professionnels ?", options: ["Il est plus rapide que les autres", "Il est entraîné sur des contenus commercialement sûrs", "Il génère des images en 4K", "Il est moins cher"], correctIndex: 1, explanation: "Firefly est entraîné exclusivement sur des images Adobe Stock et Creative Commons, ce qui le rend juridiquement sûr pour un usage commercial sans risque de violation des droits d'auteur." },
        { question: "Quel outil est spécialisé dans la génération de typographie parfaite ?", options: ["Midjourney", "DALL-E 3", "Ideogram", "Stable Diffusion"], correctIndex: 2, explanation: "Ideogram 3.0 est spécialisé dans la typographie et la génération d'images avec du texte parfaitement intégré — logos, affiches, designs graphiques." },
        { question: "Quelle plateforme offre un accès gratuit généreux à plusieurs modèles de génération ?", options: ["Adobe Firefly", "Midjourney", "DALL-E 3", "Playground AI"], correctIndex: 3, explanation: "Playground AI propose un plan gratuit généreux avec accès à plusieurs modèles (SDXL, Playground v3) et des fonctionnalités d'édition avancées directement dans le navigateur." },
      ],
    },
    {
      number: 7,
      title: "Stable Diffusion — Le Couteau Suisse Open Source",
      description: "Installation locale, ComfyUI, ControlNet et techniques avancées de Stable Diffusion.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Stable Diffusion : la liberté totale" },
        { type: "paragraph", content: "Stable Diffusion est un modèle open source de génération d'images qui peut être installé localement sur votre ordinateur. Gratuit et sans censure, il offre un contrôle total sur chaque aspect de la génération. En 2026, SDXL et SD3 sont les versions les plus utilisées." },
        { type: "subheading", content: "ComfyUI — L'interface avancée par excellence" },
        { type: "paragraph", content: "ComfyUI est une interface visuelle basée sur des nodes (nœuds) qui permet de construire des workflows de génération complexes. Vous connectez visuellement les différentes étapes : modèle, sampler, VAE, upscaler. C'est l'outil préféré des utilisateurs avancés pour sa flexibilité maximale." },
        { type: "subheading", content: "ControlNet — Contrôler la composition précisément" },
        { type: "paragraph", content: "ControlNet est une extension révolutionnaire qui permet de contrôler précisément la composition d'une image : pose d'un personnage (OpenPose), contours et formes (Canny), profondeur (Depth), lignes architecturales (MLSD). Vous pouvez ainsi générer une image exactement dans la pose que vous souhaitez." },
        { type: "subheading", content: "Les LoRA — Styles personnalisés" },
        { type: "paragraph", content: "Les LoRA (Low-Rank Adaptation) sont de petits modèles complémentaires qui ajoutent un style ou un sujet spécifique. Vous pouvez télécharger des LoRA pour un style artistique particulier, un personnage, ou entraîner votre propre LoRA avec vos photos." },
        { type: "subheading", content: "img2img — Transformer des images existantes" },
        { type: "paragraph", content: "Le mode img2img permet de modifier une image existante en conservant sa composition générale. Utile pour styliser une photo, corriger des détails, ou transformer un croquis en illustration détaillée. Le paramètre 'denoising strength' contrôle l'intensité de la transformation." },
        { type: "tip", content: "Pour commencer avec Stable Diffusion sans installation locale, testez d'abord les versions en ligne comme Leonardo.ai ou NightCafe. Ils utilisent Stable Diffusion avec une interface simplifiée et des serveurs cloud." },
        { type: "diagram", label: "L'Écosystème Stable Diffusion", flow: "vertical", nodes: [
          { label: "Stable Diffusion", sub: "Modèle de base open source", color: "blue" },
          { label: "ComfyUI", sub: "Interface visuelle par nodes (avancé)", color: "purple" },
          { label: "ControlNet", sub: "Contrôle de pose et composition", color: "emerald" },
          { label: "LoRA", sub: "Styles et personnages personnalisés", color: "amber" },
        ]},
        { type: "summary", items: [
          "Stable Diffusion est gratuit, open source et peut s'exécuter localement",
          "ComfyUI offre un workflow visuel par nodes pour les utilisateurs avancés",
          "ControlNet permet de contrôler la pose, les contours et la composition",
          "Les LoRA ajoutent des styles ou des personnages personnalisés",
          "img2img transforme une image existante en conservant sa composition"
        ]},
      ],
      quiz: [
        { question: "Quelle est la principale force de Stable Diffusion par rapport aux autres outils ?", options: ["Il génère des images plus rapidement", "Il est gratuit, open source et peut fonctionner localement", "Ses images sont de meilleure qualité", "Il nécessite moins de VRAM"], correctIndex: 1, explanation: "La principale force de Stable Diffusion est d'être open source, gratuit et installable localement, offrant ainsi un contrôle total et une confidentialité maximale." },
        { question: "À quoi sert ControlNet dans Stable Diffusion ?", options: ["Contrôler la vitesse de génération", "Contrôler précisément la composition et la pose", "Contrôler les droits d'utilisation", "Contrôler la résolution de sortie"], correctIndex: 1, explanation: "ControlNet permet de contrôler précisément la composition d'une image via des guides visuels : pose de personnage (OpenPose), contours (Canny), profondeur (Depth)." },
        { question: "Que sont les LoRA dans Stable Diffusion ?", options: ["Un type de processeur graphique", "Des petits modèles qui ajoutent un style spécifique", "Un format de fichier image", "Une interface utilisateur"], correctIndex: 1, explanation: "Les LoRA sont de petits modèles complémentaires qui s'ajoutent au modèle principal pour reproduire un style artistique, un personnage ou une esthétique particulière." },
        { question: "Dans le mode img2img, que contrôle le paramètre 'denoising strength' ?", options: ["La résolution de l'image", "L'intensité de la transformation de l'image originale", "Le nombre d'étapes de génération", "La saturation des couleurs"], correctIndex: 1, explanation: "Le 'denoising strength' contrôle l'intensité de la transformation : une valeur faible (0.2-0.4) conserve l'image originale, une valeur haute (0.7-1.0) la transforme radicalement." },
      ],
    },
    {
      number: 8,
      title: "Sora 2 — La Génération Vidéo par OpenAI",
      description: "Créer, éditer et composer des vidéos avec Sora 2 — techniques et limites.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Sora 2 : la révolution de la vidéo générée par IA" },
        { type: "paragraph", content: "Sora 2 d'OpenAI, disponible depuis début 2026, génère des vidéos d'une réalisme stupéfiant : physique cohérente, dialogues synchronisés, effets sonores intégrés et continuité narrative. C'est l'outil qui a le plus bouleversé l'industrie créative en 2025-2026." },
        { type: "subheading", content: "Fonctionnalités clés de Sora 2" },
        { type: "paragraph", content: "Génération texte-vers-vidéo : décrivez une scène en texte et obtenez une vidéo jusqu'à 60 secondes. Image-vers-vidéo : animez une image fixe. Vidéo-vers-vidéo : transformez une vidéo existante. Extension de vidéo : prolongez une vidéo existante. Re-cut : éditez des parties spécifiques d'une vidéo générée." },
        { type: "subheading", content: "Rédiger un bon prompt vidéo" },
        { type: "paragraph", content: "Un prompt vidéo efficace décrit : le sujet principal, l'action, le cadrage (plan large, gros plan, plan rapproché), le mouvement de caméra (travelling, panoramique, zoom), l'ambiance lumineuse, et le style visuel. Exemple : 'Close-up shot of a woman walking through a rainy Parisian street at night, slow motion, cinematic lighting, shallow depth of field, moody atmosphere.'" },
        { type: "subheading", content: "Les limites actuelles de Sora 2" },
        { type: "paragraph", content: "Malgré ses avancées, Sora 2 a encore des limitations : mains et doigts parfois incorrects sur des plans très rapprochés, cohérence des personnages limitée sur de longues séquences, prix élevé (inclus dans ChatGPT Pro à 200$/mois), et durée maximale de 60 secondes par clip." },
        { type: "subheading", content: "Storyboard IA — Planifier votre vidéo" },
        { type: "paragraph", content: "Utilisez ChatGPT pour créer d'abord un storyboard détaillé scène par scène, puis générez chaque scène séparément avec Sora 2. Montez ensuite les clips avec un outil standard (CapCut, DaVinci Resolve). C'est le workflow adopté par les créateurs professionnels." },
        { type: "callout", content: "Sora 2 est inclus dans l'abonnement ChatGPT Pro (200$/mois). Pour les créateurs occasionnels, les alternatives comme Runway Gen-3 ou Kling offrent de bons résultats à des prix plus accessibles." },
        { type: "diagram", label: "Workflow Vidéo Professionnel avec Sora 2", flow: "horizontal", nodes: [
          { label: "Storyboard", sub: "Planifier scène par scène avec ChatGPT", color: "blue" },
          { label: "Génération", sub: "Créer chaque scène avec Sora 2", color: "purple" },
          { label: "Montage", sub: "Assembler avec CapCut ou DaVinci", color: "emerald" },
        ]},
        { type: "diagram", label: "Modes de Génération Sora 2", flow: "horizontal", nodes: [
          { label: "Texte → Vidéo", sub: "Description textuelle vers clip vidéo", color: "purple" },
          { label: "Image → Vidéo", sub: "Animer une image fixe", color: "blue" },
          { label: "Extension", sub: "Prolonger une vidéo existante", color: "emerald" },
        ]},
        { type: "summary", items: [
          "Sora 2 génère des vidéos jusqu'à 60 secondes avec physique cohérente",
          "Supporte : texte-vers-vidéo, image-vers-vidéo, extension et édition",
          "Les prompts vidéo efficaces décrivent le sujet, l'action, le cadrage et l'ambiance",
          "Limites : mains parfois incorrectes, cohérence limitée sur longues séquences",
          "Workflow pro : storyboard avec ChatGPT, génération par scène, montage externe"
        ]},
      ],
      quiz: [
        { question: "Quelle est la durée maximale d'un clip généré par Sora 2 ?", options: ["15 secondes", "30 secondes", "60 secondes", "5 minutes"], correctIndex: 2, explanation: "Sora 2 peut générer des vidéos jusqu'à 60 secondes par clip. Pour des vidéos plus longues, il faut générer plusieurs clips et les monter ensemble." },
        { question: "Quel est le workflow recommandé pour créer une vidéo longue avec Sora 2 ?", options: ["Générer tout en une seule fois", "Storyboard avec ChatGPT, générer scène par scène, monter", "Utiliser uniquement le mode image-vers-vidéo", "Importer une vidéo existante"], correctIndex: 1, explanation: "Le workflow pro consiste à créer d'abord un storyboard avec ChatGPT, puis générer chaque scène séparément avec Sora 2, et enfin monter les clips avec un outil externe." },
        { question: "Dans quel abonnement Sora 2 est-il inclus ?", options: ["ChatGPT Free", "ChatGPT Plus (20$/mois)", "ChatGPT Pro (200$/mois)", "ChatGPT Team"], correctIndex: 2, explanation: "Sora 2 est inclus dans l'abonnement ChatGPT Pro à 200$/mois, ce qui le rend accessible principalement aux professionnels et créateurs intensifs." },
        { question: "Quelle limitation Sora 2 a-t-il encore en 2026 ?", options: ["Il ne génère que des vidéos en noir et blanc", "Les mains sont parfois incorrectes sur les gros plans", "Il ne supporte que l'anglais", "Les vidéos durent maximum 10 secondes"], correctIndex: 1, explanation: "Malgré ses avancées, Sora 2 a encore du mal avec les mains et les doigts sur les plans très rapprochés, une limitation commune à la plupart des modèles vidéo IA." },
      ],
    },
    {
      number: 9,
      title: "Runway Gen-3, Pika et Kling — Les Alternatives Vidéo",
      description: "Comparatif des outils vidéo IA : forces, tarifs et cas d'usage de chacun.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "L'écosystème des outils vidéo IA en 2026" },
        { type: "paragraph", content: "Sora 2 n'est pas le seul outil de génération vidéo. Runway, Pika et Kling proposent des alternatives accessibles avec des forces différentes. Le choix dépend de votre budget, du type de contenu et du niveau de qualité requis." },
        { type: "subheading", content: "Runway Gen-3 Alpha — La référence cinématographique" },
        { type: "paragraph", content: "Runway Gen-3 Alpha excelle dans les vidéos de qualité cinématographique avec un contrôle précis du mouvement de caméra (Motion Brush), de la cohérence des personnages et de l'interpolation entre images. Très utilisé dans la publicité et le cinéma. Abonnements à partir de 15$/mois avec 625 crédits." },
        { type: "subheading", content: "Pika 2.0 — La créativité accessible" },
        { type: "paragraph", content: "Pika 2.0 se distingue par ses effets créatifs uniques : transformation de style (Pikaffects), ajout d'effets spéciaux en un clic, et une interface très intuitive. Il est particulièrement populaire pour les créateurs de contenu sur les réseaux sociaux grâce à sa rapidité et ses effets visuels percutants." },
        { type: "subheading", content: "Kling AI — La qualité chinoise surprenante" },
        { type: "paragraph", content: "Kling AI (développé par Kuaishou) a surpris l'industrie en 2025 par la qualité de ses vidéos, notamment dans la gestion du mouvement humain et des expressions faciales. Il propose des vidéos jusqu'à 3 minutes avec cohérence des personnages remarquable. Tarifs compétitifs par rapport aux alternatives américaines." },
        { type: "subheading", content: "Comment choisir ?" },
        { type: "paragraph", content: "Qualité cinématographique et contrôle de caméra : Runway Gen-3. Effets créatifs et réseaux sociaux : Pika 2.0. Mouvement humain réaliste et longues séquences : Kling AI. Budget limité et qualité maximale : Sora 2 (si vous avez ChatGPT Pro)." },
        { type: "tip", content: "Testez tous les plans gratuits avant de vous abonner. Runway offre 125 crédits gratuits, Pika propose des essais gratuits, et Kling AI a un plan gratuit généreux. Comparez les résultats sur votre type de contenu spécifique." },
        { type: "diagram", label: "Comparatif des Outils Vidéo IA", flow: "horizontal", nodes: [
          { label: "Runway Gen-3", sub: "Qualité cinéma, contrôle caméra précis", color: "purple" },
          { label: "Pika 2.0", sub: "Effets créatifs, réseaux sociaux", color: "blue" },
          { label: "Kling AI", sub: "Mouvement humain réaliste, 3 minutes max", color: "emerald" },
        ]},
        { type: "summary", items: [
          "Runway Gen-3 : meilleur pour la qualité cinématographique et le contrôle de caméra",
          "Pika 2.0 : idéal pour les effets créatifs et le contenu réseaux sociaux",
          "Kling AI : excellent pour le mouvement humain réaliste et les longues séquences",
          "Tous proposent des plans gratuits pour tester avant d'acheter",
          "Le choix dépend du type de contenu, du budget et de l'usage prévu"
        ]},
      ],
      quiz: [
        { question: "Quel outil vidéo est particulièrement reconnu pour les effets créatifs (Pikaffects) ?", options: ["Runway Gen-3", "Sora 2", "Pika 2.0", "Kling AI"], correctIndex: 2, explanation: "Pika 2.0 se distingue par ses effets créatifs uniques appelés Pikaffects, qui permettent des transformations visuelles spectaculaires en un clic." },
        { question: "Quelle force distingue Kling AI des autres outils vidéo ?", options: ["La génération de vidéos 8K", "Le mouvement humain réaliste et la cohérence des personnages", "Les effets de texte animé", "La génération musicale synchronisée"], correctIndex: 1, explanation: "Kling AI se distingue par sa gestion exceptionnelle du mouvement humain et des expressions faciales, ainsi que par sa cohérence des personnages sur de longues séquences." },
        { question: "Pour quel type de production Runway Gen-3 est-il principalement utilisé ?", options: ["Les jeux vidéo", "La publicité et le cinéma", "Les stories Instagram", "Les podcasts vidéo"], correctIndex: 1, explanation: "Runway Gen-3 est très utilisé dans la publicité professionnelle et le cinéma grâce à sa qualité cinématographique et son contrôle précis du mouvement de caméra." },
        { question: "Quelle est la durée maximale de vidéo que Kling AI peut générer ?", options: ["30 secondes", "1 minute", "3 minutes", "10 minutes"], correctIndex: 2, explanation: "Kling AI peut générer des vidéos jusqu'à 3 minutes, ce qui le distingue de la plupart des concurrents limités à 60 secondes." },
      ],
    },
    {
      number: 10,
      title: "ElevenLabs — La Voix IA Professionnelle",
      description: "Clonage de voix, génération multilingue, doublage automatique et API ElevenLabs.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "ElevenLabs : la référence mondiale de la voix IA" },
        { type: "paragraph", content: "ElevenLabs s'est imposé comme la référence mondiale pour la synthèse vocale IA avec des voix indiscernables des voix humaines. Fondé en 2022, il propose en 2026 plus de 3 000 voix dans 32 langues, le clonage vocal avec seulement 1 minute d'audio, et un doublage automatique de vidéos." },
        { type: "subheading", content: "La bibliothèque de voix" },
        { type: "paragraph", content: "ElevenLabs propose des voix professionnelles classées par usage : narration, podcast, publicité, e-learning, médias sociaux. Chaque voix a des paramètres réglables : stabilité (cohérence), clarté (articulation) et style (expressivité). La bibliothèque Voice Lab permet de personnaliser n'importe quelle voix." },
        { type: "subheading", content: "Instant Voice Cloning — Clonez une voix en 1 minute" },
        { type: "paragraph", content: "Avec seulement 1 minute d'enregistrement audio propre, ElevenLabs clone une voix avec une précision remarquable. Professional Voice Cloning (avec 30 minutes d'audio) offre une qualité quasi parfaite. Idéal pour les créateurs de podcasts, les narrateurs et les entreprises qui veulent une voix de marque cohérente." },
        { type: "subheading", content: "Dubbing — Doublage automatique de vidéos" },
        { type: "paragraph", content: "La fonctionnalité Dubbing traduit et double automatiquement une vidéo dans une autre langue tout en conservant la voix originale du locuteur. Une vidéo en français peut être doublée en anglais, espagnol, allemand ou japonais en quelques minutes, avec lip sync approximatif." },
        { type: "subheading", content: "L'API ElevenLabs — Intégrer la voix dans vos applications" },
        { type: "paragraph", content: "L'API ElevenLabs permet d'intégrer la synthèse vocale dans n'importe quelle application : agents IA avec voix, assistants téléphoniques, applications e-learning, audiobooks automatiques. La latence est inférieure à 500ms pour les applications en temps réel." },
        { type: "key-point", content: "ElevenLabs est disponible avec un plan gratuit (10 000 caractères/mois) et des plans payants à partir de 5$/mois pour 30 000 caractères. Les créateurs professionnels optent généralement pour le plan Creator à 22$/mois." },
        { type: "diagram", label: "Fonctionnalités ElevenLabs", flow: "horizontal", nodes: [
          { label: "3 000+ Voix", sub: "32 langues, qualité humaine", color: "blue" },
          { label: "Voice Cloning", sub: "Clone vocal en 1 min d'audio", color: "purple" },
          { label: "Dubbing", sub: "Doublage vidéo multilingue auto", color: "emerald" },
          { label: "API", sub: "Latence <500ms pour apps temps réel", color: "amber" },
        ]},
        { type: "summary", items: [
          "Plus de 3 000 voix dans 32 langues avec qualité indiscernable des voix humaines",
          "Clonage vocal avec seulement 1 minute d'enregistrement audio",
          "Dubbing automatique de vidéos avec conservation de la voix originale",
          "API avec latence inférieure à 500ms pour les applications temps réel",
          "Plan gratuit disponible — 10 000 caractères/mois"
        ]},
      ],
      quiz: [
        { question: "Combien de temps d'enregistrement faut-il pour le clonage vocal Instant de ElevenLabs ?", options: ["10 secondes", "1 minute", "10 minutes", "1 heure"], correctIndex: 1, explanation: "L'Instant Voice Cloning d'ElevenLabs nécessite seulement 1 minute d'enregistrement audio propre pour créer un clone vocal de bonne qualité." },
        { question: "Combien de langues supporte ElevenLabs en 2026 ?", options: ["8 langues", "15 langues", "32 langues", "100 langues"], correctIndex: 2, explanation: "ElevenLabs supporte plus de 32 langues en 2026, avec des voix localisées qui correspondent aux accents et intonations de chaque langue." },
        { question: "Que fait la fonctionnalité Dubbing d'ElevenLabs ?", options: ["Elle crée une version audio d'un texte", "Elle traduit et double une vidéo dans une autre langue", "Elle supprime les bruits de fond", "Elle améliore la qualité audio d'un enregistrement"], correctIndex: 1, explanation: "Dubbing traduit et double automatiquement une vidéo dans une autre langue en conservant la voix originale du locuteur et en ajoutant un lip sync approximatif." },
        { question: "Quelle est la latence de l'API ElevenLabs pour les applications temps réel ?", options: ["Moins de 50ms", "Moins de 500ms", "Environ 2 secondes", "Plus de 5 secondes"], correctIndex: 1, explanation: "L'API ElevenLabs offre une latence inférieure à 500ms, ce qui la rend utilisable pour des applications en temps réel comme les agents IA vocaux ou les assistants téléphoniques." },
      ],
    },
    {
      number: 11,
      title: "Suno et Udio — Créer de la Musique avec l'IA",
      description: "Techniques de prompt musical, styles, personnalisation et limites des outils musicaux.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "La révolution musicale IA : Suno et Udio" },
        { type: "paragraph", content: "En 2025-2026, Suno et Udio ont rendu la création musicale accessible à tous. Ces outils génèrent des chansons complètes — mélodie, arrangements, voix, paroles — en quelques secondes à partir d'une simple description textuelle. Le résultat est souvent de qualité professionnelle surprenante." },
        { type: "subheading", content: "Suno — La simplicité au service de la créativité" },
        { type: "paragraph", content: "Suno V4 est la version actuelle, avec une qualité audio remarquable et une grande diversité de styles. Son interface est très simple : décrivez votre chanson en quelques mots ou choisissez parmi des styles prédéfinis. Options avancées : mode Custom pour écrire vos propres paroles, mode Instrumental pour une musique sans voix." },
        { type: "subheading", content: "Écrire un bon prompt musical pour Suno" },
        { type: "paragraph", content: "Structure d'un prompt efficace : style musical + ambiance + instruments + tempo + éventuellement thème des paroles. Exemple : 'upbeat french pop song, acoustic guitar and piano, 120 BPM, about falling in love in Paris, female vocals, sunny afternoon feel'. Plus votre description est précise, plus le résultat correspond à vos attentes." },
        { type: "subheading", content: "Udio — La qualité audiophile" },
        { type: "paragraph", content: "Udio se distingue par une qualité audio supérieure à Suno dans certains genres, notamment le jazz, la musique classique et le rock alternatif. Son interface permet de contrôler plus finement la structure de la chanson (intro, couplet, refrain, pont, outro) et d'éditer les paroles générées." },
        { type: "subheading", content: "Limitations et droits" },
        { type: "paragraph", content: "La question des droits est en pleine évolution. Suno et Udio revendiquent les droits sur les créations générées sur leur plateforme. Pour un usage commercial, vérifiez les conditions de chaque outil et préférez les plans payants qui incluent généralement des droits commerciaux." },
        { type: "tip", content: "Utilisez Suno pour la vitesse et la diversité de styles. Utilisez Udio pour les genres qui nécessitent plus de sophistication musicale (jazz, classique). Combinez les deux : générez une base avec Suno et affinez avec Udio." },
        { type: "diagram", label: "Structure d'un Bon Prompt Musical", flow: "horizontal", nodes: [
          { label: "Genre + Sous-genre", sub: "Ex : upbeat french pop", color: "purple" },
          { label: "Instruments + Tempo", sub: "Ex : piano, 120 BPM", color: "blue" },
          { label: "Voix + Ambiance", sub: "Ex : female vocals, sunny", color: "emerald" },
          { label: "Thème paroles", sub: "Ex : falling in love in Paris", color: "amber" },
        ]},
        { type: "summary", items: [
          "Suno et Udio génèrent des chansons complètes en secondes à partir d'un texte",
          "Un bon prompt musical précise : style, ambiance, instruments, tempo",
          "Suno excelle par sa simplicité et sa diversité de styles",
          "Udio offre une qualité audiophile pour le jazz, classique et rock alternatif",
          "Vérifiez les droits commerciaux selon le plan choisi"
        ]},
      ],
      quiz: [
        { question: "Quelle est la structure d'un bon prompt musical pour Suno ?", options: ["Juste le titre de la chanson", "Style + ambiance + instruments + tempo + thème", "Un poème complet", "La partition musicale"], correctIndex: 1, explanation: "Un prompt musical efficace combine : le style musical, l'ambiance, les instruments, le tempo et éventuellement le thème des paroles pour guider précisément la génération." },
        { question: "Pour quel genre musical Udio est-il particulièrement reconnu ?", options: ["La pop et l'électro", "Le jazz, la musique classique et le rock alternatif", "La musique de jeux vidéo", "Le hip-hop et le rap"], correctIndex: 1, explanation: "Udio se distingue par une qualité supérieure dans les genres musicaux complexes comme le jazz, la musique classique et le rock alternatif." },
        { question: "Que signifie le mode 'Custom' dans Suno ?", options: ["Générer de la musique personnalisée automatiquement", "Écrire et utiliser ses propres paroles", "Choisir le musicien qui joue les instruments", "Exporter en format personnalisé"], correctIndex: 1, explanation: "Le mode Custom de Suno permet d'écrire et d'utiliser ses propres paroles plutôt que de laisser l'IA les générer automatiquement." },
        { question: "Quelle précaution faut-il prendre pour l'usage commercial des créations musicales IA ?", options: ["Aucune précaution n'est nécessaire", "Vérifier les conditions de chaque outil et utiliser un plan payant", "Mentionner que c'est de l'IA dans la description", "Enregistrer la chanson à la SACEM"], correctIndex: 1, explanation: "Pour un usage commercial, il faut vérifier les conditions de licence de chaque outil. Les plans payants incluent généralement des droits commerciaux, contrairement aux plans gratuits." },
      ],
    },
    {
      number: 12,
      title: "GitHub Copilot et Cursor — Coder avec l'IA",
      description: "Autocomplete, Agent Mode, comparatif et meilleures pratiques pour coder avec l'IA.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "L'IA a transformé la programmation" },
        { type: "paragraph", content: "En 2026, les développeurs qui n'utilisent pas d'IA pour coder sont devenus une minorité. Les études montrent que les assistants IA augmentent la productivité des développeurs de 30 à 55% selon les tâches. GitHub Copilot et Cursor sont les deux outils dominants." },
        { type: "subheading", content: "GitHub Copilot — L'assistant de Microsoft/OpenAI" },
        { type: "paragraph", content: "GitHub Copilot s'intègre dans VS Code, JetBrains, Neovim et d'autres éditeurs. Il propose une complétion de code en temps réel, un chat contextuel (Copilot Chat), et depuis 2025, un Agent Mode qui peut implémenter des fonctionnalités complètes à partir d'une description. Tarif : 10$/mois ou 19$/mois pour les fonctionnalités avancées." },
        { type: "subheading", content: "Cursor — L'éditeur de code construit pour l'IA" },
        { type: "paragraph", content: "Cursor est un fork de VS Code entièrement repensé pour l'IA. Il intègre Claude 4.6, GPT-5.4 et ses propres modèles. Ses fonctionnalités uniques : Composer (modifier plusieurs fichiers simultanément), Tab (autocomplétion prédictive multilignes), et Agent (exécuter des tâches complexes autonome). C'est l'outil préféré des développeurs avancés." },
        { type: "subheading", content: "Cursor Agent — La programmation autonome" },
        { type: "paragraph", content: "Le Cursor Agent peut : lire et écrire des fichiers, exécuter des commandes terminal, déboguer des erreurs automatiquement, installer des dépendances, et refactoriser de grands codebases. Décrivez une fonctionnalité en langage naturel et l'Agent s'occupe de tout, même sur plusieurs fichiers." },
        { type: "subheading", content: "Meilleures pratiques" },
        { type: "paragraph", content: "Pour maximiser la qualité du code généré : donnez un contexte clair (décrivez l'architecture existante), soyez précis dans vos demandes, vérifiez toujours le code généré avant de le commiter, et utilisez les règles de projet (.cursorrules) pour imposer votre style de code." },
        { type: "key-point", content: "Règle d'or : l'IA génère le code, vous comprenez et validez. Ne committez jamais du code que vous ne comprenez pas. L'IA fait des erreurs subtiles — restez le pilote, l'IA est votre copilote." },
        { type: "diagram", label: "GitHub Copilot vs Cursor", flow: "horizontal", nodes: [
          { label: "GitHub Copilot", sub: "Extension dans VS Code, JetBrains — 10$/mois", color: "blue" },
          { label: "Cursor", sub: "Éditeur repensé pour l'IA (fork VS Code)", color: "purple" },
        ]},
        { type: "video", videoId: "kCc8FmEb1nY",
      videoDurationMinutes: 116, label: "Construire un GPT from scratch — Karpathy" },
        { type: "summary", items: [
          "L'IA augmente la productivité des développeurs de 30 à 55%",
          "GitHub Copilot : intégration dans les éditeurs existants, 10$/mois",
          "Cursor : éditeur repensé pour l'IA avec Agent autonome multiflchiers",
          "Cursor Agent peut lire, écrire, déboguer et refactoriser de façon autonome",
          "Toujours valider le code généré — l'IA fait des erreurs subtiles"
        ]},
      ],
      quiz: [
        { question: "De combien l'IA augmente-t-elle la productivité des développeurs ?", options: ["5 à 10%", "15 à 20%", "30 à 55%", "80 à 100%"], correctIndex: 2, explanation: "Les études montrent que les assistants IA augmentent la productivité des développeurs de 30 à 55% selon les tâches, avec des gains plus importants sur les tâches répétitives." },
        { question: "Quelle est la principale différence entre GitHub Copilot et Cursor ?", options: ["Cursor est gratuit, Copilot est payant", "Cursor est un éditeur repensé pour l'IA, Copilot est une extension", "Copilot gère plus de langages", "Cursor nécessite plus de RAM"], correctIndex: 1, explanation: "Cursor est un éditeur de code entièrement repensé autour de l'IA (fork de VS Code), tandis que GitHub Copilot est une extension qui s'intègre dans des éditeurs existants." },
        { question: "Que peut faire le Cursor Agent de façon autonome ?", options: ["Uniquement compléter des lignes de code", "Lire, écrire, déboguer et refactoriser sur plusieurs fichiers", "Générer des images pour le README", "Déployer automatiquement en production"], correctIndex: 1, explanation: "Le Cursor Agent peut gérer des tâches complexes de façon autonome : lire et écrire des fichiers, exécuter des commandes terminal, déboguer et refactoriser sur plusieurs fichiers simultanément." },
        { question: "Quelle est la règle d'or lors de l'utilisation d'IA pour coder ?", options: ["Faire confiance à 100% au code généré", "Ne jamais modifier le code généré", "Toujours valider le code généré que vous comprenez", "Utiliser uniquement pour les petits projets"], correctIndex: 2, explanation: "La règle d'or est de toujours valider le code généré et de ne commiter que du code que vous comprenez. L'IA fait des erreurs subtiles — vous restez le pilote responsable." },
      ],
    },
    {
      number: 13,
      title: "Perplexity AI — La Recherche Réinventée",
      description: "Perplexity vs Google, Spaces, API, Deep Research et cas d'usage avancés.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Perplexity : quand la recherche rencontre l'IA" },
        { type: "paragraph", content: "Perplexity AI combine la recherche web en temps réel avec la puissance des LLM pour fournir des réponses sourcées, précises et actualisées. Contrairement à ChatGPT qui peut halluciner sur des faits récents, Perplexity cite toujours ses sources et accède au web en direct." },
        { type: "subheading", content: "Perplexity vs Google — Quand utiliser quoi ?" },
        { type: "paragraph", content: "Utilisez Google pour : trouver un site web spécifique, acheter un produit, navigation locale, chercher des images. Utilisez Perplexity pour : comprendre un sujet complexe, obtenir un résumé avec sources, comparer des options, recherche académique rapide, ou tout ce qui nécessite une synthèse plutôt que des liens." },
        { type: "subheading", content: "Les Spaces — Votre base de connaissances IA" },
        { type: "paragraph", content: "Les Spaces permettent de créer des espaces de recherche thématiques avec des sources prédéfinies. Exemple : un Space 'Veille Concurrentielle' avec les sites de vos concurrents, ou un Space 'Actualité Tech' avec TechCrunch, The Verge et Wired. Perplexity recherchera en priorité dans ces sources." },
        { type: "subheading", content: "Deep Research — L'analyse approfondie automatique" },
        { type: "paragraph", content: "Deep Research est la fonctionnalité premium qui génère des rapports de recherche approfondis en 5 à 10 minutes. Perplexity effectue des dizaines de recherches, synthétise les résultats, identifie les consensus et les divergences, et produit un rapport structuré avec toutes les sources. Comparable à 2-3 heures de recherche manuelle." },
        { type: "subheading", content: "L'API Perplexity — Recherche web dans vos applications" },
        { type: "paragraph", content: "L'API Perplexity permet d'ajouter la recherche web en temps réel à n'importe quelle application. Particulièrement utile pour les agents IA qui ont besoin d'informations actualisées, les chatbots de support client, et les outils de veille automatisée." },
        { type: "tip", content: "Utilisez Perplexity Pro (20$/mois) pour accéder aux modèles les plus puissants (Claude 4.6, GPT-5.4) et à la fonctionnalité Deep Research. Le plan gratuit est déjà très puissant pour une utilisation régulière." },
        { type: "diagram", label: "Perplexity vs Google : Quand Utiliser Quoi ?", flow: "horizontal", nodes: [
          { label: "Google", sub: "Trouver un site, acheter, navigation locale", color: "blue" },
          { label: "Perplexity", sub: "Comprendre, synthétiser, recherche approfondie", color: "purple" },
        ]},
        { type: "summary", items: [
          "Perplexity combine recherche web en temps réel et synthèse IA avec sources",
          "Idéal pour comprendre un sujet complexe et obtenir un résumé sourcé",
          "Les Spaces créent des bases de connaissances thématiques avec sources prédéfinies",
          "Deep Research génère des rapports approfondis en 5-10 minutes",
          "L'API permet d'intégrer la recherche web dans vos propres applications"
        ]},
      ],
      quiz: [
        { question: "Quelle est la principale différence entre Perplexity et ChatGPT ?", options: ["Perplexity est gratuit, ChatGPT est payant", "Perplexity cite toujours ses sources et accède au web en temps réel", "Perplexity génère des images, ChatGPT non", "ChatGPT est plus rapide que Perplexity"], correctIndex: 1, explanation: "La principale différence est que Perplexity accède au web en temps réel et cite toujours ses sources, évitant ainsi les hallucinations sur des informations récentes." },
        { question: "Pour quelle tâche Perplexity est-il préférable à Google ?", options: ["Trouver un site web spécifique", "Acheter un produit en ligne", "Comprendre un sujet complexe avec un résumé sourcé", "Rechercher des images"], correctIndex: 2, explanation: "Perplexity est préférable à Google pour comprendre un sujet complexe, car il produit une synthèse structurée avec sources plutôt qu'une liste de liens à parcourir." },
        { question: "Combien de temps prend la fonctionnalité Deep Research ?", options: ["30 secondes", "5 à 10 minutes", "1 heure", "24 heures"], correctIndex: 1, explanation: "Deep Research prend 5 à 10 minutes pour générer un rapport de recherche approfondi, équivalent à 2-3 heures de recherche manuelle." },
        { question: "À quoi servent les Spaces dans Perplexity ?", options: ["Stocker des fichiers dans le cloud", "Créer des espaces de recherche thématiques avec sources prédéfinies", "Organiser les conversations par date", "Partager des recherches avec une équipe"], correctIndex: 1, explanation: "Les Spaces permettent de créer des espaces de recherche thématiques où Perplexity cherchera en priorité dans les sources que vous avez prédéfinies." },
      ],
    },
    {
      number: 14,
      title: "NotebookLM — Analyser vos Documents avec l'IA",
      description: "Import PDF, génération automatique de podcasts, questions/réponses et organisation.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "NotebookLM : votre assistant de recherche personnel" },
        { type: "paragraph", content: "NotebookLM de Google est un outil unique qui transforme vos documents en une base de connaissances interactive. Contrairement aux autres LLM, il répond uniquement en se basant sur vos documents, éliminant les hallucinations. Il peut analyser jusqu'à 50 sources simultanément." },
        { type: "subheading", content: "Importer vos sources" },
        { type: "paragraph", content: "NotebookLM accepte : PDF, Google Docs, Google Slides, sites web (URL), fichiers texte, et même des vidéos YouTube. Vous pouvez combiner différents types de sources dans un même notebook. Limite actuelle : 500 000 mots par source et 50 sources par notebook." },
        { type: "subheading", content: "Audio Overview — Le podcast automatique" },
        { type: "paragraph", content: "La fonctionnalité la plus spectaculaire : Audio Overview génère automatiquement un podcast de 10-20 minutes sur le contenu de vos documents. Deux voix naturelles (homme et femme) discutent des points clés de façon conversationnelle. Parfait pour assimiler du contenu long en commute ou en faisant de l'exercice." },
        { type: "subheading", content: "Questions et réponses contextuelles" },
        { type: "paragraph", content: "Posez n'importe quelle question sur vos documents et NotebookLM répond avec des citations précises. Il identifie exactement dans quel document et à quelle page se trouve l'information. Idéal pour : analyser des rapports d'entreprise, réviser pour des examens, rechercher des informations juridiques, ou synthétiser des études scientifiques." },
        { type: "subheading", content: "Les Guides d'étude automatiques" },
        { type: "paragraph", content: "NotebookLM génère automatiquement des résumés, des plans, des glossaires, des questions d'examen et des fiches de révision à partir de vos documents. En un clic, transformez un cours de 200 pages en une fiche de 2 pages ou en 20 questions de quiz." },
        { type: "callout", content: "NotebookLM est totalement gratuit dans sa version actuelle. C'est l'outil le plus sous-estimé de 2026 — absolument essentiel pour les étudiants, les chercheurs, les juristes et tous ceux qui travaillent avec de nombreux documents." },
        { type: "diagram", label: "NotebookLM : Du Document à la Connaissance", flow: "vertical", nodes: [
          { label: "Importer vos sources", sub: "PDF, Docs, URLs, YouTube (50 sources max)", color: "blue" },
          { label: "Questions contextuelles", sub: "Réponses avec citations précises", color: "purple" },
          { label: "Audio Overview", sub: "Podcast automatique de 10-20 minutes", color: "emerald" },
          { label: "Guides d'étude", sub: "Résumés, fiches, quiz automatiques", color: "amber" },
        ]},
        { type: "summary", items: [
          "Analyse jusqu'à 50 sources simultanément sans hallucinations",
          "Accepte PDF, Docs, Slides, URLs, texte et vidéos YouTube",
          "Audio Overview génère un podcast de 10-20 minutes sur vos documents",
          "Les réponses incluent des citations précises avec numéro de page",
          "Génère résumés, fiches, glossaires et questions de quiz automatiquement"
        ]},
      ],
      quiz: [
        { question: "Quelle est la grande différence de NotebookLM par rapport aux autres LLM ?", options: ["Il est plus rapide", "Il répond uniquement en se basant sur vos documents", "Il génère des images", "Il parle plus de langues"], correctIndex: 1, explanation: "NotebookLM répond exclusivement en se basant sur les documents que vous avez importés, éliminant ainsi les hallucinations et garantissant des réponses tracées à vos sources." },
        { question: "Combien de sources peut analyser simultanément NotebookLM ?", options: ["5 sources", "20 sources", "50 sources", "200 sources"], correctIndex: 2, explanation: "NotebookLM peut analyser jusqu'à 50 sources simultanément dans un même notebook, couvrant PDF, Docs, Slides, URLs et vidéos YouTube." },
        { question: "Que génère la fonctionnalité Audio Overview ?", options: ["Une liste de mots-clés", "Un résumé en bullet points", "Un podcast de 10-20 minutes sur le contenu", "Une présentation PowerPoint"], correctIndex: 2, explanation: "Audio Overview génère automatiquement un podcast de 10 à 20 minutes avec deux voix naturelles qui discutent des points clés de vos documents de façon conversationnelle." },
        { question: "Quel est le coût de NotebookLM ?", options: ["19$/mois", "9,99$/mois", "Freemium (version payante avancée)", "Totalement gratuit"], correctIndex: 3, explanation: "NotebookLM est totalement gratuit dans sa version actuelle, ce qui en fait l'outil IA le plus accessible et le plus sous-estimé pour l'analyse de documents." },
      ],
    },
    {
      number: 15,
      title: "Make et Zapier — Automatiser sans Coder",
      description: "Créer des workflows d'automatisation IA avec Make et Zapier, exemples concrets.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "L'automatisation no-code : connecter vos outils IA" },
        { type: "paragraph", content: "Make (anciennement Integromat) et Zapier sont les plateformes d'automatisation no-code les plus populaires. Elles permettent de connecter des centaines d'applications entre elles et d'y intégrer des outils IA. En 2026, ils sont devenus le ciment de l'IA dans les workflows professionnels." },
        { type: "subheading", content: "Make — La puissance visuelle" },
        { type: "paragraph", content: "Make propose une interface visuelle sous forme de scénarios avec des modules connectés. Il est plus puissant et flexible que Zapier pour les workflows complexes avec des conditions multiples, des boucles et des transformations de données. Idéal pour les automatisations avancées. Plan gratuit : 1 000 opérations/mois." },
        { type: "subheading", content: "Zapier — La simplicité avant tout" },
        { type: "paragraph", content: "Zapier est plus simple à prendre en main, avec une interface linéaire Trigger > Action. Il supporte plus de 6 000 applications. Son AI by Zapier permet de créer des workflows en langage naturel. Idéal pour les débutants et les automatisations simples. Plan gratuit : 100 tâches/mois." },
        { type: "subheading", content: "Exemples d'automatisations IA populaires" },
        { type: "paragraph", content: "1. Email entrant → ChatGPT résume et classe → Notion. 2. Nouveau lead CRM → Claude rédige un email personnalisé → envoi automatique. 3. Post publié → GPT traduit → publication automatique dans 3 langues. 4. Facture reçue → extraction des données → Google Sheets. 5. Mention sur les réseaux sociaux → analyse du sentiment → alerte Slack." },
        { type: "subheading", content: "Intégrer les API IA dans Make/Zapier" },
        { type: "paragraph", content: "Both Make et Zapier proposent des modules natifs pour OpenAI (GPT-5.4), Anthropic (Claude), Google AI (Gemini), ElevenLabs et Midjourney. Vous pouvez appeler ces API directement dans vos workflows sans connaissances en programmation." },
        { type: "tip", content: "Commencez par automatiser une seule tâche répétitive que vous effectuez quotidiennement. Même une automatisation simple qui fait gagner 15 minutes par jour représente plus de 90 heures par an." },
        { type: "diagram", label: "Exemple d'Automatisation IA avec Make/Zapier", flow: "horizontal", nodes: [
          { label: "Déclencheur", sub: "Email reçu, nouveau lead CRM…", color: "blue" },
          { label: "Traitement IA", sub: "GPT-5.4 ou Claude analyse et rédige", color: "purple" },
          { label: "Action", sub: "Notion, Slack, email automatique…", color: "emerald" },
        ]},
        { type: "summary", items: [
          "Make et Zapier connectent des centaines d'applications sans code",
          "Make : plus puissant pour les workflows complexes avec conditions et boucles",
          "Zapier : plus simple, idéal pour les débutants et les automatisations linéaires",
          "Les deux intègrent nativement GPT-5.4, Claude, Gemini et ElevenLabs",
          "15 minutes automatisées par jour = 90+ heures économisées par an"
        ]},
      ],
      quiz: [
        { question: "Quelle est la principale différence entre Make et Zapier ?", options: ["Make est gratuit, Zapier est payant", "Make est plus puissant pour les workflows complexes, Zapier est plus simple", "Zapier supporte l'IA, Make non", "Ils sont identiques"], correctIndex: 1, explanation: "Make est plus puissant et flexible pour les workflows complexes avec conditions et boucles, tandis que Zapier est plus simple à prendre en main pour les automatisations linéaires." },
        { question: "Combien d'opérations le plan gratuit de Make offre-t-il par mois ?", options: ["100 opérations", "500 opérations", "1 000 opérations", "5 000 opérations"], correctIndex: 2, explanation: "Le plan gratuit de Make offre 1 000 opérations par mois, ce qui est suffisant pour commencer à automatiser vos premiers workflows." },
        { question: "Quel exemple d'automatisation combine email et IA ?", options: ["Convertir un PDF en Word", "Email entrant → ChatGPT résume → Notion", "Envoyer des emails à tous les contacts", "Bloquer les spams automatiquement"], correctIndex: 1, explanation: "Un exemple courant : un email entrant déclenche une analyse par ChatGPT (résumé et classification), puis le résultat est automatiquement enregistré dans Notion." },
        { question: "Combien de temps par an représente 15 minutes automatisées par jour ?", options: ["30 heures", "60 heures", "90 heures", "180 heures"], correctIndex: 2, explanation: "15 minutes par jour x 365 jours = 5 475 minutes, soit plus de 90 heures par an. Même une petite automatisation quotidienne a un impact annuel significatif." },
      ],
    },
    {
      number: 16,
      title: "Les API IA — Accéder à la Puissance Brute",
      description: "OpenAI, Anthropic, Google : authentification, tarifs et premiers exemples d'appels.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Pourquoi utiliser les API IA directement ?" },
        { type: "paragraph", content: "Les interfaces web comme ChatGPT et Claude.ai sont pratiques, mais les API offrent une flexibilité totale : intégration dans vos propres applications, automatisation à grande échelle, contrôle précis des paramètres, et coûts souvent inférieurs pour les usages intensifs." },
        { type: "subheading", content: "L'API OpenAI — GPT-5.4 et DALL-E" },
        { type: "paragraph", content: "L'API OpenAI donne accès à GPT-5.4, DALL-E 3, Whisper (transcription), et TTS (text-to-speech). La clé API se génère sur platform.openai.com. Tarification à l'usage : GPT-5.4 coûte environ 15$ pour 1 million de tokens d'entrée et 75$ pour 1 million de tokens de sortie." },
        { type: "subheading", content: "L'API Anthropic — Claude 4.6" },
        { type: "paragraph", content: "L'API Anthropic donne accès à Claude Opus 4.6, Sonnet 4.6 et Haiku 4.5. Elle est reconnue pour sa stabilité et sa précision. Claude Opus 4.6 coûte 15$ pour 1M tokens d'entrée et 75$ pour 1M tokens de sortie. Claude Haiku 4.5 est beaucoup moins cher pour les usages à grande échelle." },
        { type: "subheading", content: "L'API Google AI — Gemini 3.1" },
        { type: "paragraph", content: "L'API Google AI (via Google AI Studio ou Vertex AI) donne accès à Gemini 3.1. Elle offre un plan gratuit généreux (1 500 requêtes/jour pour Gemini 1.5 Flash) et des tarifs compétitifs. Particulièrement intéressante pour les applications multimodales et les usages à grande échelle." },
        { type: "subheading", content: "Structure d'un appel API basique" },
        { type: "paragraph", content: "Un appel API IA contient toujours : la clé d'authentification (Bearer token), le modèle choisi, le ou les messages (système + utilisateur), et des paramètres optionnels (température, max_tokens). La réponse est en JSON. Des SDK existent pour Python, JavaScript, et la plupart des langages." },
        { type: "key-point", content: "Sécurité absolue : ne mettez JAMAIS votre clé API dans du code public (GitHub, etc.). Utilisez des variables d'environnement (.env) et ajoutez .env à votre .gitignore. Une clé exposée peut générer des coûts énormes." },
        { type: "diagram", label: "Structure d'un Appel API IA", flow: "horizontal", nodes: [
          { label: "Authentification", sub: "Bearer token (clé API secrète)", color: "pink" },
          { label: "Modèle + Messages", sub: "Système + utilisateur + paramètres", color: "blue" },
          { label: "Réponse JSON", sub: "Texte généré + métadonnées", color: "emerald" },
        ]},
        { type: "summary", items: [
          "Les API offrent plus de flexibilité et de contrôle que les interfaces web",
          "OpenAI API : GPT-5.4, DALL-E 3, Whisper, TTS — facturation à l'usage",
          "Anthropic API : Claude Opus/Sonnet/Haiku — stable et précis",
          "Google AI API : Gemini 3.1 avec plan gratuit généreux (1500 req/jour)",
          "Sécurité : toujours utiliser des variables d'environnement pour les clés API"
        ]},
      ],
      quiz: [
        { question: "Quel est l'avantage principal d'utiliser une API IA plutôt qu'une interface web ?", options: ["C'est plus rapide à utiliser", "Flexibilité totale et intégration dans ses propres applications", "Les modèles sont de meilleure qualité", "C'est toujours gratuit"], correctIndex: 1, explanation: "Les API offrent une flexibilité totale : intégration dans vos propres applications, automatisation à grande échelle, contrôle précis des paramètres et coûts adaptés à l'usage." },
        { question: "Comment sécuriser sa clé API dans un projet de code ?", options: ["L'écrire directement dans le code", "La partager dans les commentaires du code", "Utiliser des variables d'environnement (.env)", "L'envoyer par email"], correctIndex: 2, explanation: "Les clés API doivent être stockées dans des variables d'environnement (.env) jamais commitées sur Git. Une clé exposée publiquement peut générer des coûts énormes." },
        { question: "Quel plan gratuit l'API Google AI offre-t-elle ?", options: ["Aucun plan gratuit", "50 requêtes/jour", "1 500 requêtes/jour pour Gemini Flash", "10 requêtes/heure"], correctIndex: 2, explanation: "L'API Google AI propose un plan gratuit généreux avec jusqu'à 1 500 requêtes par jour pour les modèles Gemini Flash, idéal pour tester et développer." },
        { question: "Quels éléments contient toujours un appel API IA ?", options: ["Uniquement le texte du message", "Clé d'authentification, modèle, messages et paramètres optionnels", "L'adresse IP de l'utilisateur", "Le navigateur utilisé"], correctIndex: 1, explanation: "Un appel API IA contient toujours : la clé d'authentification, le modèle choisi, les messages (système et utilisateur), et des paramètres optionnels comme la température." },
      ],
    },
    {
      number: 17,
      title: "Construire Votre Workflow IA Personnel",
      description: "Audit de productivité, choix de votre stack IA et mise en place étape par étape.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Votre stack IA personnel : la clé de la productivité" },
        { type: "paragraph", content: "Un workflow IA personnel efficace n'est pas fait d'une dizaine d'outils utilisés à moitié, mais de 3 à 5 outils maîtrisés en profondeur et bien intégrés entre eux. L'objectif est d'économiser 2 à 3 heures par jour sur les tâches répétitives pour se concentrer sur la valeur ajoutée." },
        { type: "subheading", content: "Étape 1 : Audit de votre temps actuel" },
        { type: "paragraph", content: "Pendant 3 jours, notez toutes les tâches que vous effectuez et leur durée. Identifiez les tâches répétitives, celles qui demandent peu de créativité mais beaucoup de temps, et celles qui pourraient être déléguées à une IA. En général, 40 à 60% des tâches intellectuelles peuvent être accélérées significativement par l'IA." },
        { type: "subheading", content: "Étape 2 : Choisir votre LLM principal" },
        { type: "paragraph", content: "Si vous travaillez principalement sur du texte (rédaction, analyse, emails) : Claude 4.6. Si vous avez besoin de recherche web en temps réel : Perplexity. Si vous êtes dans l'écosystème Google : Gemini. Si vous faites du code : Cursor avec Claude. Si vous avez besoin d'un outil polyvalent accessible : ChatGPT." },
        { type: "subheading", content: "Étape 3 : Identifier vos outils spécialisés" },
        { type: "paragraph", content: "Selon votre métier : créatif (Midjourney, ElevenLabs, Suno), développeur (Cursor, GitHub Copilot, Claude Code), marketeur (ChatGPT, Canva AI, Perplexity), entrepreneur (ChatGPT, Make/Zapier, NotebookLM), chercheur (NotebookLM, Perplexity Deep Research, Claude)." },
        { type: "subheading", content: "Étape 4 : Créer vos prompts templates" },
        { type: "paragraph", content: "Pour chaque tâche récurrente, créez un prompt template réutilisable. Stockez-les dans Notion, Obsidian ou un simple fichier texte. Exemple : un template pour rédiger des emails clients, un pour analyser des documents, un pour générer des idées de contenu. Ces templates s'améliorent avec le temps." },
        { type: "tip", content: "Commencez par automatiser 3 tâches seulement pendant les 2 premières semaines. Maîtriser 3 outils à fond vaut mieux que de survoler 15 outils. La profondeur avant la largeur." },
        { type: "diagram", label: "Construire Votre Stack IA Personnel", flow: "vertical", nodes: [
          { label: "Audit (3 jours)", sub: "Identifier les tâches chronophages", color: "blue" },
          { label: "LLM Principal", sub: "Claude, ChatGPT, Gemini ou Perplexity", color: "purple" },
          { label: "Outils Spécialisés", sub: "Midjourney, Cursor, ElevenLabs…", color: "emerald" },
          { label: "Templates de Prompts", sub: "Réutilisables pour chaque tâche", color: "amber" },
        ]},
        { type: "summary", items: [
          "Un bon workflow IA = 3 à 5 outils maîtrisés en profondeur",
          "Étape 1 : auditer votre temps pour identifier les tâches automatisables",
          "Étape 2 : choisir votre LLM principal selon votre cas d'usage",
          "Étape 3 : sélectionner 1 à 2 outils spécialisés pour votre métier",
          "Étape 4 : créer des templates de prompts pour vos tâches récurrentes"
        ]},
      ],
      quiz: [
        { question: "Combien d'outils un workflow IA efficace devrait-il inclure ?", options: ["1 seul outil", "3 à 5 outils maîtrisés en profondeur", "10 à 15 outils variés", "Tous les outils disponibles"], correctIndex: 1, explanation: "Un workflow IA efficace repose sur 3 à 5 outils maîtrisés en profondeur plutôt que sur une dizaine d'outils utilisés superficiellement." },
        { question: "Quel est le pourcentage de tâches intellectuelles qui peuvent être accélérées par l'IA ?", options: ["5 à 10%", "15 à 25%", "40 à 60%", "100%"], correctIndex: 2, explanation: "En général, 40 à 60% des tâches intellectuelles quotidiennes (rédaction, analyse, recherche, résumé) peuvent être significativement accélérées avec les bons outils IA." },
        { question: "Que sont les prompts templates ?", options: ["Des images générées par l'IA", "Des prompts réutilisables pour des tâches récurrentes", "Des abonnements à des outils IA", "Des templates de sites web"], correctIndex: 1, explanation: "Les prompts templates sont des prompts réutilisables créés pour vos tâches récurrentes (emails, analyses, idées) qui s'améliorent avec l'expérience." },
        { question: "Quel LLM est recommandé si vous travaillez principalement sur de la rédaction et de l'analyse ?", options: ["ChatGPT", "Perplexity", "Claude 4.6", "Gemini"], correctIndex: 2, explanation: "Claude 4.6 est particulièrement recommandé pour les tâches de rédaction et d'analyse grâce à sa précision, sa nuance et sa capacité à respecter des instructions complexes." },
      ],
    },
    {
      number: 18,
      title: "Comparatif Final et Tendances 2026",
      description: "Tableau comparatif de tous les outils, cas d'usage recommandés et tendances à venir.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Récapitulatif : quel outil pour quel besoin ?" },
        { type: "paragraph", content: "Après avoir exploré 18 catégories d'outils, voici le guide de référence rapide pour choisir le bon outil selon votre besoin. Ces recommandations sont basées sur l'état de l'art de mars 2026." },
        { type: "subheading", content: "Chatbots et texte" },
        { type: "paragraph", content: "Rédaction nuancée et analyse : Claude 4.6. Polyvalence et Computer Use : ChatGPT GPT-5.4. Recherche avec sources : Perplexity. Intégration Google : Gemini 3.1. Code : Cursor + Claude. Documents longs : NotebookLM." },
        { type: "subheading", content: "Images et création visuelle" },
        { type: "paragraph", content: "Qualité artistique maximale : Midjourney V8. Texte dans les images : DALL-E 3. Usage commercial sûr : Adobe Firefly. Typographie : Ideogram. Contrôle total gratuit : Stable Diffusion." },
        { type: "subheading", content: "Vidéo et audio" },
        { type: "paragraph", content: "Vidéo photoréaliste : Sora 2. Cinématographique : Runway Gen-3. Mouvement humain : Kling AI. Effets créatifs : Pika 2.0. Voix pro : ElevenLabs. Musique complète : Suno V4 ou Udio." },
        { type: "subheading", content: "Les tendances à surveiller en 2026-2027" },
        { type: "paragraph", content: "Agents IA autonomes : les outils qui effectuent des tâches complexes de façon autonome vont exploser. Modèles locaux : des modèles de plus en plus puissants tournent sur votre ordinateur. IA multimodale native : tous les modèles vont traiter texte, image, audio et vidéo simultanément. Personnalisation : les IA apprennent votre style et s'adaptent à vous." },
        { type: "key-point", content: "L'IA n'est pas un outil statique — elle évolue chaque mois. L'investissement le plus rentable est d'apprendre à apprendre : comment tester rapidement un nouvel outil, évaluer sa valeur ajoutée, et l'intégrer à votre workflow existant." },
        { type: "diagram", label: "Guide Rapide : Quel Outil pour Quel Besoin ?", flow: "vertical", nodes: [
          { label: "Rédaction & Analyse", sub: "Claude 4.6 — précision et nuance", color: "purple" },
          { label: "Recherche Web", sub: "Perplexity — sources en temps réel", color: "blue" },
          { label: "Images Artistiques", sub: "Midjourney V8 — qualité maximale", color: "emerald" },
          { label: "Vidéo Photoréaliste", sub: "Sora 2 — physique cohérente", color: "amber" },
          { label: "Voix Professionnelle", sub: "ElevenLabs — 32 langues, clonage vocal", color: "pink" },
        ]},
        { type: "summary", items: [
          "Claude 4.6 pour la rédaction, ChatGPT pour la polyvalence, Perplexity pour la recherche",
          "Midjourney V8 pour les images artistiques, DALL-E 3 pour le texte dans les images",
          "Sora 2 pour la vidéo photoréaliste, ElevenLabs pour la voix professionnelle",
          "Les agents IA autonomes sont la tendance dominante de 2026-2027",
          "Apprendre à apprendre rapidement un nouvel outil est la compétence clé"
        ]},
      ],
      quiz: [
        { question: "Quel outil est recommandé pour générer des images contenant du texte précis ?", options: ["Midjourney V8", "Stable Diffusion", "DALL-E 3", "Adobe Firefly"], correctIndex: 2, explanation: "DALL-E 3 est le meilleur outil pour générer des images contenant du texte précis et lisible, surpassant Midjourney dans cette spécialité." },
        { question: "Quelle est la tendance dominante de l'IA en 2026-2027 ?", options: ["Les chatbots plus simples", "Les agents IA autonomes", "La reconnaissance vocale", "La traduction automatique"], correctIndex: 1, explanation: "Les agents IA autonomes — capables d'effectuer des tâches complexes de façon autonome sans intervention humaine — sont la tendance dominante de 2026-2027." },
        { question: "Pour l'usage commercial d'images générées par IA, quel outil offre la couverture juridique la plus sûre ?", options: ["Midjourney", "Stable Diffusion", "DALL-E 3", "Adobe Firefly"], correctIndex: 3, explanation: "Adobe Firefly est entraîné exclusivement sur des contenus commercialement sûrs, offrant la meilleure couverture juridique pour les usages commerciaux professionnels." },
        { question: "Quelle est la compétence clé pour réussir dans l'ère de l'IA ?", options: ["Apprendre à programmer en Python", "Mémoriser toutes les fonctionnalités de chaque outil", "Apprendre à tester et intégrer rapidement les nouveaux outils", "Acheter tous les abonnements IA"], correctIndex: 2, explanation: "La compétence clé est d'apprendre à apprendre rapidement : savoir tester un nouvel outil, évaluer sa valeur ajoutée et l'intégrer efficacement à son workflow existant." },
      ],
    },
  ],
};

export default content;
