import type { CourseContent } from "../../types";

const content: CourseContent = {
  slug: "maitriser-outils-ia",
  chapters: [
    {
      number: 1,
      title: "Overview of AI Tools in 2026",
      description: "A tour of the main AI tool categories and how to choose the right ones.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "The AI tools ecosystem in 2026" },
        { type: "paragraph", content: "In 2026, the AI tools landscape is vast: conversational chatbots, image generators, video tools, audio assistants, coding tools, automation platforms... Hundreds of tools exist, but a handful dominate each category. This course guides you to the best ones." },
        { type: "subheading", content: "The major categories" },
        { type: "paragraph", content: "Chatbots and text assistants: ChatGPT, Claude, Gemini, Mistral. Image generation: Midjourney, DALL-E, Stable Diffusion, Firefly. Video: Sora 2, Runway Gen-3, Pika, Kling. Audio and voice: ElevenLabs, Suno, Udio. Code: Cursor, GitHub Copilot, Claude Code. Research: Perplexity. Automation: Make, Zapier." },
        { type: "subheading", content: "How do you choose the right tools?" },
        { type: "paragraph", content: "Three main criteria: your use case (text, images, code?), your budget (free, subscription, pay-per-use), and your technical level. Always start with the free versions before upgrading to paid plans." },
        { type: "tip", content: "The 3-tool rule: pick one generalist tool (ChatGPT or Claude), one specialized tool for your field, and one automation tool. That's all you need to transform your productivity." },
        { type: "key-point", content: "In 2026, the best AI tools are accessible without any technical knowledge. Natural language interfaces have democratized access to capabilities once reserved for engineers." },
        { type: "summary", items: [
          "The AI ecosystem is divided into 7 main categories",
          "A handful of tools dominate each category",
          "Selection criteria: use case, budget, technical level",
          "Always start with the free versions",
          "3 well-chosen tools are enough to transform your productivity"
        ]},
      ],
      quiz: [
        { question: "How many tools do you need to master to transform your productivity?", options: ["Just 1 tool", "3 well-chosen tools", "10 different tools", "Every available tool"], correctIndex: 1, explanation: "Three well-chosen tools — one generalist, one specialized, one for automation — are enough to significantly transform your productivity." },
        { question: "What is the first criterion for choosing an AI tool?", options: ["The price", "Its popularity on social media", "Your use case", "Its release date"], correctIndex: 2, explanation: "Your use case is the primary criterion: what do you want to use AI for? Text, images, code, automation? Each need has its best tools." },
        { question: "What is the best practice before paying for an AI subscription?", options: ["Buy the pro version immediately", "Try the free version first", "Ask a friend", "Read all the reviews"], correctIndex: 1, explanation: "Always test the free version first. Most AI tools offer free trials that let you evaluate whether they meet your needs." },
        { question: "What made AI tools accessible to everyone in 2026?", options: ["Lower computer prices", "Natural language interfaces", "Mandatory training in schools", "Social media"], correctIndex: 1, explanation: "Natural language interfaces (simply writing what you want) democratized access to AI tools, requiring no technical knowledge." },
      ],
    },
    {
      number: 2,
      title: "ChatGPT and GPT-5.4 — The Industry Standard",
      description: "Master ChatGPT: modes, Custom GPTs, Computer Use, and advanced tips.",
      estimatedMinutes: 10,
      sections: [
        { type: "heading", content: "ChatGPT in 2026: far more than a chatbot" },
        { type: "paragraph", content: "ChatGPT, launched by OpenAI in 2022, has become the global reference with over 500 million active users in 2026. GPT-5.4, released on March 5, 2026, is available in three variants: Standard, Thinking (advanced reasoning), and Pro (maximum capability)." },
        { type: "subheading", content: "ChatGPT modes" },
        { type: "paragraph", content: "Standard mode: fast responses for everyday tasks. Thinking mode: the model reasons step by step before answering — ideal for complex problems, code, or math. Pro mode: access to GPT-5.4 Pro with top performance for the most demanding tasks." },
        { type: "subheading", content: "Custom GPTs — Build your personalized assistant" },
        { type: "paragraph", content: "Custom GPTs let you create specialized AI assistants without writing any code. You define instructions, upload reference documents, and connect tools. Example: a Custom GPT that writes exclusively in your brand's voice, with access to your style guide." },
        { type: "subheading", content: "Computer Use — AI that controls your computer" },
        { type: "paragraph", content: "GPT-5.4 natively integrates Computer Use: it can browse the web, fill out forms, extract data, and perform repetitive tasks on your computer. This is the most revolutionary feature of 2026 for autonomous AI agents." },
        { type: "callout", content: "Tip: use Thinking mode for complex analyses, difficult code, or important decisions. Response quality is significantly higher than Standard mode, though it takes more time." },
        { type: "summary", items: [
          "GPT-5.4 comes in 3 variants: Standard, Thinking, and Pro",
          "1.05 million token context window — equivalent to an entire novel",
          "Custom GPTs let you create specialized assistants without code",
          "Computer Use: AI can autonomously control your computer",
          "33% fewer hallucinations than GPT-5.2"
        ]},
      ],
      quiz: [
        { question: "How many variants does GPT-5.4 offer?", options: ["1 (Standard only)", "2 (Standard and Pro)", "3 (Standard, Thinking, Pro)", "4 (Lite, Standard, Thinking, Pro)"], correctIndex: 2, explanation: "GPT-5.4 is available in 3 variants: Standard for everyday tasks, Thinking for advanced reasoning, and Pro for maximum capabilities." },
        { question: "What does Computer Use in ChatGPT allow?", options: ["Speed up your computer", "Autonomously control your computer", "Fix system bugs", "Install software"], correctIndex: 1, explanation: "Computer Use allows GPT-5.4 to browse the web, fill out forms, and perform repetitive tasks on your computer, just like a human operator." },
        { question: "Which mode should you use in ChatGPT to solve a complex coding problem?", options: ["Standard mode", "Light mode", "Thinking mode", "Basic mode"], correctIndex: 2, explanation: "Thinking mode is recommended for complex problems because the model reasons step by step before answering, producing higher-quality results." },
        { question: "What are Custom GPTs?", options: ["Modified versions of GPT-4", "Specialized AI assistants created without code", "Paid plugins", "Offline versions of ChatGPT"], correctIndex: 1, explanation: "Custom GPTs allow anyone to create a specialized AI assistant by defining instructions and uploading reference documents — no programming required." },
      ],
    },
    {
      number: 3,
      title: "Claude 4.6 — The Most Precise AI",
      description: "Master Claude: Opus/Sonnet/Haiku, Projects, artifacts, and Claude Code.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Claude by Anthropic: precision and honesty" },
        { type: "paragraph", content: "Claude, developed by Anthropic, stands out for its precision, honesty, and ability to acknowledge uncertainty. In 2026, Claude 4.6 is available in three versions: Opus 4.6 (the most powerful), Sonnet 4.6 (the best speed-to-quality ratio), and Haiku 4.5 (fast and economical)." },
        { type: "subheading", content: "Claude Opus 4.6 — Maximum power" },
        { type: "paragraph", content: "Opus 4.6 offers a 1-million-token context window and a task horizon of 14.5 hours — the longest of any model. It excels at complex reasoning, analyzing long documents, advanced coding, and deep research." },
        { type: "subheading", content: "Projects — Your persistent workspace" },
        { type: "paragraph", content: "Projects let you give Claude permanent context: upload your documents, define your style, preferences, and project background. Claude remembers all of this between conversations. Ideal for long-running projects or teams." },
        { type: "subheading", content: "Artifacts — Structured content in real time" },
        { type: "paragraph", content: "Artifacts display structured content (code, HTML, SVG, tables) in a separate panel in real time. You can preview HTML code directly or edit content interactively. This is especially powerful for web development." },
        { type: "subheading", content: "Claude Code — Your AI developer in the command line" },
        { type: "paragraph", content: "Claude Code is a CLI tool that integrates Claude directly into your terminal. It can read, write, and modify files, execute commands, and manage entire projects autonomously. Developers consider it the most advanced AI coding tool of 2026." },
        { type: "tip", content: "For creative and writing tasks, Claude often outperforms ChatGPT thanks to its nuance and ability to follow complex instructions. Try Claude for your important emails, reports, and analyses." },
        { type: "summary", items: [
          "Claude 4.6 comes in 3 versions: Opus (powerful), Sonnet (balanced), Haiku (fast)",
          "1 million token context window — equivalent to 750,000 words",
          "Projects give Claude permanent context across sessions",
          "Artifacts display code and HTML in real time in a separate panel",
          "Claude Code manages entire projects directly from the terminal"
        ]},
      ],
      quiz: [
        { question: "What is the maximum autonomous task duration for Claude Opus 4.6?", options: ["1 hour", "4 hours", "14.5 hours", "24 hours"], correctIndex: 2, explanation: "Claude Opus 4.6 can sustain a task for up to 14.5 hours straight — the longest task horizon of any AI model in 2026." },
        { question: "What are Projects in Claude used for?", options: ["Organizing files on your computer", "Giving Claude permanent context across sessions", "Generating images", "Sharing conversations with friends"], correctIndex: 1, explanation: "Projects let you upload documents and define context that Claude retains across all conversations related to that project." },
        { question: "What is Claude Code?", options: ["A programming language created by Anthropic", "A CLI tool that integrates Claude in the terminal", "An online code editor", "A VS Code extension"], correctIndex: 1, explanation: "Claude Code is a command-line tool that integrates Claude directly into the terminal to autonomously read, write, and modify code files." },
        { question: "For which task is Claude particularly recommended?", options: ["Image generation", "Video creation", "Nuanced writing and complex analysis", "Audio editing"], correctIndex: 2, explanation: "Claude excels at nuanced writing, complex analysis, and following detailed instructions, making it the preferred choice for important emails and reports." },
      ],
    },
    {
      number: 4,
      title: "Gemini 3.1 — Google's AI",
      description: "G Suite integration, Gemini Advanced, document analysis, and multimodality.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Gemini 3.1: AI native to the Google ecosystem" },
        { type: "paragraph", content: "Gemini 3.1, developed by Google DeepMind, is the AI model most deeply integrated into an application ecosystem. Natively multimodal, it processes text, images, audio, video, and code simultaneously. Its integration into Gmail, Google Docs, Sheets, and Drive makes it indispensable for Google users." },
        { type: "subheading", content: "Gemini Advanced — The premium version" },
        { type: "paragraph", content: "Gemini Advanced (included in Google One Premium) provides access to Gemini 3.1 Pro with a 1-million-token context window. It can analyze entire PDF documents, complex spreadsheets, or hours of video in a single conversation." },
        { type: "subheading", content: "Google Workspace integration" },
        { type: "paragraph", content: "In Gmail: automatic email summaries, reply drafting, instant translation. In Google Docs: content generation, style improvement, document summarization. In Sheets: data analysis, complex formula generation, automatic visualization. In Meet: real-time transcription, meeting summaries." },
        { type: "subheading", content: "Gemini's strengths" },
        { type: "paragraph", content: "Gemini 3.1 excels at: analyzing very long documents (up to 1M tokens), real-time web search (integrated Google Search), native multimodal processing, and integration into Google workflows. Its score of 77.1% on ARC-AGI-2 places it among the top reasoning models." },
        { type: "callout", content: "If you're already in the Google ecosystem (Gmail, Drive, Docs), Gemini is your best choice because it accesses your files and emails directly — no copy-pasting needed." },
        { type: "summary", items: [
          "Gemini 3.1 is natively multimodal: text, image, audio, video, code",
          "1 million token context window in Gemini Advanced",
          "Integrated into Gmail, Docs, Sheets, Meet — no copy-pasting",
          "77.1% score on ARC-AGI-2, among the top reasoning models",
          "Access to real-time Google Search for always up-to-date answers"
        ]},
      ],
      quiz: [
        { question: "What is Gemini's biggest strength compared to other LLMs?", options: ["It's free for everyone", "Its native integration in the Google ecosystem", "It supports more languages", "It generates images faster"], correctIndex: 1, explanation: "Gemini's biggest strength is its direct integration into Gmail, Google Docs, Sheets, and Drive, allowing you to work without copy-pasting." },
        { question: "What does Gemini's native multimodality mean?", options: ["It works on multiple devices", "It processes text, images, audio, and video simultaneously", "It supports multiple languages", "Multiple people can use it at once"], correctIndex: 1, explanation: "Native multimodality means Gemini can process and combine different types of data (text, images, audio, video) within a single conversation." },
        { question: "Which subscription gives access to Gemini Advanced?", options: ["Google One Premium", "YouTube Premium", "Google Play Pass", "Chrome Enterprise"], correctIndex: 0, explanation: "Gemini Advanced is included in the Google One Premium subscription, which also includes extra storage and other Google benefits." },
        { question: "What is Gemini 3.1's score on ARC-AGI-2?", options: ["55.3%", "68.9%", "77.1%", "92.4%"], correctIndex: 2, explanation: "Gemini 3.1 Pro scores 77.1% on the ARC-AGI-2 benchmark, an abstract reasoning test, placing it among the top models of 2026." },
      ],
    },
    {
      number: 5,
      title: "Midjourney V7/V8 — The Art of Image Generation",
      description: "/imagine commands, parameters, styles, and advanced Midjourney techniques.",
      estimatedMinutes: 10,
      sections: [
        { type: "heading", content: "Midjourney: the undisputed leader in image generation" },
        { type: "paragraph", content: "Midjourney is recognized as the highest-quality AI image generation tool for aesthetic results. Versions V7 and V8 (2025-2026) have set a new bar for character consistency, lighting, and photographic detail." },
        { type: "subheading", content: "The basic command: /imagine" },
        { type: "paragraph", content: "Everything starts with /imagine followed by your description (prompt). Example: /imagine prompt: a golden hour portrait of a young woman in Paris, film photography, 35mm, bokeh. The more precise and detailed your description, the better the result." },
        { type: "subheading", content: "Essential parameters" },
        { type: "paragraph", content: "Aspect ratio: --ar 16:9 (landscape), --ar 9:16 (portrait), --ar 1:1 (square). Quality: --q 2 for maximum quality. Style: --style raw for a more realistic render, --style expressive for more creativity. Version: --v 8 for the latest version. Negatives: --no text, logo to exclude those elements." },
        { type: "subheading", content: "Advanced techniques" },
        { type: "paragraph", content: "Image reference (--iref): use an existing image as a style reference. Character reference (--cref): maintain character consistency across multiple images. Seed (--seed): reproduce the exact same result. Style reference (--sref): copy the style of a reference image." },
        { type: "subheading", content: "Midjourney modes" },
        { type: "paragraph", content: "Fast mode: quick generation, uses credits. Relax mode: free but slower. Turbo mode: ultra-fast generation for Pro subscribers. Stealth mode: your creations remain private (Pro subscription required)." },
        { type: "tip", content: "For professional portraits: always use --ar 4:5, add 'professional lighting, sharp focus, 85mm portrait lens', and try --style raw for a less artificial look." },
        { type: "summary", items: [
          "The basic command is /imagine followed by a precise description",
          "Key parameters: --ar (ratio), --q (quality), --style, --v (version)",
          "Character Reference (--cref) maintains character consistency",
          "Style Reference (--sref) copies the style of an existing image",
          "Subscription required: Basic ($10/mo), Standard ($30), Pro ($60), Mega ($120)"
        ]},
      ],
      quiz: [
        { question: "Which command is used to generate an image in Midjourney?", options: ["/create", "/generate", "/imagine", "/draw"], correctIndex: 2, explanation: "The /imagine command is Midjourney's main image generation command. It is followed by the word 'prompt:' and then your description." },
        { question: "Which parameter defines the aspect ratio of an image in Midjourney?", options: ["--size", "--ar", "--ratio", "--format"], correctIndex: 1, explanation: "The --ar (aspect ratio) parameter defines the image ratio. Examples: --ar 16:9 for landscape, --ar 9:16 for portrait, --ar 1:1 for square." },
        { question: "What does the --cref parameter do in Midjourney V8?", options: ["Choose a reference color", "Maintain character consistency across multiple images", "Copy an artist's style", "Define the output resolution"], correctIndex: 1, explanation: "--cref (character reference) maintains visual consistency of a character across multiple image generations." },
        { question: "Which Midjourney mode is free but slower?", options: ["Fast Mode", "Turbo Mode", "Relax Mode", "Stealth Mode"], correctIndex: 2, explanation: "Relax Mode is available for free to Standard and Pro subscribers but generations take longer since they have lower priority." },
      ],
    },
    {
      number: 6,
      title: "DALL-E 3 and Alternative Image Generators",
      description: "DALL-E 3, Adobe Firefly, Ideogram, Playground AI — strengths and use cases.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Beyond Midjourney: powerful alternatives" },
        { type: "paragraph", content: "While Midjourney dominates artistic aesthetics, other tools excel in specific areas. DALL-E 3 is integrated into ChatGPT and shines for images with text. Adobe Firefly is built for creative professionals with clear commercial rights. Ideogram is the top choice for typography." },
        { type: "subheading", content: "DALL-E 3 — The power of text in images" },
        { type: "paragraph", content: "DALL-E 3, accessible directly inside ChatGPT, is unbeatable for generating images containing precise, readable text: logos with text, posters, interface mockups, infographics. It understands highly detailed instructions thanks to its integration with GPT-5.4." },
        { type: "subheading", content: "Adobe Firefly — Creation without legal risk" },
        { type: "paragraph", content: "Adobe Firefly is trained exclusively on Adobe Stock images and Creative Commons-licensed content. Its creations are safe for commercial use without any copyright infringement risk. Ideal for design professionals, agencies, and businesses." },
        { type: "subheading", content: "Ideogram — Perfect typography" },
        { type: "paragraph", content: "Ideogram 3.0 specializes in generating images with flawless typography. It can create logos, posters, and graphic designs where text is perfectly integrated. Its letter accuracy surpasses every other model." },
        { type: "subheading", content: "Playground AI — The versatile free tool" },
        { type: "paragraph", content: "Playground AI offers an intuitive web interface with access to multiple models (SDXL, Playground v3). It provides a generous free plan and advanced editing features like inpainting and outpainting directly in the browser." },
        { type: "key-point", content: "Golden rule: Midjourney for artistic aesthetics, DALL-E 3 for images with text, Firefly for safe commercial use, Ideogram for typography, Stable Diffusion for total control." },
        { type: "summary", items: [
          "DALL-E 3 excels at images containing precise, readable text",
          "Adobe Firefly is legally safe for commercial use",
          "Ideogram 3.0 is the best tool for typography in images",
          "Playground AI offers a generous free plan with multiple models",
          "Each tool has a specialty: choose based on your specific need"
        ]},
      ],
      quiz: [
        { question: "For which use case is DALL-E 3 the best choice?", options: ["Artistic portraits", "Images containing precise text", "Photorealistic landscapes", "Manga illustrations"], correctIndex: 1, explanation: "DALL-E 3 is unbeatable for generating images containing readable, precise text: logos, posters, interface mockups, infographics." },
        { question: "Why is Adobe Firefly particularly well-suited for professionals?", options: ["It's faster than the others", "It's trained on commercially safe content", "It generates 4K images", "It's cheaper"], correctIndex: 1, explanation: "Firefly is trained exclusively on Adobe Stock and Creative Commons images, making it legally safe for commercial use without copyright infringement risk." },
        { question: "Which tool specializes in generating perfect typography?", options: ["Midjourney", "DALL-E 3", "Ideogram", "Stable Diffusion"], correctIndex: 2, explanation: "Ideogram 3.0 specializes in typography and generating images with perfectly integrated text — logos, posters, graphic designs." },
        { question: "Which platform offers generous free access to multiple generation models?", options: ["Adobe Firefly", "Midjourney", "DALL-E 3", "Playground AI"], correctIndex: 3, explanation: "Playground AI offers a generous free plan with access to multiple models (SDXL, Playground v3) and advanced editing features directly in the browser." },
      ],
    },
    {
      number: 7,
      title: "Stable Diffusion — The Open Source Swiss Army Knife",
      description: "Local installation, ComfyUI, ControlNet, and advanced Stable Diffusion techniques.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Stable Diffusion: total freedom" },
        { type: "paragraph", content: "Stable Diffusion is an open-source image generation model that can be installed locally on your computer. Free and uncensored, it offers complete control over every aspect of generation. In 2026, SDXL and SD3 are the most widely used versions." },
        { type: "subheading", content: "ComfyUI — The ultimate advanced interface" },
        { type: "paragraph", content: "ComfyUI is a node-based visual interface that lets you build complex generation workflows. You visually connect the different steps: model, sampler, VAE, upscaler. It is the preferred tool of advanced users for its maximum flexibility." },
        { type: "subheading", content: "ControlNet — Precisely controlling composition" },
        { type: "paragraph", content: "ControlNet is a revolutionary extension that lets you precisely control image composition: character pose (OpenPose), edges and shapes (Canny), depth (Depth), architectural lines (MLSD). You can generate an image in exactly the pose you want." },
        { type: "subheading", content: "LoRAs — Custom styles" },
        { type: "paragraph", content: "LoRAs (Low-Rank Adaptation) are small add-on models that introduce a specific style or subject. You can download LoRAs for a particular artistic style or character, or train your own LoRA using your own photos." },
        { type: "subheading", content: "img2img — Transform existing images" },
        { type: "paragraph", content: "The img2img mode lets you modify an existing image while preserving its overall composition. Useful for stylizing a photo, correcting details, or turning a sketch into a detailed illustration. The 'denoising strength' parameter controls the intensity of the transformation." },
        { type: "tip", content: "To get started with Stable Diffusion without a local installation, first try online versions like Leonardo.ai or NightCafe. They use Stable Diffusion with a simplified interface and cloud servers." },
        { type: "summary", items: [
          "Stable Diffusion is free, open source, and can run locally",
          "ComfyUI offers a node-based visual workflow for advanced users",
          "ControlNet lets you control pose, edges, and composition",
          "LoRAs add custom styles or characters",
          "img2img transforms an existing image while preserving its composition"
        ]},
      ],
      quiz: [
        { question: "What is Stable Diffusion's main strength compared to other tools?", options: ["It generates images faster", "It is free, open source, and can run locally", "Its images are higher quality", "It requires less VRAM"], correctIndex: 1, explanation: "Stable Diffusion's main strength is being open source, free, and installable locally, offering total control and maximum privacy." },
        { question: "What does ControlNet do in Stable Diffusion?", options: ["Control generation speed", "Precisely control composition and pose", "Control usage rights", "Control output resolution"], correctIndex: 1, explanation: "ControlNet lets you precisely control image composition using visual guides: character pose (OpenPose), edges (Canny), depth (Depth)." },
        { question: "What are LoRAs in Stable Diffusion?", options: ["A type of graphics processor", "Small add-on models that introduce a specific style", "An image file format", "A user interface"], correctIndex: 1, explanation: "LoRAs are small add-on models that complement the main model to reproduce a particular artistic style, character, or aesthetic." },
        { question: "In img2img mode, what does the 'denoising strength' parameter control?", options: ["The image resolution", "The intensity of the transformation applied to the original image", "The number of generation steps", "The color saturation"], correctIndex: 1, explanation: "Denoising strength controls transformation intensity: a low value (0.2-0.4) preserves the original image, while a high value (0.7-1.0) transforms it radically." },
      ],
    },
    {
      number: 8,
      title: "Sora 2 — Video Generation by OpenAI",
      description: "Create, edit, and compose videos with Sora 2 — techniques and limitations.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Sora 2: the AI-generated video revolution" },
        { type: "paragraph", content: "Sora 2 from OpenAI, available since early 2026, generates videos of stunning realism: coherent physics, synchronized dialogue, integrated sound effects, and narrative continuity. It is the tool that has most disrupted the creative industry in 2025-2026." },
        { type: "subheading", content: "Key features of Sora 2" },
        { type: "paragraph", content: "Text-to-video generation: describe a scene in text and get a video up to 60 seconds long. Image-to-video: animate a still image. Video-to-video: transform an existing video. Video extension: extend an existing video. Re-cut: edit specific parts of a generated video." },
        { type: "subheading", content: "Writing a good video prompt" },
        { type: "paragraph", content: "An effective video prompt describes: the main subject, the action, the framing (wide shot, close-up, medium shot), the camera movement (tracking shot, pan, zoom), the lighting mood, and the visual style. Example: 'Close-up shot of a woman walking through a rainy Parisian street at night, slow motion, cinematic lighting, shallow depth of field, moody atmosphere.'" },
        { type: "subheading", content: "Current limitations of Sora 2" },
        { type: "paragraph", content: "Despite its advances, Sora 2 still has limitations: hands and fingers sometimes incorrect in very tight close-ups, limited character consistency over long sequences, high price (included in ChatGPT Pro at $200/month), and a maximum clip length of 60 seconds." },
        { type: "subheading", content: "AI storyboard — Plan your video" },
        { type: "paragraph", content: "Use ChatGPT to first create a detailed scene-by-scene storyboard, then generate each scene separately with Sora 2. Then edit the clips with a standard tool (CapCut, DaVinci Resolve). This is the workflow adopted by professional creators." },
        { type: "callout", content: "Sora 2 is included in the ChatGPT Pro subscription ($200/month). For occasional creators, alternatives like Runway Gen-3 or Kling deliver good results at more accessible prices." },
        { type: "summary", items: [
          "Sora 2 generates videos up to 60 seconds with coherent physics",
          "Supports: text-to-video, image-to-video, extension, and editing",
          "Effective video prompts describe the subject, action, framing, and mood",
          "Limitations: hands sometimes incorrect, limited consistency on long sequences",
          "Pro workflow: storyboard with ChatGPT, scene-by-scene generation, external editing"
        ]},
      ],
      quiz: [
        { question: "What is the maximum clip length Sora 2 can generate?", options: ["15 seconds", "30 seconds", "60 seconds", "5 minutes"], correctIndex: 2, explanation: "Sora 2 can generate videos up to 60 seconds per clip. For longer videos, you need to generate multiple clips and edit them together." },
        { question: "What is the recommended workflow for creating a long video with Sora 2?", options: ["Generate everything at once", "Storyboard with ChatGPT, generate scene by scene, then edit", "Use only image-to-video mode", "Import an existing video"], correctIndex: 1, explanation: "The pro workflow involves creating a storyboard with ChatGPT first, then generating each scene separately with Sora 2, and finally editing the clips with an external tool." },
        { question: "Which subscription includes Sora 2?", options: ["ChatGPT Free", "ChatGPT Plus ($20/month)", "ChatGPT Pro ($200/month)", "ChatGPT Team"], correctIndex: 2, explanation: "Sora 2 is included in the ChatGPT Pro subscription at $200/month, making it primarily accessible to professionals and intensive creators." },
        { question: "What limitation does Sora 2 still have in 2026?", options: ["It only generates black and white videos", "Hands are sometimes incorrect in close-ups", "It only supports English", "Videos are limited to 10 seconds"], correctIndex: 1, explanation: "Despite its advances, Sora 2 still struggles with hands and fingers in very tight close-ups, a limitation common to most AI video models." },
      ],
    },
    {
      number: 9,
      title: "Runway Gen-3, Pika, and Kling — Video Alternatives",
      description: "Comparison of AI video tools: strengths, pricing, and use cases for each.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "The AI video tools ecosystem in 2026" },
        { type: "paragraph", content: "Sora 2 isn't the only video generation tool. Runway, Pika, and Kling offer accessible alternatives with different strengths. The choice depends on your budget, content type, and required quality level." },
        { type: "subheading", content: "Runway Gen-3 Alpha — The cinematic benchmark" },
        { type: "paragraph", content: "Runway Gen-3 Alpha excels at cinematic-quality videos with precise camera movement control (Motion Brush), character consistency, and image interpolation. Widely used in advertising and film. Subscriptions starting at $15/month with 625 credits." },
        { type: "subheading", content: "Pika 2.0 — Accessible creativity" },
        { type: "paragraph", content: "Pika 2.0 stands out for its unique creative effects: style transformation (Pikaffects), one-click special effects, and a very intuitive interface. It is particularly popular with social media content creators thanks to its speed and impactful visual effects." },
        { type: "subheading", content: "Kling AI — Surprisingly high Chinese quality" },
        { type: "paragraph", content: "Kling AI (developed by Kuaishou) surprised the industry in 2025 with the quality of its videos, especially in human motion and facial expressions. It offers videos up to 3 minutes long with remarkable character consistency. Competitive pricing compared to US alternatives." },
        { type: "subheading", content: "How to choose?" },
        { type: "paragraph", content: "Cinematic quality and camera control: Runway Gen-3. Creative effects and social media: Pika 2.0. Realistic human motion and long sequences: Kling AI. Limited budget with maximum quality: Sora 2 (if you have ChatGPT Pro)." },
        { type: "tip", content: "Try all the free plans before subscribing. Runway offers 125 free credits, Pika offers free trials, and Kling AI has a generous free plan. Compare results on your specific type of content." },
        { type: "summary", items: [
          "Runway Gen-3: best for cinematic quality and camera control",
          "Pika 2.0: ideal for creative effects and social media content",
          "Kling AI: excellent for realistic human motion and long sequences",
          "All offer free plans to test before buying",
          "The choice depends on content type, budget, and intended use"
        ]},
      ],
      quiz: [
        { question: "Which video tool is particularly recognized for creative effects (Pikaffects)?", options: ["Runway Gen-3", "Sora 2", "Pika 2.0", "Kling AI"], correctIndex: 2, explanation: "Pika 2.0 stands out for its unique creative effects called Pikaffects, which enable spectacular visual transformations in one click." },
        { question: "What strength sets Kling AI apart from other video tools?", options: ["8K video generation", "Realistic human motion and character consistency", "Animated text effects", "Synchronized music generation"], correctIndex: 1, explanation: "Kling AI stands out for its exceptional handling of human motion and facial expressions, as well as its character consistency across long sequences." },
        { question: "For what type of production is Runway Gen-3 primarily used?", options: ["Video games", "Advertising and film", "Instagram stories", "Video podcasts"], correctIndex: 1, explanation: "Runway Gen-3 is widely used in professional advertising and film thanks to its cinematic quality and precise camera movement control." },
        { question: "What is the maximum video length Kling AI can generate?", options: ["30 seconds", "1 minute", "3 minutes", "10 minutes"], correctIndex: 2, explanation: "Kling AI can generate videos up to 3 minutes long, setting it apart from most competitors limited to 60 seconds." },
      ],
    },
    {
      number: 10,
      title: "ElevenLabs — Professional AI Voice",
      description: "Voice cloning, multilingual generation, automatic dubbing, and the ElevenLabs API.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "ElevenLabs: the world reference for AI voice" },
        { type: "paragraph", content: "ElevenLabs has established itself as the global standard for AI voice synthesis, with voices indistinguishable from human ones. Founded in 2022, it offers in 2026 over 3,000 voices in 32 languages, voice cloning with just 1 minute of audio, and automatic video dubbing." },
        { type: "subheading", content: "The voice library" },
        { type: "paragraph", content: "ElevenLabs offers professional voices categorized by use: narration, podcast, advertising, e-learning, social media. Each voice has adjustable parameters: stability (consistency), clarity (articulation), and style (expressiveness). The Voice Lab lets you customize any voice." },
        { type: "subheading", content: "Instant Voice Cloning — Clone a voice in 1 minute" },
        { type: "paragraph", content: "With just 1 minute of clean audio recording, ElevenLabs clones a voice with remarkable accuracy. Professional Voice Cloning (with 30 minutes of audio) delivers near-perfect quality. Ideal for podcast creators, narrators, and companies that want a consistent brand voice." },
        { type: "subheading", content: "Dubbing — Automatic video dubbing" },
        { type: "paragraph", content: "The Dubbing feature automatically translates and dubs a video into another language while preserving the original speaker's voice. A French video can be dubbed into English, Spanish, German, or Japanese in just a few minutes, with approximate lip sync." },
        { type: "subheading", content: "The ElevenLabs API — Integrate voice into your applications" },
        { type: "paragraph", content: "The ElevenLabs API lets you integrate voice synthesis into any application: AI agents with voice, phone assistants, e-learning apps, automatic audiobooks. Latency is under 500ms for real-time applications." },
        { type: "key-point", content: "ElevenLabs is available with a free plan (10,000 characters/month) and paid plans starting at $5/month for 30,000 characters. Professional creators typically opt for the Creator plan at $22/month." },
        { type: "summary", items: [
          "Over 3,000 voices in 32 languages with quality indistinguishable from human voices",
          "Voice cloning with just 1 minute of audio recording",
          "Automatic video dubbing while preserving the original voice",
          "API with under 500ms latency for real-time applications",
          "Free plan available — 10,000 characters/month"
        ]},
      ],
      quiz: [
        { question: "How much recording time is needed for ElevenLabs Instant Voice Cloning?", options: ["10 seconds", "1 minute", "10 minutes", "1 hour"], correctIndex: 1, explanation: "ElevenLabs Instant Voice Cloning requires just 1 minute of clean audio recording to create a good-quality voice clone." },
        { question: "How many languages does ElevenLabs support in 2026?", options: ["8 languages", "15 languages", "32 languages", "100 languages"], correctIndex: 2, explanation: "ElevenLabs supports over 32 languages in 2026, with localized voices that match the accents and intonations of each language." },
        { question: "What does the ElevenLabs Dubbing feature do?", options: ["It creates an audio version of a text", "It translates and dubs a video into another language", "It removes background noise", "It improves the audio quality of a recording"], correctIndex: 1, explanation: "Dubbing automatically translates and dubs a video into another language while preserving the original speaker's voice and adding approximate lip sync." },
        { question: "What is the latency of the ElevenLabs API for real-time applications?", options: ["Under 50ms", "Under 500ms", "About 2 seconds", "More than 5 seconds"], correctIndex: 1, explanation: "The ElevenLabs API offers latency under 500ms, making it usable for real-time applications like voice AI agents or phone assistants." },
      ],
    },
    {
      number: 11,
      title: "Suno and Udio — Creating Music with AI",
      description: "Music prompt techniques, styles, customization, and the limitations of AI music tools.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "The AI music revolution: Suno and Udio" },
        { type: "paragraph", content: "In 2025-2026, Suno and Udio made music creation accessible to everyone. These tools generate complete songs — melody, arrangements, vocals, lyrics — in seconds from a simple text description. The results are often of surprisingly professional quality." },
        { type: "subheading", content: "Suno — Simplicity in the service of creativity" },
        { type: "paragraph", content: "Suno V4 is the current version, with remarkable audio quality and a wide variety of styles. Its interface is very simple: describe your song in a few words or choose from predefined styles. Advanced options: Custom mode to write your own lyrics, Instrumental mode for voice-free music." },
        { type: "subheading", content: "Writing a good music prompt for Suno" },
        { type: "paragraph", content: "Structure of an effective prompt: musical style + mood + instruments + tempo + optional lyric theme. Example: 'upbeat french pop song, acoustic guitar and piano, 120 BPM, about falling in love in Paris, female vocals, sunny afternoon feel'. The more precise your description, the closer the result will match your vision." },
        { type: "subheading", content: "Udio — Audiophile quality" },
        { type: "paragraph", content: "Udio stands out for superior audio quality compared to Suno in certain genres, especially jazz, classical music, and alternative rock. Its interface allows finer control over song structure (intro, verse, chorus, bridge, outro) and editing of generated lyrics." },
        { type: "subheading", content: "Limitations and rights" },
        { type: "paragraph", content: "The question of rights is still evolving. Suno and Udio claim rights over creations generated on their platforms. For commercial use, check each tool's terms and prefer paid plans, which generally include commercial rights." },
        { type: "tip", content: "Use Suno for speed and style variety. Use Udio for genres requiring greater musical sophistication (jazz, classical). Combine both: generate a base with Suno and refine it with Udio." },
        { type: "summary", items: [
          "Suno and Udio generate complete songs in seconds from a text description",
          "A good music prompt specifies: style, mood, instruments, tempo",
          "Suno excels through its simplicity and style variety",
          "Udio offers audiophile quality for jazz, classical, and alternative rock",
          "Check commercial rights according to your chosen plan"
        ]},
      ],
      quiz: [
        { question: "What is the structure of a good music prompt for Suno?", options: ["Just the song title", "Style + mood + instruments + tempo + theme", "A full poem", "The sheet music"], correctIndex: 1, explanation: "An effective music prompt combines: musical style, mood, instruments, tempo, and optionally the lyric theme to precisely guide the generation." },
        { question: "For which musical genre is Udio particularly recognized?", options: ["Pop and electronic", "Jazz, classical music, and alternative rock", "Video game music", "Hip-hop and rap"], correctIndex: 1, explanation: "Udio stands out for its superior quality in complex musical genres like jazz, classical music, and alternative rock." },
        { question: "What does 'Custom' mode in Suno mean?", options: ["Generate personalized music automatically", "Write and use your own lyrics", "Choose the musician who plays the instruments", "Export in a custom format"], correctIndex: 1, explanation: "Suno's Custom mode lets you write and use your own lyrics instead of having the AI generate them automatically." },
        { question: "What precaution should you take for commercial use of AI-generated music?", options: ["No precautions needed", "Check each tool's terms and use a paid plan", "Mention that it's AI in the description", "Register the song with a performing rights organization"], correctIndex: 1, explanation: "For commercial use, you must check each tool's license terms. Paid plans generally include commercial rights, unlike free plans." },
      ],
    },
    {
      number: 12,
      title: "GitHub Copilot and Cursor — Coding with AI",
      description: "Autocomplete, Agent Mode, comparison, and best practices for coding with AI.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "AI has transformed programming" },
        { type: "paragraph", content: "In 2026, developers who don't use AI for coding have become a minority. Studies show that AI assistants increase developer productivity by 30 to 55% depending on the task. GitHub Copilot and Cursor are the two dominant tools." },
        { type: "subheading", content: "GitHub Copilot — The Microsoft/OpenAI assistant" },
        { type: "paragraph", content: "GitHub Copilot integrates into VS Code, JetBrains, Neovim, and other editors. It offers real-time code completion, contextual chat (Copilot Chat), and since 2025, an Agent Mode that can implement complete features from a description. Price: $10/month or $19/month for advanced features." },
        { type: "subheading", content: "Cursor — The code editor built for AI" },
        { type: "paragraph", content: "Cursor is a VS Code fork entirely redesigned for AI. It integrates Claude 4.6, GPT-5.4, and its own models. Its unique features: Composer (modify multiple files simultaneously), Tab (multi-line predictive autocompletion), and Agent (execute complex tasks autonomously). It is the preferred tool of advanced developers." },
        { type: "subheading", content: "Cursor Agent — Autonomous programming" },
        { type: "paragraph", content: "The Cursor Agent can: read and write files, execute terminal commands, automatically debug errors, install dependencies, and refactor large codebases. Describe a feature in natural language and the Agent handles everything, even across multiple files." },
        { type: "subheading", content: "Best practices" },
        { type: "paragraph", content: "To maximize the quality of generated code: provide clear context (describe the existing architecture), be specific in your requests, always review the generated code before committing, and use project rules (.cursorrules) to enforce your coding style." },
        { type: "key-point", content: "Golden rule: AI generates the code, you understand and validate it. Never commit code you don't understand. AI makes subtle mistakes — stay the pilot, AI is your co-pilot." },
        { type: "summary", items: [
          "AI increases developer productivity by 30 to 55%",
          "GitHub Copilot: integrates into existing editors, $10/month",
          "Cursor: editor redesigned for AI with autonomous multi-file Agent",
          "Cursor Agent can autonomously read, write, debug, and refactor",
          "Always validate generated code — AI makes subtle mistakes"
        ]},
      ],
      quiz: [
        { question: "By how much does AI increase developer productivity?", options: ["5 to 10%", "15 to 20%", "30 to 55%", "80 to 100%"], correctIndex: 2, explanation: "Studies show AI assistants increase developer productivity by 30 to 55% depending on the task, with greater gains on repetitive tasks." },
        { question: "What is the main difference between GitHub Copilot and Cursor?", options: ["Cursor is free, Copilot is paid", "Cursor is an editor redesigned for AI, Copilot is an extension", "Copilot supports more languages", "Cursor requires more RAM"], correctIndex: 1, explanation: "Cursor is a code editor entirely redesigned around AI (a VS Code fork), whereas GitHub Copilot is an extension that integrates into existing editors." },
        { question: "What can the Cursor Agent do autonomously?", options: ["Only complete lines of code", "Read, write, debug, and refactor across multiple files", "Generate images for the README", "Automatically deploy to production"], correctIndex: 1, explanation: "The Cursor Agent can handle complex tasks autonomously: read and write files, execute terminal commands, debug and refactor across multiple files simultaneously." },
        { question: "What is the golden rule when using AI for coding?", options: ["Trust the generated code 100%", "Never modify the generated code", "Always validate the generated code that you understand", "Only use it for small projects"], correctIndex: 2, explanation: "The golden rule is to always validate generated code and only commit code you understand. AI makes subtle mistakes — you remain the responsible pilot." },
      ],
    },
    {
      number: 13,
      title: "Perplexity AI — Search Reinvented",
      description: "Perplexity vs Google, Spaces, API, Deep Research, and advanced use cases.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Perplexity: where search meets AI" },
        { type: "paragraph", content: "Perplexity AI combines real-time web search with the power of LLMs to deliver sourced, precise, and up-to-date answers. Unlike ChatGPT, which can hallucinate about recent facts, Perplexity always cites its sources and accesses the web live." },
        { type: "subheading", content: "Perplexity vs Google — When to use which?" },
        { type: "paragraph", content: "Use Google for: finding a specific website, buying a product, local navigation, searching for images. Use Perplexity for: understanding a complex topic, getting a sourced summary, comparing options, quick academic research, or anything requiring synthesis rather than a list of links." },
        { type: "subheading", content: "Spaces — Your AI knowledge base" },
        { type: "paragraph", content: "Spaces let you create themed research areas with predefined sources. Example: a 'Competitive Intelligence' Space with your competitors' websites, or a 'Tech News' Space with TechCrunch, The Verge, and Wired. Perplexity will prioritize searching within those sources." },
        { type: "subheading", content: "Deep Research — Automatic in-depth analysis" },
        { type: "paragraph", content: "Deep Research is the premium feature that generates thorough research reports in 5 to 10 minutes. Perplexity conducts dozens of searches, synthesizes the results, identifies consensus and disagreements, and produces a structured report with all sources — comparable to 2-3 hours of manual research." },
        { type: "subheading", content: "The Perplexity API — Web search in your applications" },
        { type: "paragraph", content: "The Perplexity API lets you add real-time web search to any application. Particularly useful for AI agents that need up-to-date information, customer support chatbots, and automated monitoring tools." },
        { type: "tip", content: "Use Perplexity Pro ($20/month) to access the most powerful models (Claude 4.6, GPT-5.4) and the Deep Research feature. The free plan is already very capable for regular use." },
        { type: "summary", items: [
          "Perplexity combines real-time web search and AI synthesis with sources",
          "Ideal for understanding complex topics and getting sourced summaries",
          "Spaces create themed knowledge bases with predefined sources",
          "Deep Research generates in-depth reports in 5-10 minutes",
          "The API lets you integrate web search into your own applications"
        ]},
      ],
      quiz: [
        { question: "What is the main difference between Perplexity and ChatGPT?", options: ["Perplexity is free, ChatGPT is paid", "Perplexity always cites its sources and accesses the web in real time", "Perplexity generates images, ChatGPT does not", "ChatGPT is faster than Perplexity"], correctIndex: 1, explanation: "The key difference is that Perplexity accesses the web in real time and always cites its sources, avoiding hallucinations about recent information." },
        { question: "For which task is Perplexity preferable to Google?", options: ["Finding a specific website", "Buying a product online", "Understanding a complex topic with a sourced summary", "Searching for images"], correctIndex: 2, explanation: "Perplexity is preferable to Google for understanding a complex topic, as it produces a structured synthesis with sources rather than a list of links to browse." },
        { question: "How long does the Deep Research feature take?", options: ["30 seconds", "5 to 10 minutes", "1 hour", "24 hours"], correctIndex: 1, explanation: "Deep Research takes 5 to 10 minutes to generate a thorough research report, equivalent to 2-3 hours of manual research." },
        { question: "What are Spaces in Perplexity used for?", options: ["Storing files in the cloud", "Creating themed research areas with predefined sources", "Organizing conversations by date", "Sharing research with a team"], correctIndex: 1, explanation: "Spaces let you create themed research areas where Perplexity will prioritize the sources you have predefined." },
      ],
    },
    {
      number: 14,
      title: "NotebookLM — Analyze Your Documents with AI",
      description: "PDF import, automatic podcast generation, Q&A, and document organization.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "NotebookLM: your personal research assistant" },
        { type: "paragraph", content: "NotebookLM by Google is a unique tool that transforms your documents into an interactive knowledge base. Unlike other LLMs, it answers only based on your documents, eliminating hallucinations. It can analyze up to 50 sources simultaneously." },
        { type: "subheading", content: "Importing your sources" },
        { type: "paragraph", content: "NotebookLM accepts: PDFs, Google Docs, Google Slides, websites (URLs), text files, and even YouTube videos. You can combine different types of sources in the same notebook. Current limits: 500,000 words per source and 50 sources per notebook." },
        { type: "subheading", content: "Audio Overview — The automatic podcast" },
        { type: "paragraph", content: "The most impressive feature: Audio Overview automatically generates a 10-20 minute podcast about the content of your documents. Two natural voices (male and female) discuss the key points in a conversational way. Perfect for absorbing long content during your commute or workout." },
        { type: "subheading", content: "Contextual questions and answers" },
        { type: "paragraph", content: "Ask any question about your documents and NotebookLM answers with precise citations. It pinpoints exactly which document and page the information comes from. Ideal for: analyzing business reports, studying for exams, researching legal information, or synthesizing scientific studies." },
        { type: "subheading", content: "Automatic study guides" },
        { type: "paragraph", content: "NotebookLM automatically generates summaries, outlines, glossaries, exam questions, and study cards from your documents. With one click, transform a 200-page course into a 2-page cheat sheet or 20 quiz questions." },
        { type: "callout", content: "NotebookLM is completely free in its current version. It is the most underrated tool of 2026 — absolutely essential for students, researchers, lawyers, and anyone who works with large volumes of documents." },
        { type: "summary", items: [
          "Analyzes up to 50 sources simultaneously without hallucinations",
          "Accepts PDFs, Docs, Slides, URLs, text, and YouTube videos",
          "Audio Overview generates a 10-20 minute podcast from your documents",
          "Answers include precise citations with page numbers",
          "Automatically generates summaries, study cards, glossaries, and quiz questions"
        ]},
      ],
      quiz: [
        { question: "What is the key difference between NotebookLM and other LLMs?", options: ["It's faster", "It answers only based on your uploaded documents", "It generates images", "It supports more languages"], correctIndex: 1, explanation: "NotebookLM answers exclusively based on the documents you have uploaded, eliminating hallucinations and ensuring all answers are traceable to your sources." },
        { question: "How many sources can NotebookLM analyze simultaneously?", options: ["5 sources", "20 sources", "50 sources", "200 sources"], correctIndex: 2, explanation: "NotebookLM can analyze up to 50 sources simultaneously in a single notebook, covering PDFs, Docs, Slides, URLs, and YouTube videos." },
        { question: "What does the Audio Overview feature generate?", options: ["A list of keywords", "A bullet-point summary", "A 10-20 minute podcast on the content", "A PowerPoint presentation"], correctIndex: 2, explanation: "Audio Overview automatically generates a 10 to 20 minute podcast with two natural voices discussing the key points of your documents in a conversational way." },
        { question: "How much does NotebookLM cost?", options: ["$19/month", "$9.99/month", "Freemium (advanced paid version)", "Completely free"], correctIndex: 3, explanation: "NotebookLM is completely free in its current version, making it the most accessible and underrated AI tool for document analysis." },
      ],
    },
    {
      number: 15,
      title: "Make and Zapier — Automate Without Coding",
      description: "Build AI automation workflows with Make and Zapier, with concrete examples.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "No-code automation: connecting your AI tools" },
        { type: "paragraph", content: "Make (formerly Integromat) and Zapier are the most popular no-code automation platforms. They connect hundreds of applications together and allow AI tools to be integrated throughout. In 2026, they have become the backbone of AI in professional workflows." },
        { type: "subheading", content: "Make — Visual power" },
        { type: "paragraph", content: "Make offers a visual interface in the form of scenarios with connected modules. It is more powerful and flexible than Zapier for complex workflows with multiple conditions, loops, and data transformations. Ideal for advanced automations. Free plan: 1,000 operations/month." },
        { type: "subheading", content: "Zapier — Simplicity first" },
        { type: "paragraph", content: "Zapier is easier to get started with, featuring a linear Trigger > Action interface. It supports over 6,000 applications. Its AI by Zapier feature lets you build workflows in natural language. Ideal for beginners and simple automations. Free plan: 100 tasks/month." },
        { type: "subheading", content: "Popular AI automation examples" },
        { type: "paragraph", content: "1. Incoming email → ChatGPT summarizes and categorizes → Notion. 2. New CRM lead → Claude writes a personalized email → automatic send. 3. Published post → GPT translates → automatic publication in 3 languages. 4. Invoice received → data extraction → Google Sheets. 5. Social media mention → sentiment analysis → Slack alert." },
        { type: "subheading", content: "Integrating AI APIs into Make/Zapier" },
        { type: "paragraph", content: "Both Make and Zapier offer native modules for OpenAI (GPT-5.4), Anthropic (Claude), Google AI (Gemini), ElevenLabs, and Midjourney. You can call these APIs directly in your workflows without any programming knowledge." },
        { type: "tip", content: "Start by automating just one repetitive task you do every day. Even a simple automation that saves 15 minutes per day adds up to over 90 hours per year." },
        { type: "summary", items: [
          "Make and Zapier connect hundreds of applications without code",
          "Make: more powerful for complex workflows with conditions and loops",
          "Zapier: simpler, ideal for beginners and linear automations",
          "Both natively integrate GPT-5.4, Claude, Gemini, and ElevenLabs",
          "15 minutes automated per day = 90+ hours saved per year"
        ]},
      ],
      quiz: [
        { question: "What is the main difference between Make and Zapier?", options: ["Make is free, Zapier is paid", "Make is more powerful for complex workflows, Zapier is simpler", "Zapier supports AI, Make does not", "They are identical"], correctIndex: 1, explanation: "Make is more powerful and flexible for complex workflows with conditions and loops, while Zapier is easier to get started with for linear automations." },
        { question: "How many operations does Make's free plan offer per month?", options: ["100 operations", "500 operations", "1,000 operations", "5,000 operations"], correctIndex: 2, explanation: "Make's free plan offers 1,000 operations per month, which is enough to start automating your first workflows." },
        { question: "Which automation example combines email and AI?", options: ["Converting a PDF to Word", "Incoming email → ChatGPT summarizes → Notion", "Sending emails to all contacts", "Automatically blocking spam"], correctIndex: 1, explanation: "A common example: an incoming email triggers analysis by ChatGPT (summarization and classification), and the result is automatically saved to Notion." },
        { question: "How many hours per year does 15 minutes automated per day represent?", options: ["30 hours", "60 hours", "90 hours", "180 hours"], correctIndex: 2, explanation: "15 minutes per day x 365 days = 5,475 minutes, which is over 90 hours per year. Even a small daily automation has a significant annual impact." },
      ],
    },
    {
      number: 16,
      title: "AI APIs — Accessing Raw Power",
      description: "OpenAI, Anthropic, Google: authentication, pricing, and first API call examples.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Why use AI APIs directly?" },
        { type: "paragraph", content: "Web interfaces like ChatGPT and Claude.ai are convenient, but APIs offer total flexibility: integration into your own applications, large-scale automation, precise control over parameters, and often lower costs for intensive usage." },
        { type: "subheading", content: "The OpenAI API — GPT-5.4 and DALL-E" },
        { type: "paragraph", content: "The OpenAI API provides access to GPT-5.4, DALL-E 3, Whisper (transcription), and TTS (text-to-speech). The API key is generated at platform.openai.com. Usage-based pricing: GPT-5.4 costs approximately $15 per 1 million input tokens and $75 per 1 million output tokens." },
        { type: "subheading", content: "The Anthropic API — Claude 4.6" },
        { type: "paragraph", content: "The Anthropic API provides access to Claude Opus 4.6, Sonnet 4.6, and Haiku 4.5. It is recognized for its stability and precision. Claude Opus 4.6 costs $15 per 1M input tokens and $75 per 1M output tokens. Claude Haiku 4.5 is much cheaper for large-scale use." },
        { type: "subheading", content: "The Google AI API — Gemini 3.1" },
        { type: "paragraph", content: "The Google AI API (via Google AI Studio or Vertex AI) provides access to Gemini 3.1. It offers a generous free plan (1,500 requests/day for Gemini 1.5 Flash) and competitive pricing. Particularly attractive for multimodal applications and large-scale usage." },
        { type: "subheading", content: "Structure of a basic API call" },
        { type: "paragraph", content: "An AI API call always contains: the authentication key (Bearer token), the chosen model, the message(s) (system + user), and optional parameters (temperature, max_tokens). The response is in JSON. SDKs are available for Python, JavaScript, and most programming languages." },
        { type: "key-point", content: "Absolute security: NEVER put your API key in public code (GitHub, etc.). Use environment variables (.env) and add .env to your .gitignore. An exposed key can generate enormous costs." },
        { type: "summary", items: [
          "APIs offer more flexibility and control than web interfaces",
          "OpenAI API: GPT-5.4, DALL-E 3, Whisper, TTS — usage-based billing",
          "Anthropic API: Claude Opus/Sonnet/Haiku — stable and precise",
          "Google AI API: Gemini 3.1 with generous free plan (1,500 req/day)",
          "Security: always use environment variables for API keys"
        ]},
      ],
      quiz: [
        { question: "What is the main advantage of using an AI API over a web interface?", options: ["It's faster to use", "Total flexibility and integration into your own applications", "The models are higher quality", "It's always free"], correctIndex: 1, explanation: "APIs offer total flexibility: integration into your own applications, large-scale automation, precise parameter control, and costs tailored to your usage." },
        { question: "How do you secure your API key in a code project?", options: ["Write it directly in the code", "Share it in code comments", "Use environment variables (.env)", "Send it by email"], correctIndex: 2, explanation: "API keys must be stored in environment variables (.env) and never committed to Git. A publicly exposed key can generate enormous costs." },
        { question: "What free plan does the Google AI API offer?", options: ["No free plan", "50 requests/day", "1,500 requests/day for Gemini Flash", "10 requests/hour"], correctIndex: 2, explanation: "The Google AI API offers a generous free plan with up to 1,500 requests per day for Gemini Flash models, ideal for testing and development." },
        { question: "What elements does an AI API call always contain?", options: ["Only the message text", "Authentication key, model, messages, and optional parameters", "The user's IP address", "The browser used"], correctIndex: 1, explanation: "An AI API call always contains: the authentication key, the chosen model, the messages (system and user), and optional parameters such as temperature." },
      ],
    },
    {
      number: 17,
      title: "Building Your Personal AI Workflow",
      description: "Productivity audit, choosing your AI stack, and step-by-step implementation.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "Your personal AI stack: the key to productivity" },
        { type: "paragraph", content: "An effective personal AI workflow isn't built on a dozen half-used tools — it's built on 3 to 5 tools mastered in depth and well integrated with each other. The goal is to save 2 to 3 hours per day on repetitive tasks, freeing you to focus on high-value work." },
        { type: "subheading", content: "Step 1: Audit your current time" },
        { type: "paragraph", content: "For 3 days, log every task you do and how long it takes. Identify repetitive tasks, tasks that require little creativity but lots of time, and tasks that could be delegated to AI. In general, 40 to 60% of intellectual tasks can be significantly accelerated by AI." },
        { type: "subheading", content: "Step 2: Choose your primary LLM" },
        { type: "paragraph", content: "If you mostly work with text (writing, analysis, emails): Claude 4.6. If you need real-time web research: Perplexity. If you're in the Google ecosystem: Gemini. If you write code: Cursor with Claude. If you need a versatile, accessible tool: ChatGPT." },
        { type: "subheading", content: "Step 3: Identify your specialized tools" },
        { type: "paragraph", content: "Based on your field: creative (Midjourney, ElevenLabs, Suno), developer (Cursor, GitHub Copilot, Claude Code), marketer (ChatGPT, Canva AI, Perplexity), entrepreneur (ChatGPT, Make/Zapier, NotebookLM), researcher (NotebookLM, Perplexity Deep Research, Claude)." },
        { type: "subheading", content: "Step 4: Create your prompt templates" },
        { type: "paragraph", content: "For each recurring task, create a reusable prompt template. Store them in Notion, Obsidian, or a simple text file. Examples: a template for writing client emails, one for analyzing documents, one for generating content ideas. These templates improve over time." },
        { type: "tip", content: "Start by automating just 3 tasks during the first 2 weeks. Mastering 3 tools thoroughly is worth more than skimming 15 tools. Depth before breadth." },
        { type: "summary", items: [
          "A good AI workflow = 3 to 5 tools mastered in depth",
          "Step 1: audit your time to identify automatable tasks",
          "Step 2: choose your primary LLM based on your use case",
          "Step 3: select 1 to 2 specialized tools for your field",
          "Step 4: create prompt templates for your recurring tasks"
        ]},
      ],
      quiz: [
        { question: "How many tools should an effective AI workflow include?", options: ["Just 1 tool", "3 to 5 tools mastered in depth", "10 to 15 varied tools", "Every available tool"], correctIndex: 1, explanation: "An effective AI workflow relies on 3 to 5 tools mastered in depth rather than a dozen tools used superficially." },
        { question: "What percentage of intellectual tasks can be accelerated by AI?", options: ["5 to 10%", "15 to 25%", "40 to 60%", "100%"], correctIndex: 2, explanation: "In general, 40 to 60% of everyday intellectual tasks (writing, analysis, research, summarization) can be significantly accelerated with the right AI tools." },
        { question: "What are prompt templates?", options: ["Images generated by AI", "Reusable prompts for recurring tasks", "Subscriptions to AI tools", "Website templates"], correctIndex: 1, explanation: "Prompt templates are reusable prompts created for your recurring tasks (emails, analyses, ideas) that improve with experience." },
        { question: "Which LLM is recommended if you primarily work on writing and analysis?", options: ["ChatGPT", "Perplexity", "Claude 4.6", "Gemini"], correctIndex: 2, explanation: "Claude 4.6 is particularly recommended for writing and analysis tasks due to its precision, nuance, and ability to follow complex instructions." },
      ],
    },
    {
      number: 18,
      title: "Final Comparison and 2026 Trends",
      description: "Comparison table of all tools, recommended use cases, and upcoming trends.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Recap: which tool for which need?" },
        { type: "paragraph", content: "Having explored 18 categories of tools, here is the quick reference guide for choosing the right tool for your need. These recommendations are based on the state of the art as of March 2026." },
        { type: "subheading", content: "Chatbots and text" },
        { type: "paragraph", content: "Nuanced writing and analysis: Claude 4.6. Versatility and Computer Use: ChatGPT GPT-5.4. Research with sources: Perplexity. Google integration: Gemini 3.1. Code: Cursor + Claude. Long documents: NotebookLM." },
        { type: "subheading", content: "Images and visual creation" },
        { type: "paragraph", content: "Maximum artistic quality: Midjourney V8. Text in images: DALL-E 3. Safe commercial use: Adobe Firefly. Typography: Ideogram. Free total control: Stable Diffusion." },
        { type: "subheading", content: "Video and audio" },
        { type: "paragraph", content: "Photorealistic video: Sora 2. Cinematic: Runway Gen-3. Human motion: Kling AI. Creative effects: Pika 2.0. Professional voice: ElevenLabs. Full music: Suno V4 or Udio." },
        { type: "subheading", content: "Trends to watch in 2026-2027" },
        { type: "paragraph", content: "Autonomous AI agents: tools that perform complex tasks autonomously are set to explode. Local models: increasingly powerful models running on your own computer. Native multimodal AI: all models will process text, image, audio, and video simultaneously. Personalization: AIs learn your style and adapt to you." },
        { type: "key-point", content: "AI is not a static tool — it evolves every month. The most worthwhile investment is learning how to learn: how to quickly test a new tool, evaluate its value, and integrate it into your existing workflow." },
        { type: "summary", items: [
          "Claude 4.6 for writing, ChatGPT for versatility, Perplexity for research",
          "Midjourney V8 for artistic images, DALL-E 3 for text in images",
          "Sora 2 for photorealistic video, ElevenLabs for professional voice",
          "Autonomous AI agents are the dominant trend of 2026-2027",
          "Learning how to quickly adopt new tools is the key skill"
        ]},
      ],
      quiz: [
        { question: "Which tool is recommended for generating images containing precise text?", options: ["Midjourney V8", "Stable Diffusion", "DALL-E 3", "Adobe Firefly"], correctIndex: 2, explanation: "DALL-E 3 is the best tool for generating images containing precise, readable text, outperforming Midjourney in this specialty." },
        { question: "What is the dominant AI trend in 2026-2027?", options: ["Simpler chatbots", "Autonomous AI agents", "Voice recognition", "Automatic translation"], correctIndex: 1, explanation: "Autonomous AI agents — capable of performing complex tasks without human intervention — are the dominant trend of 2026-2027." },
        { question: "For commercial use of AI-generated images, which tool offers the safest legal coverage?", options: ["Midjourney", "Stable Diffusion", "DALL-E 3", "Adobe Firefly"], correctIndex: 3, explanation: "Adobe Firefly is trained exclusively on commercially safe content, offering the best legal coverage for professional commercial use." },
        { question: "What is the key skill for succeeding in the AI era?", options: ["Learning to code in Python", "Memorizing every feature of every tool", "Learning to quickly test and integrate new tools", "Buying every AI subscription"], correctIndex: 2, explanation: "The key skill is learning how to learn quickly: knowing how to test a new tool, evaluate its value, and effectively integrate it into your existing workflow." },
      ],
    },
  ],
};

export default content;
