import type { CourseContent } from "../../types";

const content: CourseContent = {
  slug: "prompt-engineering-pro",
  chapters: [
    {
      number: 1,
      title: "What Is Prompt Engineering?",
      description: "Definition, importance in 2026, and why it's the most in-demand skill on the market.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Prompt engineering: the art of talking to AI" },
        { type: "paragraph", content: "Prompt engineering is the art of crafting precise instructions to get the best possible responses from an AI model. It's the difference between getting a generic answer and getting exactly what you need on the first try." },
        { type: "paragraph", content: "In 2026, prompt engineering has become one of the most sought-after skills in the job market. Companies like Google, Microsoft, and Anthropic are hiring 'Prompt Engineers' at salaries ranging from $100,000 to $300,000 per year." },
        { type: "subheading", content: "Why most people get poor results" },
        { type: "paragraph", content: "The majority of AI users ask vague, imprecise questions and then complain that the AI doesn't understand them. In reality, the AI always produces a response consistent with the instruction it received. If the instruction is vague, the response will be vague. If the instruction is precise and well-structured, the response will be precise and useful." },
        { type: "callout", content: "Concrete example: 'Write an email' produces a mediocre result. 'Write a professional follow-up email to a client for an unpaid invoice of $3,000, firm but courteous tone, 150 words maximum, with a compelling subject line' produces a directly usable result." },
        { type: "key-point", content: "A good prompt = context + role + precise instruction + desired output format. These 4 elements are enough to radically transform the quality of your interactions with AI." },
        { type: "summary", items: [
          "Prompt engineering is the art of crafting precise instructions for AI",
          "It's one of the most in-demand and highest-paying skills of 2026",
          "Vague instructions produce vague responses — the responsibility lies with the human",
          "A good prompt = context + role + precise instruction + desired format",
          "Mastering prompting multiplies your AI productivity by 3 to 10 times",
        ]},
      ],
      quiz: [
        { question: "What is the main reason people get poor results with AI?", options: ["The AI is not smart enough", "Their prompts are vague and imprecise", "They are using the wrong tool", "The models have bugs"], correctIndex: 1, explanation: "The main cause of poor results is vague prompt wording. The AI always produces a response consistent with the instruction it received — a fuzzy instruction generates a fuzzy response." },
        { question: "What are the 4 elements of a good prompt?", options: ["Title, body, signature, conclusion", "Context, role, precise instruction, desired format", "Question, examples, constraints, style", "Subject, verb, object, punctuation"], correctIndex: 1, explanation: "A good prompt contains: context (the situation), role (who the AI should be), precise instruction (what it should do), and desired format (length, structure)." },
        { question: "What salary can a senior Prompt Engineer expect in 2026?", options: ["$30,000 to $50,000", "$50,000 to $80,000", "$100,000 to $300,000", "At least $500,000"], correctIndex: 2, explanation: "In 2026, senior Prompt Engineers at major tech companies earn between $100,000 and $300,000 per year, reflecting the strategic importance of this skill." },
        { question: "By how much does mastered prompting multiply AI productivity?", options: ["By 1.5 times", "By 3 to 10 times", "By 100 times", "It makes no difference"], correctIndex: 1, explanation: "Mastering prompting multiplies AI productivity by 3 to 10 times depending on the task, by obtaining directly usable results rather than responses that need reworking." },
      ],
    },
    {
      number: 2,
      title: "Tokenization — How AI Reads Your Text",
      description: "Understanding tokens, their impact on the quality and cost of interactions.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Tokens: the basic unit of LLMs" },
        { type: "paragraph", content: "LLMs don't read words the way humans do. They split text into 'tokens' — fragments that can be whole words, parts of words, or punctuation characters. Understanding tokens helps you write better prompts and optimize costs." },
        { type: "subheading", content: "How does tokenization work?" },
        { type: "paragraph", content: "In English, 1 token ≈ 0.75 words. Tokenization efficiency varies slightly by language. Examples: 'intelligence' = 1 token, 'artificial' = 1 token, 'anticonstitutionally' = 4 tokens. Numbers, punctuation, and spaces also have their own tokens." },
        { type: "subheading", content: "The context window — AI's memory" },
        { type: "paragraph", content: "The context window is the maximum number of tokens a model can process in a single conversation. In 2026, the best models reach 1 million tokens (GPT-5.4, Claude 4.6, Gemini 3.1), roughly 750,000 words — the equivalent of several full novels." },
        { type: "subheading", content: "The impact of tokens on cost" },
        { type: "paragraph", content: "When you use an AI API, you pay per token: input tokens (your prompt) and output tokens (the model's response). Output tokens generally cost 3 to 5 times more than input tokens. An efficient prompt achieves the same quality with fewer output tokens." },
        { type: "tip", content: "To count your tokens before sending a prompt: use OpenAI's free Tokenizer at platform.openai.com/tokenizer, or Claude.ai displays the number of tokens used in the conversation." },
        { type: "summary", items: [
          "LLMs split text into tokens, not words",
          "In English: 1 token ≈ 0.75 words",
          "The context window in 2026 reaches 1 million tokens (750,000 words)",
          "Output tokens cost 3 to 5 times more than input tokens via API",
          "Understanding tokens helps optimize costs and prompt quality",
        ]},
      ],
      quiz: [
        { question: "What is a token in the context of LLMs?", options: ["A whole word only", "A text fragment (partial word, whole word, or punctuation)", "A single character", "A complete sentence"], correctIndex: 1, explanation: "A token is a text fragment that can be a whole word, part of a word, or a punctuation mark. It is the basic unit that LLMs use to process text." },
        { question: "How many words does 1 million tokens represent (approximately)?", options: ["100,000 words", "500,000 words", "750,000 words", "2 million words"], correctIndex: 2, explanation: "1 million tokens represents approximately 750,000 words, equivalent to several complete novels. This is the context window of the best models in 2026." },
        { question: "Why do output tokens cost more than input tokens?", options: ["They are longer", "Text generation requires more computation than reading", "It is an arbitrary decision by companies", "They are of higher quality"], correctIndex: 1, explanation: "Text generation (output tokens) requires far more computation than reading the context (input tokens), which explains their 3 to 5 times higher cost." },
        { question: "Which free tool lets you count the tokens in a text?", options: ["Google Translate", "OpenAI's Tokenizer at platform.openai.com", "WordCounter.net", "Grammarly"], correctIndex: 1, explanation: "OpenAI's free Tokenizer, available at platform.openai.com/tokenizer, lets you visualize exactly how a text is split into tokens and count their number." },
      ],
    },
    {
      number: 3,
      title: "Zero-Shot vs Few-Shot Prompting",
      description: "Two fundamental prompting approaches and when to use each one.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "The two main approaches to prompting" },
        { type: "paragraph", content: "Before diving into advanced techniques, it's essential to master the two fundamental approaches: zero-shot prompting (without examples) and few-shot prompting (with examples). The choice between them depends on the complexity of the task and the desired output format." },
        { type: "subheading", content: "Zero-Shot Prompting — Directly, without examples" },
        { type: "paragraph", content: "Zero-shot prompting means giving a direct instruction without providing any examples. The AI relies solely on its training knowledge. Example: 'Translate this text into Spanish: [text]'. This is sufficient for simple, well-defined tasks the AI knows well." },
        { type: "subheading", content: "Few-Shot Prompting — Guide with examples" },
        { type: "paragraph", content: "Few-shot prompting provides 2 to 5 examples before the actual request. The AI understands the pattern you want and applies it to your case. Particularly effective for: classifying data according to your own logic, generating content in a very specific style, transforming data into a precise format." },
        { type: "subheading", content: "Concrete example of few-shot" },
        { type: "paragraph", content: "To classify customer reviews, instead of describing your classification logic, show examples: 'Review: Fast delivery → Positive / Review: Product arrived broken → Negative / Review: Matches the description, nothing more → Neutral. Now classify: [your review]'. The AI learns your logic through examples." },
        { type: "subheading", content: "One-Shot — The middle ground" },
        { type: "paragraph", content: "One-shot prompting uses a single example. It's a good compromise when you want to show the output format without bloating the prompt. Useful for document templates, emails with a particular structure, or responses in a specific style." },
        { type: "tip", content: "Practical rule: always start with zero-shot. If the result doesn't match the desired format or style, move to one-shot (1 example). If still insufficient, use few-shot (2–5 examples)." },
        { type: "summary", items: [
          "Zero-shot: direct instruction without examples — for simple, well-defined tasks",
          "Few-shot: 2 to 5 examples before the request — for specific formats and styles",
          "One-shot: 1 example — a good compromise for templates and particular formats",
          "Few-shot is especially effective for classification and data transformation",
          "Always start with zero-shot and escalate if needed",
        ]},
      ],
      quiz: [
        { question: "What is zero-shot prompting?", options: ["A prompt with no instruction", "A direct instruction without providing any examples", "A prompt with zero words", "A prompt that never works"], correctIndex: 1, explanation: "Zero-shot prompting means giving a direct instruction without providing examples, relying solely on the model's training knowledge." },
        { question: "How many examples does a few-shot prompt contain?", options: ["Exactly 1 example", "2 to 5 examples", "10 to 20 examples", "More than 50 examples"], correctIndex: 1, explanation: "A few-shot prompt generally contains 2 to 5 examples. More examples can improve accuracy but make the prompt heavier and increase costs." },
        { question: "For what type of task is few-shot prompting most effective?", options: ["Simple translation", "Classification using custom logic", "Mathematical calculations", "Text summaries"], correctIndex: 1, explanation: "Few-shot is especially effective for classification using custom logic, because the examples let you demonstrate your own logic that the AI could not have guessed on its own." },
        { question: "What is the practical rule for choosing between zero-shot, one-shot, and few-shot?", options: ["Always use few-shot", "Start with zero-shot and escalate if needed", "Always use more-shot", "Choose randomly"], correctIndex: 1, explanation: "The practical rule is to start with zero-shot (simpler and less costly), then move to one-shot if the format is wrong, and finally to few-shot if the result is still insufficient." },
      ],
    },
    {
      number: 4,
      title: "Chain-of-Thought — Making AI Reason Step by Step",
      description: "The CoT technique for more accurate responses on complex problems.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Chain-of-Thought: the secret to intelligent responses" },
        { type: "paragraph", content: "Chain-of-Thought (CoT) is a prompting technique that pushes the AI to reason explicitly step by step before giving its final answer. Google researchers showed that this technique dramatically improves performance on logic, math, and complex reasoning problems." },
        { type: "subheading", content: "How do you activate Chain-of-Thought?" },
        { type: "paragraph", content: "Simply add to your prompt: 'Think step by step', 'Think out loud before answering', or 'Explain your reasoning'. These simple phrases trigger a more in-depth thinking mode. For GPT-5.4 in Thinking mode and Claude Opus 4.6, this reasoning is automatic and even more thorough." },
        { type: "subheading", content: "CoT example for a logic problem" },
        { type: "paragraph", content: "Without CoT: 'Marie is 3 times Paul's age. In 10 years, Marie will be twice Paul's age. How old is Marie now?' — The AI might get it wrong. With CoT: 'Solve this problem step by step, showing each calculation step: [problem]' — The AI sets up the equations, solves each step, and arrives at the correct answer (30 years old)." },
        { type: "subheading", content: "Zero-Shot CoT — The magic formula" },
        { type: "paragraph", content: "Zero-Shot CoT is an extremely simple approach: just add 'Think step by step' to the end of any prompt. Studies show that this simple phrase improves LLM accuracy by 40 to 80% on complex reasoning problems." },
        { type: "subheading", content: "Auto-CoT — Generating your own steps" },
        { type: "paragraph", content: "Auto-CoT consists of asking the AI to first generate the reasoning steps needed, then follow them. Example: 'What are the steps to solve this problem? Now solve it by following those steps.' This approach is particularly effective for planning problems." },
        { type: "key-point", content: "CoT is not magic for every problem. It is very effective for logic, mathematics, planning, and analysis. For simple creative tasks (writing a poem, summarizing a text), CoT is less necessary." },
        { type: "summary", items: [
          "CoT pushes the AI to reason step by step before answering",
          "Activated with: 'Think step by step' or 'Think out loud'",
          "Improves accuracy by 40 to 80% on reasoning problems",
          "Zero-Shot CoT is the simplest and most effective formula",
          "Especially useful for: logic, math, planning, and analysis",
        ]},
      ],
      quiz: [
        { question: "What is the simplest formula to activate Chain-of-Thought?", options: ["Write the prompt in all caps", "Add 'Think step by step' to the end of the prompt", "Ask several questions in a row", "Use only simple words"], correctIndex: 1, explanation: "The simplest formula is to add 'Think step by step' (or 'Let's think step by step') to the end of your prompt. This simple phrase significantly improves performance." },
        { question: "By how much does CoT improve accuracy on reasoning problems?", options: ["5 to 10%", "15 to 25%", "40 to 80%", "200 to 300%"], correctIndex: 2, explanation: "Studies show that Chain-of-Thought improves LLM accuracy by 40 to 80% on complex reasoning problems (logic, mathematics, planning)." },
        { question: "For what type of task is CoT LEAST useful?", options: ["Math problems", "Formal logic", "Simple creative tasks", "Project planning"], correctIndex: 2, explanation: "CoT is least useful for simple creative tasks (writing a poem, summarizing a short text) where step-by-step reasoning adds little improvement over a direct response." },
        { question: "What is Auto-CoT?", options: ["An automatic CoT without human intervention", "Asking the AI to first generate the steps, then follow them", "A CoT that automatically adapts to the model", "A paid OpenAI tool"], correctIndex: 1, explanation: "Auto-CoT consists of asking the AI to generate the necessary reasoning steps itself, then follow them to solve the problem." },
      ],
    },
    {
      number: 5,
      title: "Tree of Thoughts — Exploring Solutions",
      description: "The advanced technique for complex problems that require exploring multiple paths.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Tree of Thoughts: going beyond linear CoT" },
        { type: "paragraph", content: "Tree of Thoughts (ToT) is an evolution of Chain-of-Thought that allows the AI to explore multiple reasoning paths in parallel, evaluate each branch, and choose the best one. Published by researchers from Princeton and Google in 2023, it is one of the most powerful techniques for complex problems." },
        { type: "subheading", content: "When should you use Tree of Thoughts?" },
        { type: "paragraph", content: "ToT is particularly well-suited to situations where: multiple valid approaches exist, you need to anticipate constraints or obstacles, the optimal solution is not obvious, or intermediate decisions influence future options. Examples: business strategy, puzzle solving, complex project planning." },
        { type: "subheading", content: "How to implement ToT in a prompt" },
        { type: "paragraph", content: "Simplified ToT prompt: 'Imagine 3 different experts thinking about this problem. Each expert proposes a different approach, evaluates the strengths and weaknesses of their approach, then all experts evaluate each other's approaches and converge on the best solution. Problem: [your problem]'" },
        { type: "subheading", content: "Concrete example: choosing a marketing strategy" },
        { type: "paragraph", content: "Without ToT: 'What marketing strategy for my app?' → Generic response. With ToT: 'Imagine 3 experienced marketing strategists. Each proposes and defends a different strategy (growth hacking, content marketing, B2B partnerships), evaluates the risks and ROI of each approach, then selects the best one with justification.' → Structured analysis and informed decision." },
        { type: "callout", content: "ToT is slower and costs more tokens than standard CoT. Reserve it for important decisions that warrant in-depth analysis. For everyday tasks, standard CoT remains more efficient." },
        { type: "summary", items: [
          "ToT explores multiple reasoning paths in parallel before choosing",
          "Ideal for complex problems where multiple valid approaches exist",
          "Implemented with the '3 experts' prompt who debate different approaches",
          "More token-intensive than CoT — reserve it for important decisions",
          "Especially effective for strategy, planning, and complex puzzles",
        ]},
      ],
      quiz: [
        { question: "What is the main difference between CoT and Tree of Thoughts?", options: ["ToT uses more tokens", "ToT explores multiple paths in parallel, CoT follows a linear path", "CoT is more recent than ToT", "They are identical"], correctIndex: 1, explanation: "The main difference is that CoT follows a single linear reasoning path, while ToT explores multiple branches in parallel, evaluates each, and chooses the best." },
        { question: "For what type of problem is ToT particularly well-suited?", options: ["Simple translations", "Text summaries", "Complex problems with multiple valid approaches", "Arithmetic calculations"], correctIndex: 2, explanation: "ToT is particularly well-suited to complex problems where multiple valid approaches exist and where intermediate decisions influence future options (strategy, planning)." },
        { question: "How do you simply implement ToT in a prompt?", options: ["Write 'tree of thoughts' in the prompt", "Ask the AI to think multiple times", "Use the '3 experts' prompt who propose and debate approaches", "Split the problem into 3 separate questions"], correctIndex: 2, explanation: "The simplified ToT prompt asks you to imagine 3 experts with different approaches who evaluate their respective solutions and converge on the best one." },
        { question: "Why should you reserve ToT for important decisions?", options: ["It produces worse results", "It is slower and costs more tokens", "It is only available on ChatGPT Pro", "It requires programming knowledge"], correctIndex: 1, explanation: "ToT is slower and consumes more tokens (and is therefore more expensive via API) than standard CoT. It is therefore best reserved for important decisions that warrant thorough analysis." },
      ],
    },
    {
      number: 6,
      title: "The CRISPE Framework",
      description: "The structured 6-step framework for perfect prompts every time.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "CRISPE: the reference framework for professional prompts" },
        { type: "paragraph", content: "CRISPE is an acronym that structures a complete prompt into 6 components: Context, Role, Instructions, Steps, Parameters, Expected output. It is the most widely taught framework in professional prompt engineering training." },
        { type: "subheading", content: "C — Context" },
        { type: "paragraph", content: "Context places the AI in your situation. The more relevant context you provide, the more tailored the response will be. Example: 'I run a 15-person SMB in the restaurant industry. We launched an online ordering app 6 months ago and are looking to increase customer retention.' All this context guides the AI toward a relevant response." },
        { type: "subheading", content: "R — Role" },
        { type: "paragraph", content: "Assigning a role to the AI activates a different response mode. 'You are a digital marketing expert with 15 years of experience in the restaurant industry' will produce a very different response from 'You are a financial analyst'. The role sets the perspective, vocabulary, and approach of the response." },
        { type: "subheading", content: "I — Instructions" },
        { type: "paragraph", content: "Instructions describe the task precisely. Use clear action verbs: 'Analyze', 'Compare', 'List', 'Write', 'Explain'. Avoid vague wording. Bad: 'Tell me about retention'. Good: 'Propose 5 concrete strategies to increase my customer repurchase rate by 30%'." },
        { type: "subheading", content: "S — Steps" },
        { type: "paragraph", content: "For complex tasks, break them down into sequential steps. 'Proceed in 3 steps: 1. Analyze the weaknesses of my current strategy, 2. Propose improvements, 3. Prioritize these improvements by potential impact.' Steps force the AI to structure its thinking." },
        { type: "subheading", content: "P — Parameters and E — Expected Output" },
        { type: "paragraph", content: "Parameters set the constraints: length (200 words maximum), tone (professional but accessible), format (bullet list or table), language (English only). Expected Output describes the final deliverable: 'An action plan in 5 points, with for each point: the action, the tool needed, the estimated duration, and the success KPI.'" },
        { type: "key-point", content: "You don't have to use all CRISPE elements for every prompt. Adapt according to task complexity. A simple email doesn't need all 6 components, but a strategic analysis will benefit fully from them." },
        { type: "summary", items: [
          "CRISPE = Context, Role, Instructions, Steps, Parameters, Expected Output",
          "Context places the AI in your specific situation",
          "Role activates a response mode tailored to the desired perspective",
          "Steps break complex tasks into logical sequences",
          "Parameters set the constraints (length, tone, format)",
        ]},
      ],
      quiz: [
        { question: "What does the CRISPE acronym stand for?", options: ["Create, Review, Improve, Send, Publish, Evaluate", "Context, Role, Instructions, Steps, Parameters, Expected Output", "Clear, Relevant, Informative, Specific, Precise, Effective", "Creative, Readable, Intelligent, Simple, Practical, Elegant"], correctIndex: 1, explanation: "CRISPE stands for: Context, Role, Instructions, Steps, Parameters, Expected Output. It is a structured framework for creating professional prompts." },
        { question: "What effect does assigning a role to the AI have in a prompt?", options: ["It has no effect", "It activates a different response mode suited to that perspective", "It makes the response longer", "It changes the model being used"], correctIndex: 1, explanation: "Assigning a role to the AI activates a different response mode: vocabulary, perspective, level of expertise, and approach all adapt to the defined role." },
        { question: "Why break a task into steps in a prompt?", options: ["To make the prompt longer", "To force the AI to structure its thinking and produce an organized response", "To save tokens", "To speed up generation"], correctIndex: 1, explanation: "Breaking a task into steps forces the AI to follow a logical sequence, producing a better-structured response and reducing the risk of omissions." },
        { question: "Do you always have to use all 6 CRISPE components?", options: ["Yes, always", "No, adapt according to task complexity", "Yes, otherwise the AI ignores the prompt", "No, only use C and I"], correctIndex: 1, explanation: "CRISPE is a guide, not a requirement. For a simple email, 2–3 components are enough. For a complex strategic analysis, all 6 components add real value." },
      ],
    },
    {
      number: 7,
      title: "Personas and Roles — Giving the AI an Identity",
      description: "Creating effective personas to get expert, teacher, or coach responses.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "The power of personas in prompting" },
        { type: "paragraph", content: "Assigning a persona (an identity) to the AI is one of the most powerful techniques in prompt engineering. By giving it a precise role, you activate a specific set of knowledge, tones, and approaches. The same LLM can behave like a doctor, a lawyer, a sports coach, or a Michelin-starred chef." },
        { type: "subheading", content: "Expert personas — Specialized knowledge" },
        { type: "paragraph", content: "Effective examples: 'You are a general practitioner with 20 years of experience. Explain this symptom in simple terms.' / 'You are a corporate law attorney. Analyze this contractual clause.' / 'You are a senior data scientist at Google. Explain this ML concept to a beginner.' The level of expertise and specialization significantly refines the responses." },
        { type: "subheading", content: "Communication style personas" },
        { type: "paragraph", content: "Beyond expertise, personas can define communication style: 'You are a Socratic professor who only teaches through questions.' / 'You are a blunt, direct coach who doesn't sugarcoat anything.' / 'You are a supportive mentor who encourages without criticizing.' / 'You are a McKinsey consultant who structures everything in bullet points with hard data.'" },
        { type: "subheading", content: "Combining personas and context" },
        { type: "paragraph", content: "The most powerful technique: combining a precise persona with detailed context. 'You are a marketing director with 15 years of experience in B2C e-commerce, specializing in customer retention. You work with SMBs of 5 to 50 employees with limited marketing budgets (under $50,000/year).' This level of precision produces directly applicable advice." },
        { type: "tip", content: "Add boundaries to your persona to prevent drift. Example: 'Always stay within the domain of finance. If I ask about something outside your expertise, say so clearly and redirect to your area of knowledge.' This improves the reliability of responses." },
        { type: "summary", items: [
          "Assigning a persona activates specific knowledge and response styles",
          "Expert personas give access to simulated specialized knowledge",
          "Style personas define how to communicate (Socratic, coach, mentor)",
          "Combining a precise persona with detailed context produces the most relevant results",
          "Add boundaries to the persona to maintain consistency and reliability",
        ]},
      ],
      quiz: [
        { question: "What is the main effect of assigning a persona to the AI?", options: ["It changes the AI model used", "It activates a specific set of knowledge, tone, and approaches", "It makes the response shorter", "It improves generation speed"], correctIndex: 1, explanation: "Assigning a persona activates a specific set of knowledge, communication style, and approaches suited to the defined role, without changing the underlying model." },
        { question: "What is the most powerful persona technique?", options: ["Giving only the job title", "Combining a precise persona with detailed context", "Using the names of famous people", "Changing personas with each question"], correctIndex: 1, explanation: "The most powerful technique is to combine a precise persona (expertise, specialization) with detailed context (industry, type of clients, constraints), producing directly applicable advice." },
        { question: "Why add boundaries to a persona?", options: ["To reduce the length of responses", "To maintain consistency and reliability within the area of expertise", "To save tokens", "To make the AI less creative"], correctIndex: 1, explanation: "Adding boundaries (e.g., 'stay within the finance domain') improves reliability by preventing the AI from straying outside its simulated area of expertise and generating less reliable information." },
        { question: "Which persona should you use to get structured analyses with hard data?", options: ["A Socratic professor", "A supportive coach", "A McKinsey consultant", "A creative artist"], correctIndex: 2, explanation: "The 'McKinsey consultant' persona is ideal for getting structured analyses with bullet points, data, and actionable recommendations, reflecting the culture of that consulting firm." },
      ],
    },
    {
      number: 8,
      title: "System Prompts — Configuring Global Behavior",
      description: "Global instructions, temperature, style, and how to create custom AI assistants.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "System prompts: defining the AI's personality" },
        { type: "paragraph", content: "A system prompt (or system instruction) is a higher-level instruction that defines the AI's overall behavior for an entire conversation. Unlike regular user prompts, the system prompt applies persistently — the AI does not step outside this framework." },
        { type: "subheading", content: "Structure of an effective system prompt" },
        { type: "paragraph", content: "A good system prompt contains: 1. The assistant's identity (who it is, its expertise). 2. Its objectives (what it must accomplish). 3. Its communication style (tone, language level, preferred format). 4. Its constraints (what it must not do). 5. Permanent context information (data about the company, products)." },
        { type: "subheading", content: "Example system prompt for a customer assistant" },
        { type: "paragraph", content: "Example: 'You are Alex, the customer assistant for TechShop, an online computer hardware store. You help customers with questions about products, orders, and returns. Your tone is warm, professional, and concise. You always respond in fewer than 100 words. If a question is outside your scope, direct users to support@techshop.com. You never mention competitors.'" },
        { type: "subheading", content: "Temperature — Controlling creativity" },
        { type: "paragraph", content: "Temperature (0 to 2 in OpenAI) controls the level of creativity and randomness in responses. Temperature 0: very deterministic and predictable responses (ideal for classification, code, facts). Temperature 0.7–1.0: balance of creativity and coherence (ideal for general writing). Temperature 1.5–2.0: very creative and unpredictable (poetry, brainstorming)." },
        { type: "subheading", content: "System prompts in Custom GPTs and Claude Projects" },
        { type: "paragraph", content: "OpenAI's Custom GPTs and Claude's Projects use system prompts to create permanent assistants. You define the behavior, tone, constraints, and context once — and the assistant keeps these settings for all future conversations, without having to repeat them." },
        { type: "key-point", content: "System prompts are the key to creating consistent AI products. Every professional AI application (customer chatbot, internal assistant, content generation tool) uses a carefully written system prompt." },
        { type: "summary", items: [
          "The system prompt defines the AI's global, persistent behavior",
          "It contains: identity, objectives, style, constraints, and permanent context",
          "Temperature controls creativity (0 = deterministic, 2 = highly creative)",
          "Custom GPTs and Claude Projects are built on system prompts",
          "It is the foundation of all professional AI products (chatbots, assistants)",
        ]},
      ],
      quiz: [
        { question: "What is the difference between a system prompt and a user prompt?", options: ["No difference", "The system prompt applies persistently to the entire conversation", "The system prompt is shorter", "The system prompt costs fewer tokens"], correctIndex: 1, explanation: "The system prompt applies persistently to the entire conversation, defining overall behavior. A user prompt is a one-time instruction for a specific response." },
        { question: "What temperature should you use to generate code or classify data?", options: ["Temperature 0 (deterministic)", "Temperature 0.7–1.0", "Temperature 1.5", "Temperature 2.0 (highly creative)"], correctIndex: 0, explanation: "For code and classification, using a temperature close to 0 produces deterministic and predictable responses, reducing errors and unwanted variations." },
        { question: "What elements should a good system prompt contain?", options: ["Only constraints", "Identity, objectives, style, constraints, and permanent context", "Only the persona and language", "A list of all possible questions"], correctIndex: 1, explanation: "An effective system prompt contains: the assistant's identity, its objectives, its communication style, its constraints (what it must not do), and permanent context information." },
        { question: "What are Custom GPTs and Claude Projects used for?", options: ["To create new AI models", "To create custom assistants with permanent system prompts", "To store files in the cloud", "To share conversations publicly"], correctIndex: 1, explanation: "Custom GPTs and Claude Projects use permanent system prompts to create custom assistants that maintain the same behavior, tone, and context across all conversations." },
      ],
    },
    {
      number: 9,
      title: "Meta-Prompting — Prompts That Create Prompts",
      description: "Using AI to automatically optimize and generate your own prompts.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Meta-prompting: letting AI improve your prompts" },
        { type: "paragraph", content: "Meta-prompting consists of using AI to create or improve other prompts. It's a recursive approach where the AI becomes your prompt engineering assistant. The result: more effective prompts, optimized and tailored to your specific use case." },
        { type: "subheading", content: "Technique 1: Ask the AI to improve your prompt" },
        { type: "paragraph", content: "Meta-prompt: 'Here is my prompt: [YOUR PROMPT]. Analyze its weaknesses and propose an improved version that will produce better results. Explain why each improvement is beneficial.' This simple technique can turn a mediocre prompt into a professional one in seconds." },
        { type: "subheading", content: "Technique 2: Generate a prompt from a description" },
        { type: "paragraph", content: "Meta-prompt: 'I want to create a prompt to obtain [DESCRIPTION OF DESIRED RESULT]. Create the optimal prompt for me that uses the best prompt engineering techniques (personas, CoT, structured format) to achieve this goal.' Ideal when you know what you want to get but not how to phrase it." },
        { type: "subheading", content: "Technique 3: Prompt Critic" },
        { type: "paragraph", content: "The Prompt Critic technique consists of asking the AI to evaluate a prompt against specific criteria. Example: 'Rate this prompt from 1 to 10 on the following criteria: clarity, precision, context, output format. For each insufficient criterion, propose a specific improvement.' Excellent for critical prompts before deploying them in production." },
        { type: "subheading", content: "Automating prompt generation" },
        { type: "paragraph", content: "For applications that generate many similar prompts (product description generation, personalized emails, reports), create a 'prompt of prompts' that automatically generates the right prompt for each situation by filling in variables. This is the foundation of RAG (Retrieval-Augmented Generation) systems." },
        { type: "tip", content: "Keep your best meta-prompts in a dedicated library. A good meta-prompt that improves your writing prompts, for example, can be reused hundreds of times and save hours of work." },
        { type: "summary", items: [
          "Meta-prompting uses AI to create and improve other prompts",
          "Technique 1: ask the AI to improve your existing prompt",
          "Technique 2: generate a prompt from a description of the desired result",
          "Technique 3: Prompt Critic to evaluate and rate a prompt against criteria",
          "Keep your best meta-prompts in a reusable library",
        ]},
      ],
      quiz: [
        { question: "What is meta-prompting?", options: ["A very long prompt", "Using AI to create or improve other prompts", "A prompt in multiple languages", "A prompt that generates images"], correctIndex: 1, explanation: "Meta-prompting consists of using AI to create, improve, or evaluate other prompts — a recursive approach where the AI becomes your prompt engineering assistant." },
        { question: "What is the 'Prompt Critic' technique?", options: ["Criticizing AI responses", "Asking the AI to evaluate a prompt against specific criteria", "Using one AI to critique another", "Evaluating the quality of an AI model"], correctIndex: 1, explanation: "Prompt Critic consists of asking the AI to evaluate your prompt against specific criteria (clarity, context, format) and to propose specific improvements for each insufficient criterion." },
        { question: "For what situation is the 'generate a prompt from a description' technique ideal?", options: ["When you already have a good prompt", "When you know the desired result but not how to phrase the prompt", "When you want to save tokens", "When the AI refuses to respond"], correctIndex: 1, explanation: "This technique is ideal when you clearly know what you want to obtain but don't know how to effectively phrase the prompt to get there." },
        { question: "What is a 'prompt of prompts' in automated applications?", options: ["A prompt that repeats itself", "A prompt that automatically generates prompts suited to each situation", "The first prompt in a conversation", "A prompt in a programming language"], correctIndex: 1, explanation: "A 'prompt of prompts' is a template that automatically generates prompts suited to each situation by filling in variables, the foundation of large-scale content generation systems." },
      ],
    },
    {
      number: 10,
      title: "Prompt Chaining — Breaking Down Complex Tasks",
      description: "Prompt sequences, variables, and pipelines for complex AI projects.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Prompt chaining: divide and conquer" },
        { type: "paragraph", content: "Prompt chaining consists of breaking a complex task into a sequence of simpler prompts, where the output of one prompt becomes the input for the next. This technique makes it possible to handle projects of a complexity impossible to manage in a single prompt." },
        { type: "subheading", content: "Why chain prompts?" },
        { type: "paragraph", content: "A single very long and complex prompt often produces poor results because the AI loses track of the multiple instructions. By breaking it down into steps, each step receives the model's full attention. Moreover, you can review and correct each step before moving to the next." },
        { type: "subheading", content: "Example: creating a blog post in 4 steps" },
        { type: "paragraph", content: "Prompt 1: 'Generate 10 original angles for an article on [TOPIC].' → You choose the angle. Prompt 2: 'Create a detailed 5-section outline for an article on [CHOSEN ANGLE].' → You validate the outline. Prompt 3: 'Write section 1 of the following outline: [OUTLINE].' → Repeat for each section. Prompt 4: 'Review and improve the coherence of this article: [FULL ARTICLE].' → Finalized article." },
        { type: "subheading", content: "Variables in prompt chains" },
        { type: "paragraph", content: "Use [bracketed variables] to create reusable chain templates. Example for generating product sheets: Prompt 1: 'Analyze this product and list its 5 key advantages: [RAW PRODUCT DESCRIPTION].' Prompt 2: 'Write a compelling product sheet for [PRODUCT NAME] using these advantages: [ADVANTAGES FROM STEP 1].'" },
        { type: "subheading", content: "Conditional chains" },
        { type: "paragraph", content: "Conditional chains choose the next prompt based on the output of the previous one. Example: Sentiment analysis prompt → If positive, thank-you prompt. If negative, crisis management prompt. If neutral, clarification request prompt. These are at the core of most AI agents." },
        { type: "key-point", content: "Prompt chaining is the foundation of all complex AI systems: agents, automated workflows, large-scale content generation, long document analysis. Mastering this technique allows you to build genuinely powerful AI products." },
        { type: "summary", items: [
          "Chaining breaks a complex task into a sequence of simple prompts",
          "Each output becomes the input for the next prompt",
          "Allows you to review and correct each intermediate step",
          "[Bracketed variables] create reusable chain templates",
          "Conditional chains are the foundation of intelligent AI agents",
        ]},
      ],
      quiz: [
        { question: "Why do chained prompts produce better results than a single long prompt?", options: ["Because short prompts cost less", "Because each step gets the model's full attention and can be reviewed", "Because the AI prefers short prompts", "Because they are easier to write"], correctIndex: 1, explanation: "Chained prompts are more effective because each step receives the model's full attention (without being spread thin), and you can review and correct each intermediate result." },
        { question: "What are [bracketed variables] used for in a prompt chain?", options: ["To bold text", "To create reusable templates with dynamic parts", "To indicate math calculations", "To define hyperlinks"], correctIndex: 1, explanation: "[Bracketed variables] are used to create reusable prompt chain templates where the dynamic parts are replaced by the specific data for each use." },
        { question: "What is a conditional chain in prompt chaining?", options: ["A chain that stops after 3 prompts", "A prompt that adapts based on the previous output", "A very long chain of prompts", "A type of security system"], correctIndex: 1, explanation: "A conditional chain chooses the next prompt based on the previous output (e.g., if positive → prompt A, if negative → prompt B). It is the foundation of intelligent AI agents." },
        { question: "In the 4-step article creation example, what is the 4th step?", options: ["Choose the title", "Create the detailed outline", "Write the sections", "Review and improve the coherence of the full article"], correctIndex: 3, explanation: "The 4th step consists of reviewing the full article and improving its coherence — an essential quality control step to produce a smooth and cohesive article." },
      ],
    },
    {
      number: 11,
      title: "Prompts for Code — Programming with AI",
      description: "Debugging, refactoring, documenting, and generating code with effective prompts.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "AI as a programming partner" },
        { type: "paragraph", content: "In 2026, developers who master code prompting are 30 to 55% more productive. AI can generate code, debug errors, refactor existing codebases, write unit tests, and automatically generate documentation. But the quality of the generated code depends directly on the quality of the prompt." },
        { type: "subheading", content: "Prompt for generating code" },
        { type: "paragraph", content: "Effective template: 'You are a senior [LANGUAGE] developer. Write a function [NAME] that [DESCRIPTION]. Constraints: [PERFORMANCE / SECURITY / COMPATIBILITY]. The code must: be commented, handle error cases, include unit tests. Return only the code, no explanations.' Specifying the language, constraints, and output format is crucial." },
        { type: "subheading", content: "Prompt for debugging" },
        { type: "paragraph", content: "Debugging template: 'Here is [LANGUAGE] code that produces the following error: [ERROR MESSAGE]. Code: [YOUR CODE]. Identify the root cause of the bug, explain why it occurs, and provide the corrected code. If multiple causes are possible, list them all by probability.' Including the exact error message is essential." },
        { type: "subheading", content: "Prompt for refactoring" },
        { type: "paragraph", content: "Refactoring template: 'Refactor this [LANGUAGE] code to: improve readability, reduce cyclomatic complexity, eliminate duplication (DRY principle), and follow best practices for [FRAMEWORK/STYLE]. Preserve exactly the same behavior. Explain each major change.' The key: specify the refactoring goals and the constraint of preserving behavior." },
        { type: "subheading", content: "Prompts for tests and documentation" },
        { type: "paragraph", content: "Tests: 'Write exhaustive unit tests for this function in [TEST FRAMEWORK]. Cover: normal cases, edge cases, error cases, and invalid inputs.' Documentation: 'Generate complete documentation in [FORMAT: JSDoc/Docstring/etc.] for this code. Include: description, parameters, return value, usage examples, and error cases.'" },
        { type: "tip", content: "For large projects, always give the AI the architectural context. Explain: the overall architecture, the framework used, naming conventions, and existing dependencies. The richer the context, the more consistent the generated code will be with your existing codebase." },
        { type: "summary", items: [
          "Always specify the language, constraints, and desired output format",
          "For debugging: include the exact error message and the problematic code",
          "For refactoring: specify the goals and the constraint of preserving behavior",
          "For tests: ask for coverage of normal, edge, and error cases",
          "Provide architectural context for large projects",
        ]},
      ],
      quiz: [
        { question: "What is essential in a debugging prompt?", options: ["The date of the bug", "The exact error message and the problematic code", "The developer's name", "The operating system used"], correctIndex: 1, explanation: "For effective debugging, it is essential to include the exact error message (including the full traceback) and the problematic code so the AI can identify the root cause." },
        { question: "What constraint is essential in a refactoring prompt?", options: ["Improve performance at all costs", "Preserve exactly the same code behavior", "Reduce file size", "Rename all variables"], correctIndex: 1, explanation: "The constraint of preserving exactly the same behavior is essential in a refactoring prompt to prevent the AI from accidentally changing the code's functional logic." },
        { question: "What should you specify in a unit test generation prompt?", options: ["Only normal cases", "Only error cases", "Normal cases, edge cases, error cases, and invalid inputs", "Only the function name"], correctIndex: 2, explanation: "A complete test generation prompt should request coverage of normal cases, edge cases (extreme values), error cases, and invalid inputs for a thorough test suite." },
        { question: "Why give the AI architectural context for large projects?", options: ["To save tokens", "So the generated code is consistent with the existing codebase", "To speed up generation", "To reduce API costs"], correctIndex: 1, explanation: "Providing architectural context (framework, conventions, dependencies) allows the AI to generate code consistent with your existing codebase, reducing conflicts and rework." },
      ],
    },
    {
      number: 12,
      title: "Prompts for Creative Writing",
      description: "Novels, scripts, marketing, SEO — prompting techniques for every type of content.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Creative writing with AI: keeping your voice" },
        { type: "paragraph", content: "AI can generate professional-quality writing, but the risk is ending up with a generic, impersonal style. The best prompting techniques for writing allow the AI to amplify your creativity while preserving your authentic voice." },
        { type: "subheading", content: "Transferring your style to the AI" },
        { type: "paragraph", content: "The most effective technique: provide examples of your own writing. 'Here are 3 paragraphs I wrote: [EXAMPLES]. Analyze my style (sentence structure, vocabulary, tone, punctuation) then write [REQUESTED TEXT] in exactly that same style.' The AI becomes your ghostwriter who adopts your signature." },
        { type: "subheading", content: "Prompts for novels and short stories" },
        { type: "paragraph", content: "For a novel scene: 'Write a [GENRE] scene where [CHARACTER] faces [CONFLICT]. Tone: [ATMOSPHERE]. POV: [POINT OF VIEW]. Style: [REFERENCE AUTHOR]. Length: [X] words. The scene must: establish the emotional stakes, advance the plot, and end on a cliffhanger.' The precision of the parameters is key." },
        { type: "subheading", content: "Prompts for copywriting and marketing" },
        { type: "paragraph", content: "For a landing page: 'Write the main text (hero section) of a landing page for [PRODUCT/SERVICE]. Target: [CUSTOMER PERSONA]. Main benefit: [PROMISE]. Tone: [STYLE]. Length: 50 words maximum. Include: catchy headline (max 8 words), explanatory subtitle (max 20 words), and an irresistible CTA.' Precision about the persona and format constraints is essential." },
        { type: "subheading", content: "Prompts for SEO" },
        { type: "paragraph", content: "For an SEO-optimized article: 'Write a 1,500-word article on [TOPIC] optimized for the keyword [KEYWORD]. Structure: H1 containing the keyword, introduction with the keyword in the first 100 words, 4 H2 subsections, conclusion with CTA. Include the keyword [X] times naturally. Tone: [STYLE]. Audience: [TARGET READER].'" },
        { type: "key-point", content: "AI excels at generating a first draft, not a perfect text. Use it for 80% of the writing work, then refine with your human judgment. The real value is in speed: an article that used to take 4 hours now takes 45 minutes." },
        { type: "summary", items: [
          "Providing examples of your own writing allows the AI to adopt your style",
          "For novels: specify genre, conflict, tone, POV, reference style, and length",
          "For copywriting: specify the persona, main promise, and format constraints",
          "For SEO: indicate H1/H2 structure, keyword frequency, and target length",
          "AI generates the first draft in minutes — refine it with your human judgment",
        ]},
      ],
      quiz: [
        { question: "How do you effectively transfer your writing style to the AI?", options: ["Describe your style in words", "Provide examples of your own writing", "Name a famous author you admire", "Ask the AI to guess your style"], correctIndex: 1, explanation: "The most effective technique is to provide examples of your own writing and ask the AI to analyze then reproduce your style — structure, vocabulary, and tone." },
        { question: "What is AI's ideal role in the creative writing process?", options: ["Write the perfect final text", "Generate 80% of the content to be refined with your human judgment", "Only correct spelling", "Completely replace the human author"], correctIndex: 1, explanation: "AI ideally generates 80% of the work (a quick first draft) that you then refine with your human judgment and authentic voice, reducing writing time by 70–80%." },
        { question: "For an SEO article, what should you specify in the prompt?", options: ["Only the keyword", "H1/H2 structure, keyword frequency, length, and target audience", "Only the word count", "Only the article title"], correctIndex: 1, explanation: "An effective SEO prompt specifies: the tag structure (H1/H2), the natural keyword frequency, the target length, the tone, and the target audience for an optimized and readable article." },
        { question: "For landing page copywriting, which element is most important to specify?", options: ["The exact word count", "The customer persona and the main promise (benefit)", "The font", "The number of images"], correctIndex: 1, explanation: "The customer persona (who you are addressing) and the main promise (the key benefit) are the most important elements for landing page copy that converts." },
      ],
    },
    {
      number: 13,
      title: "Prompts for Image Generation",
      description: "Structure of visual prompts, negative prompts, and artistic styles for Midjourney and DALL-E.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "The visual language of image generators" },
        { type: "paragraph", content: "Prompts for image generation follow a different logic than text prompts. They describe what the image should contain, the composition, the visual style, the lighting, the color palette, and the technical quality. Mastering this syntax multiplies result quality by 5." },
        { type: "subheading", content: "Structure of an effective image prompt" },
        { type: "paragraph", content: "Recommended structure (for Midjourney and DALL-E): [Main subject] + [Action or state] + [Framing and composition] + [Lighting] + [Artistic style] + [Technical quality] + [Mood/atmosphere]. Example: 'Portrait of an elderly fisherman, weathered face, three-quarter view, dramatic side lighting, oil painting style, highly detailed, melancholic atmosphere'" },
        { type: "subheading", content: "Style modifiers" },
        { type: "paragraph", content: "Photographic styles: portrait lens, golden hour, long exposure, macro photography, aerial view. Artistic styles: oil painting, watercolor, concept art, manga, art nouveau, brutalist architecture, Studio Ghibli style. Quality: photorealistic, highly detailed, 8K, sharp focus, masterpiece. These terms are universally understood by Midjourney, DALL-E, and Stable Diffusion." },
        { type: "subheading", content: "Negative prompts — Removing what you don't want" },
        { type: "paragraph", content: "In Stable Diffusion and some Midjourney modes, negative prompts indicate what should not be generated. Common negatives: 'blurry, deformed hands, extra fingers, low quality, watermark, text, logo, bad anatomy, ugly, duplicate, mutated'. These negatives drastically reduce unwanted visual artifacts." },
        { type: "subheading", content: "Reproducing a specific artistic style" },
        { type: "paragraph", content: "To reproduce an artist's style: 'in the style of [ARTIST]' works for deceased artists (Van Gogh, Monet, Rembrandt). For living artists, it is ethically questionable and some generators refuse these requests. Alternative: describe the characteristics of the style rather than naming the artist." },
        { type: "tip", content: "Start with a simple prompt and enrich it progressively. Generate 4 variations, identify what works, add or modify elements, regenerate. Image prompting is an iterative process — rarely perfect on the first try." },
        { type: "summary", items: [
          "Image structure: Subject + Action + Framing + Lighting + Style + Quality + Atmosphere",
          "Style modifiers are universally understood by all generators",
          "Negative prompts eliminate unwanted visual artifacts",
          "To reproduce a style: describe characteristics rather than naming the artist",
          "Image prompting is iterative: progressively enrich your prompt",
        ]},
      ],
      quiz: [
        { question: "What is the recommended structure for an image prompt?", options: ["Just describe the subject in one word", "Subject + Action + Framing + Lighting + Style + Quality + Atmosphere", "A complete sentence in natural language", "Only technical parameters"], correctIndex: 1, explanation: "The recommended structure combines: the main subject, its action, the framing, the lighting, the artistic style, the technical quality, and the atmosphere/mood to precisely guide generation." },
        { question: "What are negative prompts used for in image generation?", options: ["To indicate what you want", "To eliminate unwanted elements (artifacts, deformations)", "To speed up generation", "To reduce resolution"], correctIndex: 1, explanation: "Negative prompts indicate what the image should not contain (deformed hands, text, watermarks, blur), drastically reducing unwanted visual artifacts." },
        { question: "Why is it discouraged to use living artists' styles in prompts?", options: ["Because it doesn't work", "For ethical reasons and because some generators refuse these requests", "Because it is more expensive", "Because the results are worse"], correctIndex: 1, explanation: "Using living artists' styles is ethically questionable (potential violation of their intellectual property) and some image generators explicitly refuse these requests." },
        { question: "What is the recommended approach for optimizing an image prompt?", options: ["Create a perfect prompt on the first try", "Iterative process: simple prompt → progressively enrich → iterate", "Copy existing prompts", "Use only technical parameters"], correctIndex: 1, explanation: "Image prompting is an iterative process: start simple, generate variations, identify what works, enrich the prompt, and regenerate. Rarely perfect on the first try." },
      ],
    },
    {
      number: 14,
      title: "Prompts for Video and Music",
      description: "Specific syntax for Sora, Runway, Suno, and Udio — the secrets of multimedia prompts.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Multimedia prompts: video and music" },
        { type: "paragraph", content: "Generating video and music with AI requires a different syntax and approach from text or image generation. These media have additional dimensions: movement for video, rhythm and harmony for music." },
        { type: "subheading", content: "Video prompts for Sora 2 and Runway" },
        { type: "paragraph", content: "Structure of an effective video prompt: [Shot type] + [Subject] + [Action] + [Environment] + [Camera movement] + [Cinematic style] + [Mood]. Example for Sora 2: 'Slow motion close-up of a drop of water falling into a still pond, creating perfect ripples, golden hour sunlight, cinematic depth of field, documentary style, peaceful atmosphere.'" },
        { type: "subheading", content: "Technical terms for video prompts" },
        { type: "paragraph", content: "Shot types: extreme close-up (ECU), close-up (CU), medium shot (MS), wide shot (WS), aerial shot, POV shot. Camera movements: tracking shot, dolly zoom, handheld, crane shot, timelapse, slow motion. Styles: cinematic, documentary, commercial, news, social media vertical. These terms precisely guide video composition." },
        { type: "subheading", content: "Music prompts for Suno and Udio" },
        { type: "paragraph", content: "Structure of a music prompt: [Genre] + [Subgenre] + [Tempo] + [Instruments] + [Vocals] + [Mood] + [Lyric theme]. Example for Suno: 'Upbeat indie pop song, acoustic guitar and synths, 128 BPM, female vocals with harmonies, summer festival vibe, about reconnecting with an old friend, catchy chorus.'" },
        { type: "subheading", content: "Controlling musical structure" },
        { type: "paragraph", content: "In Suno (Custom mode), you can structure the song with tags: [Verse 1], [Chorus], [Verse 2], [Bridge], [Outro]. You write the lyrics for each section. In Udio, similar controls let you define the intro, verses, and chorus separately for a precise narrative structure." },
        { type: "tip", content: "For video: always describe movement explicitly. 'A bird flies' is less effective than 'A bird takes off in slow motion, wings spreading frame by frame, camera tracking upward as the bird ascends into a cloudy sky'. The detail of movement is what separates a poor video prompt from an excellent one." },
        { type: "summary", items: [
          "Video prompts: Shot + Subject + Action + Environment + Camera Movement + Style",
          "Cinematic terms (close-up, tracking shot, slow motion) guide composition",
          "Music prompts: Genre + Tempo + Instruments + Vocals + Mood + Theme",
          "Suno (Custom mode) allows structuring songs section by section",
          "Describing movement explicitly is the key to a great video prompt",
        ]},
      ],
      quiz: [
        { question: "What element is most important in a video prompt?", options: ["The video duration", "The explicit description of movement", "The name of a reference director", "The desired resolution"], correctIndex: 1, explanation: "The explicit description of movement (camera movement, subject action, timing) is the most important element in a video prompt because it defines the very essence of the video." },
        { question: "What tag is used in Suno (Custom mode) to indicate the chorus?", options: ["[Refrain]", "[Chorus]", "[Refrain:]", "[HOOK]"], correctIndex: 1, explanation: "In Suno's Custom mode, the [Chorus] tag is used to indicate the chorus. Suno uses English terms for musical structure tags." },
        { question: "For an aerial video shot, what technical term should you use?", options: ["Bird view", "Top shot", "Aerial shot", "Sky angle"], correctIndex: 2, explanation: "'Aerial shot' is the standard cinematographic term for a shot taken from the air (drone, helicopter). This is the term understood by Sora 2 and Runway Gen-3." },
        { question: "What is the structure of an effective music prompt for Suno?", options: ["Only the musical genre", "Genre + Tempo + Instruments + Vocals + Mood + Lyric theme", "Just the song title", "A poetic description of the atmosphere"], correctIndex: 1, explanation: "An effective music prompt combines: the genre and subgenre, the tempo (BPM), the instruments, the vocal type, the mood, and the lyric theme to precisely guide generation." },
      ],
    },
    {
      number: 15,
      title: "Reducing Hallucinations — Anti-Error Techniques",
      description: "Techniques for obtaining reliable responses and avoiding incorrect information.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "AI hallucinations: a real and manageable problem" },
        { type: "paragraph", content: "An AI hallucination is information generated by the model that seems convincing but is false. In 2026, GPT-5.4 has reduced its hallucinations by 33% compared to GPT-5.2, but the problem has not disappeared. Prompting techniques can significantly reduce this risk." },
        { type: "subheading", content: "Technique 1: Ask for sources and justification" },
        { type: "paragraph", content: "Add to your prompt: 'For each factual statement, cite your source. If you are not certain of a piece of information, indicate your confidence level (certain / probable / uncertain).' The AI is less likely to fabricate information when asked to source it and indicate its level of certainty." },
        { type: "subheading", content: "Technique 2: Grounding (factual anchoring)" },
        { type: "paragraph", content: "Instead of asking the AI to generate facts, provide the facts yourself and ask it to analyze them. Example: 'Here is our company's sales data for 2025: [DATA]. Analyze this data and identify trends.' The AI analyzes your real data rather than inventing it." },
        { type: "subheading", content: "Technique 3: Verification decomposition" },
        { type: "paragraph", content: "Ask the AI to verify its own claims: 'In your response, identify all the factual claims you made. For each one, indicate whether you are certain, probable, or uncertain. Propose alternatives or nuances for uncertain claims.' This self-checking technique reduces confident errors." },
        { type: "subheading", content: "Technique 4: Use Perplexity for recent facts" },
        { type: "paragraph", content: "For recent information (dates, figures, events), don't rely on ChatGPT or Claude alone — their knowledge has a cutoff date. Use Perplexity, which accesses the web in real time. For critical factual information, always verify against a primary source." },
        { type: "key-point", content: "Golden rule against hallucinations: the more specific a piece of information is (a statistic, a date, a name, a price), the more you need to verify it. LLMs are excellent at analyzing, synthesizing, and reasoning, but unreliable at citing precise figures without a source." },
        { type: "summary", items: [
          "Asking for sources and confidence levels reduces confident hallucinations",
          "Grounding: provide the facts and ask for analysis rather than generation",
          "Verification decomposition: ask the AI to check its own claims",
          "For recent facts: use Perplexity + verify against primary sources",
          "Precise figures, dates, and names must always be verified",
        ]},
      ],
      quiz: [
        { question: "What is a hallucination in the context of LLMs?", options: ["A response that is too long", "Information that seems true but is false", "An incorrect image generated by AI", "A prompt the AI doesn't understand"], correctIndex: 1, explanation: "An AI hallucination is information generated by the model that seems convincing and is presented with confidence, but is factually incorrect." },
        { question: "What is the 'grounding' technique for reducing hallucinations?", options: ["Connecting the AI to the internet", "Providing real facts and asking for analysis rather than generation", "Grounding the AI electrically", "Limiting response length"], correctIndex: 1, explanation: "Grounding consists of providing real factual data in your prompt and asking the AI to analyze it, thereby preventing the AI from generating (and potentially inventing) facts." },
        { question: "For what type of information should you systematically verify AI responses?", options: ["Conceptual explanations", "Text summaries", "Precise figures, dates, and names", "Definitions of common terms"], correctIndex: 2, explanation: "Precise figures, dates, and proper names are the information most prone to hallucinations. Always verify this information against primary sources." },
        { question: "Which tool is recommended for recent information instead of ChatGPT/Claude?", options: ["Google Translate", "Wikipedia", "Perplexity AI", "Wolfram Alpha"], correctIndex: 2, explanation: "Perplexity AI is recommended for recent information because it accesses the web in real time and cites its sources, unlike ChatGPT and Claude which have a knowledge cutoff date." },
      ],
    },
    {
      number: 16,
      title: "Prompts for AI Agents",
      description: "Autonomous instructions, tools, JSON format, and error handling for AI agents.",
      estimatedMinutes: 9,
      sections: [
        { type: "heading", content: "AI agents: a new level of prompting" },
        { type: "paragraph", content: "AI agents are systems that plan, decide, and act autonomously to achieve an objective. Prompts for agents are different from standard prompts: they define objectives rather than tasks, specify available tools, and include behavioral rules for unforeseen situations." },
        { type: "subheading", content: "Structure of an agent prompt" },
        { type: "paragraph", content: "An agent system prompt contains: 1. The overall objective (not the immediate task). 2. Available tools and when to use them. 3. The communication format (often JSON). 4. Decision rules (when to stop, when to ask for confirmation). 5. Error handling instructions. 6. Limits and constraints." },
        { type: "subheading", content: "The ReAct format for agents" },
        { type: "paragraph", content: "The ReAct paradigm (Reasoning + Acting) structures agents: Thought (I think about what I need to do), Action (I use tool X with parameters Y), Observation (the result is Z), Thought (now I need to...). This cycle repeats until the objective is reached. Structuring your prompt around this paradigm considerably improves agent performance." },
        { type: "subheading", content: "JSON format for structured communication" },
        { type: "paragraph", content: "Agents often communicate in JSON for responses parsable by applications. Example of requested format: 'Always respond in JSON with the structure: {action: string, parameters: object, reasoning: string, next_step: string}'. This format allows applications to process the agent's decisions reliably." },
        { type: "subheading", content: "Error handling and escalation" },
        { type: "paragraph", content: "A good agent prompt includes escalation rules: 'If you encounter an error, try 2 times with a different approach before reporting failure. If a decision involves critical data (deletion, payment), always ask for confirmation before acting. Never exceed a budget of [X] API requests.'" },
        { type: "tip", content: "For agents in production, always add an explicit safety instruction: 'When in doubt about the impact of an action, always choose the most conservative option and report the uncertainty rather than acting.' Autonomous agents can cause irreversible damage if misconfigured." },
        { type: "summary", items: [
          "Agent prompts define global objectives and behavioral rules",
          "The ReAct paradigm (Thought → Action → Observation) structures decisions",
          "JSON format allows responses parsable by applications",
          "Escalation rules define when to stop and ask for confirmation",
          "Always add a safety instruction to avoid irreversible actions",
        ]},
      ],
      quiz: [
        { question: "What is the main difference between a standard prompt and an agent prompt?", options: ["The agent prompt is shorter", "The agent prompt defines objectives and behavioral rules, not just a task", "The agent prompt is in English only", "The agent prompt contains no text"], correctIndex: 1, explanation: "An agent prompt defines global objectives, available tools, decision rules, and error handling — well beyond a simple one-off task instruction." },
        { question: "What does ReAct stand for in the context of AI agents?", options: ["Reactive Actions", "Reasoning + Acting", "Real-time Actor", "Recursive Automation Technology"], correctIndex: 1, explanation: "ReAct stands for Reasoning + Acting: the agent alternates between reasoning phases (Thought), action phases (Action), and observation phases (Observation) in a repeating cycle." },
        { question: "Why use JSON format for AI agent responses?", options: ["To save tokens", "To make decisions parsable and processable by applications", "Because the AI understands JSON better", "To improve generation speed"], correctIndex: 1, explanation: "JSON format allows applications to process the agent's decisions reliably and automatically, accessing specific fields (action, parameters, reasoning) without interpreting free text." },
        { question: "What safety instruction is essential in a production agent prompt?", options: ["Never stop before the task is complete", "When in doubt, choose the conservative option and report", "Always act without asking for confirmation", "Execute all actions simultaneously"], correctIndex: 1, explanation: "When in doubt, choosing the most conservative option and reporting the uncertainty is the essential safety instruction to prevent the agent from performing unwanted irreversible actions." },
      ],
    },
    {
      number: 17,
      title: "Case Study 1 — Marketing: +150% ROI",
      description: "How a marketing agency transformed its content production with prompt engineering.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Real case: digital marketing agency — Paris, 2025" },
        { type: "paragraph", content: "The agency ContentPro (12 employees, SMB clients) was facing growing pressure: produce more content, faster, without increasing headcount. In January 2025, they decided to integrate prompt engineering into all their content creation processes." },
        { type: "subheading", content: "The initial problem" },
        { type: "paragraph", content: "The situation before: each blog article took 4 to 6 hours (research + writing + revision). Each email campaign required 3 hours of writing. Social media posts (30/month per client) took 2 days. The average delivery time was 10 business days. Revenue was capped due to limited capacity." },
        { type: "subheading", content: "Setting up prompt templates" },
        { type: "paragraph", content: "ContentPro created a library of 47 prompt templates covering: blog articles (8 templates by format), marketing emails (6 templates), social media posts (12 templates per platform), product sheets (5 templates by industry), and press releases (3 templates). Each template incorporated CRISPE and CoT best practices." },
        { type: "subheading", content: "Results after 6 months" },
        { type: "paragraph", content: "Blog article: 4–6h → 45 minutes (–85%). Marketing email: 3h → 25 minutes (–86%). Social media posts: 2 days → 3 hours (–90%). Delivery time: 10 days → 2 days (–80%). Production capacity: +320%. New clients taken on thanks to freed-up capacity: +6 clients/month. ROI of the prompt engineering program: +150% in revenue in 6 months." },
        { type: "subheading", content: "The key prompts that changed everything" },
        { type: "paragraph", content: "ContentPro's highest-impact prompt: 'You are a B2B content marketing expert with 15 years of experience. Write a 1,200-word blog article on [TOPIC] for [CLIENT] whose audience is [TARGET]. Tone: [STYLE]. SEO: optimized for [KEYWORD]. Structure: compelling H1, 4 H2 sections with concrete examples, conclusion with CTA. Data: use only the following data: [CLIENT DATA]. Format: ready-to-publish text with no comments or explanations.'" },
        { type: "key-point", content: "The main lesson: the time invested in creating quality prompt templates pays off within weeks. ContentPro spent 40 hours over 3 weeks creating its 47 templates — an investment recouped in less than 2 months." },
        { type: "summary", items: [
          "ContentPro reduced content production time by 80 to 90% in 6 months",
          "47 prompt templates created over 3 weeks — investment recouped in 2 months",
          "Production capacity increased by 320% without new hires",
          "ROI of the prompt engineering program: +150% in revenue in 6 months",
          "The key: complete CRISPE templates with precise persona, context, and format",
        ]},
      ],
      quiz: [
        { question: "How much time did an agency like ContentPro save on article writing?", options: ["10%", "30%", "85%", "99%"], correctIndex: 2, explanation: "ContentPro reduced blog article writing time from 4–6 hours to 45 minutes, saving 85% of the time through optimized prompt templates." },
        { question: "What ROI did the agency achieve through prompt engineering in 6 months?", options: ["+20% revenue", "+50% revenue", "+150% revenue", "+500% revenue"], correctIndex: 2, explanation: "Thanks to freed-up production capacity (x3.2), ContentPro was able to take on 6 additional new clients per month, generating a revenue increase of +150% in 6 months." },
        { question: "How many prompt templates did ContentPro create?", options: ["12 templates", "47 templates", "150 templates", "500 templates"], correctIndex: 1, explanation: "ContentPro created a library of 47 prompt templates covering all content types: articles, emails, social media posts, product sheets, and press releases." },
        { question: "How quickly was the investment in prompt templates recouped?", options: ["In 1 week", "In less than 2 months", "In 6 months", "In 1 year"], correctIndex: 1, explanation: "The 40-hour investment over 3 weeks to create the 47 templates was recouped in less than 2 months thanks to the time saved on each piece of content produced." },
      ],
    },
    {
      number: 18,
      title: "Case Study 2 — Development: 10x Faster",
      description: "How a tech startup multiplied its development speed by 10 with prompting.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Real case: SaaS startup — Lyon, 2025" },
        { type: "paragraph", content: "DevFlow, a SaaS startup with 8 developers, needed to deliver a major update in 3 months with the same team. Rather than hiring (too slow and costly), they decided to master code prompt engineering and integrate Cursor into their workflow." },
        { type: "subheading", content: "Integrating Cursor and structured prompting" },
        { type: "paragraph", content: "Phase 1 (weeks 1–2): training the entire team on code prompting best practices. Creation of a .cursorrules file defining team conventions (strict TypeScript, mandatory tests, JSDoc documentation). Phase 2 (weeks 3–4): creation of prompt templates for repetitive tasks (database migrations, unit tests, REST API endpoints)." },
        { type: "subheading", content: "The prompts that transformed productivity" },
        { type: "paragraph", content: "API endpoint prompt: 'You are a senior Node.js/TypeScript developer following project conventions (see .cursorrules). Create a REST endpoint [METHOD] /api/[ROUTE] that [DESCRIPTION]. Constraints: Zod validation, complete error handling (400/401/403/404/500), structured logs, Jest tests with mocks. Return only the code, no explanations.' This single prompt reduced endpoint creation time from 3 hours to 20 minutes." },
        { type: "subheading", content: "Results after 3 months" },
        { type: "paragraph", content: "New feature development speed: 7x faster. Debugging: 10x faster (Cursor Agent identifies and fixes bugs autonomously). Unit tests: went from 23% to 87% coverage (–75% time to write tests). Code review time: –60% (generated code is more consistent and follows conventions). The major update was delivered in 2.5 months instead of 3." },
        { type: "subheading", content: "The lesson on limitations" },
        { type: "paragraph", content: "DevFlow also learned from experience that AI-generated code always requires human review. Two subtle bugs almost made it to production: one involving database transaction management, another involving race conditions in a multi-threaded environment. The AI had generated code that appeared correct but was wrong in specific edge cases." },
        { type: "summary", items: [
          "DevFlow multiplied its development speed by 7 to 10 depending on the task",
          "The .cursorrules file automatically enforces team conventions on the AI",
          "Precise prompt templates reduce endpoint creation from 3 hours to 20 minutes",
          "Test coverage went from 23% to 87% while saving time",
          "Human review remains essential — AI makes subtle errors on edge cases",
        ]},
      ],
      quiz: [
        { question: "By how much did DevFlow accelerate new feature development?", options: ["2 times faster", "4 times faster", "7 times faster", "50 times faster"], correctIndex: 2, explanation: "DevFlow achieved a new feature development speed 7 times faster than before integrating prompt engineering and Cursor into their workflow." },
        { question: "What is the .cursorrules file used for in a project?", options: ["To block certain Cursor features", "To define team conventions that the AI automatically follows", "To configure keyboard shortcuts", "To manage Cursor licenses"], correctIndex: 1, explanation: "The .cursorrules file defines team conventions (code style, frameworks used, naming rules) that Cursor automatically applies to all generated code." },
        { question: "What lesson did DevFlow learn about the limits of AI for code?", options: ["AI cannot generate TypeScript", "Generated code always requires human review for edge cases", "AI is perfect and never makes mistakes", "You should never use AI for tests"], correctIndex: 1, explanation: "DevFlow learned that AI-generated code can look correct but contain subtle bugs in specific edge cases (DB transactions, race conditions) — human review remains essential." },
        { question: "How long does it take to create a REST endpoint with DevFlow's optimized prompt template?", options: ["3 hours", "1 hour", "20 minutes", "5 minutes"], correctIndex: 2, explanation: "With the optimized prompt template, creating a REST endpoint (with Zod validation, error handling, logs, and tests) went from 3 hours to 20 minutes, a reduction of 89%." },
      ],
    },
    {
      number: 19,
      title: "Case Study 3 — Customer Support: 70% Automation",
      description: "How a scale-up automated 70% of its customer support with AI prompts.",
      estimatedMinutes: 8,
      sections: [
        { type: "heading", content: "Real case: e-commerce scale-up — Bordeaux, 2025" },
        { type: "paragraph", content: "ShopFast, an e-commerce scale-up with 150 employees, was receiving 2,500 support tickets per week. Their team of 12 agents was struggling to manage the load. Rather than doubling the team, they implemented an AI-powered support management system based on carefully engineered prompts." },
        { type: "subheading", content: "Architecture of the AI support system" },
        { type: "paragraph", content: "Level 1: Automatic ticket classification (problem type, urgency, VIP or standard customer). Level 2: Automatic response generation for the 15 most frequent question types (order status, returns, refunds, delivery problems). Level 3: Smart escalation to a human agent for complex cases or dissatisfied customers." },
        { type: "subheading", content: "The central classification prompt" },
        { type: "paragraph", content: "Classification prompt: 'You are a customer support expert for e-commerce. Analyze this ticket: [TICKET]. Classify it in JSON: {category: [delivery/return/payment/product/account/other], urgency: [critical/high/medium/low], vip_customer: [true/false], sentiment: [positive/neutral/negative/angry], suggested_action: [auto_reply/human_escalation], reason: string}. Do not generate a response — classify only.' The precision of this prompt is critical to the quality of the system." },
        { type: "subheading", content: "Results after 4 months" },
        { type: "paragraph", content: "Tickets handled automatically: 70% (1,750/week). Average response time: 4 hours → 8 minutes (–97%). Customer satisfaction (CSAT): 3.8/5 → 4.4/5 (+16%). Tickets escalated to humans: 750/week (vs. 2,500 before). Cost per resolved ticket: –58%. The human team now focuses on the 30% of complex, high-value cases." },
        { type: "subheading", content: "The automated response prompts" },
        { type: "paragraph", content: "Each category has its specialized response prompt. Example for a return: 'You are Alex, the ShopFast assistant. Write a warm and professional response for this customer requesting a return: [TICKET]. Customer data: [NAME, ORDER, HISTORY]. The response must: 1. Empathize with the situation. 2. Confirm the refund within 5 days. 3. Provide the return label (see link). 4. Offer a 10% discount for the next purchase. Maximum 120 words.'" },
        { type: "summary", items: [
          "ShopFast automated 70% of its 2,500 weekly support tickets",
          "Response time went from 4 hours to 8 minutes (–97%)",
          "Customer satisfaction increased from 3.8 to 4.4/5 despite automation",
          "Cost per resolved ticket decreased by 58%",
          "The human team focuses on the 30% of complex, high-value cases",
        ]},
      ],
      quiz: [
        { question: "What percentage of ShopFast's tickets are handled automatically by AI?", options: ["30%", "50%", "70%", "95%"], correctIndex: 2, explanation: "After 4 months of optimization, ShopFast's AI system automatically handles 70% of tickets (1,750 out of 2,500 per week), leaving complex cases to human agents." },
        { question: "What was the impact on average response time?", options: ["4 hours → 2 hours", "4 hours → 30 minutes", "4 hours → 8 minutes", "No change"], correctIndex: 2, explanation: "The average response time went from 4 hours to 8 minutes (–97%) thanks to automatic responses generated instantly by the AI system." },
        { question: "What is the output format of the ticket classification prompt?", options: ["Free text", "XML", "Structured JSON", "Markdown"], correctIndex: 2, explanation: "The classification prompt uses a structured JSON format (category, urgency, sentiment, suggested_action) to allow the system to automatically process the routing decision." },
        { question: "Why did customer satisfaction increase despite automation?", options: ["AI is more friendly than humans", "The ultra-fast response time compensates for the lack of human interaction", "Customers prefer talking to robots", "AI makes fewer mistakes than humans"], correctIndex: 1, explanation: "Customer satisfaction increased because the ultra-fast response time (8 minutes) and 24/7 availability more than compensate for the automated nature, and complex cases are still handled by humans." },
      ],
    },
    {
      number: 20,
      title: "Building Your Prompt Library",
      description: "Organization, versioning, sharing, and templates — creating your prompt engineering asset.",
      estimatedMinutes: 7,
      sections: [
        { type: "heading", content: "Your prompt library: a strategic asset" },
        { type: "paragraph", content: "A well-organized prompt library is one of the most valuable assets you can build. Unlike knowledge in your head, a library is shareable, versionable, and improves over time. The best teams treat their prompts like source code." },
        { type: "subheading", content: "Recommended structure for a prompt library" },
        { type: "paragraph", content: "Organization by category and use: /prompts/writing (articles, emails, copywriting, social media), /prompts/analysis (data, documents, sentiment, competitors), /prompts/code (generation, debugging, refactoring, tests), /prompts/images (portraits, landscapes, products, advertising), /prompts/agents (classification, routing, planning). Each prompt in its own file with metadata." },
        { type: "subheading", content: "Standardized format for each prompt" },
        { type: "paragraph", content: "Recommended structure for each prompt file: Name + Description + Version + Creation date + Author + Model tested on + Quality score (1–10) + Required variables + Input example + Output example + Optimization notes. This documentation allows others to understand and use the prompt without explanation." },
        { type: "subheading", content: "Versioning and continuous improvement" },
        { type: "paragraph", content: "Treat your prompts like code: version them with numbers (v1.0, v1.1, v2.0), note changes between versions, and keep old versions. A v2.0 prompt may regress on certain cases — having v1.0 available allows you to roll back. Git is an excellent tool for versioning your prompts." },
        { type: "subheading", content: "Sharing and collaboration" },
        { type: "paragraph", content: "For teams, share your library via Notion, Confluence, or a Git repo. Establish a contribution process: each new prompt is tested on 10 real cases before being added to the library. Organize monthly 'prompt review' sessions to improve existing prompts." },
        { type: "tip", content: "Start small: create 5 perfectly documented prompts rather than 50 approximate ones. The quality of your library matters more than its size. Every prompt should have been tested and validated on real cases before being archived." },
        { type: "summary", items: [
          "A prompt library is a shareable and versionable strategic asset",
          "Organize by category: writing, analysis, code, images, agents",
          "Each prompt must have: description, version, variables, examples, and notes",
          "Version with Git — treat your prompts like source code",
          "Test on 10 real cases before adding a prompt to the library",
        ]},
      ],
      quiz: [
        { question: "How do the best teams treat their prompts?", options: ["As personal notes", "As source code (versioning, documentation, sharing)", "As confidential secrets", "As disposable documents"], correctIndex: 1, explanation: "The best teams treat their prompts like source code: they are versioned, documented, shared among team members, and continuously improved." },
        { question: "Which tool is recommended for versioning a prompt library?", options: ["Excel", "Email", "Git", "Post-its"], correctIndex: 2, explanation: "Git is ideal for versioning prompts because it allows you to track changes, roll back to previous versions, and collaborate easily as a team." },
        { question: "How many real cases should you test before adding a prompt to the library?", options: ["Just 1 test is enough", "3 tests", "10 real cases minimum", "100 tests"], correctIndex: 2, explanation: "Testing on at least 10 real cases before archiving a prompt guarantees its robustness and reliability in varied situations, avoiding archiving prompts that only work in a single context." },
        { question: "Why keep old versions of a prompt?", options: ["For legal reasons", "To roll back if a new version regresses on certain cases", "To show the evolution to clients", "Out of nostalgia"], correctIndex: 1, explanation: "Keeping old versions allows you to roll back if a v2.0 prompt regresses on certain cases compared to v1.0 — a common practice in software development that applies equally to prompts." },
      ],
    },
  ],
};

export default content;
